### ISSUE TITLE
Toolbar not floating for long inline WYSYWYG fields

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1018]
The editor toolbar is not accessible when your content is higher than the vertical viewport:

https://www.loom.com/share/984064ffddad4bb0a0ba323181033e9c

**Comment by spbyrne** [comment]
This was previously addressed but got lost in the shuffle. I'm working on a fix now.

**Comment by spbyrne** [comment]
This was tested and working at the time of the last fix, but unfortunately it appears to have resurfaced. Something different may be causing the problem this time, though. I'm going to troubleshoot.
