### ISSUE TITLE
useGithubMarkdownForm's SourceProvider type does not match SourceProvider from getGithubPreviewProps

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#1027]
`useGithubMarkdownForm`'s [GithubOptions](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-github/src/form/GithubOptions.ts) type does not match [SourceProviderConnection](https://github.com/tinacms/tinacms/blob/master/packages/next-tinacms-github/src/github/content/sourceProviderConnection.ts) from `getGithubPreviewProps`.

`next-tinacms-github` should import the `SourceProviderConnection` type from `react-tinacms-github` so that they can be consistent.

Also.. SourceProviderConnection isn't the best name

**Comment by ncphillips** [comment]
Yeah, it's definitely not a SourceProvider. Seems like it's really a Repository:

```ts
export interface Repository {
  fullName: string
  branch: string  // or maybe `baseBranch`
}
```

**Comment by jamespohalloran** [comment]
Yeah. As is, it kind of tracks your full editing repository state:
https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-github/src/form/GithubOptions.ts

Maybe once we add branching, it can be:
```
export interface Repository {
  fullName: string
  baseFullName: string
  branch: string
  baseBranch: string
}
```

**Comment by ncphillips** [comment]
I did some refactoring in [this branch](https://github.com/tinacms/tinacms/pull/1030/files) and wound up removing the SourceProvider connection entirely and the properties just exist on the GithubClient
