### ISSUE TITLE
Global Forms Label

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#1029]
## Description

With global forms, the ‘name’ property is used as the label in the global menu instead of 'label' as expected. 

### Steps to reproduce

Define a global form with a label but no name. No text will be rendered in the global forms list in the sidebar.

<img width="444" alt="Screen Shot 2020-04-20 at 11 36 46 AM" src="https://user-images.githubusercontent.com/5075484/79764042-383ac800-82fb-11ea-8b4f-f3e04004521c.png">

### Expected result

I'd expect the 'label' property gets used to label the form.

### Actual result

The label property is not used.

**Comment by ncphillips** [comment]
Is this still the case? It looks like [GlobalFormPlugin sets `name` to the form label](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/plugins/screens/index.tsx#L37)

**Comment by kendallstrautman** [comment]
Closing this — just tested in `demo-gatsby` and it's working as exptected. iow if you pass a label, the label is rendered in the global form list, if you don't pass a label, the name is rendered.
