### ISSUE TITLE
Select field label and value

### ISSUE THREAD

**Issue by DaniTulp** [tinacms/tinacms#1044]
## Summary

Say I'm using a SelectField for creating a form and I want to be able to have a different label from the value of the option, right now I can't do that with the default component.

### Basic example
The api I would propose would look like this
```     
{
    name: 'gridCols',
    label: 'Grid columns',
    component: 'select',
    options: [
       {value:  'grid-cols-3', label: '3' }
    ]
},
```
We could probably also keep the old API if you just pass in an array of Strings

### Motivation

I think the use case described above explains it well enough. I also think it would keep it inline with the other elements within forms, most of them have a way to modify the way something is displayed for the end-user.

**Comment by ncphillips** [comment]
Absolutely! The type for option should be :

```
type Option = string | {
  value: string
  label: string
}
```
