### ISSUE TITLE
Gatsby -- JSON Form only accepts one node

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#106]
### Issue: The JSON form currently assumes that you only pass it one node at a time. 

However, if someone has their json modeled as an array of objects, gatsby creates multiple nodes for each object in the array. So we have one json file, but containing multiple nodes (of json objects). 

If you map over each node and add an individual form to them, this result in separate individual files to edit for each object. If you only pass the form one node, the other nodes (other json objects with relevant data) will be deleted in the source file. 

### **To replicate**
Check out the [toc.json](https://github.com/tinacms/tinacms-site/blob/master/docs/toc.json) data file in the tinacms-site repo. This is an example of the content structure references above. 

The query for this json data occurs in [layouts/index.ts](https://github.com/tinacms/tinacms-site/blob/master/src/layouts/index.tsx). You will see that the query says allTocJson , as opposed to just tocJson, which would just return the first node or obj from the data.

The json data (an array of objs) gets passed down to [Navigations.tsx](https://github.com/tinacms/tinacms-site/blob/master/src/components/layout/Navigation/Navigation.tsx) where it is mapped over....

```
<DocumentationNav onClick={() => dispatch({ type: NavigationActionTypes.TOGGLE_DRAWER })}>
          {navigation &&
          navigation.map(({ node }) => {
            return(
            <NavigationMenu key={node.title} menuKey={node.title} node={node} />)
          })}
</DocumentationNav>
```

If you try to use the `useJsonForm` hook here, you will get a `fields is undefined` error. 

I made a [branch](https://github.com/tinacms/tinacms-site/tree/json-issue) to set up a test case.

**Comment by ncphillips** [comment]
Leaving this issue open, but incase anyone comes looking, @kendallstrautman [documented](https://tinacms.org/docs/gatsby/json/) some of the caveats around working with JSON files and Gatsby.

**Comment by kendallstrautman** [comment]
Closing since this is stale and there is documentation for the workaround.
