### ISSUE TITLE
Clicking the Table's Column selects the Menu items

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#1061]
## Description

Describe the issue that you're seeing.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/824015/80385462-75173980-887c-11ea-8a9e-4c187b7880eb.png">

### Steps to reproduce

Click the first column in a table

**Comment by DirtyF** [comment]
@ncphillips It looks fixed on current master: https://www.loom.com/share/11be127369414e6b93157c20b059d20e
