### ISSUE TITLE
Cursor not visible in first column of wysiwyg tables

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#1062]
## Description

The cursor is there but I can't see it. If I start typing it shows up.

<img width="419" alt="image" src="https://user-images.githubusercontent.com/824015/80385889-09819c00-887d-11ea-9e19-3afea60c9552.png">

### Steps to reproduce

1. Create a table
2. Click into first column

**Comment by DirtyF** [comment]
This one looks fixed on master:
https://www.loom.com/share/e7a3a413b8ed4d0d9056f8ba6cbe9888
