### ISSUE TITLE
Several clicks required for Table floating menu items to trigger

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#1063]
## Description

Must click multiple times to add/remove columns

### Steps to reproduce
1. Create a table
1. Click on the Add Column button; nothing happens
1. Click the Add Column button multiple times in a row; column is added

**Comment by jpuri** [comment]
Hey @ncphillips : are you facing this in latest code from master ?

I created this few days ago: https://github.com/tinacms/tinacms/issues/1017
