### ISSUE TITLE
react-tinacms-github: Pull Request button is still visible when on the base branch

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#1069]
<img width="581" alt="Screen Shot 2020-04-28 at 2 54 54 PM" src="https://user-images.githubusercontent.com/3323181/80520824-5ee2a980-8960-11ea-8589-ffc8c157ba56.png">
It appears as if I can create a pull request from the base_repo master > master.

When you click "Create Pull Request", it fails

### Expected result

Should the pull request button be hidden when you are on the base_repo base_branch?

**Comment by ncphillips** [comment]
I'll make it say something like:

> You're currently on the base. Switch to a new branch to create a pull request.
