### ISSUE TITLE
Toolbar Actions Cut Off On Mobile

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#1070]
## Description

The toolbar is no longer functional on mobile. The save button gets cut off.

<img width="508" alt="Screen Shot 2020-04-28 at 3 04 36 PM" src="https://user-images.githubusercontent.com/5075484/80521554-956cf400-8961-11ea-90c7-017753d20030.png">

### Steps to reproduce

View the TinaCNS.org website on mobile and enter edit mode.

### Expected result

You could be able to perform all essential actions on mobile.

### Actual result

Some actions are cut off as the GitHub widgets don't collapse.

**Comment by kendallstrautman** [comment]
@spbyrne we have mobile styles for these actions now right?
