### ISSUE TITLE
409 error when saving master while working on origin

### ISSUE THREAD

**Issue by jhuggett** [tinacms/tinacms#1078]
## Description

When saving on master on tinacms.org while working on origin it doesn't visually fail but logs a 409 (conflict) in the console.

### Steps to reproduce

- Enter edit mode (working on origin)
- Make changes on master
- Save

### Expected result

Require me to switch branches.

### Actual result

Looks like it saved properly but there's a 409 error in the console.

### Environment

prod

**Comment by kendallstrautman** [comment]
@jhuggett did this issue happen again on your second round of setup?

**Comment by jhuggett** [comment]
@kendallstrautman This is an issue on tinacms.org, I should have mentioned it in the issue sorry, will update it

**Comment by kendallstrautman** [comment]
I see, I wonder if its cause master is locked
