### ISSUE TITLE
[Feature Request] Debounce changes / Preview button

### ISSUE THREAD

**Issue by cleitonper** [tinacms/tinacms#1089]
## Summary

The live preview is the best feature of the Tina, but sometimes this feature is very slow, especially when editing text. Things like drag and drop _blocks_ or _list items_ are fine, only text editing is slow.

An option in the settings to control the time do updates would be a nice feature. The interface only updates after a period of time after the editor has stopped typing, using a technique known as **debounce**.

Another way to get around the slowness problem would be to add a **preview button**. With an option added in the settings, the live preview will be disabled, and the interface will only update after the user click on the preview button.

### Basic example

```javascript
// gatsby-config.js
module.exports = {
// ... other options omited
  plugins: [
    {
      resolve: 'gatsby-plugin-tinacms',
      options: {
        // use 'auto' for live preview
        // use ['debounce', 500] for debouncing the live preview after 500ms
        livePreview: 'manual' // for enable preview button
        plugins: [
          'gatsby-tinacms-git',
          'gatsby-tinacms-remark',
        ],
      },
    },
  ]
}
```

### Motivation

I'm using the Tina CMS with the Gatsby, and for me the live preview is not working because of the performance problems. The suggestions above will solve these problems and improve the usability of the cms.

### Aditional information

|Reproduction video|
|:------:|
|![screen-capture](https://user-images.githubusercontent.com/13934790/80893645-ac398080-8caa-11ea-97b1-b93503e8aa99.gif)|
|  As can be seen in the video, I start to insert content in the editor, but the form freezes right at the beginning, as does the ui.  |
| It is not `CTRL` `+` `C` _and_ `CTRL` `+` `V`, **I am typing without pauses**.   |

**Comment by DirtyF** [comment]
Hey, did you try so set `TINA_GIT_DEBOUNCE_MS` option? https://tinacms.org/docs/gatsby/configure-git-plugin#configuring-the-file-writing-debounce

**Comment by cleitonper** [comment]
Hi @DirtyF, I didn't know this option. Thanks for your suggestion.

But, even using `TINA_GIT_DEBOUNCE_MS=3000 gatsby develop` I still have the same problem: the form freezes as soon as I start editing.

Looking at the terminal, the number of file changes per second has decreased after using `TINA_GIT_DEBOUNCE_MS=3000 gatsby develop`, but the performance problems persist. Another thing I noticed is that several changes continue to be made even after and have stopped typing.

**Comment by ncphillips** [comment]
Hey @cleitonper this is a good idea. Thanks for the suggestion! I have an idea for how something like this could be made possible. I have some downtime in the next couple weeks so I may have time to check it out. 

@kendallstrautman this definitely relates to [Reasonable Defaults](https://github.com/tinacms/rfcs/blob/4d257bbc54f692cd148d8b59e6c2c2a89efe05c0/0007-higher-order-form-hooks.md#reasonable-defaults) section of tinacms/rfcs#8. My thought generally being that the user should be able to override the default behaviour of onChange and onSubmit so that the first does nothing and the second writes to disk. Then a secondary "Commit" action could be added. 

@all-contributors please add @cleitonper for ideas

**Comment by ncphillips** [comment]
Update: We're making some headway on this with some refactoring happening in #1157

**Comment by cleitonper** [comment]
Hi @ncphillips, thanks for your help!

I noticed the PR #1157 has been merged, and I have some questions about that.

1. A new version of Tina is already published with this changes?
2. How can I control the `change` behavior of the TinaCMS with these changes?
3. Is possible to disable the live preview, and only preview changes when I click in a **preview button** in the sidebar, as mentioned in this issue?


If possible, can you post a example of code?

**Comment by ncphillips** [comment]
Sorry I misrepresented that a bit. That PR was just a refactoring I.e. no api or behaviour change. Well have to change a couple more things to get what you’re looking for. I am hoping to get to that this week 🤞
