### ISSUE TITLE
Open Authoring with [...slug] (catch all routes)

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#1106]
## Description

I am trying to add open authoring a repo and they have used [dynamic routing](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes). I followed the [guide on tinaCMS](https://tinacms.org/guides/nextjs/github-open-authoring/initial-setup) and everything worked on the main page but it does not work when I try it on the docs/[...slug] pages. When I click edit this page it just redirects back but does not bring out the edit panel as it does when I click it on the index page.

### Steps to reproduce

* clone repo [here](https://github.com/logan-anderson/TinaBejamasStarter/tree/feature/open-authoring)
* Make sure you are on the feature/open-authoring branch
* run ```yarn``` and ```yarn dev```
* go to ```http://localhost:3000/```
* observe that the edit button works on the home page but not the doc page (edit button is located on the bottom of the page)

### Expected result

What should happen?
Edit this site button should work on the docs page

### Actual result

What actually happened?
It redirects you without opening the edit panel

#### Tinacms Package Versions

```
├─┬ @tinacms/api-git@0.7.0
├── @tinacms/git-client@0.6.7
├── hygen-next-tinacms-github@0.0.0 invalid
├─┬ next-tinacms-github@0.1.0
├── next-tinacms-json@0.3.13
├─┬ next-tinacms-markdown@0.2.13
├─┬ react-tinacms-github@0.2.0
├─┬ react-tinacms-inline@0.4.6
├─┬ tinacms@0.19.1
│ ├── @tinacms/alerts@0.1.2
│ ├── @tinacms/core@0.7.4
│ ├─┬ @tinacms/fields@0.10.1
│ ├─┬ @tinacms/form-builder@0.3.2
│ ├─┬ @tinacms/forms@0.4.1
│ ├── @tinacms/icons@0.10.0
│ ├── @tinacms/media@0.1.0
│ ├── @tinacms/react-alerts@0.1.3
│ ├─┬ @tinacms/react-core@0.2.11
│ ├─┬ @tinacms/react-forms@0.1.3
│ ├── @tinacms/react-modals@0.1.3
│ ├── @tinacms/react-screens@0.1.2
│ ├─┬ @tinacms/react-sidebar@0.1.3
│ ├─┬ @tinacms/react-toolbar@0.1.1
│ ├── @tinacms/styles@0.4.2
│ └─┬ react-tinacms-editor@0.5.1
│   ├─┬ @tinacms/react-forms@0.1.2-alpha.0

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Chrome |
| os      |  ubuntu 18.04 |
| node    |    v12.16.3   |
| npm     |  6.14.4 |

#### .env file
```
# OAuth App Credentials from GitHub
GITHUB_CLIENT_ID=***
GITHUB_CLIENT_SECRET=****

# The path to your repository in GitHub
REPO_FULL_NAME=logan-anderson/TinaBejamasStarter

# The base branch that new changes and forks are created from. Defaults to 'master'.
BASE_BRANCH=feature/open-authoring
```
#### Other Thoughts

I have a feeling that it may have something to do with the fact that the code that I was given is using 
```javascript
DocTemplate.getInitialProps = async function...
```
instead of 
 ```javascript
export const getStaticProps = async function ....
```

**Comment by ncphillips** [comment]
I think you're right. We do something similar [in our blog](https://github.com/tinacms/tinacms.org/blob/d1d78c2e3b09a9b22b8d2fefabc4a8449b9f94be/pages/docs/%5B...slug%5D.tsx#L95-L129), but this might be a helpful example to look

**Comment by dwalkr** [comment]
We're relying on [preview mode](https://nextjs.org/docs/advanced-features/preview-mode) to activate edit mode, which requires using `getStaticProps` instead of `getInitialProps`. I'm assuming preview data isn't passed to `getInitialProps` when it's set.

**Comment by logan-anderson** [comment]
@dwalkr @ncphillips  Thanks for your help. From looking at tinacms.org example [here](https://github.com/tinacms/tinacms.org/blob/0e1e9d0c5b0f994d031199c4d9d1c7927d2de3e0/pages/docs/%5B...slug%5D.tsx#L116) I was able to make it work.  I changed getInitialProps to getStaticProps and added the getStaticPaths function. 

Final result looked like
```javascript
export const getStaticPaths = async function () {
  const fg = require("fast-glob")
  const contentDir = "docs/"
  const files = await fg(`${contentDir}**/*.md`)
  return {
    fallback: false,
    paths: files
      .map((file) => {
        const path = file.substring(contentDir.length, file.length - 3)
        return { params: { slug: path.split("/") } }
      }),
  }
}
```
