### ISSUE TITLE
External reference in tinacms 0.19.0

### ISSUE THREAD

**Issue by Muthaias** [tinacms/tinacms#1108]
Monitoring network traffic in firefox I noticed that en external css resource is loaded.

I would blame this part but I am not too familiar with styled-components. https://github.com/tinacms/tinacms/blob/da37710076665f6dfc06ca4352c5a287fa0de793/packages/%40tinacms/styles/src/Styles.tsx#L90

The overall system seems to work even though there not network available but I consider it odd that it tries to load this resource in runtime.

**Comment by kendallstrautman** [comment]
@Muthaias that is the font we use for the Tina UI

**Comment by Muthaias** [comment]
Ok. Yes I understand. But as it is currently TinaProvider binds GlobalStyles hard which in turn binds this external resource hard. Is this intended behaviour? Do you expect all users of TinaCMS to rely on this external resource?

Obviously I can work around this by reimplementing a few things myself but I'd like to be able to configure it through injection or something similar. Do you see this as a problem?

**Comment by spbyrne** [comment]
Hey @Muthaias we're definitely open to improving this. In issue #926 we discuss needing to improve the font import. This is part of a larger issue of only loading Tina assets as they're needed. I think in the future we'll move away from Styled Components to make the styling infrastructure easier to work with, but that will require a lot of work.

I'd love to hear your suggestions.

**Comment by Muthaias** [comment]
@spbyrne I am far from an expert in regards to `styled-components` and what would be best in this case. But I do appreciate the way for example `office-ui-fabric-react` is configured and would suggest something similar in this case.

Here is an example where I use it in a project: https://github.com/Muthaias/card-creator/blob/master/src/index.tsx

But as a solution in this specific case I would suggest just removing `<GlobalStyles />` from `TinaProvider` since it would improve modularity. I have solved it like this: https://github.com/Muthaias/tiny-tinacms-test/blob/master/src/index.tsx

Note that I am not using the built in `TinaProvider` but instead a local variant which does not include `GlobalStyles`.

I understand that this complicates the setup process and might not be preferrable from that perspective. In that case then maybe one could setup a `StyleProvider` which could optionally deliver a style object that replaces the built in `GlobalStyles`?

**Comment by Muthaias** [comment]
@spbyrne now that I further investigate `createGlobalStyles` I'd suggest just using `ThemeProvider` and add an option to remove the external font-reference.

**Comment by Muthaias** [comment]
@spbyrne this branch contains an example of a possible solution using `ThemeProvider` https://github.com/Muthaias/tiny-tinacms-test/blob/demo/theme-provider/src/index.tsx

Note that the naming of the theme option is more from my point of view and that the default could be true in the actual TinaCMS case.

Please excuse the comment spamming. I realized that an example would improve communication.

**Comment by spbyrne** [comment]
I think we'll need to solve this in several stages.

First stage I'd like to remove the `@import` statement from `GlobalStyles` but leave the global CSS properties. Instead, I'll use a `FontLoader` component within the `TinaProvider` that uses the **typekit/webfontloader** to load the typeface when the CMS is active. I have a draft PR (#1135) open where I've been experimenting with this approach.
