### ISSUE TITLE
Saving stuck on loading state.

### ISSUE THREAD

**Issue by geocine** [tinacms/tinacms#1124]
**Describe the bug**
When you hit on the save button, it will be stuck on the loading state.

**To Reproduce**
1. Open the sidebar
2. Hit `Save`
3. Wait for it to finish (it will never finish)

**Expected behavior**
Saving loading state should be back to normal once saving is done.

**Screenshots** _(do not mind the artifact)_

![](https://i.imgur.com/pAjD7WU.gif)

 - OS: MacOS Mojave 10.14.6
 - Version 0.1.0

**Additional context**
I can see my terminal is asking for Github credentials. I should be able to use this without a remote.

![](https://i.imgur.com/l01vi9f.png)

**Comment by kendallstrautman** [comment]
@geocine — by default the Git Client will commit+push on save so this behavior is expected unless you configure the package with the option shared by @mpartipilo — `pushOnCommit: false`
