### ISSUE TITLE
Error message for invalid markdown field not helpful

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#1128]
## Description

I accidentally used an object as my markdown data instead of a string.

```
  const formConfig = {
   // ...
    fields: [
      {
        name: "content",
        label: "Content",
        component: "markdown",
      },
    ],
  };

  const [post, form] = useForm(formConfig);
```

In the above example, "content" was formatted as 
```
{
"en-US": "blah blah" 
}
```

react-beautiful-dnd seems to be making the error message extra difficult to parse:

<img width="886" alt="Screen Shot 2020-05-12 at 11 24 50 AM" src="https://user-images.githubusercontent.com/3323181/81703614-37510e00-9443-11ea-8cdf-db5848ad232a.png">

### Steps to reproduce

See above. 

### Expected result

Error message should clearly state which field is formatted incorrectly, and reference the proper line-number. Should be caught and formatted before it bubbles up to react-beautiful-dnd

### Actual result

Generic error (See description). When you have many fields, it is difficult to know which is not properly formatted.

#### Tinacms Package Versions

```text
├─┬ tinacms@0.19.1
│ ├── @tinacms/alerts@0.1.2
│ ├── @tinacms/core@0.7.4
│ ├─┬ @tinacms/fields@0.10.1
│ ├─┬ @tinacms/form-builder@0.3.2
│ ├─┬ @tinacms/forms@0.4.1
│ ├── @tinacms/icons@0.10.0
│ ├── @tinacms/media@0.1.0
│ ├── @tinacms/react-alerts@0.1.3
│ ├─┬ @tinacms/react-core@0.2.11
│ ├─┬ @tinacms/react-forms@0.1.3
│ ├── @tinacms/react-modals@0.1.3
│ ├── @tinacms/react-screens@0.1.2
│ ├─┬ @tinacms/react-sidebar@0.1.3
│ ├─┬ @tinacms/react-toolbar@0.1.1
│ ├── @tinacms/styles@0.4.2
│ └─┬ react-tinacms-editor@0.5.1
│   ├─┬ @tinacms/react-forms@0.1.2-alpha.0
```

Mac OSX, chrome

**Comment by jamespohalloran** [comment]
It looks like this might be patched in react-beautiful-dnd v12 👀
https://github.com/atlassian/react-beautiful-dnd/issues/1108

**Comment by ncphillips** [comment]
Amazing! Doesn't necessarily fix this issue, but it will be an improvement.

**Comment by DirtyF** [comment]
https://github.com/atlassian/react-beautiful-dnd/releases/tag/v12.0.0 was released back in October, can we upgrade to the latest version (v13.0)?
