### ISSUE TITLE
Add tooltips to wysiwym menu

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#1136]
Wysiwym menu should have tooltips which also show keyboard shortcut for the menu item.

**Comment by DirtyF** [comment]
Some tooltip examples:

**GitHub**
<img width="283" alt="Capture d’écran 2020-05-14 à 11 13 01" src="https://user-images.githubusercontent.com/103008/81916337-fe946e80-95d3-11ea-912f-243d55078a86.png">

**Slack**
<img width="345" alt="Capture d’écran 2020-05-14 à 11 14 56" src="https://user-images.githubusercontent.com/103008/81916790-972aee80-95d4-11ea-9a10-6cefd97945f8.png">

**Comment by jpuri** [comment]
Hey @spbyrne : can you plz share ur suggestions for the design of tooltips.

**Comment by DirtyF** [comment]
@jpuri Can we already add some tips to help users as the https://prosemirror.net/ page demoes and make it better by showing shortcodes or showing a tooltip later?

**Comment by jpuri** [comment]
Yes @DirtyF : I can do that, adding simple basic html tooltip is easy.

**Comment by DirtyF** [comment]
OK, so let's add something simple like:

- Heading: Toggle Heading level
- Bold: Toggle Bold text (cmd-b)
- Italic: Toggle Italic text (cmd-i)
- Strike: Toggle Strikethrough text
- Link: Add or remove link (cmd-k)
- Table: Add Table
- Quote: Toggle Quote paragraph
- Code: Toggle Code block
- List: Toggle unordered list
- Ordered List: Toggle ordered list
- Undo: Undo (cmd-z)
- Redo: Redo
- Markdown: Toggle Markdown mode

**Comment by DirtyF** [comment]
Fixed in #1367 

Functional, to be improved with a generic tooltip component later in a later iteration.
