### ISSUE TITLE
WYSIWYM not keeping integrity of fenced code blocks

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1138]
## Description

WYSIWYM not maintaining fenced code blocks on copy and paste. Confirmed using open authoring.

### Steps to reproduce

1. Create a fenced code block, e.g: (don't copy this example, it has 0 width spaces in it)
   ```
   ``᠎`typescript
   let x: string = "hello world!"
   ``᠎`
   ```
2. Open the page in WYSIWYM
3. Copy the block by using the arrow key to position the cursor above the block, and then use shift + arrows to select and then copy the code block
4. Paste the code block below and then save
5. Examine the new code block, it's tabular, not fenced!

### Expected result

It should stay fenced.

### Actual result

It becomes tabular.

#### Tinacms Package Versions

```text

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by ncphillips** [comment]
I personally would prefer if code-blocks defaulted to the fence rather then spaced style.

A feature request might be to make it possible to modify the language after the block is created
