### ISSUE TITLE
Interest check and comments request: gatsby plugin for site settings, similar to settings available in tina-starter-grande's hamburger menu

### ISSUE THREAD

**Issue by mirabilio** [tinacms/tinacms#1143]
I think it would be convenient to have a plugin that enables configuration of typical site-wide settings, similar to what `tina-starter-grande` does with the hamburger menu with Menu, Theme, Site configuration screens.

Some very initial thoughts on features:
- First-class support of the [System UI](https://system-ui.com/) theme specification
- Potentially opinionated about design framework by preferring or explicitly requiring [Theme UI](https://theme-ui.com/)
- Ability to configure _n_ number of color modes / palettes and allow site admin to set the default mode to one of these available modes via the admin menu
- First-class support of dark mode and its configurations (plus fixing some of the current wonky OOTB dark mode behaviors in theme-ui: [624](https://github.com/system-ui/theme-ui/issues/624) [787](https://github.com/system-ui/theme-ui/issues/787))
- The plugin would only provide _configurability_ of the UI and meta elements. It would be up to the site developer to consume these configurations in their components via adhering to System UI / Theme UI standards.
- The goal would be to require nothing (or as little as possible) of the site developer other than adhering to System UI spec / Theme UI in their components. Plugin should be immediately functional and working upon plugin installation as long as these requirements are met.

I also want to make sure I won't be duplicating any work that's already been developed by Tina team or conflict with any requirements already fleshed-out in the TinaCMS roadmap.

Please let me know your thoughts. I have to develop a plugin like this anyway for my TinaCMS-based sites, so I thought it would be useful for other site developers if something like this was available as an easy, "just works" plugin.

**Comment by kendallstrautman** [comment]
I think this seems like a great idea! So it's like a pre-baked screen (or global form) plugin? I'd be curious to hear how you'd approach the content modeling; another requirement I foresee for this to 'just work' is for the data structure and graphQL queries to exactly match the plugin. Or if I have the wrong idea, feel free to expand on how folks will use this.

I think this would be an awesome external plugin, but not sure it makes sense to be a part of the actual Tina packages. A couple points for this reasoning: the coupling with a design framework and the prescriptive nature of this type of plugin. I'd love to hear others' thoughts on this though.

**Comment by mirabilio** [comment]
> I think this seems like a great idea! So it's like a pre-baked screen (or global form) plugin? 
> [snip]
> I think this would be an awesome external plugin, but not sure it makes sense to be a part of the actual Tina packages. A couple points for this reasoning: the coupling with a design framework and the prescriptive nature of this type of plugin. I'd love to hear others' thoughts on this though.

100% agree that it should not be part of core Tina package. The grander vision is that this would be just one of many "site administration" plugins that would collectively be used by site designers to add to sites for the clients / site owners to use for every day end-user, admin purposes.

I'm envisioning three plugins: 
1. generic gatsby plugin
Provides core theme configuration APIs, features (no included UI admin components)
2. GlobalForm plugin
A host for "site administration" plugins (like the one I'm proposing).
3. finally, the TinaCMS theme admin plugin
Plugs into the above global admin host plugin. Provides the theme configuration features that are yet to be fully fleshed-out :)

This week looks like I'm fully booked on client work, but I'll be hopefully working through the rest of your questions to solidify this. Thanks so much for the input!
