### ISSUE TITLE
Date component with timeFormat doesn't allow the time to change

### ISSUE THREAD

**Issue by TorrinLynn** [tinacms/tinacms#1144]
## Description

Enabling time in the date component (timeFormat: true or timeFormat: "HH:mm ZZ"), displays the time and shows the time editor, but clicking on the arrows changes the time and immediately reverts it back.

### Steps to reproduce

In the Tina-starter-grande project, in src/templates/post.js, add dateFormat: true, timeFormat: true to the date field. Navigate to http://localhost:8000/blog/introducing-tina-grande, click the edit icon, click the date and select the time. Attempting to change the time with the arrows will cause the number to briefly change and then immediately go back to its previous value.

### Expected result

Time should change when the arrows are clicked

### Actual result

User is unable to change the time.

#### Tinacms Package Versions

```text
├─ @tinacms/alerts@0.1.2
├─ @tinacms/api-git@0.7.0
├─ @tinacms/core@0.7.4
├─ @tinacms/fields@0.10.1
│  ├─ @tinacms/icons@^0.10.0
│  ├─ @tinacms/styles@^0.4.2
├─ @tinacms/form-builder@0.3.2
│  ├─ @tinacms/forms@^0.4.1
│  ├─ @tinacms/react-core@^0.2.11
├─ @tinacms/forms@0.4.1
├─ @tinacms/git-client@0.6.7
├─ @tinacms/icons@0.10.0
├─ @tinacms/media@0.1.0
├─ @tinacms/react-alerts@0.1.3
├─ @tinacms/react-core@0.2.11
│  ├─ @tinacms/core@^0.7.4
│  └─ @tinacms/forms@^0.4.1
├─ @tinacms/react-forms@0.1.3
│  ├─ @tinacms/form-builder@^0.3.2
├─ @tinacms/react-modals@0.1.3
├─ @tinacms/react-screens@0.1.2
├─ @tinacms/react-sidebar@0.1.3
│  ├─ @tinacms/core@^0.7.4
│  ├─ @tinacms/forms@^0.4.1
├─ @tinacms/react-toolbar@0.1.1
│  ├─ @tinacms/core@^0.7.3
│  ├─ @tinacms/fields@^0.10.1
│  ├─ @tinacms/forms@^0.4.1
├─ @tinacms/styles@0.4.2
├─ gatsby-plugin-tinacms@0.1.35
│  └─ tinacms@^0.19.1
├─ gatsby-tinacms-git@0.4.9
│  ├─ @tinacms/api-git@^0.7.0
│  └─ @tinacms/git-client@^0.6.7
├─ gatsby-tinacms-json@0.8.20
├─ gatsby-tinacms-remark@0.7.15
├─ react-tinacms-editor@0.5.1
│  ├─ @tinacms/core@^0.7.4
│  ├─ @tinacms/fields@^0.10.1
│  ├─ @tinacms/icons@^0.10.0
│  ├─ @tinacms/react-forms@0.1.2-alpha.0
│  ├─ @tinacms/react-forms@0.1.2-alpha.0
│  │  ├─ @tinacms/form-builder@^0.3.2-alpha.0
│  ├─ @tinacms/styles@^0.4.2
├─ react-tinacms-inline@0.4.6
├─ tinacms@0.19.1
│  ├─ @tinacms/alerts@^0.1.2
│  ├─ @tinacms/core@^0.7.4
│  ├─ @tinacms/fields@^0.10.1
│  ├─ @tinacms/form-builder@^0.3.2
│  ├─ @tinacms/forms@^0.4.1
│  ├─ @tinacms/icons@^0.10.0
│  ├─ @tinacms/media@^0.1.0
│  ├─ @tinacms/react-alerts@^0.1.3
│  ├─ @tinacms/react-core@^0.2.11
│  ├─ @tinacms/react-forms@^0.1.3
│  ├─ @tinacms/react-modals@^0.1.3
│  ├─ @tinacms/react-screens@^0.1.2
│  ├─ @tinacms/react-sidebar@^0.1.3
│  ├─ @tinacms/react-toolbar@^0.1.1
│  ├─ @tinacms/styles@^0.4.2
│  └─ react-tinacms-editor@^0.5.1

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Brave 1.8.96, Chrome 81.0.4044.138      |
| os      |   macOS Catalina      |
| node    |   v12.16.1      |
| yarn     |     1.22.4    |

**Comment by kendallstrautman** [comment]
[Reproduced](https://www.loom.com/share/29beb409d0d040b39c9bf8c20c63e1b8) in `demo-gatsby`. With a little testing, I noticed that if I removed the `onChange` handler from the `ReactDatetime` component, the field will change (and persist) the time value property, but obviously those changes won't update in the input and source file.

We need to add more tests for the `timeFormat` implementation. The date field in general needs some love, there's a few more bugs to take a look at.

**Comment by mittonface** [comment]
It looks like we're just not handling `timeFormat` at all. I think the fix looks something like this: https://github.com/tinacms/tinacms/commit/6a72ce6eb215a3f2d33141e933febca5bd59708e

Not fully tested yet, but it seems to be working better.

![working_somewhat](https://user-images.githubusercontent.com/5082908/82356379-764a0b00-99d1-11ea-902c-4046ed455c60.gif)
