### ISSUE TITLE
Support remote names other than `origin`

### ISSUE THREAD

**Issue by IronSean** [tinacms/tinacms#1199]
## Summary

We should be able to support committing to remotes other than `origin`.

### Basic example

Maybe it could be on the client configuration? I'm not really sure but as an example this might make sense:
```typescript
const tina = new TinaCMS();
const client = new GitClient("http://localhost:3000/___tina", "myRemote");
tina.registerApi("git", client);
```

and the signature of the GitClient constructor could be
```typescript
constructor(baseUrl: string, remote: string = "origin");
```

### Motivation

Tina's git backend fails if there is no remote named `origin` currently. `origin` is fairly generic and may not be used depending on the use case. 

For instance, if you forked a repo you had also checked out (with the source as `origin` and your fork as `myForm`) and ran Tina locally, you might expect to push to `myFork` instead of `origin` if remote `myFork` is set as the current upstream in other tools.

Or in cases where the source repo is in BitBucket but I keep my working fork in GitHub, I tend to name my remotes `Github` and `BitBucket` for clarity.

**Comment by ncphillips** [comment]
I like it, though I would probably opt to put this configuration in the Repo class on the server. 

[This is where the upstream `"origin"` is hardcoded](https://github.com/tinacms/tinacms/blob/master/packages/@tinacms/api-git/src/repo.ts#L112)
