### ISSUE TITLE
Editor scrolling when toggling markdown mode

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#1225]
Editor scrolls to top when toggling markdown editing mode.

Ref: https://github.com/tinacms/tinacms/pull/1217#issuecomment-639624509

**Comment by ncphillips** [comment]
I'm guessing the window size is changing? The wysiwyg is usually taller then the plain text editor

**Comment by jpuri** [comment]
That could be one of the reasons, also editor scroll editable areas into view once they are focused.
