### ISSUE TITLE
Vue.js support

### ISSUE THREAD

**Issue by maxerbox** [tinacms/tinacms#1258]
## Summary

I would love to use tinacms with Vue.js. Vue.js is a great framework with a good learning curve.

### Motivation

I'm a vue.js junior dev and we don't have much open source alternative with git-based cms. Tinacms seems very interesting for jamstack websites. I noticed that there was no issue asking for a vue.js support.

List of packages that should be adapted :

- [ ] react-tinecms
- [ ] react-dismissible
- [ ] react-tinacms-editor
- [ ] react-tinacms-github
- [ ] react-tinacms-inline

**Comment by DirtyF** [comment]
The core team is currently focused on tailoring a good editing experience with React, we're still pre v1.0 and a lot of things are moving.  TinaCMS could work with Vue.js, but we'll need help from the VueJS community to adapt and maintain all the packages for VueJS.

**Comment by kendallstrautman** [comment]
This is awesome! Definitely needed, but not a small enhancement to take on. The entire Tina UI is built with React. We've discussed converting it to web components ([with Stencil](https://stenciljs.com/)) to mitigate this issue. I would take a look at [this PR](https://github.com/tinacms/tinacms/pull/601) to see previous discussion.

**Comment by alijaya** [comment]
hello I'm interested in this, is there any current development that I could help with this?

**Comment by louis-lau** [comment]
👀

**Comment by louis-lau** [comment]
👀

**Comment by anmol1905** [comment]
eyes

**Comment by Remzi1993** [comment]
Please open this issue to track the progression of Vue.js

**Comment by ngustavo** [comment]
Vue is currently on [v3.2.47](https://vuejs.org/about/releases.html)
Nuxt is on [v3.3.1](https://nuxtjs.org/releases/)

BTW Nuxt has a [Content](https://content.nuxtjs.org/) module among [others](https://nuxt.com/modules). That module has MDC support.

**Comment by Youhan** [comment]
Would love to see if there are any plans to add Vue or Nuxt support.

**Comment by chrisspiegl** [comment]
To have this in the docs as "planned" and then having it basically "dead" for 3 years? Not sure that's the best way to get new customers. I was so excited by finding it to support Vue/Nuxt… guess not.

**Comment by Youhan** [comment]
[Nuxt Studio](https://nuxt.studio/) is built on to of Nuxt Content module and is a really good alternative if you love working with Vue.

**Comment by lastlink** [comment]
I use netlify to manage markdown content in git in vue nuxt.
```shell
# start netlify cms, make sure to have a sep port, if running more than one website at a time 
# change port in static\admin\config.yml
yarn start:cmsProxy
yarn dev
# navigate to localhost:3000/admin to see cms system
```

here's my package.json
```json
{
  "name": "nuxt-content-article",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "lint:js": "eslint --ext .js,.vue --ignore-path .gitignore .",
    "lint:style": "stylelint **/*.{vue,css} --ignore-path .gitignore",
    "lint:stylefix": "stylelint **/*.{vue,css}  --fix  --ignore-path .gitignore",
    "lint:fix": "eslint --ext .js,.vue  --fix --ignore-path .gitignore .",
    "lint": "yarn lint:js && yarn lint:style",
    "start:cms": "netlify dev --port=8891",
    "start:cmsProxy": "npx netlify-cms-proxy-server"
  },
  "lint-staged": {
    "*.{js,vue}": "eslint",
    "*.{css,vue}": "stylelint"
  },
  "dependencies": {
    "@nuxt/content": "^1.11.1",
    "nuxt": "^2.14.12",
    "prism-themes": "1.5.0"
  },
  "devDependencies": {
    "@nuxtjs/eslint-config": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/stylelint-module": "4.0.0",
    "@nuxtjs/tailwindcss": "^3.4.2",
    "babel-eslint": "10.1.0",
    "eslint": "^7.17.0",
    "eslint-config-prettier": "^7.1.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-prettier": "^3.3.1",
    "husky": "^4.3.7",
    "jquery": "^3.5.1",
    "lint-staged": "^10.5.3",
    "netlify-cli": "^2.69.10",
    "prettier": "^2.2.1",
    "stylelint": "13.8.0",
    "stylelint-config-prettier": "8.0.2",
    "stylelint-config-standard": "20.0.0"
  }
}
```
