### ISSUE TITLE
Gridsome support

### ISSUE THREAD

**Issue by maxerbox** [tinacms/tinacms#1260]
## Summary

Integrate with gridsome static site generator

### Motivation

Gridsome is a gatsby like static site generator, but for vue.js

**Comment by djmtype** [comment]
Would love to experience this with Gridsome!

**Comment by moonstash** [comment]
wen gridsome support :D.

**Comment by aManNamedJed** [comment]
I might take this on

**Comment by DirtyF** [comment]
@aManNamedJed Curious about how you would aproach this for Gridsome.
We decided to mainly focus on Next.js for now who offers a [preview mode](https://nextjs.org/docs/advanced-features/preview-mode) that makes real-time contextual editing easy.

**Comment by aManNamedJed** [comment]
I have been crushing it with the `gatsby-tinacms-git` package and would love to see that move over to Vue. Would be happy to spearhead the whole thing as much as I can but obviously a huge undertaking.

**Comment by maxerbox** [comment]
Pouet
