### ISSUE TITLE
Create plugin for youtube embeddable media for wysiwym

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#1262]
Ref: https://github.com/tinacms/rfcs/blob/master/0007-tinacms-wysiwym-plugins.md

A plugin is required to be created for youtube embeddable media. The plugin is similar to example in RFC above, plugin will be an object with following properties:

1. name - name of the plugin
2. schema - new node to be defined for embeddable
3. nodeView - node view for the youtube video, this will show video in an iFrame
4. menuItem - this will be added to menubar, it will show an icon for video, when clicked it will open a small popup to enter link which will have options - `Insert`, `Cancel`.
5. markdownTranslator - it will have following properties
    1. to_markdown - it will be a function similar to these defined [here](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-editor/src/translator/MarkdownTranslator/commonmark/tokens.ts#L119). It will take as props `MarkdownSerializerState` and `Node`.
    2. from_markdown - it will be mapping from markdown token to prosemirror node like defined [here](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-editor/src/translator/MarkdownTranslator/commonmark/tokens.ts#L41).
     3. markdown-it-plugin - this will be plugin for [markdown-it parser](https://github.com/markdown-it/markdown-it). It will create tokens for video by parsing input.

**Comment by veerjainATgmail** [comment]
Hi, 

Is there a work around to achieve embedding a video-player/record-and-upload with link now? 

thanks.
mj

**Comment by ncphillips** [comment]
Hey @veerjainATgmail you can past the html for an embed directly in the editor. Here is an example on the [tinacms.org website](https://tinacms.org/blog/inline-editing-project) and here is the [source file](https://github.com/tinacms/tinacms.org/blob/master/content/blog/inline-editing-project.md).

Make sure to remove the link when you paste the embed into the editor.

**Comment by veerjainATgmail** [comment]
> Hey @veerjainATgmail you can past the html for an embed directly in the editor.
> 
> Here is an example on the [tinacms.org website](https://tinacms.org/blog/inline-editing-project) and here is the [source file](https://github.com/tinacms/tinacms.org/blob/master/content/blog/inline-editing-project.md).
> 
> Make sure to remove the link when you paste the embed into the editor.

@ncphillips , thanks. :+1: 
Just to clarify, the ask is to use htm media record and upload with the edit mode and playback.I'll try that.

**Comment by veerjainATgmail** [comment]
@ncphillips , thanks.
