### ISSUE TITLE
GitHub API: Switching branches does not sync form state

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#1264]
Using the GitHub API with a client-side editing flow, switching branches via the toolbar does not update the form state with the contents of that branch. We need to re-initialize the form (re-run `loadInitialValues`) after switching branches.

**Comment by ncphillips** [comment]
Right now the Form `id` is just the file's relative path within the repo. If that was changed to be the branch + fileRelativePath then re-initializing would happen automatically.

**Comment by dwalkr** [comment]
I just had that exact thought! The thing is, in some cases we will need to get the branch asynchronously

**Comment by dwalkr** [comment]
Adding branch name to the ID would also make the localStorage behavior work seamlessly

**Comment by ncphillips** [comment]
Why would tou have to get the branch name asynchronously?

**Comment by dwalkr** [comment]
j/k that's for the SHA, looks like we'll always have a branch name to work from

**Comment by dwalkr** [comment]
Updating the form ID works but it needs a signal from the branch switcher to know that the branch has been updated. In a moment I will submit a PR that dispatches an event on branch select
