### ISSUE TITLE
Not possible to get out of code block

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#1270]
If code block is the only block in editor it is not possible to come out of it.
![code](https://user-images.githubusercontent.com/2182307/84895942-bf6ca800-b0c0-11ea-9561-3c0805a8b9b1.gif)

Like in case of `blockquote` 2 / 3 `Enter` should take user out of code block.

**Comment by DirtyF** [comment]
I've ran into this one quiet a few times during my testing.
Does SHIFT+ENTER help?

**Comment by jpuri** [comment]
Yes I found that `SHIFT-ENTER` is doing the needful.
May be we can close this.
