### ISSUE TITLE
Incorrect working repository in the Github Toolbar after re-authentication

### ISSUE THREAD

**Issue by sibyl229** [tinacms/tinacms#1294]
## Description

The working repository in the Github Toolbar is incorrectly set to the base repository instead of the fork repository, on the 2nd, and subsequent _even_ number of re-authentication. Strangely, the problem doesn't seem to occur on odd number of re-authentications.

![Screen Shot 2020-06-25 at 3 00 05 PM](https://user-images.githubusercontent.com/1753893/85784270-1ba17e80-b6f6-11ea-960c-3871a49849e5.png)

### Steps to reproduce

- Visit the tinacms.org site as a user without write permission to the tinacms/tinacms.org Gitbub repo.
- Visit a blog post page, and click on Edit this Post, and follow the prompt to login and create a fork
- Observe that the working directory is now correctly set to the fork
- Click on Exit Edit Mode
- Wait a few seconds or longer, click on Edit this Post again
- Observe that the working directory is now incorrectly set to the base repository

### Expected result

The Working Repository in the Github Toolbar should always be set to the fork for people without write permission to the base repo.

### Actual result
The Working Repository in the Github Toolbar is sometime set to the base repo for people without write permission to it. 

The problem appears consistently on second (and subsequent even number) attempts to enter edit mode with "Edit this Post" button. 

#### Tinacms Package Versions

```text
react-tinacms-github@0.4.1 (probably)
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Chrome 83.0.4103.116        |
| os      |  MacOS 10.14.6       |
| node    |         |
| npm     |         |

**Comment by ncphillips** [comment]
>  the problem doesn't seem to occur **on odd number** of re-authentications.

🤦‍♀️

Thanks for the report @sibyl229!
