### ISSUE TITLE
Add Babel Plugin for better style debugging

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#130]
Currently debugging style issues is terrible, there's no naming or context when you're looking at the devtools. For example, if you're trying to debug styles, the outputted classnames are basically gibberish. [This plugin](https://github.com/styled-components/babel-plugin-styled-components) would help with that by appending the actual component name to the class name, as far as I understand.

 > [Example from their docs](https://styled-components.com/docs/tooling#better-debugging): In your page source you'll see: \<button class="Button-asdf123 asdf123" /> instead of just \<button class="asdf123" />.

Seems like we would need to add babel to rollup and then also use [this preset](https://babeljs.io/docs/en/babel-preset-typescript) to make it work with typescript.

**Comment by maciekgrzybek** [comment]
Is that still something that you want to add to the project? If so, I can give it a go.

**Comment by ncphillips** [comment]
It’s a bit awkward because we don’t actually use Babel in this project. You can still free to take a look. I believe you would want to look in @tinacms/scripts

**Comment by maciekgrzybek** [comment]
Ok, I'll speak to Kendall and see what's what :)

**Comment by maciekgrzybek** [comment]
I think this is something we could use - https://github.com/Igorbek/typescript-plugin-styled-components

**Comment by kendallstrautman** [comment]
That plugin looks cool! ☝️ But we don't use webpack so not sure exactly how it would be implemented.

**Comment by kendallstrautman** [comment]
@spbyrne — does the styled-components debugging bother you? Or a better way to ask, would the appending of actual classnames you can read make your life a whole lot easier?

**Comment by maciekgrzybek** [comment]
@kendallstrautman I did a little digging in the docs and looks like it's possible to use it in Rollup
