### ISSUE TITLE
don't bundle full crypto-js

### ISSUE THREAD

**Issue by sakulstra** [tinacms/tinacms#1302]
## Summary
[In the change log i read that moment was dropped from core which should improve bundle size](https://tinacms.org/blog/2020-06-29-release-notes).
After updating i had to realize that while moment was dropped, but at least [crypto-js was added](https://github.com/tinacms/tinacms/commit/a494f8f) in sum slightly increasing the bundle size.

### Motivation
Bundle size is relevant for initial render at al. - would be nice if it was reasonable sized. I'm not 100% sure yet what is responsible for the increase in bundle size - at first sight it seems like it's pulling in parts of crypto-js that might not be needed.

**before updating tina packages**
![image](https://user-images.githubusercontent.com/4396533/86118317-e4094c80-bad0-11ea-9460-e65d975a3414.png)
**after updating tina packages**
![image](https://user-images.githubusercontent.com/4396533/86118001-5299da80-bad0-11ea-9a6f-c74d2e44ac07.png)

**Comment by sakulstra** [comment]
sorry... was on a weirdly forked & linked version. nvm

**Comment by ncphillips** [comment]
It's really weird that `crypto-js` is being bundled, as it's not being used in any front-end code. All of those `next-tinacms-github` uses are server side. I wonder if that chunk is served to the frontend, or if it's only created for the backend code n 🤔

**Comment by sakulstra** [comment]
@ncphillips sorry for the fuzz - i broke the serverside shaking on my side by doing weird stuff :/
