### ISSUE TITLE
api-git: Improve error communication on failed push

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#1316]
### Summary

Reposting from [the Forum](https://community.tinacms.org/t/no-error-message-when-github-push-fails/252).

TL:DR, when a commit or push fails, we should better alert the editor beyond just posting error details to the console.

### Basic example

Seems like adding a `cms.alerts.error()` to these catch statements would be good? Or should we allow the developer to configure this with a callback in the `GitRouterConfig`?

### Motivation

To make sure editors get feedback when their attempts to save content fails.

**Comment by ncphillips** [comment]
This came up with [GithubFile](https://github.com/tinacms/tinacms/blob/github-file-commit/packages/react-tinacms-github/src/github-client/GithubFile.ts#L62) recently. I think the direction we're going is to dispatch plain CMS events rather then alerts. The develope could then setup a listener to dispatch a CMS alert in their language of choice, pop a modal, or do whatever else they have in mind.

```js
cms.events.subscribe("git:error", (event) => {
  if (isGitPushFailure(event)) cms.alerts.error("Error al empujar al repositorio")
})
```
