### ISSUE TITLE
useJsonForm with InlineBlocks not working as expected.

### ISSUE THREAD

**Issue by RobertBroersma** [tinacms/tinacms#1320]
## Description

When using `useJsonForm` in conjunction with `InlineForm` and `InlineBlocks` in a Gatsby project there seems to be something wrong. According to the Tina docs `InlineBlocks` takes a `name` prop with the object key of where the blocks are. This results for me in an empty page, perfectly editable, but nothing happens when pressing Save (it succeeds but nothing happened).

**However** it works when passing `rawJson.blocks` to the `name` prop.

I was wondering if this was intended or the docs are correct 😄 

### Steps to reproduce

```jsx
function BlogPostTemplate({ data }) {
  const [, form] = useJsonForm(data.dataJson)
  usePlugin(form)

  return (
    <div className={`home theme-light primary-teal`}>
      <InlineForm form={form}>
        <InlineBlocks name="blocks" blocks={BLOCKS} />
      </InlineForm>
    </div>
  )
}
```

Here's a demo: https://github.com/RobertBroersma/statikly

Check out the `templates/blog-post.js`!

### Expected result

`<InlineBlocks name="blocks" blocks={BLOCKS} />` works.

### Actual result

`<InlineBlocks name="rawJson.blocks" blocks={BLOCKS} />` works.

### Environment

Windows 10 with WSL.

#### Tinacms Package Versions
─┬ gatsby-plugin-tinacms@0.2.5
│ └─┬ tinacms@0.22.1
│   ├── @tinacms/alerts@0.1.6
│   ├── @tinacms/core@0.10.1
│   ├─┬ @tinacms/fields@0.12.3
│   ├─┬ @tinacms/form-builder@0.3.8
│   ├─┬ @tinacms/forms@0.6.3
│   ├── @tinacms/icons@0.14.0
│   ├── @tinacms/media@0.1.0
│   ├── @tinacms/react-alerts@0.1.12
│   ├─┬ @tinacms/react-core@0.3.3
│   ├─┬ @tinacms/react-forms@0.2.3
│   ├── @tinacms/react-modals@0.1.12
│   ├── @tinacms/react-screens@0.1.11
│   ├─┬ @tinacms/react-sidebar@0.3.1
│   ├─┬ @tinacms/react-toolbar@0.3.1
│   ├─┬ @tinacms/styles@0.5.2
├─┬ gatsby-tinacms-git@0.5.7
│ ├─┬ @tinacms/api-git@0.7.0
│ └── @tinacms/git-client@0.6.7
├─┬ gatsby-tinacms-json@0.8.31
├─┬ react-tinacms-inline@0.10.1

#### Tools

| Tool    | Version |
| ------- | ------- |
| Chrome|83.0         |
| Windows + WSL      |10         |
| node    | 14      |
| yarn | 1.22.4         |

---

EDIT: Looking at the examples it seems to be correct. You can close this!

**Comment by kendallstrautman** [comment]
Hi @RobertBroersma, thanks for posting! This is expected behavior. The `name` should be the _path to the blocks data_. So `blocks` is just an example if it was in the root of the data, since Gatsby paths work a bit differently, that `rawJson.blocks` is what you need. Let us know if you have any other questions!
