### ISSUE TITLE
html WYSIWYG component - link modal position is displaced by scrolling text input

### ISSUE THREAD

**Issue by aratner** [tinacms/tinacms#1322]
## Description

When you have enough copy in the text input (of the html WYSIWYG component) to get a scrollbar, the link edit/add modal will position itself as far as you scroll within that text input (within the sidebar, outside the text input). It will even increase the height of the sidebar itself (if there is a lot text and you can scroll far). Originally thought the modal wasn't working, but then found it way at the bottom, past all the component inputs at the bottom of the newly created blank space.

<img width="338" alt="Screen Shot 2020-07-08 at 7 34 37 PM" src="https://user-images.githubusercontent.com/47365929/86980673-7608f900-c152-11ea-988b-f677e99f2021.png">

Seems sort of similar to [#735](https://github.com/tinacms/tinacms/issues/735), but in the sidebar.

### Steps to reproduce

1. Paste approximately 700+ characters of text (or enough to get a scroll) into the input of an html WYSIWYG component. Paste more if you want to see how far it will travel. 

2. Scroll to the bottom within the text input

3. Add/edit a link to a word at the bottom.

### Expected result

Link  modal should not position further than height/width of html WYSIWYG.

#### Tinacms Package Versions

```├─┬ gatsby-plugin-tinacms@0.2.2
│ └─┬ tinacms@0.21.2
│   ├── @tinacms/alerts@0.1.4
│   ├── @tinacms/core@0.9.0
│   ├─┬ @tinacms/fields@0.12.0
│   ├─┬ @tinacms/form-builder@0.3.5
│   ├─┬ @tinacms/forms@0.6.0
│   ├── @tinacms/icons@0.14.0
│   ├── @tinacms/media@0.1.0
│   ├── @tinacms/react-alerts@0.1.9
│   ├─┬ @tinacms/react-core@0.3.0
│   ├─┬ @tinacms/react-forms@0.2.0
│   ├── @tinacms/react-modals@0.1.9
│   ├── @tinacms/react-screens@0.1.8
│   ├─┬ @tinacms/react-sidebar@0.2.0
│   ├─┬ @tinacms/react-toolbar@0.2.0
│   ├─┬ @tinacms/styles@0.5.1
├─┬ gatsby-tinacms-git@0.5.4
│ ├─┬ @tinacms/api-git@0.7.0
│ └── @tinacms/git-client@0.6.7
├─┬ gatsby-tinacms-json@0.8.28
├─┬ gatsby-tinacms-remark@0.8.3
│ ├─┬ react-tinacms-editor@0.8.1
│ ├─┬ react-tinacms-inline@0.8.0

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Chrome Version 83.0.4103.116      |
| os      |   macOS Sierra Version 10.12.6      |
| node    |    v13.14.0     |
| npm     |     6.14.5    |
| Gatsby CLI     |     2.12.52    |
| Gatsby    |     2.23.3    |

**Comment by kendallstrautman** [comment]
@spbyrne some modal goodness 😊 although I'm not sure if this is @DirtyF & @jpuri territory since it seems specific to the WYSIWYM.

**Comment by DirtyF** [comment]
Most of the WYSIWYG editing experience has been designed with Inline editing in mind until now as it's a way much nicer experience. @aratner Could you use [inline WYSIWYG](https://tinacms.org/docs/inline-editing/inline-wysiwyg) here instead?

**Comment by aratner** [comment]
@DirtyF ok good to know will give inline a try!

**Comment by daho-turner** [comment]
also an issue for me. :(
tried using the inline WYSIWYG editor but having a slew of other issues with that.  I'm thinking because there my forms are nested in layers of components.

any chance there might be a quick (not too dirty) fix for the non-inline WYSIWYG component?  A scrollTo perhaps?
