### ISSUE TITLE
UX - validate create branch with spaces

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1323]
Can we ease the creation of branches for editors that don't know about branch naming conventions?

**Scenario**

```gherkin
Given I type a space in a branch name
When I click on Create Branch
Then nothing happens
And I have no feedback on why
```

**Demo**
https://www.loom.com/share/70bf123c26594a319533a270d1119a77

**Comment by kendallstrautman** [comment]
If the branch creation fails, there should be a `github:error` event that fires. The dev has to subscribe to the event and then they can provide feedback with an alert or something. I agree more validation would be good there though.

**Comment by DirtyF** [comment]
So it's something developers can act upon using [events](https://tinacms.org/docs/cms/events/) and writing their own `Submit` function? I have no idea how it's part of the `react-tinacms-github` package and if this part is extensible 😊

**Comment by kendallstrautman** [comment]
Yeah so they can subscribe to events and then use a callback function to invoke whenever the event is fired. They can subscribe to the event in their app, something like: 

```
  React.useEffect(() => {
    cms.events.subscribe("github:error", function handleError(event) {
        cms.alerts.error("Something went wrong!")
    })
  }, [])
```

**Comment by kendallstrautman** [comment]
At the very least I think we should just slugify the branch names in the package though to avoid this presumably common mistake folks will run into.
