### ISSUE TITLE
[Bug] Hidden sidebar being ignored

### ISSUE THREAD

**Issue by raulfdm** [tinacms/tinacms#1325]
## Description

Hey there.

Since version `gatsby-plugin-tinacms@0.2.4^` I'm having some issue with `hidden` option.

Since I was checking if it's production or not, I thought I screwed something in there, however, I notice that even if I enforce by passing explicitly `true`, the bar got shown.

**IMPORTANT**

In version `gatsby-plugin-tinacms@0.2.3` it **does not** happen.

### Steps to reproduce

It's in my open source web site so you can either check in this PR: https://github.com/raulfdm/raulmelo.dev/pull/850 or:

1. Clone the project;
1. Install dependencies;
1. Be sure to setup `hidden: true`;
1. `yarn dev`

### Expected result

Show bar not shown when I define to.

### Actual result

Showing the bar doesn't matter if it's true or false

#### Tinacms Package Versions

```text
npm ERR! peer dep missing: @typescript-eslint/eslint-plugin@^2.16.0, required by @sub-tv/eslint-config@1.1.0
npm ERR! peer dep missing: @typescript-eslint/parser@^2.16.0, required by @sub-tv/eslint-config@1.1.0
npm ERR! peer dep missing: eslint@^6.8.0, required by @sub-tv/eslint-config@1.1.0
npm ERR! peer dep missing: gatsby-transformer-remark@>=2.1.1, required by gatsby-tinacms-remark@0.8.6
npm ERR! peer dep missing: react-refresh@^0.8.2, required by @pmmmwh/react-refresh-webpack-plugin@0.3.3
npm ERR! missing: acorn@^7.3.1, required by gatsby-recipes@0.1.49
npm ERR! missing: xstate@^4.11.0, required by gatsby-recipes@0.1.49
npm ERR! missing: minimist@^0.2.0, required by hicat@0.7.0
npm ERR! missing: acorn@^7.1.1, required by espree@6.2.1
npm ERR! missing: xstate@^4.11.0, required by gatsby-source-filesystem@2.3.18
npm ERR! peer dep missing: react-dropzone@10.2.1, required by react-tinacms-inline@0.10.1
npm ERR! peer dep missing: react-final-form@^>=6, required by react-tinacms-inline@0.10.1
npm ERR! peer dep missing: prosemirror-tables@^0.9.1, required by prosemirror-utils@0.9.6
npm ERR! missing: acorn@^7.1.1, required by jsdom@16.2.2
npm ERR! missing: acorn@^7.1.1, required by acorn-globals@6.0.0
├─┬ gatsby-plugin-tinacms@0.2.5
│ └─┬ tinacms@0.22.1
│   ├── @tinacms/alerts@0.1.6
│   ├── @tinacms/core@0.10.1
│   ├─┬ @tinacms/fields@0.12.3
│   ├─┬ @tinacms/form-builder@0.3.8
│   ├─┬ @tinacms/forms@0.6.3
│   ├── @tinacms/icons@0.14.0
│   ├── @tinacms/media@0.1.0
│   ├── @tinacms/react-alerts@0.1.12
│   ├─┬ @tinacms/react-core@0.3.3
│   ├─┬ @tinacms/react-forms@0.2.3
│   ├── @tinacms/react-modals@0.1.12
│   ├── @tinacms/react-screens@0.1.11
│   ├─┬ @tinacms/react-sidebar@0.3.1
│   ├─┬ @tinacms/react-toolbar@0.3.1
│   ├─┬ @tinacms/styles@0.5.2
├─┬ gatsby-tinacms-git@0.5.7
│ ├─┬ @tinacms/api-git@0.7.0
│ └── @tinacms/git-client@0.6.7
├─┬ gatsby-tinacms-json@0.8.31
├─┬ gatsby-tinacms-remark@0.8.6
│ ├─┬ react-tinacms-editor@0.8.4
│ ├─┬ react-tinacms-inline@0.10.1
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |    12.15.0     |
| npm     |   6.13.4      |
| yarn |   1.22.4     |

**Comment by raulfdm** [comment]
Maybe related to https://github.com/tinacms/tinacms/issues/744

**Comment by ncphillips** [comment]
Hey @raulfdm sorry, you should instead use the new top-level `enabled` flag:
```
{
  resolve: "gatsby-plugin-tinacms", 
  options: {
    enabled: process.env.NODE_ENV !== "production"
    sidebar: {
      ...
    }
  }
}

**Comment by raulfdm** [comment]
Ah.... I didn't find reference for that in the Docs.

Do you want to keep this PR open as reference? Want some help to upgrading README there?

**Comment by raulfdm** [comment]
@ncphillips I notice that even passing enable: false, it does not show the bar but the code seems being injected anyways. Is that right?

![image](https://user-images.githubusercontent.com/12464600/87467968-12cb0b00-c619-11ea-97c9-57fe919eb37d.png)

**Comment by kendallstrautman** [comment]
Hey @raulfdm, we post release notes in the blog. You can checkout the [notes regarding this change](https://tinacms.org/blog/2020-06-29-release-notes#tinacms-) and the documentation with that [newer enabling the user interface documentation](https://tinacms.org/docs/cms/ui#enabling-the-user-interface).

As you noticed, when disabled, the CMS isn't completely removed from the codebase, but there are some things that cant help reduce bundle size — [optionally loading editors](https://tinacms.org/blog/2020-05-19-release-notes#deprecation) & [the date field](https://tinacms.org/blog/2020-06-29-release-notes#react-tinacms-date-) for one. And there is more discussion here on [cutting down](https://github.com/tinacms/tinacms/issues/771) production overhead.

**Comment by raulfdm** [comment]
Thanks for the feedback @kendallstrautman
