### ISSUE TITLE
withTina 

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#1328]
## Description

The withTina higher-order component uses old defaults when it creates a new CMS object.

### Steps to reproduce

Use withTina with no provided config and it will default to showing the sidebar.

### Expected result

The sidebar should be hidden by default.

### Actual result

The sidebar is visible.

**Comment by spbyrne** [comment]
[This is fixed here.](https://github.com/tinacms/tinacms/commit/9885271a994b9ed77f2beb9df8570dd1698c9ab0)

**Comment by kendallstrautman** [comment]
Confirmed this works on master 👌
