### ISSUE TITLE
react-tinacms-github: GithubErrorModal breaks if github.getBranch throws an error

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#1335]
## Problem Rendering the Modal

The blow up is actually coming from **getModalProps** though. The reason is that it unsafely calls `GithubClient#getBranch` (i.e. it doesn't wrap it in a try-catch)

<img width="478" alt="image" src="https://user-images.githubusercontent.com/824015/87675549-e4028100-c74d-11ea-8350-52841f87017c.png">

`GithubClient#getBranch` is a little funky because it doesn't throw for 404's but it does throw for everything else. This doesn't make sense to me and there's no comment explaining why. 

<img width="785" alt="image" src="https://user-images.githubusercontent.com/824015/87675676-101e0200-c74e-11ea-91d6-e05013a175d9.png">

The safest thing to do is to just put the try-catch in `getModalProps` but we should also investigate removing the inconsistent behaviour in `getBranch`.

_Originally posted by @ncphillips in https://github.com/tinacms/tinacms/issues/1333#issuecomment-659408283_

**Comment by kendallstrautman** [comment]
@logan-anderson was this fixed?

**Comment by kendallstrautman** [comment]
Seems like it was addressed in [this pr](https://github.com/tinacms/tinacms/pull/1400), closing. Feel free to reopen if this isn't the case.

**Comment by ncphillips** [comment]
Sorry, this is a bit different. The 404 issue is fixed, the issue here is that the switch statement doesn't safely call `getBranch`. The result is the error gets thrown and the modal doesn't pop up.
