### ISSUE TITLE
Improve UX of working with multiple forms & toolbar

### ISSUE THREAD

**Issue by grncdr** [tinacms/tinacms#1340]
## Summary

The toolbar should reflect the state of _all_ loaded forms, and clicking the save/reset buttons should save or reset all forms.

### Motivation

I am frequently using multiple forms to enable editing content from multiple files used by a single page (e.g. page-specific content from one file, application messages from another). I am enabling *both* of these uses with inline forms/editing components.

Currently (with release 0.24) the toolbar only seems to interact with the last form to be registered. In my case this is usually an "app layout" form. Therefore changes to data in the other forms do not reflect in the toolbar and clicking the save/reset buttons does anything. An editing user has to open the sidebar, figure out which form needs saving, navigate to it, and then click save in the sidebar. This can be pretty annoying, and is the only reason I need the sidebar enabled for one project.

Edit: I previously said it was the first form registered above, but it appears to be the last form.

**Comment by kendallstrautman** [comment]
Related to #1365
