### ISSUE TITLE
GitHub: On branch deletion

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1353]
## Description

Stuck on a deleted branch after a PR is merged and the working branch has been deleted.

### Steps to reproduce

```gherkin
Given I'm connected to GitHub to work on a branch
When that branch gets deleted from the origin repository
Then I get a "fork needed" modal
```

### Expected result

Branch "feat/work" has been deleted from the remote origin, switching you to the default master branch.

### Actual result

Dialog modal until you clear the browser cookies for the edited site.

#### Tinacms Package Versions

updated to v0.28.0

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |    Firefox   |
| os      |     macOS    |

**Comment by ncphillips** [comment]
I would add that there is a second bug here: when a branch is deleted it tells you there's no fork, when really there is no branch

**Comment by DirtyF** [comment]
On latest Tina, I'm now getting a switch to branch modal but it does not do anything and loops endlessly.
https://www.loom.com/share/dd4f3d64de28431ba777ef7e3f42d84e

**Comment by ncphillips** [comment]
Your base branch is set to `update-packages` but that doesn't exist in your repository.

**Comment by DirtyF** [comment]
Exactly, didn't remember I changed that 😊

**Comment by ncphillips** [comment]
Right now that modal only lets you switch to the base branch. Maybe good feature to explore would be making it so you can switch to any branch.

**Comment by DirtyF** [comment]
If the modal was to display a branch switcher instead (base branch would be the default choice), it could remove the need for an editor to rely on a developer. Looks likes an edge case.
