### ISSUE TITLE
Document node versions with "engine" field

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1355]
## Summary

You can get build errors if you don't use the right node version. NPM/Yarn can warn on this if it's specified in package.json.

https://docs.npmjs.com/files/package.json#engines

### Basic example

N/A
### Motivation

Reduce any need for support related to this issue.

### What we know

| Node Version | Works |
| --- | --- |
| v10.18.1| ✅ |
| v12.16.1 | ✅ |
| v12.18.3 |  ✅|

**Comment by ncphillips** [comment]
I have no idea what versions do and do not work. If anyone would like to contribute by investigating this it would be greatly appreciated 👍

**Comment by DirtyF** [comment]
node v12.16.1 ✅ 
node v12.18.3 ✅ 

I can test with node v14 if that helps.

**Comment by chrisdmacrae** [comment]
@ncphillips @DirtyF why don’t we quickly add a node js actions build that runs a matrix of all node LTS and release versions, and put a badge on the readme?

This way we document what we support, in real time.

**Comment by ncphillips** [comment]
Both of those passed. Did you have a version that didn't work @chrisdmacrae?

**Comment by chrisdmacrae** [comment]
@ncphillips I was on current (14.x.x)
