### ISSUE TITLE
Toolbar save button doesn't work with multiple forms

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#1365]
## Description

When using the toolbar and having more then one form on the page the toolbar save button only works with the first form on the page

### Steps to reproduce

clone my repo 
```
git clone git@github.com:logan-anderson/cra-hosted-demo.git
git checkout bug/multiple-forms
yarn
yarn start
```

see the toolbar save button only works with the first form registered

[see loom here](https://www.loom.com/share/c797edcba7004d0ba9d90fe6b689b295)
### Expected result

The save button should work with the forms on the page

### Actual result

only saves the first form

#### Tinacms Package Versions

```text
├─┬ react-tinacms-inline@0.8.0
├─┬ tinacms@0.21.2
│ ├── @tinacms/alerts@0.1.4
│ ├── @tinacms/core@0.9.0
│ ├─┬ @tinacms/fields@0.12.0
│ ├─┬ @tinacms/form-builder@0.3.5
│ ├─┬ @tinacms/forms@0.6.0
│ ├── @tinacms/icons@0.14.0
│ ├── @tinacms/media@0.1.0
│ ├── @tinacms/react-alerts@0.1.9
│ ├─┬ @tinacms/react-core@0.3.0
│ ├─┬ @tinacms/react-forms@0.2.0
│ ├── @tinacms/react-modals@0.1.9
│ ├── @tinacms/react-screens@0.1.8
│ ├─┬ @tinacms/react-sidebar@0.2.0
│ ├─┬ @tinacms/react-toolbar@0.2.0
│ ├─┬ @tinacms/styles@0.5.1
```

[Looking at the code for the toolbar plugin it seems that this is happing on purpose](https://github.com/tinacms/tinacms/blob/ee547b732a56d0ad49197f70075028fe9dd7fa6f/packages/%40tinacms/react-toolbar/src/components/Toolbar.tsx#L56)

**Comment by BaggioGiacomo** [comment]
Same problem here

**Comment by logan-anderson** [comment]
Not relevant since we are not using the toolbar anymore.
