### ISSUE TITLE
@tinacms/git-client: `undefined` on upload when image already exists.

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1381]
When you upload an image that already exists, you get `undefined`.

Demo:
https://www.loom.com/share/98717e9589a64689908402a685e6ed30

Expected: 
Warn that an image with the same name already exists before the upload

_Originally posted by @DirtyF in https://github.com/tinacms/tinacms/pull/1380#issuecomment-670554912_

**Comment by ncphillips** [comment]
I'm guessing this is specific to `@tinacms/git-client` rather then a general `react-tinacms-editor` bug

**Comment by dwalkr** [comment]
We had issues around overwriting images before: https://github.com/tinacms/tinacms/issues/1250

couple of things to check:

1. using the latest release of `react-tinacms-github`
2. devtools network tab: check the result of the upload request and see if it's returning `409 conflict` or something else

**Comment by BaggioGiacomo** [comment]
Same problem here.
