### ISSUE TITLE
File system only backend

### ISSUE THREAD

**Issue by divyenduz** [tinacms/tinacms#1382]
## Summary

Is there already a file-system only backend? Raising this as a feature request but maybe it is already possible. I couldn't find it in docs/issues.

Related https://github.com/tinacms/tinacms/issues/420

### Basic example

The behavior I am looking for is: 

1. Changing the content doesn't write to the file system
2. Clicking "Save" in toolbar writes to the file system

This can be an option in the git backend (by disabling auto-writing to the file system and adding a new toolbar button "write" instead of commit)

Or it can be a separate backend. 

### Motivation

It is a subset of the git client API but it is the workflow that I prefer. I was working on a project to enable this before I ran into TinaCMS https://github.com/divyenduz/offline-cms :)

**Comment by ncphillips** [comment]
Hey @divyenduz that's really cool! We have no plans to make a file-system only backend, but if you setup a little Node REST server you could make your own backend + client pretty easily I bet!
