### ISSUE TITLE
Upload Images To Cloudinary/Imgix

### ISSUE THREAD

**Issue by pxwee5** [tinacms/tinacms#1383]
## Summary

A lot of static hosting have employed the use of cloudinary to optimise images. Can we support these in TinaCMS during image upload ?

### Motivation

For the better web.

**Comment by ncphillips** [comment]
A new [MediaStore](https://tinacms.org/docs/media#media-store) for Cloudinary could definitely be created! We love Cloudinary and would love to make one but there's no plans for it so far.

**Comment by PaulPCIO** [comment]
I would also love to see cloudinary media store 🤩

**Comment by ncphillips** [comment]
Update: We've started streaming TinaCMS development on Twitch. The project we're currently working on is a Cloudinary Media Store. It's not ready for primetime but you can checkout the prototype here:

https://github.com/tinalabs/media-manager-prototype/tree/d232ee3c53be85e4cf04f81e59c46cf668830e8a/next-tinacms-cloudinary
