### ISSUE TITLE
react-tinacms-editor: pressing ENTER in link modal should act as "save"

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#1387]
* Open the Editor
* Select some text and press the "link" button in the menu –> Modal Opens
* Fill in the URL
* Press ENTER –> Modal Closes
* Click on the link –> Modal opens
* The URL will be empty

<img width="336" alt="image" src="https://user-images.githubusercontent.com/824015/89892353-e6b99000-dbac-11ea-916b-da04e7166801.png">

**Comment by daho-turner** [comment]
+1

**Comment by DirtyF** [comment]
@ncphillips I can't reproduce it on tinacms.org. I will do more tests, as I stumbled upon this one when using a second wysiwyg field while testing #1392

**Comment by ncphillips** [comment]
Yeah I think it was fixed 👍

**Comment by ncphillips** [comment]
WOops

**Comment by ncphillips** [comment]
Okay, I can't reproduce on master anymore. Did you make sure to build react-tinacms-editor @DirtyF?

**Comment by DirtyF** [comment]
@ncphillips yes I did.

**Comment by andrewfader** [comment]
+1

**Comment by andrewfader** [comment]
Has this been fixed?

**Comment by jamespohalloran** [comment]
The react-tinacms-inline package is no longer being maintained as TinaCMS has shifted away from inline editing for the time being. This is however not an issue with the sidebar editing.
