### ISSUE TITLE
Tina renders all inline blocks on change to any block

### ISSUE THREAD

**Issue by grncdr** [tinacms/tinacms#1394]
## Description

When using the inline blocks component, it appears that a change to any block will cause the entire array of blocks to be re-rendered. When combined with relatively heavy editing components (such as `InlineWysiwyg`) this makes editing slow enough to be unusable.

### Steps to reproduce

I've created a reproduction repo here: https://github.com/grncdr/tina-wysiwyg-performance The relevant code was just [added directly to App.js](https://github.com/grncdr/tina-wysiwyg-performance/blob/d5918a6799abf239ad38f37fd52f0a408fcc4a31/src/App.js#L24-L71). Clone it, run `yarn && yarn start` and try editing. You should see that the performance is quite bad, and gets worse as you add more fields.

### Expected result

Editing a field only re-renders that field.

### Actual result

Editing any field re-renders all fields.

#### Tinacms Package Versions

```text
├─┬ react-tinacms-editor@0.27.3
├─┬ react-tinacms-inline@0.27.3
└─┬ tinacms@0.27.1
  ├── @tinacms/alerts@0.26.0
  ├── @tinacms/core@0.26.0
  ├─┬ @tinacms/fields@0.27.1
  ├─┬ @tinacms/form-builder@0.26.0
  ├─┬ @tinacms/forms@0.26.0
  ├── @tinacms/icons@0.26.0
  ├── @tinacms/media@0.26.0
  ├── @tinacms/react-alerts@0.26.0
  ├─┬ @tinacms/react-core@0.26.0
  ├─┬ @tinacms/react-forms@0.27.1
  ├── @tinacms/react-modals@0.27.1
  ├── @tinacms/react-screens@0.27.1
  ├─┬ @tinacms/react-sidebar@0.27.1
  ├─┬ @tinacms/react-toolbar@0.27.1
  ├─┬ @tinacms/styles@0.26.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Firefox, Safari, and Chrome, all latest stable versions.        |
| os      |  OS X       |

**Comment by ncphillips** [comment]
Thanks for the report @grncdr!

I started digging into and took some notes during the process which I've documented in the above issue.

**Comment by dwalkr** [comment]
Thanks for the reproduction @grncdr !

I just tested it against #1572 and determined that 611fc70eaba95168db9531f35d283d69dfe56e05 fixes the issue for the `InlineText` field, but not the `InlineWysiwyg`. I'll keep digging to see if there are any easy optimizations we can make for `InlineWysiwyg` to improve the situation.

**Comment by dwalkr** [comment]
The performance improvements introduced by #1613 have mitigated the slowdown in the demo site you've provided. There are still scenarios where parts of the inline blocks stack are rerendering when it seems like they shouldn't, but the impact on performance is significantly reduced.

Performance is going to be a continuously moving target. Our work on this front isn't done, but the inline experience is improved enough that I think this issue can be closed.

We're still testing the improvements, but they will be bundled in our next release. If you want to try them out early, the prerelease can be installed via the `next` channel:

```
yarn add react-tinacms-inline@next react-tinacms-editor@next
```
