### ISSUE TITLE
Performance issues with Wysiwyg

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#1398]
## Description

While investigating #1394 I found that I could only reproduce the issue when the wysiwyg was on the page. Digging around revealed that the InlineBlocks definitely hurt, but only when the wysiwyg is also on the page. It seems that the Wysiwyg alone has some performance problems that get exacerbated as more things are added to the page.

## Testing

- https://localhost:3000/editor for an isolated editor. The issue is barely noticeable here
- https://localhost:3000/nesting for an editor inside of nested blocks. The issue is extremely noticeable here.

## Nolan's Lab Notes

Here are my "lab notes" taken while troubleshooting

- I confirmed that it's not a result of re-mounting of the editor or any other component.
- I checked if the useEffect that builds the EditorState is a bit too eager, but it seems fine.
- I notice that the wysiwyg menu keeps appearing and disappearing while I type. An unrelated bug. 
- I tried going to try memoing the `pluginList` in the root `Wysiwyg`, but no luck.
- The Firefox devetools performance monitor. The Waterfall view makes it looks like there's a function getting called that's doing the dirt. I can't tell what function it is though.
- I tried changing the BrowserFocus value to just be a boolean instead of an object, but that did not help
- I tried removing the menu bar and no improvement
- **Okay, this isn't specifically a blocks issue. A wysiwyg at the root also has problems.**  
- If I remove everything except the root wysiwyg it doesn't cause problems.
- If I gradually add more items to the page it gradually gets worse. Once I a second wysiwyg is added it gets really bad.
- **Made an /editor page for the `demo-next`**
- The Firefox Dev Tools shows a function in the Prosemirror editor that takes more time to work. It seems like it's related to some kind of DOM observation.
  <img width="790" alt="image" src="https://user-images.githubusercontent.com/824015/90024936-d9bf9e00-dc8b-11ea-8fee-fd74ea0984b9.png">
- There's [a post in the Prosemirror forum](https://discuss.prosemirror.net/t/keyboard-input-lagging-delay-slow-performance/1706/5) that suggest this might have something to do with a prosemirror plugin's state, so I tried disabling extra plugins (i.e. inline, link, tableEditing, table, image, codeBlock) but that did not improve the framerate.
- For reference, here is the framerate graph. The sharp drop is where I start typing quickly.
  <img width="548" alt="image" src="https://user-images.githubusercontent.com/824015/90027067-7be08580-dc8e-11ea-9209-31221e9f121b.png">
- I was wondering if this happens in the sidebar as well. It could be a inline specific issue, but I just want to make sure. That framerate drop happens whether in the sidebar or with inline editing.

Taking a break for now

**Comment by ncphillips** [comment]
This is likely also related to #1368

**Comment by ncphillips** [comment]
cc: @jpuri

**Comment by grncdr** [comment]
Hey @ncphillips thanks so much for looking into this ❤️ 

> I was wondering if this happens in the sidebar as well. It could be a inline specific issue, but I just want to make sure. That framerate drop happens whether in the sidebar or with inline editing.

I didn't mention it in #1394, but it does happen when typing in the sidebar in my "real app". In fact the entire sidebar seems to re-render on every key press.

**Comment by ncphillips** [comment]
Thanks @grncdr! Rerendering isn't necessarily a problem. React is efficient at figuring out that there doesn't need to be any DOM updates for a component. I feel pretty good about this because with paintflashing turned on the sidebar does not get updated, only the wysiwyg area. We could maybe optimize rendering further, but since the performance issues don't show up with regular text fields and it does show up without the sidebar I don't think that's the constraint on performance right now.

**Comment by grncdr** [comment]
> Rerendering isn't necessarily a problem. React is efficient at figuring out that there doesn't need to be any DOM updates for a component.

I get this, but I _think_ that there's enough work happening during the rendering that it is a problem. First a disclaimer: I am not an expert user of the React devtools, so I may be misinterpreting my observations. That said, this is what I see:

## Steps to reproduce

- Launch the reproduction app from #1394.
- Start the React devtools profiler
- Type a character in the first wysiwyg
- Stop the profiler
- Select the slow commit (it's pretty obvious what one it is).

## Results

As far as I understand this is telling me that `InlineBlocks` is taking 136ms to _render_ and that the time is pretty evenly split between each `InlineBlock`:

![Bildschirmfoto 2020-08-13 um 10 00 28](https://user-images.githubusercontent.com/82634/90109245-d390f680-dd4b-11ea-8594-2c82b3b7416a.png)

Each of those `InlineBlock ...` stacks goes quite a bit deeper as well. This is the render stack for the block that received input:

![Bildschirmfoto 2020-08-13 um 10 02 39](https://user-images.githubusercontent.com/82634/90109444-210d6380-dd4c-11ea-8904-bc38d7c1123e.png)

So 27ms is pretty bad, but IMO it's a lot worse that _every other block_ is also taking 10-17ms:

![Bildschirmfoto 2020-08-13 um 10 04 34](https://user-images.githubusercontent.com/82634/90109641-65006880-dd4c-11ea-8321-6ad7bdf5879e.png)

It should (theoretically) be possible to skip this work entirely, since nothing about these blocks has changed.

--

It seems there are two performance issues:

1. Wysiwyg takes too long to rerender (this issue)
2. It's rerendering too frequently (#1394), which multiplies problem 1.

IMO the redundant renders are a bigger win, because it's going to reduce the impact of any single slow block component. Keep in mind that users might write terribly slow block components themselves (I certainly have a couple 😬).

**Comment by cleitonper** [comment]
I'm facing the same issue here. In the past, I related a performance issue with text editor in the #1089. I thought this issue was caused by editing files, but this was not the real problem.

Thanks so much for looking into this. Solving this will make tina even better.

**Comment by jpuri** [comment]
@ncphillips : I need to debug this more, is this issue reproducible in demo projects ?

Improper use of wysiwyg component can also actually hurt performance, in case it causes too many react re-rendering cycles, that in turn may cause lot of prosemirror state calculation and other complex calculation in wysiwyg like modal / toolbar position calculation etc.

**Comment by ncphillips** [comment]
Yup. I was testing on demo-next mostly. Read through the notes I checked a bunch of things. There is a DOM observer somewhere that may be the main blocker.

I also dug into trying to reduce the rendering of InlineBlocks but had a negligible effect on frame rate drop that happens when you start typing. Besides, it also happens in the sidebar which does not rerender much while typing and it's still noticeable.

> too many react re-rendering cycles, that in turn may cause lot of prosemirror state calculation and other complex calculation in wysiwyg like modal / toolbar position calculation etc.

The wysiwyg does a great job of not recalculating state unnecessarily so I don't think that's the cause. Also note that it _only_ happens when typing in the wysiwyg. Typing in other inputs, even with the wysiwyg on page, does not cause the frame rate drop.

> modal / toolbar position calculation etc.

I don't think those are the problems but it's definitely worth checking again. I removed all prosemirror plugins and stopped rendering the menu but the frame rate still dropped while typing.

**Comment by grncdr** [comment]
> Also note that it only happens when typing in the wysiwyg.

I just checked and I definitely get a slowdown (not as big, but still noticeable) when typing in the InlineText inputs from my demo project.

**Comment by jpuri** [comment]
A re-render or re-init of editor can cause expensive operations like again making editor state from input string. This can cause whole lot of heavy calculations in turn.

In my experience with editors react re-rendering cycles if not managed properly can cause visible performance impacts.

Typing or editor state change does triggers re-rendering in parts of editor like menu, react does minimal DOM diffing but state change in so many component (like menu) on each letter typed can become expensive.

**Comment by ncphillips** [comment]
> A re-render or re-init of editor can cause expensive operations like again making editor state from input string. This can cause whole lot of heavy calculations in turn.

Right but there's no re-mounting happening and you wrapped those expensive operations in `useEffect` hooks that don't run when the editor has focus. I am pretty sure the prosemirror state is _not_ being needlessly regenerated.

> Typing or editor state change does triggers re-rendering in parts of editor like menu,

It does but when I removed the `<Menu>` component entirely and it didn't really help.

**Comment by jpuri** [comment]
@ncphillips : I actually need to spend time debugging this issue to be able to pin point what is messing up.

In past I have faced issues with editors many times where improper state mgt. and re-rendering cycles slow it down. It is evident from fact that slowdown happens on which typing - there is something that these keydown events are trigerring.

I will catchup with @DirtyF and prioritise some of these tasks required to be done for editor.

**Comment by chrisdmacrae** [comment]
To add to this, I’m playing around with many wysiwigs on a page [here] (https://staging.chrisdmacrae.com/articles/2020-08-24-first-post), and ezperience:

- performance degradation with each new wysiwyg
- weird typing behaviours with subsequent wysiwygs after the first, such as space bar not working
