### ISSUE TITLE
Have all dependencies of @tinacms/scripts bundled with the package, allowing it to be used for third-party plugin dev

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1399]
## Summary

I don't want to use TSDX for plugin dev, I'd like to use `@tinacms/scripts` to get the same experience as deving for Tina Core.

### Basic example

```
npm i @tinacms/scripts
```

Then, in `package.json`:

```
{
  "scripts": {
    "start": "npm run dev:watch",
    "build": "npx tinacms-scripts build",
    "dev": "npx tinacms-scripts dev",
    "dev:watch": "npx tinacms-scripts watch",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "@tinacms/scripts": "^0.26.0",
    "@types/react": "^16.9.46"
  }
}
```

### Motivation

We'd like `@tinacms/scripts` to be the official way of building Tina plugins.

**Comment by ncphillips** [comment]
Are you sure it doesn't work already?

What dependencies aren't bundled?

**Comment by chrisdmacrae** [comment]
@ncphillips all of the rollup deps.

It works, but you have to install each and every one.
