### ISSUE TITLE
Wysiwym / Inline Blocks: UI z-index issues

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#1406]
## Description

The add block button overlaps the Wysiwym media modal. There may be more instances of this with other UI.

<img width="770" alt="Screen Shot 2020-08-12 at 2 27 18 PM" src="https://user-images.githubusercontent.com/36613477/90070241-64ae9180-dca8-11ea-9f55-eb58aea935d4.png">

### Steps to reproduce

Checkout a blog on `demo-gatsby`, click the media attachment icon and scroll when the add block button is active.

### Expected result

Whatever was most recently interacted with should be 'on top'

### Actual result

An arbitrary z-index is being applied.

**Comment by kendallstrautman** [comment]
Related but I don't think fixes the above issue — https://github.com/tinacms/tinacms/pull/1627

**Comment by kendallstrautman** [comment]
Another example 
<img width="610" alt="Screen Shot 2020-11-19 at 11 00 33 AM" src="https://user-images.githubusercontent.com/36613477/101675587-dad0c400-3a0e-11eb-93e8-7839585b1c89.png">

**Comment by DirtyF** [comment]
When editing a link in the WYSIWYG

<img width="458" alt="Capture d’écran 2020-12-15 à 19 29 24" src="https://user-images.githubusercontent.com/103008/102279760-3c6fc180-3f2c-11eb-84c7-b338a6630702.png">
