### ISSUE TITLE
react-tinacms-editor: TypeError: imagePluginState is undefined 

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1408]
## Description

Given I run the next-demo locally on the `master` branch
When I select some text
Then I get a TypeScript error about `imagePlugin` State

Demo: https://www.loom.com/share/6380a04a1b8a497ab5c9b6ff0bf1e89c

### Expected result

I can use the nextJS demo to test wysiwyg.

#### Tinacms Package Versions

```text
├── UNMET DEPENDENCY @tinacms/api-git@0.5.3
├── UNMET DEPENDENCY @tinacms/form-builder@^0.28.0-alpha.0
├── UNMET DEPENDENCY @tinacms/git-client@0.4.1
├── UNMET DEPENDENCY @tinacms/styles@^0.26.0
├── UNMET DEPENDENCY next-tinacms-json@0.1.2
├── UNMET DEPENDENCY next-tinacms-markdown@0.1.0-canary.2441
├── UNMET DEPENDENCY react-tinacms-editor@^0.28.0-alpha.0
├── UNMET DEPENDENCY react-tinacms-inline@^0.28.0-alpha.0
├── UNMET DEPENDENCY tinacms@^0.28.0-alpha.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |     Firefox    |
| os      |    macOS 10.15.6     |
| node    |     v12.18   |
| npm     |       v6.14  |

**Comment by ncphillips** [comment]
Good catch @DirtyF 

Sidenote: there's no need to do the package versions when you're running the demos in the `tinacms` codebase, just the branch name
