### ISSUE TITLE
gastby-tinacms-git: form becomes dirty after first reset

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1410]
## Description

Why do I need to click on reset changes twice when I want to revert the change I just made?

### Steps to reproduce

Demo: https://www.loom.com/share/d14849c21bdc43aaa343ebe91ceaaad7

### Expected result

I thought reset changes would reset the current state of the form.

### Actual result

Had to click twice to get the initial state

#### Tinacms Package Versions

```text
tinacms/packages/demo-gatsby on master [$!] is 📦 v0.28.0-alpha.0
```

**Comment by mitchmac** [comment]
Going to close this issue because using Gatsby with this approach is no longer recommended.
