### ISSUE TITLE
Allow wysiwyg/wysiwym buttons to be configured

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1424]
## Summary

I want to be able to disable and hide the buttons in the toolbar to make it not possible to add some formatting. 

### Basic example

Add a “controls” prop/option that:

- expects a list of enabled buttons/controls

### Motivation

Allow basic formatting for paragraphs that I wish to have formatting, but not many lines.

**Comment by kendallstrautman** [comment]
Duplicate of #690?

**Comment by chrisdmacrae** [comment]
@kendallstrautman yup, didn’t see this. 

I’m planning out a block based editor for one of our clients, and would like to restrict what they can do in their rich text blocks.

**Comment by kendallstrautman** [comment]
Makes sense! 👍

**Comment by chrisdmacrae** [comment]
@kendallstrautman closing this, as it’s now referenced in #690
