### ISSUE TITLE
Support accessing the prose mirror schema instead of HTML/markdown

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1425]
## Summary

I want to write a portable text parser for the wysiwym. 

### Basic example

Add an experimental API to the wysiwym with format “custom” and an input and output option that each take a function that respectively receives the input data and expects the return of a proawmirror schema, and receives the prosemirror schema and allows you to output your own document format.  

### Motivation

This will make the wysiwym open to extension but not modification, allowing more formats to be used with it.

**Comment by ncphillips** [comment]
I updated the name of this issue to better reflect how the editor works.

- [Editor Docs](https://github.com/tinacms/tinacms/tree/master/packages/react-tinacms-editor/editor-docs)
- [Translator Abstract Class](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-editor/src/translator/TranslatorClass.ts#L21-L24)
