### ISSUE TITLE
react-tinacms-inline 0.28.0 breaks image previews in edit mode

### ISSUE THREAD

**Issue by martaver** [tinacms/tinacms#1433]
## Description

I have a nextjs app using tinacms to edit cms content.

I've set up a strapi back-end and am adapting the steps found at https://tinacms.org/guides/nextjs/tina-with-strapi/overview/.

Updating to the latest (0.28.0) version of `tinacms`, `react-tinacms-editor`, `react-tinacms-editor` and `react-tinacms-strapi` causes an error to appear when editing the blog in the guide:

![image](https://user-images.githubusercontent.com/6123570/91151891-ebab3300-e6c6-11ea-82e1-8709814d4e83.png)

### Steps to reproduce

You can refer to the associated demo repo as a reproduction: https://github.com/mittonface/tina-strapi-blog

(assuming a configured strapi backend as per the guide)
Update all tinacms related packages to 0.28.0 and run the app.
Go to edit a blog post, and while logging in to strapi back-end...
The error should appear.

Downgrading react-tinacms-inline to 0.27.3 makes the error message stop appearing.

### Expected result

Should work with latest version no errors :)

### Actual result

Error appears.

**Comment by kendallstrautman** [comment]
Hey @martaver, [this pr](https://github.com/tinacms/tinacms/pull/1429) should fix that issue. It should be out in next week's release!

**Comment by ncphillips** [comment]
I think that was released this week in 0.29

**Comment by kendallstrautman** [comment]
Closing for now, reopen if the issue persists in the latest release.
