### ISSUE TITLE
Allow configure inline wysiwym to only display toolbar when focused

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1434]
## Summary

I have a ton of individual WYSIWYG's on my page. It looks objectively bad. I would like the toolbars to only show when my cursor is focused in the wysiwyg.

### Basic example

<img width="1294" alt="Screen Shot 2020-08-27 at 1 07 24 AM" src="https://user-images.githubusercontent.com/6855186/91383181-e1418400-e801-11ea-8b12-33c230c0320d.png">
### Motivation

The above not looking silly.

**Comment by chrisdmacrae** [comment]
For better reference, check out: https://staging.chrisdmacrae.com/articles/2020-08-24-first-post

**Comment by DirtyF** [comment]
@chrisdmacrae This should be fixed by #1613

**Comment by chrisdmacrae** [comment]
@DirtyF @dwalkr does #1613 improve the rendering of WYSIWYMs, or make the toolbar conditionally render altogether?

**Comment by DirtyF** [comment]
@chrisdmacrae the toolbar is only rendered when you are editing the inline wysiwyg field
