### ISSUE TITLE
next-tinacms-github: Default the selected branch in GitHub client to local branch during local development

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1435]
## Summary

The GitHub plugins default to master in prod, but locally, you end up forgetting to switch branches between changes, and end up trying to commit to prod.

This is bad.

### Basic example

Read the current git branch when `process.env.NODE_ENV !== "production"`, and if successful, use that instead. We'll likely need end-users to pass this in via bundler injection, or something.

### Motivation

Not accidentally committing to master!

**Comment by ncphillips** [comment]
Although I added the `next-tinacms-github` prefix I suspect this is a documentation issue. 

My first thought would be to suggest using `simple-git` to set `process.env.BASE_BRANCH`

**Comment by ncphillips** [comment]
Add this to your `next-config.js`
```js
const branch = require("child_process")
  .execSync("git rev-parse --abbrev-ref HEAD")
  .toString()
  .trim()

const config = {
  env: {
    GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
    REPO_FULL_NAME: process.env.REPO_FULL_NAME,
    BASE_BRANCH: branch,
  },

**Comment by ncphillips** [comment]
This doesn't quite work. You need to clear cookies between sessions. 

So yes, this is how you will dynamically set the branch at startup time, but there's an unrelated cookies issue to be dealt with. 


>Not accidentally committing to master!

An alternative solution to this could be to lock master. That's what we do on tinacms.org

Unfortunately that may require a paid GitHub org

**Comment by chrisdmacrae** [comment]
@ncphillips that works — the cookie issue doesn’t seem to be a problem, as in most cases you’re killing the dev server and starting a whole new session anyway. 

This would make a great blog post. I’m adding a label for issues that are resolved through documentation and are a candidate for blogs.
