### ISSUE TITLE
Tina needs a bunch of peer dependencies

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1437]
## Description

Since last week's release of Tina, I have to install a bunch of peer dependencies I didn't have to install before.

For example, I need to install `@tinacms/react-forms` and `@tinacms/react-modals`.

### Steps to reproduce

Just install the latest TinaCMS version in a previously working project, and then try and build.

### Expected result

It should just work?

### Actual result

It failed on dependencies.

#### Tinacms Package Versions

```text
├── UNMET PEER DEPENDENCY @tinacms/forms@>=0.3
├── @tinacms/icons@0.24.0
├── UNMET PEER DEPENDENCY @tinacms/react-core@>=0.2
├─┬ @tinacms/react-forms@0.29.0
│ ├─┬ @tinacms/form-builder@0.29.0
│ │ ├─┬ @tinacms/forms@0.29.0
│ │ ├─┬ @tinacms/react-core@0.29.0
│ │ │ ├── @tinacms/core@0.29.0
├── @tinacms/react-modals@0.29.0
├── UNMET PEER DEPENDENCY @tinacms/styles@>=0.3
├── UNMET PEER DEPENDENCY react-tinacms-editor@>=0.0
├─┬ react-tinacms-inline@0.24.0
├─┬ tinacms@0.24.0
│ ├── @tinacms/alerts@0.24.0
│ ├── @tinacms/core@0.24.0
│ ├─┬ @tinacms/fields@0.24.0
│ ├─┬ @tinacms/form-builder@0.24.0
│ ├─┬ @tinacms/forms@0.24.0
│ ├── @tinacms/icons@0.24.0
│ ├── @tinacms/media@0.24.0
│ ├── @tinacms/react-alerts@0.24.0
│ ├─┬ @tinacms/react-core@0.24.0
│ ├─┬ @tinacms/react-forms@0.24.0
│ ├── @tinacms/react-modals@0.24.0
│ ├── @tinacms/react-screens@0.24.0
│ ├─┬ @tinacms/react-sidebar@0.24.0
│ ├─┬ @tinacms/react-toolbar@0.24.0
│ ├─┬ @tinacms/styles@0.24.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Safari      |
| os      |    MacOS     |
| node    |    LTS     |
| npm     |     LTS    |
| tina | 0.24.0 |

Related #1360

**Comment by chrisdmacrae** [comment]
I also needed to install `react-beautiful-dnd` myself.

**Comment by ncphillips** [comment]
Is the issue that you actually _needed_ to install them or just that NPM was complaining in the console?

**Comment by chrisdmacrae** [comment]
@ncphillips my build failed on all of the missing unmet peer deps listed above, and they didn't seem to install their dependencies either when I installed them.

**Comment by patrickconroy** [comment]
Hello just checking if there's a solution for this? A project using tina shouldn't have to install this stuff.

**Comment by DirtyF** [comment]
Hi Patrick, when installing Tina, you only have to install the `tinacms` package by default. Did you run into any dependency issue while upgrading? We changed some stuff since this was posted.
