### ISSUE TITLE
react-tinacms-editor depends on unlisted dependency react-tinacms-inline

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#1442]
`react-tinacms-editor` depends on `react-tinacms-inline` because it contains `InlineWysiwyg`, but `react-tinacms-inline` is not automatically installed when installing `react-tinacms-editor`.

I feel like either `react-tinacms-inline` should be a direct dependency of `react-tinacms-editor` or, perhaps, `react-tinacms-inline-editor` should be a standalone package that depends on both?

**Comment by ncphillips** [comment]
Is it totally unlisted? Another option is for it to just be a `peerDep`

**Comment by dwalkr** [comment]
it's listed as a dev dependency, but not a dep or peer dep. Sounds like the most straightforward, immediate fix is to just make it a peer dep
