### ISSUE TITLE
Add a common "backend-helpers" package with shared utils.

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#1445]
## Summary

Creating a new tinacms backend involves a bit of boilerplate that is commonly shared between packages. I think it's time to create a "base-backend" or "backend-helpers" package to make adding a new backend  (with auth) easier.

### Basic example

One example of this is creating a [popupWindow](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-github/src/github-client/popupWindow.ts)

Another could be properly [grabbing a token](https://github.com/tinacms/tinacms/issues/1444) from an auth window's callback.

### Motivation

Creating a new backend could be streamlined a bit. This may help encourage new Tinacms integrations (and clean up our codebase)

**Comment by chrisdmacrae** [comment]
Oath is a mess, so there is some things that we should consider OUT of scope:

- the workflow itself (we provide the legos to assemble the workflow, but we don't automate it)
- storing the token (let's not even considering taking this risk)
  - this includes http only cookies, localstorage, etc

The legos we should support to make all auth approaches feel consistent to end-users are:

- creating the popup
- creating the auth modal
- post messaging between popup and parent window
- PKCE secret generation
- creating the `authorize` endpoint page (`useWhateverAuthRedirect`) helper
