### ISSUE TITLE
Editor gets out of sync when editing a link

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1447]
The editor gets out of sync when editing a link text in the sidebar, then when updating from the inline field the changes aren't reflected in the sidebar.

Tested on the Gatsby demo.

https://www.loom.com/share/156fbc969fc542279ac8c7daa819cbc7

**Comment by jpuri** [comment]
Hi @DirtyF : this does not seems to be issue with wysiwyg but rather the code that is syncing the state, sync is implemented correctly from sidebar to main editor, but it is broken the other way.
