### ISSUE TITLE
Creating new json files not committing to git ...

### ISSUE THREAD

**Issue by TorrinLynn** [tinacms/tinacms#1449]
## Description

When creating new Json files using JsonCreatorPlugin, the files are successfully created on the file system, but are not committed to my git repository (they're untracked) even though I have pushOnCommit set to true. If I edit and save the content using useJsonForm, the file is pushed to my git repo.

Looking at the source code for JsonCreatorPlugin, the onSubmit method is calling git onChange which only writes the file to disk and doesn't commit it.

### Steps to reproduce

1. Create a new Json plugin using JsonCreatorPlugin
2. Register the plugin using usePlugins
3. Enable pushOnCommit
4. Create a new Json file through TinaCMS

### Expected result

What should happen?

The newly created Json file should be added to git, committed, and pushed to my repo.

### Actual result

What actually happened?

The Json file is written to the file system, but is not added to git.

#### Tinacms Package Versions

```text
├─ @tinacms/alerts@0.29.0
├─ @tinacms/api-git@0.29.0
├─ @tinacms/core@0.29.0
├─ @tinacms/fields@0.29.0
├─ @tinacms/form-builder@0.29.0
│  ├─ @tinacms/forms@^0.29.0
│  ├─ @tinacms/react-core@^0.29.0
├─ @tinacms/forms@0.29.0
├─ @tinacms/git-client@0.29.0
├─ @tinacms/icons@0.29.0
├─ @tinacms/media@0.29.0
├─ @tinacms/react-alerts@0.29.0
├─ @tinacms/react-core@0.29.0
│  ├─ @tinacms/core@^0.29.0
│  └─ @tinacms/forms@^0.29.0
├─ @tinacms/react-forms@0.29.0
│  ├─ @tinacms/form-builder@^0.29.0
├─ @tinacms/react-modals@0.29.0
├─ @tinacms/react-screens@0.29.0
├─ @tinacms/react-sidebar@0.29.0
│  ├─ @tinacms/core@^0.29.0
│  ├─ @tinacms/forms@^0.29.0
├─ @tinacms/react-toolbar@0.29.0
│  ├─ @tinacms/core@^0.29.0
│  ├─ @tinacms/fields@^0.29.0
│  ├─ @tinacms/forms@^0.29.0
├─ @tinacms/styles@0.29.0
├─ gatsby-plugin-tinacms@0.29.0
│  └─ tinacms@^0.29.0
├─ gatsby-tinacms-git@0.29.0
│  ├─ @tinacms/api-git@^0.29.0
│  └─ @tinacms/git-client@^0.29.0
├─ gatsby-tinacms-json@0.29.0
├─ react-tinacms-date@0.29.0
├─ react-tinacms-editor@0.29.0
├─ react-tinacms-inline@0.29.0
├─ tinacms-relation-field@1.3.0
├─ tinacms@0.29.0
│  ├─ @tinacms/alerts@^0.29.0
│  ├─ @tinacms/core@^0.29.0
│  ├─ @tinacms/fields@^0.29.0
│  ├─ @tinacms/form-builder@^0.29.0
│  ├─ @tinacms/forms@^0.29.0
│  ├─ @tinacms/icons@^0.29.0
│  ├─ @tinacms/media@^0.29.0
│  ├─ @tinacms/react-alerts@^0.29.0
│  ├─ @tinacms/react-core@^0.29.0
│  ├─ @tinacms/react-forms@^0.29.0
│  ├─ @tinacms/react-modals@^0.29.0
│  ├─ @tinacms/react-screens@^0.29.0
│  ├─ @tinacms/react-sidebar@^0.29.0
│  ├─ @tinacms/react-toolbar@^0.29.0
│  ├─ @tinacms/styles@^0.29.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Safari, Firefox, Chrome - Latest      |
| os      |   macOS Catalina 10.15.6      |
| node    |  12.18.0       |
| yarn     | 1.22.4        |

**Comment by ncphillips** [comment]
Thanks for the heads up and the patience @TorrinLynn! 

I just opened a PR to fix this:

https://github.com/tinacms/tinacms/pull/1531
