### ISSUE TITLE
The GitMediaStore should implement the MediaStore#list method

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#1463]
### Summary
The `GitMediaStore#list` method currently just throws an error.

* Add a route to `@tinacms/api-git` for fetching a list of media.
* Implement `GitMediaStore#list` in `@tinacms/git-client` so it hits that endpoint. 
 
### Motivation

This is required for the GitMediaStore to work with the upcoming Media Manager GUI

**Comment by divyenduz** [comment]
Is there a reason why this one was closed? 🤔

**Comment by DirtyF** [comment]
It's implemented:
https://github.com/tinacms/tinacms/blob/7fc603828c29fb9967d3ff87775459e2c008aee9/packages/%40tinacms/git-client/src/git-media-store.ts#L59-L78
