### ISSUE TITLE
Specify Default or Initial Values

### ISSUE THREAD

**Issue by BjoernRave** [tinacms/tinacms#1492]
## Summary

I would like to be able to specify a default value for some fields, especially for the date field.

### Basic example

It could just be another key on the formOptions

### Motivation

I have a blog, with a creation time which the creator can select. By default it shows the current date, so the user assumes it picks that date up, but it doesnt actually do it. I would like to specify new Date() as default or initial value, so it takes the current date if the user doesnt specify otherwise

**Comment by DirtyF** [comment]
Hey, you should be able to set default values in a Creator plugin.

[Here's an example in the Gatsby demo](https://github.com/tinacms/tinacms/blob/master/packages/demo-gatsby/src/components/layout.js#L106-L133)
