### ISSUE TITLE
Update BlocksControls to receive the `name` of the blocks instance being rendered

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1533]
## Description

I'm using `useInlineBlocks` and `activeBlock` is always `-1`, but I _am_ getting the correct blocks instance. I'm assuming this value is just not getting set.

My use case is inside a custom `BlocksControls` component, I want to add some tooltips to the active block. I'm trying to do so by doing:

```
export function MyBlocksControlsTooltip(props: BlocksControlsProps) {
  const [isFocused, setIsFocused] = useState(true);
  const inlineForm = useInlineForm();
  const inlineBlocks = useInlineBlocks();

  if (props.index !== inlineBlocks.activeBlock) {
    return null;
  }

  return (
    <InlineField name={inlineForm.focussedField}>
      {({ input }) => {
        input.onFocus = (event) => { setIsFocused(true); input.onFocus(event); }
        input.onBlur = (event) => { setIsFocused(false); input.onBlur(event); }

        if (isFocused) {
          return <div>{input.name}</div>
        }

        return null;
      }}
    </InlineField>
  )
}
```

### Steps to reproduce

Use the above code block inside of a component using BlocksControls. See that `inlineBlocks.activeBlock` is always `-1` no matter how focus is working.

### Expected result

It should reflect the index of the active block.

### Actual result

`inlineBlocks.activeBlock` is always `-1` no matter how focus is working.

#### Tinacms Package Versions

```text

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by kendallstrautman** [comment]
Looks like the active block is only set when a [block is moved](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-inline/src/blocks/inline-field-blocks.tsx#L111).

**Comment by chrisdmacrae** [comment]
I was using the functionality incorrectly. Submitted a feature request instead.

https://github.com/tinacms/tinacms/issues/1536
