### ISSUE TITLE
(react-tinacms-editor): Naming Improvements

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#1535]
## Description

The [names of key components](https://github.com/tinacms/tinacms/tree/master/packages/react-tinacms-editor/editor-docs#high-level-architecture) in this package could use improvement. Currently the 'controller' component is called _Wysiwyg_; this decides whether to render the _Prosemirror_ or _Markdown_ editor, along with maintaining some other state.  

The _Prosemirror_ editor is truly the wysiwyg or rich-text editor, however it uses Prosemirror to do so. The _Markdown_ editor is really just a plain text editor, but it doesn't use Markdown to enable this editing power. The naming logic is flawed.

 ![](https://camo.githubusercontent.com/16370b8afbfbee1e7c6f110e482a143cd13106fb/68747470733a2f2f692e696d6775722e636f6d2f354970327253752e706e67)

## Suggestion

Wysiwyg 👉 Editor
Prosemirror 👉 Wysiwyg
Markdown 👉 PlainText

![react-tinacms-editor-structure(2)](https://user-images.githubusercontent.com/36613477/95506509-d6335500-0964-11eb-80ad-d8d61322ccfe.png)
cc'ing @jpuri @DirtyF

**Comment by ncphillips** [comment]
I like it. I would maybe note that `HTML` and `Markdown` are not editors but [Translators](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-editor/src/translator/TranslatorClass.ts#L21-L24)

**Comment by jpuri** [comment]
Make sense @kendallstrautman
