### ISSUE TITLE
Initial values arent loaded when starting tina in enabled mode

### ISSUE THREAD

**Issue by wvffle** [tinacms/tinacms#1551]
## Description

Initial values arent loaded when I start tina with `enabled: true` or `cms.enable()` just after defining `cms`. To be specific, I'm using `group-list` field.

If I do `setTimeout(cms.enable, 1)` it works like a charm but it feels hacky.

Also I'm using react-router, so it may be the case.

### Steps to reproduce

1. Initialize tina with `enabled: true`
2. Create a group list field with any inner field 
3. Create `async loadInitialValues () {}` with some data
4. Open the site and see the CMS not loading those values 

### Expected result

Should load values into CMS

### Actual result
I'm able to render the values in the view but CMS is not doing that until I refresh it by either adding a new item or changing the path to another page and back

#### Tinacms Package Versions

```text
├─ @tinacms/alerts@0.31.0
├─ @tinacms/browser-storage@0.31.0
├─ @tinacms/core@0.31.0
├─ @tinacms/fields@0.31.0
├─ @tinacms/form-builder@0.31.0
│  ├─ @tinacms/forms@^0.31.0
│  ├─ @tinacms/react-core@^0.31.0
├─ @tinacms/forms@0.31.0
├─ @tinacms/icons@0.31.0
├─ @tinacms/react-alerts@0.31.0
├─ @tinacms/react-core@0.31.0
│  ├─ @tinacms/core@^0.31.0
│  └─ @tinacms/forms@^0.31.0
├─ @tinacms/react-forms@0.31.0
│  ├─ @tinacms/form-builder@^0.31.0
├─ @tinacms/react-modals@0.31.0
├─ @tinacms/react-screens@0.31.0
├─ @tinacms/react-sidebar@0.31.0
│  ├─ @tinacms/core@^0.31.0
│  ├─ @tinacms/forms@^0.31.0
├─ @tinacms/react-toolbar@0.31.0
│  ├─ @tinacms/core@^0.31.0
│  ├─ @tinacms/fields@^0.31.0
│  ├─ @tinacms/forms@^0.31.0
├─ @tinacms/styles@0.29.0
├─ tinacms@0.31.0
│  ├─ @tinacms/alerts@^0.31.0
│  ├─ @tinacms/core@^0.31.0
│  ├─ @tinacms/fields@^0.31.0
│  ├─ @tinacms/form-builder@^0.31.0
│  ├─ @tinacms/forms@^0.31.0
│  ├─ @tinacms/icons@^0.31.0
│  ├─ @tinacms/react-alerts@^0.31.0
│  ├─ @tinacms/react-core@^0.31.0
│  ├─ @tinacms/react-forms@^0.31.0
│  ├─ @tinacms/react-modals@^0.31.0
│  ├─ @tinacms/react-screens@^0.31.0
│  ├─ @tinacms/react-sidebar@^0.31.0
│  ├─ @tinacms/react-toolbar@^0.31.0
│  ├─ @tinacms/styles@^0.29.0

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |     Chromium and Firefox    |
| os      |     Archlinux    |
| node    |     14.13.1    |
| yarn    |     1.22.10    |

**Comment by DirtyF** [comment]
Any public repository where we could reproduce this issue?

**Comment by wvffle** [comment]
I'll create one tomorrow

**Comment by wvffle** [comment]
@DirtyF https://github.com/wvffle/tinacms-issue-1551-demo

It turned out that it's caused by the screen plugin having another group-list in it.

Am I doing something wrong or is it a bug for real?

**Comment by DirtyF** [comment]
We'll have a closer look later. For now, our core team is focused on shipping the media manager 😅

**Comment by kendallstrautman** [comment]
@wvffle since you're [not fetching data asynchronously](https://github.com/wvffle/tinacms-issue-1551-demo.git) in your demo, you can just use `initialValues`.

**Comment by wvffle** [comment]
@kendallstrautman I know though I'll fetch it in the future. It should not make a difference

**Comment by dwalkr** [comment]
@wvffle I pulled down that demo repo to test against our latest prerelease, but I don't think I'm seeing the described problem even when using 0.31.0. All the default data returned by `loadInitialValues` is being rendered in the view correctly.
