### ISSUE TITLE
Add `layout` prop to BlocksControls, similar to screen plugins

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1560]
## Summary

The screen plugins have a layout prop, that decides whether or not the screen component is rendered in a fullscreen "sidebar" or a popup.

I'd like the BlocksControls settings to have the same API, as the popup isn't super useful in some use cases.

### Basic example

```
<BlocksControls index={index} layout="fullscreen">
  <Component />
</BlocksControls>
```

### Motivation

For complicated settings modals, you get a bigger more expressive UI.

**Comment by kendallstrautman** [comment]
Could you elaborate on what the 'fullscreen' layout would look like or behave?

**Comment by chrisdmacrae** [comment]
@kendallstrautman exactly the same as a screen plugin!
