### ISSUE TITLE
On Tina CMS constructor, trying to register the same api twice with the same key should throw an error.

### ISSUE THREAD

**Issue by canrozanes** [tinacms/tinacms#1578]
## Description

Not sure if its a bug or a feature request but as I was going through the [Nextjs: github backend guide](https://tinacms.org/guides/nextjs/github/initial-setup/), I accidentally registered the github client twice. I spent a good amount of time trying to figure out why my `onLogin` and `onLogout` calls were being fired twice and turns out it was because of just that: I had registered github client twice.

### Steps to reproduce

1. Register github inside the config object of the `new TinaCMS()` constructor.
2. Register github again using `cms.registerApi("github", github)`

Here is what my Tina Cms Provider looked like before I diagnosed the problem:

```javascript
export interface CmsProviderProps {
  isEditing: boolean;
  error: Error;
  children: React.ReactChild | React.ReactChild[];
}

function CmsProvider({ isEditing, error, children }: CmsProviderProps) {
  const memoizedCms = useMemo(() => {
    const github = new GithubClient({
      proxy: "/api/proxy-github",
      authCallbackRoute: "/api/create-github-access-token",
      clientId: process.env.NEXT_PUBLIC_GITHUB_CLIENT_ID,
      baseRepoFullName: process.env.NEXT_PUBLIC_REPO_FULL_NAME,
      baseBranch: process.env.NEXT_PUBLIC_BASE_BRANCH,
    });
    const cms = new TinaCMS({
      enabled: isEditing,
      apis: {
        github,
      },
      media: new GithubMediaStore(github),
      sidebar: isEditing,
      toolbar: isEditing,
    });

    cms.registerApi("github", github);

    return cms;
  }, []);
  return (
    <TinaProvider cms={memoizedCms}>
      <TinacmsGithubProvider
        onLogin={onLogin}
        onLogout={onLogout}
        error={error}
      >
        <GithubToolbarProvider>{children}</GithubToolbarProvider>
      </TinacmsGithubProvider>
    </TinaProvider>
  );
}

export default CmsProvider;
```

### Expected result

Should throw an error that says something along the lines of `can't register the same client twice with the same key: ${key}`

### Actual result

No error is thrown.

#### Tinacms Package Versions
```text
├─┬ react-tinacms-github@0.32.0
│ └─┬ next-tinacms-markdown@0.32.0
├─┬ tinacms@0.32.0
│ ├── @tinacms/alerts@0.32.0
│ ├─┬ @tinacms/fields@0.32.0
│ ├─┬ @tinacms/form-builder@0.32.0
│ ├─┬ @tinacms/forms@0.32.0
│ ├── @tinacms/icons@0.31.0
│ ├── @tinacms/react-alerts@0.32.0
│ ├─┬ @tinacms/react-core@0.32.0
│ ├─┬ @tinacms/react-forms@0.32.0
│ ├── @tinacms/react-modals@0.32.0
│ ├── @tinacms/react-screens@0.32.0
│ ├─┬ @tinacms/react-sidebar@0.32.0
│ ├─┬ @tinacms/react-toolbar@0.32.0
│ ├─┬ @tinacms/styles@0.29.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |Latest Chrome|
| os      | macOS v10.15.4|
| node    | v13.8.0 |
| npm     |6.13.7|

**Comment by kendallstrautman** [comment]
Thank you, good catch. There's definitely a lot of room for better feedback with the GitHub client.

**Comment by dwalkr** [comment]
I'm hesitant to throw an error in this case. `CMS#registerApi` is intended to have the APIs swappable if necessary. The bug you encountered here, I believe, is that the old API's event handlers aren't cleaned up when a new API is attached to the namespace, thus causing two subscriptions to the same events to exist.
