### ISSUE TITLE
Add the option to add true/false labels for the toggle plugin.

### ISSUE THREAD

**Issue by canrozanes** [tinacms/tinacms#1579]
## Summary

Currently there is no way to add true/false labels to the  [toggle plugin](https://tinacms.org/docs/plugins/fields/toggle/).
I'd like to request a feature to allow developers to optionally add customizable true/false label to the plugin.

Modified Interface
```typescript
interface ToggleConfig extends FieldConfig {
  component: 'Toggle'
  name: string
  label?: string
  description?: string,
  trueLabel:? string,
  falseLabel?: string
}
```
Alternatively: 
```typescript
interface ToggleConfig extends FieldConfig {
  component: 'Toggle'
  name: string
  label?: string
  description?: string,
  toggleLabels?: {
    true?: string,
    false?: string
  }
}
```
### Basic example
```javascript
const formOptions = {
  label: "Paragraph",
  fields: [{ 
     name: "isBold", 
     label: "Should font be bold?", 
     component: "toggle",
     trueLabel: "Yes",
     falseLabel: "No",
    }]
};
```

Results in:
![toggle](https://user-images.githubusercontent.com/37912128/97628069-9ced8280-1a02-11eb-843a-b1aff0aefaaf.png)

### Motivation

Sometimes toggle's overarching label might not be enough to capture the toggles intended behaviour. Adding true/false labels for each option would help clarify the intended behaviour for content editors. This would also be an accessibility win.

I was inspired by Contentful's API as it allows for this kind of customization in its [contentful-migration](https://github.com/contentful/contentful-migration) package with the following form:

```javascript
  const blogPost = migration.editContentType('blogPost');
  blogPost.changeFieldControl('hasPublishDate', 'builtin', 'boolean', { 
    trueLabel: 'Has visible publish date ',
    falseLabel: 'Does not have visible publish date'
  });
```

**Comment by canrozanes** [comment]
If it's an approved feature request, I'd like to work on it. Seems like a relatively simple change.

**Comment by kendallstrautman** [comment]
This looks great! Let us know if you need help 👏 I think I'd prefer the alternative API, where the labels are contained in an object. This way, the interface could be something like:

```
  toggleLabels?: boolean | {
    true: string,
    false: string
  }
```

And we could provide defaults as 'yes' / 'no'. I wouldn't want to account for cases where only one label were passed if they were both optional.

**Comment by dwalkr** [comment]
I agree w/ @kendallstrautman regarding the proposed API. And we look forward to your PR! :smile:
