### ISSUE TITLE
Expose SettingsModal in react-tinacms-inline

### ISSUE THREAD

**Issue by alexbchr** [tinacms/tinacms#1583]
## Summary

It would be very useful to have the `SettingsModal` component in `react-tinacms-inline` exported and available for global usage. The `Screens` and `Content-Creator` plugins let you create "Modals", but they add menu items in the sidebar.

However, for certain use cases, such as a custom `InlineField`, it would be useful to be able to use custom modals such as the SettingsModal directly, without going through `InlineGroup` or `InlineBlocks`.

My use case is that I have an `Icon` component in my website that I want to make editable through a custom `InlineField`. When the user clicks on it, I want to show the `SettingsModal` directly, as an `InlineGroup` would be too restrained by the small space available on this component. The code of `SettingsModal` can easily be copy-pasted in my code and is working, but it would be nice to directly get it from the `tinacms` or `react-tinacms-inline` package.

### Basic example

Usage would be the same as in the `react-tinacms-inline` package:

```tsx
{selectorOpen && (
  <SettingsModal
      title="Icon Settings"
      fields={[
        {
          name: input.name,
          label: 'Icon',
          description: 'Choose an icon to display',
          component: 'text',
        },
      ]}
      close={() => setSelectorOpen(false)}
  />
)}
```

Also, maybe also add a `title` prop to be able to customize the Modal title.

### Motivation

This would answer several use cases such as this one and ensure a consistent editing UX for users, in case of future modifications to this `SettingsModal` component.

_Additional Note: Just started playing with TinaCMS and inline editing a week back and I really enjoy it! Very cool library and easy to use API :tada:_

**Comment by kendallstrautman** [comment]
Good idea! This would be a great first issue as it seemingly would only involve [exporting that modal](https://github.com/tinacms/tinacms/blob/master/packages/react-tinacms-inline/src/inline-settings.tsx#L71) from the package. Would you be interested in making a PR?

**Comment by alexbchr** [comment]
Of course! I will try to find some time later today or sometimes next week!

**Comment by kendallstrautman** [comment]
Great 😁! Feel free to reach out if you need help.

**Comment by alexbchr** [comment]
`SettingsModal` is now exported in `master` branch (following PR #1587)
