### ISSUE TITLE
WYSIWYG: clicking on URLs in editing mode follows the link

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#159]
When using the WYSIWYG component in inline editing mode, highlighting a URL to edit it causes the browser to follow the link and take the user away from the editor.

Behavior occurs in Chrome, have not tested in other browsers.

**Comment by jpuri** [comment]
The issue appears to be fixed already:

![link](https://user-images.githubusercontent.com/2182307/73666639-1b620180-46c9-11ea-9e1a-7dfdb9baf85b.gif)

**Comment by ncphillips** [comment]
👍 closing
