### ISSUE TITLE
Allow me to select the bottom of an inline blocks stack

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1597]
## Summary

Most design tools allow you to select the most deeply nested element by pressing a keyboard modifier when selecting.

### Basic example

If you have nested blocks:

- a
   - b
     - c
       - d

And want to select d, you must select a, then b, then c, then d. It would be nice if D could be directly selected.

### Motivation

Make inline UIs more delightful to navigate.

**Comment by DirtyF** [comment]
Webflow has a navigation panel

<img width="292" alt="Capture d’écran 2020-11-03 à 16 30 37" src="https://user-images.githubusercontent.com/103008/98013885-3a79f500-1dfb-11eb-9df8-fc04dc584397.png">

**Comment by chrisdmacrae** [comment]
@DirtyF this is a different use case. I want to point my mouse at a block, and drill directly to it.
