### ISSUE TITLE
react-tinacms-inline: undo changes

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1609]
## Summary

Editors should get to the previous state when they make a mistake while manipulating inline blocks.

### Basic example

I accidentally deleted a photo or a text; how can I go back to the previous state?

### Motivation

Tina should be tolerant of human mistakes for editors to feel safer to experiment when they use blocks.

**Comment by chrisdmacrae** [comment]
Food for thought: I think this should be more low
level than inline. 

In our core forms interface, we could dispatch commands that mutate the data and track them. Undoing is applying the inverse, redo is reapplying the command. 

This would allow undo/redo across the entire CMS.
