### ISSUE TITLE
Add option to display BlockMenuWrapper (in BlockControls) below the block 

### ISSUE THREAD

**Issue by alexbchr** [tinacms/tinacms#1624]
## Summary

Add an option to display BlockMenuWrapper (in BlockControls) below the block. Right now, you can only display the Block Menu above the element or inside it (`inset` option).

Being able to control the `BlockMenuWrapper` offset independently from the `FocusRing` offset could solve this issue too. Another option (the best one according to me), would be to render the `BlockMenuWrapper` as a "Modal" inside `TinaProvider` (absolutely positioned relative to it). This would put the BlockMenu higher in the DOM hierarchy and prevent it from being cropped by hidden elements.

### Basic example

Being able to use something like `<BlockControls belowControls />` would be useful. However, since we already have `insetControls`, the best option could be to add a prop like `controlsPosition: 'above' | 'inside' | 'below'`. on the `BlockControls` component.

### Motivation

In some cases, such as in small blocks, having the block inset is not an option. Additionally, when a container element has `overflow: hidden` and the blocks are on top, the Menu is cropped/hidden. Rendering it below the block in specific cases would solve this issue.

**Comment by spbyrne** [comment]
Hey, thanks for raising this issue.

We're looking to improve the inline UI flexibility. Certainly more customization is needed. Sometimes you don't want directional controls, sometimes you don't want the add block buttons..etc.

**Comment by spbyrne** [comment]
@alexbchr  For block control placement options, do you think 'top | topInset | bottom | bottomInset' would provide enough control? What other options may be useful?

**Comment by alexbchr** [comment]
> @alexbchr For block control placement options, do you think 'top | topInset | bottom | bottomInset' would provide enough control? What other options may be useful?

I think so, as providing an option to render the block controls `left` or `right` would simply confuse the user. I think this would be flexible enough, especially with the existing `offset` option.

However, it would be very useful if the controls were absolutely positioned relatively to the `TinaProvider`, maybe through a `Portal` component... This would several issues with BlockControl placement, such as:
- Prevent cropping by parent components having `overflow: hidden` style
- Prevent cropping by screen/document edges.

Right now, if you don't inset the controls, the controls can be hidden if the component is on top of the screen, and insetting the conmtrols is not always an option, as sometimes the component's height and/or width may be too small for it.

Of course, changing the controls placement in such a drastic way would probably be a breaking change, but I think it would simplify the controls "placement" situation, as maybe the dev would not need to worry that much about where the component is rendered to determine where to render the controls.

**Comment by spbyrne** [comment]
We're actually exploring that option, but for all inline UI. Basically using a ref attached to your component to place the UI in a container that's out of the flow of your site. Since the controls will get placed procedurally we'll be able to account for things like being outside of the viewport. 

[Check out the RFC here.](https://github.com/tinacms/rfcs/blob/9cb943b837df8290dd6d6f29437c6e2e2a0b5385/0012-inline-api.md) - "however those controls are actually mounted at the root of the dom via portal, they're just positioned over the elements with absolute positioning"

**Comment by alexbchr** [comment]
Great! I wasn't aware of that RFC until now! Depending how soon (or late) this change can be implemented, maybe this issue can wait until then?

Just a question on the RFC, would it be simpler to use a HoC or simply return a `ref` from the React hook? I imagine there is a good reasoning behind the "spread function" approach?
