### ISSUE TITLE
make it easier to add/replace Media Store outside of constructor

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#1629]
At one point (not sure when) we moved `cms.media.store` to a wrapper class, allowing us to call store methods on `cms.media`. This provided a mild improvement to the API but has made it very clumsy to dynamically add or replace a media store after the CMS object is instantiated.

I don't see dynamically replacing a media store to be a particularly useful or practical thing, but being able to easily attach one outside of the constructor would be useful in the case of the proposed [initializer plugin](https://github.com/tinacms/rfcs/pull/13).

**Comment by chrisdmacrae** [comment]
This would be a huge help for me!

It would also be nice to standardize this interface across all of the different top level CMS scopes and soft deprecate any interfaces that don’t match the standard convention. 

```
interface CMSEntity {
  add
  remove
  update
}
```

**Comment by chrisdmacrae** [comment]
@dwalkr #1637
