### ISSUE TITLE
feat: hide/show hamburger in sidebar

### ISSUE THREAD

**Issue by keery** [tinacms/tinacms#1631]
## Summary

Hi everybody,
My suggestion is to add the possibility with a prop in sidebar configuration to have the possibility to hide hamburger button.

### Basic example

An exemple if you use edition features provided by tinacms but you don't need the entire media part.

### Motivation

It doesn't take that much time to implement, and I think many people don't use this part of the editor even if it might be really usefull, depends of user context;

Thanks to all support from tinacms, this project is really awesome, you do a great job with 👍🏼

**Comment by mitchmac** [comment]
@keery I think I agree that the Media Manager UI should be opt-in.

You can remove the Media Manager screen plugin, which should hide the hamburger, with:

`cms.screens.remove("Media Manager");`

**Comment by keery** [comment]
It works well, thanks !
