### ISSUE TITLE
Allow developers to pass a `key` prop to InlineBlocks

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#1638]
Or even, use `itemProps.key`. Probably better to be explicit though.

This will help limit re-rendering of block lists, as is being hinted at in #1630 

However, there is other reactivity that is dependent on the field name, which is in turn dependent on the block's position in the list. @chrisdmacrae I'd appreciate if you could describe the problem you're encountering w/ reordering blocks. If it's a major performance degradation, I'd guess it's as much (or more) due to the memoized components being discarded due to `blockName` (`data.blocks.0...etc`) changing.

**Comment by chrisdmacrae** [comment]
@dwalkr this is a better issue than #1630.

I would think about this in regards to the `blocks` field and `group-list` field. The same issue can present here with long lists.

**Comment by dwalkr** [comment]
> unless we need the `key` field to be placed higher up the React tree than where `itemProps` is used.

This issue is suggesting we do exactly that. We would need to pull the `key` out of `itemProps` and use it in a parent component
