### ISSUE TITLE
[ feature 💅  ] extended theme support for tina's UI

### ISSUE THREAD

**Issue by pixelmord** [tinacms/tinacms#1641]
## Summary

I am working on a project where the client would like to have tina's UI styled (more) according to his CD. It would be great if we could extend the existing theme to support more customizations. Ideally, that would be done in a way that respects the work you have done already and just offer a more granular approach of being able to set variables for example. 

### Basic example

For example, this could be done by introducing more specific css custom properties that could optionally be set if the need arises to do more granular styling. The current variables could be set as default/fallback value and thus the current style would not break if the more granular variables are not set.
Example:

```javascript
export const Button = styled.button<ButtonProps>`
  text-align: center;
  border: 0;
  border-radius: var(--tina-button-border-radius, --tina-radius-big);
  box-shadow: var(--tina-button-box-shadow, --tina-shadow-small);
  background-color: var(--tina-button-background-color, --tina-color-grey-0);
  // ...
`;
```
### Motivation

This would allow a more customizable UI and therefore improve UX in projects where users are already accustomed to working with an interface they know.

**Comment by spbyrne** [comment]
Nice, this is a great idea. Certainly the intent is to expand on the (very limited) existing theming. I suspect other UI fixes/upgrades will take precedent but this is something that will have to happen at some point to allow for non-trivial theming.

**Comment by pixelmord** [comment]
Great, I will open a draft PR today or tomorrow
