### ISSUE TITLE
onLogin of TinacmsGithubProvider is no longer triggered

### ISSUE THREAD

**Issue by c58** [tinacms/tinacms#1647]
## Description
onLogin of TinacmsGithubProvider is no longer called when cms enabled.

### Steps to reproduce
Just setup next.js + github exactly as it is in the guide: https://tina.io/guides/nextjs/github/initial-setup/
Click to "Edit this page" button

### Expected result
The base branch should be checkout, the preview mode should be activated

### Actual result
Preview mode is not activated and the branch is not checked out.

### Environment
MacOS

#### Tinacms Package Versions
```text
├── UNMET PEER DEPENDENCY @tinacms/core@^0.29.0
├── UNMET PEER DEPENDENCY @tinacms/fields@^0.29.0
├─┬ next-tinacms-github@0.34.0
│ ├── UNMET PEER DEPENDENCY @tinacms/core@0.33.0
│ ├── UNMET PEER DEPENDENCY @tinacms/fields@^0.29.0
├─┬ react-tinacms-editor@0.34.0
├─┬ react-tinacms-github@0.34.0
│ └─┬ next-tinacms-markdown@0.34.0
├─┬ react-tinacms-inline@0.34.0
├─┬ tinacms@0.34.0
│ ├── @tinacms/alerts@0.33.0
│ ├─┬ @tinacms/fields@0.34.0
│ ├─┬ @tinacms/form-builder@0.34.0
│ ├─┬ @tinacms/forms@0.33.0
│ ├── @tinacms/icons@0.31.0
│ ├── @tinacms/react-alerts@0.34.0
│ ├─┬ @tinacms/react-core@0.34.0
│ ├─┬ @tinacms/react-forms@0.34.0
│ ├── @tinacms/react-modals@0.34.0
│ ├── @tinacms/react-screens@0.34.0
│ ├─┬ @tinacms/react-sidebar@0.34.0
│ ├─┬ @tinacms/react-toolbar@0.34.0
│ ├─┬ @tinacms/styles@0.33.0
```

#### Tools
| Tool    | Version |
| ------- | ------- |
| browser |    chrome     |
| os      |    macos     |
| node    |    v12.18.3     |
| npm     |    6.14.6     |

# NOTES
I believe that this is a degradation because of this commit: https://github.com/tinacms/tinacms/commit/6580c8afa247e3d6a1beb9d7e4967b45c130fa1e

TinacmsGithubProvider calls github.checkout on a success authorization of a base branch with `gihtub.branchName`, and then `checkout` compares it with `this.branchName` and does nothing, which produces the bug.

**Comment by jd4d** [comment]
+1 this has been very confusing trying to spin up a new project locally.

**Comment by dwalkr** [comment]
@all-contributors add @c58 for bugs
