### ISSUE TITLE
Add support for Images to Markdown field plugin

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#166]
In order to support images in the wyswiyg, a specialized [Node View](https://prosemirror.net/docs/ref/#view.NodeView) will have to be added. We have an ImageNodeView in the `forestryio` source code.

There may need to be a specialized ImageNodeView for handling Gatsby's relative path transformations.

**Update:**

 Now that Tina offers a media store, we can start working on managing images in the Markdown editor.

The first step is to allow people to add one media at a time in the editor.

```gherkin
Given I'm using the WYSIWYG editor
When I click on media button
Then I can add an image in the editor
```

- [x] showing loading state on upload
- [x] copy-paste an image in the editor
- [x] drag-n-drop an image in the editor
- [x] Upload an existing image in the WYSIWYM trough a UI

**Comment by jpuri** [comment]
We already have a NodeView for images, I am not sure if this task is still valid.

**Comment by ncphillips** [comment]
The base of this issue is technically complete. Further work will have to be done later specifically around:

1. Rendering local images via the wysiwyg
1. Uploading images via the wysiwyg

We can look to the [Image Field](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/plugins/fields/ImageFieldPlugin.tsx#L39-L53) for inspiration and consistency on how to address these issues.

## Rendering Images

Here's a bit more background on the first problem.

In Gatsby sites the image paths in markdown files get transformed at build time. A markdown file might have this in the body:

```markdown
![](../assets/cute-cat.jpg)
```

but it will actually be turned into this at build time:

```
<img src="/public/assets/cute-cat.jpg" />
```

That means the URL in the markdown source won't actually work for previewing.

A solution like that found in [the "image" field](https://tinacms.org/docs/fields/image#examples) would probably work and be flexibile enough to cover whichever use case. For that field, there is a `previewSrc` function that accepts the frontmatter value and outputs the url to used for previewing. It is the field user's responsibility to tell it how to work. (Aside: this adherence to the dependency inversion principle is pretty core to Tina's philosophy.)

The `"markdown"` field config might look something like this:

```js
useForm({
  fields: [
    { 
      name: "markdownBody",
      component: "markdown", 
      imagePreviews(url) {
        return url.replace('../', '/public/')
      }
    }
  ],
  // .....
})

**Comment by jpuri** [comment]
Hey @spbyrne , @DirtyF : we also need to work on showing loading state in editor when image is uploaded.
