### ISSUE TITLE
InlineForm adds two non-targetable divs to DOM layout

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1664]
## Description

Not sure if this is a "bug", but it's breaking behaviour for me. `InlineForm` appears to be rendering two classless divs when added to a page since updating to `tinacms@0.34.0` and `react-tinacms-inline@0.34.0`.

### Steps to reproduce

Add an inline form. See the divs.

### Expected result

Inline form shouldn't require any DOM elements?

### Actual result

Inline form is adding DOM elements, and they can't be classed or managed, so they mess up my design.

#### Tinacms Package Versions

```text
N/A
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   safari@latest      |
| os      |    macos     |
| node    |     LTS    |
| npm     |     LTS    |

**Comment by dwalkr** [comment]
Are you upgrading from `0.33` or an earlier version?

**Comment by chrisdmacrae** [comment]
@dwalkr went from 0.30.0 => 0.34.0 => 0.35.0

**Comment by dwalkr** [comment]
I checked out v0.30.0 and ran _demo-next_ in the monorepo, and still have the two wrapping divs. I can see how that's could be a problem, but doesn't seem to be a regression from previous behavior.

If you think it's a regression, I think we'll need more info and, ideally, a reproduction of the problem.

**Comment by chrisdmacrae** [comment]
@dwalkr irregardless of it being a regression or not, it _is_ a problem, because the divs have no reliable way of targeting with CSS.

Ideally they wouldn't be there at all. But if that's a big challenge, then making them easier to target to fix styling would be ideal.

**Comment by dwalkr** [comment]
I completely agree, but there is a difference between "my existing Tina setup suddenly broke after an update" and "Tina is hard to work with because X" in terms of how we prioritize an issue like this.

**Comment by zenflow** [comment]
> Inline form shouldn't require any DOM elements?

You can see from PR #1726 (and issue #1725) why those divs are required.
They're used for capturing events that will deselect any selected inline form field.

Perhaps though there is another way to do this though, which doesn't require extra divs.
 
Note that the `<Dismissible>` component (which renders the other div) lives in another repo: https://github.com/tinacms/react-dismissible/blob/5bf1d004505a4ede9c8fab72b5b5057b94346821/src/Dismissible.tsx#L57-L75

**Comment by zenflow** [comment]
So, right now we have two extra divs covering the exact same space (i.e. one is just inside the other, & neither have padding or margin)...
The first div is only used for capturing clicks *inside* the space
The second div is only used for capturing clicks *outside* the space.

I think we could remove both divs and instead use `useEffect` to attach a single click handler to the document body.

The only complication with this is that clicks outside the space are handled slightly differently than clicks inside the space..
Clicks outside the space are ignored if `settingsModalIsOpen` (see current InlineForm implementation below).
But I think it makes sense to also apply this logic to "inside clicks" also anyway.

Current InlineForm implementation: https://github.com/zenflow/tinacms/blob/3e8aab4f324454752e2a88d99e9bdf869c26447f/packages/react-tinacms-inline/src/inline-form.tsx#L44-L90

**Comment by Juje** [comment]
What is the status of this issue?
Cause the divs are still being created and there is no way to interact with them other then to add a styled-container to style them :slightly_frowning_face:.
