### ISSUE TITLE
Open by default sidebar

### ISSUE THREAD

**Issue by keery** [tinacms/tinacms#1670]
## Summary

The possibility to open by default the sidebar, this is a simple feature almost already implemented in the code, we can use a prop or something to define the state open/close of the sidebar

### Basic example

I have my tina editor on my page, and I want to access my fields directly when I arrive on it

### Motivation

Avoid to click on the icon to open the sidebar every time I use the editor

Thanks for your great job !

**Comment by kendallstrautman** [comment]
Hi @keery! You can already do this by calling `cms.sidebar.isOpen(true)`. That might look something like this in your page component:

```js
function Page() {
    const cms = useCMS()
    
    React.useEffect(() => {
        cms.enabled && cms.sidebar.isOpen(true)
    },[])
    
    return (
        //...
    )
}
```

**Comment by keery** [comment]
Thanks for your answer 👍 
Unfortunately it doesn't work, I am using `"tinacms": "^0.34.0"` with the following config
``` js
const DigestCreator = (props: IDigestCreator) => {
  const cms = useCMS()

  useEffect(() => {
    // @ts-ignore
    cms.enabled && cms.sidebar.isOpen(true)
  }, [])

  return (
        ...
  )
}

export default withTina(DigestCreator, {
  sidebar: true,
  enabled: true,
})
```

But I got this error 
![image](https://user-images.githubusercontent.com/10221598/102330929-7374c000-3f8a-11eb-8563-8aa20a2cf5cf.png)

**Comment by kendallstrautman** [comment]
Sorry, try `cms.sidebar.isOpen = true`....not as a function call.

**Comment by keery** [comment]
Thank you it works ! 
But the content of the page is not centered, so the sidebar is above the page

**Comment by kendallstrautman** [comment]
If you could link to a demo repo that'd be helpful!
