### ISSUE TITLE
Form in sidebar is empty for second opened page

### ISSUE THREAD

**Issue by akoltun** [tinacms/tinacms#1676]
## Description

Hello,

I follow the instruction on the web-site, how to [setup TinaCMS](https://tina.io/docs/getting-started/cms-set-up/) and [create a form](https://tina.io/docs/getting-started/edit-content/). I have cms setup code in the parent component, and two child components (each one with its own form) are shown via reach router.

Parent Page:
```
import { Router } from "@reach/router"
import React, { useMemo } from "react"
import { TinaCMS, TinaProvider } from "tinacms"
import { Link } from "gatsby"

import { One } from "../components/one";
import { Two } from "../components/two";

export default function Index () {
  const cms = useMemo(() => new TinaCMS({ sidebar: true, enabled: true }), [])
  return (
    <TinaProvider cms={cms}>
      <Link to="/one">One</Link>&nbsp;<Link to="/two">Two</Link>
      <Router>
        <One path="/one" />
        <Two path="/two" />
      </Router>
    </TinaProvider>
  )
}
```

Page 1
```
import React from "react"
import { useCMS, useForm,usePlugin } from "tinacms"

export const One = () => {
  const formConfig = {
    id: "one",
    label: "Edit 1st Page",
    fields: [
      { name: "name", label: "Name", component: "text" },
      { name: "oneLabel", label: "1st Label", component: "text" },
    ],
    initialValues: { name: "One", oneLabel: "1st" },
    onSubmit: data => { console.log("Submitting", data) },
  }
  const [data, form] = useForm(formConfig)
  usePlugin(form)

  return (
    <div>
      <p>{data.name}</p>
      <p>{data.oneLabel}</p>
    </div>
  )
}
```

Page 2
```
import React from "react"
import { useCMS, useForm,usePlugin } from "tinacms"

export const Two = () => {
  const formConfig = {
    id: "two",
    label: "Edit 2nd Page",
    fields: [
      { name: "name", label: "Name", component: "text" },
      { name: "twoLabel", label: "2nd Label", component: "text" },
    ],
    initialValues: { name: "Two", twoLabel: "2nd" },
    onSubmit: data => { console.log("Submitting", data) },
  }
  const [data, form] = useForm(formConfig)
  usePlugin(form)

  return (
    <div>
      <p>{data.name}</p>
      <p>{data.twoLabel}</p>
    </div>
  )
}
```

I'm facing the issue that TinaCMS sidebar has only form of the first opened page and is empty for the page that is opened next. 

Page 1:

![](https://github.com/akoltun/tinacms-error/raw/master/images/one-ok.png)

Page 2, visited after Page 1:

![](https://github.com/akoltun/tinacms-error/raw/master/images/two-error.png)

Doesn't matter, whether I start from page 1 or page 2.

If I start from the page 1, then it has the form, and after navigating to the page 2, the form disappears from the sidebar (which is correct) but new form from the page 2 doesn't appear (which is incorrect). If I start in opposite order - first, open the page 2, and after - the page 1, then only page 2 has the form in the sidebar but not the page 1.

So, the page, that is opened first, has form, but the page that is opened next, doesn't have form.

### Steps to reproduce

I created a simple repository that reproduces this issue: (https://github.com/akoltun/tinacms-error/tree/master). The repository uses gatsby but without any tinacms-gatsby plugins because I would like to have a clean simple setup, independent from any framework (like gatsby or next).
Steps to reproduce:

1. Clone the repo: `git clone https://github.com/akoltun/tinacms-error.git`
2. Install packages and run the project: `yarn && yarn dev`
3. Open the 1st page in the browser: `localhost:8000/one`
4. Open TinaCMS sidebar and make sure that the form is present
5. Click on the link to the page Two
6. The sidebar is empty now - the form from the page Two is not visible

### Expected result

The form from the Page 2 should appear in the sidebar as soon as I navigate to the Page 2.

### Actual result

Sidebar becomes empty as soon as I navigate to Page 2.

### Environment

Simple Gatsby project with client-side navigation managed by reach router. The same effect for dev and prod environments.

#### Tinacms Package Versions

```
npm ERR! peer dep missing: react@^16.4.2, required by gatsby@2.29.3
npm ERR! peer dep missing: react-dom@^16.4.2, required by gatsby@2.29.3
npm ERR! peer dep missing: react@15.x || 16.x || 16.4.0-alpha.0911da3, required by @reach/router@1.3.4
npm ERR! peer dep missing: react@^16.4.2, required by gatsby-link@2.8.0
npm ERR! peer dep missing: react@^16.4.2, required by gatsby-react-router-scroll@3.4.0
npm ERR! peer dep missing: react-dom@15.x || 16.x || 16.4.0-alpha.0911da3, required by @reach/router@1.3.4
npm ERR! peer dep missing: react-dom@^16.4.2, required by gatsby-link@2.8.0
npm ERR! peer dep missing: react-dom@^16.4.2, required by gatsby-react-router-scroll@3.4.0
npm ERR! peer dep missing: react@^0.14.0 || ^15.0.0 || ^16.0.0, required by create-react-context@0.3.0
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
npm ERR! peer dep missing: typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta, required by tsutils@3.17.1
npm ERR! peer dep missing: typescript@>=2.7, required by ts-node@9.1.1
npm ERR! peer dep missing: final-form@^4.20.0, required by react-final-form@6.5.2
npm ERR! peer dep missing: react@^16.8.5, required by react-beautiful-dnd@11.0.5
npm ERR! peer dep missing: react@^16.8.0, required by use-memo-one@1.1.1
tinacms-test@1.0.0 /Users/sasha/Develop/test/tinacms-test
└─┬ tinacms@0.34.0
  ├── @tinacms/alerts@0.33.0
  ├── @tinacms/core@0.33.0
  ├─┬ @tinacms/fields@0.34.0
  ├─┬ @tinacms/form-builder@0.34.0
  ├─┬ @tinacms/forms@0.33.0
  ├── @tinacms/icons@0.31.0
  ├── @tinacms/react-alerts@0.34.0
  ├─┬ @tinacms/react-core@0.34.0
  ├─┬ @tinacms/react-forms@0.34.0
  ├── @tinacms/react-modals@0.34.0
  ├── @tinacms/react-screens@0.34.0
  ├─┬ @tinacms/react-sidebar@0.34.0
  ├─┬ @tinacms/react-toolbar@0.34.0
  ├─┬ @tinacms/styles@0.33.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Chrome 87.0.4280.88 (however, issue present in other browsers also)     |
| os      |  macOS 10.14.6       |
| node    |  v12.18.4 (however, issue also present with v14)       |
| yarn     | 1.22.4 (however, issue also present with npm 6.14.6)       |

Happy New Year and 
Best wishes!

**Comment by mitchmac** [comment]
Hi @akoltun -- I wasn't able to re-create the issue with a similar but slightly different setup in a CodeSandbox: https://codesandbox.io/s/compassionate-bash-zpqxy

Differences:

- Create React App instead of Gatsby
- using the Link component from @reach/router instead of Gatsby... I would guess that this may be where the issue is coming from

**Comment by anguy95** [comment]
Hey @akoltun, I am facing this same issue on Next.js with basically the same component set up. Have you found a solution or what the problem was? Thank you.

**Comment by mitchmac** [comment]
Hi @anguy95! Can you share a sandbox or repo with your setup where you're seeing the issue? Wondering if you're doing any special routing?

**Comment by akoltun** [comment]
Hi @anguy95, I didn't find a cause of the problem. As a solution I just had to use another CMS instead of TinaCMS, which is pity because TinaCMS has nicer and more user-friendly interface.

**Comment by anguy95** [comment]
@mitchmac , @akoltun.  I actually figured it out. For some reason when I included `id` in the `formConfig` it seems to break on route changes. However, if you remove the `id` it starts working. I am not sure why it's working on the code sandbox link however :/ 

```
const formConfig = {
    id: "two", <-----------------------
    label: "Edit 2nd Page",
    fields: [
      { name: "name", label: "Name", component: "text" },
      { name: "twoLabel", label: "2nd Label", component: "text" },
    ],
    initialValues: { name: "Two", twoLabel: "2nd" },
    onSubmit: data => { console.log("Submitting", data) },
  }
```

**Comment by employee451** [comment]
I'm having this issue with Next.js v10.0.3

**Comment by aaron5670** [comment]
Same issue too on Next.js v10.2 and React 17.0.1

**Comment by employee451** [comment]
Temporary solution for Next.js:
Replace all instances of Next/Link with a `CustomLink` component:

```typescript
import Link, { LinkProps } from 'next/link'
import { useRouter } from 'next/router'
import { FC } from 'react'

const CustomLink: FC<LinkProps> = (props) => {
	const { isPreview } = useRouter()
	const { href, children } = props

	if (isPreview) {
		return (
			<a href={typeof href === 'string' ? href : href.pathname ?? undefined}>
				{children}
			</a>
		)
	} else {
		return <Link {...props}>{children}</Link>
	}
}

export default CustomLink
```

**Comment by brunocangs** [comment]
For NextJS I've set the form `id` as `""` on all my configs and seems to work. Could not remove them as Typescript complained
