### ISSUE TITLE
Feat: Conditional Fields

### ISSUE THREAD

**Issue by austincondiff** [tinacms/tinacms#1678]
## Summary

Currently there is no way to make fields conditional based on values of other fields or other variables. I would really love this eventuality to keep our forms concise for users.

### Basic example

One approach could be the following...

```js
const fields = ({ data }) => [
  {
    name: 'useReadme',
    label: 'Use ReadMe',
    component: 'toggle',
  },
  ...(data.useReadme
    ? [
        {
          name: 'title',
          label: 'Title',
          component: 'text',
        },
        {
          name: 'body',
          label: 'Body',
          component: 'markdown',
        },
      ]
    : []
  ),
]
```

```js
const fields = ({ data }) => [
  {
    label: 'Internal',
    name: 'internal',
    description: 'Set to false if you want link to another website',
    component: 'toggle',
  },
  ...(data.internal
    ? [
        {
          label: 'Slug',
          name: 'slug',
          component: 'text',
        },
      ]
    : [
        {
          label: 'Link',
          name: 'link',
          component: 'text',
        },
      ]
  ),
]
```

As previously mentioned however, we may want a more deliberate API instead of using ternaries in the forms array.

### Motivation

This seems like an expected form behavior and it would improve the overall user experience.

### Other considerations

This feature request was brought about from [this community discussion](https://community.tinacms.org/t/custom-field-conditional-field-s/425).

A package that does this already exists called [tinacms-conditional-fields](https://www.npmjs.com/package/tinacms-condition-field), but it is not maintained by the TinaCMS team.

**Comment by pixelmord** [comment]
I think we need to also consider non-boolean fields as a condition similar to what the final form example shows with a subscription to a field value to test against.

**Comment by jaschaio** [comment]
This stale bot makes me sad. Did anyone find a workaround for conditional fields?

**Comment by hspotorno** [comment]
@jaschaio The original discussion thread is gone so I'm not sure if this was already suggested, but for those coming here now, this is what we did to get conditional fields on the CMS:

The use case was a component for links in which we have a toggle for "external" - if it's true, we want to display a text input; if false, we want to display a page selection component.


```
{
  label: 'External',
  name: 'external',
  component: 'toggle',
},
{
  label: 'Link To',
  name: 'to',
  component: ({ form, field, input, meta }) => {
      const isExternal = form.getFieldState(
        `${field.name.replace('.to', '.external')}`,
       )?.value; // a bit hacky, this is inside an array and we don't have access to the current index otherwise

    return isExternal
      ? React.createElement(TextField, {
        input,
        form,
        field,
        meta,
        placeholder: "Link To",
      })
      : React.createElement(TinaPageSelect, {
        input,
        });
    },
  parse: parseString,
},
```


It is quite verbose but it works.
