### ISSUE TITLE
Feat: Duplicate Action for Inline Blocks

### ISSUE THREAD

**Issue by austincondiff** [tinacms/tinacms#1681]
## Summary

I have several nested inline blocks. To make page creation easier, it would be helpful to be able to duplicate an inline block along with it’s child inline blocks, settings etc. This would prevent users from having to recreate the same block multiple times. A button to trigger this duplicate action could be added to the inline block overlay menu.

### Basic example

User edits or creates a new page. They add a block, configure the block, add a few child blocks, configure them, etc. In the block overlay menu, the user clicks a new button with a duplicate icon to duplicate the block. Another block appears beneath it with the. same configuration as the first. The user changes a few things in the newly duplicated block to make it unique. This has saved the user time because they didn't have to start from scratch.

### Motivation

This would improve the editing experience by providing a way to save users time and making the flow much easier and faster if users desire multiple similar blocks in a page.

**Edit:** Temporary solution here https://github.com/tinacms/tinacms/issues/1681#issuecomment-758776880

**Comment by DirtyF** [comment]
When you add a new inline-block, the current params are reused to avoid to set them up again, maybe @spbyrne has more info on how to do this.

I remember @chrisdmacrae showing us copy-pasting inline-blocks but it's very fragile if you don't paste at the right level, we'll likely need a way to easily undo changes before allowing pasting blocks.

**Comment by austincondiff** [comment]
It would be awesome if the overlay menu looked something like this... 
![image](https://user-images.githubusercontent.com/806104/104198901-69f54100-53ec-11eb-8ee7-94af2667f1e7.png)

**Comment by chrisdmacrae** [comment]
@austincondiff duplicate is not a hard feature to deliver. In the interim, here is some pseudo code that _probably_ doesn't work, but _might_.

```
export function ExampleBlock = ({index, data}) => {
  const {insert} = useInlineBlocks();
  const DuplicateAction = useMemo(() => {
    icon: () => "Duplicate" // TODO: replace w/ an icon
    onClick: () => insert(index + 1, data) 
  }, [data]);

  return (
    <BlocksControls index={index} customActions={[DuplicateAction])>
      {// Your component code }
    </BlocksControls>
  )
}
```

**Comment by austincondiff** [comment]
For those wanting to do the same thing, this is what ended up working (Very close @chrisdmacrae)...

```js
const DuplicateIcon = () => <Icon size="sm" name="copy" style={{ width: 26, height: 18 }} />

export function ExampleBlock = ({index, data}) => {
  const { insert } = useInlineBlocks()
  const DuplicateAction = useMemo(() => ({
    icon: DuplicateIcon(),
    onClick: () => insert(index + 1, data),
  }), [data])

  return (
    <BlocksControls index={index} customActions={[DuplicateAction]}>
      {// Your component code }
    </BlocksControls>
  )
}
```

For some reason it didn't like me defining the function, it wanted me to execute it for the. `icon` property.

**Comment by austincondiff** [comment]
Can someone add me as a contributor to this repo? I have a local branch that is ready to be pushed to a PR.

**Comment by DirtyF** [comment]
@austincondiff you should be able to create a PR.

**Comment by EdgarGomez** [comment]
Hello,

is there any way to add this duplicate action in sidebar blocks component?

Best

**Comment by DirtyF** [comment]
@EdgarGomez Not for now.

**Comment by chrisdmacrae** [comment]
@EdgarGomez not from a third party extension perspective, but if you want to submit a feature request, that’s not a big piece of work provided the request gets discussed and scoped well.
