### ISSUE TITLE
Feat: Block Presets, Templates, and Symbols

### ISSUE THREAD

**Issue by austincondiff** [tinacms/tinacms#1688]
## Summary

**Block presets** allows the user to select from a list of user-defined presets that would set the current block to a specific configuration using existing fields on the block.

**Block templates** pull from a library of starter nested block structures for specific kinds of content. Think [Elementor Template Library](https://elementor.com/help/template-library/). A block template may contain more than one block.

**Block symbols** would be more in line with React components. A block symbol could be a call-to-action that appears on multiple pages. When one changes, they all change. It could even be smaller like a title and paragraph within a parent block, the content could change per instance, but the overall configuration remains consistent across other instances of that symbol (exactly what fields could even be user-configurable). This may help with a more consistent look throughout the site or it might help when you have a group of features on a page for example.

#### Presets
- User defines a block, clicks edit, defines several settings. In the dialog the user clicks save configuration as preset.
- User is presented with dialog to name the preset.
- User sees a new presets dropdown at the top of the dialog.

This behavior only exists if developer specifies a presets data file for the system to write to.

#### Templates
- User selects an inline block, clicks more menu of block, clicks "Save block as template"
- User is presented with dialog to give the template a name, and place the template in a category.
- User creates a new page.
- User clicks add block icon.
- User can either add a block or add a template. User clicks add a template.
- User is presented with dialog displaying available templates separated by categories.
- User can preview the template.
- User clicks add.
- Template is added as new block.

This behavior only exists if developer specifies a templates data file for the system to write to.

#### Symbols
- User selects an existing inline block
- User clicks more menu in overlay menu.
- User clicks "Create Symbol from Block"
- User is presented with a dialog asking the user to give the new symbol a name and category.
- User clicks Create and symbol is created from block.
- User navigates to another existing page.
- User adds new block and menu appears prompting user to either add a block, template, or symbol.
- User selects symbol.
- User is presented with dialog listing available symbols.
- User clicks symbol that was previously created.
- Symbol Block is added to page.
- User edits that symbol block.
- User navigates to the original page.
- User sees that change is persisted to both pages.

This behavior only exists if developer specifies a symbols data file for the system to write to.

### Motivation

Allow users even more control while maintaining consistency throughout their site.

### Other considerations

These three are very similar but each do different things. There may be some overlap so, is there a way to combine some or all of these concepts it a way that is not confusing to the user. 
This would need to be thought through in more depth to get a achieve a desirable DX pattern to get this behavior.

**Comment by DirtyF** [comment]
I like the idea that Developers/Designers could provide page or block templates variants through a config file, it would already be a nice first step to save editors from always having to build pages from scratch, and let them focus on their job which is to write content.

**Comment by spbyrne** [comment]
@austincondiff this is brilliant and something I'd definitely like to explore! Right now we're at the start of another round of work on improving the inline editing experience, [which you can read more about here](https://tina.io/blog/more-changes-coming-to-inline-editing/). We're going to try and address these issues before moving on to more advanced features. 

I've been building a prototype page builder using the existing inline editing controls and it seems we've come to some very similar conclusions about what features would make it a better experience. Things like template blocks, a visual block selector, duplicate/copy/paste, more advanced custom block actions, better directional controls..etc. I think our current project aimed at DX improvements will make some of these features easier to implement.
