### ISSUE TITLE
Convert inline text to content editable area

### ISSUE THREAD

**Issue by joeinnes** [tinacms/tinacms#1691]
## Summary

Currently, the InlineText field uses an input in edit mode. This can break layouts which depend on a parent element growing to the size of the contents (eg: in case there is a border or shadow around the text element, etc.), because inputs are rendered with a fixed width of 20 characters by default. I put together a field below which instead uses a span with content editable.

There are a couple of caveats to my approach:

1. A span with no content renders with zero width. I opted for a placeholder below, although a more appropriate production fix might be a minimum width (1 or 2ch perhaps?)
2. As React re-renders the field reactively when input.value changes, if we trigger this on the field's `onChange` handler, then the caret will jump back to the start of the span, making it impossible to type something properly. I solved this by only triggering the change handler on blur and focus, but a more appropriate fix might be keeping the caret position in state, and setting it on render (this is a [solved](https://github.com/lovasoa/react-contenteditable) [problem](https://draftjs.org), but goes beyond the scope of the basic example below).

### Basic example

```
import { InlineField, FocusRing } from "react-tinacms-inline";
import { useCMS } from "tinacms";

export function Inline2TextField(props) {
  const cms = useCMS();
  const focusRing = props.focusRing ?? true;
  return (
    <InlineField name={props.name}>
      {({ input }) => {
        const handleChange = (e) => {
          input.onChange(e.target.innerText);
        };
        if (cms.enabled) {
          return (
            <FocusRing name={input.name} options={focusRing}>
              <span
                onBlur={handleChange}
                onFocus={handleChange}
                contentEditable
                suppressContentEditableWarning={true}
                className="outline-none"
              >
                {input.value}
              </span>
            </FocusRing>
          );
        }
        return <span>{input.value}</span>;
      }}
    </InlineField>
  );
}

```

### Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

* Reduces differences between the way a page displays in edit mode and view mode.
* Use cases are specifically for text elements displayed on screen which have parents which grow to accommodate them. A very simple example of a layout which would benefit from this is available at https://example-layout.glitch.me
* Similar use cases exist where the text is wrapped in another inline element (eg: an `a` or `button` tag)

**Comment by atifsyedali** [comment]
This bug was a dealbreaker for us for now ... but that workaround works really well. Thanks @joeinnes!
