### ISSUE TITLE
InlineImage component should have `cursor: pointer` style when CMS is enabled

### ISSUE THREAD

**Issue by zenflow** [tinacms/tinacms#1705]
## Summary

`InlineImage` component should have `cursor: pointer` style when CMS is enabled.
(Currently is only ever has the normal `default` cursor.)
The pointer cursor indicates to the user that clicking it will trigger some action.
In this case that action is opening a Media Manager dialog.

### Motivation

I did my first introduction/training of a TinaCMS application to a person, and got to observe them exploring the editing interface. I noticed more than once when he was just trying to move the focus from an InlineText back to the inline block, he clicked an InlineImage, unintentionally opening the Media Manager dialog. 
I noticed that even I make this mistake (opening the opening the Media Manager dialog by accident) because the image is fit within the image *element*, and the actual area of the block which can be clicked to select the block is narrow.

Besides that, with the pointer cursor it actually cues the user who's exploring the interface that they found some kind of action or control.

A good first issue I think.
I may make a PR myself if I get around to it.

**Comment by DirtyF** [comment]
We all been there, I would prefer an overlay on the image with some default actions to avoid default upload.
