### ISSUE TITLE
Feat: Support for theme variable names in the color field instead of hex

### ISSUE THREAD

**Issue by austincondiff** [tinacms/tinacms#1706]
## Summary

When picking a color, it would be a predefined set of theme color variables (i.e. primary, secondary, neutral, etc). 

### Basic example

```js
{
  name: 'rawFrontmatter.background_color',
  component: 'color',
  label: 'Background Color',
  description: 'Edit the page background color here',
  colorFormat: 'hex',
  colors: [
    { label: 'Primary', color: theme.color.primary, value: 'primary' },
    { label: 'Secondary', color: theme.color.secondary, value: 'secondary' },
    { label: 'Neutral', color: theme.color.neutral, value: 'neutral' },
  ],
  widget: 'block',
},
```

### Motivation

Currently, when colors are selected, the values are hardcoded in the data file. This can be problematic if developers wish to change specific colors in a color palette. If the color field supported theme values, we could leave the color values in the theme and simply render it's color in the color field. This way if the theme ever changes, all the selected colors throughout the site change as well.

**Comment by DirtyF** [comment]
You can use data files to set theme colors and then access those through a global screen plugin

**Comment by austincondiff** [comment]
@DirtyF oh yeah, I understand that I can use a global data file to define site wide colors. Currently I have a select field with color name options you can choose from. The problem with this is that I cannot see the color swatch associated with the color name in the field. It would be nice to be able to be able to use the color field to do this instead of a select field so I can see the color associated with the name.
