### ISSUE TITLE
Tina with Strapi tutorial: Image only updated after reload

### ISSUE THREAD

**Issue by chris-schra** [tinacms/tinacms#1733]
## Description

I just started with TinaCMS and really love it. We're already using Next and Strapi, so I thought a good starting point would be the "Using Tina With Strapi" tutorial (https://tina.io/guides/nextjs/tina-with-strapi/editing-with-tina/)
Everything works as expected, but the image (coverImage) of the post is not immediately updated, only after a reload:

![Kapture 2021-02-05 at 09 43 20](https://user-images.githubusercontent.com/26594889/107010465-acfdc680-6796-11eb-8edb-4c5a09d3d280.gif)

I've set a breakpoint in post-header.js PostHeader function to check when it is rendered and found that it actually is re-rendered when I change the headline, but not when I change the image

### Steps to reproduce

- Follow the Tina/Strapi tutorial
- Go to one of your posts
- Change the coverImage of the post

### Expected result

updated coverImage should be shown

### Actual result

old coverImage is shown

#### Tinacms Package Versions

```text
├─┬ react-tinacms-editor@0.36.1
├─┬ react-tinacms-inline@0.36.1
├─┬ react-tinacms-strapi@0.36.0
└─┬ tinacms@0.36.1
  ├── @tinacms/alerts@0.33.0
  ├── @tinacms/core@0.33.0
  ├─┬ @tinacms/fields@0.36.0
  ├─┬ @tinacms/form-builder@0.34.0
  ├─┬ @tinacms/forms@0.33.0
  ├── @tinacms/icons@0.36.0
  ├── @tinacms/react-alerts@0.36.0
  ├─┬ @tinacms/react-core@0.34.0
  ├─┬ @tinacms/react-forms@0.36.0
  ├── @tinacms/react-modals@0.36.0
  ├── @tinacms/react-screens@0.36.0
  ├─┬ @tinacms/react-sidebar@0.36.1
  ├─┬ @tinacms/react-toolbar@0.36.0
  ├─┬ @tinacms/styles@0.33.0

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |     Chrome 88.0.4324    |
| os      |   macOS Big Sur      |
| node    |   v14.5.0      |
| npm     |     6.14.5    |

**Comment by chris-makaio** [comment]
related to #1307 (sorry, found it only after googling for code lines)

**Comment by tyhoerr** [comment]
Also having this issue after setting up the nextjs/strapi tutorial. @chris-makaio like you said might be related to #1307, but that issue is specifically labeled as a gatsby problem, so worth pointing out the issue exists with the nextjs/strapit tutorial as well.
