### ISSUE TITLE
Allow getting the state of a field from the form

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1735]
## Summary

The form currently has a `change` method, that takes a field name and updates the value. Would be nice if there was a `get` method that takes a field name and returns the current value.

### Basic example

```
const form = new Form({ ...options })
const name = form.get("field.name")

console.log(name);
```

### Motivation

There's a lot of use cases where getting the current value of a specific field is useful. E.g, for conditional field logic, or when wanting to get the current value of the field before updating the value (e.g, to update a single key in an object).

**Comment by dwalkr** [comment]
`form.finalForm` has access to final form's `FormApi` which can get the form values: https://final-form.org/docs/final-form/types/FormApi#getstate
