### ISSUE TITLE
`StyledFocusRing` has `width:100%;height:100%` which can break CSS layout

### ISSUE THREAD

**Issue by r00dY** [tinacms/tinacms#1743]
Hey guys,

Awesome job with Tina, couldn't love your project more!!!

Just one issue I noticed. `react-tina-inline` adds `StyledFocusRing` to the DOM. It's all fine but by making it `width: 100%; height: 100%` it can break CSS layout. I'm talking about this line of code:

https://github.com/tinacms/tinacms/blob/a22063fdf2e10f873df9bd401f5d224c73ef6729/packages/react-tinacms-inline/src/styles/focus-ring.tsx#L85-L86

Imagine you have an `InlineGroup` or `InlineBlock` with content that has some "intrinsic natural width" which is not 100%. Like a `button` with `width: 200px`. Imagine that the parent of this element is `display: flex`. Flex parent makes a use of natural width of its children during layout (uses `width` as `flex-basis` if the latter is missing). However, if you add `width: 100%` between parent and child (`StyledFocusRing`) then layout breaks, because flex parent thinks that its child is 100% width. Basically any kind of layout that makes a use of content size of its children will break if we add Tina container in between.

In my opinion `StyledFocusRing` shouldn't have neither `width` nor `height`. Its size should be determined by the content and it should be as non-intrusive as possible. (can't wait for `display: contents` to have better support btw).

I know this change could break backward compatibility in some projects. Maybe we could add a flag? I'd be happy to do a PR, but curious about rationale behind the current behaviour.

**Comment by spbyrne** [comment]
Just with some quick testing it seems that this was done for components that use relative or absolute positioning within their parent, which is probably the minority compared to intrinsic sizing. I think possibly just accepting a class string and passing it to the focus ring, or only setting width/height when some prop is set could solve the issue for now. This component is used by the inline group and inline block components, and they already accept focus ring options which could accommodate this change.

**Comment by atifsyedali** [comment]
Currently for us, certain types of elements that expect direct children to have certain CSS constraints ends up with incorrect layouts while editing. For example, a FlexGroup that has FlexItems requires FlexItems to have flex properties. 

It would be great if we can just pass a className to be appended to the StyledFocusRing elements. This way, if I have an element like FlexGroup and another set called FlexItems, then I can give classNames to StyledFocusRing elements that would make them behave like FlexItems.

In the long term, it would be great to not even have feedback elements injected. For example, notion.so adds separate feedback elements that are positioned absolutely for mouse move and dnd effects.

Also, thanks for an amazing project!
