### ISSUE TITLE
GithubMediaStore Pagination not getting the correct offset

### ISSUE THREAD

**Issue by louMoxy** [tinacms/tinacms#1747]
## Description

The pagination on the Media Manager screen isnt getting the correct offset, when you click for page 2 on the media manager nothing loads, after pulling it apart a bit, I found that the MediaListOptions offset is 0 on the first (expected) and then 100 on the second page, but the limit is only 50, therefore nothing is loaded.

### Steps to reproduce

Have more than 50 media items, click the 2 in the bottom right corner, and nothing loads.

![Screenshot_2021-02-17 Screenshot](https://user-images.githubusercontent.com/20976565/108273637-b5c5a380-716b-11eb-8394-759ed697d182.png)

#### Tinacms Package Versions
"tinacms": "^0.37.0"

I am happy to add a PR, if someone could point me in the right direct? As not sure what is calling MediaStore.list

**Comment by DirtyF** [comment]
50 is the default, do you pass any [options to your Media List](https://tina.io/docs/media/#media-list)?

**Comment by louMoxy** [comment]
No I dont pass any options, I was using the default set by GithubMediaStore

**Comment by louMoxy** [comment]
Hi again,

So I have created a small repo with over 50 images in it, to show the issue: 
https://github.com/louMoxy/tinacms-media-issue

https://user-images.githubusercontent.com/20976565/109432598-d6131f00-7a03-11eb-8304-93cd11916f6b.mp4


Any help or advice would be apprciated, thank you
