### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by patrickconroy** [tinacms/tinacms#1753]
## Description

There are a lot of open issues @ https://github.com/tinacms/tinacms/issues but only 2 comments in the past month. The last closed issue was 3 weeks ago. If there's no active development here does anyone know a fork where things are happening?

Thanks

**Comment by DirtyF** [comment]
The project is very much alive and kicking and we did merge 22 pull requests in the last weeks, amongst them some new fields from external contributors
https://github.com/tinacms/tinacms/pulse/monthly

Our small core team works in 6 weeks cycles, [watch our roadmap](https://github.com/tinacms/tinacms/blob/master/ROADMAP.md) to see what's next, current focus is on improving the developer experience by reducing tina's footprint an improve our API to add editing on top of your website.
