### ISSUE TITLE
Cannot add Nested Blocks without using Inline Blocks

### ISSUE THREAD

**Issue by shire17** [tinacms/tinacms#1757]
## Description

I am currently working with blocks in the TinaCMS sidebar. I would like to have nested blocks. Is this possible without using inline blocks?

I have a CardDeck block that consists of multiple Card blocks. However, when I click on the plus button in the CardDeck block, it does not display any options for blocks to add:

![image](https://user-images.githubusercontent.com/46686978/110221076-a8a8f400-7e8f-11eb-86aa-0f07c8dc42d1.png)

### Steps to reproduce

I can't link the project as it is private, but here is my code for the fields portion of the CardDeck block. I thought because I have 'card-block' in the templates, that the card block would be added as an option with the plus sign:

fields: [
{
name: ‘cards’,
label: ‘Cards’,
component: ‘blocks’,
templates: {
‘card-block’: CardBlock,
},
}
],

When I go to the admin panel and click on the Card Deck block, I get to the screenshot provided.

### Expected result

I would like to click on the plus button and see Card as an option of a block to add

### Actual result

When I click on the plus button, there are no options displayed of blocks to add

#### Tinacms Package Versions

```text
+-- tinacms@0.36.1
| +-- @tinacms/alerts@0.33.0
| +-- @tinacms/core@0.33.0
| +-- @tinacms/fields@0.36.0
| +-- @tinacms/form-builder@0.34.0
| +-- @tinacms/forms@0.33.0
| +-- @tinacms/icons@0.36.0
| +-- @tinacms/react-alerts@0.36.0
| +-- @tinacms/react-core@0.34.0
| +-- @tinacms/react-forms@0.36.0
| +-- @tinacms/react-modals@0.36.0
| +-- @tinacms/react-screens@0.36.0
| +-- @tinacms/react-sidebar@0.36.1
| +-- @tinacms/react-toolbar@0.36.0
| +-- @tinacms/styles@0.33.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  Chrome   |
| os      |    Windows 10  |
| node    |    12.19.0   |
| npm     |    6.14.8   |

**Comment by zenflow** [comment]
Yes I was going to make an issue for this too. "Cannot add block to nested block field in sidebar (+ button does nothing)" 
The first/root block field works fine

**Comment by tschie** [comment]
I noticed this recently as well. I checked the HTML in dev tools and saw that the list was populated correctly, but the opacity was 0. I think the + button just sets the opacity to 1: 

https://github.com/tinacms/tinacms/blob/62e2105fb26878b2c618b0048812cd48c681b3a1/packages/%40tinacms/fields/src/plugins/BlocksFieldPlugin.tsx#L327-L333

I think the visible state is somehow flipping back to false on open.

**Comment by rDuckDev** [comment]
Adding to the intrigue, if you expose the neighboring panel (the root, if you will), then you can trick it into opening.

![tina menu](https://user-images.githubusercontent.com/30515855/110281070-9a4afd00-7fa1-11eb-81ad-2f5e6f47fd62.gif)

For clarity, the _Cards_ panel has the CSS `top` property increased such that the _Page Sections_ field of _another_ panel is exposed.

**Comment by mitchmac** [comment]
I was able to setup a [sandbox reproducing this](https://codesandbox.io/s/tina-sidebar-nested-blocks-lkpsd?file=/src/App.js)

Steps to reproduce:

1. Open sidebar
2. Add a "Deck" block
3. Click into the Deck and try adding a "Card". The button doesn't respond.
