### ISSUE TITLE
gatsby-plugin-tinacms: support Gatsby v3

### ISSUE THREAD

**Issue by v4iv** [tinacms/tinacms#1763]
## Description

Adding TinaCMS to a new gatsby site throws Runtime error:
```
Error in function Mn in ./node_modules/tinacms/build/index.js:1
Cannot read property 'enabled' of undefined
```

Which after analysing, might be in the useCMS hook in the package `/packages/@tinacms/react-core/src/use-cms.ts` where for some reason cms is undefined.

### Steps to reproduce

* Step 1: generate new Gatsby project using `npm init gatsby`
* Step 2: add Tina CMS packages `gatsby-plugin-tinacms` & `styled-components` as well as add `gatsby-plugin-tinacms` to `gatsby-config.js`
* Step 3: add `path` polyfill to Gatsby's Webpack 5 config by adding the following code to `gatsby-node.js`:
```
exports.onCreateWebpackConfig = ({actions}) => {
    actions.setWebpackConfig({
        resolve: {
            fallback: {
                "path": require.resolve("path-browserify")
            }
        },
    })
}
```
* Step 4: Run `gatsby develop` 

### Expected result

A pencil icon should be appear, which you can use to toggle the Tina sidebar.

### Actual result

Runtime error:
```
Error in function Mn in ./node_modules/tinacms/build/index.js:1
Cannot read property 'enabled' of undefined
```

<img width="1063" alt="Screenshot 2021-03-16 at 4 47 18 PM" src="https://user-images.githubusercontent.com/9848613/111300609-4a41f980-8677-11eb-9987-52b0a63ae773.png">

#### Tinacms Package Versions

```text
gatsby-plugin-tinacms@0.38.0
tinacms@0.38.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |    Google Chrome version 89.0.4389.82     |
| os      |    macOS version 11.2.1    |
| node    |     v15.11.0    |
| npm     |    7.6.0    |

**Comment by tomalex0** [comment]
Facing Similar Issue running in `gatsby develop`. mode with `Gatsby v3`

**Comment by DirtyF** [comment]
How did you set up TinaCMS? looks like it's missing some configuration here 🤔

**Comment by v4iv** [comment]
@DirtyF I just followed the TinaCMS official guide for Gatsby <https://tina.io/guides/gatsby/adding-tina/project-setup/>

```javascript
module.exports = {
  // ...
  plugins: [
    {
      resolve: 'gatsby-plugin-tinacms',
      options: {
        // The CMS will be disabled on your production site
        enabled: process.env.NODE_ENV !== 'production',
        sidebar: true,
        plugins: [
          // We'll add some gatsby-tinacms plugins later
        ],
      },
    },
    // ...
  ],
}
```

**Comment by v4iv** [comment]
@tomalex0 I'm using Gatsby v3 as well

**Comment by tomalex0** [comment]
> How did you set up TinaCMS? looks like it's missing some configuration here 🤔

@DirtyF  was this question for me ?

**Comment by aronmartin** [comment]
Same here!

**Comment by rossng** [comment]
It was a little hard to debug this because TinaCMS' code is pre-minified. But the crash seems to be happening [here in `use-cms.ts`](https://github.com/tinacms/tinacms/blob/62e2105fb26878b2c618b0048812cd48c681b3a1/packages/%40tinacms/react-core/src/use-cms.ts#L33).

After sticking in some breakpoints, it seems that the issue lies in the design of [`gatsby-browser.tsx`](https://github.com/tinacms/tinacms/blob/4f0908934ae71c069d06f9b3db8b2fda031343c1/packages/gatsby-plugin-tinacms/gatsby-browser.tsx). It uses `onClientEntry` to instantiate the `TinaCMS` object and attach it to `window`. Then it passes `window.tinacms` into the provider in `wrapRootElement`. Unfortunately, during my testing, `onClientEntry` executed *after* `wrapRootElement`. I wonder if this behaviour changed in Gatsby 3?

**Comment by mweitzen** [comment]
I'm not sure the issue, but if you pass `{ manualInit: true }` to your options param in `gatsby-config.js`, you can set up `TinaProvider` manually in your `gatsby-browser.js` file. Import the `TinaProvider` and `TinaCMS` in `gatsby-browser.js`. Use the [wrapRootElement](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#wrapRootElement) API to initialize your TinaCMS and pass it the the TinaProvider manually. It worked for me! Hope this helps!

**Comment by tomalex0** [comment]
@mweitzen  how did you passed the plugins for tinacms from `gatsby-browser`

```
{
      resolve: "gatsby-plugin-tinacms",
      options: {
        enabled: process.env.NODE_ENV !== "production",
        sidebar: true,
        manualInit: true,
        plugins: [
          "gatsby-tinacms-git",
          "gatsby-tinacms-remark",
          "gatsby-tinacms-json",
        ],
      },
    }
```

**Comment by patbranchaud** [comment]
> I'm not sure the issue, but if you pass `{ manualInit: true }` to your options param in `gatsby-config.js`, you can set up `TinaProvider` manually in your `gatsby-browser.js` file. Import the `TinaProvider` and `TinaCMS` in `gatsby-browser.js`. Use the [wrapRootElement](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#wrapRootElement) API to initialize your TinaCMS and pass it the the TinaProvider manually. It worked for me! Hope this helps!

@mweitzen if you can, could you elaborate just a little bit more on how to do that? It just doesn't work for me..

**Comment by patbranchaud** [comment]
> > I'm not sure the issue, but if you pass `{ manualInit: true }` to your options param in `gatsby-config.js`, you can set up `TinaProvider` manually in your `gatsby-browser.js` file. Import the `TinaProvider` and `TinaCMS` in `gatsby-browser.js`. Use the [wrapRootElement](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#wrapRootElement) API to initialize your TinaCMS and pass it the the TinaProvider manually. It worked for me! Hope this helps!
> 
> @mweitzen if you could elaborate just a little bit more on how to do that? It just doesn't work for me..

Nevermind, managed to make it work finally!

**Comment by DirtyF** [comment]
See https://github.com/tinacms/tinacms/issues/2067#issuecomment-908411715
