### ISSUE TITLE
Copyright information needs updating

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#1778]
## Description

In some files in this repo and other repos, the copyright information needs to be updated. 

For example this
```
/**
Copyright 2019 Forestry.io Inc
Licensed under the Apache License...
```

Should become this (notice company name and year): 
```
/**
Copyright 2021 Forestry.io Holdings, Inc.
Licensed under the Apache License...
```

**Comment by skShekhar** [comment]
Can I take this up? Looks like there are around 600 files to be updated.
