### ISSUE TITLE
Uploaded images should be committed to the repo

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#178]

**Comment by jamespohalloran** [comment]
@ncphillips This one can be closed, right?

**Comment by ncphillips** [comment]
I don’t think so? I don’t think I implemented this

**Comment by jpatters** [comment]
I can confirm that this has not been implemented. Thoughts on how this should work? There are two scenarios.

1. when pushOnCommit is true
1. when pushOnCommit is false

With 1. we could simply commit and push when the image is uploaded. With 2. it's a bit more complicated. Should the page be expected to know about the file and send it along with the put request to be committed with the page when it is saved? Should the uploaded file be committed but not pushed? etc.

**Comment by ncphillips** [comment]
IMO I would adhere to pushOnCommit but always commit the file.

Once the media manager is more feature complete they delete it from there afterwards

**Comment by jpatters** [comment]
That is probably the easiest route.

**Comment by jpatters** [comment]
#734 addresses this
