### ISSUE TITLE
Inline settings modal field/submission issues

### ISSUE THREAD

**Issue by ezg27** [tinacms/tinacms#1780]
## Description

First of all I really love what you guys are building with Tina, it's a great editing experience and a real win for making interactive content management accessible to non-devs in our team 🎉

However I've run into a few bugs with the inline editing experience, specifically using the Inline Settings modal and nested fields inside Group, Group List and Blocks fields. I would love to use Inline Blocks to their fullest in my current project, but I'm having to fall back to the sidebar and standalone Inline elements for now.

All of these issues are reproducible in the demo linked from the Tina homepage (https://tina-demo-two.vercel.app), and in the tinacms repo's demo projects that use the above elements.

1. When clicking into a group/group-list/block, the first interaction with any field inside it (e.g. the first keypress inside a focused input/textarea, clicking a toggle) will retrigger the enter animation from the first form page and cause the active field to lose focus.
2. When clicking into a group/group-list/block, if there is another group/group-list/block nested inside it these items won't respond to clicks and you will not be able to proceed deeper into the form. However, if you click the back button and re-enter the group/group-list/block, the previously inaccessible fields will now work as expected. Furthermore, attempting to interact with any fields inside the newly accessible group/group-list/block will retrigger the enter animation mentioned in point 1 above, except you are returned to the previous page and must perform the 'go-forward-to-go-back' steps again in order to get back to where you were.
3. Specifically with group-lists (and sometimes groups, see 2nd video below), editing them in any way (either by dragging to reorder, deleting an item, editing any of the fields nested within a group-list item) causes the `Form Status` field in the toolbar to show `Unsaved changes` in the background as expected. But if `Confirm` is clicked without editing any other fields, the status returns to `No changes` and the changes cannot be saved, even though they can still be seen on the page. If you re-open the inline settings menu the `Form Status` shows in the background that there are unsaved changes, but this does not persist when closing the settings modal.

None of these issues appear to exist when using the same fields in the sidebar, everything functions seamlessly there. My suspicion is this is caused by stale form state/re-rendering issues related to React Final Form in the inline package, but I haven't been able to diagnose so far when running the tinacms repo demo's locally.

### Steps to reproduce

1.

https://user-images.githubusercontent.com/40216869/112761787-cc75da80-8ff4-11eb-9986-52d9ed942f26.mp4

2.

https://user-images.githubusercontent.com/40216869/112761799-da2b6000-8ff4-11eb-9caf-4e82e0de96b6.mp4

3.

https://user-images.githubusercontent.com/40216869/112761806-e3b4c800-8ff4-11eb-8975-fdf2df6036fe.mp4

### Expected result

1. When clicking into a group/group-list/block in the inline settings modal and interacting with a field (e.g. typing into an input, clicking a toggle), the respective field works normally.
2. When clicking into a group/group-list/block in the inline settings modal and attempting to click into another nested group/group-list/block, it opens the the nested item normally as expected.
3. When editing group-list items in the inline settings modal, clicking `Confirm` should update the form status to `Unsaved changes` in the toolbar and allow the changes to be saved.

### Actual result

1. When clicking into a group/group-list/block in the inline settings modal and interacting with a field (e.g. typing into an input, clicking a toggle), the enter animation is re-triggered and causes the field that was being used to lose focus.
2. When clicking into a group/group-list/block in the inline settings modal and attempting to click into another nested group/group-list/block, the nested item is unresponsive and you must click back and re-enter the current page to make them accessible.
3. When editing group-list items in the inline settings modal, clicking `Confirm` does not update the `Form Status` to `Unsaved changes`.

#### Tinacms Package Versions

(These are from the tina-demo project, however the above issues are also present when using 0.38.0 of `tinacms`, and 0.37.0 + 0.38.0 of `react-tinacms-inline`)

```text
"tinacms": "0.37.0"
"react-tinacms-inline": "^0.39.0-alpha.1",
```

**Comment by spbyrne** [comment]
Thanks for reporting these and breaking down the issues with videos! We're trying to track down the issue. I believe it may have something to do with the fact the sidebar uses the full form component, while the modal is using a stripped down form in order to handle saving/clearing differently.

**Comment by ezg27** [comment]
No worries, thanks for responding! :)
Ahh interesting, I was looking at the plugins themselves to see if there was a common pattern that might be causing issues, but that idea sounds plausible if the form itself is handled differently between sidebar and toolbar/modal. I’ll take another look when I get chance tomorrow evening, will update if I find anything 👍

**Comment by c58** [comment]
Ough, few hours of my life are gone due to this bug. Hopefully, you will accept the PR and release it soon, it is really annoying.

**Comment by c58** [comment]
Ok, I found what causes the second issue, and it is related with FormPortal again. It is because of z-index. When you are in a group field (1 level), the Panel is rendered under the portal element and everything great. But when you go deeper and opens another group (2 level), the second Panel could be added to the portal element before or after the Panel of the level one Panel, and since we have no z-index management, If the second one added before the first one it won't be visible.

So, to fix that I see no other way than to introduce some kind of zIndex management, but it requires more than one line of code that I did so far :) The only idea I have right now is to convert FormPortal to a component that manages the z-Index and provide it to the children via children function, so the child will have to set provided zIndex where needed.

**Comment by ezg27** [comment]
Ahh amazing @c58! Confirmed first PR fixes the rerender issues, nice one on the z-index management too!

Re the 3rd issue, I can still reproduce in the `demo-next` project and the Tina Tailwind Demo (after fixing the first issue in the source).

It’s very weird - in `demo-next`, it affects fields in the two InlineGroups on the Nesting page: `hero.description`, `hero.toggle` and `author.description`, but interestingly not the fields inside `author.colors`. In the tailwind demo, the issues with nav fields in the 3rd video above still persist after updating the source with the wrapperRef fix.

However in both of these examples, if you enable the sidebar and add the same fields to the `useForm` config, the issue stops (see video of tailwind demo below). This perhaps explains why the InlineGroup on the Info page in `demo-next` isn’t affected.

This might tally with what @spbyrne mentioned above, that the inline modal only uses a stripped down version of the form? I’ve been having a look at `Toolbar.tsx` in the inline package to see if it's a subscription issue.


https://user-images.githubusercontent.com/40216869/114303989-b8d47480-9ac8-11eb-97fd-bb7aacdb356d.mp4

**Comment by c58** [comment]
Hm, I see. I tried in my project a similar "fields" configuration and it worked fine. I will try to reproduce it in demo-next

**Comment by ezg27** [comment]
Apologies I’ve been on a tight deadline so not had chance to look at this again until now. I’ve done a bit more investigation though and think I know how that 3rd issue is happening, but not yet why.

It seems to be specific to fields that are only registered via the `fields` prop of the `InlineGroup` component, and don’t have a corresponding inline field on the page or one in the sidebar. If this is the case, then `Toolbar.tsx` rerenders when Confirm is clicked, and a new instance of the form is created with `pristine` and `dirty` set to `true` and `false` respectively, even though the `values` contain the new changes.

I haven’t yet managed to figure out why `Toolbar.tsx` rerenders on clicking `Confirm` in this scenario, but not when a field is also registered inline or in the sidebar.
