### ISSUE TITLE
Group-list enhancements

### ISSUE THREAD

**Issue by GregoryPotdevin** [tinacms/tinacms#1793]
## Summary

Group-list could have a few quick and easy feature enhancements : 
- `itemProps: (item) => ({ key, label })` could be changed to `itemProps: (item, index) => ({ key, label })` to allow using the index to generate a label
- `addItem` could use a flag on the field to decide if the item should be added at the beginning or at the end of the list

Both changes feel pretty basic, just wondering if you would be interested in such enhancements, I can work on a quick PR for those.

### Basic example

`addItem` flag : 
```
    {
      name: 'files',
      label: 'Files',
      component: 'group-list',
      addPosition: 'end', 
      itemProps: (item) => ({
        key: item._id,
        label: item.title || 'Video',
      }),
      fields: [
        [...]
      ],
    }
```

Sample use case for `itemProps: (item, index)` :
```
    {
      name: 'files',
      label: 'Files',
      component: 'group-list',
      itemProps: (item, index) => ({
        key: item._id,
        label: item.title || `Video ${index+1}`,
      }),
      fields: [
        {
          name: 'title',
          label: 'Title',
          component: 'text',
        },
        [...]
      ],
    }
```

### Motivation

Would help customize the behavior for some pretty basic needs. When adding items to a list in our editor, we generally want them added at the end.

**Comment by DirtyF** [comment]
🤔 If you prefet to have it always at the end, should we add a config to each group list for the direction preference or could that be some generic setting to allow defining the items order for all lists? There should be at least a default convention, to make this optional. The less setup the better.

If you do submit a PR, please address a single issue at a time. 🙏

**Comment by GregoryPotdevin** [comment]
Thanks for the feedback, yes, each PR would have a single issue, I wasn't sure it was worth spamming the issue tracker with 2 minor enhancements if you didn't find this interesting.
I'll check out the code some more. Having generic settings at the group-list level (or for all lists) could indeed be easier.

**Comment by joshuafcole** [comment]
I'm interested in adding the ability to add items to either the beginning or end of the list via configuration. I'd be happy with either approach (single global config or per field config) though I think the latter is probably slightly better in the case that your CMS contains both feed-ish content like posts (which prefers the current stack insertion) and generic structural content.

Would you accept a PR adding either/both?
