### ISSUE TITLE
'options' does not exist in type 'Field<AnyField>' when using InlineGroup

### ISSUE THREAD

**Issue by Juje** [tinacms/tinacms#1800]
Hi all,

So I recently started using TinaCms and I am going to say that this is an amazing piece of software and I had a great first experience with it until now.

So when I tried using the `<InlineGroup />` system I wanted to add a select field but this failed cause I am using TypeScript. And it threw an error from this code:

```jsx
<InlineGroup name="blocks" fields={[
    {
        name: 'blocks.cols',
        label: 'Cols',
        component: 'select',
        options: [
            'grid-cols-3'
        ],
    }
]}>
    ...
</InlineGroup>
```

And the error that I've got was the following:

```
TS2322: Type '{ name: string; label: string; component: string; options: string[]; }' is not assignable to type 'Field<AnyField>'.
Object literal may only specify known properties, and 'options' does not exist in type 'Field<AnyField>'.
```

Which is kind of weird cause I almost literally copied the code from the docs at https://tina.io/docs/ui/inline-editing/inline-group/#definition even using those examples caused issues.

So I went on mission to find out why and it turned out that the definition for `InlineGroupProps` uses `Field[]` and not `AnyField[]` which is used in other places.

https://github.com/tinacms/tinacms/blob/80fc1e7793b31b2d353101129af48fa59d188456/packages/react-tinacms-inline/src/inline-group/inline-group.tsx#L28

FYI. I saw that a related issue was created https://github.com/tinacms/tinacms/issues/1603 but it seems that it was disregarded because of some replication issue.

So my question is what I should do or does a change need to happen for the definition?

**Comment by Juje** [comment]
Okay, so for now I did find a workaround.
By using a variable the type-checking doesn't fail.
So the above example can be fixed using this way:

```jsx
const = fields = [
    {
        name: 'blocks.cols',
        label: 'Cols',
        component: 'select',
        options: [
            'grid-cols-3'
        ],
    }
];

<InlineGroup name="blocks" fields={fields}>
    ...
</InlineGroup>
```

**Comment by DirtyF** [comment]
@Juje Right, it's also what we do.

**Comment by Juje** [comment]
Okay, so should I close this issue or?

**Comment by DirtyF** [comment]
Nah, it's OK, our team should know about this, and if it leads to errors we should fix our docs.

**Comment by Juje** [comment]
Okay, thanks for the information :slightly_smiling_face:.
