### ISSUE TITLE
feat: provide a sane default width for the sidebar

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#1811]
## Background

Since Tina 0.40.0, the sidebar can be resized, this is a great feature. The thing is I find myself having to increase this width every time I go into edit mode to match my optimal preference. It would be nice if I could provide a better default once for all. Usually I use something closer to half the width of the screen especially when using a WYSIWYG editor. 
Your mileage may vary.

### Example

![image](https://user-images.githubusercontent.com/103008/117268942-1e154e80-ae58-11eb-961b-e5dc3bfbc77c.png)
When editing a long content format, you need a wider sidebar.

### Possible solution

```json
const tinaOptions = {
  enable: true,
  sidebar: [true, options: {width: "50vw"}],
  toolbar: false,
};
```

Even better if Tina automatically adapts the sidebar width when a WYSIWYG field is present.

### Value

Provide a sane default editing experience for your editors, avoid tedious and repetitive manual resizing every time they edit a page.

**Comment by spbyrne** [comment]
The sidebar is designed to set its initial width from CSS property, which can be set by the user to a custom value. I'm having problems getting this behaviour to work, and it was limited to begin with to only `px` values. I think making this more flexible would be a great idea.

I think an another improvement would be storing the sidebar width in local storage so it's persistent across loads once the user drags it to a custom width.

**Comment by spbyrne** [comment]
I tested and you can set the initial width in CSS. Here's an example:
```
<style global jsx>{`
  :root {
    --tina-sidebar-width: 800px !important;
  }
`}</style>
```
I'll see about opening this up to other units or saving to local storage.
