### ISSUE TITLE
TinaCMS is not tree-shakable

### ISSUE THREAD

**Issue by chrisdmacrae** [tinacms/tinacms#1818]
## Description

TinaCMS is bundled as CommonJS bundle only, meaning Webpack and Rollup can't statically analyze them for tree shaking, as tree shaking is only supported for ES Modules

### Steps to reproduce

1. Install tinacms
2. Import tinacms
3. See that all dependant code of `tinacms` is included in the built app no matter what concrete implementation is imported
  4. Try `webpack-bundle-analyzer` 

### Expected result

TinaCMS is deployed with both a commonJS module assigned to `main` in `package.json`, and an ES module assigned to `module` in `package.json`.

Also, the `tinacms` and other packages [specify `sideEffects` in `package.json` for webpack tree shaking support](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) . 

FYI: this logic existed in the studio prototype.

### Actual result

No tree shaking.

#### Tinacms Package Versions

Only `tinacms@latest|0.40.0`

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |    Chrome     |
| os      |    Windows 10     |
| node    |    14.16.2     |
| npm     |      6.x.x   |

**Comment by DirtyF** [comment]
Hey Chris 😄 

Are you saying, it's time to [say hello to ESM modules](https://blog.sindresorhus.com/hello-modules-d1010b4e777b)?

**Comment by chrisdmacrae** [comment]
@DirtyF hey-o!

This is currently a pretty big deal, as importing _anything_ from `tinacms` (with or without the react UI stuff) adds 100kb gzipped (~300kb unminified) to your application JS.

**Comment by DirtyF** [comment]
@chrisdmacrae Did you try loading TinaCMS dynamically or through a custom route to minimize the impact on production?

**Comment by chrisdmacrae** [comment]
@DirtyF webpack and rollup rely on the ES Module syntax for tree shaking:

```
// index.js
export * from './example';

// example.js
export const Example = () => <h1>I am an example</h1>
export const OtherExample = () => <1>I am another example</h1>
```

It actually parses the modules as text files and finds the `export` and `import` statements, and builds a map of what the code _actually_ depends on.

So if you had code like:

```
import { Example } from 'example-package';
```

It's able to go "Oh, you specifically _only_ imported `Example` from that library -- I'll only take its code along with me.

In fact, if you do _glob_ imports like: `import * as Thing from 'example-package';`, you break tree shaking.

CommonJS creates modules that look like:

```
const exports = module.exports;

exports.Example = () => <h1>I am an example</h1>
exports.OtherExample = () => <h1>I am another example</h1>
```

This means that from a static analysis perspective, `exports` is the _only_ real export from this module -- all of `Example` and `OtherExample` are _properties_ of that main export. So it can't tree shake them, because it would actually break the code.

Since TinaCMS is built as a series of commonJS bundles, none of them can be tree shaken. The `tinacms` package imports a _handful_ of things from `@tinacms/forms`, `@tinacms/react-sidebar`, etc. Mainly for types and such.

But because it does this, _the entire package gets bundled_ when using _anything_ from the `tinacms` bundle, even if you didn't import any of the TinaCMS react UI.

**Comment by jamespohalloran** [comment]
Closing now that we have TinaEditProvider to dynamically import Tina
