### ISSUE TITLE
"module" field of next-timacms-markdown package points to nowhere

### ISSUE THREAD

**Issue by c58** [tinacms/tinacms#1824]
## Description

I'm playing with ESM building tools, like WMR or Vite, and I found that "module" field of "next-tinacms-markdown" package points to a non-existing file

### Steps to reproduce

Nothing to reproduce really, just look at the package published in NPM and find that the file "dist/next-tinacms-markdown.esm.js" doesn't exist, but it should since it is used in the "module" field of "package.json".

### Expected result

The file "dist/next-tinacms-markdown.esm.js" should be there in the built package.

### Actual result

The file is not there

**Comment by c58** [comment]
Same with "react-tinacms-editor"

**Comment by DirtyF** [comment]
Right, we don't provide ES Modules for now, see #1818

**Comment by c58** [comment]
Great, thanks for the reference! But until TinaCMS support it there is no reason to have the "module" field in the package.json at all, especially that points to a non-existing file :)
