### ISSUE TITLE
Radio group field is not responsive 

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#1825]
## Description

When using the radio group field button variant and you resize the sidebar the button does not resize with it.

Video: https://www.loom.com/share/1366454af483429d9596d27052c37b26

cc @spbyrne

**Comment by DirtyF** [comment]
The whole sidebar is not responsive, as it was just set loose of it's default fixed with, same happens with other components like buttons and such.

**Comment by jeffsee55** [comment]
There are some low-level issues with the way this is handling refs. Tabling the animation challenges and keeping it simple will allow us to move forward quickly

**Comment by logan-anderson** [comment]
As far as I can tell we are not using this UI anymore
