### ISSUE TITLE
Pointer event issue with BlockMenuWrapper

### ISSUE THREAD

**Issue by Juje** [tinacms/tinacms#1834]
## Description

So I was working on a block that needed to have `insetControls` but when I enabled it I couldn't click on my `InlineTextarea`. And so I found out that I was clicking on the `BlockMenuWrapper` on not on the `InlineTextarea` box.

After further investigation I found out that there was a setting to prevent this with `pointer-events: none` but it was set to the `BlockMenuSpacer` but this doesn't do anything because then you just click on the `BlockMenuWrapper`.

So I found a quick solution for me but of course someone else might have this issue too.
When I put the following around the `BlocksControls` the problem is fixed :slightly_smiling_face:.

```tsx
const StyledContainer = styled(Container)`
    > div > div:nth-child(2) {
        pointer-events: none;

        > div {
            pointer-events: auto;
        }
    }
`;
```

Of course a full fix would require these settings to be set on BlockMenuWrapper, BlockLabel & BlockMenu.

### Steps to reproduce

1. Have a `BlockControls` with the option of `insetControls`.
2. Give the `focusRing` the following details `{ offset: { x: -1, y: 15 }, borderRadius: 10 }`.
2. Insert a `InlineTextarea` as a child of `BlockControls`.
3. Run it in the browser and you will find that clicking on the `InlineTextarea` is almost impossible.

### Expected result

I should be able to click on the `InlineTextarea` even if the `BlockMenuWrapper` is hovering over it.

### Actual result

A dead click on the `BlockMenuWrapper`.

#### Tinacms Package Versions

```text
├─┬ react-tinacms-editor@0.40.1
├─┬ react-tinacms-inline@0.40.1
├─┬ tinacms@0.39.0
│ ├── @tinacms/alerts@0.39.0
│ ├── @tinacms/core@0.39.0
│ ├─┬ @tinacms/fields@0.39.0
│ ├─┬ @tinacms/form-builder@0.39.0
│ ├─┬ @tinacms/forms@0.39.0
│ ├── @tinacms/icons@0.39.0
│ ├── @tinacms/react-alerts@0.39.0
│ ├─┬ @tinacms/react-core@0.39.0
│ ├─┬ @tinacms/react-forms@0.39.0
│ ├── @tinacms/react-modals@0.39.0
│ ├── @tinacms/react-screens@0.39.0
│ ├─┬ @tinacms/react-sidebar@0.39.0
│ ├─┬ @tinacms/react-toolbar@0.39.0
│ ├─┬ @tinacms/styles@0.39.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Vivaldi (Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.79 Safari/537.36) |
| os      | Ubuntu   |
| node    | v14.15.4 |
| npm     | 6.14.10  |

**Comment by DirtyF** [comment]
@Juje Can you reproduce the issue with the latest TinaCMS package, I wonder if we didn't change something related to pointer events recently @spbyrne?

**Comment by Juje** [comment]
Okay that was odd. I had too manually change the versions to get the latest packages :thinking:.
But these are my versions now:

```
├─┬ react-tinacms-editor@0.41.0
├─┬ react-tinacms-inline@0.41.0
├─┬ tinacms@0.41.0
│ ├── @tinacms/alerts@0.39.0
│ ├── @tinacms/core@0.39.0
│ ├─┬ @tinacms/fields@0.41.0
│ ├─┬ @tinacms/form-builder@0.39.0
│ ├─┬ @tinacms/forms@0.39.0
│ ├── @tinacms/icons@0.39.0
│ ├── @tinacms/react-alerts@0.40.0
│ ├─┬ @tinacms/react-core@0.39.0
│ ├─┬ @tinacms/react-forms@0.40.0
│ ├── @tinacms/react-modals@0.40.0
│ ├── @tinacms/react-screens@0.40.0
│ ├─┬ @tinacms/react-sidebar@0.40.1
│ ├─┬ @tinacms/react-toolbar@0.41.0
│ ├─┬ @tinacms/styles@0.40.0
```

but sadly the issue was not fixed :slightly_frowning_face:.
