### ISSUE TITLE
Do not load font from google by default

### ISSUE THREAD

**Issue by davidpfahler** [tinacms/tinacms#1836]
## Description

While not a technical bug (as the font is loaded as intended), [loading a font from Google Fonts](https://github.com/tinacms/tinacms/blob/80fc1e7793b31b2d353101129af48fa59d188456/packages/%40tinacms/styles/src/FontLoader.tsx#L25) is a bug from a user perspective. As a user of TinaCMS in the EU, I would like to be able to use TinaCMS in compliance with applicable data protection law, in particular the GDPR. Loading fonts from google without the user's consent violates the GDPR.

### Steps to reproduce

Use TinaCMS.

### Expected result

Either load the required font from same origin or - preferably - just use a sensible system font, like so:

`font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
    "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol",
    "Noto Color Emoji";`

### Actual result

Font gets loaded from Google Fonts.

**Comment by DirtyF** [comment]
Good catch @davidpfahler
