### ISSUE TITLE
Allow localization / translation of labels in the Media Manager

### ISSUE THREAD

**Issue by fabarea** [tinacms/tinacms#1837]
## Summary

I would like to translate some labels in the Media Manager
Perhaps the translation of labels is already possible, but I was not able to find how to proceed.

### Basic example

This issue is somehow related https://github.com/tinacms/tinacms/issues/620

### Motivation

We need a translated UI for our client

<img width="976" alt="image" src="https://user-images.githubusercontent.com/620730/120097526-36b01600-c131-11eb-84d9-4c18404a61c9.png">

**Comment by DirtyF** [comment]
@logan-anderson Does the react-i18n plugin support the media manager?

**Comment by logan-anderson** [comment]
Unfortunately it does not at the moment.

**Comment by logan-anderson** [comment]
Still relevant
