### ISSUE TITLE
Combine `FormView` and `FormBuilder`

### ISSUE THREAD

**Issue by Enigmatical** [tinacms/tinacms#1840]
Full pitch: https://github.com/tinacms/product/discussions/8

> ...Tina Forms display and behave differently depending on where they are built and this functionality is at the whim of how they are plugged into the CMS.

> Referencing the diagram once more, only Sidebar and Screen Forms use <FormView /> which contains <DragDropContext />, <FormPortalContext /> and support for <FormActionMenu />.

> `Content Creator Plugins` (and `BranchSwitcher`) only utilize `<FormBuilder />` which does not have `<DragDropContext />` and offers limited customization of the `<FormHeader />` and `<FormFooter />` (more than likely because the form is split into parts for the `<Modal />`).

### Objectives

Combine `<FormView />` and `<FormBuilder />`

**Comment by jeffsee55** [comment]
- [ ] Formalize actions array as a singular structure for handling what can happen in and around a form
- [ ] Actions may behave differently and should have improved type definitions/documentation

**Comment by Enigmatical** [comment]
Reopened by https://github.com/tinacms/tinacms/pull/1857#pullrequestreview-686652287
