### ISSUE TITLE
Support cursor-based media manager pagination

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1842]
Right now the media manager assumes an "offset"-based pagination. But that doesn't work for many digital asset management APIs. Ideally we can invert that control to the given media manager's implementation.

**Comment by jeffsee55** [comment]
Related to https://github.com/tinacms/tinacms/pull/1819 and https://github.com/tinacms/tinacms/pull/1838

**Comment by jeffsee55** [comment]
Consider whatever breaking changes to the media list interface (or any interface in the [media implementation](https://tina.io/docs/media/)) are ok in order to get this up and running. We'll reevaluate the API once we have a production-ready Cloudinary implementation.

**Comment by dwalkr** [comment]
proposed: remove `limit, offset, totalCount` from `MediaList`. add `prevOffset`. Make `nextOffset` required. this is a breaking change that will require a small migration for any existing `MediaStore` implementation.

**Comment by jeffsee55** [comment]
Github and Strapi media packages should reflect these changes as well, likely meaning we'll need to do some arithmetic from within those packages
