### ISSUE TITLE
Inconsistent `onSubmit` depending on type of form plugin

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1860]
The `onSubmit` signature is different depending on how the form is registered (screen plugin, content creator, sidebar, etc)

**Comment by Enigmatical** [comment]
This issue stems from a conversation in our Discord:

> i subscribed to all events and logged them in console to see which events are being logged. Isn't screen-plugin form treated as a form? I dont see any events from screen-plugin forms(edited)...
> I find all that all plugins have a very inconsistent onSubmit() signature. The content-creator gets a cms object as a param whereas a screen-plugin or sidebar form doesnt get the cms object. Also form events seems to be dispatched only for sidebar forms.

Going to investigate if this behavior is still inconsistent now that https://github.com/tinacms/tinacms/pull/1858 and https://github.com/tinacms/tinacms/pull/1855 have been merged.

In theory, everything (_not_ inline, but `ContentCreator`, Sidebar, and Screen) should be routing through the new `<FormBuilder />` component and should have a consistent API.

**Comment by Enigmatical** [comment]
Unsurprisingly, this is a bit more complicated than it initially appears.

While the issue at hand is _core_ to the "Form Inconsistencies" pitch, solving this particular problem has potential to introduce breaking changes to nearly every use of `useForm(...)` so before I take a stab at correcting it, I want to lay out all the facts and get some feedback.

While it is true that the rendered structure of a Tina Form has been made consistent with `<FormBuilder />`, the configuration of a `ContentCreator` Plugin still differs from that of `useForm(...)`.

`ContentCreator` is, by Tina's own admission, a simpler interface.  It makes no assumptions about the content it is creating and expects the user to supply the `onSubmit()` methods:

https://tina.io/docs/plugins/content-creators/#building-a-contentcreatorplugin
```ts
//onSubmit(values: FormShape, cms: CMS): Promise<void> | void

onSubmit: async values => {
  await plugin.onSubmit(values, cms).then(() => {
    close()
  })
},
```

In contrast, `useForm(...)`'s `onSubmit()` is directly mapped to Final Form's:

```ts
// onSubmit(values: FormShape, form: FormApi, callback: Promise<void> | void)

onSubmit: Config<S>['onSubmit'] // Config is from final-form

private handleSubmit: Config<S>['onSubmit'] = async (values, form, cb) => {
  try {
    const response = await this.onSubmit(values, form, cb)
    form.initialize(values)
    return response
  } catch (error) {
    return { [FORM_ERROR]: error }
  }
}
```

In most usecases, this `onSubmit()` is entirely optional (and often entirely omitted).  Nearly all variations of `useForm(...)` (for example, `useJsonForm()`, `useGitHubForm()`, `useMarkdownForm()`) implement their own `onSubmit()` that ties directly to the `cms` and the `client`:

```ts
// From use-markdown-form.ts

onSubmit() {
  return cms.api.git.commit({
    files: [markdownFile.fileRelativePath],
    message: `Commit from Tina: Update ${markdownFile.fileRelativePath}`,
  })
},
```

Ideally, we'd want the `onSubmit()` signature to be universally consistent.  

For example:
```ts
onSubmit(values: FormShape, cms: CMS, form: FormApi, callback?: Promise<void> | void)
```

One suggestion from DJ was to embed the `cms` instance in the `Form` when attached via `usePlugin()` (perhaps make `_cms` a private property) and provide it back:

```ts
private handleSubmit: Config<S>['onSubmit'] = async (values, form, cb) => {
  try {
    const response = await this.onSubmit(values, form, cb, this._cms) /** like this **/
    form.initialize(values)
    return response
  } catch (error) {
    return { [FORM_ERROR]: error }
  }
}
```

**Comment by jeffsee55** [comment]
> Ideally, we'd want the onSubmit() signature to be universally consistent.

I think it's ok that higher-level abstractions don't _require_ `onSubmit`, `useGitHubForm` should allow `onSubmit`, but not require it, while `useForm` should require it. Having said that, yes 100% their payloads should be the same IMO, so the only difference would be `onSubmit: ...` vs `onSubmit?: ...`. 

But one thing that's implicit here is this indirect relationship between Tina's API and the underlying API client you're wired up for. We expose _everything_ as if they're equal, but `useForm` is low-level, and I think we should insist that it's not for _direct_ consumption, but should instead be used internally for specific client development. As an example, saying that this is the wrong way to do things might go a long way:
```jsx
// top of tree:  Initialize the CMS with an api client and wrap your site in it
<TinaProvider cms={new CMS({api: {myClient: new MyClient())} />...

// further down in the stack
const cms = useCMS()
// When you need to do something, pop the client off of the CMS object:
const [values,] = useForm(..., onSubmit: (payload) => cms.api.myClient.doThing(payload))
```
You should instead build things like we've done with Tina Cloud:
```jsx
import { MyClientProvider, useMyClientForm } from 'my-client-package'
// top of tree:  Initialize the CMS with an api client and wrap your site in it
<MyClientProvider >...

// further down in the stack
const [values,] = useMyClientForm(...)
```
To achieve this, I think we'd need to become more opinionated about how to build with Tina, but using Tina Cloud as a North star seems like the right approach, meaning `tinacms` modules are meant to be wrapped by a client-specific package. That's a pretty aggressive opinion, but it seems easier to grok

**Comment by jeffsee55** [comment]
This will be resolved with the useGraphQLForms refactor https://github.com/tinacms/tinacms/issues/2417
