### ISSUE TITLE
Add `object` field plugin

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1861]
We're going to be introducing a series of more primitive shapes to Tina. 

Initial work on this should essentially wrap the `group`, `group-list`, and `blocks` fields and just switch on whatever one is appropriate for now. 

Determine strategy for `block` (singular) behavior

**Comment by logan-anderson** [comment]
@jeffsee55 can this be closed?

**Comment by jeffsee55** [comment]
Not yet since we don't have `object` as a core field

**Comment by jamespohalloran** [comment]
object field is available: https://tina.io/docs/reference/types/object/
