### ISSUE TITLE
Allow internal blocks logic to not be an array automatically

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1862]
Currently when you have an object with `templates`, there's no way to only allow 1 item, it must be a list. 

> My use case is, someone can add a component, that component can contain ONE of a: youtube video, image, form, etc.  each of these would be a template because they have their own unique fields.

```ts
{
  // Note the lack of `list: true` here
  type: 'object', 
  name: 'feature',
  templates: [{
    name: 'video',
    fields: [{
      type: 'string',
      name: 'url',
    }]
  }, {
    name: 'contactForm',
    fields: [{
      type: 'string',
      name: 'emailAddress',
    }]
  }]
}
```

While this is supported from the GraphQL side, the UI doesn't accommodate this (see the underlying [BlocksFieldPlugin](https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/packages/fields/plugins/BlocksFieldPlugin/index.tsx)).

**Comment by jeffsee55** [comment]
Not stale

**Comment by jamespohalloran** [comment]
Do you mind clarifying in the description what this is about, and what impacts it has? @jeffsee55

**Comment by llibdude** [comment]
Alternatively, and possibly a different feature, is to allow an item limit to be set on lists in the configuration.  Then we could set a limit of 1 to solve (at least my) issue of wanting a single item instead of allowing a list.  Certainly there are use cases out there for preventing lists from exceeding a specific number.

**Comment by llibdude** [comment]
keep alive

**Comment by jeffsee55** [comment]
Not stale
