### ISSUE TITLE
`blocks` should take an array of templates instead of an object

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1863]

**Comment by jeffsee55** [comment]
Not stale

**Comment by jamespohalloran** [comment]
Do you mind adding some info to this description @jeffsee55 ? In the schema.ts, looks like templates takes an array but I'm guessing I'm looking at the wrong place. 

Does this relate to: https://github.com/tinacms/tinacms/issues/1862 ?

**Comment by jeffsee55** [comment]
For the blocks field plugin (in `@tinacms/toolkit`) we provide an object:

```ts
{
  component: 'blocks',
  templates: {
    cta: {...}
  }
}
```
But we'd like for it to match the schema way instead:

```
```ts
{
  component: 'blocks',
  templates: [
    name: 'cta',
    ...
  ]
}
```
```

**Comment by jeffsee55** [comment]
Not stale
