### ISSUE TITLE
tina.io open authoring doesnt work on Safari

### ISSUE THREAD

**Issue by mbrain-io** [tinacms/tinacms#1867]
Given I'm using Safari
When I try to edit this page: https://tina.io/guides/nextjs/tina-with-strapi/editing-with-tina
Then I get this error:

<img width="480" alt="Screen Shot 2021-07-08 at 10 35 49 AM" src="https://user-images.githubusercontent.com/86771348/124890582-77c10300-dfd8-11eb-861a-b6a3427e13d6.png">

There is an error on that page I wanted to address. This `<ReactMarkdown source={content} />` should be replaced with this `<ReactMarkdown children={content} />`

**Comment by DirtyF** [comment]
@mbrain-io What browser are you using?

**Comment by mbrain-io** [comment]
Safari
