### ISSUE TITLE
Must be able to clear Image Fields

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#190]
You can add em', but you can't remove em'. 

![Screen Shot 2019-09-26 at 2 29 38 PM](https://user-images.githubusercontent.com/776019/65710849-27c6b580-e06a-11e9-8bc1-28edee4b8ab9.png)

**Comment by jamespohalloran** [comment]
Fixed with https://github.com/tinacms/tinacms/pull/328
