### ISSUE TITLE
Make sure media works on starter in monorepo

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1901]
The image field `onChange` is throwing an error. There was an attempt to fix it but I wasn't really sure what I was doing. This needs to be revisited with someone more knowledgable about what it should do https://github.com/tinacms/tinacms/pull/1885

**Comment by logan-anderson** [comment]
Error is `TypeError: n.src.includes is not a function`. Have to add `mediaStore={TinaCloudCloudinaryMediaStore}` to tina-wrapper.
