### ISSUE TITLE
can we use Tailwind css?

### ISSUE THREAD

**Issue by lindamacdonald** [tinacms/tinacms#1911]
So Tailwind is sweeping accross  a lot of dev communities like absolute wild-fire and for good reason it makes layouts a complete breeze :) are we able to use it with TinaCMS? I think it would be fantastic if we could :)

**Comment by logan-anderson** [comment]
@lindamacdonald Great Question. Im sure @spbyrne can speak to this better but TinaCMS is not opinionated about the styling system that you use.  For example if you are using Next.js you can [add tailwind](https://tailwindcss.com/docs/guides/nextjs) and then use it in your components with editing powered by TinaCMS. We also have an [example here](https://github.com/tinacms/tina-tailwind-sidebar-demo/tree/tina-cloud) of using TailwindCSS with TinaCMS (Make sure you are on the tina-cloud branch)

**Comment by DirtyF** [comment]
@lindamacdonald yes you can, [our current demo](https://tina-tailwind-sidebar-demo-git-main-tinacms.vercel.app/, ) and the following one are built with TailwindCSS

**Comment by lindamacdonald** [comment]
Absolutely phenomenal guys will make sure to let EVERYONE KNOW that we can use tailwind with tinacms🤩🤩🤩🤩🤩🤩

**Comment by DirtyF** [comment]
[Tailwind Demo](https://tina-tailwind-sidebar-demo-git-main-tinacms.vercel.app/)

**Comment by lindamacdonald** [comment]
@DirtyF thanks a mil :) Im gonna take it for a spin right now :)
