### ISSUE TITLE
CLI init expects _app.js

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tinacms#1922]
## Description
@tinacms/cli init fails if _app.js is missing. I expect that most Next.js sites would have this file, but I don't believe it's required.

### Steps to reproduce

In a fresh project:

```
npm i --save next react react-dom
npx @tinacms/cli init
```

### Expected result

It should probably still optionally create an _app.js?

### Actual result

The command stops:

<img width="1113" alt="Screen Shot 2021-07-28 at 11 32 10 AM" src="https://user-images.githubusercontent.com/618212/127341419-4adece38-693a-4f20-b2df-7bda77158752.png">

#### Tinacms Package Versions
0.50

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |     MacOS    |
| node    |    14.15.1     |
| npm     |     6.14.8    |

**Comment by logan-anderson** [comment]
I don't _think_ the CLI assumes a `_app.ts`  / `_app.js`. But it does assume you are in a next.js app with a pages directory. Was the pages directory missing @mitchmac ?

**Comment by mitchmac** [comment]
@logan-anderson Yep, that was it. Seems like that's too far off the typical path to worry about!
