### ISSUE TITLE
Installing packages from latest version breaks Vercel builds.

### ISSUE THREAD

**Issue by damiensedgwick** [tinacms/tinacms#1928]
## Description

When following this guide https://tina.io/guides/tinacms/github/initial-setup/ and after installing the packages in the last step `yarn add react-tinacms-github next-tinacms-github tinacms styled-components` Vercel is no longer able to build and deploy the application, please see attached image

<img width="1440" alt="vercel-build-failed" src="https://user-images.githubusercontent.com/42817702/127372823-8b0e6f19-89f0-4f7f-a4f3-7941f973b341.png">

### Steps to reproduce

I got here by following the guide linked above but the steps are:

1. Create a new NextJS project using `yarn create next-app`.
2. Create a public repository and publish new NextJS project to Vercel.
3. Install TinaCMS packages as per the guide `yarn add react-tinacms-github next-tinacms-github tinacms styled-components`.
4. Push changes to Github to trigger a new build from Vercel. 

### Expected result

I would expect the build to succeed so that I can continue with the rest of the guide.

### Actual result

The build fails due to `error Couldn't find any versions for "next-tinacms-markdown" that matches "^0.44.0"`

#### Tinacms Package Versions
```text
├── next-tinacms-github@1.1.0
├── react-tinacms-github@0.50.0
└── tinacms@0.50.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |     Chrome     |
| os      |     MacOS (m1 chip)    |
| node    |    v14.17.0     |
| npm     |    7.15.1     |

#### NB.

I also done a screen grab of the installation so that you can see the Vercel build being fine before installation and then being broken after however due to file size, I cannot upload it. Happy to email it over though. I have also managed to get a different project past this stage by installing the packages all at v0.43.0 and the build passes there so I am thinking it could be a recent change that is causing this issue.

The github repo for the broken build is https://github.com/damiensedgwick/tinacms-broken-deps-issue just in case that is any use to you.

I spent some time looking around the packages and I cannot see a v0.44.0 anywhere so hopefully this is something that is easily fixed and is just a simple mistake or maybe there is a patch (that I was unable to find).

**Comment by logan-anderson** [comment]
Hello @damiensedgwick What happens if you try `yarn add react-tinacms-markdown@0.50.0`. We are going thought a lot of big changes right now (see https://github.com/tinacms/tinacms/issues/1898) we apologize for the inconvenience.

**Comment by logan-anderson** [comment]
If that does not work you also could try pinning react-tinacms-markddown at `0.43.3` in your package.json.


Ex: in your `package.json`
```
"react-tinacms-markdown": "0.43.3"
``` 
If that doesn’t work or more issue arise please feel free to let us know.


It might also be worth mentioning you might [find better success with Tina Cloud](https://tina.io/guides/tina-cloud/starter/overview/). It would be very similar to the Github setup you are using but we currently dont support open authoring workflow.

**Comment by damiensedgwick** [comment]
> Hello @damiensedgwick What happens if you try `yarn add react-tinacms-markdown@0.50.0`. We are going thought a lot of big changes right now (see #1898) we apologize for the inconvenience.

Hey @logan-anderson, thanks for getting back to me. I did try this a couple of times earlier but for records sake. The first time I do this it asks me to choose a version as per my screen shot

<img width="1472" alt="Screenshot 2021-07-28 at 19 19 44" src="https://user-images.githubusercontent.com/42817702/127375474-2490e44b-9e7c-4a70-a41e-5475ebab68cf.png">

After I select v0.50.0 I get the following output

```
error An unexpected error occurred: "https://registry.yarnpkg.com/react-tinacms-markdown: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/Users/damienk.sedgwick/Desktop/tinacms-broken-deps-issue/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

If I try another version, I get the same choice but no matter the selection the outcome is the same.

**Comment by logan-anderson** [comment]
We just did another publish so that may have fixed it. You should also try editing your package.json manually and then running a `yarn install` (you might have already tried this). 

> I am planning on looking at the cloud solution but for this particular case it is the NextJS / Github setup I need.
>
> Thanks again.
>
>PS. Super excited to see all the hard work the team is putting in!

@damiensedgwick Tina Cloud still uses Github as a backend 😄  Instead of editors using Github to login they would login with Tina Cloud and then our Github App would commit the changes to Github for you. It also adds a Graphql layer to interact with Github and your file system seamlessly. If you end up checking it out Let us know If you run into any issues. 

I pinged my team to look at this dependency issue, I have a feeling it is a result of all the the recent changes.

**Comment by damiensedgwick** [comment]
Awesome, thank you! I will try it again and come back to you. I will also checkout Tina Cloud too!

**Comment by damiensedgwick** [comment]
Just an update @logan-anderson - I removed node_modules and installed the packages as per the guide and the builds have passed as one would want.

commit: https://github.com/damiensedgwick/tinacms-broken-deps-issue/commit/17934ab36070d1f9fe03758f6c5905e229eacdc0

Thanks for your help!
