### ISSUE TITLE
Export classes needed to extend "githubRoute"

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#1932]
## Summary

We would like to extend the Github route from the teams-serverless repo. We are not currently exporting `GithubBridge` (and perhaps other pieces within the [githubRoute](https://github.com/tinacms/tinacms/blob/7a18be212d10572181a828d685cc3770e5ff5c12/packages/%40tinacms/graphql/src/primitives/index.ts#L46) function) from the @tinacms/graphql package. When that is exported, the tina-cloud team will have more control over the content-api's extension. 

## Motivation

One example, is wiring up Sentry or analytics to specific events within the GithubBridge. To implement that, we would have to either add those external libraries to the open-source repo, or reimplement existing logic within @tinacms/graphql 's githubRoute

**Comment by jeffsee55** [comment]
Everything is already exported from `@tinacms/graphql`, sorry I didn't realize!

**Comment by jamespohalloran** [comment]
Ahh interesting, ok IntelliSense may have lied to me. Well, that should make things easier @ashleyjanedoiron!

**Comment by jeffsee55** [comment]
@jamespohalloran  you were probably looking at `tina-graphql` for the old endpoint, the new one is `@tinacms/graphql` and it's [here](https://github.com/tinacms/teams-serverless/blob/main/js/content-api/src/graphql-content.ts#L3-L6)

**Comment by jamespohalloran** [comment]
Yep I think that's likely what I did! Closing this one.
