### ISSUE TITLE
Fix bugs during build for Windows

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1934]
We've removed the Windows CI build due to it blocking releases, but we'll want to fix it properly. 

See the failing build here:
https://github.com/tinacms/tinacms/runs/3175210514

Once that's done, add the Windows check back into CI. Which was removed [here](https://github.com/tinacms/tinacms/pull/1916/commits/7faea04f2baea85e6b42c7da3498a13a9afaf0da)

**Comment by logan-anderson** [comment]
I was able to build the mono repo on my windows device
