### ISSUE TITLE
Sidebar empty state links to an old documentation page

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#1942]
## Description

<img width="1161" alt="Screen Shot 2021-07-29 at 3 45 09 PM" src="https://user-images.githubusercontent.com/776019/127548849-53351a64-c88a-4b42-8837-a124f7481cef.png">

The sidebar empty state links to an [old doc](https://tina.io/docs/getting-started/introduction/#get-started).

This could send new users astray, especially if they're kicking the tires with Tina Init and they open the sidebar on a page that's not our init demo content.

**Comment by scottgallant** [comment]
@spbyrne Just flagging this for you.  Seems like we'll want to get this fixed before the beta.

**Comment by DirtyF** [comment]
What link should we point to? https://tina.io/docs/forms/?

Look like it's just a matter of updating a URL (and publish a new release)
https://github.com/tinacms/tinacms/blob/1a16ef190c3ad07c16751d87acbf27759d14d347/packages/%40tinacms/toolkit/src/packages/react-sidebar/components/NoFormsPlaceHolder.tsx#L34-L36
