### ISSUE TITLE
No template found for slug when using camel_case for the template name

### ISSUE THREAD

**Issue by techbrethren** [tinacms/tinacms#1970]
## Description
When saving an edit from tina, it is unable to save specific components. It saves the page data, but leaves out important content, giving the error `No template found for slug <mismatched component name>` For example, if I have a component named "side_by_side" I will receive the error `No template found for slug sideBySide`

### Steps to reproduce
Save a project with an array of blocks. Tina is unable to find specific blocks.

### Expected result

All data to be saved to JSON

### Actual result

Most data is saved, but it deletes already existing component of same name if error `No template found for slug ` is present.

#### Tinacms Package Versions
<html><body>
<h4>Tinacms Package Versions</h4>

<div class="snippet-clipboard-content position-relative"><pre><code>
react-tinacms-editor@npm:0.41.1
react-tinacms-inline@npm:0.41.1
tinacms@npm:0.41.1

</code></pre></div>

<h4>Tools</h4>

Tool | Version
-- | --
browser | Chrome 91.0.4472.106
os | Windows 10, WSL 2 Ubuntu
node | 15.7.0
npm | 7.4.3

</body>
</html>

**Comment by jamespohalloran** [comment]
@logan-anderson @jeffsee55 Do you guys happen to know if this is still an issue?

**Comment by logan-anderson** [comment]
I believe it is still an issue @jamespohalloran
