### ISSUE TITLE
Client access times out and silently fails

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tinacms#1977]
After logging in and editing content, then waiting a while, it seems that the session times out and API operations like saving content silently fail.

![Screen Shot 2021-04-21 at 12 36 13 PM](https://user-images.githubusercontent.com/618212/115583769-926cc100-a2a0-11eb-9997-651514925d50.png)

**Comment by jeffsee55** [comment]
I believe this was solved by @mittonface https://github.com/tinacms/tinacms/pull/2319
