### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#1978]
## The problem
Lets say you have a a relationship between blogs and authors defined like this

schema.ts
```
import { defineSchema } from 'tina-graphql-gateway-cli';

export default defineSchema({
  collections: [
    {
      label: 'Blog Posts',
      name: 'posts',
      path: 'content/posts',
      templates: [
        {
          label: 'Article',
          name: 'article',
          fields: [
            {
              type: 'text',
              label: 'Title',
              name: 'title',
            },
            {
              type: 'reference',
              label: 'Author',
              name: 'author',
              collection: 'authors',
            },
          ],
        },
      ],
    },
    {
      label: 'Authors',
      name: 'authors',
      path: 'content/authors',
      templates: [
        {
          label: 'Author',
          name: 'author',
          fields: [
            {
              type: 'text',
              label: 'Name',
              name: 'name',
            },
            {
              type: 'text',
              label: 'Avatar',
              name: 'avatar',
            },
          ],
        },
      ],
    },
  ],
});
```

Now further suppose for whatever reason I want to change the name of the folder `content` to `logans-content`. When I do so I get an error from the graphql client because of have it can no longer resolve the author reference field because the file in the front-matter template does not exists. It would be nice if the graphql client made those changes for me.

I fixed this by changes the author reference in my markdown file and everything  worked as expected.

## expectations 

I dont get any errors when changing the name of the content folder and updating my schema instead it changes the author references. 

Not sure if this is possible or if it is an enhancement that can be made

**Comment by jamespohalloran** [comment]
Still seems relevant
