### ISSUE TITLE
Better error message when no `.tina` schema files are found

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#1993]
When using Tina Cloud it's possible that the user selects the wrong repo, if that happens they'd get `Unable to find record for .tina/__generated__/_graphql.json`

We should show a more clear error message:

```
We could not find a valid Tina schema at:
Repo: https://github.com/blahblah
Path: src/.tina/graphql/blahblah
Branch: main
```

**Comment by DirtyF** [comment]
I guess it's not possible to scan a repository for a valid .tina config _before_ it's selected to only show "eligible" repositories?
