### ISSUE TITLE
Wysiwyg not receiving media store data

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#2000]
related: https://github.com/tinacms/handbook/issues/8

Image plugin deactivates itself when it doesn't know how to handle images. Currently there seems to be a bug in the WYSIWYG component where it is not aware of media store functions and thus does not display the image menu plugin

**Comment by logan-anderson** [comment]
@dwalkr I am also looking at this and have an idea of how to possible fix it

**Comment by dwalkr** [comment]
@logan-anderson I have a fix on the way

**Comment by logan-anderson** [comment]
@dwalkr ME too 😂

https://www.loom.com/share/63bf4cc06e7a47fea5b8cb03748f88c8

**Comment by logan-anderson** [comment]
@dwalkr If you want to see how I fixed it. I have a draft PR here: https://github.com/tinacms/tinacms/pull/2001. it requires changes to the schema but I don't think we should require that change
