### ISSUE TITLE
Better feedback needed when you click the refresh button and it fails again

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#2002]
## Description

<img width="760" alt="Screen Shot 2021-08-05 at 3 27 54 PM" src="https://user-images.githubusercontent.com/776019/128402860-f670a1c8-6784-4a86-8367-1aae8e38f43e.png">

### Steps to reproduce

I just encountered this screen after getting an error while creating a new document with the Tina Starter on Vercel (see [here](https://github.com/tinacms/tina-cloud-starter/issues/147))

I ran through the tina cloud starter workflow and was editing on vercel.app

Jeff notes below that when I clicked "refresh", it just hit the same error and nothing appeared to be happening.

### Expected result

Better feedback would be an improvement. I.e. A message saying "Something seems wrong with your site, and this page cannot refresh".  (please, feel free to revise that error message)

### Actual result

Nothing

#### Tinacms Package Versions

```text

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by jeffsee55** [comment]
This is working as intended from what I can tell, the refresh button runs into the error again, perhaps we can give better feedback that they tried again and it's still broken.

**Comment by scottgallant** [comment]
> perhaps we can give better feedback that they tried again and it's still broken 

That would be a significant improvement. Otherwise, people who encounter a situation like this are left scratching their heads.  

I'll rename this issue and re-open it

**Comment by DirtyF** [comment]
I once ran into this screen when I edited a post date field and that for a brief moment, the date wasn't valid anymore, when the change was done I could hit refresh and the page could render.
