### ISSUE TITLE
CLI init - unclear how to exit edit-mode

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2006]
## Summary

When initializing Tina on my site, it's unclear how to exit edit-mode. I see that the [starter](https://github.com/tinacms/tina-cloud-starter#urls) has an exit-admin page, should we be creating that page with the CLI init?
Currently, it looks like the CLI only creates a page to enter admin mode

### Motivation

Without making it obvious how to exit edit-mode, it gives the feeling that my production page will show the pencil icon to all users, rather than it being a special admin state that the user can enter/exit.

### Bonus
If we can standardize how exit-mode is toggled, it would be awesome to have this exit-admin functionality baked into the Tina sidebar / toolbar, rather than having the user navigate to a exit-admin page.

**Comment by logan-anderson** [comment]
This was added in  this pr: https://github.com/tinacms/tinacms/pull/2022

**Comment by DirtyF** [comment]
The CLI now generates an exit route.
