### ISSUE TITLE
getStaticPropsForTina with no variables causes getStaticProps to error

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2009]
## Description

I am querying a list from my getStaticProps. My query doesn't need any variables:
```
export const getStaticProps = async ({ params }) => {
  const tinaProps = await getStaticPropsForTina({
    query: `
    query {
      getProjectsList {
        edges {
          node {
            data {
              title
              description
              image
              body
            }        
          }
        }
      }
    }
    `,
  });

  return {
    props: {
      ...tinaProps, // {data: {...}, query: '...', variables: {...}}
    },
  };
};
```

The response is: 
```
tinaProps  {
  data: { getProjectsList: { edges: [Array] } },
  query: '\n' +
    '    query {\n' +
    '      getProjectsList {\n' +
    '        edges {\n' +
    '          node {\n' +
    '            data {\n' +
    '              title\n' +
    '              description\n' +
    '              image\n' +
    '              body\n' +
    '            }        \n' +
    '          }\n' +
    '        }\n' +
    '      }\n' +
    '    }\n' +
    '    ',
  variables: undefined
}
```

This causes my page to error with:
> Error: Error serializing `.variables` returned from `getStaticProps` in "/projects".
> Reason: `undefined` cannot be serialized as JSON. Please use `null` or omit this value.

### Steps to reproduce

Create a query similar to above, without any variables. Return the full props to getStaticProps

### Expected result

variables should either be omitted from the `getStaticPropsForTina` response, or set to null within `getStaticPropsForTina`

### Actual result

See error above

#### Tinacms Package Versions

├─┬ @tinacms/cli@0.53.0
│ ├─┬ @tinacms/graphql@0.51.1
└─┬ tinacms@0.52.0
  ├─┬ @tinacms/toolkit@0.50.1

**Comment by jamespohalloran** [comment]
The workaround for the user in this situation would be to return 
```
    props: {
      ...tinaProps, // {data: {...}, query: '...', variables: {...}}
      variables: null,
    },
```
but I figure it probably should fall under the responsibility of getStaticPropsForTina to format that response

**Comment by jeffsee55** [comment]
We should fix this, but the traditional advice for this from Nextjs is to stringify it:
```
    props: {
      ...JSON.parse(JSON.stringify(tinaProps))
    },
```
