### ISSUE TITLE
@tinacms/cli init - On a windows machine, we do not add stylesheets back giving a poor UX.

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2024]
## Description

When working with @tinacms/cli on windows we do not add the stylesheets back to _app.js files. 
### Steps to reproduce

1. run npx @tinacms/cli init on a windows machine.
2. Check the app.js file to see stylesheets have not been added.

### Expected result

Styleesheets should be added. 

### Actual result

Stylesheets have not been added back

#### Tinacms Package Versions

```text
  @tinacms/cli V0.53.3
```

#### Tools

Windows 10 
git bash / powershell / command prompt

**Comment by logan-anderson** [comment]
is this fixed now @perkinsjr  ?

**Comment by perkinsjr** [comment]
Yup! We fixed it with that latest release that is in the @dev branch.
