### ISSUE TITLE
Make `DateFieldPlugin` timezone-aware

### ISSUE THREAD

**Issue by Enigmatical** [tinacms/tinacms#2025]
Today, `DateFieldPlugin` accepts and submits all dates as UTC (where the `utc` flag is set to `true`).

Ideally, we would want to accept and submit a timezone-aware format (ISO 8601) rather than exclusively UTC.

**Comment by DirtyF** [comment]
As long as when I use the UI, Tina uses my timezone and on save Tina converts the date to what format is more appropriated for its backend. If I'm GMT+2, I don't find 4PM translates to 2PM UTC.

**Comment by Enigmatical** [comment]
> As long as when I use the UI, Tina uses my timezone and on save Tina converts the date to what format is more appropriated for its backend. If I'm GMT+2, I don't mind if 4 PM GMT+2 translates to 2 PM UTC in the front matter.

It should.  

The initial fix (using `UTC` universally) was, I believe, an over correction.  This change will save with your local timezone (using `moment()` instead of `moment.utc()`, convert to UTC when saving (via `toISOString()` utilizing built-in methods), and, when querying, you can take the value and convert back to a timezone-aware `Date`:

```
const myDate = new Date(data.date)
console.log(myDate.toLocaleDateString())
````

Unless you are accessing the data directly (through the markdown files), you'll never know that it was stored in UTC.  And if you _do_ access it directly, converting should be straightforward (and something you would have to do anyway).
