### ISSUE TITLE
Media Manager Causes increase in bundle size

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2035]
## Summary

I build the Tina-cloud starter with and without the media manager and here is the result.

#### With

<img width="973" alt="Screen Shot 2021-08-13 at 9 10 56 AM" src="https://user-images.githubusercontent.com/43075109/129355184-33a0be47-e76e-4950-9f86-ea014477c66e.png">

#### Without

<img width="973" alt="Screen Shot 2021-08-13 at 9 11 13 AM" src="https://user-images.githubusercontent.com/43075109/129355219-9775c792-9d62-46c9-86ff-13671589dedf.png">

As you can see it is tripling the size of the starter. We should provide a way to dynamically import it. It might look like this.

```ts
 mediaStore={import("next-tinacms-cloudinary").then(({ TinaCloudCloudinaryMediaStore }) => {
                return TinaCloudCloudinaryMediaStore
              })}
```

NOTE: this can be done now by using the CMS callback (Its a bit messy)

```ts
cmsCallback={(cms) => {
              import("next-tinacms-cloudinary").then(
                ({ TinaCloudCloudinaryMediaStore }) => {
                  cms.media.store = new TinaCloudCloudinaryMediaStore(
                    cms.api.tina
                  );
                }
              );
            }}
```

**Comment by jeffsee55** [comment]
@logan-anderson  This is fixed right?

**Comment by logan-anderson** [comment]
> @logan-anderson This is fixed right?

I dont believe so

**Comment by jeffsee55** [comment]
What are you suggesting we do other than import it dynamically?

**Comment by logan-anderson** [comment]
Something like this perhaps ?
```ts
 mediaStore={import("next-tinacms-cloudinary").then(({ TinaCloudCloudinaryMediaStore }) => {
                return TinaCloudCloudinaryMediaStore
})}
```

**Comment by jeffsee55** [comment]
Ah ok, yeah I can see that being better

**Comment by logan-anderson** [comment]
@jeffsee55 want me to implement this?

**Comment by logan-anderson** [comment]
@jeffsee55 #2074 Fixes this issue.
