### ISSUE TITLE
Add Admin page that doesn't redirect

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2038]
- Implement admin as [an optional catch all route](https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes) as `/pages/admin/[[...slug]].js`
- `/admin` - Admin page should _not_ redirect user
  - Should not enter edit mode immediately
  - It should display 3 options
    - Enter edit mode / Log in (if logged in, show the opposite?)
    - Go back
    - Go home (?)
- (BONUS) `/admin/exit` Exits edit mode and logs user out
- Update docs/guides accordingly

**Comment by perkinsjr** [comment]
For the cloud starter, this seems like a great approach to the problem. It will allow users to understand, the mode they are currently in without breaking anything.
