### ISSUE TITLE
Using `list: true` with `'type: "reference"`

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2056]
Example field in schema.ts
```js
 {
          name: "featuredPosts",
          label: "Featured Posts",
          type: "reference",
          list: true,
          collections: ["posts"],
 },
```

Everything works as expected except the UI produced looks like this.

<img width="659" alt="Screen Shot 2021-08-24 at 3 12 16 PM" src="https://user-images.githubusercontent.com/43075109/130668204-d72695b7-e905-4222-8b76-778f0049fdb9.png">

I would expect that I would be able to add new posts to the list and delete posts from the list. Instead I am given a normal reference field. 

## Temporary work around

I can put this in my schema.ts file as a work around
```
        {
          type: "object",
          list: true,
          name: "featurePosts",
          label: "Featured Posts",
          fields: [
            {
              type: "reference",
              label: "Post",
              name: "post",
              collections: ["posts"],
            },
          ],
        },
```

**Comment by DirtyF** [comment]
@logan-anderson what is the corresponding UI to the workaround you shared? Do you get a plus sign to add a new post?

**Comment by eduoliveira85** [comment]
Hi! I've followed the workaround suggestion from @logan-anderson and what it returns from the reference is the path of the content file. Perhaps there's something else missing?

```
{
			type: "object",
			label: "Contatos de imprensa",
			name: "contacts",
			list: true,
			ui: {
				itemProps: (item) => {
					console.log('item', item)
					return {
						label: item?.name 
					}
				}
			},
			fields: [
				{
					name: 'name',
					label: 'nome',
					type: 'string'
					
				},
				{
					label: "Pessoa associada",
					name: "contactPerson",
					type: "reference",
					collections: ['pressContact'],
				},
				
			]
		},
```
Console return
```
{
  name: 'Luiza', 
  contactPerson: 'content/pressContact/luiza.md'
}

```

**Comment by logan-anderson** [comment]
> and what it returns from the reference is the path of the content file. Perhaps there's something else missing?
> 
> ```
> {
> ```

@eduoliveira85  That is the expected behaviour. The reference field is string id (filename) that points to the file path of another collection item. When / If you query the data with the client or GQL API you can get the 'pressContact' data.

**Comment by eduoliveira85** [comment]
Oh, I see. Makes sense. Thanks for clarifying that.

**Comment by maxjvh** [comment]
so is this a wontfix or why was it closed exactly?
