### ISSUE TITLE
List of references does not update when new document is added

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2058]
See video: https://www.loom.com/share/6935c5b2dfec43bda70cc825bfe6ba22

When a new document is added I would expect that the list of references would be updated as well.

**Comment by logan-anderson** [comment]
This _could_ be a fix: https://github.com/tinacms/tinacms/pull/2099

**Comment by jeffsee55** [comment]
This would be fixed by a dedicated `reference` field.

**Comment by jeffsee55** [comment]
Will be closed by https://github.com/tinacms/tinacms/pull/2204

**Comment by jeffsee55** [comment]
Still relevant
