### ISSUE TITLE
Can't upload file from media manager in tina v0.55.0

### ISSUE THREAD

**Issue by otnansirk** [tinacms/tinacms#2073]
## Description

I can't upload from media manager tinacms . when I console.log() inside method persist(files) in my MediaStore class I get empty array from args files. 

### Steps to reproduce

- Install tinacms v0.55.0
- Create MediaStore class extends MediaStore tinacms
- log args file inside method persist()

### Expected result
Get file object from args files in method persist()

| Tool    | Version |
| ------- | ------- |
| browser |     Chrome    |
| os      |     LINUX    |
| node    |     v14.17.0    |
| npm     |    6.14.13     |

**Comment by arpi0003** [comment]
@DirtyF @jeffsee55 I'm seeing the same thing as @krisnantobi .

I created a branch off of the `inline-blocks-demo` repo where you can reproduce the issue with a vanilla media store. https://github.com/arpi0003/inline-blocks-demo/blob/media-store-test-upgrade/src/mediaStore.js#L8

My other branch before upgrading to the latest tina works: https://github.com/arpi0003/inline-blocks-demo/blob/media-test/src/mediaStore.js

Hope that helps!

**Comment by xaviemirmon** [comment]
Hey @arpi0003 @krisnantobi,

I also ran into this error when creating my own custom media store.  I had a look at the Cloudinary integration I could see that the `accept` parameter has become more specific https://github.com/tinacms/tinacms/blob/main/packages/next-tinacms-cloudinary/src/cloudinary-media-store.ts.  When I changed `accept = '*'` to `accept = 'text/*,  application/*, image/*'` on my integration the image data started populating.  

@DirtyF any ideas why it won't accept a full wildcard?

I hope this helps!

**Comment by jeffsee55** [comment]
Great catch @xaviemirmon - I'm not sure `*` is supported by the file input spec https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#accept. But I see that our interface does have `*` as the value. I think what you've got is the appropriate and we need to update our interface so others don't run into this issue.
