### ISSUE TITLE
Edit state context issue.

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2081]
I am not sure why but recently there has been context issues with the edit state provider. I am assuming because the edit state being "built" and the one being used internationally are separate. (This might be because we switched to ES build @jeffsee55 ?)

This means that when the user uses the edit state in their app (for admin page, an edit button etc) it works as expected but when used internally we get the wrong context.

For example when doing this the `tinacms` package. We get the wrong context.
```
import { useEditState } from '../edit-state'
//...

const { setEdit } = useEditState()
```

**Comment by logan-anderson** [comment]
I have been trying to fix this for a while now and I am sorta blocked.

## What I have tried so far to fix it

### 1. Different imports

If the problem is the that two different builds are happening then importing from the correct file should fix it.

I tried
```ts
import { useEditState } 'tinacms/dist/edit-state'
```
but got this error
```
seEditState' is not exported by dist/edit-state.js, imported by src/auth/TinaCloudProvider.tsx
file: /Users/logananderson-forestry-mac/dev/tinacms/tinacms/packages/tinacms/src/auth/TinaCloudProvider.tsx:6:9
4: import { useTinaAuthRedirect } from "./useTinaAuthRedirect";
5: import { createClient } from "../utils";
6: import { useEditState } from "tinacms/dist/edit-state";
            ^
7: function sleep(ms) {
8:   return new Promise((resolve) => setTimeout(resolve, ms));
Error building tinacms
(node:49488) UnhandledPromiseRejectionWarning: Error: Error: 'useEditState' is not exported by dist/edit-state.js, imported by src/auth/TinaCloudProvider.tsx
```
I also tried
```ts
import { useEditState } from 'tinacms/dist/edit-state.es'
```
Which does not produce a build error but the context run time error still arises.
```
Error: No `TinaEditProvider` found
```

I even tried changing the import in tina-cloud-stater app to
```ts
import { TinaEditProvider } from "tinacms/dist/edit-state.es";
```
with no luck.


### 1. Different build command

I also tried a few different build commands in combination with the different imports. 

#### different order
```
  "build": "yarn tsup src/edit-state.tsx  src/index.ts --format cjs --dts",
  "watch": "yarn tsup src/edit-state.tsx src/index.ts --watch --format cjs --dts"
```
Got the same context error

#### Exclude tinacms 
```
"build": "yarn tsup src/edit-state.tsx  src/index.ts --external tinacms --format cjs --dts",
"watch": "yarn tsup src/edit-state.tsx src/index.ts --external tinacms --watch --format cjs --dts",
```

Got the same context error.

### Next steps

Not sure what else to try. I could also try putting the `edit-state` in a separate package? Not sure if this is the end result we want though.

**Comment by logan-anderson** [comment]
I tried moving the edit-state into its own package and it did resolve the context issue. 

You can see a draft PR here: https://github.com/tinacms/tinacms/pull/2104

**Comment by jeffsee55** [comment]
> This means that when the user uses the edit state in their app (for admin page, an edit button etc) it works as expected but when used internally we get the wrong context.

@logan-anderson to be clear, are you saying that we haven't actually broken this for any users of Tina? Just for something we were doing internally? How are you trying to use it? 

And are you sure this is new behavior? This wasn't designed to be used internally, and I'm not sure how it would have worked before the build changes either. The point of edit-state is to determine if we should load the `tinacms` module or not, therefore: if `tinacms` runs, we're in edit mode. Is there something else I'm missing there?

 It makes sense why it's broken, when you import `{ useEditState } from './edit-state'`, that will all get bundled together into one file (eg. `tinacms/dist/index.js`), which would be a separate `createContext` call than the one that doesn't get bundled `tinacms/dist/edit-state.js`).

**Comment by logan-anderson** [comment]
@jeffsee55 it strangely was working before. 

We need to have the context be available to us as well as the end user because we need to do things like
- Exit edit state when they close the login model
- We might want to provide the admin page for the user at some point
then there admin.tsx would look like
```tsx
import { AdminPage } from "tinacms" 

export default AdminPage
```

Even when in the `tinacms` package I tried importing from the dist folder and that also did not work.

**Comment by jeffsee55** [comment]
There are definitely some problems with this, but it's working for now - though the details aren't the best. As we're looking into studio this will likely be part of a UI that we own.

**Comment by jeffsee55** [comment]
Discussing out of band and we may introduce a "context" package that's used as a direct dependency by `tinacms`. Some discovery needs to be done on this

**Comment by logan-anderson** [comment]
Should be fixed by https://github.com/tinacms/tinacms/pull/2281
