### ISSUE TITLE
Bring admin page into tinacms package

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2084]
Provide a dedicated UI for authenticating that can be exported as a Next.js page.

Support CLI dropping in this new component instead of the current implementation of setting the edit cookie.

**Comment by logan-anderson** [comment]
Related: https://github.com/tinacms/tinacms/issues/2081

**Comment by logan-anderson** [comment]
@spbyrne Any suggestions as to what this should look like? The one we have [in the starter](https://github.com/tinacms/tina-cloud-starter/blob/main/pages/admin/%5B%5B...slug%5D%5D.tsx) heavily relies on tailwind and the starter specific code.

**Comment by spbyrne** [comment]
Yes, this is something I'm currently thinking about and exploring in Figma. I should have something to discuss for tomorrow.

**Comment by jeffsee55** [comment]
Closing this in favor of a larger batch of UI work as discussed
