### ISSUE TITLE
Improve document creator

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2085]
When creating a document, it's not possible to provide fields. This makes it impossible to create new documents which have required fields. We should provide the proper APIs to create a new document with the full form for a given collection/template.

**Comment by Enigmatical** [comment]
I'm collection my very (very) rough ideas on this Whimsical chart:
https://whimsical.com/a-new-document-creator-8GRWKnq7odGn2KXRcDTzSr

**Comment by 3lijah** [comment]
@Enigmatical I'm not able to access that chart, but I would add that filenames should be allowed to have dashes.

**Comment by jamespohalloran** [comment]
Is this ticket different than https://github.com/tinacms/tinacms/issues/2090? (And still relevant? @jeffsee55 @chrisdmacrae )
