### ISSUE TITLE
Allow commit+push to be configured

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#209]
Right now every commit is paired with a push. This is required for production use, but it is not always wanted when editing files locally. The developer should be able to configure the git-api, or the git-client, to decide when to push.

**Comment by lyleunderwood** [comment]
For my use case it would be really nice if some kind of pull request-oriented workflow could be figured out. I think what would really make sense for me would be branch management. If we could:

- Change branch from the tina sidebar (this may be somewhat feasible currently using custom fields, I haven't looked into it yet), and
- Protect branches, `master` for example, forcing the user to select a new / different branch.

It would also be nice to be able to prompt the user for a commit message when saving.

If I had those tools I could probably cobble together a workflow to open pull requests automatically using github actions.

Overall it seems like there is lots of room for expansion with the git integration.

**Comment by ncphillips** [comment]
Great suggestions @lyleunderwood!

I think each of these deserves they're own feature request:

* #332 - Change branch from the tina sidebar 
* #333 - Could make protected branches possible
* #334 - Commit messages

**Comment by abtris** [comment]
I can point that I have pre-commit hooks automatically for every repo and that blocks any remark form and you get just ERROR: `fatal: Invalid object name 'HEAD'.` that isn't helpful.  I don't think so that  ERROR `fatal: No configured push destination.` is nice too and blocking edit function for this doesn't make sense.

**Comment by lyleunderwood** [comment]
Yes, pushing should definitely be configurable. Would it make sense to make pushing a separate action?

**Comment by ncphillips** [comment]
@abtris the error about `No configured push destination` occurs when the branch you're on is not in the remote. The `Invalid object name 'Head'` is less familiar, and unrelated to this issue in particular. Could you open a new Bug Report with as much detail as possible about the setup of your repo (i.e. pre-commit hooks) and the actions you're performing?

@lyleunderwood I think it depends on who the user is. If I was writing content locally I would want commit and push to be separate. But if I was setting up a site for a non-technical client using [TinaTeams](https://tinacms.org/teams/) then I would want them to be coupled. 

A potential API could look like:

```js
export default remarForm(BlogPostTemplate, {
  pushOnCommit: true
})
```

Then we could use some kind of environment variable for Tina Teams:

```js
export default remarForm(BlogPostTemplate, {
  pushOnCommit: process.env.NODE_ENV === "tinateams"
})
```

**Comment by lyleunderwood** [comment]
I mean should it be in the overflow menu UI as an action button like Delete is currently?

**Comment by lyleunderwood** [comment]
I feel like there should be two options:

- **`pushOnCommit: boolean`** When this is `true` then tina will push commits automatically upon commit. When it is `false`, an action button gets added to the overflow menu that triggers a `git push`.
- **`allowPush: boolean`** When this is `true` the above is true. When it is `false`, regardless of the value of `pushOnCommit`, commits will not be pushed automatically and no push action button appears in the overflow menu.

Not sure what the defaults should be.

**Comment by ncphillips** [comment]
That's what I'm thinking. 

[Here's where the delete action is defined.](https://github.com/tinacms/tinacms/blob/master/packages/gatsby-tinacms-remark/src/useRemarkForm.tsx#L125-L145)

A similar action could be defined and it could be left to the user to add it:

```js
import { GitPushAction } from "gatsby-tinacms-remark" 

const inTinaTeams =  process.env.NODE_ENV == "tinateams"

export default remarForm(BlogPostTemplate, {
  pushOnCommit: inTinaTeams,
  actions: inTinaTeams ? undefined : [GitPushAction],
})
```

**Comment by lyleunderwood** [comment]
Ah, okay. I haven't really looked into how actions work yet.

**Comment by ncphillips** [comment]
For sure. It's not documented, and that is the only example so far. Actions are just components rendered in that menu. We export the `ActionButton` component so it's easy to create you're own actions, but also easy to override how it looks/behaves.

**Comment by abtris** [comment]
I think that separation is good. Default can be set to that way as is simplest for users. I just follow guide on https://tinacms.org/docs/gatsby/quickstart and using gatsby cli is not set git remote. I think that is correct. 

Another  issue is that `Invalid object name 'Head'` is caused that git can't commit. In my case I have in global config: 

```
[user]
	useconfigonly = true
```
 that need setup identity for commits in every repository on my mac. Similar are hooks. I'm using https://github.com/kvz/ochtra for setup hooks. You don't need solve every situation but will be great is error message will be: "I can do this <commit-or-push> and this fail <error from git>.  

People who have issues can easy find what is problem and remove hooks (as I did) to solve issue.

**Comment by lyleunderwood** [comment]
Should open an issue to improve error messages for sure.

**Comment by ncphillips** [comment]
Thanks @abtris! Does explicitly configuring the Git plugin help? 

See the [demo-gatsby](https://github.com/tinacms/tinacms/blob/master/packages/demo-gatsby/gatsby-config.js#L48-L50) for an example.

**Comment by abtris** [comment]
@ncphillips yes, that will be great!

**Comment by lyleunderwood** [comment]
Hmmm, a push action should only really be enabled if there is something to push, right?

**Comment by ncphillips** [comment]
Yeah. The API for the actions is unstable, but it will likely include some form state. That way a separate `PushAction` could be disabled if the form is not dirty (i.e. no uncommitted changes)

**Comment by ncphillips** [comment]
See #345 for more thoughts on form actions

**Comment by lyleunderwood** [comment]
I was thinking about responding from the `commit` endpoint with a `needsPush: boolean`.

**Comment by ncphillips** [comment]
Riiight. That's an interesting point, but I wouldn't add that to the API just yet.

**Comment by lyleunderwood** [comment]
I think the original intent of this issue is resolved, should it be closed? Maybe anything outstanding here can be migrated to new issues?

**Comment by ncphillips** [comment]
Agreed
