### ISSUE TITLE
Address Content Creator issues

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2090]
There are a few friction points that pop up when creating new content with Tina, I want to start a thread to collect as much info as possible on how it could be better. I've started with a few things that seem to get in the way most:

### The lack of data fields makes documents invalid
For now, the document creator modal only shows the `collection`, `template` (if necessary), and the `name` of the document you want to create. Our thinking was, due to the nature of Tina, it doesn't really make sense for an editor to work on more data than that until they're on the actual page so visual editing works. However this puts us in a really bad place for creating valid document states. If you wanted your document to require a title, you can't really use the document creator flow. This is because it'll create an empty document, which is immediately invalid. The way this content is created is via the addPendingDocument mutation in GraphQL. It's called that for good reason, the idea is that the document is not yet valid. However after working with this for a while, I think we should really just stick to the idea that our API should never create content in an invalid state. So if title is required, it must be present upon document creation.

![](https://user-images.githubusercontent.com/5414297/128778980-2330db2a-5f35-42ab-b6d6-c4e764cccbea.png)

### Missing some sort of callback to control the document creation process
Developer's want a way to jump in between the form submission and the request to control the process a bit. An example of when this is useful would be to specify internaionalized filename endings (ie. `hello.en.md` & `hello.fr.md`)

---

Some general things we've been thinking of fixing:
### Show the full form during document creation

Just show every field, it might not be the best UX but it'll remove any blockers from the awkward flow we're seeing right now

### Supporting defaults for new collection items

```ts
defineSchema({
  collections: [{
    label: "Post",
    name: "post",
    path: "posts",
    fields: [{
      label: "Title",
      name: "title",
      required: true,
      type: "string"
    }],
    ui: {
      defaultItem: [{
        title: "Hello, World"
      }]
    }
  }]
})
```

#### A word of caution on defaults
Default values are somewhat dangerous. When you provide defaults the editing experience is much better, but the chance that some fake data will make it into production is higher. I think we're in a position to have to face this kind of issue more because without defaults the Tina editing experience is lacking. Other CMSs don't have to worry about the time between document creation and having a valid document. We should think of some mechanisms or APIs we can expose to the developer in case they want to make sure this kind of thing doesn't happen#2089

**Comment by Enigmatical** [comment]
I'm starting the discovery process of this in this Whimsical document:
https://whimsical.com/a-new-document-creator-8GRWKnq7odGn2KXRcDTzSr

Really high-level stuff that just seeks to roughly (very roughly) mock-up what we're thinking.

This issue is related to https://github.com/tinacms/tinacms/issues/2085

**Comment by jamespohalloran** [comment]
Seems like this is improving with the new admin ("CMS") windows, but still relevant
