### ISSUE TITLE
WARNING: The user interface for {type} does not support `list: true`

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2097]
To see current work arounds for this warning [read this page](https://tina.io/docs/errors/ui-not-supported/).

## The issue

We added the backend capabilities to support list true for any types but we currently do not have user interfaces for the following types
- boolean
- datetime
- reference
- image
- number

### Boolean

Not really sure how to implement this one. The data structure for 
```ts
{
  name: "test",
  label: "Test",
  type: "boolean",
  list: true
}
```
would look like
{
   test: [true, false, false, ...]
}

I am unsure what this UI would look like. (Array of toggles?)

### Datetime

UI would just be a list of  datetime fields that the user can add and delete.

### Reference
We we previously where using a list field with a dropdown of choices. Something similar would be good.

### Image
List of image fields

### number
List of Numbers

**Comment by jeffsee55** [comment]
This has been resolved
