### ISSUE TITLE
Export things using tinacms/something

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2105]
## Summary

In the past we have exported things that needed to be separated from the main TinaCMS package but should not require a separate package. We used `tinacms/dist/edit-state` for handling the edit state code. This is good as it separate from the main TinaCMS bundle but does not require a separate package. 

We could also do this for other things as well. For example 

`tinacms/node`: Could have all of the node packages for back-end use.
`tinacms/media`: Cloud have the media stores.

ect,

We could do a lot with this. 

It is also relitvate easy to do. If you want an example [take a look at the Next.js mono repo](https://github.com/vercel/next.js/tree/canary/packages/next)

## Potential Issues. 

We are getting [context issues](https://github.com/tinacms/tinacms/issues/2081) with the `edit-state` we would have to find a fix for this issue that does not involve putting the edit state into a new package.

The TinaCMS package could get very large. This could cause larger install times.

**Comment by jeffsee55** [comment]
My only concern with this is how will it work when we start supporting ESM for node, since this will use `require` we may just need to think about that in the near future

**Comment by logan-anderson** [comment]
Still relevant
