### ISSUE TITLE
Support specifying path to `.tina` config

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2112]
For apps in monorepos, the `.tina` folder should be next to the rest of their code ideally. We should support some way of specifying the path to the `.tina` folder relative to the root of the repo.

**Comment by employee451** [comment]
This might be a setting in the Tina Cloud dashboard, like how Vercel does it: 
![alt text](https://yiksanchan.com/images/free-and-simple-directory-listing-with-vercel/vercel-settings-root-directory.png)

For local development, it can be an env variable.

**Comment by employee451** [comment]
Workaround for Next.js: Move `.tina` folder to the root of your repo and update the `tina-dev` and `tina-build` commands to this in the app's `package.json`:

```json
"dev": "cd .. && yarn tinacms server:start -c \"cd path-to-project && next dev\"",
"build": "cd .. && yarn tinacms server:start -c \"cd path-to-project && next build\"",
```

**Comment by employee451** [comment]
@jeffsee55 Is there an update on this issue?

**Comment by jeffsee55** [comment]
This has been completed https://tina.io/docs/tina-cloud/faq/#does-tina-cloud-work-with-monorepos

**Comment by jonlambert** [comment]
@jeffsee55 Those docs don't explain what config option to set, they just say it's possible. How can I configure a subdirectory?

**Comment by jeffsee55** [comment]
@jonlambert here's a bit about it https://tina.io/docs/tina-cloud/faq/#does-tina-cloud-work-with-monorepos. You'll need to specify the path in your project config on tina.io under "Configuration -> Advanced settings".
<img width="1331" alt="Screen Shot 2022-07-08 at 5 33 47 PM" src="https://user-images.githubusercontent.com/5414297/178084863-81212f5b-b12b-40db-bca7-29190a7a69c5.png">
