### ISSUE TITLE
MDX Editor Improvements

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2131]
Won't fix (for now)
- No table support

Punch list of bugs:
- ~~Ensure `reference` field is not allowed in schema (for now)~~
- Toolbar UI doesn't resize well
- Link UI uses `prompt` instead of popup
- Types on TInaMarkdown are incomplete

**Comment by scottgallant** [comment]
MDX field seems disabled but you really need to click on the first line to active the field.  Ideally, you could click anywhere inside the field like a text-area. 

https://user-images.githubusercontent.com/776019/145108199-1a6c490b-cc7b-4847-92ee-9b4944192520.mov
