### ISSUE TITLE
Graphql float type

### ISSUE THREAD

**Issue by kauly** [tinacms/tinacms#2147]
## Description

Seems that we cant use float numbers, the auto generate `schema.gql` will always infer any number as integer. I cant provide a sandbox because Im using the graphql api.

### Steps to reproduce

[DEMO PROJECT](https://github.com/kauly/tina-101)

- go to `_content/pages/home.md`
- change `mapProps.longitude` and/or `mapProps.latitude` to a float value like  `-48.527` , `-27.628`
- `yarn && yarn dev`

### Expected result

A beautiful site..

### Actual result

App crashing, auto generated graphql stuff with Int type on those fields.  More context:
```
query{
  getPageDocument(relativePath: "home.md"){
   data {
    	title
    	mapProps {
        longitude
        latitude
        zoom
      }
  	}
  }
}
```
the bug
```
{
  "errors": [
    {
      "message": "Int cannot represent non-integer value: -48.527"
    }
....
}
```

#### Tinacms Package Versions

├── @tinacms/cli@0.56.0
├── react-tinacms-editor@0.52.0
├── tinacms@0.56.0

**Comment by jeffsee55** [comment]
Thanks @kauly 

I'm thinking this would make sense as a subset of the `number` primitive, so:
```ts
// .tina/schema.ts

export default defineSchema({
   collections: [{
     name: "post",
     label: "Blog Posts",
     fields: [{
       name: "lat",
       label: "Latitude",
       type: "number",
       float: true,
     }]
   }]
})
```

**Comment by logan-anderson** [comment]
@jeffsee55 It seems that type: "number" still maps to a graphql type of number. Can we change this to an "Float" so we do not run into this error?

**Comment by jeffsee55** [comment]
Let's double check that if we use `float` by default we _don't_ necessarily get a decimal representation (eg. `1.0`). If integers become coerced into floats, I think we should use the `float: true` portion to alter the type based on that.

**Comment by logan-anderson** [comment]
This is fixed on `main` and will be released when https://github.com/tinacms/tinacms/pull/2462 is merged.
