### ISSUE TITLE
tinacms package readme uses dated API

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2149]
## Summary

The readme for the tinacms package uses an outdated API: https://github.com/tinacms/tinacms/tree/main/packages/tinacms
It references functions like LocalClient (which is no longer called directly), useGraphqlForms
It also has some mistakes, like tina being added as a dev dependency in the installation

This readme is what shows up for our npm package, so it may cause confusion. 
https://www.npmjs.com/package/tinacms

**Comment by jeffsee55** [comment]
For now we'll update README.md files to point to Tina.io
