### ISSUE TITLE
non-200 status code on content save does not display error to user

### ISSUE THREAD

**Issue by kldavis4** [tinacms/tinacms#2179]
## Description

@scottgallant encountered the following: https://www.loom.com/share/15692d67c6c64642a45737d5f475f782

### Steps to reproduce

- Open the editor on a page connected to tina-cloud and leave idle until the access token has expired
- Make an edit and click save (verify non-200 (500 or 403) status code in the browser console)
- Note the Document Saved toast is displayed instead of an error message

### Expected result

- Error message toast

### Actual result

- Document Saved Confirmation Toast

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.1
├─┬ @tinacms/cli@0.55.2
│ ├─┬ @tinacms/graphql@0.54.3
├─┬ next-tinacms-cloudinary@3.2.4
├─┬ react-tinacms-editor@0.51.7
│ ├─┬ @tinacms/toolkit@0.52.3
├─┬ UNMET PEER DEPENDENCY tinacms@0.0.0-2021830181628
│ ├─┬ @tinacms/toolkit@0.0.0-2021830181628
```

**Comment by mitchmac** [comment]
Hoping this can be looked at soon, the success state is particularly misleading.

![Screen Shot 2021-11-26 at 12 33 39 PM](https://user-images.githubusercontent.com/618212/143610335-69b5a3d3-0a67-419b-91eb-ec8d9b5c43b6.png)

**Comment by kldavis4** [comment]
@jeffsee55 just to clarify, this particular issue is not about enabling refresh tokens (although that would help) but rather displaying an error message so the user doesn't keep thinking that edits are successful.

**Comment by kldavis4** [comment]
that said, with regards to the refresh token the following request (from https://github.com/tinacms/tina-cloud/issues/1051) can be used for refreshing the access token ([reference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html)):

```
curl --location --request POST 'https://cognito-idp.us-east-1.amazonaws.com/' \
--header 'x-amz-target: AWSCognitoIdentityProviderService.InitiateAuth' \
--header 'Content-Type: application/x-amz-json-1.1' \
--data-raw '{
    "ClientId": "<userPool_clientId>",
    "AuthFlow": "REFRESH_TOKEN_AUTH",
    "AuthParameters": {
        "REFRESH_TOKEN": "<refreshToken>",
        "DEVICE_KEY": null
    }
}'
```

which returns:

```
{
    "AuthenticationResult": {
        "AccessToken": ...,
        "ExpiresIn": 3600,
        "IdToken":  ...,
        "TokenType": "Bearer"
    },
    "ChallengeParameters": {}
}
```
and IdToken can be sent as a bearer token to the content api

or using fetch:

```
var myHeaders = new Headers();
myHeaders.append("x-amz-target", "AWSCognitoIdentityProviderService.InitiateAuth");
myHeaders.append("Content-Type", "application/x-amz-json-1.1");

var raw = "{\n    \"ClientId\": \"<userPool_clientId>\",\n    \"AuthFlow\": \"REFRESH_TOKEN_AUTH\",\n    \"AuthParameters\": {\n        \"REFRESH_TOKEN\": \"<refreshToken>",\n        \"DEVICE_KEY\": null\n    }\n}";

var requestOptions = {
  method: 'POST',
  headers: myHeaders,
  body: raw,
  redirect: 'follow'
};

fetch("https://cognito-idp.us-east-1.amazonaws.com/", requestOptions)
  .then(response => response.text())
  .then(result => console.log(result))
  .catch(error => console.log('error', error));
```

**Comment by mitchmac** [comment]
I think I was able to test this:

- Start editing a page
- Run `localStorage.clear()` in the console
- Try saving content
- Received "There was a problem saving your document"

@jeffsee55 if that test seems good, we can close. Eventually I think we should try to get more descriptive messages for problems but this is a good start.

**Comment by kldavis4** [comment]
@mitchmac can you verify that there is a non-200 status from content-api code prior to the message being displayed?

**Comment by mitchmac** [comment]
@kldavis4 yep :) 401
