### ISSUE TITLE
Add `create-tina-app` package and CLI capabilities

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2185]
- Users should be able to initialize a next app with a single `npm init` or `yarn create` command and specify one of our starters
- Ideally this is just a package from within our monorepo but not sure
- Add a vanilla starter site
  - Site should just have `pages/index.js`, `pages/[something-dynamic]` - which just use `getStaticProps`/`getStaticPaths` and dump the values as JSON onto the page
  - When admin is ready, adds `/pages/admin`
  - `.tina/` folder with minimal schema

**Comment by logan-anderson** [comment]
PR here: https://github.com/tinacms/tinacms/pull/2251
