### ISSUE TITLE
Website starts scrolling if you're scrolling in the sidebar and reach the top/bottom

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#219]
If you're scrolling in the sidebar and hit the top or bottom it will start scrolling the actual website. I don't think this is the expected behaviour and it's preventable with javascript.

In addition, it sometimes 'locks' the scrolling to the website so that if you begin scrolling the other direction it doesn't transfer scrolling back to the sidebar unless you interact with it in some way. This behaviour is quite jarring.

**Comment by narendrasoni1989** [comment]
Sent a pull request, please review if it is as expected.

**Comment by spbyrne** [comment]
Closing this for now since a solution may be more problematic than the issue. If someone thinks they have a good solution, we can open this back up.
