### ISSUE TITLE
Tina doesn't always return all images in Cloudinary when they are moved. 

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2206]
## Description

When moving images in cloudinary our media manager fails to update correctly even after closing and re-entering media manager.

### Steps to reproduce

Opened up the cloudinary dashboard and went to the media library
- Media library has lots of unorganized images making it hard to find things in Tina

2. I created 3 or 4 new directories

3. I started batch-selecting images and moving them to the correct directories

4. Checked Tina to see if the new directories were in the Tina media library (they were - that's good)

5. Opened up the directories in Tina and the images that I had sorted in the cloudinary dashboard were not there.

6. The Tina media library showed me that I had less images in my list because many images had been sorted into new directories. (that's good)

7. It looked like all that I could do was open up my new directories and re-upload images from my computer. No images were shown that had been moved in cloudinary.

8. (this one is random) There was a sub-directory that had a random handful of images in it that I had sorted into different folders.

### Expected result

We should return the images in the correct directories as expected. 

### Actual result

Images were removed from the root of / folder in media manager but did not show up in the newly-created directory. 

#### Tinacms Package Versions
Latest.

**Comment by jeffsee55** [comment]
This appears to be a caching issue related to Cloudinary, will investigate further but there may not be much we can do about it

**Comment by logan-anderson** [comment]
@perkinsjr Are the folders you using have a "space" in the name. I was just looking at this and it seems that folders with a space in the name are not working. This is likely an oversight on our end and I will look into it.

**Comment by logan-anderson** [comment]
Thanks for the context @perkinsjr. This fixes the spacing issue which might be the root cause. 

https://github.com/tinacms/tinacms/pull/2399
