### ISSUE TITLE
Any thought's on supporting @Remix.run framework ?

### ISSUE THREAD

**Issue by AlonGvili** [tinacms/tinacms#2209]
I close this issue and move it into discussions

**Comment by logan-anderson** [comment]
@AlonGvili This might be good to post in our [Github Discussions](https://github.com/tinacms/tinacms/discussions). Do you mind if we move the conversation there?

**Comment by AlonGvili** [comment]
> @AlonGvili This might be good to post in our [Github Discussions](https://github.com/tinacms/tinacms/discussions). Do you mind if we move the conversation there?

i open a discussion instead, thanks
