### ISSUE TITLE
Layout issues for "object" type in sidebar 

### ISSUE THREAD

**Issue by maximeMD** [tinacms/tinacms#2242]
## Description

When using "object" type in model, there are some issues with the displayed fields in the Tina sidebar.

- when the object's inner fields can be totally displayed in the view, they are shifted to the bottom : we can see the fields from the parent element : 

https://www.loom.com/share/8de68e94ff2b4345a357af997d5e09d9

- when the object's inner fields overflow the sidebar  height, the scrollbar does not appear so we can't access the fields in the overflow

https://www.loom.com/share/eb0d93f8a8ac4341931e71517ceae894

### Steps to reproduce

Create a model with a "object" field, then add the required number of inner fields (like "string" types) depending of you viewport height.

### Expected result

- the inner fields should be pushed to top instead of bottom
- the grey background should appear to fill the empty space below the inner fields
- the scroll bar should be working to scroll among the inner fields

### Actual result

Refer to the description.

#### Tinacms Package Versions

```text
+-- @tinacms/auth@0.50.1
+-- @tinacms/cli@0.56.4
| +-- @tinacms/graphql@0.56.0
+-- hygen-next-tinacms-github@0.0.0 invalid
+-- next-tinacms-cloudinary@3.3.4
+-- react-tinacms-editor@0.52.4
| +-- @tinacms/toolkit@0.55.2
+-- tinacms@0.57.3
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |     Chrome 96.0    |
| os      |     Windows 10    |
| node    |    14.8     |
| npm     |    6.14.15     |

**Comment by maximeMD** [comment]
I tried to reproduce it cloning this repo and using tina-cloud-starter, unsuccessfully...
I am closing this issue for now, and will comment if I find the solution 😉

**Comment by maximeMD** [comment]
Hi, I'm reopening this issue because I found that the issue comes from the TailwindCSS classes, which have no style attached in my project.
Do you know why this happens ?
Thanks in advance

**Comment by jeffsee55** [comment]
cc @spbyrne, perhaps some Tailwind has slipped in from the admin work?

**Comment by cjmcintyre** [comment]
Found this issue as well impacting the global menu, adding an **overflow: auto;** style to a class allowed me to see the contents.

![image](https://user-images.githubusercontent.com/18439866/142363362-17df2857-47f8-467a-b317-30edfaf53ddb.png)

**Comment by spbyrne** [comment]
Thank you @maximeMD for spotting that; I've created a PR that corrects the issue. This was my mistake.
