### ISSUE TITLE
Error: Cannot find module '../dist'

### ISSUE THREAD

**Issue by baticodes** [tinacms/tinacms#2253]
## Description

I'm not able to install tinacms since when running `npx @tinacms/cli@latest` it returns a  `Error: Cannot find module '../dist'` error.

### Steps to reproduce

run `npx @tinacms/cli@latest` inside a nextjs project and you will get the error.
At this  moment latest version of cli is @tinacms/cli@0.57.0 
If I run `npx @tinacms/cli@0.56.5`instead it seems to works

### Actual result

it throws the following error:

```bash
/Users/me/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/bin/tinacms:1
Error: Cannot find module '../dist'
Require stack:
- /Users/me/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/bin/tinacms
    at Object.<anonymous> (/Users/me/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/bin/tinacms:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/me/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/bin/tinacms'
  ]
}
```

### Environment
macOS Big Sur 11.6.1 
node v14.17.6
npm 7.20.2
next.js v12.0.3

#### Tinacms Package Versions

running `npm ls | grep tinacms | grep -v deduped`returns nothing.

**Comment by logan-anderson** [comment]
@baticodes Thanks for bringing this to our attention, we had an issue with a build but we have fixed it now. Is everything working as expected now?

**Comment by baticodes** [comment]
Thanks @logan-anderson .

Running `npx @tinacms/cli@latest` works fine now, but if I run it with init instead it will fail `npx @tinacms/cli@latest init`

```
Error: Cannot find module '@tinacms/cli'
Require stack:
- /Users/me/Desktop/temp/my-app/.tina/__generated__/temp/schema.js
- /Users/me/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/dist/index.js
- /Users/me/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/bin/tinacms
```

It seems to be another issue so I will close this one.
