### ISSUE TITLE
Several instances of 'styled-components' initialized in this application.

### ISSUE THREAD

**Issue by cjmcintyre** [tinacms/tinacms#2270]
## Description

Not sure if this would be classified as a bug, but should the default npx init provide the following warning when using it on the default Nextjs example? 
> It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles to not render properly, errors during the rehydration process, a missing theme prop, and makes your application bigger without good reason.
See https://s-c.sh/2BAXzed for more info.

### Steps to reproduce

1. Create a new directory
2. execute `npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn/tree/master/basics/learn-starter"`
3. cd nextjs-blog
4. execute `npx @tinacms/cli@latest init` and wait

> Setting up Tina...
> Installing Tina packages. This might take a moment... ✅
> Adding _app.js ... ✅
> Adding a content folder... ✅
> Tina setup done  ✅
>          Start your dev server with yarn tina-dev and go to http://localhost:3000/demo/blog/HelloWorld to check it out the page that was created for you
> Enjoy Tina 🦙 !

5. execute `yarn tina-dev` and check your browser console at http://localhost:3000/

### Expected result

I assume that we shouldn't have issue with several instances of styled-components.

### Actual result

![image](https://user-images.githubusercontent.com/18439866/143003995-d7e9967c-e3f3-46ac-908b-df79570cc452.png)

#### Tinacms Package Versions

```{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "tina-dev": "yarn tinacms server:start -c \"next dev\"",
    "tina-build": "yarn tinacms server:start -c \"next build\"",
    "tina-start": "yarn tinacms server:start -c \"next start\""
  },
  "dependencies": {
    "@tinacms/cli": "^0.57.2",
    "next": "latest",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "styled-components": "^5.3.3",
    "tinacms": "^0.59.0"
  }
}
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| Chrome | Version 96.0.4664.45 (64-bit) |
| os      | Windows 10 Pro |
| node    |    14.15.4     |
| npm     | 6.14.10 |

**Comment by jeffsee55** [comment]
Thanks @cjmcintyre - I don't think this is manifesting as a bug but it was coming from our use of Plate which is what we're using for our rich text field. We patched a fix for this downstream https://github.com/udecode/plate/pull/1214 so just need to bump our version which I've done [here](https://github.com/tinacms/tinacms/pull/2274).

**Comment by cjmcintyre** [comment]
Sorry... I just want to confirm if this has been released into a package yet @jeffsee55 ?

I've upgraded to the following on one of my projects and am facing the following.

    "tinacms": "^0.60.3",
    "@tinacms/cli": "^0.58.2",
    "react-tinacms-editor": "^0.52.10"

![image](https://user-images.githubusercontent.com/18439866/145333543-ac5419c6-1be6-4a84-a637-8a2e76f08646.png)

**Comment by logan-anderson** [comment]
@jeffsee55 Still seeing this

**Comment by cjmcintyre** [comment]
Happy holidays Tina team - would love an update when you get back on this please.

**Comment by jeffsee55** [comment]
This is a strange one, but we're moving away from styled components for the rich text editor. I expect there are some oddities around how some of our dependencies in [plate](https://plate.udecode.io/docs/playground) are loading styled-components. We're confident that this isn't manifesting in any actual bugs, just a false positive warning. @cjmcintyre bare with us as this might be a couple of weeks before this is fully refactored out.

**Comment by cjmcintyre** [comment]
Glad to hear the confidence and will keep following along then and report anything I find.

**Comment by f4z3k4s** [comment]
For anybody encountering this: the issue still persists due to @udecode/plate-headless. Should be fixed when this package migrates to 22 or above. Currently it's 21.5. See: https://github.com/udecode/plate/issues/1075
