### ISSUE TITLE
Provide ability to customize the sidebar-empty state

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#228]
The empty-state ui is great for a developer setting up the site, but not appropriate afterwards.

<img width="476" alt="image" src="https://user-images.githubusercontent.com/824015/66169166-d8f2c000-e615-11e9-9960-474ce2ee1cb9.png">

 I want to be able to somehow make my own empty sidebar so I can add links to other services i.e. hosting, analytics, github repo, etc.

**Comment by kendallstrautman** [comment]
It would be cool to perhaps pass an `EmptyState` component via the `sidebar` config.
