### ISSUE TITLE
Make `label` optional in `schema.ts` optional

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2283]
When making large schema's it can get annoying to have pass a label for every field when you want to to be the same as the name of the field. We should make this type optional and have label default to the name of the field (this is the way it works now we just have to change the ts type).

Another idea: We allow the user to provide a `plugin` that can transform the `name` into a `label` that way if they want the label to just be the uppercase version of the name they can easily do so.

cc @jhuggett  for brining up this issue. (I also felt this pain)

**Comment by jeffsee55** [comment]
This is a fix to the Typescript types from the `defineSchema` config
