### ISSUE TITLE
Visual Indicator to show when things are in local-mode. 

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2290]
## Summary

I question if all users know that Tina sites configured with local-mode, won't work on production. I've also made the mistake of thinking I'm in local-mode, when I'm not (and vice-versa)

### Basic example

I think something simple like this would help

<img width="756" alt="Screen Shot 2021-11-29 at 12 59 07 PM" src="https://user-images.githubusercontent.com/3323181/143936198-a2222ceb-abc5-4ebc-88ef-0d7982891ffc.png">

It could also link to a doc that talks more about why one should use local-mode & differences between local-mode vs prod-mode (writing to filesystem vs commiting, auth, etc)

**Comment by jeffsee55** [comment]
This should use the `isLocalClient` property that's passed in from <TinaCMS>

**Comment by mitchmac** [comment]
One edge case that I ran into trying to do similar with tina-cloud-starter... the local client is how production content builds happen with CI right now so the local mode indicator would show up in production content. I think my naive-ish fix was to also check if `window` was defined.

**Comment by jeffsee55** [comment]
> so the local mode indicator would show up in production content

I'm not sure what you mean, this flag should be falsey for CI https://github.com/tinacms/tina-cloud-starter/blob/main/pages/_app.js#L23

**Comment by mitchmac** [comment]
> I'm not sure what you mean, this flag should be falsey for CI https://github.com/tinacms/tina-cloud-starter/blob/main/pages/_app.js#L23

Ah k, I must have been doing something weird (maybe not using the prop)!
