### ISSUE TITLE
Minheight / maxheight for textarea & markdown fields

### ISSUE THREAD

**Issue by dwalkr** [tinacms/tinacms#230]
![image](https://user-images.githubusercontent.com/15221702/66174335-7bb13b80-e622-11e9-88a4-0fbb86173192.png)

auto-resizing is great, but there should be min and max bounds on it. Editing longform content in what initially looks like a single line of text is uninviting, and a super long post will be tedious to scroll past if you want to edit fields further down in the form.

**Comment by bolariin** [comment]
I know you can set the minheight and maxheight using CSS. To make this configurable, would that mean adding a style option to Field
 
https://github.com/tinacms/tinacms/blob/d2c806f5c1c7b81155fc1aa2126c2b3462d1e19f/packages/%40tinacms/core/src/cms-forms/form.ts#L30-L32

**Comment by kendallstrautman** [comment]
Let's open a new issue if we see the need for configuration on these heights.
