### ISSUE TITLE
Print out next steps with create-tina-app after a starter's been created 

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2321]
## Summary

After creating a starter with create-tina-app, we should log out some instructions of what to do next. 

### Basic example

We currently tell them to do a `yarn dev`, but maybe we could add notes on:

- Go to localhost:3000/admin to enter edit-mode.
- Edit some content on localhost:3000 (See https://tina.io/using-tina-editor )
- Check out [our concept docs](/docs/schema/), to learn how Tina powers the starters under the hood.
- Learn how [Tina can be extended](/docs/advanced/extending-tina/) to create new field components.
- Make your site [editable with Tina on production](/docs/tina-cloud/).

### Motivation

If we show the `create-tina-app` command on our homepage, the user will have more context on how to use the starter, and where to take it next

**Comment by logan-anderson** [comment]
@jamespohalloran I added this in the CLI and it is deployed now. Going to close this for now but feel free to re-open it if we should revisit it.
