### ISSUE TITLE
MDX-Editor & TinaMarkdown not saving bold, italic, underline, striketrough correctly

### ISSUE THREAD

**Issue by Perni1984** [tinacms/tinacms#2323]
## Description

When using the new mdx editor in a rich-text field I can format texts with bold, italic, underline and strikethrough and this also gets rendered correctly in the preview. Unfortunately when I save the content, the bold, italic, underline, strikethrough markdown formatting doesn't get written to the disk, despite it being present in the payload that get's sent to the TinaCMS local dev server. So on reload, the formatting is gone.

Interestingly, formatting text as headline 2 works without any problems and also gets written to disk correctly.

Schema:
![image](https://user-images.githubusercontent.com/9039956/144763566-b73af0da-6ccb-445b-aabd-9e06873e88f1.png)

Editor View + Onsite Rendering:
![image](https://user-images.githubusercontent.com/9039956/144763495-07a36cf4-7964-414d-b8ac-d2a82ee57d95.png)

Console.log of payload inside formify onSubmit hook that gets sent to the TinaCMS local dev server:
![image](https://user-images.githubusercontent.com/9039956/144763617-c19864e8-3173-422e-8a46-33de5da13faa.png)

Saved `.md` file on disk:
```markdown
---
components:
  - mdxContent: |+
      This should be bold text.

      This should be italic text.

      This should be underlined text.

      This should be strikethrough text.

      ## This is headline 2.

    _template: blogPostSection
---
```

Thus on a reload, all formatting of the text other then the headline 2 is gone.

### Steps to reproduce

1. Create a rich-text field in a document of a collection
2. Add text to the rich-text field that is formatted bold, italic, underline or strikethrough in the new mdx editor
3. Save the document from the tina sidebar
4. Reload the page in the browser

### Expected result

The `.md` file should contain respective formatting of text in bold, italic, underline or strikethrough.

### Actual result

The `.md` file doesn't contain any markdown formatting of text in bold, italic, underline or strikethrough. It's just plain text.

#### Tinacms Package Versions
```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.57.2
├── next-tinacms-cloudinary@3.4.0
├── tinacms@0.59.1
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | brave Version 1.32.113 Chromium: 96.0.4664.45 (Offizieller Build) (64-Bit)        |
| os      |    Ubuntu 20.x     |
| node    |    v16.13.0     |
| npm     |      8.1.4   |

**Comment by Perni1984** [comment]
My guess would be that here (https://github.com/tinacms/tinacms/blob/92856d6f3474b2ce1c8d81b061fb48032250f671/packages/%40tinacms/graphql/src/mdx/stringify.ts#L60), the MARK_ITALIC, MARK_BOLD, ... (https://github.com/tinacms/tinacms/blob/92856d6f3474b2ce1c8d81b061fb48032250f671/packages/%40tinacms/graphql/src/mdx/parse.ts#L537-L540) are not handled correctly.

**Comment by jeffsee55** [comment]
Thanks @Perni1984 ! This is great detail, and I think you're right about where the issue is ocurring, we'll take a look!

**Comment by Perni1984** [comment]
@jeffsee55 

here is a patch file that would enable bold and italic. It seems that underlined and strikethrough are only possible through a markdown plugin. I will try to make a PR later this evening (as this involves some more setup on my side), but maybe also the patch file is ok.

```
Index: packages/@tinacms/graphql/src/mdx/stringify.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/packages/@tinacms/graphql/src/mdx/stringify.ts b/packages/@tinacms/graphql/src/mdx/stringify.ts
--- a/packages/@tinacms/graphql/src/mdx/stringify.ts	(revision cf7cdb61bd7491ef57b9fced8e58e7c9b661b57f)
+++ b/packages/@tinacms/graphql/src/mdx/stringify.ts	(date 1638819630168)
@@ -436,6 +436,60 @@
       }
 
     case 'text':
+      if(node?.bold && node?.italic) {
+        return {
+          type: 'strong',
+          children: [{
+            type: 'emphasis',
+            children: [{
+              // @ts-ignore
+              type: 'text',
+              value: node.text || '',
+            }]
+          }]
+        }
+      }
+
+      // @ts-ignore
+      if(node?.bold) {
+        return {
+          type: 'strong',
+          children: [{
+            // @ts-ignore
+            type: 'text',
+            value: node.text || '',
+          }]
+        }
+      }
+
+      if(node?.italic) {
+        return {
+          type: 'emphasis',
+          children: [{
+            // @ts-ignore
+            type: 'text',
+            value: node.text || '',
+          }]
+        }
+      }
+
+      // type delete is only supported via an extension
+      // see https://github.com/syntax-tree/mdast#delete
+      //
+      // if(node?.strikethrough) {
+      //   return {
+      //     type: 'delete',
+      //     children: [{
+      //       // @ts-ignore
+      //       type: 'text',
+      //       value: node.text || '',
+      //     }]
+      //   }
+      // }
+
+      // it seems that underline is not supported directly via mdast
+      // but only via github flavored markdown extension
+
       return {
         type: 'text',
         // @ts-ignore
```
