### ISSUE TITLE
Branch Switcher modal dialog too narrow for branch names

### ISSUE THREAD

**Issue by Perni1984** [tinacms/tinacms#2324]
## Description

Not sure if you want to get some bug reports on experimental features aswell, but kindly let me know if you don't.

Currently we are playing around with the branch-switcher and we noticed that the modal dialog is too narrow for our branch names to be displayed correctly.

![image](https://user-images.githubusercontent.com/9039956/144815459-79a161d3-7219-4106-9393-49b97bfdf303.png)
![image](https://user-images.githubusercontent.com/9039956/144814818-5ef67c6d-591a-48d1-8c41-7e2dfe11fa6c.png)

### Steps to reproduce

1. Enable `branch-switcher` experimental feature (-> https://github.com/tinacms/tinacms/blob/main/packages/@tinacms/toolkit/src/plugins/branch-switcher/README.md) 
2. Deploy site
3. Open Branch switcher via `Select Branch` in sidebar

### Expected result

All branch names should be viewable and not being truncated

### Actual result

The Modal dialog looks somewhat distorted.

![image](https://user-images.githubusercontent.com/9039956/144815475-1ca2ec85-453d-448f-ba56-fb19f5ac4c27.png)

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.57.2
├── next-tinacms-cloudinary@3.4.0
├── tinacms@0.59.1
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | brave Version 1.32.113 Chromium: 96.0.4664.45 (Offizieller Build) (64-Bit)        |
| os      |    Ubuntu 20.x     |
| node    |    v16.13.0     |
| npm     |      8.1.4   |

**Comment by mitchmac** [comment]
Thanks @Perni1984! Definitely appreciate feedback on experimental features.
