### ISSUE TITLE
Support `apiURL` prop instead of other config props

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2328]
## Summary

Right now, all of the Tina Cloud properties are configured on the root `<TinaCMS>` container. Most of these properties are optional, and it's easy to misconfigure these properties. 

```
   <TinaCMS
      query={pageProps.query}
      variables={pageProps.variables} // Variables used in your query
      data={pageProps.data}
      isLocalClient={true}
      branch="main"
      clientId="<some-id-from-tina-cloud>"
    >
 ```
 
`branch` and `clientId` are always optional, even if isLocalClient is false. 
 When talking to TinaCloud, they should always be required. When started out locally, the user shouldn't need to set these.

### Basic example

If we can group some of these properties, we can ensure that all required Cloud properties are set, only when `isLocalClient` is false:

```
  const backendConfig = process.env.NODE_ENV == 'development' ? new createDevelopmentConfig() : createCloudConfig({
    branch=process.env.NEXT_PUBLIC_VERCEL_GIT_COMMIT_REF,
    clientId="my-client-id"
  })

  render() {
    const { Component, pageProps } = this.props

    return (
      <TinaEditProvider
        editMode={
          <TinaCMS
            query={pageProps.query}
            variables={pageProps.variables} // Variables used in your query
            data={pageProps.data}
            backend= {backendConfig}
            {...pageProps}
          >
            {(livePageProps: any) => <IndexLayout Component={Component} pageProps={livePageProps} />}
          </TinaCMS>
        }
      >
        <IndexLayout Component={Component} pageProps={pageProps} />
      </TinaEditProvider>
    )
  }
  ``` 
  
 This approach is similar to GitHub's octokit auth, where there are multiple ways to auth: https://www.npmjs.com/package/@octokit/auth-app
  
### Motivation

When users try to take Tina to prod, I would imagine it usually takes a few commits to get things working on Vercel. This should reduce friction around that process.

Also, having `isLocalClient` default to true feels weird. This change will make that more explicit.

**Comment by jeffsee55** [comment]
I agree about `isLocalClient` defaulting to true, can we come up with something more clear than `backend`? Another option for the local vs cloud config is just to have them give us the API url directly:

```tsx
    const { Component, pageProps } = this.props

    return (
      <TinaEditProvider
        editMode={
          <TinaCMS
            query={pageProps.query}
            variables={pageProps.variables} // Variables used in your query
            data={pageProps.data}
            apiURL={`https://content.tinajs.io/content/${clientID}/github/main`}
            // apiURL={`http://localhost:4001`}
            {...pageProps}
          >
            {(livePageProps: any) => <IndexLayout Component={Component} pageProps={livePageProps} />}
          </TinaCMS>
        }
      >
        <IndexLayout Component={Component} pageProps={pageProps} />
      </TinaEditProvider>
    )
```
If we did want to simplify it like this, I'd wonder if some portions of the URL are even necessary, could it just be `https://content.tinajs.io/${clientID}/main`

**Comment by jamespohalloran** [comment]
> If we did want to simplify it like this, I'd wonder if some portions of the URL are even necessary, could it just be https://content.tinajs.io/${clientID}/main

Ooo yeah I like that! I think it may clear up the relationship between local & cloud modes.

**Comment by jeffsee55** [comment]
I think a while back we didn't want to do this because the identity url _also_ changed from one user to another, but now that's not the case. So yeah, we'd get rid of `isLocalClient` entirely. And for determining local vs cloud, we could just look for `localhost` in the URL as a simple check, even if that may not always be the case if they're editing there `/hosts` file.

**Comment by jamespohalloran** [comment]
I wonder how branching may be affected by passing in only a apiUrl
https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/auth/TinaCloudProvider.tsx#L143

Should branching be pulled out of the TinaCMSProvider in this case?

```
   const { Component, pageProps } = this.props
   
   const branch = useBranch() // or 'main' if you didn't care to support branching. 

    return (
      <TinaEditProvider
        editMode={
          <TinaCMS
            query={pageProps.query}
            variables={pageProps.variables} // Variables used in your query
            data={pageProps.data}
            apiURL={process.env.NODE_ENV == 'development' ? 'http://localhost:4001' : `https://content.tinajs.io/content/${clientId}/github/${branch}`}
            {...pageProps}
          >
            {(livePageProps: any) => <IndexLayout Component={Component} pageProps={livePageProps} />}
          </TinaCMS>
        }
      >
        <IndexLayout Component={Component} pageProps={pageProps} />
      </TinaEditProvider>
    )
```

**Comment by jeffsee55** [comment]
`useBranch` is for the current branch, it needs a default one which uses whatever is passed in, so I don't think this would be a factor here

**Comment by jamespohalloran** [comment]
> useBranch is for the current branch, it needs a default one which uses whatever is passed in, so I don't think this would be a factor here

Oh I didn't know useBranch was already a thing. I was just proposing a potential workaround for our current handling of branching within the TinaCloudProvider 
https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/auth/TinaCloudProvider.tsx#L143

Otherwise, when we pass in the full apiURL, it may be awkward to tease out the branchName
