### ISSUE TITLE
Tabbing should be disabled for all non lists items in the slate editor

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#2332]
## Description

See video. 

https://user-images.githubusercontent.com/776019/145108771-e7250a73-b8ab-4548-bfce-fc6ca0e7ee94.mov

Note, I haven't tested hitting tab with lists. Does it nest them properly?

**Comment by jeffsee55** [comment]
I believe tabbing through list items behaves as expected. https://www.loom.com/share/dd59d84dbcea453ca30dddfba9b9d702

Tabbing in all other elements will be disabled by https://github.com/tinacms/tinacms/pull/2365

**Comment by scottgallant** [comment]
Right, but you should not be able to tab paragraphs, headings, etc.
