### ISSUE TITLE
Can not save code blocks

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2339]
When using the `rich-text` type and saving a code block it does not save as expected but instead saves like this.

https://www.loom.com/share/a6243e689e9e40a481add77f7c81b8eb

**Comment by perkinsjr** [comment]
We have also had a report of this from a Discord user. Using the latest tina and tinacms/cli 

![image](https://user-images.githubusercontent.com/45409975/148554742-83ffbc06-7505-4235-ad87-cafec1dedf11.png)
