### ISSUE TITLE
TinaAdmin: View/Edit buttons are hidden when filename is too long

### ISSUE THREAD

**Issue by Perni1984** [tinacms/tinacms#2342]
## Description

If the filename's in the TinaAdmin are too long, the View / Edit Button from the RouteMappingPlugin are getting hidden, because of `overflow-hidden` in https://github.com/tinacms/tinacms/blob/e0ec70f5a40a9ac4155b68cc5affa29849902ef2/packages/tinacms/src/admin/pages/CollectionListPage.tsx#L138 or the `max-w-screen-md` in https://github.com/tinacms/tinacms/blob/e0ec70f5a40a9ac4155b68cc5affa29849902ef2/packages/tinacms/src/admin/pages/CollectionListPage.tsx#L120

![image](https://user-images.githubusercontent.com/9039956/145674804-99f7eba0-4180-4492-b24b-c43b1ba5674b.png)

### Steps to reproduce

1. Activate TinaAdmin with a RouteMappingPlugin
2. Add a new document with a "long" filename

### Expected result

View / Edit buttons should still be visible

### Actual result

View / Edit buttons are hidden

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.58.2
├── next-tinacms-cloudinary@3.4.2
├── tinacms@0.60.3
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by Enigmatical** [comment]
This is a great find!  Thanks so much 👍 

Should have a fix for it soon.
