### ISSUE TITLE
Support list of references

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2347]
## Description

I'd like to use a list of references. 
When I try and do so, I get this in the console:

> WARNING: The user interface for reference does not support `list: true`
> Visit https://tina.io/docs/errors/ui-not-supported/ for more information

> Generating types...
> AggregateErrorClass: GraphQL Document Validation failed with 2 errors;
>   Error 0: GraphQLDocumentError: Fragment cannot be spread here as objects of type "HomeFeaturedConnection" can never be of type "Document".
>     at /Users/jamesohalloran/Documents/sites/awkosock/.tina/__generated__/frags.gql:36:5
> 
> Error 1: GraphQLDocumentError: Fragment cannot be spread here as objects of type "HomeFeaturedConnection" can never be of type "Document".

^ Where Home is the collection that contains a list of references.

Sidenote: It was pretty easy to miss that first warning in the console. I don't know of any other place where we document supported field options. If a user is using an unsupported field, should we exit server:start?

### Steps to reproduce

Add a field like:

`{ name: 'featured', label: 'featured', type: 'reference', collections: ['Sock'], list: true }`

#### Tools

├─┬ @tinacms/cli@0.57.2
│ ├─┬ @tinacms/graphql@0.57.0
├─┬ tinacms@0.59.1 invalid
│ ├── @tinacms/sharedctx@0.0.1 extraneous
│ ├── @tinacms/toolkit@0.56.1 extraneous

**Comment by perkinsjr** [comment]
+1 for this I want a list of references, in my example:

Featured blog posts on the home page. 

Instead of manually having to put the info in, I could just put a list of references to the document.

**Comment by namjul** [comment]
Will this be one the [roadmap](https://tina.io/roadmap/) in the next months?

**Comment by LushawnDev** [comment]
Is there any update on this? Does Tina not support lists of references?

**Comment by GustavoGigacz** [comment]
Are there any updates on this?

**Comment by jaschaio** [comment]
Related #2056

@jeffsee55 [mentioned back in 2021 that you planned to support this as soon as possible](https://github.com/tinacms/tinacms/pull/2087#pullrequestreview-752868475) – any chance you can reopen this issue?

**Comment by spassvogel** [comment]
I'm also very interested in this...
