### ISSUE TITLE
Can not access media manager in TinaAdmin

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2364]
When using TinaAdmin one can not edit media.

See: https://www.loom.com/share/64c19a962bf74188bc6e6bdb9042d10f

**Comment by Enigmatical** [comment]
There's a good chance this is fixed by https://github.com/tinacms/tinacms/pull/2261 (`inject-tailwind` PR).

**Comment by logan-anderson** [comment]
It did fix it.
