### ISSUE TITLE
create-tina-app still uses yarn when npm is selected

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2379]
## Description

When using create-tina-app@latest we ask the user to select a package manager, however if you select our starter they are using yarn still which causes the app not to launch/

### Steps to reproduce

Below is a gif to repro the issue, but it is:

1. create-tina-app@latest
2. select NPM
3. select project
4. follow commands

![Kapture 2021-12-21 at 16 17 40](https://user-images.githubusercontent.com/45409975/146999361-3de93eeb-2f31-4115-9ffe-8ad5f1d132db.gif)

### Expected result

If user selects npm they shouldn't need to install yarn.

### Actual result

yarn is required and fails with yarn not found.

**Comment by perkinsjr** [comment]
pinging @logan-anderson

**Comment by logan-anderson** [comment]
@perkinsjr This is issue is because `tina-cloud-starter` had `yarn` in its `package.json` when its not needed. [I made a pr over there](https://github.com/tinacms/tina-cloud-starter/pull/197) to remove it.
