### ISSUE TITLE
cannot initialize tina behind firewall

### ISSUE THREAD

**Issue by cht132** [tinacms/tinacms#2388]
not work to run behind corp firewall
`npx create-tina-app@latest`

**Comment by jeffsee55** [comment]
@cht132 can you provide some more information? What's the error you're seeing?

**Comment by cht132** [comment]
i run `npx create-tina-app@latest`
"Cannot read property 'username' of undefined"
i think it need some kind of proxy config mapping


```
√ Which package manager would you like to use? » NPM
√ What is your project named? ... tina
√ What starter code would you like to use? » Bare bones starter
(node:21560) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:21560) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'username' of undefined
    at downloadExample (C:\Users\cht132\AppData\Local\npm-cache\_npx\ddaf51790a52b1fc\node_modules\create-tina-app\dist\index.js:273:84)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (C:\Users\cht132\AppData\Local\npm-cache\_npx\ddaf51790a52b1fc\node_modules\create-tina-app\dist\index.js:344:3)
(node:21560) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21560) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by logan-anderson** [comment]
Hello @cht132, when using `create-tina-app` it uses `https://api.github.com/repos/tinacms/tina-basic-starter` to get information about the repo. It seems that this request is failing for you.

Would this URL be blocked for any reason?

**Comment by cht132** [comment]
my env behind corp proxy server, npm install and yarn is fine for download

**Comment by logan-anderson** [comment]
@cht132 would there be anyway for us to re-create this issue? 

Also, If you want to get started without this command you can clone one of the starters directly from Github or use [our quick-start flow](https://app.tina.io/quickstart).

List of starters
- https://github.com/tinacms/tina-basic-starter
- https://github.com/tinacms/tina-cloud-starter
- https://github.com/tinacms/tina-docs-starter

**Comment by cht132** [comment]
thanks, let me clone it directly
