### ISSUE TITLE
NPM causes strange issue when using Tina + Markdown

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2389]
## Description

A user reported to me over the weekend a strange behavior where they would get an error. `Duplicate use of selection JSON ID Cell' 

![dup use of ](https://user-images.githubusercontent.com/45409975/148084742-87bc5939-53c3-4ba6-8d21-14e7da4bd51a.png)

After testing his repository I couldn't recreate this when using Yarn. I then used NPM latest LTS and would receive the same error.  

### Steps to reproduce

1. Create a tina application 
2. Use the basic Markdown editor.
3. Launch with NPM

### Expected result

Yarn versus NPM shouldn't make a difference, I could not understand the reasoning behind this. 

### Environment

TINACMS and Tina CLI latest.

#### Tools

Tested on windows 11 NPM and node LTS.

**Comment by jamespohalloran** [comment]
Does this include our starters as well? If not, do you have a reproducible public repo?

**Comment by perkinsjr** [comment]
I don't have a public repo but I can provide a copy of a private repo that the user provided via a zip file.

**Comment by perkinsjr** [comment]
@logan-anderson i shoot you a DM it could be windows as he was on windows. Happy to test after the fact but I did get the same issue when we were chatting at the time.
