### ISSUE TITLE
Tina Admin route should be dynamic loaded to keep bundle size down

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2395]
Corey in our discord was discussing bundle sizes and made a good point that we should dynamically load to keep bundle size down

```
import dynamic from 'next/dynamic';

const TinaAdmin = dynamic(() => import('tinacms').then((module) => module.TinaAdmin));

export default TinaAdmin;
```

**Comment by jeffsee55** [comment]
I commented on the tina-cloud-starter that I don't think this actually benefits the end user.

https://github.com/tinacms/tina-cloud-starter/pull/201

> @cjmcintyre since the admin must load this module I'm not sure what is gained by loading it async. Typically this is useful for when Tina is loading on a page that a visitor to your site would visit (so only those in edit mode actually load tina's modules).

Is there some reason aside from the bundle size output that maybe I'm missing?

**Comment by cjmcintyre** [comment]
> Corey in our discord was discussing bundle sizes and made a good point that we should dynamically load to keep bundle size down

Thanks for raising this @perkinsjr - I did go ahead and make an Issue + PR trying to not rely on you to raise it so I appreciate it however may cause some confusion now 😅

> I commented on the tina-cloud-starter that I don't think this actually benefits the end user.
> 
> https://github.com/tinacms/tina-cloud-starter/pull/201
> 
> > @cjmcintyre since the admin must load this module I'm not sure what is gained by loading it async. Typically this is useful for when Tina is loading on a page that a visitor to your site would visit (so only those in edit mode actually load tina's modules).
> 
> Is there some reason aside from the bundle size output that maybe I'm missing?

My only reasoning was for reducing the **First Load JS** which I'm under the impression would aid with performance on build and bundling?

**Comment by jeffsee55** [comment]
Closing since this is something the end user can do if they wish, but doesn't have a positive impact on performance.
