### ISSUE TITLE
CLI Audit next phase

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2396]
This is looking good, next phase of this as discussed:

- [ ] Git checks to ensure that when `clean` is run, the user has a clean working directory
- [ ] Show extra fields found in markdown
- [ ] The error messages are GraphQL-specific, they should be more user friendly

_Originally posted by @jeffsee55 in https://github.com/tinacms/tinacms/pull/2378#pullrequestreview-843876363_

**Comment by logan-anderson** [comment]
>  The error messages are GraphQL-specific, they should be more user friendly

I was looking into this and could not find any more specific errors from GraphQL besides the `location`

**Comment by jeffsee55** [comment]
I think you look at the actual `Error` instance you'll get a lot more

![image](https://user-images.githubusercontent.com/5414297/149025618-a1c2ed38-eb71-49e0-a120-8b2674a56f27.png)

**Comment by jeffsee55** [comment]
Not stale
