### ISSUE TITLE
Tailwind: Login Admin styles not loading.

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2397]
When you add `tinacms@tailwind` to a project without tailwind and go to `/admin` the admin styles do not load.

See  https://www.loom.com/share/0361036c4b8a4df59559b46cd21961c3

cc @Enigmatical @spbyrne

**Comment by logan-anderson** [comment]
Related to https://github.com/tinacms/tinacms/pull/2261

**Comment by logan-anderson** [comment]
The same issue occurs in the `basic` starter on the `inject-tailwind` branch

**Comment by Enigmatical** [comment]
Here's the fix:
https://github.com/tinacms/tinacms/pull/2261/commits/086c74417480ad6fa833c5bf37f9e767ead9b025

When we removed `embedTailwind()`, we didn't replace those styles with the new `tina-tailwind` styles.

Good catch!  We did half of the task, but not the other half.

**Comment by logan-anderson** [comment]
🎉
