### ISSUE TITLE
Provide better error message when TinaField is not given a Component

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#241]
TineField blows up with a confusing `type is undefined` error if the `Component` prop is not provided.

Should be setting TinaField.propTypes so we can do some runtime checking of the proptypes

**Comment by M-ZubairAhmed** [comment]
Can i take a look ?

**Comment by DirtyF** [comment]
@M-ZubairAhmed Please do, we're here if you have any questions.

**Comment by M-ZubairAhmed** [comment]
Sorry making this availability, due to time constrains
