### ISSUE TITLE
useGraphQLForms improvements

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2417]
Leverage the `onChange` event to simplify the `useGraphQLForms` hook.

**Comment by jeffsee55** [comment]
Auto-generating forms from a GraphQL query has been implemented at a somewhat rudimentary level and as we move into a more stable state there will be an increasing need for it to be full-featured. Some of the missing capabilities right now:

1. When you query for a subset of fields on a document, you can still edit every field. It'd be nice to limit that to only what's queried, or let the developer choose how to handle that.
2. Similarly, when a field that hasn't been queried receives an update, we populate the query payload with that value, which is confusing.
3. We don't generate forms for a `list` query, (ie. `getPostList`) - this should be a form for each node, and while we'll want to talk about how this would look from a UX perspective, it seems clear that this needs to be supported, and the groundwork for it needs to be done and shares a lot of the same requirements as some of the other items in this list
4. We don't support `reference` where `list: true`, again - similar constraints to point #1, and the work to support it architecturally needs to come first
5. We don't support references as _part_ of `list` of `objects` (ie. `data.feaureList[0].author`) - (this "works" right now, but if you don't do good defensive coding checks it's easy to break)
6. We don't support the ability to "step through" one form, into another (ie. `post -> author`). 

All of these will require a more sophisticated approach that's unlocked by relying on a more event-based system. And while a few of them will need UX considerations, they're all unlocked by the same low-level improvements we need to make. I'm happy to go into details about how this will be implemented if it's helpful, but might also be a good pairing session for anyone interested.

---

_Also see comment from original [PR](https://github.com/tinacms/tinacms/pull/2318)_

**Comment by gitsstewart** [comment]
For this round of work we will focus on getting items 1,2 & 5 above completed. 
New issues will be started for items 3, 4, & 6.

**Expected results:**
- [ ] Instead of returning all fields to be edited, return only the fields needed (requested) by the specific query
- [ ] (opt) Provide an option to the developer for limiting the field result set can be configured by the developer
- [ ] Stop populating query payload with fields that haven't been queried for, regardless of whether or not they've been updated
- [ ] Strongly support references as part of lists of objects 
- [ ] Make references as part of lists of objects more robust (harder to "break")

**Comment by jeffsee55** [comment]
As discussed in standup this PR won't deliver the first 2 checkbox items, but those are now supported if we want to do that in the future.

This PR will also introduce a breaking change which is that the `form.id` that we generate will be the path of the document (so `content/posts/hello-world.md`). Previously this was the name of the query and would probably only surface in the `formifyCallback`:

```js
formifyCallback={({ formConfig, createForm, createGlobalForm }) => {
  // this will now be the full path (eg. `content/global/index.json`)
  if (formConfig.id === "getGlobalDocument") {
    //@ts-ignore
    return createGlobalForm(formConfig, { layout: "fullscreen" });
  }

  return createForm(formConfig);
}}
```

**Comment by jeffsee55** [comment]
[PR](https://github.com/tinacms/tinacms/pull/2651) 
- [ ]  ~~Instead of returning all fields to be edited, return only the fields needed (requested) by the specific query~~ Out of scope, but now possible
- [ ]  ~~(opt) Provide an option to the developer for limiting the field result set can be configured by the developer~~ Out of scope, but now possible
- [x]  Stop populating query payload with fields that haven't been queried for, regardless of whether or not they've been updated
- [x]  Strongly support references as part of lists of objects
- [x]  Make references as part of lists of objects more robust (harder to "break")
- [ ]  Testing
- [ ]  Update documentation (once this fully released)
  - [ ] Breaking change is communicated
  - [ ] Any `formifyCallback` examples are updated
- [x]  Update starters?
  - [x] Tina docs starter has a branch that can be tested https://github.com/tinacms/tina-docs-starter/pull/51
  - [x] Tina cloud starter has a branch that can be tested https://github.com/tinacms/tina-cloud-starter/pull/239
