### ISSUE TITLE
Fix publishing in CI

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2419]
For some reason the publish command:
```
yarn workspaces foreach --no-private --verbose npm publish --tolerate-republish --access public
```
Only triggers the `@tinacms/auth` package (which is the first package 🤔):
<img width="917" alt="Screen Shot 2022-01-11 at 12 49 36 PM" src="https://user-images.githubusercontent.com/5414297/149019434-2a126dd1-cf13-46a8-8675-9c5384a7abfb.png">

**Comment by Enigmatical** [comment]
For curious minds:
When was the last time this workflow worked?

**Comment by dwalkr** [comment]
I can't be sure if this will fix it, but based on that error I think it may be that the `--tolerate-republish` flag is misleading: https://github.com/tinacms/tinacms/pull/2430
