### ISSUE TITLE
Update our examples/documentation/CLI to use apiURL

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2433]
## Description

We've updated our API to merge the `branch`, `clientId`, and `isLocalClient` properties into a single apiURL. 
We have several examples/documentation still using branch, clientId, and isLocalClient that we should update.
E.g https://github.com/tinacms/tinacms/blob/main/examples/basic/pages/_app.js#L20

The same goes for each of our starters, CLI init, etc.

**Comment by jeffsee55** [comment]
- [ ] cli init
- [ ] tina-cloud-starter template
- [ ] docs template

**Comment by logan-anderson** [comment]
I can take on the work for updating the starters as well as the CLI.

**Comment by logan-anderson** [comment]
@jamespohalloran should we update https://tina.io/guides/tina-cloud/add-tinacms-to-existing-site/deployment/#connect-your-local-project-with-tinacms-backend to only have one environment variable? Might be easy for folks to understand.

(in Local)
```env
NEXT_PUBLIC_APIURL=http://localhost:4001/graphql
```
(in Prod)
```env
NEXT_PUBLIC_APIURL=https://content.tinajs.io/content/<myClientId>/github/<myBranch>
```

**Comment by jeffsee55** [comment]
I also noticed an inconsistency with when we tell users to put their `client_id` in an environment variable vs hardcoded. I'm sort of thinking we should document it as hardcoded since it's not private

- [Here](https://tina.io/docs/tina-cloud/connecting-site/#using-the-deployment-branch)
- vs [here](https://github.com/tinacms/tinacms/blob/main/examples/basic/pages/_app.js#L13)

**Comment by logan-anderson** [comment]
For now I will make it so that it uses the old ENV vars. This way we don't break any docs or our Quickstart workflow.

**Comment by logan-anderson** [comment]
PR for the basic repo: https://github.com/tinacms/tina-barebones-starter/pull/14

**Comment by logan-anderson** [comment]
PR for tina-cloud-starter: https://github.com/tinacms/tina-cloud-starter/pull/209

**Comment by logan-anderson** [comment]
PR for tina-docs-starter: https://github.com/tinacms/tina-docs-starter/pull/24

**Comment by logan-anderson** [comment]
CLI PR: https://github.com/tinacms/tinacms/pulls

**Comment by jamespohalloran** [comment]
> 

I think from a docs pespective, hardcoding it make sense. 
From a starter perspective, having it as an environment variable is nice so that the Vercel deploy flow works.

**Comment by jeffsee55** [comment]
> From a starter perspective, having it as an environment variable is nice so that the Vercel deploy flow works.

Good point! That's definitely something I hadn't considered 👍

**Comment by logan-anderson** [comment]
Going to close this for now. We can revisit the documentation as needed.
