### ISSUE TITLE
Able to create a document with an invalid nested object

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2441]
## Description

See video: https://www.loom.com/share/35ef7513fc8d480c8389faa73cde7206

### Steps to reproduce
Use a `schema.ts` that looks like the following,

```ts

export default defineSchema({
  collections: [
    {
      label: "Some Collection",
      name: "test",
      format: "json",
      path: "content/test",
      fields: [
        {
          required: true,
          name: "objField",
          type: "object",
          fields: [{ name: "test", type: "string", required: true }],
        },
      ],
    },
// ...
})
```

Go to `/admin` (or use the document creator), and then create a new document and click save.

Noticed how the UI is valid when you have not added a valid value for the `object` component.

### Expected result

Object component should make sure that it is valid before clicking submit.

### Actual result

Can save an invalid form

**Comment by NicolasRoehm** [comment]
Hi, I am currently using tinacms 2.7.5 and @tinacms/cli 1.9.5 and I am still facing the same issue.

I am able to create a page with a required object, without actually defining it. This shouldn't be possible as the object is marked as required. Do I need to create a new issue?
