### ISSUE TITLE
Jest tests not running in CI

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2442]
## Description

I don't believe our jest tests within the repo are running in CI. 

On this PR, I looked at the test action and it only printed out:

```
Run yarn test
  yarn test
  shell: /usr/bin/bash -e {0}
➤ YN0000: [@tinacms/auth]: No tests found, exiting with code 0
```

When running `yarn test` from the root locally, it logs out tests from each package, but it seems to exit on the first package within CI.

<img width="867" alt="Screen Shot 2022-01-17 at 3 20 56 PM" src="https://user-images.githubusercontent.com/3323181/149826697-cdd9a361-ffdf-49a3-a98b-6592b04691a0.png">

### Expected result

Tests from every package should run on PR build, and prevent merging if there's a failure

### Actual result

Tests quietly immedietly fail and stop running

**Comment by logan-anderson** [comment]
Maybe related to #2419 ?

**Comment by jamespohalloran** [comment]
Fixed with https://github.com/tinacms/tinacms/pull/2412
