### ISSUE TITLE
Number field cannot be empty again once edited; Invalid value

### ISSUE THREAD

**Issue by douweknook** [tinacms/tinacms#2445]
## Description
I'm using a number field with the GQL + Tina Cloud setup and realized that there is a bug in the number field. If you edit the field, e.g. from empty to `100` and then remove the `100` again, an error occurs when saving the value. If I do not touch the fields at all tho it does accept it when they are empty. Here's a video to illustrate:

https://user-images.githubusercontent.com/3264754/149910849-f6b038b0-a0c4-456f-9a45-ef475a910682.mov

I think what causes this is that the initial value is `undefined` while after touching the field and emptying it the value becomes `""` which fails some type check. To fix it maybe the [NumberInput component](https://github.com/tinacms/tinacms/blob/1a16ef190c3ad07c16751d87acbf27759d14d347/packages/%40tinacms/toolkit/src/packages/fields/components/NumberInput.tsx#L34)'s `onChange` handler should parse `""` to `undefined` again. Or maybe it should happen at some later stage?

### Steps to reproduce

1. Create a field in your schema like this:
```
{
  type: "number",
  label: "My Number",
  name: "myNumber",
}
```

2. Go into the admin editor and change the value to a valid number. Remove the value again and try to save the form. An error will occur.

### Expected result

The value should go back to undefined and saving should not fail. If the field is not marked required setting it back to empty should just work.

### Actual result

Saving fails.

### Environment

Local development environment

#### Tinacms Package Versions
```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.59.0
├── next-tinacms-cloudinary@3.4.5
├── tinacms@0.62.0
```

**Comment by logan-anderson** [comment]
@douweknook good catch. This is happening because our graphQL package is trying to parse `""` as a number and is failing.

**Comment by azizChebbi** [comment]
@logan-anderson I want to take this issue.

**Comment by RiccardoGai** [comment]
@logan-anderson I have the same issue, any update on this? thanks!

**Comment by isaaclombardssw** [comment]
I still encounter this bug, with the date fields.

**Comment by gsicvj** [comment]
Same here. It would be nice if this was handled.

![Image](https://github.com/user-attachments/assets/25c69e7b-c9a6-4dcb-958e-6149daedc04f)

**Comment by shuaixr** [comment]
@logan-anderson  can I take this? im thinking of change the onChange in https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/toolkit/fields/components/number-input.tsx to set null when its not a number, and doing similar for datetimeInput. What do you think?

**Comment by JackDevAU** [comment]
Thanks to @shuaixr, this fix will be in the next release of TinaCMS! 
We aim to release updates weekly, so you can expect a new version by December 16th at the latest. If you need it asap, you can install the `@beta` versions (`npm install tinacms@beta`)
