### ISSUE TITLE
Dropdown Styling issue

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2453]
Super small issue with the new style changes. Looks like the icon in the select field is slightly off.

![Screen Shot 2022-01-18 at 3 53 22 PM](https://user-images.githubusercontent.com/43075109/150017096-4bd30872-d1df-44c0-ae0a-b743584661de.png)

**Comment by spbyrne** [comment]
Might be a browser-specific issue; what's this in?

**Comment by Enigmatical** [comment]
> Might be a browser-specific issue; what's this in?

Ha, I asked him the same thing :) 

In Firefox, I'm getting a gray select:
<img width="414" alt="Screen Shot 2022-01-18 at 4 02 07 PM" src="https://user-images.githubusercontent.com/1699544/150025831-b0188338-df70-444e-bfe0-2c6f08e804a9.png">

That's solved by just putting `bg-white` on the `select`.

In Chrome, I'm not seeing any issues.

**Comment by spbyrne** [comment]
In #2434 I've added just that to the select field as I noticed it was missing a bg color, likely after the removal of the forms plugin, so that will fix the gray select issue (and possibly this issue, if related).

**Comment by logan-anderson** [comment]
Was fixed in https://github.com/tinacms/tinacms/pull/2434
