### ISSUE TITLE
Difficult to know what "schema version" a given "frontend-tinacms version" expects 

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2465]
## Description

There is going to be a linked dependency between frontend (tinacms) versions, and backend (@tinacms/cli / _schema.json) versions. Right now, if you aren't using the latest version of both packages, it's difficult to know if versions are compatible.

The easy (and immediate) answer might just be to upgrade both packages to the latest, when upgrading either. In practice, I think users are going to take longer to upgrade, there's going to blockers preventing upgrades, and it's going to be difficult to keep both tinacms / @tinacms/cli in sync.

I'm not sure of the best route forward, but here's a few questions

- Should we version the packages together, so that it's obvious which versions to use?
- Should we have some sort of chart in our docs for compatible versions?
- If the frontend client makes a request to the server, and the schema.json version is incompatible, should we respond with an error message?
- ~~Can / should we eventually fail the site's build, if the `tinacms` version from the package.json is incompatible with the connected backend/app's version?~~ (I'm assuming this isn't currently possible unless we make tinacms more part of a site's build process, and other significant changes to how tina is setup).

**Comment by jeffsee55** [comment]
Maybe we should just bundle `@tinacms/cli` into `tinacms`. What would be the point of them remaining separate?
