### ISSUE TITLE
Deprecate legacy packages and their related issues

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2466]
- [ ] Deprecate packages which are no longer effectively receiving updates (eg. `react-tinacms-inline`, `react-tinacms-github`, `next-tinacms-json`, etc)
- [ ] Close issues related to APIs that we're not planning to bring forward (eg. `inline editing`)

**Comment by jamespohalloran** [comment]
Step 1:

- [ ] Update readmes of each package
- [ ] Create a post detailing deprecation
- [ ] Stop publishing to old packages
- [ ] Close out old issues when we have something to link to.

For now we will keep packages where they are

**Comment by logan-anderson** [comment]
>  (Maybe an npm deprecation would suffice?).

Yeah I think this is fine and is the path of least resistance.

**Comment by jeffsee55** [comment]
- `@tinacms/core` - https://www.npmjs.com/package/@tinacms/core
- `@tinacms/forms` - https://www.npmjs.com/package/@tinacms/forms
- `@tinacms/fields` - https://www.npmjs.com/package/@tinacms/fields
- `react-tinacms-date` - https://www.npmjs.com/package/react-tinacms-date
- `@tinacms/api-git` - https://www.npmjs.com/package/@tinacms/api-git
- `@tinacms/alerts` - https://www.npmjs.com/package/@tinacms/alerts
- `@tinacms/react-alerts` - https://www.npmjs.com/package/@tinacms/react-alerts
- `next-tinacms-github` - https://www.npmjs.com/package/next-tinacms-github
- `tinacms-contentful-root` - https://www.npmjs.com/package/tinacms-contentful-root
- `react-tinacms-i18n` - https://www.npmjs.com/package/react-tinacms-i18n
- `gatsby-tinacms-git` - https://www.npmjs.com/package/gatsby-tinacms-git
- `@tinacms/form-builder` - https://www.npmjs.com/package/@tinacms/form-builder
- `gatsby-plugin-tinacms` - https://www.npmjs.com/package/gatsby-plugin-tinacms
- `gatsby-tinacms-json` - https://www.npmjs.com/package/gatsby-tinacms-json
- `@tinacms/react-core` - https://www.npmjs.com/package/@tinacms/react-core
- `@tinacms/media` - https://www.npmjs.com/package/@tinacms/media
- `@tinacms/browser-storage-client` - https://www.npmjs.com/package/@tinacms/browser-storage-client
- `@tinacms/webpack-helpers` - https://www.npmjs.com/package/@tinacms/webpack-helpers
- `@tinacms/browser-storage` - https://www.npmjs.com/package/@tinacms/browser-storage
- `@tinacms/styles` - https://www.npmjs.com/package/@tinacms/styles
- `@tinacms/icons` - https://www.npmjs.com/package/@tinacms/icons
- `gatsby-tinacms-remark` - https://www.npmjs.com/package/gatsby-tinacms-remark
- `gatsby-tinacms-teams` - https://www.npmjs.com/package/gatsby-tinacms-teams
- https://www.npmjs.com/package/@tinacms/git-client
- https://www.npmjs.com/package/@tinacms/react-forms
- https://www.npmjs.com/package/react-tinacms
- https://www.npmjs.com/package/@tinacms/react-sidebar
- https://www.npmjs.com/package/@tinacms/react-toolbar
- https://www.npmjs.com/package/next-tinacms-markdown
- https://www.npmjs.com/package/gatsby-tinacms-mdx
- https://www.npmjs.com/package/@tinacms/teams
- https://www.npmjs.com/package/react-tinacms-strapi
- https://www.npmjs.com/package/@tinacms/tina-build

**Comment by jeffsee55** [comment]
- https://www.npmjs.com/package/react-tinacms-github
- https://www.npmjs.com/package/next-tinacms-json
- https://www.npmjs.com/package/react-tinacms-inline
- https://www.npmjs.com/package/react-tinacms-blocks

**Comment by jeffsee55** [comment]
If others find a package that's not properly marked please post it here
