### ISSUE TITLE
Upgrading @tinacms/cli from 0.59.0 -> 0.60.0 breaks language props for custom Code component in rich-text

### ISSUE THREAD

**Issue by c-kirkeby** [tinacms/tinacms#2470]
## Description

When upgrading @tinacms/cli from 0.59.0 -> 0.60.0 , the syntax highlighting with react-prism-renderer seems to break. It seems to apply the 

### Steps to reproduce

1. `git clone git@github.com:c-kirkeby/portfolio-next.git tinacms-language-bug` 
2. `cd tinacms-language-bug`
3. `git checkout 5adcb80620af26cd5e435ced097c6f65fc689697`
4. `npm install`
5. `npm install @tinacms/cli@^0.59.0`
6. `npm run dev`
7. Navigate to `http://localhost:3000/blog/syntax-highlighting`
At this point, a language prop of `typescript` gets passed to the custom `Code` component defined in my [custom TinaMarkdown wrapper component](https://github.com/c-kirkeby/portfolio-next/blob/5adcb80620af26cd5e435ced097c6f65fc689697/components/MDX.tsx).
8. Stop the dev server and run `npm install @tinacms/cli@^0.60.0
9. Start the dev server back up `npm run dev`
10. Repeat step 7.
At this point the `language` prop gets passed as `undefined`.

I originally had this issue with the latest versions of tinacms and @tinacms/cli; I just went ahead and determined when the breaking change was introduced.

### Expected result

Since I've defined the `language` field on the `Code` template, I would expect that it gets passed like it does in 0.59.0.

### Actual result

It seems the pre-0.60.0 isn't passing the right `language` field.

#### Tinacms Package Versions

```text
tinacms 0.64.2
@tinacms/cli 0.60.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Firefox 96.0 (64-bit)      |
| os      |  Zorin OS 16 (Ubuntu)       |
| node    |      16.13.2   |
| npm     |     8.13    |

**Comment by logan-anderson** [comment]
@c-kirkeby I think that the types might have been off in our Markdown renderer component (believe it is fixed now in latest version).  Can you try using `props.lang` instead?
