### ISSUE TITLE
Getting error when I run the new Tina starter command.

### ISSUE THREAD

**Issue by rafidalhaque** [tinacms/tinacms#2484]
### Discussed in https://github.com/tinacms/tinacms/discussions/2483

<div type='discussions-op-text'>

<sup>Originally posted by **rafidalhaque** January 25, 2022</sup>
**Hello!**
When I run this :arrow_down:  command to setup a new Tina starter from CLI,

```bash
npx create-tina-app@latest
```

I receive this error message,
```bash 
npm ERR! code E404
npm ERR! 404 Not Found - GET https://packagecloud.io/github/git-lfs/npm/isexe/-/isexe-2.0.0.tgz
npm ERR! 404 
npm ERR! 404  'isexe@https://packagecloud.io/github/git-lfs/npm/isexe/-/isexe-2.0.0.tgz' is not in this registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2022-01-25T06_30_58_841Z-debug-0.log
```

How can I fix it, please? 

**P.S.:** Log is attached. 

**Log:**
[2022-01-25T06_30_58_841Z-debug-0.log](https://github.com/tinacms/tinacms/files/7931200/2022-01-25T06_30_58_841Z-debug-0.log)
</div>

**Comment by perkinsjr** [comment]
Closing this issue in favor of the Discussion 2483
