### ISSUE TITLE
Using useTina at the layout-level a bit awkward

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2503]
With the useTina rework, now instead of passing query/variables/data into the `<TinaCMS>` container, you plug your data into `useTina`. 
Some sites, such as our tina-cloud-starter, use tina to edit layout-level content. 

The workaround involved creating a `QueryContainer` component at the layout level, and passing down its value as a childProp:
https://github.com/tinacms/tina-cloud-starter/pull/214/files 
This wouldn't be too bad on its own, but the user needs to be aware to add this key so their container component: https://github.com/tinacms/tina-cloud-starter/pull/214/files#diff-a9827ce1be32c607c948881a89b99c592f752898f9c49e0dea0b7199eb151029R76 (or else they will get an error when changing pages in edit-mode). 

Should we create a `QueryContainer` helper component in our tinacms package? (The code-splitting side of that might be a bit awkward, but maybe that gets better with [this proposal](https://github.com/tinacms/tinacms/discussions/2402#discussioncomment-2000313))

Is editing a site-wide layout even common with Tina in practice?

**Comment by jeffsee55** [comment]
> Is editing a site-wide layout even common with Tina in practice?

I think it is, with themes and navs both being site-wide things to consider. We can educate users that they'll have an easier time dropping that stuff into page-level components - which makes sense for things like nav headers and footers since you'll likely have at least 1 page that doesn't need them eventually. But makes less sense for something like a theme.

**Comment by jamespohalloran** [comment]
Maybe this type of thing is a good fit for our ["Micro-guides"](https://github.com/tinacms/tinacms/discussions/2667)
Editing Theme/Layout-level data with Tina
