### ISSUE TITLE
Active field indicator doesn't seem to be working for some fields

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tinacms#2518]
## Description

The Active Field Indicator doesn't appear to be highlighting in certain cases. 

### Steps to reproduce

@Perni1984 created a video of this happening within a block: https://www.loom.com/share/07ee0ea741d34bed85a413982447136c

Here's an example outside of a block (not sure if these are the same issue):

- Edit a blog post title in the tina-cloud-starter (example: http://localhost:3000/posts/anotherPost)
- The component appears to have the correct data attribute: https://github.com/tinacms/tina-cloud-starter/blob/main/components/post.tsx#L132

### Expected result

The field is highlighted.

### Actual result

The field is not highlighted.

#### Tinacms Package Versions

```text
tinacms@0.64.2
```

**Comment by gitsstewart** [comment]
Per Mitch - this could be a regression because our docs have a gif of this working.
Per pcode - this doesn't feel experimental for them, but rather really critical.
