### ISSUE TITLE
Link to FAQ for common "Content API unavailable" errors

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2519]
As a developer I want to have some error messaging for common "Content API unavailable" errors so that I can have better information to help me debug the issue. 

**Expected Results:**
- Confirm the below list of potential issues
- Create FAQ for this category of "Content API not available" errors
- The Error is visually displayed for all of the defined error-cases. The error body should link to the FAQ.

**Notes:**

Currently, we have several common usage errors that can lead to an abiguous error such as:

![](https://cdn.discordapp.com/attachments/835172431836479508/937675650360279080/unknown.png)

### Common causes of the GraphQL request failing

- Invalid branch (or undefined branch)
- .tina directory (with generated subdirectory) not pushed to git
- api url is misformatted
- Trying to access localhost graphql in prod (or locally when it's not running). 
- Document doesn't exist

### Where should we display this error?

- On the admin, when `getCollections` fails
- In the admin, in an individual document
- When contextual editing, and on a document

Note: For V1, from the clientside, we should just show this generic error that links to the FAQ
(In the future, we can probably should specific errors for certain specific cases. 
E.g, For the case where the schema isn't pushed to a given branch, the backend could check if there's a schema missing, and give an error with an error code)

**Comment by jeffsee55** [comment]
@jamespohalloran I like it, should we start to think about a list of error codes to help with this? For example, yarn does a nice job of this https://yarnpkg.com/advanced/error-codes

**Comment by gitsstewart** [comment]
Outstanding question:
1. Does adding the link to the new FAQ page belong in the client side (which is only one place in the code) or in the graphQL api everywhere that "Content API Unavailable" is thrown?

**Comment by jamespohalloran** [comment]
I added some notes in the description. For v1, I believe we can handle this all from the clientside

**Comment by mittonface** [comment]
@tinacms/maintainers I'm having a slightly tricky time actually knowing where to find where to the different errors. Not quite sure what I'd search to find the different locations. Any hints?

**Comment by mittonface** [comment]
I wasn't overthinking it. [Changing the error boundary](https://github.com/tinacms/tinacms/commit/43d9f3bf7e451a1d7368a9e514eb8c0f6273729c) is easy enough but only covers a couple of the errors. 

Other errors that you might get just get sent out as a `cms.alert`, which are not really able to handle links. i.e. https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/admin/components/GetCollections.tsx#L32-L35 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/5082908/160478195-8fed3cb0-2a3d-4e2b-96e9-aa340622401a.png">

**Comment by mittonface** [comment]
@tinacms/maintainers Should I go down the path of using dangerouslySetInnerHTML within cms.alerts? Is there some other solution? Or should we just rethink this ticket? 

The UI for the dangerouslySetInnerHTML option isn't great. You don't get a lot of ability to style things in there and the whole alert is clickable so a link in there is sort of hard to distinguish.

**Comment by logan-anderson** [comment]
> Should I go down the path of using dangerouslySetInnerHTML within cms.alerts? Is there some other solution? Or should we just rethink this ticket?

No I don't think so. 

Couple of options.
- Put the link the `console.error` and add "look at console for additional error context" text in the popup
- Throw the error and let Nextjs take care of it.

**Comment by jamespohalloran** [comment]
Are we using dangerouslySetInnerHTML so that the server can return something that includes the link HTML?

I'm sure I'm missing context, but what I originally was thinking was that the server (or whatever throws the error) would include some error code for this error, and the frontend Error boundary would conditionally be responsible for interpreting the error, and rendering the error display with the proper link.

**Comment by mittonface** [comment]
I can throw the error and try to let it bubble to the error boundary. I just wasn't sure if we were using `cms.alert` for a good reason or not!
