### ISSUE TITLE
MDX field triggers "Unsaved changes" indicator without content changes

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2521]
See [original comment on PR](https://github.com/tinacms/tinacms/pull/2473#issuecomment-1026232632)

The indicator is triggered just by the act of clicking on the area. The reason for this is that we need to normalize so they always have `children`, even if they're void nodes. The drawback of this is that the shape of the editor changes as soon as we interact with it (because the normalizer runs).

**Comment by dwalkr** [comment]
wonder if it could be as easy as calling [updateInitialValues](https://github.com/tinacms/tinacms/blob/861b42fef603ff587a8d71122293382253d45e26/packages/%40tinacms/toolkit/src/packages/forms/form.ts#L251) after doing an initial normalization

we use `updateInitialValues` to enable form values to load asynchronously while maintaining the pristine state

**Comment by jeffsee55** [comment]
@dwalkr That sounds perfect! I'll give that a shot. Is that being used anywhere?

**Comment by dwalkr** [comment]
the only usage example I'm aware of is to support `useForm`'s `loadInitialValues` option: https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/packages/react-core/use-form.ts#L86

**Comment by jeffsee55** [comment]
Even if it doesn't work, I think you're on the right track and we can probably get something working with a few tweaks if necessary.
