### ISSUE TITLE
Look into submitting more information about errors to metrics API

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2524]
This looks great, a couple of small comments. One thing we may also want to include (though it may be too noisy) would be [here](https://github.com/tinacms/tinacms/blob/132c630b97bcf29fb98a91784a9444a8bad4a9b9/packages/@tinacms/cli/src/cmds/start-server/server.ts#L59). If `result.errors`, we could report those. Let's hold off on that until we get this thing working and maybe revisit.

_Originally posted by @jeffsee55 in https://github.com/tinacms/tinacms/pull/2450#pullrequestreview-868542583_

**Comment by jamespohalloran** [comment]
We may still want to track different types of errors, but closing for now (as we have an open ticket for: https://github.com/tinacms/tinacms/issues/2620)
