### ISSUE TITLE
Set up Vercel deployments for examples

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2528]
Now that Tina supports pathToConfig, we should use at least one of our starters to deploy previews on PRs

**Comment by jamespohalloran** [comment]
Can you clarify what you mean with this ticket @jeffsee55?

**Comment by jeffsee55** [comment]
I just mean that we should run the Tina Cloud Starter or something so reviewers of a PR will have something to look at without pulling it down. Before we had `pathToConfig` in Tina.io this wasn't easily doable.

**Comment by jamespohalloran** [comment]
So just to be clear, this task would be adding 3 Vercel projects for the following mono-repo examples?
https://github.com/tinacms/tinacms/tree/main/examples/basic
And the 2 experimental examples?
https://github.com/tinacms/tinacms/tree/main/experimental-examples

Or are you referring to the standalone starter repos?

**Comment by jeffsee55** [comment]
I'd say we could just deploy the starter that's in this repo (https://github.com/tinacms/tinacms/tree/main/experimental-examples).
