### ISSUE TITLE
Importing from .tina directory doesn't work on non-typescript sites

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2531]
## Description

We have a few instances where the user would import from files in the .tina directory:
1) Import types from `/.tina/__generated__/types.ts` (This wouldn't make sense to do outside of typescript)
2) Import autogenerated SDK (client): This part of the `types` file. I don't believe we mention anywhere that it only works with typescript
3) In the [Extending Tina conversation](https://github.com/tinacms/tinacms/discussions/2402), we're discussing importing the Tina configuration from the .tina directory (This could technically be a jsx file, but it's something to be discussed)

These files are mostly typescript files, so they will throw a "module not found" error if imported from a non-typescript site.
I wanted to use the experimental SDK in the [barebones starter](https://github.com/tinacms/tina-barebones-starter), and I had to first add a .tsconfig to the project

Should we:
- Add documentation to any cases where a .tsconfig file is needed?
- Make typescript a prerequisite to using tina?
- Add non-typescript support for the .tina directory files.

**Comment by jamespohalloran** [comment]
> With the extending Tina discussion I think we'd just allow the schema file to be whatever the user wants it to be `.jsx | .tsx | .ts | .js`, I feel like that'd solve the issues here right?

For the client-specific problem (# 2 on the list above), We'd also need to conditionally output the autogenerated-client/SDK into a non-js file instead of the types.ts file.

**Comment by jeffsee55** [comment]
Related to https://github.com/tinacms/tinacms/issues/2457
