### ISSUE TITLE
Move default Tina wrapper to its own file

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2545]
## Summary

One clunky part of setting up Tina is handling the dynamic imports. 

Here's the most simple example of setting up Tina in your _app.jsx
```jsx
// pages/_app.js
import dynamic from 'next/dynamic'
import { TinaEditProvider } from 'tinacms/dist/edit-state'
const TinaCMS = dynamic(() => import('tinacms'), { ssr: false })

const App = ({ Component, pageProps }) => {
  return (
    <>
      <TinaEditProvider
        editMode={
          <TinaCMS apiURL="http://localhost:4001/graphql">
            <Component {...pageProps} />
          </TinaCMS>
        }
      >
        <Component {...pageProps} />
      </TinaEditProvider>
    </>
  )
}

export default App
```

Our `tina init` will ask if you want to overwrite your _app.jsx file (which I think would think for 99% of NextJS sites, that wouldn't be ideal). If we could instead output all the of the Tina setup in its own file, then Tina could be added by running tina init, and wrapping the layout in one simple `<Tina>` wrapper component.

We kind of touched on this in [this thread](https://github.com/tinacms/tinacms/discussions/2402), but I don't see a reason that it couldn't be tackled independently of the "Extending Tina" work
 
### Basic example

The cli would create `./components/tina.(jsx|tsx)`  
```jsx
import dynamic from "next/dynamic";
const TinaCMS = dynamic(() => import("tinacms"), { ssr: false });
import { TinaEditProvider } from "tinacms/dist/edit-state";

const branch = "main";
// When working locally, hit our local filesystem.
// On a Vercel deployment, hit the Tina Cloud API
const apiURL =
  process.env.NODE_ENV == "development"
    ? "http://localhost:4001/graphql"
    : `https://content.tinajs.io/content/${process.env.NEXT_PUBLIC_TINA_CLIENT_ID}/github/${branch}`;

const Tina = ({ children }) => {
  return (
    <>
      <TinaEditProvider
        showEditButton={false}
        editMode={
          <TinaCMS
            apiURL={apiURL}
            cmsCallback={(cms) => {
              cms.flags.set("tina-admin", true);
            }}
          >
            {children}
          </TinaCMS>
        }
      >
        {children}
      </TinaEditProvider>
    </>
  );
};

export default Tina;
```
^ This would only ever need to be adjusted later by the user if they want to update their config.

The CLI would instruct the user to add `<TinaCMS>` to their _app.jsx

```jsx
import TinaCMS from "../components/Tina";

const App = ({ Component, pageProps }) => {
  return (
    <>
      <TinaCMS>
        <Component {...pageProps} />
      </TinaCMS>
    </>
  );
};

export default App;
```

### Motivation

Now the user doesn't need to manually setup the dynamic imports. 
It's also less error-prone, as before in the user's _app.jsx, there was 2 places where the child `Component` was rendered (one in edit-mode, 1 in production):
```jsx
   <>
      <TinaEditProvider
        showEditButton={true}
        editMode={
          <TinaCMS apiURL={apiURL}>
            <Component {...pageProps} />
          </TinaCMS>
        }
      >
        <Component {...pageProps} />
      </TinaEditProvider>
    </>
```
If the user didn't pass those `pageProps` to one of the children components, it would cause issues. Now, it's only handled in one place in the user's _app.jsx:

```jsx
      <TinaCMS>
        <Component {...pageProps} />
      </TinaCMS>
    </>
```

This project would entail:
- Updating the CLI
- Updating the docs
- Updating our examples

---
Note: See[ this draft PR](https://github.com/tinacms/tinacms.org/pull/1226) for a list of remaining TODOs

**Comment by jeffsee55** [comment]
The one thing that sticks out as a bit awkward here is that most sites will have other dynamic imports. I know what you mean, it is cleaner with your example as shown, but I'd argue that the `<TinaEditProvider>` should be in it's own file, separate from the stuff you need to import dynamically else because of all of the other imports you're likely to need. For example our cloud starter looks more like this:
```tsx
import dynamic from "next/dynamic";
const TinaCMS = dynamic(() => import("tinacms"), { ssr: false });
import { TinaEditProvider } from "tinacms/dist/edit-state";

const TinaCMS = dynamic(() => import("tinacms"), { ssr: false });

const branch = "main";
// When working locally, hit our local filesystem.
// On a Vercel deployment, hit the Tina Cloud API
const apiURL =
  process.env.NODE_ENV == "development"
    ? "http://localhost:4001/graphql"
    : `https://content.tinajs.io/content/${process.env.NEXT_PUBLIC_TINA_CLIENT_ID}/github/${branch}`;

const Tina = ({ children }) => {
  return (
    <>
      <TinaEditProvider
        showEditButton={false}
        editMode={
          <TinaCMS
            apiURL={apiURL}
            mediaStore={async () => {
              // this is awkward
              const pack = await import("next-tinacms-cloudinary");
              return pack.TinaCloudCloudinaryMediaStore;
            }}
            cmsCallback={(cms) => {
              cms.flags.set("tina-admin", true);
              // this is awkward
              import("react-tinacms-editor").then(({ MarkdownFieldPlugin }) => {
                cms.plugins.add(MarkdownFieldPlugin);
              });
          >
            {children}
          </TinaCMS>
        }
      >
        {children}
      </TinaEditProvider>
    </>
  );
};

export default Tina;
```

I'd find this to be cleaner:
```tsx
import TinaCMS from "tinacms";
import { TinaCloudCloudinaryMediaStore } from "next-tinacms-cloudinar";
import { MarkdownFieldPlugin } from "react-tinacms-editor";

const branch = "main";
// When working locally, hit our local filesystem.
// On a Vercel deployment, hit the Tina Cloud API
const apiURL =
  process.env.NODE_ENV == "development"
    ? "http://localhost:4001/graphql"
    : `https://content.tinajs.io/content/${process.env.NEXT_PUBLIC_TINA_CLIENT_ID}/github/${branch}`;

const Tina = (props) => {
  return (
    <TinaCMS
      apiURL={apiURL}
      mediaStore={TinaCloudCloudinaryMediaStore}
      cmsCallback={(cms) => {
        cms.flags.set("tina-admin", true);
        cms.plugins.add(MarkdownFieldPlugin);
      }}
      {...props}
    />
  );
};
```
And then obviously keep most of the other code
```tsx
import dynamic from "next/dynamic";
import { TinaEditProvider } from "tinacms/dist/edit-state";
const Tina = dynamic(() => import("./components/tina"), { ssr: false });

export default function () {
  return (
    <TinaEditProvider
      showEditButton={true}
      editMode={(props) => <Tina {...props} />}
    >
      <Component {...pageProps} />
    </TinaEditProvider>
  );
}
```

**Comment by jamespohalloran** [comment]
> The one thing that sticks out as a bit awkward here is that most sites will have other dynamic imports.

Can you clarify what you mean here? I don't quite why other dynamic imports wouldn't work with what I suggested.

> ```tsx
> import dynamic from "next/dynamic";
> import { TinaEditProvider } from "tinacms/dist/edit-state";
> const Tina = dynamic(() => import("./components/tina"), { ssr: false });
> 
> export default function () {
>   return (
>     <TinaEditProvider
>       showEditButton={true}
>       editMode={(props) => <Tina {...props} />}
>     >
>       <Component {...pageProps} />
>     </TinaEditProvider>
>   );
> }
> ```

So this is your _app.jsx right? What's the props your passing into `<Tina {...props} />`
This to me looks very close to what we have now, except `editMode={(props) => <Tina {...props} />}` doesn't need to include the child `Component`. Is that correct?

**Comment by jeffsee55** [comment]
> Can you clarify what you mean here? I don't quite why other dynamic imports wouldn't work with what I suggested.

I mean that if we put everything in another file, then the other imports like `TinaCloudCloudinaryMediaStore` and `MarkdownFieldPlugin` still need to be imported dynamically. If you failed to do that you'd mess up your bundle size. So moving _everything_ over to another file means you still need to import those dynamically, if we can keep the edit state stuff in your `_app.jsx` then you don't have to worry about that.

> This to me looks very close to what we have now

I just meant to show that your example above:
```tsx
   <>
      <TinaEditProvider
        showEditButton={true}
        editMode={
          <TinaCMS apiURL={apiURL}>
            <Component {...pageProps} />
          </TinaCMS>
        }
      >
        <Component {...pageProps} />
      </TinaEditProvider>
    </>
```
Shouldn't supply `pageProps` to the `Component` in editMode, and we can simplify that under the hood to make things more concise.

**Comment by jamespohalloran** [comment]
Oh I see what you mean.
So, I think my example makes the initial setup easier, but yours makes adding plugins more foolproof. 

What if..

```jsx
//components/tina.index.jsx

//The user should never have to touch this file

import dynamic from "next/dynamic";
const TinaProvider = dynamic(() => import("./TinaProvider"), { ssr: false });
import { TinaEditProvider } from "tinacms/dist/edit-state";

const Tina = ({ children }) => {
  return (
    <>
      <TinaEditProvider editMode={<TinaProvider>{children}</TinaProvider>}>
        {children}
      </TinaEditProvider>
    </>
  );
};

export default Tina;
```

```jsx
// components/tina/TinaProvider
// User customizes Tina here, any anything added here is already dynamically imported

import TinaCMS from "tinacms";

const TinaProvider = ({ children }) => {
  return (
    <TinaCMS
      apiURL={"http://localhost:4001/graphql"}
    >
      {children}
    </TinaCMS>
  );
};

export default TinaProvider;
```

```jsx
// app.jsx
import TinaCMS from "../components/Tina";

const App = ({ Component, pageProps }) => {
  return (
    <>
      {/* This wrapper is the only thing the user needs to manually add to add Tina */}
      <TinaCMS> 
        <Component {...pageProps} />
      </TinaCMS>
    </>
  );
};

export default App;
```

I feel like I may be on the verge of over-engineering :D, but, compared to what we have now:
- The user has a simpler (and more copy&pastable) wrapper to add to their layout
- The user never needs to handle dynamic imports

**Comment by jeffsee55** [comment]
> So, I think my example makes the initial setup easier, but yours makes adding plugins more foolproof.

Yeah exactly. I think I'm on the same page, you kinda need 2 for this to feel easy and stay out of the way for `_app.js` - and yes over-engineering thoughts are creeping in for me too. 

I think it's worth toying around with to see, but since our chat on Extending Tina I've been more convinced that `.tina/` is the right place for all of these files. Shouldn't be a blocker either way though.

Sidenote: I _think_ we could use React.lazy instead of `next/dynamic` because this is all client-side stuff. We should probably look into that so we can keep the same flow regardless of framework.

**Comment by mitchmac** [comment]
> Another thing I'm wondering..
By default, should tina init wrap the /admin page in <TinaCMS>? That way the user can just run tina init, go to localhost:3000/admin, and start editing content.

This would be consistent with how folks will have to set up if they aren't able to use contextual editing (non React SSGs).

**Comment by gitsstewart** [comment]
Goal: Keep things simple for now

Remainder of work for this:
1. Review the CLI work - is this what we want to do? how we want it to work?
2. Write up docs to accompany what has been done so far

Review draft PR https://github.com/tinacms/tinacms/pull/2549

**Comment by jamespohalloran** [comment]
For transparency, There are some remaining TODO's in this draft PR body: https://github.com/tinacms/tinacms/pull/2549
