### ISSUE TITLE
Explore using React.lazy instead of next/dynamic for dynamic loading Tina

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2552]
## Summary

Currently, we encourage using next/dynamic for code-splitting Tina. If we can get this working with React.lazy, we'll be  closer to support Non-NextJS React-based sites.

As @jeffsee55 mentioned [here](https://github.com/tinacms/tinacms/issues/2545#issuecomment-1030419362), 
> TinaEditProvider will need to wrap children with Suspense, I think.

**Comment by jeffsee55** [comment]
This works as expected, we could remove the `TinaDynamicProvider` file entirely and do this instead in your `_app.js`:

```tsx
import "../styles.css";
import { lazy } from "react";
import { TinaEditProvider } from "tinacms/dist/edit-state";

const App = ({ Component, pageProps }) => {
  return (
    <TinaEditProvider editMode={lazy(() => import("../.tina/config"))}>
      <Component {...pageProps} />
    </TinaEditProvider>
  );
};

export default App;
```
We just needed Suspense in the `TinaEditProvider` component. 

- [ ] Confirm if this requires a new minimum version of React
- [ ] For the loading state during `next/dynamic` we show a blank screen. We can probably improve that. This is not the same as the loading state of `useTina`.

**Comment by jamespohalloran** [comment]
Users no longer need to manually lazy load, with upcoming iframe implementation
