### ISSUE TITLE
No Media Store Configured

### ISSUE THREAD

**Issue by ari-motors-team** [tinacms/tinacms#2559]
## Summary

I tried to get tinacms running, but wasn't able to use the media store.

error
```
No Media Store Configured
To use the media manager, you need to configure a Media Store.
```
provider in _app.js
```js
<TinaEditProvider
        editMode={
          <TinaCMS
            apiURL={apiURL}
          >
            <Component {...pageProps} />
          </TinaCMS>
        }
      >
        <Component {...pageProps} />
</TinaEditProvider>
```

I know that I am supposed to ass `mediaStore`, but I can't find a hint on how to create the media store instance itself.

### Motivation

I want to be able to upload images through the media store to the github repo (/public/images).
I do not want to use cloudinary.

**Comment by mitchmac** [comment]
Hi @ari-motors-team 👋  Thanks for the report; there isn't direct repo based media support currently, but we are hoping to get to it soon. [Discussion with a bit of background](https://github.com/tinacms/tinacms/discussions/2298).

For reference, there is some context on media stores in the [docs for the Cloudinary implementation](https://tina.io/docs/media-cloudinary/).

Specifically, [here are the docs](https://tina.io/docs/media-cloudinary/#register-the-media-store) on how to register the Cloudinary media store to use it on a site. Using the repo based store will be configured similarly I would guess, any opinion on how that is done?

**Comment by ari-motors-team** [comment]
ty :)
