### ISSUE TITLE
Add hook for client-side data fetching

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2560]
With the addition of read-only tokens support coming soon, we'd like to expose a hook that allows us to do data fetching _and_ "hydrating" that data with contextual editing. We currently have `useTina` which accepts `query`, `variables`, and `data` - but now we'll need one which would not accept a `data` property, and would instead do the actual data fetching itself.

This hook needs to know the API url and the read-only token, I don't want to get into implementation details here too much, but we've talked about exposing a lightweight HTTP client which makes this setup easy, something that just takes `apiURL` and `token` or something similar. Perhaps that could be passed in to this hook:
```ts
const client = createClient({apiURL: "", token: ""})
const { data, isLoading } = useTinaQuery({query, variables, client})
// or more simply
const { data, isLoading } = useTinaQuery({query, variables, apiURL: "", token: ""})

```

---

Down the road we'll want this to support React Server Components, it's too early to say what that should look like but I expect we'll be able to use this same hook in that context, though I'm not sure.

Note: This work is important for Read-Only Tokens

**Comment by logan-anderson** [comment]
Closing in favour of #2628
