### ISSUE TITLE
Date picker gets crazy

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#257]
## Description

Hours and minutes are spinning endlessly in the date picker

### Steps to reproduce

1. Click on a date field
2. Try to click on hours or minutes

### Expected result

Increment or decrement hours and minutes

### Actual result

Infinite loop

![tina-crazy-date-picker](https://user-images.githubusercontent.com/103008/66414894-9ad11400-e9fa-11e9-8dc0-c444d46da3e0.gif)

### Environment

latest macOS/Firefox

```
@tinacms/gatsby-plugin-tinacms": "next"
@tinacms/gatsby-tinacms-git": "next"
@tinacms/gatsby-tinacms-json": "next"
@tinacms/react-tinacms-remark": "next"
```

**Comment by kendallstrautman** [comment]
Assuming this was fixed in #322, please reopen if behavior persists
