### ISSUE TITLE
Mdx file gets wiped when saving nested rich-text fields

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2581]
## Description

When I try and edit rich-text blocks, that are nested in other rich-text blocks, my mdx content will get wiped out. 

https://www.loom.com/share/4f85b22ec24a410b97c7c3868c7ab8b4

### Steps to reproduce

```ts
import { defineSchema } from "@tinacms/cli";

export default defineSchema({
  collections: [
    {
      label: "Slides",
      name: "slides",
      format: "mdx",
      path: "content/slides",
      fields: [
        {
          label: "Body",
          name: "body",
          isBody: true,
          type: "rich-text",
          templates: [
            {
              name: "Steps",
              label: "Steps",
              fields: [
                {
                  type: "rich-text",
                  name: "children",
                  label: "children",
                  templates: [
                    {
                      name: "Step",
                      label: "Step",
                      fields: [
                        {
                          type: "rich-text",
                          name: "children",
                          label: "children",
                          templates: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },

          ],
        },
      ],
    },
  ],
});

Go and edit the "Step" component, and you will see that the underlying mdx file is now empty.

@spbyrne mentioned he has a reliable reproduction on the Tina Cloud Starter:

> Here’s how I replicated it when testing: “Add a blockquote component, open it and add an image to the blockquote’s MDX editor (select from media manager, don’t fill caption or alt text) & then click ‘save’. Seems to save a blank document every time, not sure if this is specific to something in the cloud starter.”

```

#### Tinacms Package Versions

├── @tinacms/cli@0.60.5
├── tinacms@0.66.3

(This uses the alt-mdx editor)

**Comment by scottgallant** [comment]
I've been hitting this issue too but my nested fields are just string fields.

**Comment by jamespohalloran** [comment]
> I've been hitting this issue too but my nested fields are just string fields.

I dug into Scott's site, as it's fairly easy to reproduce:
Here's a fork: https://github.com/jamespohalloran/scottgallant.me-bug

The error can be reproduced by adding some text to the body of [this page](http://localhost:3000/articles/temp)

Error in the console: 
<img width="678" alt="Screen Shot 2022-06-23 at 9 02 10 AM" src="https://user-images.githubusercontent.com/3323181/175295830-89180618-c01b-4471-90e2-14e36c6308fa.png">

(Seems to be an error around [handling of `li`](https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/graphql/src/mdx/stringify.ts#L222)).

I dug through the code in the node_modules, it seems there's a lot of places we're swallowing the error. I don't think Scott was running into the exact same issue as me, but it seems if there's any issue parsing the MDX, the content gets deleted. 

E.g
[1](https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/graphql/src/mdx/stringify.ts#L50)
[2](https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/graphql/src/mdx/stringify.ts#L521)
[3]https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/graphql/src/mdx/parse.ts#L394
