### ISSUE TITLE
Implement `RouteMapping` plugin for dummy posts created with tina cli's init

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2591]
## Summary

The `npx @tinacms/cli@latest init` command creates some dummy posts, a dummy schema, and an admin page. Now that we have added the new admin experience, and introduced the ["RouteMapping" plugin](https://github.com/tinacms/tinacms.org/pull/1232/files#diff-7349b5c7f0dd200645c64944973bc6ab5784a61c7ba52e4e212725a44579390dR132), the CLI should implement the `RouteMapping` plugin so that the user can quickly experience contextual editing.

**Comment by jeffsee55** [comment]
I thought we were thinking that `init` would no longer add the contextual part since admin can stand up by itself?

**Comment by jamespohalloran** [comment]
What would be the reason not to? I would think we'd want to showcase the best experience possible as it will be one of the first that the user interacts with when using Tina init.

**Comment by jeffsee55** [comment]
Just that we run into issues when we overwrite `_app.js`

**Comment by jamespohalloran** [comment]
Oh ok, yeah https://github.com/tinacms/tinacms/pull/2549 would have to be a precursor to this ticket.
That way, we can reliably spit out that route Mapper config within the .tina directory without worrying about overwriting the _app.js.

**Comment by jeffsee55** [comment]
> - ~~Should the CLI init wrap the admin page with <TinaCMS> to start? Then the user could move it to _app.jsx later to optionally add contextual editing~~ Let's say no for now

This sounded good to me, it prevents a manual step for the user during init, are you suggesting we just go ahead and prompt the user from the CLI to make the final change to their `_app.js`?

**Comment by jeffsee55** [comment]
Also related to this, we're eying a change to the route mapper logic, so that it lives collocated with the schema https://github.com/tinacms/tinacms/discussions/2402#discussioncomment-2046317. This would probably be a bit cleaner for us to provide from the CLI but needs to wait on extending Tina work.

```ts
defineSchema({
 collections: [{
   name: "post",
   label: "Posts",
   path: 'content/posts',
   router: (collection, document) => {
     if(document.data.title === "Hello, World!") {
       return "/"
     }
     return `${collection.name}/document.sys.filename}`
   }
 }]
})
```

**Comment by jamespohalloran** [comment]
> Also related to this, we're eying a change to the route mapper logic, so that it lives collocated with the schema [#2402 (reply in thread)](https://github.com/tinacms/tinacms/discussions/2402#discussioncomment-2046317). This would probably be a bit cleaner for us to provide from the CLI but needs to wait on extending Tina work.
> 
> ```ts
> defineSchema({
>  collections: [{
>    name: "post",
>    label: "Posts",
>    path: 'content/posts',
>    router: (collection, document) => {
>      if(document.data.title === "Hello, World!") {
>        return "/"
>      }
>      return `${collection.name}/document.sys.filename}`
>    }
>  }]
> })
> ```

Oh nice, that seems cleaner. That way, when the dev wants to clear out the dummy stuff created from the CLI, they can just remove this collection. Otherwise, they would need to remove both the collection, and the routemapping config in separate files)

**Comment by jamespohalloran** [comment]
Still relevant (Even if the Routemapper may change in the future)
