### ISSUE TITLE
Using Queries from Autogenerated GraphQL Client leaks whole tina package into client bundle

### ISSUE THREAD

**Issue by Perni1984** [tinacms/tinacms#2602]
## Description

We would like to use the `useTina` hook together with the pregenerated queries from the experimental autogenerated GraphQL client. When doing so the `First Load JS` size increases significantly, as the whole tinacms package is included in the client bundles then, altough we are only importing one query.

The reason for this is IMHO that the autogenerated GraphQL client is exporting the queries with the `gql()` function, but we would just need the string of the queries. Copying over the strings of the queries in a separate file and just using this results in the expected decrease of the client side bundle size.

With query from autogenerated GraphQL Client imported:
![image](https://user-images.githubusercontent.com/9039956/154832890-f12c3c11-e123-453d-87fa-1624da3ea1e4.png)

With query (just the string) imported from a separate file:
![image](https://user-images.githubusercontent.com/9039956/154832916-2ce8b116-4fba-4420-acff-1dbce7fb5b90.png)

One solution could be to export just the plain query strings without the `gql()` function in the autogenerated client.

### Steps to reproduce

Just use the useTina hook with a autogenerated query from graphql client vs. just using the query string.

### Expected result

No significant increase in client bundle size.

### Actual result

Significant increase in client bundle size ( + ~770kb in our case)

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.5
├── next-tinacms-cloudinary@3.5.8
├── tinacms@0.66.4
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by logan-anderson** [comment]
@Perni1984 Currently the auto generated client is meant for only using on the backend and you can return your queries and variables in `getStaticProps`. You can see that happening in [this example](https://github.com/tinacms/tina-cloud-starter/blob/main/pages/%5Bfilename%5D.tsx#L8). This way next.js will automatically code-split out the generated client.

**Comment by llibdude** [comment]
@logan-anderson I have a simple repo here https://github.com/llibdude/tinacmsplayground

When i build it I am noti
![Screen Shot 2022-04-07 at 9 37 50 PM](https://user-images.githubusercontent.com/5255924/162354305-b672d5d4-fe55-4418-8a56-5a36d84e4d36.png)
cing the same bloat in builds

The repo is very simple, and seems to be doing exactly what you are suggesting with using the auto generated client server side and passing the info via `getStaticProps` https://github.com/llibdude/tinacmsplayground/blob/main/pages/%5B...campaign%5D.tsx

In fact, i even cloned the basic repo from tinacms and can also reproduce https://github.com/tinacms/tinacms/tree/main/examples/basic
![image](https://user-images.githubusercontent.com/5255924/162354591-5b397430-93f1-454b-9f42-676e26376bc3.png)

**Comment by jamespohalloran** [comment]
Do we know if this is still an active issue @logan-anderson ? 

> To update this ticket, I have found that while the documentation says to use defineSchema from @tinacms/cli, for me to fix my build size issues I actually need to import it from tinacms https://tina.io/docs/schema/.

Looks like these docs have since been updated.

**Comment by melon-husk** [comment]
@jamespohalloran Still happening, https://cdn.discordapp.com/attachments/835172431836479508/998684693157400666/unknown.png

**Comment by logan-anderson** [comment]
> @jamespohalloran Still happening, ![image](https://user-images.githubusercontent.com/30780724/179673993-b34d3cf7-7ba5-4d00-8458-a7590b0b8f09.png)

@melon-husk This bundle size is because you are using gql function from tinaCMS on the frontend. To get around this you can pass it as props in `getStaticProps`.

```ts
export const getStaticProps = async () =>{
   const query = gql`
   //... your query
  `
 
  // ... rest of data fetching

  return {
    props: {
       query,
       //..other props
    }
   } 
} 
```

and then in your component use the query passed from the props.

```ts
useTina({
  query: props.query
  // ... other tina props
})
```

If this does not fix your issue please let us know.

**Comment by melon-husk** [comment]
@logan-anderson Yes, that solves it, I went further and added custom query inside queries folder so the query would we available through through the experimentalClient. 
![image](https://user-images.githubusercontent.com/30780724/180339672-84ad539a-3c37-4ff9-b835-70e7cbc013b4.png)
Thank you !
