### ISSUE TITLE
create-tina-app fails (on Node 15)

### ISSUE THREAD

**Issue by papiermache** [tinacms/tinacms#2617]
## Description

npx create-tina-app fails.

### Steps to reproduce

```
$ npx create-tina-app@latest
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     XXXXXX\Local\npm-cache\_logs\2022-02-24T20_21_07_156Z-debug.log
```
error log just contains same text as above.

### Expected result

tina app created

### Actual result

failed to create tina app

### Environment

Windows 10

#### Tinacms Package Versions
    npm ls | grep tinacms | grep -v deduped

produced no result

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    | 15.8.0  |
| npm     |  7.5.1   |

**Comment by jamespohalloran** [comment]
Thinking this is likely a Windows specific bug. Mind if I assign to you @logan-anderson to test?

**Comment by papiermache** [comment]
Hello James,
A co-worker got it to install on his system, so might be something wrong specifcally with my machine, am re-testing now on another machine, back to you shortly on results.
Regards, Rick.

**Comment by papiermache** [comment]
Hello James, it installed fine on other machine (using Node 10.16.3).  But on first machine, still fails (using Node 15.8.0).

**Comment by logan-anderson** [comment]
@papiermache  It is working for me (on windows) on node version v14.17.0 and node version v16.14.0. Can you try updating to the latest LTS ( v16.14.0) and see if that resolves the issue?

**Comment by papiermache** [comment]
Ok I upgraded to latest node (17.6.4) and yes it all worked, thx!
Regards, Rick.

**Comment by jamespohalloran** [comment]
So I just tested on Mac on the Node version specified in the description (15.8.0) and I'm seeing the original error.
Upgrading to Node 16 works

**Comment by papiermache** [comment]
Hi james, thanks for digging into this issue. I’ll upgrade all our machines to latest node.
Regards, Rick.

**Comment by gitsstewart** [comment]
Next steps:
1. Finish researching and confirming this is a problem for which versions/products 
2. Update messaging to say "We do not support: Node 15, [list unsupported findings]"
