### ISSUE TITLE
When loading data, we should replace the Tina didn't find any queries.

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2637]
When loading data, we place an overlay over the site with "Tina is loading data, please wait" but in the side bar we have "Tina didn't find any queries" 

<img width="1440" alt="Screenshot_2022-03-04_at_12 10 15" src="https://user-images.githubusercontent.com/45409975/156753724-9d7f3e21-4bcd-43ca-a7a2-72617eb8ae59.png">

From a UX perspective this is confusing as you might believe that your site is in fact not working correctly. When we are loading the data, we should provide better feedback, so the user knows that we are attempting to load the data. 

Then if it fails, we can return the usual errors and replace the text in the sidebar. If successful return the forms.

**Comment by adnathanail** [comment]
Don't close! This is a good idea

**Comment by perkinsjr** [comment]
> Don't close! This is a good idea

Don't worry it won't be closed.
