### ISSUE TITLE
Make the dummy content/editor that is generated from @tinacms/cli more interesting

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2641]
As a developer trying out Tina with `@tinacms/cli init` I want to see a more fleshed-out editor with the generated dummy content, so that I can get a better representation of the Tina UI's potential

Expected Results:

~~Decide if we have different types of pages to show off more variety of examples / field-types?~~
~~Suggestion: One MDX page, One Blocks-based page (with 3 blocks), One Markdown-based "blog-post" page~~
- Edit: Update content/editor to use MDX
- Implement the changes to the new dummy content, the new Tina configuration, and the new pages.

Notes:

Currently, when you load up the first piece of dummy content, it looks like this:

<img width="1106" alt="Screen Shot 2022-03-04 at 10 56 32 AM" src="https://user-images.githubusercontent.com/3323181/156786794-cd604d14-0743-4b81-b5e3-72abafbb649e.png">

It's a tad underwhelming, compared to what Tina can do. The dev might think "My editors need to write Markdown?". I think there's a sweet spot of not bloating the users' site, but also capturing their interest when they first try Tina.

**Comment by logan-anderson** [comment]
@jamespohalloran This was created before we had the MDX component and renderer. I think that simple changing this site from using a text area to using the MDX renderer plus maybe a few components would go a long way. 

What do you think?

**Comment by mittonface** [comment]
I'll do my best!

**Comment by logan-anderson** [comment]
> I'll do my best!

@mittonface Please feel free to PM me for help.

**Comment by mittonface** [comment]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/5082908/159293214-ee9838d3-250d-4341-985f-a58e0ddd6dab.png">

I figured it out. Just going to spend a little more time making it actually a bit more interesting!
