### ISSUE TITLE
Should we add a triple-dot menu to the admin-view form if there’s a route mapped? Or some way to get to the contextual form and/or site?

### ISSUE THREAD

**Issue by gitsstewart** [tinacms/tinacms#2644]
Should we add a triple-dot menu to the admin-view form if there’s a route mapped? Or some way to get to the contextual form and/or site?

**Comment by Enigmatical** [comment]
This was answered both in the original discussion about the change in workflows surrounding the CMS and once more as we were nearing release - we'd like to strive for simplicity:  A single link that routes to either the basic editor or the contextual editor depending on how the site is configured.  For a user, having to choose between editors can introduce friction.

In the future, we may still want to introduce a triple-dot menu for things like Delete or other Document actions.
