### ISSUE TITLE
Alert the developer if pages/admin.{js|tsx} is missing when `tina-admin` flag is `true`

### ISSUE THREAD

**Issue by gitsstewart** [tinacms/tinacms#2645]
(If low effort) Alert the developer if the tina-admin flag is true (or defaulted true) and /pages/admin/[[...tina]].tsx is missing
From [@Enigmatical](https://github.com/Enigmatical) :
This would be achieved via the CLI so it might be best to poke [@logan-anderson](https://github.com/logan-anderson) and see what the effort would be.

**Comment by Enigmatical** [comment]
The good news is that the `tina-admin` flag _defaults_ to `true` now.  

I still think this card has merit for alerting the user if `pages/admin.{js|tsx}` is missing via the CLI.
