### ISSUE TITLE
Rich Text Dropdown menu Z-index issue

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#2648]
## Description
The rich text field dropdown menu is behind the toolbar. This probably isn't noticeable if you have one really long rich text field, but  it is noticeable if you have a second rich text field like in the "two columns" block of our new homepage. 

<img width="656" alt="Screen Shot 2022-03-04 at 5 21 23 PM" src="https://user-images.githubusercontent.com/776019/156843403-3edd9c91-bd1a-4633-96aa-28361d5f3c13.png">

**Comment by spbyrne** [comment]
Right now each toolbar has a `z-index` set to `50` in `@tinacms/toolkit/src/packages/fields/plugins/MdxFieldPlugin/updated/plate/plugins/ui/toolbar/index.tsx` on line 202. If I knew it was the active field I could bump it to `60` and it would fix this issue, maybe that information is available through the form context?

Other solutions I considered:
- I tried using `focus-within` but focus isn't really captured all the time when you're using the menu.
- I also tried setting a higher `z-index` on the panel dropdown component, but that didn't work; the stacking order is bound to the toolbar.
