### ISSUE TITLE
TinaCMS App crashes when using Brave Browser with Brave Shields enabled

### ISSUE THREAD

**Issue by kiastorm** [tinacms/tinacms#2654]
## Description

My TinaCMS app crashes when using Brave Browser with Brave Shields enabled.

### Steps to reproduce

1. Download and use Brave Browser
2. Ensure Brave Shields is enabled and visit https://kormsen-cms.vercel.app 
<img width="144" alt="image" src="https://user-images.githubusercontent.com/63059016/156919399-230fdd3d-0b56-4fbe-9c29-6453abce1d29.png">
3. Click 'Edit with Tina' `/admin` or visit any pages under 'Code' `/code/XXX`

4. The page crashes

### Expected result

It should work with Brave Shields enabled, or at least not crash and show a meaningful error.

### Actual result

It crashes / infinite loops

### Environment
Mac OS v11.5.2
Brave v1.36.109
```
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.0
├── next-tinacms-cloudinary@3.5.5
└── tinacms@0.65.3
```

**Comment by jamespohalloran** [comment]
I do notice that https://kormsen-cms.vercel.app/admin gives a 500, on Chrome.
Seems like there may be a site-specific issue? Closing for now as we'll need the admin.js to debug further.
