### ISSUE TITLE
Add support for `_template` field in objects

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2656]
Right now an `object` with `templates` doesn't return the `_template` field, even though it's present in the raw file. We should support it 

cc @employee451

**Comment by jeffsee55** [comment]
Not stale

**Comment by selenecodes** [comment]
Would be great if this was added.

**Comment by jamespohalloran** [comment]
I think it does make sense to have it, but just for putting a priority-level on it.. is there a usecase where we'd need `_template` rather than just using the `__typename`? https://github.com/tinacms/tina-cloud-starter/blob/main/components/blocks-renderer.tsx#L13

**Comment by selenecodes** [comment]
The only reason for me would be the ease of use/more intuitive way of working. Currently, one part of my codebase refers to a template with its given name, and another part relates to it by its `__typename`, reducing code-readability.

**Comment by jamespohalloran** [comment]
> The only reason for me would be the ease of use/more intuitive way of working. Currently, one part of my codebase refers to a template with its given name, and another part relates to it by its `__typename`, reducing code-readability. There's also the aspect where the JSON generated does contain the `_template` name, but this is not provided in the actual `useTina` data.
> 
> So for priority, personally, it's a "nice to have".

Perfect, thanks for the context! I agree that it is pretty awkward. We'll add it to our TODO's

**Comment by jeffsee55** [comment]
not stale

**Comment by arthuratmeetbreeze** [comment]
+1

**Comment by jeffsee55** [comment]
not stale
