### ISSUE TITLE
Code blocks are invisible when inline editing

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#267]
## Description

See https://github.com/tinacms/tinacms-site/issues/38

### Steps to reproduce

1. launch documentation website locally
2. browse to a page containing code blocks with an inline `edit` button
3. Click on `edit`

### Expected result

Code blocks content should be displayed

### Actual result

Code blocks content are invisible.

### Environment

latest macOS/Firefox

**Comment by kendallstrautman** [comment]
I can't reproduce this. Closing for now & also [tinacms-site #38](https://github.com/tinacms/tinacms-site/issues/38)
