### ISSUE TITLE
Sidebar Body Displacement Logic

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#2674]
Tina's Sidebar uses some pretty simple code to displace the website, and it has a number of issues.

1. It assumes the user is using `box-sizing: border-box;`, but that's not always true.
2. It takes control of the body element's left padding and transition properties, which may be in use already.
3. It doesn't actually change the size of the viewport, so responsive elements might not work as expected.

Example of **1**:
![image](https://user-images.githubusercontent.com/5075484/157680142-e77d93a9-36e9-4ed2-aad1-39d3b2da1479.png)
@jhuggett: "the sidebar is pushing my content off the screen."

**Comment by jeffsee55** [comment]
I think this is now closed since the iframe doesn't displace the user's window at all.
