### ISSUE TITLE
MDX Field Resets With Invalid Data

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#2701]
While testing the Smashing demo, Scott G came across an issue where reseting the form would insert the wrong data into the MDX field, using data from the summary textarea. [See at 0:45 in this loom video](https://www.loom.com/share/2fa4f540a106430286d5e9bc9e539823). I was able to recreate on my first try; I launched the project locally, clicked in to the MDX field (incorrectly signalling a 'dirty' form), clicked 'reset' and confirmed, and the same incorrect data was used to populate the form.

**Comment by jamespohalloran** [comment]
Same deal with: https://github.com/tinacms/tinacms/issues/2750
https://github.com/tinacms/tinacms/pull/2864 mentions that it fixes this issue, but I'm still seeing it on the latest of the tina-cloud-starter (tinacms: 0.68.7)
