### ISSUE TITLE
Collections not loading

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#2702]
I sometimes find the collections list loads indefinitely.  See screenshots.   Here are the steps that I followed today

1. Went to Tina.io/admin: saw collections
2. Went to Tina.io/docs and opened the sidebar: collections did not load
3. Refreshed the page: collections did not load
4. In a new tab, opened up app.tina.io (I was already signed in)
5. Went back to Tina.io/docs and reloaded the page for a 3rd time: collections loaded

<img width="533" alt="Screen Shot 2022-03-17 at 10 31 34 AM" src="https://user-images.githubusercontent.com/776019/158819642-72eba50e-d46b-4e18-972e-27b773d1c334.png">

<img width="1150" alt="Screen Shot 2022-03-17 at 10 31 46 AM" src="https://user-images.githubusercontent.com/776019/158819657-7f57127c-5b6d-4ffc-9041-7b366e749752.png">

**Comment by jamespohalloran** [comment]
I can't seem to reproduce this one. It's a bit old, so maybe fixed? @scottgallant
