### ISSUE TITLE
Ability to designate a field as the title (of a document)

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2723]
## Summary

As a user I want to see a more readable title than the filename in my collection view so that I can easily find the content that I want

### Depends On:
Data Layer no longer experimental OR a flag indicating opt-in to data layer (so we can see easily whether data layer is enabled)

### Expected Results

- In the schema, I should be able to set a "isTitle" property on a field definition, which marks it as the "title" field.
- If "isTitle" is true, it is also required
- When looking at the collection list view in the CMS, the "title" should be used as the main label (with the filename as a "secondary" field to differentiate between same titles that are not unique)
- Ideally, if there are more than one defined "isTitle" fields, the schema build will fail with an error.
- "isTitle" field must comply with the following constraints:
      - Must be a non-list field of type string with required: true.
      - Must be a top-level field (ie. not inside an object)
- Update documentation for this and for the addition of the data layer opt-in flag
- Tests pass

### Notes
If "isTitle" is false (on all fields of a collection), filename can be used as the title

**Comment by jeffsee55** [comment]
We've chatted about this before, following the convention of `isBody`, `isTitle` makes sense. It should be a static (non-ui) field so we can index it. Without the data layer this wouldn't be possible but should be doable now. @kldavis4 if we know which field is the title field at index-time, do you see any issues implementing this?

**Comment by jamespohalloran** [comment]
> We've chatted about this before, following the convention of `isBody`, `isTitle` makes sense. It should be a static (non-ui) field so we can index it. 

Sounds good to me, just updated the ticket description

**Comment by jeffsee55** [comment]
Additional constraints that I've sort of assumed:

- Must be a non-list field of type `string` with `required: true`.
- Must be a top-level field (ie. not inside an `object`)
- The value must be unique within a collection (perhaps globally unique?)

We may want to consider supporting a concept of uniqueness across certain fields. Perhaps the `isTitle` would do this automatically, but we could start to consider implementing some custom directives that a lot of other GraphQL apis have, could be the first of many, but it'd look like this when compiled to GraphQL:

```graphql
type Post {
  title: String! @unique
}
```

**Comment by jeffsee55** [comment]
Yeah, perhaps not a requirement on that last one. Coincidentally I think your comment [here](https://github.com/tinacms/product-roadmap/issues/96#issuecomment-1077659052) would require that it be a unique field, but maybe that's another flag we could support separately (`isUnique`?)

**Comment by jeffsee55** [comment]
The response to a document should support `title` as a property:

```graphql
{
  document {
    sys {
      title
    }
  }
}
```
