### ISSUE TITLE
Sorting by nested fields

### ISSUE THREAD

**Issue by kldavis4** [tinacms/tinacms#2735]
## Summary

As a TinaCMS developer I want to sort by nested fields so that I can present results according to the order of those field values

Sample field definition:

```
{
  type: 'object',
  name: 'numbers',
  fields: [
    {
      name: 'speed',
      type: 'number',
      required: true,
    },
    {
      name: 'glide',
      type: 'number',
      required: true,
    },
    {
      name: 'turn',
      type: 'number',
      required: true,
    },
    {
      name: 'fade',
      type: 'number',
      required: true,
    },
  ],
},
```

Should be able to sort by numbers.speed

### Expected Results

* result 1
* result 2
* example output
* UI/UX

### Notes

Currently any nested fields are being excluded from indexing which prevents sorting on these fields

**Comment by jamespohalloran** [comment]
When we circle back to this, we'll have to decide how this behavior works for an object with templates:
Certain sub-fields may be present in some documents, but not others.
