### ISSUE TITLE
TinaEditProvider error on create-tina-app@latest

### ISSUE THREAD

**Issue by blazardsky** [tinacms/tinacms#2752]
## Description

I just tried to install Tina on a new project using `npx create-tina-app@latest` and after going to localhost:3000/admin I got 
**Unhandled Runtime Error**
Error: No `TinaEditProvider` found

I haven't done anything. Inside TinaDynamicProvider.jsx the module {TinaEditProvider} is imported.

### Steps to reproduce
During build I choose:
- Package manager: NPM
- Project name: (left empty) my-tina-app
- Starter: Tailwind Starter

I got this errors from npm:

    Downloading files from repo tinacms/tina-cloud-starter. This might take a moment.
    Installing packages. This might take a couple of minutes.
    
    npm WARN ERESOLVE overriding peer dependency
    npm WARN While resolving: @udecode/zustood@0.4.0
    npm WARN Found: zustand@3.5.11
    npm WARN node_modules/@tinacms/toolkit/node_modules/@udecode/plate/node_modules/@udecode/plate-combobox/node_modules/zustand
    npm WARN   zustand@"3.5.11" from @udecode/plate-combobox@7.0.2
    npm WARN   node_modules/@tinacms/toolkit/node_modules/@udecode/plate/node_modules/@udecode/plate-combobox
    npm WARN     @udecode/plate-combobox@"7.0.2" from @udecode/plate@7.0.3
    npm WARN     node_modules/@tinacms/toolkit/node_modules/@udecode/plate
    npm WARN     2 more (@udecode/plate-mention, @udecode/plate-mention-ui)
    npm WARN
    npm WARN Could not resolve dependency:
    npm WARN peer zustand@"3.5.10" from @udecode/zustood@0.4.0
    npm WARN node_modules/@tinacms/toolkit/node_modules/@udecode/plate/node_modules/@udecode/plate-combobox/node_modules/@udecode/zustood
    npm WARN   @udecode/zustood@"0.4.0" from @udecode/plate-combobox@7.0.2
    npm WARN   node_modules/@tinacms/toolkit/node_modules/@udecode/plate/node_modules/@udecode/plate-combobox
    npm WARN
    npm WARN Conflicting peer dependency: zustand@3.5.10
    npm WARN node_modules/zustand
    npm WARN   peer zustand@"3.5.10" from @udecode/zustood@0.4.0
    npm WARN   node_modules/@tinacms/toolkit/node_modules/@udecode/plate/node_modules/@udecode/plate-combobox/node_modules/@udecode/zustood
    npm WARN     @udecode/zustood@"0.4.0" from @udecode/plate-combobox@7.0.2
    npm WARN     node_modules/@tinacms/toolkit/node_modules/@udecode/plate/node_modules/@udecode/plate-combobox
    npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
    npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
    npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
    npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
    npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
    npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
    npm WARN deprecated mdast@3.0.0: `mdast` was renamed to `remark`
    npm WARN deprecated subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`ps://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
    npm WARN deprecated axios@0.19.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
    npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
    npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cawdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
    
    added 1661 packages, and audited 1662 packages in 5m
    
I then just went to localhost:3000 as stated in the quickstart guide and it was working. But when I tried to go to the admin page, after login I got TinaEditProvider error.

### Expected result

I should see what the quickstart guide show and be ablw to use the admin panel

### Actual result
On localhost:3000/admin

    Unhandled Runtime Error
    Error: No `TinaEditProvider` found

    Call Stack
    Module.useEditState
    node_modules\@tinacms\toolkit\node_modules\@tinacms\sharedctx\dist\index.js (49:0)
    Nav
    node_modules\@tinacms\toolkit\dist\index.js (9005:22)
    renderWithHooks
    node_modules\react-dom\cjs\react-dom.development.js (14985:0)
    mountIndeterminateComponent
    node_modules\react-dom\cjs\react-dom.development.js (17811:0)
    beginWork
    node_modules\react-dom\cjs\react-dom.development.js (19049:0)
    HTMLUnknownElement.callCallback
    node_modules\react-dom\cjs\react-dom.development.js (3945:0)
    Object.invokeGuardedCallbackDev
    node_modules\react-dom\cjs\react-dom.development.js (3994:0)
    invokeGuardedCallback
    node_modules\react-dom\cjs\react-dom.development.js (4056:0)
    beginWork$1
    node_modules\react-dom\cjs\react-dom.development.js (23964:0)
    performUnitOfWork
    node_modules\react-dom\cjs\react-dom.development.js (22776:0)
    workLoopSync
    node_modules\react-dom\cjs\react-dom.development.js (22707:0)
    renderRootSync
    node_modules\react-dom\cjs\react-dom.development.js (22670:0)
    performSyncWorkOnRoot
    node_modules\react-dom\cjs\react-dom.development.js (22293:0)
    eval
    node_modules\react-dom\cjs\react-dom.development.js (11327:0)
    unstable_runWithPriority
    node_modules\scheduler\cjs\scheduler.development.js (468:0)
    runWithPriority$1
    node_modules\react-dom\cjs\react-dom.development.js (11276:0)
    flushSyncCallbackQueueImpl
    node_modules\react-dom\cjs\react-dom.development.js (11322:0)
    flushSyncCallbackQueue
    node_modules\react-dom\cjs\react-dom.development.js (11309:0)
    scheduleUpdateOnFiber
    node_modules\react-dom\cjs\react-dom.development.js (21893:0)
    dispatchAction
    node_modules\react-dom\cjs\react-dom.development.js (16139:0)
    eval
    node_modules\tinacms\dist\index.js (2754:0)

I tried to hit the refresh button but nothing changed.

#### Tinacms Package Versions

```
@tinacms/starter@0.1.0 D:\Documents\DEV\my-tina-app
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.9
├── next-tinacms-cloudinary@3.5.11
├── tinacms@0.66.9
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |    Brave browser  v 1.36.122 Chromium: 99.0.4844.88 (Official build) (64 bit)  |
| os      |     Windows  10 Pro 64bit 2004 19041.1415  |
| node    |    v16.13.0     |
| npm     |   8.1.0      |

**Comment by jamespohalloran** [comment]
I haven't seen any other similar reports so I assume this must have since been fixed! Closing, but let us know if you're still running into it on latest
