### ISSUE TITLE
Vulnerability in simple-git

### ISSUE THREAD

**Issue by 3lijah** [tinacms/tinacms#2759]
It looks like there's a vulnerability in simple-git: https://github.com/advisories/GHSA-3f95-r44v-8mrg

This is in the @tinacms/toolkit dependencies: https://github.com/tinacms/tinacms/blob/67f92b1ec54a33e2a5381184b6503b26f5337a57/packages/%40tinacms/toolkit/package.json#L113

**Comment by jamespohalloran** [comment]
I believe our usage around this is deprecated anyways. (I'm assuming it was used before Tina Cloud was introduced.) Could we remove this dependency (and git package) altogether @tinacms/maintainers?

**Comment by jamespohalloran** [comment]
Deprecated packages have been removed, fixing this vulnerability
