### ISSUE TITLE
Unable to login through Tina Cloud when branch name contains `/`.

### ISSUE THREAD

**Issue by mittonface** [tinacms/tinacms#2764]
## Description

Whenever you try to login to edit a site through Tina Cloud and you are pointing at a branch that contains a `/` (i.e., `feat/cool-feature`, the login process breaks.

The login screen pops up with this error.

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/5082908/161077233-8f022d5b-ce7f-4c63-9c3e-060d386850a2.png">

### Steps to reproduce

1. Deploy one of the starter projects.
2. Create a branch on that project that contains a `/` character.
3. Change the API url to point at that branch, push the project
4. Try to login to that project.

This is happening because the UrlPattern matcher in `tinacms/src/tina-cms.tsx` is treating anything after `/` in a branch name as another subdirectory. Maybe URL-escaping is the fix to this problem?
```
const pattern = new UrlPattern('/content/:clientId/github/:branch')
```

**Comment by mittonface** [comment]
It's worth mentioning that even if we fix this here it _could_ fail later down the line when it tries to call `content.tinajs.io/content/<clientId>/github/feat/cool-feat`

Maybe this can be fixed by URL escaping the slashes and always dealing with that.

**Comment by jamespohalloran** [comment]
We used to URIEncode the branch name: https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/client/index.ts#L142 (and I'm pretty sure this was also handled on the backend), but I'm wondering we're doing some requests outside of this? maybe?

**Comment by kldavis4** [comment]
Wildcarding the branch [here](https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/tina-cms.tsx#L174) should fix it (assuming URLPattern supports it).

**Comment by logan-anderson** [comment]
PR: https://github.com/tinacms/tinacms/pull/2843
