### ISSUE TITLE
Data layer: collections with more than 1000 items are not fully indexed

### ISSUE THREAD

**Issue by kldavis4** [tinacms/tinacms#2779]
## Description

If you are working in tina-cloud, the github bridge glob function will only return the first 1000 items in a directory due to limitations of the github rest api. This means that content will not be fully indexed.

### Steps to reproduce

Enable data layer on a site, add more than 1000 items. Add the site to tina-cloud and then attempt to query the collection. The items are ordered by filename and the items above 1000 will not be returned in the query.

### Expected result

All items should indexed

### Actual result

Only the first 1000 items are indexed

**Comment by gitsstewart** [comment]
With isomorphic git in place, this is no longer needed however makes a great test case!
