### ISSUE TITLE
`create-tina-app` should remove `yarn.lock`

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#2809]
When using `create-tina-app`, the Tina dependencies are switched to `latest` but the `yarn.lock` is copied over, so a dependency like `latest` has no effect https://github.com/tinacms/tina-barebones-starter/blob/main/yarn.lock.

#### Steps to reproduce

`npx create-tina-app@latest`

- Choose barebones starter 
- Choose yarn

`yarn.lock` will still be there, so you get an older version

**Comment by jamespohalloran** [comment]
Would this potentially cause issues when we introduce breaking changes?
