### ISSUE TITLE
createGlobalForm using the wrong type in the FormifyArgs interface 

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2812]
Currently in tinaCMS package we are using 

```
export interface FormifyArgs {
    formConfig: FormOptions<any>;
    createForm: FormCreator;
    createGlobalForm: FormCreator;
    skip?: () => void;
}
```

When we should be using:

```
export interface FormifyArgs {
    formConfig: FormOptions<any>;
    createForm: FormCreator;
    createGlobalForm: GlobalFormCreator;
    skip?: () => void;
}
```

This allows for layout overrides

**Comment by jamespohalloran** [comment]
Is this just a 1-liner, here?: https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/hooks/use-graphql-forms.tsx#L146

**Comment by perkinsjr** [comment]
> Is this just a 1-liner, here?: https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/hooks/use-graphql-forms.tsx#L146

Yup, that one liner fixes overrides
