### ISSUE TITLE
The `useTina` hook does not receive live data for nested reference fields

### ISSUE THREAD

**Issue by coreyaus** [tinacms/tinacms#2816]
## Description

Currently if you create a page that has a field of `type: "reference"`, any changes to the value selected in that field are not reflected in the data returned by the `useTina` hook. Put another way, live editing is completely broken for reference fields.

## Update

I have discovered that this is fixed by reverting to `tinacms@0.66.9`, so the issue described here only started to appear on `v0.66.10` of TinaCMS (and it persists on the latest version `0.67.0`). I've added other related issues with the latest version of the `tinacms` package here: #2817. Thanks for all your wonderful work team!

### Steps to reproduce

1. Create a repository with a schema along the lines of the example below
2. Inside of your `pages/index.tsx` or any other Tina-powered page, add a `console.log` statement to log the data returned by the `useTina` hook
3. Open your page in edit mode and make changes to the 3 fields in the sidebar
    - Note which fields trigger the `console.log` command. You will see the string and dropdown fields trigger that fine, but changes in the value of the reference field do NOT trigger the `console.log` statement 
    - Also, if you make a change to the reference field then change one of the other fields (to trigger the `console.log`), the data that gets output on the console will contain the original value for the reference field, not the updated value.

### Expected result

I would expect a change in the value selected in the reference field to trigger a change in the live data returned by the `useTina` hook, in order to update the visual elements associated with that change. For example, if I change the author of a page, the author bio display should update to show the information of the newly-selected author (i.e. to deliver the live editing experience).

### Actual result

At the moment the `useTina` hook does not return the latest data for reference fields, and it does not trigger updates when a change occurs in a reference field. This process does work as expected for dropdown fields.

### Example schema below

```typescript
import { defineSchema, defineConfig } from "tinacms";

export default defineSchema({
  collections: [
    {
      label: "Pages",
      name: "pages",
      path: "content/pages",
      fields: [
        {
          type: "string",
          name: "title",
          label: "Title",
        },
        {
          type: "reference",
          name: "backgroundColourReference",
          label: "Background colour reference field",
          collections: ["colours"],
        },
        {
          type: "string",
          name: "backgroundColourDropdown",
          label: "Background colour dropdown field",
          options: ["colour 1", "colour 2", "colour 3"],
        },
      ],
    },
    {
      label: "Colours",
      name: "colours",
      path: "content/colours",
      format: "json",
      fields: [
        {
          type: "string",
          name: "rgbColour",
          label: "Colour",
          ui: {
            component: "color",
            colorFormat: "rgb",
          },
        },
      ],
    },
  ],
});

const apiURL =
  process.env.NODE_ENV == "development"
    ? "http://localhost:4001/graphql"
    : `https://content.tinajs.io/content/${process.env.NEXT_PUBLIC_TINA_CLIENT_ID}/github/${process.env.NEXT_PUBLIC_EDIT_BRANCH}`;

export const tinaConfig = defineConfig({
  apiURL,
});
```

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.11
├── next-tinacms-cloudinary@3.5.13
├── tinacms@0.67.0
```

**Comment by coreyaus** [comment]
**Update:** I have discovered that this is fixed by reverting to `tinacms@0.66.9`, so the issue described here only started to appear on `v0.66.10` of TinaCMS (and it persists on the latest version `0.67.0`). I've added other related issues with the latest version of the `tinacms` package here: #2817. **Thanks for all your wonderful work team!**

**Comment by jamespohalloran** [comment]
Thanks for reporting this! I've just reproduced it on the Tina Cloud Starter (by upgrading to `"tinacms": "^0.67.0"`)

**Comment by coreyaus** [comment]
Hey @jamespohalloran - hope you had a top Easter break and thanks for the quick response on this one!

I'm using `@tinacms/cli@0.60.11` and seeing that issue if I try to upgrade to `tinacms@0.67.0`

Dropping the version of `tinacms` to `0.66.9` fixes the problem while still using `@tinacms/cli@0.60.11`. I could experiment with different versions of `@tinacms/cli` if useful but at this stage it seems something changed between `tinacms@0.66.9` and `tinacms@0.66.10` that causes this problem (as well as the other issues listed in #2817)

Massive thanks for looking into it, and apologies I'm not more across the internals of the package to try isolating the root cause in more detail!

**Comment by jeffsee55** [comment]
Hey @coreyaus 👋 

I was trying to reproduce this myself but haven't been able to, I've pushed up my code to this repo https://github.com/jeffsee55/reference-issue-debug if you can take a look and point me in the right direction to reproduce.

Thanks!

**Comment by coreyaus** [comment]
Thanks mate - I'm heading out of the office shortly but will take a look at this in the next week or two - hopefully it will already be resolved with the latest releases of tinacms but I'll keep you posted 👍 Thanks for your work on it so far!

**Comment by coreyaus** [comment]
Hey team,

I'm closing this issue as I've worked out what was happening, and it might not be a bug so sorry for the hassle! It's definitely a bit of a rough edge so I'll post my notes below in case they're useful:

1. The case where `reference` fields do NOT live-update via the `useTina` hook:
    - This happens if the GraphQL query simply uses the `PostParts` fragment (or equivalent `[collection_name]Parts` fragment) to access all the necessary data, without defining any inlineFragment on the particular `reference` field (e.g. no `... on Author` fragment or whatever the reference field is called).
        - In this case the data from `useTina` still returns the `id` value for the reference field - that was all I needed in my case, so I hadn't realised you need to explicitly include an extra inlineFragment in your query in order to get the live-updating behaviour for reference fields
        - If this is expected behaviour it might be helpful to document it somewhere - I found it a bit surprising and fairly hard to diagnose
    - As an example of this, you can see the live-updating does not work for the post author in the Tina tailwind starter repo after making this change: https://github.com/coreyaus/tinacms-issue-2816/commit/cd99486b792145e7decebc279a1f508f5a37d414

2. Fixing the issue is as simple as including an inline fragment for the `reference` collection
    - Using the Tina tailwind starter repo as the example, the live updating works with the following GraphQL (which is admittedly this version included by default):
        ```graphql
        query BlogPostQuery($relativePath: String!) {
          ...LayoutQueryFragment
          post(relativePath: $relativePath) {
            ...PostParts
            author {
              ... on Author {
                name
                avatar
              }
            }
          }
        }
        ```
    - However with the following GraphQL, the live updating does NOT occur when making changes in a post's author field:
        ```graphql
        query BlogPostQuery($relativePath: String!) {
          ...LayoutQueryFragment
          post(relativePath: $relativePath) {
            ...PostParts
          }
        }
        ```
    - For my specific use case I didn't need anything more than the `id` of my reference field, which is why I saw this issue originally as my query didn't include any inline fragments on the `reference` field I was using (the `id` field is included by default without adding an extra inlineFragment to the query, and that gave me everything I needed).

3. One note is that I haven't confirmed the behaviour if your `reference` field includes multiple collections, e.g. using something like `collections: ["author", "page"],` in the `schema.ts`
    - In that case I'm not sure whether you'd need to update your query to include an inline fragment on each collection mentioned in that `collections` array

Let me know if you have any questions about that, or if the underlying behaviour is worth reviewing/discussing in more detail at any point 👍 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/7799612/170194205-1a8d1f58-180a-4858-a1ca-614d867d2df4.png">

**Comment by jeffsee55** [comment]
Thanks for the detailed info, @coreyaus - this is due to the fact that that we don't update nodes unless the user has queried for actual fields on the given document. So for our experimental client we do references like this:

```graphql
query BlogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    title
    author {
      ...on Document {
        id
      }
    }
  }
}
```
But if you specify fields of any kind:

```graphql
query BlogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    title
    author {
      ...on Document {
        id
      }
      ...on Author {
        name
      }
    }
  }
}
```
Those should be picked up. We should fix that so all values are populated.

**Comment by logan-anderson** [comment]
@coreyaus is this still an issue?
