### ISSUE TITLE
Can not save with Hyphen in file name in CMS

### ISSUE THREAD

**Issue by git-no** [tinacms/tinacms#2818]
## Description

Can not save with Hyphen in file name. The hyphen is an allowed character but the SAVE button is disabled till no hyphen is in the filename.

### Steps to reproduce

1. Create the documentation template at Vercel.
2. Create a new documenation page with a hyphen in the file name and try to save via the save button.

### Expected result

Save button is not disabled when a hyphen is in the filename
Save button should be enabled to click, also with hyphen in the filename.

### Actual result

Save button is disabled when a hyphen is in the file name.

### Environment

Vercel, TinaCMS Documentation Template.

#### Tinacms Package Versions

```text
Latest on April 17. 2022
```

#### Tools

On Safari (15.4), MacOS 12.3.1, Tina Cloud

**Comment by jeffsee55** [comment]
@git-no what version are you on? This should be supported now.

**Comment by git-no** [comment]
I assume v0.43.1

**Comment by jamespohalloran** [comment]
Confirmed this is working for me on a later version:
├── @tinacms/cli@0.60.18
├── tinacms@0.68.6
