### ISSUE TITLE
Extra click needed to start editing MDX field

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2827]
## Description

When clicking into an MDX field (from another textarea field), I need to click into the MDX editor twice

https://www.loom.com/share/e549eb061b36499a9609487aa7a36ad1

### Steps to reproduce

- Create a local copy of the tina cloud starter, 
- Go to http://localhost:3000/posts/voteForPedro
- Click between "exerpt" & "body" fields

### Expected result

Should be able to start editing immediately

#### Tinacms Package Versions

├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.11
├── next-tinacms-cloudinary@3.5.11
├── tinacms@0.67.0

**Comment by llibdude** [comment]
I noticed in your loom that you try to click in the field, i find attempting to tab between certain fields doesn't work (might be related)
