### ISSUE TITLE
Any text inside a code block turns into markdown

### ISSUE THREAD

**Issue by Yash-Singh1** [tinacms/tinacms#2837]
## Description

If I type anything inside a code block in a rich text field, it turns into markdown. For example, writing `# a header` will create an `h1` inside the code block instead of simply rendering `# a header`

### Steps to reproduce

1. Create a code block
2. Write some markdown inside it (e.g. `# a header`)
3. Notice the markdown is interpreted as markdown instead of that language's text

### Expected result

It shouldn't render the code, it should simply consider it as code and syntax highlight it.

### Actual result

The code inside the code block was interpreted as markdown.

#### Tinacms Package Versions

```text
├── @tinacms/cli@0.60.12
└── tinacms@0.66.10
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  Chrome       |
| os      |  Ubuntu       |
| node    |  v16.13.0       |
| npm     |  8.1.0       |

#### Video

![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/53054099/164578301-8c1b809d-cd1c-4348-97c0-a2ab34a82d5b.gif)

**Comment by Yash-Singh1** [comment]
Don't close.

**Comment by jeffsee55** [comment]
This has been resolved in the latest release
