### ISSUE TITLE
Make the CMS sidebar collapsible by default via config when Tina loads

### ISSUE THREAD

**Issue by gitsstewart** [tinacms/tinacms#2845]
## Summary

As a user of Tina I want to have the CMS editor sidebar remain open by default, but with the option (via config) to override that behavior to closed so that I have more control over the state of the sidebar when Tina first loads.

### Expected Results
* The CMS sidebar is open by default when a page first loads
* When changing the config value to collapse it by default, then the CMS sidebar correctly is collapsed when the page loads
* The CMS sidebar can still be manually opened/collapsed by clicking on the pencil/collapse icons

### Notes
For example, we need to be able to change only the embedded example on [this page](https://tina.io/docs/features/data-fetching/) so that the sidebar loads collapsed for this one case.

**Comment by spbyrne** [comment]
Here's a PR for the ability to define the default open state: #2874 

This doesn't add the ability to persist sidebar state on refresh, I think that should be handled by another PR.

**Comment by spbyrne** [comment]
Here's a PR for Jeff's request: #2879
