### ISSUE TITLE
Unable to select items from dropdown menus in RichText UI

### ISSUE THREAD

**Issue by gopaljigaur** [tinacms/tinacms#2849]
## Description

Markdown elements don't get inserted in the Rich Text box when selected from dropdown menus. In the GIF below, you can see that I cannot insert Headings, Code Blocks, and Custom Templates, while I can easily add the quotation element.
 
![ezgif-5-581cc2769c](https://user-images.githubusercontent.com/30744909/165727622-a265fc60-5dd2-41e7-95b5-dee09829c9a5.gif)

### Steps to reproduce

- Create a NextJS blog
- Integrated TinaCMS into the existing project
- Create schema for the blog that includes RichText element
- Log in to Tina from the `/admin` page and open the blog page in edit mode
- Try to insert the Markdown elements in the RichText form from the drop-down menus.

### Expected result

When any Markdown element is selected in the RichText form, it should be readily inserted into the box.

### Actual result

Only elements with separate buttons are inserted into the form, not those available through dropdown menus.

#### Tinacms Package Versions

```text
﻿+-- @tinacms/cli@0.60.12
+-- tinacms@0.67.3
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Microsoft Edge Version 100.0.1185.39 (Official build) (64-bit) |
| os      | Windows 11 Version 21H2 OS Build 22000.613 |
| node    | v16.13.2 |
| npm     | 7.24.1 |

**Comment by jeffsee55** [comment]
Thanks @gopaljigaur, looks like this was introduced here https://github.com/tailwindlabs/headlessui/compare/@headlessui/react@v1.4.1...@headlessui/react@v1.4.2. Stop propagation. @gopaljigaur if you're not on React 18 and are using yarn you can add:

```
"resolutions": {
  "@headlessui/react": "1.4.1"
}
```
That should get around the issue for now.
