### ISSUE TITLE
ImageFieldPlugin uploadDir (and all other function) properties are mutated and destroyed

### ISSUE THREAD

**Issue by llibdude** [tinacms/tinacms#2850]
## Description/Steps to reproduce

I have followed the contributing guide here https://github.com/tinacms/tinacms/blob/main/CONTRIBUTING.md and am testing using the `tina-cloud-starter`.

I would like to change the upload directory of a specific image field in my schema to another folder in cloudinary.  According to the docs here https://tina.io/docs/reference/toolkit/fields/image/#definition it should be doable.

I added the `uploadDir` property to the image type to have it use the `samples` directory of my cloudinary account by default for uploading.  Here is the source i edited https://github.com/tinacms/tinacms/blob/main/experimental-examples/tina-cloud-starter/components/blocks/hero.tsx#L165

```javascript
{
      type: "object",
      label: "Image",
      name: "image",
      fields: [
        {
          name: "src",
          label: "Image Source",
          type: "image",
          uploadDir: () => {
            return "samples";
          },
        },
        {
          name: "alt",
          label: "Alt Text",
          type: "string",
        },
      ],
    },
```

If you make that change and run the tina-cloud-starter you will get the error
![image](https://user-images.githubusercontent.com/5255924/165830084-10848c2b-9993-4bc6-a58e-e34d704cf498.png)

Why?  I'm not sure what is going on under the hood (i dug around the source i have no clue whats going on), but when I go into the source code of the plugin here https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/packages/fields/plugins/ImageFieldPlugin.tsx#L100 and console out `props.field.outputDir` I get
![image](https://user-images.githubusercontent.com/5255924/165830274-2df62dbf-bee4-4bcb-92dd-bccbe6521c89.png)
The function no longer exists, it has been replaced by an array that is apparently the path to the field from the root.

### Expected result

That the `uploadDir` property of the image field is preserved and passed down to the media plugin so that it can be used.  This is independent of cloudinary, any media plugin written would suffer this issue.  The cloudinary plugin has bugs of it's own, but those are outside the scope of this issue.

`

**Comment by gitsstewart** [comment]
* We need to investigate this and determine if it is something that is broken or if it's a feature that is no longer supported

**Comment by logan-anderson** [comment]
Going to close this for now. If you are still running into issue please reach out on discord or re-open this issue.
