### ISSUE TITLE
Add offset-based pagination to GraphQL client

### ISSUE THREAD

**Issue by Enigmatical** [tinacms/tinacms#2859]
## Overview
Our pagination solution seems to be at odds with SSG.  SSG expects a collection with a finite number of documents (specifically when using `getStaticPaths`) whereas our current solution (cursor-based pagination) allows for an infinite, constantly evolving number of documents.

While we can continue to offer cursor-based pagination for those that want it (as it does adhere to the Relay spec), we should also offer `offset` and `limit` for more traditional pagination needs - a set of pages across the bottom of a list, jump to a specific page, etc.

This could include adding `limit` and `offset` to the `<collection>Connection` props (exclusive, like how `after` & `first` and `before` & `last` are exclusive).  I'm not sure `pageInfo` would need to be changed (obliviously, we wouldn't need `endCursor`, `hasNextPage` or `hasPreviousPage`).

## Reason

I wanted to recreate a pretty common pagination route in one of our starters:

`/articles/page/2`, `/articles/page/3`, etc.

### Create the dynamic page

I knew I needed to create a dynamic route, so I added `pages/articles/page/[page].tsx`:

```tsx
import { ExperimentalGetTinaClient } from "../../../.tina/__generated__/types";
import Articles from "../index";

export default function ArticlesPage(props) {
  return <Articles {...props} />;
}

export const getStaticPaths = async () => { ... };

export const getStaticProps = async (ctx) => { ... };
```

### Provide `paths` to `getStaticPaths`

From there, I needed to provide `getStaticPaths`:

```tsx
export const getStaticPaths = async () => {
  const client = ExperimentalGetTinaClient();
  // Returns only `totalCount` for all documents in the `articles` collection
  const response = await client.getArticleTotal();

  // Using some simple math, determine how many total pages I'll need (assuming each page has 10 articles)
  let totalPages = Math.floor(response.data.articleConnection.totalCount / 10);
  const addPage = response.data.articleConnection.totalCount % 10;

  if (addPage > 0) {
    totalPages = totalPages + 1;
  }

  // Build `paths` based on total number of pages needed
  const paths = [];
  for (let i = 1; i <= totalPages; i++) {
    paths.push({
      params: { page: `${i}` },
    });
  }

  return {
    paths,
    fallback: "blocking",
  };
};
```

With this in place, I have access to `/articles/pages/1`, `/articles/pages/2`, on and on, as needed.
However, the trouble comes when converting a simple page number into an `endCursor`.

### Determine `endCursor` in `getStaticProps`

I had a hint that our `endCursor`s are derived from `Document.id` (basically just base64 encoded).  I needed to figure out which article was the first article of the desired `page` and derive the `endCursor` from that.

```tsx
export const getStaticProps = async (ctx) => {
  const page = ctx.params.page;
  const client = ExperimentalGetTinaClient();

   // Get a list of every article id (I set `first` to `99999` to avoid issues with built-in set size limitations)
   const idResponse = await client.getArticleIds();
   const ids = idResponse.data.articleConnection.edges.map(
     ({ node }) => node.id
   );

   // Determine the first article of the desired page (in this example, 2 - 1 = 1 * 10 = 10 + 1 = 11th article)
   const pageToId = ids[((page - 1) * 10) + 1];
   const endCursor = Buffer.from(pageToId).toString("base64");

   const response = await client.getArticles({
     after: endCursor,
  });

  return {
    props: {
      ...response,
    },
  };
};
```

Regretfully, it was here that I discovered that `endCursor` is not _just_ the `base64`-encoding of `node.id`, but appears to be based on `key` in the `Store`: 
https://github.com/tinacms/tinacms/blob/main/packages/@tinacms/datalayer/src/database/store/level.ts#L148

I then tried a different approach:  Utilizing a `promise` recursion pattern to "flip" through the pages, using the `endCursor` of the previous request in the next until I arrived at my desired page.

```tsx
export const getStaticProps = async (ctx) => {
  const page = ctx.params.page;
  const client = ExperimentalGetTinaClient();
  
  // Keeps track of the pages I've flipped through
  let count = 0;
  const fetchArticles = async (endCursor) => {
    const response = await client.getArticles({ after: endCursor });
    count = count + 1;

    if (count < page) {
      // Use the endCursor for the previous request for the next one
      return fetchArticles(response.data.articleConnection.pageInfo.endCursor);
    } else {
      return response;
    }
  };

  const response = await fetchArticles("");

  return {
    props: {
      ...response,
    },
  };
};
```
Obliviously, this is not ideal at all (if I wanted to view page 50, I would need 49 other requests).

### What if `offset` and `limit` existed?

With `offset` and `limit` all of this becomes fairly trivial.

`getStaticPaths` remains the same - using the total document count to determine the number of pages.

```tsx
export const getStaticPaths = async () => {
  const client = ExperimentalGetTinaClient();
  const response = await client.getArticleTotal();

  let totalPages = Math.floor(response.data.articleConnection.totalCount / 10);
  const addPage = response.data.articleConnection.totalCount % 10;

  if (addPage > 0) {
    totalPages = totalPages + 1;
  }

  const paths = [];
  for (let i = 1; i <= totalPages; i++) {
    paths.push({
      params: { page: `${i}` },
    });
  }

  return {
    paths,
    fallback: "blocking",
  };
}
```

`getStaticProps` becomes much simpler, only needing to determine `offset` from the `page`.  `limit` would need to be consistent between the `query` and here.

```tsx
export const getStaticProps = async (ctx) => {
  const client = ExperimentalGetTinaClient();
  
  const page = ctx.params.page;
  const offset = page * 10
  
  const response = client.getArticles({
    offset,
    limit: 10,
  })

  return {
    props: {
      ...response,
    }
  }
}
```

**Comment by kldavis4** [comment]
I don't think cursor based pagination should be a problem for SSG except for this [issue](https://github.com/vercel/next.js/discussions/11272). The recommended workaround appears to be leveraging a filesystem cache. I believe the way this would work is in getStaticPaths you can track page # and associated cursors and write that info to your cache. Then in getStaticProps you lookup the cursor based on the page and retrieve the article content to be rendered.

**Comment by Enigmatical** [comment]
In our conversation during Office Hours on Friday, we discussed that, while some of our competitors offer cursor-based pagination solutions, _all_ of them offer offset/index-based solutions.

Offering both sounds like the ideal approach.

**Comment by kldavis4** [comment]
I just watched the office hours so I'm caught up on that conversation. The issue here is not primarily about the graphql interface (relay vs non-relay pagination). The issue is that we made a choice to go with a key-value store for the data layer and one of the limitations of that is you can't query using a numeric offset/skip. We could hack our way to a solution by doing something like performing the skip on the backend, but for large collections that's going to get progressively slower. If offset/skip is a hard requirement, then a key-value store isn't really the right solution for data layer.

I still think cursors aren't really a problem for SSG, so you can grab your entire collection at build time. I am more concerned about ISR being an issue, which I thought is what smashing needed due to the large number of articles.

**Comment by kldavis4** [comment]
just a small update on this - I've been thinking about the tradeoffs for this, and I think it may be ok to do a offset -> cursor translation on the backend, given that most users don't actually click on the higher number pages. So if offset / limit is specified instead of the relay spec, the backend would first make some queries to find just the cursor, and then make a final query using that cursor to return the results. This is going to be slower for higher pages, but even in a relational database this is going to be the case.

I think actually the bigger issue might be determining the total number of pages, when rendering the pagination control for a specific page. The only way to get this count is to do actually query all the items (of interest). For a large site, it would probably better to do a pseudo pagination control, where it renders buttons for the next couple pages, but not every page.

**Comment by konsumer** [comment]
It's a glaring issue in contrast with relay, which [has this](https://graphql.org/learn/pagination/). As it is I see no way to paginate with only the number, and passing cursors in the URL or something is not an option for me, other than loading every record and slicing it.

**Comment by kldavis4** [comment]
> It's a glaring issue in contrast with relay, which [has this](https://graphql.org/learn/pagination/). As it is I see no way to paginate with only the number, and passing cursors in the URL or something is not an option for me, other than loading every record and slicing it.

Can you clarify what the contrast with relay is? The relay based pagination is a type of cursor based pagination and our graphql implementation tries to adhere to it

**Comment by konsumer** [comment]
@kldavis4 you know, I think you are right. I could have sworn I saw `offset` on that page I linked, but I think I was mistaken, or it changed. I ended up faking it like this:

```js
const ALL_BLOG_CURSORS = `
query ALL_BLOG_CURSORS {
  blogConnection(last: -1 ) {
    edges {
      cursor
    }
  }
}
`

const GET_BLOG_PAGE = `
query GET_BLOG_PAGE($cursor: String!, $len: Float!) {
  blogConnection(last: $len, after: $cursor, sort: "date") {
    edges {
      node {
        title
        slug
        date
        body
        description
      }
    }
  }
}
`

// get a list of all blog-post cursors (for paging)
export const getBlogAllCursors = pMemoize(async () => {
  const { data } = await client.request({ query: ALL_BLOG_CURSORS, variables: {} })
  return data.blogConnection.edges.map(e => e.cursor)
})

// get a single page of blog-posts, by number
// TODO: filter by category
export const getBlogPageList = pMemoize(async (currentPage = 1, categoryID) => {
  const cursors = await getBlogAllCursors()
  const pageCount = Math.ceil((cursors.length - 1) / 12) + 1

  const len = (currentPage === 1 ? 13 : 12)
  let start = (currentPage - 1) * 12

  if (currentPage !== 1) {
    start = start + 1
  }

  const { data } = await client.request({ query: GET_BLOG_PAGE, variables: { len, cursor: cursors[start] } })

  return {
    pageCount,
    currentPage,
    data
  }
})
```

**Comment by konsumer** [comment]
@kldavis4 actually, [I found what I saw](https://graphql.org/learn/pagination/#pagination-and-edges)

Basically they are making an example of how one might choose to do pagination, but say this:

> In general, we've found that cursor-based pagination is the most powerful of those designed. Especially if the cursors are opaque, either offset or ID-based pagination can be implemented using cursor-based pagination (by making the cursor the offset or the ID), and using cursors gives additional flexibility if the pagination model changes in the future. As a reminder that the cursors are opaque and that their format should not be relied upon, we suggest base64 encoding them.

So essentially they are saying "you can do `offset` on your own" which is what I did.
