### ISSUE TITLE
Show a "disconnected" indicator when gatsby server stops

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#286]
## Summary

Show a "disconnected" indicator when Gatsby server becomes unresponsive. If the Gatsby server crashes for whatever reason, there's often a few seconds of "Why won't this field save?" before realizing that the Gatsby server is no longer running. The save button should also be disabled when this occurs.

**Comment by mitchmac** [comment]
Going to close this because this Gatsby approach is no longer recommended.
