### ISSUE TITLE
TinaCMS GraphQL error after updating to latest version

### ISSUE THREAD

**Issue by gopaljigaur** [tinacms/tinacms#2860]
## Description

When a page is opened in browser for contextual editing, NextJS throws Runtime errors which might be related to the newest update to GraphQL.

![image](https://user-images.githubusercontent.com/30744909/166060806-d90559c2-7cb7-42bd-9df1-babbd52288f3.png)
![image](https://user-images.githubusercontent.com/30744909/166060845-c1219943-2b37-488a-aa7d-9286d43f3095.png)

I had made the relevant changes mentioned here - #2846 before starting the development server.

### Steps to reproduce

- Update Tina to latest version
- Make changes to `schema.ts` and GraphQL queries according to the latest suggestions in #2846
- Open any page for contextual editing

### Expected result

The page should open up with TinaCMS sidebar without any Runtime errors.

### Actual result

- Runtime errors shown on webpage
- Following error received in console:
```
[
  GraphQLError [Object]: Cannot query field "getCollections" on type "Query". Did you mean "collections" or "collection"?
      at Object.Field (D:\project\node_modules\graphql\validation\rules\FieldsOnCorrectTypeRule.js:48:31)
      at Object.enter (D:\project\node_modules\graphql\language\visitor.js:323:29)
      at Object.enter (D:\project\node_modules\graphql\utilities\TypeInfo.js:370:25)
      at visit (D:\project\node_modules\graphql\language\visitor.js:243:26)
      at validate (D:\project\node_modules\graphql\validation\validate.js:69:24)
      at graphqlImpl (D:\project\node_modules\graphql\graphql.js:99:49)
      at D:\project\node_modules\graphql\graphql.js:28:31
      at new Promise (<anonymous>)
      at graphql (D:\project\node_modules\graphql\graphql.js:26:10)
      at Object.resolve (D:\project\node_modules\@tinacms\graphql\dist\index.js:22953:51) {
    locations: [ [Object] ]
  }
]
```
#### Tinacms Package Versions

```text
+-- @tinacms/cli@0.60.15
+-- tinacms@0.67.4
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  Microsoft Edge Version 101.0.1210.32 (Official build) (64-bit)       |
| os      | Windows 11 Version 21H2 (OS Build 22000.652)        |
| node    |   v16.13.2      |
| npm     |  7.24.1       |

**Comment by jeffsee55** [comment]
@gopaljigaur it looks like that's coming from our internal usage of `getCollections`, which is updated in `tinacms@0.68`. Can you give that update a shot and report back?

**Comment by gopaljigaur** [comment]
@jeffsee55 Thanks. I upgraded to latest tinacms version `tinacms@0.68.2` and the problem disappeared.
I realized that `yarn upgrade tinacms` was not automatically pulling the latest version. I had to manually specify the latest version and add it to the dependencies using `yarn add tinacms@0.68.2`.
