### ISSUE TITLE
add Debugging

### ISSUE THREAD

**Issue by scil** [tinacms/tinacms#2875]
## Summary

nextjs can be debugged using env var `NODE_OPTIONS=--inspect `, for example, with `dotenv-cli`,  `dotenv  -v NODE_OPTIONS=--inspect  --  next dev`

right now  debugging can not work with tina.   
Both of  
` tinacms server:start -c \" dotenv  -e .env.development  -v NODE_OPTIONS=--inspect'  --  next dev\"`  
and    
`tinacms server:start -c \" set NODE_OPTIONS=--inspect  &&  next dev\"" `   on windows  
produce error    
```
Compilation failed with errors. Server has not been restarted. see error below
 The argument 'file' cannot be empty. Received ''
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at new NodeError (node:internal/errors:371:5)
    at normalizeSpawnArguments (node:child_process:508:11)
    at Proxy.spawn (node:child_process:693:13)
    at startSubprocess (D:\vagrant\www\zc-tina\node_modules\@tinacms\cli\dist\index.js:1567:47)
    at FSWatcher.<anonymous> (D:\vagrant\www\zc-tina\node_modules\@tinacms\cli\dist\index.js:1622:9) {
  code: 'ERR_INVALID_ARG_VALUE'
}
```

### Ref

https://nextjs.org/docs/advanced-features/debugging

**Comment by scil** [comment]
> @scil in dev mode, as a temporary fix you could run `tinacms server:start` and `dotenv -e .env.development -v NODE_OPTIONS=--inspect' -- next dev\` in two separate processes (two separate terminals would work).

Thank you.  Now I use `npm install npm-run-all dotenv-cli  -D `   and  `npm run debug`

```
  "scripts": {
    "debug": "run-p debug-1 debug-2 ",
    "debug-1": "tinacms server:start ",
    "debug-2": "dotenv  -e .env.development  -v NODE_OPTIONS=--inspect  --  next dev",
   ...
  },
```

**Comment by jamespohalloran** [comment]
Closing this as it has a reasonable workaround
