### ISSUE TITLE
Difficult to debug invalid MD for a file in a collection

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2880]
## Description

When there is an error in a collection's file, it's difficult to debug which file has the issue

https://www.loom.com/share/30bd09e574aa489e8264a824f0299767

### Steps to reproduce

Add "invalid" content to a`.md` file in a collection. E.g:

```md
{{ WarningCallout text="" }}
```

Make sure the body is set up with the rich-text field

```
{
        type: "rich-text",
        name: "body",
        label: "body",
        isBody: true,
}
```

Try and navigate to that collection in the CMS (or run `yarn run tinacms audit`)

### Expected result

- The file(s) that is causing the issue should be included in the error message
- If possible, improve the error message as well
- Add error to console
- Add error to cms alerts

### Actual result

Ambiguous error is logged, without knowing which file is causing the issue.

#### Tinacms Package Versions

├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.15
├── @tinacms/graphql@0.60.0
├── next-tinacms-cloudinary@3.5.12
├── react-tinacms-editor@0.53.9
├── tinacms@0.68.3

**Comment by logan-anderson** [comment]
@jamespohalloran 

Would this be a better error message?

```
error in fetching content/posts/anotherPost.mdx
error in querying posts
[
  GraphQLError [Object]: Could not parse expression with acorn: Unexpected token
      at locatedError (/Users/logananderson-forestry-mac/dev/tinacms/tinacms/.yarn/cache/graphql-npm-15.5.1-13daad554e-509cdc2fc0.zip/node_modules/graphql/error/locatedError.js:29:10)
      at /Users/logananderson-forestry-mac/dev/tinacms/tinacms/.yarn/cache/graphql-npm-15.5.1-13daad554e-509cdc2fc0.zip/node_modules/graphql/execution/execute.js:479:52
      at async Promise.all (index 4)
      at async Promise.all (index 0)
      at async Object.resolve (/Users/logananderson-forestry-mac/dev/tinacms/tinacms/.yarn/$$virtual/@tinacms-graphql-virtual-5c3d4447ac/1/packages/@tinacms/graphql/dist/index.js:23016:17)
      at async /Users/logananderson-forestry-mac/dev/tinacms/tinacms/packages/@tinacms/cli/dist/index.js:308:24 {
    locations: [ [Object] ],
    path: [ 'collection', 'documents' ]
  }
]
```

**Comment by jamespohalloran** [comment]
> Would this be a better error message?

Yes! Just having the filename (and collection) goes a long way
