### ISSUE TITLE
React Key Error in `fields/plugins/BlocksFieldPlugin/BlockSelectorBig.tsx in @tinacms/toolkit`

### ISSUE THREAD

**Issue by skyfriends** [tinacms/tinacms#2896]
## Description

There is a React key error on line 168 in this component

### Steps to reproduce

Run the editor in contextual editing mode, open console

### Expected result

It shouldn't be there

### Actual result

It is there (I tried to open a PR, but I kept getting a 403, even after following the guide in CONTRIBUTING)

**Comment by jamespohalloran** [comment]
Hey @skyfriends, thanks for reporting. What's the actual behavior that you're seeing from this issue?
Just a performance impact from the re-render? Or are you seeing an actual error?

**Comment by skyfriends** [comment]
Just the performance impact.  Apologies on the delayed response.
