### ISSUE TITLE
Can't name root level field "id"

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2898]
## Description

When modelling your content, if you have a root-level field named id, you get:

> Compilation failed with errors. Server has not been restarted. see error below 
 Field "Post.id" can only be defined once.
 
 ^(Where Post is the name of my collection)
 
I think the easy answer is "Don't use id as a field name", however if someone is migrating content to Tina, it could be annoying to have to update all of their existing content just to test out Tina. 

### Steps to reproduce

Add `{ type: "string", label: "Id", name: "id" }` as a root level field to a collection.
Run the graphql server locally

### Expected result

Ideally, should be able to use "id" as a field name, since all of the system-level fields are stored in _sys

#### Tinacms Package Versions

├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.15
├── @tinacms/graphql@0.60.0
├── next-tinacms-cloudinary@3.5.12
├── react-tinacms-editor@0.53.9
├── tinacms@0.68.2

**Comment by johtso** [comment]
Oh no.. this is not what I wanted to read today! Currently migrating from forestry and this is going to be a major pain to work around..
