### ISSUE TITLE
Tina should clear auth state if logged out of tina cloud

### ISSUE THREAD

**Issue by kldavis4** [tinacms/tinacms#2900]
## Summary

As a tina editor I want to be reauthenticated to tina cloud when I am logged out of tina cloud so that I don't get confusing errors

### Expected Results

If I authenticate to tina cloud on my site, and then log out separately from tina cloud, then next time I edit my site, it should ask me to login again

### Notes

I think currently the best solution for handling this is to clear cookies on my site

**Comment by jamespohalloran** [comment]
Just trying to get a clear idea of how frequently this happens. 

What do you mean by:

> , and then log out separately from tina cloud

**Comment by kldavis4** [comment]
I mean open app.tina.io in a separate browser tab and log out
