### ISSUE TITLE
Error running tinacms in Docker: "esbuild-linux-64" could not be found

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#2906]
A user reported an issue in [Intercom](https://app.intercom.com/a/apps/lu8gsps6/inbox/inbox/1527467/conversations/189572000013048), when they run `tinacms server:start -c "next dev"` in a Docker environment, they get a BuildSchemaError:

![error](https://user-images.githubusercontent.com/3323181/168598393-51a7b5bd-0074-45cc-8e7c-2dfa5996e6d7.png)

## Description

(It looks like this may have been fixed on Vite's end, so it may just be a matter of upgrading vite)

### Steps to reproduce

- Setup Docker, on a Windows machine
- Run `tinacms server:start -c "next dev"`

### Actual result

See error above

#### Tinacms Package Versions

```text
"tinacms": "^0.68.0"
"@tinacms/cli": "^0.60.14"
```

#### Tools

| Tool    | Version |
Windows
Docker

**Comment by skyfriends** [comment]
This is an environment mismatch issue.  I've encountered this before when working locally on mac and deploying to a linux box.  Maybe try regenerating your lockfile?

**Comment by charles-brainbox** [comment]
Hi, has anybody been able to solve this issue?

**Comment by kldavis4** [comment]
> Hi, has anybody been able to solve this issue?

can you provide a Dockerfile that replicates the issue?
