### ISSUE TITLE
Forms with many fields take too long to render

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#292]
## Description

If a form is loaded up with many fields, when the user navigates to the page where the form is rendered the form view is left blank until the form renders, which can take a few seconds.

### Steps to reproduce

Load up a form with lots of fields. Open the sidebar on a page where that form should render.

### Expected result

The form should slide in or a loading indicator should let the user know something is happening. 

### Actual result

The sidebar goes blank white for a while.

### Environment

MacOS Mojave / Chrome Version 77.0.3865.90

**Comment by ncphillips** [comment]
Closing because it seems to be fixed
