### ISSUE TITLE
Configurable git commit message

### ISSUE THREAD

**Issue by jonlambert** [tinacms/tinacms#2936]
## Summary

As a developer or content creator, I want to be able to see who saved changes to the CMS in the git history, so that I can audit and identify changes more easily.

### Expected Results

Currently, commit messages are all the same: `Update from GraphQL client`. 

IMO, identifying which user made the commit is essential to have in order to scale a site backed by TinaCMS. This by itself would be a required feature for us to adopt this tool. 

Building on top of that, though, it would be really handy to be able to customise the commit message in the project configuration section of Tina Cloud, perhaps with tokens. For example: `Content update from {{author}}`.

**Comment by rfrowe** [comment]
I think this is a very important and good idea. We should be able to set the git author information given the GitHub auth information for the editor in question. What I really want to see is a commit message like `Update foo/bar/baz.mdx` or even a text box in which one can type their own commit message (perhaps with the aforementioned message as a default).

**Comment by darenmalfait** [comment]
Very much this. The commit message is not even accurate from a repo perspective. It's a file that is being updated.

`chore({{collection}}): update content `

Something like that would be nice.
