### ISSUE TITLE
If there are two collections with names that start the same, the second collection in the admin will always query the first

### ISSUE THREAD

**Issue by llibdude** [tinacms/tinacms#2947]
## Description
If I have two collections named `test` and `test2`, when I go to edit a document from the `test2` collection via "Edit in Tina Admin" button , the underlying graphql will actually query the `test` collection and the correct data will not be fetched.

### Steps to reproduce
Here is a sample schema:
```
const schema = defineSchema({
  collections: [
    {
      label: 'Test',
      name: 'test',
      path: 'content/test',
      format: 'mdx',
      fields: [
        {
          label: 'field',
          type: 'string',
          name: 'field'
        }
      ]
    },
    {
      label: 'Test2',
      name: 'test2',
      path: 'content/test2',
      format: 'mdx',
      fields: [
        {
          label: 'field',
          type: 'string',
          name: 'field'
        }
      ]
    }
  ]
})
```

- Create a document for `test`, then create a document for `test2`.  Attempt to edit the document made for `test2` via the "Edit in Admin" option.
- For me, when opening the network tab the graphql query was attempting to fetch data for document `test`

I dont have time to make an example but if this isnt reproducible I can attempt to.  Note, I am currently on an older version of Tina than latest.

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.12
├── @tinacms/toolkit@0.56.22
├── next-tinacms-cloudinary@3.5.13
├── tinacms@0.67.3
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |     16.4.2    |
| npm     |   8.5.0      |

**Comment by jamespohalloran** [comment]
Yeah this is an odd one. The Content API seems to be giving the wrong relativePath & breadcrumbs for these collections
<img width="1311" alt="Screen Shot 2022-08-31 at 4 41 57 PM" src="https://user-images.githubusercontent.com/3323181/187768080-d217cbd7-9402-4860-abdf-d8d48c4354db.png">
