### ISSUE TITLE
Grammarly support for Tina Rich Text field

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#2963]
When using Grammarly, it appears that I can fix spelling issues but the text does not change. 

https://www.loom.com/share/dbf95c92e7224ecd85d0acde48891c04

I thought this worked in the past, but perhaps it was only supported by other Tina fields.

**Comment by selenecodes** [comment]
Having the same issue, is there any update for this?

**Comment by scottgallant** [comment]
> Having the same issue, is there any update for this?

Nothing as far as I'm aware.
