### ISSUE TITLE
Create a better way to import Experimental client for both javascript and typescript projects

### ISSUE THREAD

**Issue by perkinsjr** [tinacms/tinacms#2966]
We should look at a way to generate a file for both systems so that users that aren't using typescript don't run into an error like:

```javascript
Module not found: Can't resolve '../../.tina/__generated__/types'
  2 | import { Layout } from "../../components/Layout";
  3 | import { useTina } from "tinacms/dist/edit-state";
> 4 | import {ExperimentalGetTinaClient} from "../../.tina/__generated__/types";
```
This is because in javascript we have to import with the .ts at the end.
`import {ExperimentalGetTinaClient} from "../../.tina/__generated__/types.ts";`

We could separate the client into its own file for example `client.js` and `client.ts` and then a user can import both the same way without having to include the extension.

**Comment by perkinsjr** [comment]
One thing I noticed yesterday, when using javascript:

Autocomplete doesn't work when imported as `import {ExperimentalGetTinaClient} from "../../.tina/__generated__/types.ts";` but does when imported as `import {ExperimentalGetTinaClient} from "../../.tina/__generated__/types`

Then you can't compile or test without adding `.ts`

**Comment by jamespohalloran** [comment]
This is smoother with the new `client.queries`. See barebones starter for an example:
https://github.com/tinacms/tina-barebones-starter
