### ISSUE TITLE
Repo-Based Media: Support `config` in `localhost` endpoints

### ISSUE THREAD

**Issue by Enigmatical** [tinacms/tinacms#2973]
With this PR (https://github.com/tinacms/tinacms/pull/2971), we introduced `schema.config.media.tina` to determine public and upload paths.  We'll need to make sure our local endpoints recognize and use them.

**Comment by Enigmatical** [comment]
I made this "3 points," factoring in the work we already did:
https://github.com/tinacms/tinacms/pull/2971

I'll let @logan-anderson decide if that is fair or if this needs to be higher 👍

**Comment by logan-anderson** [comment]
3 seems good. I found a bug (linked in the PR) if we want to fix that bug in this work it probably jumps to a 5-8
