### ISSUE TITLE
Support {global: true} in collections

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#2990]
## Summary

As a Tina dev I want to add a global form so that my editors can edit global content

## How it looks to the user

In the schema add  global true. 
```ts
const schema = defineSchema({
    collections: [
      {
       name: "posts",
       label: "Blog Posts",
       path: "content/posts",
       format: "mdx",
       global: true,
       fields: [
        // An array of fields
       ],
      },
    ]
}) 

// ...

export default schema
```

After adding this it will show up as a global form.

### Expected Results
- impletment feature as describe above
- add to reference docs page
- update and add tests

**Comment by jamespohalloran** [comment]
To zoom out a bit, what makes a global form special? 
At a high-level, I feel like it's a form that is editable from mostly anywhere on the site.
Could a user accomplish the same thing by setting up useTina at the layout level?

**Comment by jamespohalloran** [comment]
Curious if you have thoughts on this one @spbyrne. Having a global:true would help us avoid some ugly cmsCallback usages, but global forms in general might be something you're planning on looking at for your UI mockups.
