### ISSUE TITLE
Z-index issue with drop down menu for MDX components 

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#2994]
MDX components hide the menu when multiple components are close to each other. 

![Mx6lxG1IpI](https://user-images.githubusercontent.com/776019/174199420-4431c595-91fb-4bc2-8466-255bdace01bb.gif)

**Comment by asharonbaltazar** [comment]
Hey, all. I'm aware this issue is somewhat old, but I'd like to take a shot at fixing this. Also, that'll help me get acquainted with the codebase.

**Comment by asharonbaltazar** [comment]
Seems like it's been fixed?

<img width="454" alt="Screenshot 2022-12-14 at 10 20 12 AM" src="https://user-images.githubusercontent.com/58940073/207635555-29372588-47a5-4c6d-b6dc-49524c2c23f0.png">
