### ISSUE TITLE
CLI looks for _app in wrong path when using init command

### ISSUE THREAD

**Issue by jaisbajwa** [tinacms/tinacms#3006]
## Description

Searched for this issue but didn't see any similar atm. I have an existing Next.js app and when I run `npx @tinacms/cli@latest init`, it fails with an error specifying _app.js does not exist.

Full error: ENOENT: no such file or directory, open `/<directory-path>/src/pages/_app.js`

I have the _app.js file in `<directory-path>/pages/_app.js` and not in the `<directory-path>/src/pages/` directory. I checked the Tina starter templates and they all do not have an src directory. Is there an additional argument I need to provide to the CLI so that it looks in the default directory instead of src?

### Steps to reproduce

1. Create a Nextjs project by running `npx create-next-app@latest --ts`. Note: you could skip `--ts` if you need JS. I have tried both _app.ts and app.js.
2. Run `npx @tinacms/cli@latest init`

### Expected result

TinaCMS should initialize itself and detect _app.js file in `<project-directory>/pages/_app.js`.

### Actual result

```
Checking dependencies. ✅
Installing Tina packages. This might take a moment... ✅
(node:21976) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Adding _app.js ... ✅
Error: ENOENT: no such file or directory, open '/<directory-path>/src/pages/_app.js'
```

#### Tinacms Package Versions

```text
├── @tinacms/cli@0.60.23
├── tinacms@0.68.9
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| os      |    macOS 12.13     |
| node    |     v16.14.2    |
| npm     |     8.5.0    |

**Comment by jaisbajwa** [comment]
@jamespohalloran Thanks for checking and yes, that sounds like the root cause. I do have an `src` directory in my project that contains `src/components`, `src/layouts`, etc. However, the pages directory is still in the root directory.
I'll rename my src directory temporarily and then run the CLI. Renaming it back to src could be a workaround for now.

**Comment by DmacMcgreg** [comment]
Also getting this error.
Came after I initialized a next.js project using blitzjs
_app.tsx exists in this case. 
Brand new project using the blitz cli and tina cli
