### ISSUE TITLE
Use of GraphQL Fragments and reusable Object Templates and Components across Blocks

### ISSUE THREAD

**Issue by brvnonascimento** [tinacms/tinacms#3021]
## Summary

As a Developer I want to be able to reuse more atom-level React Components across Tina Blocks and define GraphQL Fragments so that I can query them from within the Tina Block GraphQL Fragment without being tied to a parent Collection or need a reference.

### Expected Results

```graphql
fragment HeroBlockProps on HeroBlock {
  headline
  text
}
```

Currently is always tied to the parent Collection (Page, in this case): 

```graphql
fragment HeroBlockProps on PageBlocksHero {
  headline
  text
}
```

However, we might not want a Template available at the top level of the Page, for example a Link component would be used inside other Blocks and have a Fragment as in:

```graphql
fragment LinkProps on Link {
  text
  internalRouteReference
  externalUrl
}
```

and then could be queried as in: 

```graphql
fragment CtaSection on CtaSectionBlock {
  text
  variant
  colorScheme
  link {
    # This would be an Union type of Link and CtaSectionLink
    ...LinkProps
  }
}
```

My thought was that defining `templates` globally on the `defineSchema` would solve this issue but no GraphQL Types are generated from doing that:

```typescript
const schema = defineSchema({
  templates: [heroTemplate, linkTemplate],
  collections: []
})
```

### Notes

This is to create reusable Fragments which should be used on more atomic components that are not necessarily exposed at the top level of the Block List field on the Page (or any parent Collection).

**Comment by logan-anderson** [comment]
@brvnonascimento I like this idea. We currently do this for each collection so you can write queries [like this](https://github.com/tinacms/tina-cloud-starter/blob/main/.tina/queries/queries.gql#L24) what would be the use case for doing this at the block level?

Sorry for the delayed response.

**Comment by brvnonascimento** [comment]
At the Block level we can reuse "atoms" or smaller components across Blocks. For example, we have a `<Link />` component which has a `Link` GraphQL Type associated to it. Then we can have that same `Link` type on the Header Nav Links or inside a Page Section and they would both derive from the same type that we can use to type the `<Link />` props.

The workaround that I'm using is defining all those "atoms" as Page Blocks and then we have a type generated like `PageBlocksLink` that we can (not so safely) use across the components. However, they're not "top level blocks" that belongs to the `Page` type, they're reusable bits of data.

Even with this hack we still have the problem that they're not the same `__typename`. On the example above we'll have two unique ones: `PageBlocksCtaSectionLink` and `GlobalLayoutHeaderNavLink`. However, if we could register a reusable `Link` object type, they would just be a `Link` type.
