### ISSUE TITLE
items.map is not a function (defaultValue vs defaultItem issue)

### ISSUE THREAD

**Issue by DmacMcgreg** [tinacms/tinacms#3027]
## Description

Error appears in admin sidepanel editor when adding then editing a list of objects, whereby the nested object in the list also has a list of objects, and those objects have a ui prop in the schema

### Steps to reproduce

```
import linkSchema from "../schemas/linkSchema"
import headerSchema from "../schemas/headerSchema"
import bodyRichText from ".tina/schemas/bodyRichText"
import tableSchema, { tableFields } from "../schemas/tableSchema"


const pagesCollection: any = {
  label: "Pages",
  name: "pages",
  path: "content/pages",
  format: "mdx",
  fields: [
    {
      name: "multiTables",
      list: true,
      type: "object",
      fields: [
        {
          type: "object",
          label: "Headers",
          name: "headers",
          list: true,
          ui: {
            defaultValue: {
              colspan: 1,
              bg: "white",
              color: "black",
            },
          },
          fields: [
            { type: "rich-text", name: "name", label: "Header Name" },
            { type: "string", name: "bg", label: "Header Background Color", component: "color" },
            { type: "string", name: "color", label: "Text Color", component: "color" },
            { type: "string", name: "colspan", label: "Colspan" },
            { type: "string", name: "width", label: "Header Width" },
            { type: "string", name: "height", label: "Header Height" },
          ],
        },
```

### Expected result

It should not error when clicking edit of the list item

### Actual result

items.map is not a function
<img width="697" alt="CleanShot 2022-07-02 at 14 31 31@2x" src="https://user-images.githubusercontent.com/3266023/177010796-d16a3272-9e1b-4ca9-9ee7-8d04502ab6fa.png">

### Environment
Mac Os 12.4
```
"@chakra-ui/react": "1.x",
    "@emotion/react": "11.x",
    "@emotion/styled": "11.x",
    "@tinacms/cli": "0.60.25",
    "blitz": "0.45.4",
    "framer-motion": "5.x",
    "lodash": "4.17.21",
    "next-tinacms-cloudinary": "3.4.3",
    "polished": "4.2.2",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "styled-components": "5.3.5",
    "tinacms": "0.68.11"
  },
  "devDependencies": {
    "@tinacms/cli": "0.60.14",
    "@types/react": "18.0.1",
    "eslint": "7.32.0",
    "husky": "7.0.4",
    "lint-staged": "11.3.0-beta.2",
    "prettier": "2.7.1",
    "pretty-quick": "3.1.3",
    "typescript": "~4.5"
  },
```

#### Tinacms Package Versions

```
├── @tinacms/cli@0.60.14
├── next-tinacms-cloudinary@3.4.3
├── tinacms@0.68.11

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |    Chrome 103     |
| os      |   Mac OS 12.4       |
| node    |   16.13.0      |
| npm     |   8.1.0      |

**Comment by DmacMcgreg** [comment]
Seems like I'm able to fix by replacing 'defaultValue' within the ui property to the function 'defaultItem'

**Comment by jamespohalloran** [comment]
Is defaultItem used for a list? or an object? @tinacms/maintainers 

This doc says its used for objects:
https://tina.io/docs/schema/#default-value-for-objects

But this doc says its used specifically for lists:
https://tina.io/docs/reference/types/object/#as-a-list

**Comment by DmacMcgreg** [comment]
I mean, ideally this should not throw an error, or at least it should warn the user 'hey you are trying to use defaultValue, but you should instead be using defaultItem instead' ?

I somehow managed to fix this by mistake... and i recommend leaving the title of the post as it is so that people who also get this error can find it, at least until this is fixed or a better error message is added.

**Comment by jamespohalloran** [comment]
>  and i recommend leaving the title of the post as it is so that people who also get this error can find it, at least until this is fixed or a better error message is added.

So correct me if I'm wrong, but I believe the "items.map" is within your page not something within Tina. It's blowing up because there's no default value set, but your page is trying to iterate through it.

**Comment by DmacMcgreg** [comment]
No the error is coming from Tina itself

**Comment by jamespohalloran** [comment]
I added some thoughts [in this thread](https://github.com/tinacms/tinacms/issues/2706#issuecomment-1232819969) on how I'd expect defaultValue vs defaultItem to behave.

**Comment by jamespohalloran** [comment]
We've updated the bahaviour of defaults, so there is no longer a "defaultValue". This bug should no longer be an issue.
https://tina.io/blog/tina-version-0.69.13
