### ISSUE TITLE
Allow passing navigation callback for routeOverride's in collection views.

### ISSUE THREAD

**Issue by danielknell** [tinacms/tinacms#3044]
## Summary

As a User I want to navigate via a callback so that previews work with single page apps.

### Expected Results

When I click on an item in a collection, and have configured a route in `RouteMappingPlugin`, Tina calls a configurable callback function with the new url.

### Notes

When in a single page app, it would be handy if instead of using `window.location.href` [here](https://github.com/tinacms/tinacms/blob/eff421469eeb3f2c4c175d678060fb4e45e4a70b/packages/tinacms/src/admin/pages/CollectionListPage.tsx#L112) we could instead configure a callback (with default implementation being what's already there).

This would allow some collusion between RouteMappingPlugin and what ever router is being used to do navigation in the context of a single page app.

At the moment you can hax this into working by prefixing the urls with `#/something/` in RouteMappingPlugin

```js
      const RouteMapping = new RouteMappingPlugin((collection, document) => {
        if (["post"].includes(collection.name)) {
          return `#/preview/post/${document._sys.filename}`;
        }

        return undefined;
      });
```

then wrapping the admin to listen for those hashes.

```js
const Admin = () => {
  useEffect(() => {
    const onHashChange = () => {
      if (!location.hash.startsWith("#/preview/")) {
        return;
      }

      navigationCallbackGoesHere(location.hash.slice(9));
    };

    window.addEventListener("hashchange", onHashChange);

    return () => {
      window.removeEventListener("hashchange", onHashChange);
    };
  });

  return <TinaAdmin />;
};
```

but it would be nice to be able to just set this as a prop or something like the following:

```js
const Admin = () => {
  return <TinaAdmin navigationCallback={navigationCallbackGoesHere} />;
};
```

**Comment by logan-anderson** [comment]
@danielknell I like this idea as well. 

Here is a work around that is also hacky but works.  

```ts
import router from 'next/router'
//... 

cmsCallback: (cms) => {
    // ...
    cms.plugins.add(
      new RouteMappingPlugin((collection, doc) => {
        if (
         someCondition
        ) {
          router.push('/links');
        }
        return '';
      })
    );
    return cms;
  },

```

The awkwardness here is that it will navigate to the admin page for a second and then navigate clientSide to the desired page. 

What do you think about this API for this feature.

- if a string is returned navigate to that string (how it works now and is not framework specific ). 
- if a falsy value is returned navigate to the admin page (how it works now) 
- If a function is returned run that function. So my example would become. 

```ts
import router from 'next/router'
//... 

cmsCallback: (cms) => {
    // ...
    cms.plugins.add(
      new RouteMappingPlugin((collection, doc) => {
        if (
         someCondition
        ) {
          return ()=>{router.push('/links');}
        }
        return '';
      })
    );
    return cms;
  },

```


@danielknell What do you think? Do you have a better API in mind?

**Comment by danielknell** [comment]
hrm, that's interesting and would probably solve my exact case, but I wonder how easy it would be to get a router callback from something more hook based or reliant on providers into into `scheme.ts`.

**Comment by logan-anderson** [comment]
@danielknell We have something like that planned. 

it will look like https://github.com/tinacms/tinacms/issues/2714. Would this work for you as well?

**Comment by danielknell** [comment]
@logan-anderson 

Looks like this would still require some hackery, and will still trigger the `location.href` based navigation? I want to override the other side of it, route generation works for me.

**Comment by jamespohalloran** [comment]
Do you mind explaining a bit more what you're trying to do @danielknell? 

> As a User I want to navigate via a callback so that previews work with single page apps.

I don't think I understand why previews won't work with single page apps.

A lot's changed since this ticket was filed ([new router override](https://tina.io/docs/contextual-editing/router/), and also now the [preview runs in an iframe](https://tina.io/blog/upgrading-to-iframe/)), so maybe this ticket is already complete.
