### ISSUE TITLE
@tinacms/api-git file-writer should lock on a file-by-file basis

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#305]
## Summary

The `file-writer` currently has a single queue that gets locked. Once unlocked, it only performs the most recent request. There should instead be a queue for each file.

### Motivation

A queue-per-file is necessary to allow multiple files to be edited at the same time.

**Comment by abtris** [comment]
Good point, how you can manage persistence? Just in memory or some db?

**Comment by ncphillips** [comment]
Entirely in-memory/filesystem. There's no database being used by tinacms.
