### ISSUE TITLE
Support reference fields in Rich Text

### ISSUE THREAD

**Issue by mAAdhaTTah** [tinacms/tinacms#3050]
## Summary

As an author, I want to be able to embed other documents in my rich text fields so that I don't have to interweave rich text blocks + other templates in my content.

### Expected Results

* Reference fields are saved in the MDX properly
* Reference fields are returned by the GraphQL API properly

### Notes

I saw somewhere that this was intentionally left out due to difficulty handling the GraphQL part. Personally, I'd be fine just outputting the reference string and then doing some post-processing of the GraphQL to fetch the reference separately. I'm mostly filing this ticket to track cuz I definitely want to take advantage of this.

**Comment by LeoMartinDev** [comment]
Same here, I thought it was supported by the framework :(

![image](https://user-images.githubusercontent.com/7238941/181099051-82a64484-e169-46c0-a5ef-2ab57d8892a7.png)

**Comment by mAAdhaTTah** [comment]
Not stale.

**Comment by mAAdhaTTah** [comment]
Can we get this reopened? This issue is the only thing that's holding me back from moving everything into a single Rich Text field rather than an array of blocks.

**Comment by mmorkt** [comment]
please reopen, I'm having the same problem.
