### ISSUE TITLE
Media manager doesnt show images for certain subfolders when using Cloudinary

### ISSUE THREAD

**Issue by llibdude** [tinacms/tinacms#3061]
## Description

I recently upgraded  Tina and noticing since I am still using Cloudinary that some of my cloudinary subfolders are no longer showing images in the Media Manager.

It has to do with ./ being prepended to the beginning of the folder paths now.  I suspect due to the github hosting feature recently added.

What is strange is for me some of the cloudinary subfolders will return images with the ./ but others will not.  Luckily for me since I've already branched off the main cloudinary code its easy for me to "undo" the ./ but I suspect others who upgrade and are still using cloudinary will likely hit this bug

In addition, clicking the back icon breaks the UI (and the `/ . /` in the path doesnt really make sense for cloudinary either.
![unknown](https://user-images.githubusercontent.com/5255924/181363572-d8cb5bd3-e311-4636-b825-a905000c2b76.png)

### Steps to reproduce

This could be tough to repro potentially as some folders work and others don't and I don't really know why.

- Set up a repo to use cloudinary and have images in subfolders inside the cloudinary project
- From Tina, using the media manager, navigate to these subfolders.
- I cannot see the images in these subfolders

### Expected result
Navigating through the media manager should show images for all directories

#### Tinacms Package Versions

```text
├── @tinacms/auth@0.50.2
├── @tinacms/cli@0.60.28
├── @tinacms/toolkit@0.56.35
├── next-tinacms-cloudinary@3.5.13
├── tinacms@0.68.13
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by jamespohalloran** [comment]
Looks like this will be fixed with: https://github.com/tinacms/tinacms/pull/3041
(In the meantime, it is now available under the "beta" npm tag)
