### ISSUE TITLE
cannot escape from rich-text code block

### ISSUE THREAD

**Issue by danielknell** [tinacms/tinacms#3062]
## Description

once you add a code block at the end of the document, there is no escape 😂.

### Steps to reproduce

typing is hard... here's a video...

https://user-images.githubusercontent.com/229004/181450411-d8ecc117-2351-4e7d-82ef-33fa1341408a.mov

### Expected result

when I click the code block button or another type of block, it should let me escape the code block and add non code after the code block

### Actual result

trapped in an eternal prison of code...

#### Tinacms Package Versions

```text
├── @tinacms/cli@0.0.0-20220727195451
├── react-tinacms-editor@0.53.26
├── tinacms@0.0.0-20220727195451
```

also saw this on previous version before upgrading. video is from latest beta.

#### Tools

tested and saw it happening in Safari 15.6 (17613.3.9.1.5) and Chrome 103.0.5060.134 (Official Build) (arm64)
 on macOS 12.5

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by llibdude** [comment]
noticing this as well

**Comment by robbyph** [comment]
Ctrl + Enter

**Comment by jeffsee55** [comment]
This should be fixed in the latest version of `tinacms`.
