### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by Yash-Singh1** [tinacms/tinacms#3067]
## Summary

Currently, the `tinacms` isn't tested nor supports React 18 in some of its dependencies.

### Expected Results

* Create a starter `tinacms` project
* Run `pnpm add react@18`
* Notice peer dependency warnings

### Notes

Peer dependency warnings:

```console
├─┬ tinacms
│ ├── ✕ missing peer react-is@"^16.13.1 || <18.0.0"
│ ├─┬ @tinacms/sharedctx
│ │ └── ✕ missing peer react-is@>=16.14.0
│ └─┬ @tinacms/toolkit
│   ├── ✕ missing peer react-is@>=16.14.0
│   ├─┬ @udecode/plate-ui-combobox
│   │ ├─┬ @udecode/plate-styled-components
│   │ │ └── ✕ missing peer react-is@>=16.8.0
│   │ └─┬ @udecode/plate-ui-popper
│   │   └─┬ react-popper
│   │     └── ✕ unmet peer react@"^16.8.0 || ^17": found 18.2.0
│   ├─┬ @react-aria/listbox
│   │ └── ✕ unmet peer react@"^16.8.0 || ^17.0.0-rc.1": found 18.2.0
│   └─┬ react-beautiful-dnd
│     ├── ✕ unmet peer react@"^16.8.5 || ^17.0.0": found 18.2.0
│     └─┬ use-memo-one
│       └── ✕ unmet peer react@"^16.8.0 || ^17.0.0": found 18.2.0
```

**Comment by Koala-gentil** [comment]
Adding tina to a new next project with react 18 will give you this error:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
```

It's a pity that it is not specified in the documentation that react 18 is not supported and you have to downgrade to 17 because this error could discourage newcomers.

**Comment by jamespohalloran** [comment]
@jeffsee55 Does the new iframe-based editing unlock support for React 18?

**Comment by jeffsee55** [comment]
@jamespohalloran yes because it decouples Tina's version from the one that's installed. Tina will stay on 17 for a bit longer but shouldn't block others

**Comment by brvnonascimento** [comment]
Can confirm that it is working on React 18 + Next.js 13 with the iframe based implementation

**Comment by brvnonascimento** [comment]
Also adding 'use client' on both the `TinaDynamicProvider.js` and `app/admin/page.tsx` made it work on React 18 and Next 13 on the non iframe based implementation.

**Comment by jamespohalloran** [comment]
Thanks @brvnonascimento! Closing as complete
