### ISSUE TITLE
Error: Cannot query field "sys" on type "Document". Did you mean "_sys" when you try to add a new document with cms.flags.set("tina-admin", false) set to false.

### ISSUE THREAD

**Issue by the-digital-anarchist** [tinacms/tinacms#3068]
## Description
Error: `Cannot query field "sys" on type "Document". Did you mean "_sys"` 
when you try to add a new document with cms.flags.set("tina-admin", false) set to false.

### Steps to reproduce

Clone the latest tina-cloud-starter start it up and set cms.flags.set("tina-admin", false).
Then try to add a new document in the sidebar.

### Expected result

Makes a new record/document

### Actual result

Get error: `Cannot query field "sys" on type "Document". Did you mean "_sys"?`

#### Tinacms Package Versions

Latest

**Comment by jamespohalloran** [comment]
Hey! So this works for you without the `cms.flags.set("tina-admin", false)` flag, correct? 

That flag isn't really something we designed to be toggled off, now that the feature's been released, so I'd be curious to hear more about your use-case and why you want it off.

**Comment by gumyn** [comment]
In fact you can just `npx create-tina-app@latest` and then try a `yarn build` and you will have the same issue. Impossible to deploy the latest version on vercel.
