### ISSUE TITLE
Formatted Date not showing on initial load

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#307]
## Description

Upon passing in date field options to a form, on initial load the unformatted date string shows. If you open the date picker and select a new date, the new formatted date will be reflected unless you navigate to another page or refresh and you'll see the raw string again.

### Steps to reproduce

Pass in formatDate options to the date field in gatsby-demo, open the sidebar.

### Expected result

I would expect to see the formatted date filling the input.

### Actual result

The raw unformatted date string fills the input until a date is selected.

**Comment by jamespohalloran** [comment]
PR open: https://github.com/tinacms/tinacms/pull/322

**Comment by ncphillips** [comment]
Closed in #322
