### ISSUE TITLE
Tina 0.68.14 crashes on build

### ISSUE THREAD

**Issue by selenecodes** [tinacms/tinacms#3076]
## Description

When converting an existing Next.js project to TinaCMS using [the official guide](https://tina.io/docs/introduction/tina-init/) the latest version of Tina is installed (tinacms@0.68.14 and @tinacms/cli@0.61.0), however these versions crash the build and complains about a  EBUSY lock.

```bash
[Error: EBUSY: resource busy or locked, unlink 'C:\Users\Selene\Documents\tina-bug-report\.tina\__generated__\db\LOG'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'C:\\Users\\Selene\\Documents\\tina-bug-report\\.tina\\__generated__\\db\\LOG'
}
Compilation failed with errors. Server has not been restarted. see error below
 EEXIST: file already exists, mkdir 'C:\Users\Selene\Documents\tina-bug-report\.tina\__generated__'
[Error: EEXIST: file already exists, mkdir 'C:\Users\Selene\Documents\tina-bug-report\.tina\__generated__'] {
  errno: -4075,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: 'C:\\Users\\Selene\\Documents\\tina-bug-report\\.tina\\__generated__'
}
```

### Steps to reproduce

1. `npx create-next-app tina-bug-report`
2. `cd tina-bug-report`
3. `npx @tinacms/cli@latest init`
4. Add the TinaProvider to `_app.js`
5. `npm run dev`

Demo project:
[https://github.com/selenecodes/tina-ebusy-bug-report](https://github.com/selenecodes/tina-ebusy-bug-report)

### Expected result

TinaCMS should generate the files it needs and start the Next.js dev server

### Actual result

TinaCLI crashes during build and has a resource lock/busy error.

#### Tinacms Package Versions

```text
"@tinacms/cli@0.61.0",
"tinacms@0.68.14"
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  104.0.5112.80 (Official Build) (64-bit) (cohort: 104_stable_rampup_79) |
| os      |  Windows 10 Pro 64bit Version 21H2 OS Build 19044.1826 |
| node    |  16.14.2  |
| npm     | 8.5.0 |

**Comment by selenecodes** [comment]
For anyone that wishes to add Tina to an existing Next.js page follow the following steps:
1. `npx @tinacms/cli@latest init`
4. Use the following Tina schema
```typescript
// .tina/schema.ts
import { defineSchema, defineConfig } from "tinacms";

const schema = defineSchema({
  config: {
    media: {
      // If you wanted cloudinary do this
      // loadCustomStore: async () => {
      //   const pack = await import("next-tinacms-cloudinary");
      //   return pack.TinaCloudCloudinaryMediaStore;
      // },
      // this is the config for the tina cloud media store
      tina: {
        publicFolder: "public",
        mediaRoot: "uploads",
      },
    },
  },
  collections: [
    // Add your collection definition here
  ],
});

const branch = "main";
const apiURL =
  process.env.NODE_ENV == "development"
    ? "http://localhost:4001/graphql"
    : `https://content.tinajs.io/content/${process.env.NEXT_PUBLIC_TINA_CLIENT_ID}/github/${branch}`;

export const tinaConfig = defineConfig({
  apiURL,
  schema,
  cmsCallback: (cms) => {
    //  add your CMS callback code here (if you want)

    // The Route Mapper
    /**
     * 1. Import `tinacms` and `RouteMappingPlugin`
     **/
    import("tinacms").then(({ RouteMappingPlugin }) => {
      /**
       * 2. Define the `RouteMappingPlugin` see https://tina.io/docs/tinacms-context/#the-routemappingplugin for more details
       **/
      const RouteMapping = new RouteMappingPlugin((collection, document) => {
        return undefined;
      });
      /**
       * 3. Add the `RouteMappingPlugin` to the `cms`.
       **/
      cms.plugins.add(RouteMapping);
    });

    return cms;
  },
});

export default schema;
```
5. Change `_app.tsx` to the following:
```typescript
// pages/_app.tsx
import "../styles.css";
import TinaProvider from "../.tina/components/TinaDynamicProvider";

const App = ({ Component, pageProps }) => {
  return (
    <TinaProvider>
      <Component {...pageProps} />
    </TinaProvider>
  );
};

export default App;
```
6. Modify `package.json`
```diff
{
  "name": "tina-bug-report",
  "version": "0.1.0",
  "private": true,
  "scripts": {
-    "dev": "tinacms dev -c \"next dev\"",
+   "dev": "tinacms server:start -c \"next dev\"",
-    "build": "tinacms build && next build",
+   "build": "tinacms server:start -c \"next build\"",
-    "start": "tinacms build && next start",
+   "start": "tinacms server:start -c \"next start\"",
    "lint": "next lint"
  },
  "dependencies": {
-   "@tinacms/cli": "^0.61.0",
+   "@tinacms/cli": "0.60.28",
    "next": "12.2.4",
    "react": "18.2.0",
    "react-dom": "18.2.0",
-   "tinacms": "^0.68.14"
+   "tinacms": "0.68.13"
  },
  "devDependencies": {
    "eslint": "8.21.0",
    "eslint-config-next": "12.2.4"
  }
}
```
7. `npm i`
8. `npm run dev`

**Extra notes:**
Make sure to follow the version of the docs that's appropriate: [Tina 0.68.13 Docs](https://tinacms-site-next-i08bcbicy-tinacms.vercel.app/)

**Comment by logan-anderson** [comment]
@selenecodes Thank you for the bug report. I am unable to reproduce this on MacOS so I have a feeling its a windows issue. Going to try to reproduce in a windows PC later today.

Thanks again for reporting the issue

**Comment by 96312** [comment]
@logaI I just started started following https://tina.io/docs/introduction/using-starter/ and running `npx create-tina-app@latest` gives me this exact error. Fresh directory, fresh project and everything.

**Comment by selenecodes** [comment]
@96312 if you're still having the issue, I suggest upgrading to the latest version of `tinacms` and `@tinacms/cli`
