### ISSUE TITLE
retrieve all unique values for a list of strings field.

### ISSUE THREAD

**Issue by danielknell** [tinacms/tinacms#3081]
## Summary

As a developer I want to be able to pull all unique values for a field (especially values within lists of strings) and count of matching posts so that I can build tag clouds efficiently

### Expected Results

some query goes in taking the field of interest and out comes the values and associated counts:

```
[
    { "value": "foo", "count": 123 },
    { "value": "bar", "count": 456 },
    { "value": "bad", "count": 789 }
]
```

### Notes

being able to pull unique tags or categories will allow efficient `getStaticPath` and `getStaticProps` implementations when dealing with tag or category indexes when values are not set up as a separate collection. Otherwise you have to pull the entire collection and process client side.

**Comment by jeffsee55** [comment]
Aside from the other issue with filtering [here](https://github.com/tinacms/tinacms/issues/3079). Would this get you what you want?

```graphql
{
  postsWithFoo: postConnection(filter: {
    tags: { in: "foo"}
  }) {
    totalCount
  }
  postsWithBar: postConnection(filter: {
    tags: { in: "bar"}
  }) {
    totalCount
  }
  postsWithBad: postConnection(filter: {
    tags: { in: "bad"}
  }) {
    totalCount
  }
}
```
Would yield:

```
{
  "postsWithFoo": { "totalCount": 123 },
  "postsWithBar": { "totalCount": 456 },
  "postsWithBad": { "totalCount": 789 },
}
```

**Comment by danielknell** [comment]
There is still the problem of knowing what the tags are in the first place though...

**Comment by jeffsee55** [comment]
Ah I see, it seems like it'd make sense for a `tag` to be it's own record in that case, I know that feels cumbersome to have a whole file dedicated to one simple little string of info. And this gets back to the lack of support for reverse lookups, which aren't supported yet. But in general I would think that would be ideal for this scenario (sorry, this isn't supported yet!):

```graphql
tagsConnection {
  edges {
    node {
      references { # note that this doesn't exist yet!
        totalCount
      }
    }
  }
}
```

Another issue we'd like to get to is editing references inline, so you don't have to leave the form when you're working with a reference. Would be great for stuff like this.

As for the issue of having a markdown or json file for one little tag, this is something we've discussed streamlining before https://github.com/tinacms/tinacms/discussions/2948#discussioncomment-2874040

**Comment by danielknell** [comment]
that feels pretty counter intuitive to how tags work in pretty much any other CMS though, they are normally free entry strings, or tag records are managed transparently without the user needing to worry about them...

so unless the CMS can create tags automatically in some kind of hidden collection its going to make for awful UX.

**Comment by danielknell** [comment]
I suspect the answer will probably end up being an immutable collection generated by a GitHub action...

**Comment by jeffsee55** [comment]
> or tag records are managed transparently behind the scenes and look like free entry strings

I believe this is likely how they're most-often handled (or in something like Wordpress they'd be post metadata). In general I think they need to be individual records in our data layer so they can be indexed for querying like this, and our aim would be to provide a seamless ux as well here.

**Comment by mAAdhaTTah** [comment]
In WordPress, a tag is a row in the taxonomy (or term...?) table, so they are individual records in the database. A document per tag is how I'm handling the migration out of WordPress.

**Comment by jeffsee55** [comment]
Ah right, taxonomies - forgot about those. In Tina everything is a `collection`, but we probably want to explore the idea of some collections being less "front-facing", as in - the type of collection which is mainly useful when referenced and should easy to create/edit/delete from within the form of another collection document. I don't see a lot of CMSs handling this stuff very well, perhaps Wordpress is the one that get's it right here.
