### ISSUE TITLE
types.ts break when using "templates" in a collection

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3087]
## Description

When I switch a collection to use "templates" instead of "fields", "types.ts" seems to get cleared out. 
[See the example in the starter](https://github.com/tinacms/tina-cloud-starter/compare/templates-test?expand=1), specifically this change in [types.ts](https://github.com/tinacms/tina-cloud-starter/blob/17d419ea01048032b4ca4bdfed91c40b910b4f0c/.tina/__generated__/types.ts#L10)

Console gives:

```
TypeError: Failed to fetch
    at <anonymous>:1:876
    at __webpack_require__.hmrM (http://localhost:3000/_next/static/chunks/webpack.js?ts=1660070703891:1280:20)
error - unhandledRejection: Error: aborted
    at connResetException (node:internal/errors:691:14)
    at abortIncoming (node:_http_server:596:17)
    at socketOnClose (node:_http_server:590:3)
    at Socket.emit (node:events:402:35)
    at TCP.<anonymous> (node:net:687:12) {
  code: 'ECONNRESET'
}
```

And the browser gives:

<img width="1216" alt="Screen Shot 2022-08-09 at 3 49 16 PM" src="https://user-images.githubusercontent.com/3323181/183738095-e974f5fc-7443-4159-b6d0-21d663f29ab6.png">

### Steps to reproduce

[See the example in the starter](https://github.com/tinacms/tina-cloud-starter/compare/templates-test?expand=1)
I replaced a collection's fields with a few dummy templates

#### Tools

Node 16
├── @tinacms/cli@0.61.0
├── tinacms@0.68.14

**Comment by logan-anderson** [comment]
@jamespohalloran I was just looking into this and I can not reproduce in the mono repo. 

I did however find an issue that may be causing it. It looks like if an error occurs in the the `sequential` it swallows it and the promise does not resolve (hangs forever). 

Hopefully fixing this will fix your issue. 

Note: You can see this behaviour by adding this to the code

```ts
await sequential(collections, async (collection) => {
    const frag = (await builder.collectionFragment(
      collection
    )) as FragmentDefinitionNode

    fragmentDefinitionsFields.push(frag)
    throw new Error('foo bar')
  })
```

cc @jeffsee55

**Comment by mAAdhaTTah** [comment]
I'm seeing a different error that seems related, as a result of the new sorting logic:

![Screen Shot 2022-08-20 at 11 01 53 PM](https://user-images.githubusercontent.com/4371429/185773471-67c729f0-0f12-4240-bc8a-080655091986.png)

This searches the `fields` property but that's undefined because the collection uses `templates.`
