### ISSUE TITLE
Better workflow for testing local tinacms changes from outside the monorepo

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#311]
## Summary

I want a better workflow for testing local changes within tinacms using a local site outside of the monorepo.

### Basic example
```
tinacms
   packages
      tinacms-react
      ...
my-site
```
### Motivation

Debugging changes with the monorepo on a test site (apart from the tinacms-demo within the monorepo) is currently difficult. Testing using the tinacms-demo is tricky because I have to reproduce the behaviour in my personal site, and certain actions automatically commit to git (e.g adding an image).

**Comment by jamespohalloran** [comment]
My first idea was to run `npm link` or `yarn link` on each of the individual packages using `lerna exec -- npm link`.
There were build errors when linking on my personal site because certain dependencies in the local packages were missing its dependencies

When building without using --hoist, there were build errors because of: https://github.com/tinacms/tinacms/issues/308

I resolved each of those build errors here: https://github.com/tinacms/tinacms/pull/310
...but there are now runtime errors in my local site stating that `String` is an invalid query type.
I can look deeper into the above issue, but I'm not confident there won't be more issues popping up after that.

If anyone has a better solution than `npm link`, I'd love to hear it! And if not I will dig up some actual error messages from where I left off.

**Comment by PaulBunker** [comment]
I'm not sure if this is still a problem for you but I’ve been using yalc https://github.com/whitecolor/yalc to use a package that is under development in a current project.
Install it globally `yarn global add yalc` navigate to the package and yalc publish
Then inside your project `yalc add <package>`
I’ve been running
 `lerna run dev --reject-cycles --scope gatsby-tinacms-mdx && yalc push`
after making changes and my gatsby instance has been automatically loading it.
Magic.

**Comment by ncphillips** [comment]
There's also an approach in that the [Next.js Team](https://github.com/zeit/next.js/blob/master/contributing.md#running-your-own-app-with-locally-compiled-version-of-nextjs) uses that could be useful.

**Comment by kendallstrautman** [comment]
Closing as this seemed improved by the webpack helpers.
