### ISSUE TITLE
Images updated clientside do not update on production

### ISSUE THREAD

**Issue by robbyph** [tinacms/tinacms#3112]
## Description

When modifying an image either locally or within github, tina cloud does not recognize it as a new image and keeps the old, unmodified image.

### Steps to reproduce

1. Upload an image to the Tina media manager
2. Deploy it so that it's active and visible in your deployment fufilled by tina cloud
3. Modify the image locally, such as cropping it, then push this change to github

### Expected result

The new cropped image should replace the old, uncropped image

### Actual result

Tina Cloud retains the outdated, uncropped image. Even if you delete it, then resync, it still uses the old one. Even if you delete it, resync it, save without the image, then try to resync, it still uses the old one. I've tried every workaround i can think of. 

#### Tinacms Package Versions

```
????????? @tinacms/cli@0.61.5
????????? react-tinacms-editor@0.53.26  
????????? tinacms@0.68.15  
```

Using NextJS and TailwindCSS

#### Tools

| Tool    | Version |
| browser |  Firefox 103.0.2       |
| os      |   Windows 10      |
| node    |    16.16.0     |
| npm     |   8.3.0      |

**Comment by jeffsee55** [comment]
@robbyph this is expected behavior, and is a limitation of Tina's image handling in it's current state. I will update the documentation to reflect this limitation and we hope to improve this in the future!

Closing but feel free to reopen if you think there's something more immediate that can be done.
