### ISSUE TITLE
Collection name with a - in it fails quietly

### ISSUE THREAD

**Issue by mortocks** [tinacms/tinacms#3126]
## Description

Collection name with a - in it fails quietly

### Steps to reproduce

Create a new collection with a - in the name for example case-studies

```javascript
   {
      label: "Case Studies",
      name: "case-studies", // Problem here
      path: "content/case-studies",
      format: "mdx",
      fields: [
        {
      .....
      ]
}
```

run ```yarn dev```

### Expected result

If dashes are not supported, then starting the server should throw an error.

### Actual result

The server hangs with no error output

#### Tinacms Package Versions

```text
@tinacms/starter@0.1.0
├── @tinacms/cli@0.61.0
├── tinacms@0.68.14
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   none      |
| os      |     OSX   |
| node    |    v16.13.2     |
| npm     |   8.1.2      |

**Comment by InderdeepBajwa** [comment]
The problem here looks to be with a hyphen `-` in the name. I tried with `name: case_studies` and was able to launch Tine whereas `name: case-studies` would fail.

**Comment by mortocks** [comment]
I understand the issue, the problem is that the console just hangs quietly and does not throw an error so the developer is unaware of the issue
