### ISSUE TITLE
Reference Type options only show first 10 results

### ISSUE THREAD

**Issue by dgrisham** [tinacms/tinacms#3127]
## Description

When I use a reference type in a schema, the options list in the UI only let's you choose from the first 10 items in the collection. I'm guessing this is because Tina enabled the data layer by default, which defaults to grabbing the first 10 elements.

### Steps to reproduce

A basic reference type that queries a collection with more than 10 elements should be enough to reproduce this issue.

```
const schema = defineSchema({
  // ...
  collections: [
    {
      label: "Blog Posts",
      name: "post",
      path: "content/post",
      format: "mdx",
      fields: [
        // ...
        {
          type: "reference",
          list: true,
          label: "Related Posts",
          name: "relatedPosts",
          collections: ["post"],
        },
        // ...
      ],
    },
  ],
});
```

### Expected result

All posts should be options in the `Related Posts` dropdown.

### Actual result

Only the first 10 posts were selectable.

#### Tinacms Package Versions

```text
0.69.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | brave  |
| os      |  Arch Linux  |
| node    |  18.7.0 |
| yarn     |  1.22.19 |

**Comment by jamespohalloran** [comment]
These results are being paginated. See this thread: https://github.com/tinacms/tinacms/issues/3135

**Comment by dgrisham** [comment]
> These results are being paginated. See this thread: #3135

Right, I'm just not sure how to pass in a graphql query when dealing with a reference field. Is there an option to override the default query?

**Comment by DmacMcgreg** [comment]
This also seems to me to be a strange default option paginating the first 10 only. Normally wouldn't you want to just return everything and only filter when specifically passing some filter value in?

**Comment by dgrisham** [comment]
Can this issue be reopened? The rationale used to close it was already understood/stated in the OP and doesn't provide a solution to the actual issue. The bug tag isn't completely accurate, maybe this is better framed as a feature request to override the query used in reference types? cc @jamespohalloran

**Comment by jamespohalloran** [comment]
Hmm, I assumed this was a pagination issue (because of it being limited to 10), but I'm a bit confused. I was under the impressions reference fields [weren't currently supporting lists](http://localhost:3000/showcase/) (Unless that's a recent update that slipped by me and didn't make its way into our documentation).

Is your site's source code public by any chance? 

When I test on a list of objects, it's returning the full set of results for me.

**Comment by pharmarin** [comment]
Reference form field list is paginated with version 0.69.7 too. I believe this is not the expected result.
