### ISSUE TITLE
_sys.breadcrumbs ignore its excludeExtension param

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3134]
## Description

_sys.breadcrumbs takes an "excludeExtension" param, however the extension is always omitted. 

### Steps to reproduce

Make a query with:

```
    _sys {
      breadcrumbs(excludeExtension:false)
    }
```

### Expected result

extension shouldn't be excluded

### Actual result

extension is always excluded

**Comment by jeffsee55** [comment]
I think we should just remove the argument altogether and _not_ include the extension since you can grab that elsewhere.
