### ISSUE TITLE
Cannot find record

### ISSUE THREAD

**Issue by DmacMcgreg** [tinacms/tinacms#3135]
## Description

Tina does not find some records, unsure as to why.

### Steps to reproduce

Add new .mdx file into nested folder.
For exapmle, having content/pages for the root folder for pages collection, then adding another nested folder such as 'videos' and then adding files into that folder, tina does not seem to find them.

```
const pageListData = await client.queries.pagesConnection()
  console.log(pageListData.data.pagesConnection.edges)

// this does not have the file mentioned. even restarted server does nothing.
```

### Expected result

When running graphql query for those files, they should appear.

### Actual result

`Unable to find record content/pages/patients/patient-1.mdx`

#### Tinacms Package Versions

```
├── @tinacms/auth@0.50.4
├── @tinacms/cli@0.61.0
├── next-tinacms-cloudinary@3.4.3
├── tinacms@0.68.14

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   Chrome      |
| os      |      MacOS 12.5   |
| node    |    16.13.0     |
| npm     |     8.1.0    |

**Comment by jamespohalloran** [comment]
Any chance you have more than 10 records? If so, they might just be being paginated.
If so, you can set the "first" property: https://tina.io/docs/graphql/queries/advanced/pagination/

**Comment by DmacMcgreg** [comment]
Yeah that seems to be it. Seems like this was a breaking change, as many of my pages broke recently.
How would I filter based on the file name or the folder it is in? 
I am basically putting every page under the same collection, but separating based on folders.

**Comment by DmacMcgreg** [comment]
I just looked through the docs, and I don't see any examples or guides on how to handle this anymore... 
It seems really confusing to me that we would set a hard limit of 10 per page. How are we supposed to iterate through these pages in getStaticProps? I don't see any api for going to the next page.
So we have do write a while loop to hold the reference of the last array value and continue to query the API until we get all the pages?

Maybe I'm missing something here?

**Comment by jeffsee55** [comment]
@DmacMcgreg you can specify `first: -1` to get all documents on a collection. 

```graphql
postConnection(first: -1) {
  ...
}
```

**Comment by DmacMcgreg** [comment]
@jamespohalloran 
Would be nice to have this in the docs / a guide before closing this ticket, although this is a good solution.
Or rather to have this as the default, and paginate only when asked.

**Comment by jamespohalloran** [comment]
Just created a ticket for ["Reducing friction around pagination"](https://github.com/tinacms/tina.io/issues/1392). I'm unsure if `first: -1` is something we want to promote (or if we should just have better defaults or docs)
