### ISSUE TITLE
Invalid hook call at first launch

### ISSUE THREAD

**Issue by pharmarin** [tinacms/tinacms#3148]
## Description

After I ran `npx @tinacms/cli@latest init` in my nextjs repo and ran `yarn dev` I get this error when accessing /admin : Error: Invalid hook call [...] at EditProvider ([...]/node_modules/@tinacms/sharedctx/dist/index.js:37:40

### Steps to reproduce

Run the install commande in an existing nextjs repo

Tried to delete node_modules & yarn.lock without result

### Expected result

Admin should compile without error

### Actual result

Invalid hook call error

#### Tinacms Package Versions

```
├── @tinacms/cli@0.61.9
├── tinacms@0.69.4
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |    Safari 15.5     |
| os      |     MacOS 12.4    |
| node    |    16.16     |
| npm     |    8.11.0     |

**Comment by pharmarin** [comment]
Solved by changing version of react@17.0.2 and react-dom@17.0.2

**Comment by jamespohalloran** [comment]
Closing, as EditProvider is no longer required
