### ISSUE TITLE
Let contributors know not to run `npm i` from within packages 

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#316]
It's not obvious that running `npm install` from within a package breaks the development environment.

There should be an mention of this fact and an explanation why. Something along the lines of:

> `tinacms` uses `lerna` to manage dependencies when developing locally. This allows the various packages to reference each other via symlinks. Running `npm install` from within a package replaces the symlinks with references to the packages in the npm registry.

**Comment by spbyrne** [comment]
I'll add that as a `tip` on [this page](http://tinacms.org/docs/contributing/setting-up).

**Comment by ncphillips** [comment]
Great! The README is where I was thinking
