### ISSUE TITLE
IndexFailedError on build.

### ISSUE THREAD

**Issue by gaurav712** [tinacms/tinacms#3185]
## Description

I have a NextJS project that I'm trying to build but it fails with the following error:

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/45332121/189987113-f4ef0ca4-22d8-41fd-8dda-ac3df9ff221a.png">

It worked fine until today. I tried reverting the commits but no luck!

### Steps to reproduce

Just a normal NextJS project. Can provide access to the code to reproduce if needed.

### Expected result

The project should build and generate the static pages.

### Actual result

The build fails with above error

#### Tinacms Package Versions

* @tinacms/cli@0.61.0
* tinacms@0.68.14

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |Brave|
| os      | MacOS 15.6.1 on Apple M1|
| node    |16.14.1|
| npm     |8.4.1|

**Comment by kldavis4** [comment]
@gaurav712 can you try [resetting the repository cache](https://tina.io/docs/tina-cloud/dashboard/projects/#reset-repository-cache)

**Comment by psirenny** [comment]
This error occurs for me on every pull request as well. Resetting webhooks and the repository cache temporarily fixes it.

**Comment by kldavis4** [comment]
@psirenny what is the client_id for your project?

**Comment by psirenny** [comment]
> @psirenny what is the client_id for your project?

**6abd004b-3133-4b3f-858f-960f453c8188**

**Comment by kldavis4** [comment]
@psirenny we released some fixes for issues with repository syncing this morning. Please reset the cache again and let us know if/when you see the error again.
