### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by RichDonnellan** [tinacms/tinacms#319]
## Description

There is a typo in the **Commands** section in `README.md`.

![Typo-in-README.md](https://user-images.githubusercontent.com/7773718/67043778-ac43ab80-f0df-11e9-96b2-b3441e6cf50c.png)

### Steps to reproduce

1. Scroll down to **Commands**
2. Read table headers

### Expected result

```diff
- Descriptiton
+ Description
```

### Actual result
```
Descriptiton
```

### Environment

N/A

**Comment by DirtyF** [comment]
fixed by #321
