### ISSUE TITLE
Hitting "/" in a code element (in the rich-text editor) breaks you out of the code element.

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3191]
## Description

On tina.io, we use the `code` element to show file paths. The problem is, when you hit `/`, it breaks you out of the code element.

<img width="437" alt="Screen Shot 2022-09-14 at 11 01 27 AM" src="https://user-images.githubusercontent.com/3323181/190175472-ab6e5cf1-4c09-4ae5-8a50-664c59ed27ef.png">

## Expected Results

Not 100% sure if this is expected behaviour or not, but without a raw-editor, it's tricky to work with. 

#### Tools

tinacms: 0.69.7

**Comment by jeffsee55** [comment]
That's due to the slash shortcut, I think when we're in a code element though we should just not enable that feature.
