### ISSUE TITLE
queries is not a function

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#3208]
Whenever the build step fails in some way, the `queries` used by the autogenerated client are null. There was [some work](https://github.com/tinacms/tinacms/pull/3151) done to improve the messaging in one specific case, but it still fail in other ways that aren't clear. Eg. from [Discord](https://discord.com/channels/835168149439643678/835172431836479508/1021433129724026981)

```
templates: [
            heroBlockSchema,
            featureBlockSchema,
            contentBlockSchema,
            testimonialBlockSchema,
            myCustomBlockSchema,
          ],

But it does not work with the following error messages. 

TypeError: queries is not a function
    at new TinaClient ([BASEPATH]/node_modules/tinacms/dist/client.js:46:22)
    at createClient ([BASEPATH]/node_modules/tinacms/dist/client.js:86:20)
    at eval (webpack-internal:///./.tina/generated/client.ts:11:81)
    at Object../.tina/generated/client.ts ([BASEPATH]/.next/server/pages/[filename].js:33:1)
    at webpack_require ([BASEPATH]/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///./pages/[filename].tsx:13:80)
    at Object../pages/[filename].tsx ([BASEPATH]/.next/server/pages/[filename].js:429:1)
    at webpack_require ([BASEPATH]/.next/server/webpack-runtime.js:33:42)
    at webpack_exec ([BASEPATH]/.next/server/pages/[filename].js:932:39)
    at [BASEPATH]/.next/server/pages/[filename].js:933:28 {
  page: '/[filename]'
}

I am using "@tinacms/cli": "^0.61.8", "tinacms": "^0.69.3”, with node version of 16.0.0 on MacOS Catalina v. 10.15.6.
```

I think in general, if the queries are null we should throw an explicit error during the build.

**Comment by jamespohalloran** [comment]
> There was https://github.com/tinacms/tinacms/pull/3151 done to improve the messaging in one specific case, but it still fail in other ways that aren't clear.

I think this is fixed in the latest.
`"@tinacms/cli": "^0.61.8",` was before the recent CLI error handling updates. 
The issue was that we were swallowing errors [here](https://github.com/tinacms/tinacms/pull/3151/files#diff-4c4b9a84370a0b70f261f82f43d6c1a266167c9b109f2c3641527f9e6813f377L71). In general, any error in build should bubble up and fail the build.

**Comment by jeffsee55** [comment]
I know we're surfacing errors now, but this error shouldn't occur at all

**Comment by jamespohalloran** [comment]
> I know we're surfacing errors now, but this error shouldn't occur at all

By surfacing the errors in tinacms build (and exiting the process), it shouldn't ever reach the point of running the script's subprocess, which should mean the user would never get the "queries is not a function" error (theoretically).

Does that make sense? Or do you know if you've seen it since?

**Comment by jamespohalloran** [comment]
Cool, closing for now. We can reopen if "queries is not a function" gets surfaced again
