### ISSUE TITLE
html comments in markdown quietly break rich-text field

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3213]
If you have a rich-text field with html comments like `<!-- TODO -->` in the body, using a rich-text field puts everything in block quotes.

The easy answer is "don't use html comments in markdown", however we don't catch this in our audit, and it's supported by ReactMarkdown.

**Comment by alekc** [comment]
I believe that there is a broader issue. 

I am migrating from forestry to TinaCMS (hugo based site), and my theme makes use of `<!-- more -->` comment to split pages. 

running `npx tinacms audit` brings in a lot of errors, all related to this
```
Error parsing file threat-detection-tools-for-containers.md from collection posts. 
    Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
Error parsing file use-terraform-http-data-source-to-wait-for-cluster-coming-up.md from collection posts. 
    Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
Error parsing file useful-debugging-tools-for-kubernetes.md from collection posts. 
    Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```
as a result, admin page is completely unusable atm

**Comment by BattleOfPlassey** [comment]
@alekc is there any fix or workaround you may have found for this?

**Comment by alekc** [comment]
Nope, I began to look to other solutions as consequence
