### ISSUE TITLE
Generated frags.gql missing body

### ISSUE THREAD

**Issue by mAAdhaTTah** [tinacms/tinacms#3246]
## Description

I honestly haven't dug into this error much yet, so I haven't figured out the actual cause, but I'm getting this error on my personal site.

### Steps to reproduce

1. Check out PR for my personal site [here](https://github.com/mAAdhaTTah/frontend/pull/739)
2. `nvm use 14 && npm ci && npx tinacms build`
3. See error

### Expected result

Builds correctly.

### Actual result

```
  Syntax Error: Expected "{", found "}".

~/frontend/.tina/__generated__/frags.gql:483:19
482 |                     ... on PageLandingBodyResumeEmbed
483 |                   }
    |                   ^
484 |                 }
GraphQLError: Syntax Error: Expected "{", found "}".
    at syntaxError (~/frontend/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.expectToken (~/frontend/node_modules/graphql/language/parser.js:1413:40)
    at Parser.many (~/frontend/node_modules/graphql/language/parser.js:1519:10)
    at Parser.parseSelectionSet (~/frontend/node_modules/graphql/language/parser.js:271:24)
    at Parser.parseFragment (~/frontend/node_modules/graphql/language/parser.js:379:26)
    at Parser.parseSelection (~/frontend/node_modules/graphql/language/parser.js:284:58)
    at Parser.many (~/frontend/node_modules/graphql/language/parser.js:1523:26)
    at Parser.parseSelectionSet (~/frontend/node_modules/graphql/language/parser.js:271:24)
    at Parser.parseField (~/frontend/node_modules/graphql/language/parser.js:312:68)
    at Parser.parseSelection (~/frontend/node_modules/graphql/language/parser.js:284:81)
```

Looks like the `frags.gql` doesn't build correctly.

#### Tinacms Package Versions

```text
├─┬ @tinacms/cli@0.61.20
│ ├─┬ @tinacms/app@0.0.19
│ │ ├─┬ @tinacms/scripts@0.51.1
│ ├─┬ @tinacms/datalayer@0.2.4
│ ├─┬ @tinacms/graphql@0.63.12
│ │ ├─┬ @tinacms/mdx@0.61.10
│ ├─┬ @tinacms/metrics@0.0.3
│ ├─┬ @tinacms/schema-tools@0.1.6
├─┬ react-tinacms-editor@0.53.26
│ ├─┬ @tinacms/toolkit@0.56.34
│ │ ├── @tinacms/sharedctx@0.1.1
├─┬ tinacms@0.69.14
│ ├── @tinacms/sharedctx@0.1.3
│ ├─┬ @tinacms/toolkit@0.57.10
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |     OSX    |
| node    |      14.17.6   |
| npm     |     6.14.15    |

**Comment by mAAdhaTTah** [comment]
Sharing here for posterity: The `PageLandingBodyResumeEmbed` is a template with a single reference field, so it shouldn't generate an empty body. Here's the definition:

```js
const resumeEmbedTemplate = {
  name: 'resumeEmbed',
  label: 'Resume Embed',
  fields: [
    {
      type: 'reference',
      name: 'resume',
      collections: ['resume'],
    },
  ],
};
```

**Comment by Phoenix-Alpha** [comment]
In your schema, menu and page collections have each other as a reference. So while generating graphql fragment, they resolve each other recursively.
To prevent this, tinacms has a option called `maxDepth`(which is 2 as default) and stops resolving reference if depth is greater than maxDepth.
https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/graphql/src/builder/index.ts#L565-L567
resumeEmbedTemplate, in your page collection, has resume as a reference. So when resolving `PageLandingBodyResumeEmbed`, if maxDepth >= 2, this template body will be empty and it will cause the missing body issue.

**Comment by mAAdhaTTah** [comment]
Ah, that makes sense, thank you! So I think I would just need a combo of that PR & update of the `referenceDepth` to make sure it returns what I need. Or reconsider my schema to eliminate the circular reference.
