### ISSUE TITLE
Rich text editor does not preserve line breaks when rendered with TinaMarkdown component

### ISSUE THREAD

**Issue by SethThoburn** [tinacms/tinacms#3273]
## Description

Rich text editor does not preserve line breaks when rendered with TinaMarkdown component.

### Steps to reproduce

Edit a MDX field in the rich text editor in the admin. Write two paragraphs separated by a blank line.

### Expected result

There is a blank line on the page rendered with the TinaMarkdown component.

### Actual result

There is no line between the paragraphs.

#### Tinacms Package Versions

```text
├── @tinacms/cli@0.61.22
├── tinacms@0.69.16
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |Safari   |
| os      |MacOS    |
| node    |v16.17.0 |
| yarn    |1.22.18  |

**Comment by jeffsee55** [comment]
Markdown doesn't really keep track of line breaks, you can use a newline to achieve that, there's a shortcut for it (shift+enter) which will insert `\` to denote line breaks

```markdown
This is a line\
\
This is a couple of line breaks down.
```

@SethThoburn I'll mark this as closed, but feel free to reopen in case you feel like this should be handled another way.

**Comment by SethThoburn** [comment]
I'm also not able to re-open issues that are closed by collaborators @jeffsee55. Thanks for taking time to look at this!

**Comment by jeffsee55** [comment]
We do deviate from some markdown specs in some places, but that portion of logic is pulled straight out of remark, which you can see here https://astexplorer.net/#/gist/ceaabd06342f219dcc1a5ea6de397211/f07c299587014c677affc2351ea537a895a25fae

> Because of that, a line break in the rich text editor should be preserved in the markdown output

I think it's doing what you suggest here, the editor doesn't see any slashes:

<img width="1324" alt="Screen Shot 2022-10-19 at 1 43 04 PM" src="https://user-images.githubusercontent.com/5414297/196800009-2226a7a3-7da9-41ee-a1ba-adc0d4158a2f.png">

The stored markdown:
```
This is a line\
And here is a soft line break

But this is a new paragraph
```

**Comment by jeffsee55** [comment]
Maybe we could insert an empty space when there's a new paragraph 🤔 

```
This is a line

&nbsp;

This is a few lines down
```

I'll play with that to see if it works, I understand what you're saying and yeah it'd be ideal to have it behave as if markdown wasn't involved for the end user.

**Comment by SethThoburn** [comment]
Great, thank you! I think the ideal behavior is that what the user sees in the editor matches what is rendered on the page.

**Comment by jeffsee55** [comment]
not stale
