### ISSUE TITLE
Using React in non-JSX/TSX file gives ambiguous runtime error

### ISSUE THREAD

**Issue by newash** [tinacms/tinacms#3283]
## Description

If I have a custom field definition (using React) in my `defineStaticConfig`  and start the "dev" process, the admin page is blank and have a `Uncaught ReferenceError: module is not defined` in the browser console.

I believe it's because the config is imported into the generated `out.js` from a separate URL that has no access to the compiled React, and React imported from the config cannot handle module imports.

I also tried to import `react/cjs/react.development.js` but then the two separate React engines were the problem, and of course that would not be a real solution anyway.

### Steps to reproduce

Import React either directly into `config.js` or through another file defining the custom component.
Run "tinacms dev".

### Expected result

The admin page to work.

### Actual result

The admin page is blank.

#### Tinacms Package Versions
```text
├── @tinacms/cli@0.61.20
├── tinacms@0.69.14
```

**Comment by jeffsee55** [comment]
Thanks @newash - can you try this again with the latest version of Tina?

**Comment by newash** [comment]
Now that's weird. During compilation:

```text
Error: Parse error @:32:18
    at parse$b (file:///........./node_modules/vite/dist/node/chunks/dep-4da11a5e.js:33682:355)
    at Object.transform (file:///........./node_modules/vite/dist/node/chunks/dep-4da11a5e.js:42891:27) {
  idx: 1180,
  pos: 1180,
  loc: {
    column: 17,
    file: '/........./.tina/config.js',
    line: 32
  },
  frame: '30:           <option key={d} value={d} />\n' +
    '31:         ))}\n' +
    '32:       </datalist>\n' +
    '                     ^\n' +
    '33:     </React.Fragment>\n' +
    '34:   );',
  id: '/........./.tina/config.js',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'vite:build-import-analysis',
  watchFiles: [ '/........./.tina/config.js' ]
}

Node.js v18.10.0
```
Tried to change the component JSX structure, removed the block it was complaining about, but then the same error was created for another line. This very same code was compiled without problems before.

```text
├── @tinacms/cli@0.61.24
├── tinacms@0.69.18
```

**Comment by logan-anderson** [comment]
@newash I am not able to reproduce this? do you mind posting a snippet of your schema so that I can try and reproduce. 

Also, can you check that at the top of your `config.tsx` (Needs to be .tsx or .js if you want to use jsx) you must add `import React from 'react'`

**Comment by newash** [comment]
Good news: I got a hunch this morning, if renaming my `config.js` to `config.jsx` would make a difference, and it did.
With the `jsx` extension now it compiles. 🎉 

Since in theory (== under regular circumstances) React JavaScript should also work from `.js` files, you might want to make a note in the docs...

And then the second good news: with the latest packeges
```text
├── @tinacms/cli@0.61.25
├── tinacms@0.69.19
```
the compiled `config.js` imports React from `/admin/node_modules/.vite/deps/react.js?v=17f9416c` and the admin page works.

Thanks for your effort guys!

**Comment by logan-anderson** [comment]
@newash Thanks! a docs update seems like a great idea. Thanks for your help.

**Comment by jamespohalloran** [comment]
@logan-anderson @jeffsee55 Do you think we could potentially catch this and show a better error for non jsx/tsx files using React?
