### ISSUE TITLE
Images nested in two levels of rich text are a render behind

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#3289]
When adding updating an image that is is a nested RichText component (a rich text in a custom element in rich text ), the image does not update right away but instead updates when something else is edited. 

See video 
https://www.loom.com/share/d693b090539e401382c15742be63d69a

**Comment by jeffsee55** [comment]
I had originally thought this was a React 18 bug in plate and reproduced something similar to this, but maybe there are separate issues since this happened in React 17, just posting here in case its helpful https://github.com/udecode/plate/issues/1519#issuecomment-1184933602
