### ISSUE TITLE
Create a gatsby-tinacms-yaml plugin

### ISSUE THREAD

**Issue by rchrdnsh** [tinacms/tinacms#329]
YAML is really nice for storing arrays of data in an easy to read and write format. It's what frontmatter is made of, after all.

I don't know, maybe it's already possible, I just did not see it on the roadmap, so I thought I'd bring it up :-)

**Comment by ncphillips** [comment]
Awesome idea! A `gatsby-tinacms-yaml` plugin would be great. If you’re interested in giving it a shot, checkout the json plugin.

**Comment by rchrdnsh** [comment]
I would have no idea how, but i'll take a look anyway :-)

**Comment by johnhorsema** [comment]
Can follow this repo for inspiration: https://github.com/yaml/yaml.js-standalone
