### ISSUE TITLE
Custom shortcode saved back in JSX syntax

### ISSUE THREAD

**Issue by newash** [tinacms/tinacms#3291]
## Description

With a static setup I defined a custom shortcode as described in https://tina.io/docs/reference/types/rich-text/#custom-shortcode-syntax.  Existing Markdown file is loaded in the editor as expected, but when saving it is saved in JSX syntax.

I did some digging in your code, and I can see the shortcode is transformed into JSX first, and there is code also for the back-transformation, but the output is still JSX somehow.

### Steps to reproduce

`config.js` is something like:
```js
export default defineStaticConfig({
  ...
  schema: {
    collections: [
      {
        ...
        fields: [
          {
            name: "body", label: "Body", type: "rich-text", isBody: true, templates: [
              {
                name: "youtube",
                label: "Video",
                match: {
                  start: "{%",
                  end: "%}"
                },
                fields: [{
                  name: "text",
                  label: "Youtube URL",
                  type: "string",
                }]
              }
            ]
          },
        ]
      }
    ]
  }
});
```

I add the custom component to the body in the editor and save the file.

### Expected result

Output to be `{% youtube text="foobar" %}`

### Actual result

Output is
```
<youtube>
  `foobar`
</youtube>
```

#### Tinacms Package Versions
```text
├── @tinacms/cli@0.61.24
├── tinacms@0.69.18
```

**Comment by logan-anderson** [comment]
Just looking into this now and I am not able to reproduce on the latest version of tinacms and @tinacms/cli. Mind trying to update?

See loom video: https://www.loom.com/share/f9326261144e41688e462bb713ab5783

**Comment by newash** [comment]
Hey @logan-anderson, thank you so much for the video. No idea what's happening on my side.

Now with the latest packages:
```text
├── @tinacms/cli@0.61.25
├── tinacms@0.69.19
```

I recreated an identical template config as in your video in my `config.jsx`:

```js
{
  name: "body", label: "Body", type: "rich-text", isBody: true, templates: [
    {
      name: "WarningCallout",
      label: "WarningCallout",
      match: {
        start: "{%",
        end: "%}"
      },
      fields: [{
        name: "text",
        label: "Text",
        type: "string",
        required: true,
        ui: {
          component: "textarea",
        }
      }]
    }
  ]
},
```
opened a MD without the tag in the admin editor,
added WarningCallout,
added some text into it,
saved.

This was the result:
```text
<WarningCallout>
  `foobar`
</WarningCallout>
```

Any suggestion where to put a breakpoint or a `console.log` to see where it goes wrong, why is my setup differs from yours?

**Comment by logan-anderson** [comment]
@newash apologies. Upon further investigation, I am able to reproduce the issue in the monorepo (I must have been on an older version of tinacms). I will look into this.

**Comment by newash** [comment]
@logan-anderson  I hate to say it, but with the above config the output now is:
```text
{% foobar %}
```

Tina versions:
```text
├── @tinacms/cli@0.61.27
├── tinacms@0.69.22
```

**Comment by hithismani** [comment]
I am having the same issue as @newash. The output no longer matches the format shared, it's overwriting the whole syntax and only placing the value without a key either.

Output for the same "[WarningCallout](https://tina.io/docs/reference/types/rich-text/#custom-shortcode-syntax)" example is now showing 

`{{my input text}}`

instead of 

`{{WarningCallout text="my input text"}}`

**Comment by newash** [comment]
…however instead of the format in the docs, Tina devs could also consider matching sortcodes for the SSGs.

I use 11ty, and my life would be so much easier with any of the formats described at https://www.11ty.dev/docs/shortcodes/

(11ty supports several formats, but not the one in the Tina docs.)

**Comment by newash** [comment]
created a separate ticket; #3400
