### ISSUE TITLE
Provide Feedback on package sizes in PRs

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#33]
## Problem

NPM package bloat is a real possibility. We don't want packages to get too big, especially from accidentally building with a bunch of dependencies. 

## Possible Solution

1. Use a tool (e.g. [danger](https://danger.systems/js/)) to add a comment to PRs containing a table displaying each package and it's size in kb.

**Comment by NickCis** [comment]
I think it could be implemented what [material-ui does for prs](https://github.com/mui-org/material-ui/pulls). Under the hood they are using _danger_.

**Comment by ncphillips** [comment]
Awesome! Yes we have a [dangerfile](https://github.com/tinacms/tinacms/blob/master/dangerfile.ts) as well.

**Comment by NickCis** [comment]
Sorry for the late reply, I've been busy, I've found a GitHub action that reports compressed file changes. It is called [compressed size action](https://github.com/marketplace/actions/compressed-size-action). Do you think it fits Tina's needs?

**Comment by ncphillips** [comment]
That's interesting! It might do the job. I'll check it out later on, thanks a lot 👍

**Comment by kendallstrautman** [comment]
Pretty sure this was implemented. Feel free to reopen if not!
