### ISSUE TITLE
Svelte / Svelte-Kit support ?

### ISSUE THREAD

**Issue by 0gust1** [tinacms/tinacms#331]
## Summary

Like Next.js or Nuxt, Sapper is a great meta boilerplate to manage a static website engine.
I could test a forestry.io integration with a sapper instance, and it works like a charm !

### Motivation

Being able to support Sapper (or equivalent projects).  If I get enough time to have a good understanding of tinacms (looking at vue/Nuxt support could give me some hints), I could help.

**Comment by ncphillips** [comment]
Thanks for the request @0gust1 ! I have been meaning to look into Svelte so this is a good treason to 🙂

**Comment by leejoramo-d51** [comment]
I am on a team that is currently evaluating Svelte, and are very close to deciding to adopt it for our future projects. Separately, I have used Hugo and Forestry.io for several sites. I would enjoy having these tools available to Svelte. I will follow this issue and be ready to lend a hand.

**Comment by panakour** [comment]
Also Svelte would be implement within the hugo https://github.com/gohugoio/hugo/issues/5894 so as to be able for us who using hugo to use tinacms

**Comment by remisharrock** [comment]
> I could test a forestry.io integration with a sapper instance, and it works like a charm !

@0gust1 could you give some input , I have a sapper instance and would love to test it with tina ?
thanks

**Comment by 0gust1** [comment]
For forestry.io integration (and probably for tinacms integration), you have to slightly modify the rollup config to add a preprocess step to svelte component compilation. For the preprocess, I used MDsvex (https://github.com/pngwn/MDsveX).


Full rollup config here : https://raw.githubusercontent.com/0gust1/merveilles-zine/master/rollup.config.js 

You also have to adjust sapper launch script in `package.json` : 
```
  "scripts": {
    "dev": "sapper dev --ext '.svelte .md'",
    "build": "sapper build --ext '.svelte .md' --legacy",
    "export": "sapper export --ext '.svelte .md' --legacy",
    "start": "node __sapper__/build",
    "cy:run": "cypress run",
    "cy:open": "cypress open",
    "test": "run-p --race dev cy:run"
  }
```

And voilà, your sapper is processing (augmented) markdown.

**Comment by kenjonespizza** [comment]
TinaCMS looks great!!! But I have not used tried it because I don't often choose React.  Svelte support would be 🔥.

🙂

**Comment by jordankaerim** [comment]
Svelte Kit support would be great! I'm reading through the source code and would seriously be interested in helping getting this to work with Svelte.

**Comment by DirtyF** [comment]
Tina core still depends on React in a few places, so I'm not sure if it's ready to be ported to other frameworks at the moment.

For people interesting to start working on porting some packages to another framework, the core team don't have a lot of bandwidth now because we have a lot on our hands at the moment with the GraphQL API for the backend and working on features like branching, but feel free to drop any questions here or even open a PR to trigger specific discussions on what's need to be done in order to move Tina closer to being framework agnostic. 🙏

**Comment by 0gust1** [comment]
RIP @DirtyF 😢

**Comment by mmm8955405** [comment]
You can close this issue directly without any explanation or documentation. Obviously, the attitude is rubbish

**Comment by jamespohalloran** [comment]
> You can close this issue directly without any explanation or documentation. Obviously, the attitude is rubbish

We use stalebot to close stale issues, as noted in the comment above. We have also moved feature requests to our discussions, to keep our active issues manageable. If you have questions about issues, you can always just ask.

In terms of this feature request, we're actively working towards non-React support. 
More information can be found about that here: https://tina.io/guides/tinacms/non-react-based-ssg/guide/

**Comment by mmm8955405** [comment]
> close

This is a document without any technical help. There has been little change since last year. Why don't you just say that tina can't support Svete. Why do I need tina for management when using hugo? Hugo has its own way and plug-in

**Comment by mmm8955405** [comment]
> > You can close this issue directly without any explanation or documentation. Obviously, the attitude is rubbish
> 
> We use stalebot to close stale issues, as noted in the comment above. We have also moved feature requests to our discussions, to keep our active issues manageable. If you have questions about issues, you can always just ask.
> 
> In terms of this feature request, we're actively working towards non-React support. More information can be found about that here: https://tina.io/guides/tinacms/non-react-based-ssg/guide/

**Comment by jamespohalloran** [comment]
> This is a document without any technical help. There has been little change since last year. Why don't you just say that tina can't support Svete. Why do I need tina for management when using hugo? Hugo has its own way and plug-in

@mmm8955405 There has been lots of work done the last 6 months to make Tina work with non-React frameworks. Svelte should work with the basic editor by following this guide: https://tina.io/docs/frameworks/other/
Visual editing on the other hand will be looked at on a framework-by-framework basis, and doesn't currently have a timeline for Svelte.

**Comment by johannesmutter** [comment]
Tina CMS can be used with SvelteKit, however visual editing doesn't work, but you can still edit content through the regular backend. For a lightweight CMS with visual editing and SvelteKit support have a look at [Editable.website](https://github.com/michael/editable-website)

### Setup Guide to use Tina CMS with SvelteKit: 
1. Follow this guide: https://tina.io/docs/frameworks/other/
2. When prompted for the "public assets directory", type `static`.
3. You need to use the latest node version `20.3.1`. With older versions you'll get the error _"TypeError: Cannot redefine property: crypto"_
3.1. You can change node versions with the `nvm` module: `nvm install 20.3.1` and then `nvm use 20.3.1`
5. Lastly update your `package.json` scripts commands for dev and build:
```JSONC
"scripts": {
  "dev": "tinacms dev -c \"vite dev\"",
  "build": "tinacms build && vite build",
  //...
}
```
5. Navigate to `http://localhost:5173/admin/index.html` for TinaCMS and `http://localhost:5173/` for your SvelteKit App

**Comment by mikekok** [comment]
Any updates on official Sveltekit support (including visual editing)?

**Comment by justingolden21** [comment]
> Tina CMS can be used with SvelteKit, however visual editing doesn't work, but you can still edit content through the regular backend. For a lightweight CMS with visual editing and SvelteKit support have a look at [Editable.website](https://github.com/michael/editable-website)

https://github.com/michael/editable-website and https://editable.website/ both don't say anything at all about "tina."

I was also wondering if tina will ever support svelte/svelte kit. React sucks and tina seems amazing, but if I'm forced to use react I'd just use decap or another CMS instead and keep using svelte.

--

@jamespohalloran this ticket was opened nearly 5 years ago and there's definitely some interest in svelte support. I was wondering if you guys are still considering supporting it. It's gotten fairly popular recently according to all metrics. Thanks!
