### ISSUE TITLE
Can not save when having an image followed by text

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#3310]
## Description

When adding an image at the top of the rich text field followed by a piece of text the document is unable to be saved.

### Steps to reproduce

1. add an image to the top of a rich text field
2. click save
3. refresh
4. add some text
5. click save
6. see Error

Here is a video: https://www.loom.com/share/91cb1a855d43467a9782df57f14205dd

### Expected result

Should be able to save

### Actual result

Error

### Environment
Mono repo

**Comment by jeffsee55** [comment]
The fix for this needed to be reverted so reopening.

**Comment by jeffsee55** [comment]
Not stale

**Comment by kldavis4** [comment]
Just did a test of this in the basic-iframe example and wasn't able to replicate it. Can't seem to add any text as a child of the image (which is what the above loom seems to be doing). This is the best I could do (which doesn't break):
```
{
  "title": "This is a title",
  "body": {
    "type": "root",
    "children": [
      {
        "type": "p",
        "children": [
          {
            "text": ""
          },
          {
            "type": "img",
            "url": "/uploads/llama-2.avif",
            "alt": "sdfsdf",
            "caption": "sadfdsf",
            "children": [
              {
                "type": "text",
                "text": ""
              }
            ],
            "id": 1689367977164
          },
          {
            "type": "text",
            "text": "sdfsdfsdfsf"
          }
        ],
        "id": 1689367977164
      }
    ]
  },
  "posts": null,
  "__typename": "Post"
}
```
Seems strange that the img type even has children, though (to my ignorant self :) )
