### ISSUE TITLE
Switch branches from the sidebar

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#332]
## Summary

The user should be able to switch branches from the sidebar. 

This can be split into several sub-tasks:

1. Display the current branch
1. Switch to an existing local branch
1. Switch to an existing remote branch
1. Create a new branch

### Motivation

Branching is a powerful feature for writing code. It let's us test new things without worrying about breaking things for other people. It also allows us to have an editorial workflow whereby code is only _really_ added once it's been reviewed by other people. 

Creating an interface for branch management will bring those massive benefits to content writers, as well as code writers.

**Comment by ncphillips** [comment]
This will most likely be implemented as a [`screen-plugin`](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/plugins/screens/index.tsx). We haven't made many examples in that area, but more are certainly to come.

There will almost certainly be _multiple versions of branch switching_, as the mechanism for switching branches locally will be very different from switching branches in Tina Teams.

**Comment by kendallstrautman** [comment]
Implemented from the Toolbar via #1065
