### ISSUE TITLE
Missing property on second render inside iframe

### ISSUE THREAD

**Issue by genox** [tinacms/tinacms#3358]
## Description

This might very well be caused because I am trying to do something that isn't supposed to be done like that - I am not sure.

Goal: Use a template to render columns dynamically inside a grid based on the consecutive appearance of a template

The collection definition:

```
export const collectionPage: TinaCloudCollection<false> = {
  label: 'Pages',
  name: 'page',
  path: 'content/page',
  format: 'mdx',
  ui: {
    filename: {
      readonly: false,
      slugify: (values) => {
        return isNew(`${values?.locale}/${values?.slug}`);
      },
    },
  },
  fields: [
    {
      type: 'string',
      label: 'Title',
      name: 'title',
      required: true,
    },
    {
      name: 'slug',
      type: 'string',
      label: 'Slug',
      ui: {
        format: (val?: string) => getSlug(val || ''),
      },
      required: true,
    },
    {
      type: 'string',
      label: 'Locale',
      name: 'locale',
      options: [
        { value: 'de', label: 'German' },
        { value: 'en', label: 'English' },
      ],
      required: true,
    },
    {
      type: 'string',
      label: 'Summary',
      name: 'description',
      required: true,
    },
    {
      type: 'string',
      label: 'Name in lists (e.g. navigations, listviews)',
      name: 'listItemName',
      required: true,
    },
    {
      type: 'object',
      list: true,
      name: 'blocks',
      label: 'Sections',
      templates: [
        {
          name: 'content',
          label: 'Content',
          fields: [
            {
              type: 'rich-text',
              isBody: true,
              label: 'Body',
              name: 'body',
              templates: [buttonTemplate],
            },
          ],
        },
        {
          name: 'column',
          label: 'Column',
          fields: [
            {
              type: 'string',
              label: 'Fractional width',
              name: 'width',
              options: [
                { value: '2fr', label: '2 Fractions' },
                { value: '1fr', label: '1 Fraction' },
                { value: '0.5fr', label: '0.5 Fractions' },
                { value: 'auto', label: 'Remainder' },
              ],
              required: true,
            },
            {
              type: 'object',
              list: true,
              name: 'blocks',
              label: 'Sections',
              templates: [
                {
                  name: 'content',
                  label: 'Content',
                  fields: [
                    {
                      type: 'rich-text',
                      isBody: true,
                      label: 'Body',
                      name: 'body',
                      templates: [buttonTemplate],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};

```

I added a content item and filled it with dummy content and wrote a component to render the content recursively which works fine when viewing content in nextjs. As soon as I switch into iframe based edit mode, I experience the following issue:

1) first render pass on server succeeds
2) client is hydrated with the correct layout
3) I assume `useTina()` is triggering an update with changed content in edit mode, causing another render pass
4) all columns blink out of existence since I don't render invalid objects (based on the consumer perspective)

When I disable my checks, I get an error that the `blocks` property is missing on `column`.

So on first render, everything works. As soon as the `_template` property exists, the expected `blocks` array is not present anymore.

Should templates not be nested or is this an issue/bug?

I notice that I have some `name` properties in my schema definition that overlap. Could this cause the issue?

**Comment by logan-anderson** [comment]
@jeffsee55 is this fixed by https://github.com/tinacms/tinacms/pull/3360 ?

**Comment by jeffsee55** [comment]
@logan-anderson it should, @genox it may be fixed if you try the tagged release `yarn add @tinacms/cli@simplify-formify-resolve`.

Let us know if you get a chance to try it and if it helps!

**Comment by genox** [comment]
> @logan-anderson it should, @genox it may be fixed if you try the tagged release `yarn add @tinacms/cli@simplify-formify-resolve`.
> 
> Let us know if you get a chance to try it and if it helps!

Gave it a spin just now, the issue is fixed now. Thank you! :)

**Comment by jeffsee55** [comment]
Thanks @genox - we've just merged that fix so will deploy it either today or tomorrow!
