### ISSUE TITLE
Creating a post with a filename that already exists doesn't handle error gracefully

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3362]
## Description

When creating a post with a filename that already exists, creation fails without showing an error. It also disables the flename generation, and the ability to save

https://www.loom.com/share/9cb22b7c4bc84b13abab5123aac49a97

### Expected result

Error message should appear. User should be able to correct the error and re-save.

#### Tinacms Package Versions

├── @tinacms/cli@0.62.0
├── tinacms@0.70.0

**Comment by hemalshah28** [comment]
Can I work on this issue?
