### ISSUE TITLE
Documents with missing sortBy fields don't show up in the list

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3363]
## Description

Documents with missing sortBy fields don't show up in the collection list
https://www.loom.com/share/244853da315e4f959ebf371d662192dd

## Expected result

They should appear at the start, or end of the list (depending on sort order)

## Versions

Tinacms Package Versions
├── @tinacms/cli@0.62.0
├── tinacms@0.70.0

**Comment by jamespohalloran** [comment]
> @jamespohalloran This was the behaviour we made on purpose because we didn't want to place a default value on every field and wanted to leave that up to the user.

Why do the documents need a default? I don't think most editors will think to update the sort to see all the documents as-is.

**Comment by kldavis4** [comment]
The sorted lists are based on an index. The index is built based on a field
(or fields) in a document. If you have a document that has a field foo,
only the documents with that field present will be included when sorting by
that field. The only way for documents to get included, is to set a default
value for that field when building the index, which we explicitly decided
not to do.

**Comment by jamespohalloran** [comment]
Gotcha, even if we could display a label somewhere that certain documents with missing {{sortBy}} may be excluded from this list, that would help.

**Comment by kldavis4** [comment]
I don't think you could display that labelly unconditionally unless you
query the full list (with default filename sort) to get the length, and
then compare the full sortedBy list. IMO the correct solution here is to
provide a default value so you always get your full document list

**Comment by kldavis4** [comment]
I think it would probably have to be a developer configurable default,
since it would need to vary depending on the type of the field

**Comment by jamespohalloran** [comment]
> @jamespohalloran For some background context I believe we chose this behaviour because other solutions. For example [firebase](https://firebase.google.com/docs/firestore/query-data/order-limit-data#limitations) also filter out of the order by field is null.

I think there's a difference between an API behaviour (which has reference documentation) and the editor UI/UX.

I don't want to have to go out of our way too much to fix this medium UX issue, but what about something like this?

<img width="864" alt="Screen Shot 2022-11-02 at 1 58 50 PM" src="https://user-images.githubusercontent.com/3323181/199553517-4ec16fdc-b843-4f8c-a9af-5ce90b11b94c.png">
