### ISSUE TITLE
Can not save when having an empty field

### ISSUE THREAD

**Issue by celadaalejandro-kuuli** [tinacms/tinacms#3369]
## Description
Can not save when having an empty field
### Steps to reproduce

1. Create a new STRING type in the schema.
2. Include the FileName and left empty the new string.
3. Save
4. Getting error

### Expected result

What should happen? Save

### Actual result

What actually happened? Getting an error
![image](https://user-images.githubusercontent.com/113904644/199731019-02f0f6b2-c6f2-4986-9d8b-294541007b79.png)

![image](https://user-images.githubusercontent.com/113904644/199731111-038dfbef-9111-45a8-a804-5ad80f07a0e8.png)

#### Tinacms Package Versions
  },
  "devDependencies": {
    **"@tinacms/cli": "0.61.22",**
    "@types/js-cookie": "^3.0.0",
    "@types/node": "^16.11.7",
    "@types/react": "^17.0.35",
    "@types/styled-components": "^5.1.15",
    "@typescript-eslint/eslint-plugin": "^5.20.0",
    "@typescript-eslint/parser": "^5.20.0",
    "autoprefixer": "^10.4.0",
    "eslint": "^8.13.0",
    "postcss": "^8.3.11",
    "postcss-import": "^14.0.2",
    "postcss-nesting": "^10.1.0",
    "tailwindcss": "^2.2.19"
  },
  "dependencies": {
    "@headlessui/react": "^1.4.1",
    "@tailwindcss/line-clamp": "^0.4.2",
    "@tailwindcss/typography": "^0.4.1",
    "date-fns": "^2.23.0",
    "html-to-text": "^8.2.1",
    "next": "^12.0.4",
    "next-sitemap": "^3.1.24",
    "next-svgr": "^0.0.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-icons": "^4.2.0",
    "react-is": "^17.0.2",
    "styled-components": "^5.1.3",
    "styled-jsx": "^3.2.5",
    **"tinacms": "0.69.16",**
    "typescript": "^4.5.2",
    "vanilla-cookieconsent": "^2.8.6"
  },

**Comment by jamespohalloran** [comment]
> @celadaalejandro-kuuli are you using `{isTitle: true}` ?

Like @logan-anderson suggests, it sounds like the issue might be that your field has isTitle, but not isRequired. There was a recent update where your schema validation will fail if that's the case.

<img width="568" alt="Screen Shot 2022-11-16 at 10 34 06 AM" src="https://user-images.githubusercontent.com/3323181/202208931-342498ae-0733-479d-975c-a8df4a57b7aa.png">

If on latest you still this issue, let us know and we can re-open.
