### ISSUE TITLE
Docker Official Image

### ISSUE THREAD

**Issue by rafagarciac** [tinacms/tinacms#337]
## Summary

Hi all! It would be awesome create a Dockerfile in order to deploy this application with Docker !
- [ ] Write `Dockerfile` and `docker-compose.yaml`

### Basic example

Here is an example to dockerize this application and create the image ;)
https://itnext.io/dockerize-a-typescript-app-in-15-mins-a0e8c1e904b3 

### Motivation

Since, this is a distributed front-end application it's going to be more easy to deploy in local without any error dependency by final user ! 
Happy coding ! :cupid:

**Comment by sergioarroyop** [comment]
Hey buddies! I'd like to take this issue :)

**Comment by ncphillips** [comment]
Thanks @rafagarciac! 

I think there's a bit of a misunderstanding around Tina's structure. Tinacms is not an application, it's a set of npm packages which you import into your website's source code. The idea of running it locally without worrying about dependencies is amazing, however that would have to be implemented by the person developing the website. For example, you might create a new gatsby site from the [tinacms starter](https://github.com/tinacms/gatsby-starter-tinacms) and create a Docker image for that.

@sergioarroyop if you were going to dig into this, I would think of it as research for a tutorial/blog-post rather then an official tinacms image

Let me know if I'm misunderstanding!

**Comment by rafagarciac** [comment]
Hello @ncphillips ! Yes it was a misunderstanding then... :face_with_head_bandage: anyways we could create a Dockerfile into [TinaCMS Starter](https://github.com/tinacms/gatsby-starter-tinacms) to provide a stable deploy version.
Thanks for the information, and @sergioarroyop and I will work on this !

**Comment by ncphillips** [comment]
That would be amazing! 😄
