### ISSUE TITLE
Adding TinaCMS to a static blog results in error

### ISSUE THREAD

**Issue by redzimskidev** [tinacms/tinacms#3385]
## Description

Running ` npx @tinacms/cli@latest init --static` as per the documentation results in the following error:

```
npx @tinacms/cli@latest init --static
Need to install the following packages:
  @tinacms/cli@0.62.3
Ok to proceed? (y) y
error: unknown option '--static'
```

### Steps to reproduce

Run ` npx @tinacms/cli@latest init --static`

### Expected result

Prompts for package manager, etc.

### Actual result

```
npx @tinacms/cli@latest init --static
Need to install the following packages:
  @tinacms/cli@0.62.3
Ok to proceed? (y) y
error: unknown option '--static'
```

### Environment

I've tried running latest and 62.1, had to go back to 0.61.20 (I had it working wth this verison in a different repo) to get it to work.

**Comment by HFulcher** [comment]
I'm having this problem as well, manually choosing 0.61.20 avoids the issue for now

**Comment by HFulcher** [comment]
Did some digging and the latest version no longer needs the `--static` flag. Simply run `npx @tinacms/cli@latest init` and it will allow you to specify a non-nextjs implementation as the first option.

**Comment by jamespohalloran** [comment]
Thanks for logging this! Just updated the docs on tina.io to remove that --static flag
