### ISSUE TITLE
Document the tinacms release process

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#339]
This issue is about the release process for tinacms packages and how it will be communicated

## Current Understanding
There are 3 main branches:

- **master:** The bleeding edge of tinacms
- **next:** A preview of the next release
- **latest:** The current stable release

The flow of changes therefore looks like:

> `fix-some-bug` => `master` => `next` => `latest`

Tina has a 2 week release process: 

* Day 1: A new `next` branch is created from `master`.
* Week 1: `next` is kept up to date with `master` with frequent pre-releases
* Week 2: `next` is frozen for new development but critical bug fixes can be cherry picked.
* Day 14: `next` is released to npm, and then merged into `latest`

## Questions

* Where do we put this information? (e.g. README, CONTRIBUTING, tinacms.org, etc.)

**Comment by DirtyF** [comment]
This can go in the README.

**Comment by jamespohalloran** [comment]
Awesome! Yeah, README makes sense to me for now.
