### ISSUE TITLE
Repo based media: wrong url on preview image

### ISSUE THREAD

**Issue by genox** [tinacms/tinacms#3391]
## Description

Using repo based media, on localhost. Added an image in the sidebar with drag and drop. Image is uploaded in the correct folder but the link to the image is missing the upload folder segment, i.e. the `src` points to `image.jpg` instead of `/uploads/image.jpg`.

The image field:

```
{
  type: 'image',
  label: 'Image',
  name: 'src',
}
```

The image is loaded correctly within the Media Manager, the src includes the configured `uploads` folder.

### Steps to reproduce

On localhost: Add an image field to a document, upload an image using drag and drop in the editor sidebar.

### Expected result

The preview image should be displayed, the path should be correct and point to the right asset.

I noticed that the response from the API does not include a path but just the filename. Is this intended behaviour? Shouldn't the API give me a path to an image based on the current environment it is running in? For example, an absolute URL to the image in the tina.io asset cache when running in production mode and a relative path when running locally?

### Actual result

The image is missing (404)

#### Tinacms Package Versions

latest

**Comment by breizh24** [comment]
Hi, I looked into this issue, and the problem is that the image `src` is missing the leading slash (as you can see from the screenshot), so the `src` url is relative to the page and not to the root of the server.

![image](https://user-images.githubusercontent.com/38522984/201495158-2741864c-638a-46d3-872e-84806c5504f0.png)

@jeffsee55 a possible solution could be to check inside the `usePreviewSrc` hook if the `tmpSrc` has the leading slash, if not We add it. If it's ok for you I can open a PR.

**Comment by genox** [comment]
> Hi, I looked into this issue, and the problem is that the image `src` is missing the leading slash (as you can see from the screenshot), so the `src` url is relative to the page and not to the root of the server.

In case of repo based media and the default config lined out in the documentation, the path to the uploaded resource should include the folder (so, `/uploads/image.jpg`), no? There shouldn't be any other necessary steps?

https://tina.io/docs/reference/media/repo-based/

On a tangent: There is no mention of how the resource looks like when requested via api, wether it is a filename or an absolute or relative url to an asset. When I gave it a spin I just got a filename running it on localhost. So I assume I need to build urls myself. But then, how do I build a url to the asset on tina.io? Or does tina magically redirect request on the upload folder in production?

**Comment by breizh24** [comment]
I tested it with the tina cloud starter on local, and I noticed that the files that are uploaded with drag and drop are placed in the root folder and not in the upload one.

In fact after adding the leading slash to it, inside the tina code, I was able to correctly see the image.

So maybe there could be also another problem with the file not being saved in the upload folder.

**Comment by breizh24** [comment]
So I did another check on this, setting the `mediaRoot` to be `uploads` inside the tina-cloud-starter example, and yes I can confirm that the image src comes without the folder.

**Comment by Azunyan1111** [comment]
This is a temporary solution with no sense.
https://github.com/tinacms/tinacms/blob/3c89a11de96931b8b3d42d4af1ae51739ee20439/packages/%40tinacms/toolkit/src/packages/core/media.ts#L219

Change the url here from const to let and put the following change under it
```
url = "/uploads/" + url
```

This is a very bad example, but it worked in my environment (I don't know anything about this project, so please forgive the part where I didn't use config)
