### ISSUE TITLE
next-tinacms-cloudinary: fix wrong accept property on input

### ISSUE THREAD

**Issue by Perni1984** [tinacms/tinacms#3395]
Hi,

FYI today we noticed that in `next-tinacms-cloudinary` currently the accept property for the upload input contains the following string:

`"text/*,  application/*, image/*"`

The spaces included in the string lead to the arbitrary situation that when you click the upload button in the media manager (in Windows and on MacOSX) it is interpreted as `"text/*"` - basically only allowing text files to be uploaded.

We used patch-package to circumvent this behavior (as we did not find out how to overwrite this in the tina config). As we don't have the tina project checked out locally, I am submitting the below patch file so somebody can make a "correct" PR for it.
    

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/next-tinacms-cloudinary/dist/index.js b/node_modules/next-tinacms-cloudinary/dist/index.js
index ef6e7fe..a520960 100644
--- a/node_modules/next-tinacms-cloudinary/dist/index.js
+++ b/node_modules/next-tinacms-cloudinary/dist/index.js
@@ -52,7 +52,7 @@
       this.fetchFunction = (input, init) => {
         return fetch(input, init);
       };
-      this.accept = "text/*,  application/*, image/*";
+      this.accept = "text/*,application/*,image/*";
       this.previewSrc = (publicId) => {
         if (typeof publicId === "string")
           return publicId;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by logan-anderson** [comment]
@Perni1984 Thanks for the report, just pushed up a fix.
