### ISSUE TITLE
Markdown parsing regression: Image inside a link

### ISSUE THREAD

**Issue by L-A** [tinacms/tinacms#3396]
## Description

Up to `0.70`, Tina correctly parsed the following markdown (a link with a single image as content):

```markdown
[![My image](http://placekitten.com/200/300)](https://example.com/)
```
<img width="386" alt="CleanShot 2022-11-10 at 15 55 51@2x" src="https://user-images.githubusercontent.com/861964/201204032-229b623c-9fc2-4999-8427-58556a87a9be.png">

In both `0.70.2` and `1.0.0`, content that contains the above line is serialized as `invalid_markdown` and displayed as such:

<img width="656" alt="CleanShot 2022-11-10 at 15 47 02@2x" src="https://user-images.githubusercontent.com/861964/201202554-a5fd00d3-9a7b-42c0-8da3-844031aa6bc4.png">

## Steps to reproduce

The above is from the barebones `1.0.0` starter. Here's how to get the same result:

- ` npx create-tina-app@latest` - Follow as usual, select the Barebones starter.
- Append the following in `content/page/home.mdx`:
  - ```
      [![My image](http://placekitten.com/200/300)](https://example.com/)
      ```
- `yarn dev` and visit the home page

### Expected result

The AST contains a `link` element under which is an `image`, and `<TinaMarkdown />` displays it correctly.

### Actual result

The AST contains a single object of type `invalid_markdown`, with the whole of the `rich-text` field as its value.

#### Tinacms Package Versions
<!--
Run the following command to get the list of tinacms-package versions in your node_modules:

    npm ls | grep tinacms | grep -v deduped
-->

```text
├── @tinacms/cli@1.0.0
└── tinacms@1.0.0
```

**Comment by logan-anderson** [comment]
Thanks for the report @L-A I am assuming this is related to #3334. Taking a look now.

cc @jeffsee55

**Comment by logan-anderson** [comment]
@L-A It looks like this Syntax should work `![My image](http://placekitten.com/200/300 "https://example.com/")`. We will look at a fix for the other one ASAP. Sorry for the inconvenience in the mean time.

**Comment by jipiboily** [comment]
@logan-anderson did you folks have some time to look at it? Just wondering if it's likely to be fixed soon-ish :)

**Comment by jipiboily** [comment]
Perfect, thanks! Hope the conf was both good and fun :)

**Comment by logan-anderson** [comment]
@jipiboily This will be fixed in the next release

**Comment by jipiboily** [comment]
Perfect; thanks!
