### ISSUE TITLE
Support shortcode syntax for the target SSGs (Hugo, 11ty)

### ISSUE THREAD

**Issue by newash** [tinacms/tinacms#3400]
## Description

This is partly a bug report but also a feature request.
I elaborate below.

### Steps to reproduce
1. you name your shortcode, like `WarningCallout`
2. you pick a starting character sequence, like `{%`
3. you also pick an ending sequence, like `%}`
4. then you define a single field that must be named `text`, that is a string

### Expected result
The docs says it is gonna be in the Markdown like `{% WarningCallout text="value of the field" %}`.

### Actual result
It is `{% value of the field %}`.

Beside the docs being incorrect, there are also some non-obvious issues with the implemented behaviour.
1. It's not possible to define multiple shortcodes with the same starting or ending sequence with the ending sequence being the bigger issue. It's possible to hack the setup with `{% WarningCallout` and `{% OtherCallout` as the starters (expecting `{% WarningCallout value of the field %}` and `{% OtherCallout value of the field %}`) but using the same ending will **CRASH** Tina.
2. Even the different starters are a hack.
3. I'm not sure about other SSG frameworks but the 11ty I use [supports 3 different template engines built-in](https://www.11ty.dev/docs/shortcodes/), and neither can understand the `{% WarningCallout text="value of the field" %}` format. And those are not some weird template engines but pretty standard ones, like Handlebars. These are the formats they understand:
   1. `{{{ WarningCallout "value of the field" }}}`
   2. `{% WarningCallout "value of the field" %}`
   3. or if you want to bother with multiple fields: `{% WarningCallout "value of the field", "other field value" %}`

I believe your goal is to support the SSGs, so it would be really nice if you would change the (target, documented) logic to support these formats. 🙏

#### Tinacms Package Versions
```text
├── @tinacms/cli@1.0.0
├── tinacms@1.0.0
```

**Comment by newash** [comment]
Let me know if you need any additional info about the bug or the suggested syntax. Thank you!

**Comment by hithismani** [comment]
This would be so helpful!

I would also add, that some frameworks like Hugo support shortcodes that are enclosed. 

I.e {{< shortcode attribute="anything" >}}SOME INNER TEXT THAT GOES ON 
FOR MULTIPLE LINES 
{{< /shortcode >}}


I see there's an `inline:true/false` key for the configuration in Tina, but it doesn't do anything from what I see.

**Comment by newash** [comment]
Ah so, it's Hugo where the named parameter syntax is coming from. 👍
Luckily it also supports non-named syntax.

Anyway, let's hope the devs pick this up and come up with a simple working solution for a start...

**Comment by crimcol** [comment]
+1 to support Hugo shortcodes.
Hugo can support two types of shortcodes:
`{{% myshortcode %}}Hello **World!**{{% /myshortcode %}}`
and 
`{{< myshortcode >}}<p>Hello <strong>World!</strong></p>{{< /myshortcode >}}`

There are two problems:
* It is not possible to register such kind of shortcodes
* if switch to markdown mode it will highlight as invalid syntax and doesn't allow to save it.
`Could not parse expression with acorn: Unexpected token at line: 7, column: 4`

Questions:
Is it possible to achieve such shortcodes with a custom UI like here for [custome boolean type](https://tina-gql-playground.vercel.app/boolean-component?markdownCode=---%0Apublished%3A+true%0A---&schemaCode=import+*+as+React+from+%22react%22%3B%0Aimport+%7B+defineSchema%2C+defineConfig+%7D+from+%22tinacms%22%3B%0A%0Aconst+schema+%3D+defineSchema%28%7B%0A++collections%3A+%5B%0A++++%7B%0A++++++label%3A+%22Post%22%2C%0A++++++name%3A+%22post%22%2C%0A++++++path%3A+%22posts%22%2C%0A++++++fields%3A+%5B%0A++++++++%7B%0A++++++++++label%3A+%22Published%22%2C%0A++++++++++name%3A+%22published%22%2C%0A++++++++++type%3A+%22boolean%22%2C%0A++++++++++ui%3A+%7B%0A++++++++++++component%3A+%28%7B+input+%7D%29+%3D%3E+%7B%0A++++++++++++++return+%28%0A++++++++++++++++%3Cdiv%3E%0A++++++++++++++++++%3Clabel+htmlFor%3D%22published%22%3E+Published%3A+%3C%2Flabel%3E%0A++++++++++++++++++%3Cinput%0A++++++++++++++++++++%7B...input%7D%0A++++++++++++++++++++id%3D%22published%22%0A++++++++++++++++++++type%3D%22checkbox%22%0A++++++++++++++++++++checked%3D%7Binput%3F.value%7D%0A++++++++++++++++++%3E%3C%2Finput%3E%0A++++++++++++++++%3C%2Fdiv%3E%0A++++++++++++++%29%3B%0A++++++++++++%7D%2C%0A++++++++++%7D%2C%0A++++++++%7D%2C%0A++++++%5D%2C%0A++++%7D%2C%0A++%5D%2C%0A%7D%29%3B%0Aexport+default+defineConfig%28%7B+schema+%7D%29%3B%0A&reactCode=import+*+as+React+from+%27react%27%0Aimport+%7B+useTina+%7D+from+%27tinacms%2Fdist%2Freact%27%0A%0A%2F%2F+Note%3A+In+most+cases%2C+this+query+would+be%0A%2F%2F+autogenerated+with+%60client.queries.%3CCollection%3E%60%0A%2F%2F+https%3A%2F%2Ftina.io%2Fdocs%2Ffeatures%2Fdata-fetching%2F%0Aconst+QUERY+%3D+%60query+%7B%0A++post%28relativePath%3A+%22hello-world.md%22%29+%7B%0A++++published%0A++%7D%0A%7D%60%0A%0Aexport+default+function+Page%28props%29+%7B%0A++const+%7Bdata%2C+isLoading%7D+%3D+useTina%28%7B+query%3A+QUERY%2C%0A++++variables%3A+%7B%7D%2C%0A++++data%3A+props.data%0A++%7D%29%0A%0A++if%28isLoading%29+%7B%0A++++return+%3Cdiv%3ELoading...%3C%2Fdiv%3E%0A++%7D%0A%0A++return+%28%0A++%3Cdiv+className%3D%22bg-white%22%3E%0A++++%3Cdiv+className%3D%22max-w-7xl+mx-auto+text-center+py-12+px-4+sm%3Apx-6+lg%3Apy-16+lg%3Apx-8+flex+items-center+justify-center%22%3E%0A++++++%3Ca+className%3D%7B%27bg-gray-50+text-gray-90+flex+items-center+px-3+py-2+text-sm+font-medium+rounded-md+space-x-3%27%7D%3E%0A++++++++%3Cspan%3EPublished%3C%2Fspan%3E%0A++++++++%3Cspan+className%3D%27bg-gray-300+text-gray-600+ml-auto+inline-block+py-0.5+px-3+text-xs+rounded-full%27%3E%7Bdata.post.published+%3F+%22true%22+%3A+%22false%22%7D%3C%2Fspan%3E%0A++++++%3C%2Fa%3E%0A++++%3C%2Fdiv%3E%0A++%3C%2Fdiv%3E%0A%29%0A%7D)?

**Comment by robigan** [comment]
+1 Hugo shortcode support, Tina is great. But I wish for Hugo shortcode support

**Comment by kslstn** [comment]
The merge suggests that this is supported now, but I can't get my Jekyll shortcodes to work as the shortcode name is inserted. For example, a template defined like this:

```js
templates: [
  {
    label: 'Figure',
    name: 'figure',
    match: {
      start: '{% include /component/figure.liquid',
      end: '%}',
    },
    fields: [
      {
        label: 'File',
        name: 'file_path',
        type: 'image',
        required: true,
      },
    ]
  }
]
```

Inserts this into my markdown body:

```liquid
{% include /component/figure.liquid figure file\_path = '/assets/image.jpg' %}
```

I tried mucking around with the `nameOverride` for the template's name, but it is ignored completely. Am I perhaps missing something?

**Comment by newash** [comment]
would it "leak" to the UI if you would name the template like
```js
name: "include /component/figure.liquid",
```
?

**Comment by kslstn** [comment]
It doesn't even get there, because of:
```
Uncaught TinaSchemaValidationError: Error name, "include /component/figure.liquid" must be alphanumeric and can only contain underscores. (No spaces, dashes, special characters, etc.)
```
I hoped the `nameOverride` property would save me from that, but like I said, it's ignored.
