### ISSUE TITLE
Naming convention for "backend" packages

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#341]
Tina only has support for `git` at the moment. 

The packages used to define this behaviour are:

1. `@tinacms/api-git`
2. `@tiancms/git-client`

**What do they do?**

Generally speaking, supporting a backend requires:

1. a "server" that runs with the Gatsby/Next/etc. express server and
2. a "client" that is used to interact with the "server" in the browser.

In the specific case of git:

1. `@tinacms/api-git` provides an express app that exposes endpoints for interacting with git and the filesytem

2. `@tinacms/git-client` provides functions for making requests to `@tinacms/api-git`

**Why change the naming convention?**

Our naming convention is still being figured out a bit. Our thought is that packages in the `@tinacms` namespace would be core packages, mostly meant for internal use. Packages likely meant for direct use in developer's sites would not be under that organization. This description does not match the above plugins, so we're thinking about the naming convention we want for these "backend" packages.

**How to help**

I will add example conventions in the comments below. Please use reactions to express your love/hatred. 

Also feel free to add other suggestions :)

**Comment by ncphillips** [comment]
**Convention**
```
tinacms-${backend}-server
tinacms-${backend}-client
```

Example
```
tinacms-git-server
tinacms-git-client
```

**Comment by ncphillips** [comment]
**Convention**
```
tinacms-${backend}-api
tinacms-${backend}-client
```

Example
```
tinacms-git-api
tinacms-git-client
```

**Comment by ncphillips** [comment]
**Convention**
```
tinacms-${backend}-backend
tinacms-${backend}-client
```

Example
```
tinacms-git-backend
tinacms-git-client
```

**Comment by ncphillips** [comment]
**Convention**
```
tinacms-api-${backend}
tinacms-api-${backend}-client
```

Example
```
tinacms-api-git
tinacms-api-git-client
```

**Comment by kendallstrautman** [comment]
Should we add this convention to the contributing docs?

**Comment by ncphillips** [comment]
Not yet. The  current packages don't adhere to this convention :( they'll have to be changed
