### ISSUE TITLE
Blocks can't setup custom list item labels

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3415]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am trying to setup a custom list rendering label for my list field (on tina.io)
https://github.com/tinacms/tina.io/blob/30bd59ac1bc14721b305e92a94d4336df80f8688/.tina/schema.tsx#L71

I trying setting a `isTitle` field on each of the templates. I would expect those isTitle field to be used as the labels, but they aren't.

I also tried implementing a custom itemProps function, but that gives a typescript error unless the object field is defined with `fields` (instead of `templates`)
https://tina.io/docs/extending-tina/customize-list-ui/

### Reproduction

https://github.com/tinacms/tina.io/tree/blocks-bug

### Steps to reproduce

Clone branch above
Go to http://localhost:3000/admin/index.html#/~/roadmap/
See how list doesn't use isTitle field values in list UI
<img width="896" alt="Screen Shot 2022-11-22 at 4 17 43 PM" src="https://user-images.githubusercontent.com/3323181/203412989-076e5da1-867d-4d00-ac63-7a8fdc3dd2d8.png">

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.70 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
    Yarn: 1.22.19 - ~/Documents/forestry/tinacms-site-next/node_modules/.bin/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.110
    Firefox: 88.0.1
    Safari: 15.6.1
  npmPackages:
    @tinacms/auth: ^1.0.0 => 1.0.0 
    @tinacms/cli: ^1.0.1 => 1.0.1 
    @tinacms/datalayer:  0.2.3 
    @tinacms/graphql:  0.60.0 
    tinacms: ^1.0.1 => 1.0.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jessrezac** [comment]
This is not in the documentation for Template as far as I can see, but you can implement the custom itemProps function on the Template object itself.

```typescript
// node_modules/@tinacms/schema-tools/dist/types.d.ts

export interface Template {
    label?: string;
    name: string;
    ui?: {
        /**
         * Override the properties passed to the field
         * component. This is mostly useful for controlling
         * the display value via callback on `itemProps.label`
         */
        itemProps?(item: Record<string, any>): {
            key?: string;
            /**
             * Control the display value when object
             * items are shown in a compact list, eg:
             *
             * ```ts
             * itemProps: (values) => ({
             *   label: values?.title || 'Showcase Item',
             * }),
             * ```
             */
            label?: string;
        };
        defaultItem?: DefaultItem<Record<string, any>>;
        /**
         * When used in relation to the `visualSelector`,
         * provide an image URL to be used as the preview
         * in the blocks selector menu
         */
        previewSrc?: string;
    };
```

**Comment by jamespohalloran** [comment]
Thanks @jessrezac! Good catch.
In that case, I'd say this one can be closed out with the following tweaks:
- Use the `isTitle` field on templates to populate the default list item label
- In our [docs](https://tina.io/docs/extending-tina/customize-list-ui/) note that itemProps needs be applied on a template, rather than a list field if you are using `templates` rather than `fields`
