### ISSUE TITLE
Collections link in sidebar stays "loading" after login

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3433]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

After logging in to the CMS. The collections link in the sidebar stays in a loading state:
<img width="375" alt="Screen Shot 2022-12-01 at 3 16 18 PM" src="https://user-images.githubusercontent.com/3323181/205140425-784f75f0-dc1a-4f02-9139-88ffe7210d56.png">

It's not until refreshing the page does the collections link load.

### Reproduction

Ask James For Access

### Steps to reproduce

- Go to a hosted site with tina.
- Go to the admin
- Log out
- Log in
- Open sidebar, you'll see the collections link is loading

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 444.61 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - 
    npm: 9.1.2 -
  Browsers:
    Chrome: 108.0.5359.71
    Firefox: 88.0.1
    Safari: 15.6.1
  npmPackages:
    @tinacms/cli: ^1.0.1 => 1.0.1 
    tinacms: ^1.0.1 => 1.0.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
This is also something that we shouldn't even be loading async, now that we have the config as part of the build this doesn't need to be a network request at all
