### ISSUE TITLE
gatsby new my-tina-starter hangs and doesn't install packages

### ISSUE THREAD

**Issue by ChrisTalksTech** [tinacms/tinacms#344]
## Description

Trying to run `gatsby new my-tina-starter` with latest node version.

### Steps to reproduce

Quickstart steps

### Expected result

gatsby site should build and be available at Localhost:8000

### Actual result

build hangs in CLI

### Environment

latest node version on windows

**Comment by DirtyF** [comment]
Do you have a public repo we can check? What is the output of the CLI?

**Comment by ChrisTalksTech** [comment]
solved, used a different package manager, uninstalled node and reinstalled latest version.

**Comment by ncphillips** [comment]
So you remember the exact versions of node/npm you were using previously? It might be useful for future troubleshooting.
