### ISSUE TITLE
RFC: Remark Form Actions API

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#345]
## Status Quo

Currently, Remark Forms have a `Delete` action. 

`Actions` are simply React components that are rendered in the menu.

<img width="345" alt="image" src="https://user-images.githubusercontent.com/824015/67308285-3b7e0400-f4d0-11e9-8631-101e9d328d99.png">

## Proposal

* Export the `DeleteAction` as it's own component
* Change `useRemarkForm` so that it does _not_ add the `DeleteAction` by default.

Future work

* Create additional Action components for common Markdown behaviours.

### Basic example

```javascript
import { 
  remarkForm

  // Secondary Actions
  DeleteAction, 
  RenameAction,  
  PushAction,
  CommitWithMessageAction, 

} from "gatsby-tinacms-remark"

function BlogPostTemplate(props) {
  // ...
}

export default remarkForm(BlogPostTemplate, {
  actions: [
    DeleteAction, 
    RenameAction,  
    PushAction,
    CommitWithMessageAction,
  ]
})
```

## Motivation

This API needs to change for two specific reasons:

* This API assumes that all users should be able to delete all markdown files. That assumption is definitely wrong.
* This API does not allow more actions to be added to Remark Forms.

The proposed solution has several benefits:

* **Small API** This change will actually remove code and simplify the logic of `useRemarkForm`.
* **Few Assumptions:** The fewer assumptions we make about the way something will be used the better. This adds no more assumptions then is currently in `useCMSForm`
* **Easily Extensible:** Don't like the existing DeleteAction? Create you're own.

**Comment by lyleunderwood** [comment]
Would it make sense `actions` to take a render function so we could pass things like form state into it?

**Comment by ncphillips** [comment]
That's effectively what the API is now. Each `action` is treated as a component:

This currently works:

```jsx
import { ActionButton, ActionButtonProps } from "tinacms"
let actions = [
  (props: ActionButtonProps) => <ActionButton onClick={() => alert("Hello World")}>Greeting</ActionButton>,
]
```

The interface for `props` is just empty for now.

**Comment by lyleunderwood** [comment]
Ahh, I see, I was thinking they were elements for some reason.
