### ISSUE TITLE
Branches with `/` cause issues with Tina Cloud

### ISSUE THREAD

**Issue by kyleawayan** [tinacms/tinacms#3458]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I created a new branch, in the format of `githubusername/mybranchfeature`, but Tina Cloud was not pushing any of my changes to my GitHub repo. Everything worked locally, so I was thinking something must've been wrong with Tina Cloud. I kept trying different things (clearing repo cache, force push, etc.), then I tried using "Export Branch". When I tried to export my branch, it would keep infinitely loading with `Checking branch for export...`. However, exporting the `main` branch worked.

I inspected element and saw that the `lastpush` endpoint was getting a 404 error... I saw in the endpoint URL, the branch name is getting appended as is... so the additional `/`  in the branch name may have thrown off the actual real API endpoint.

In this example below the branch name is `kyleawayan/mybranchfeature`
```
https://content-v2.tinajs.io/db/project-id/kyleawayan/mybranchfeature/lastpush
```
This gets a 204 and a 404 error (I think there's `OPTIONS` and `GET` requests for this endpoint, the `GET` one fails)

However I created a new branch `kyleawayan-mybranchfeature`
```
https://content-v2.tinajs.io/db/project-id/kyleawayan-mybranchfeature/lastpush
```
This returns a 204 and 200 and I'm able to export the branch. Also Tina Cloud fully works again and is pushing commits to the repo.

### Reproduction

npx create-tina-app@latest

### Steps to reproduce

1. Make a branch with a `/` in it
2. Deploy and let Tina Cloud index the branch
3. Try exporting the branch

### System Info

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Memory: 169.81 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /usr/local/opt/node@16/bin/node
    Yarn: 1.22.19 - ~/path-to-project-folder/.bin/yarn
    npm: 8.15.0 - /usr/local/opt/node@16/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 105.0.3
    Safari: 15.2
  npmPackages:
    @tinacms/cli: ^1.0.3 => 1.0.3 
    tinacms: ^1.1.0 => 1.1.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
Could you try this again when you get a chance? There was a temporary issue around this on Tina Cloud that has since been patched.

**Comment by jamespohalloran** [comment]
Making this as complete, let us know if you continue to experience this issue.
