### ISSUE TITLE
TinaCMS/Nextjs github pages 404 when accessing root url in

### ISSUE THREAD

**Issue by mtnstar** [tinacms/tinacms#3459]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I just deployed a TinaCMS page on github pages using github actions. It seems to work fine except on initial access to the root URL. On this initial load, Nextjs renders a 404 error page with a link 'Return to home'. When clicking this link, the browser's URL is still the root URL and the home page is rendered correctly. when I access a sub page like example.com/posts directly, the page is rendered correctly. when I do a build and export locally and open the files using a local nginx server, the home page is rendered correctly on initial access. in my next.config.js a have the following:

### Reproduction

https://mtnstar.net

### Steps to reproduce

visit https://mtnstar.net

404 was displayed and u had to click 'Return to home' and it worked perfectly after this.

### System Info

```shell
https://github.com/mtnstar/web

I was able to temporarily fixing it by adding a useEffect / router.push to the App Component.

now the 404 error page quickly flashes up, but then home page is displayed correctly.

https://github.com/mtnstar/web/commit/b1727dfaa4a1c661218b3a66a5d55380898a7d4f

would be nice to fix it.

TinaCMS Version 1.0.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
Can you try upgrading tinacms and @tinacms/cli to the latest?
There was a recent issue where useTina would flash `undefined` in certain instances that has since been fixed.

**Comment by mtnstar** [comment]
I was able to update cli to version 1.0.2

when I try to update tinacms to either 1.1.0 or 1.0.2, I'm getting the following error when accessing localhost:3000/admin:

```
No matching export in "node_modules/@tinacms/toolkit/node_modules/@headlessui/react/dist/index.esm.js" for import "Combobox"

    node_modules/@tinacms/toolkit/dist/index.es.js:13:9:
      13 │ import { Combobox, Transition, Popover as Popover$1, Disclosure, Menu } from "@headlessui/react";
         ╵          ~~~~~~~~

```

I just updated the version in my package.json and ran yarn install.

**Comment by logan-anderson** [comment]
@mtnstar Please remove this from your package.json.


```
  "resolutions": {
    "final-form": "4.20.1",
    "@headlessui/react": "1.4.1"
  }
```

See [this commit](https://github.com/tinacms/tina-cloud-starter/commit/8a89ec3f56134b843c606da132d35c31a7416143) for more details

**Comment by mtnstar** [comment]
@logan-anderson perfect, now I was able to update tinacms to 1.1.1.

but the problem with the 404 still persists unfortunately.

**Comment by logan-anderson** [comment]
@mtnstar Just looking at the repo it looks like the build command may be the issue. 

You have `"build": "tinacms dev -c \"next build\"",`
And it should be `"build": "tinacms build $$ next build",`. You will also have to make sure you have your read only token configured.

See [this doc](https://tina.io/docs/tina-cloud/connecting-site/)  for more details.

**Comment by mtnstar** [comment]
@logan-anderson thx for your feedback.

I switch the build command to `tinacms dev -c \"next build\"` by intention since I wanna use tinaCMS as standalone without cloud. 

I now solved the problem by not hosting the compiled sources on github but on my other webserver. 

now it's working perfectly. Seems to be an issue with github's webserver somehow.
