### ISSUE TITLE
gatsby starter hangs

### ISSUE THREAD

**Issue by pdhoward** [tinacms/tinacms#346]
## Description

Installed the Gatsby starter linked through your docs. Ran through some simple tests (posted, edit an existing blog post). The app successful posted, but unable to edit an existing post .. the terminal no loner permits to stop the app

### Steps to reproduce

1. installed Gatsby starter which I linked to through your docs
2. Gatsby develop
3. opened the app in browser
4 opened the sidebar and posted
5. clicked on existing blog post 
6 opened the side bar to edit
7. edits are not applied in the Gatsby blog
8 terminal is now unresponsive … unable to ctl c our of app

### Expected result

> blog post created (success)
> blog post changed (failed)

### Actual result

see above

### Environment

win 10 environment with latest versions of nodejs

**Comment by DirtyF** [comment]
Can you provide a link to a public repository to demo this behavior?

**Comment by ncphillips** [comment]
It's been a while since this was created and I haven't heard any other reports. Closing until further notice.
