### ISSUE TITLE
'Tags' field plugin

### ISSUE THREAD

**Issue by gabelluardo** [tinacms/tinacms#347]
## Summary

Hi, first thank you for this pretty tool, I love it.
I had a trouble with Gatsby and group-list and I think would be great if there was a Field that could parse markdown list, in particular I have an MDX file with this header: 

```
title: Title
description: Description
tags:
  - tag1
  - tag2
  - tag3
```

I've tried to parse tags with group-list in this way:

```
fields: [
    {
      label: 'Tags',
      name: 'rawFrontmatter.tags',
      component: 'group-list',
      itemProps: (item) => ({
        label: item,
      }),
      defaultItem: 'new-tag',
      fields: [
        { component: 'text' }
      ],
    },
  ...
```

But seems this is not the proper way to use group-list, I've also tried to add a `name` option but nothing.

I used to do that with NetlifyCMS with this configuration: 

```
fields:
      - { name: tags, label: Tags, widget: list }
```

### Basic example

I think that something like this could be much more easy to use:

```
fields: [
    {
      label: 'Tags',
      name: 'rawFrontmatter.tags',
      component: 'list',
      fields: [
        { name: 'tag', component: 'text' }
      ],
    },
  ...
```

### Motivation

This tool is great I want use it and I would see more people use it.

**Comment by ncphillips** [comment]
Hey @gabelluardo! Thanks for the request. I changed the title because what you're asking for is not specific to any data format (i.e. mdx, json, yaml)
