### ISSUE TITLE
SiteWrapper component in `tinacms` sometimes hides the wrapped site's content

### ISSUE THREAD

**Issue by erickzhao** [tinacms/tinacms#348]
## Description

I had an existing Gatsby project on which I wanted to load TinaCMS. I followed the instructions on the "Manual Setup" page (https://tinacms.org/docs/gatsby/manual-setup/) and am greeted with the following screen:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16010076/67317228-d0d0c680-f4d7-11e9-8b68-96ae5c085d79.png">

I asked @ncphillips about it on Slack, and they said it might be because I'm using styled-components to build my site, and it might have to do with these LoC:

https://github.com/tinacms/tinacms/blob/692125c559df4936532f4b70efd8b1fad00f39f3/packages/tinacms/src/components/Tina.tsx#L66-L68

The error occurs when I add the Tina plugin to my Gatsby config:

```js
    {
      resolve: "gatsby-plugin-tinacms",
      options: {
        plugins: [
          // We'll add some Tinacms plugins in the next step.
        ]
     }
```

### Steps to reproduce
1. Clone https://github.com/gamedevmcgill/gamedevmcgill.ca/tree/tina
2. Either comment out all parts of the code having to do with `itch.io`, or generate an API token from itch.io and add it to the `.env`.

### Expected result

Site renders correctly without error in console.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/16010076/67316828-235db300-f4d7-11e9-865d-334d2994ef33.png">

### Actual result

Most of site renders as a blank page, and console shows error:

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `ot`. See https://fb.me/react-warning-keys for more information.
    in styled.div (created by ot)
    in ot
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div
    in P
    in ThemeProvider
    in Unknown
    in _default (at app.js:67)
```

### Environment
Browser: Firefox Developer Edition 71.0b2 (64-bit), Chrome 77.0.3865.120, Safari 13.0.2
OS: macOS 10.14.6
Package versions:
```
"gatsby": "^2.13.34"
"react": "^16.8.6",
"styled-components": "^4.1.3",
"gatsby-plugin-tinacms": "^0.1.7",
```

**Comment by ncphillips** [comment]
Thanks for the report @erickzhao! This is a weird one 🤔

**Comment by jamespohalloran** [comment]
Cloned the site and took a peek. It's a css issue, the content is being hidden because of:
https://github.com/tinacms/tinacms/blob/3412fcde95d6294f783f641e02857c0ddd0ac38c/packages/tinacms/src/components/Tina.tsx#L88
@spbyrne Do you know if the site container being `absolute` is required?

**Comment by spbyrne** [comment]
I can't say for sure, but I'm going to look in to it.

**Comment by spbyrne** [comment]
What @jamespohalloran pointed out seems to be the issue, though if you manually set your `html` and `body` elements to `height: 100%` it also fixes the issue. I'll look into a better way to position the site wrapper for Tina to get around this issue. I suspect `position: relative;` would do the trick without breaking things.

**Comment by spbyrne** [comment]
@erickzhao  I created a PR on your repo with my recommended change to fix this issue.

**Comment by ncphillips** [comment]
Updated the title in light of new info

**Comment by ncphillips** [comment]
Closing because it hasn't come up again
