### ISSUE TITLE
Preview Deployments on Vercel Fail

### ISSUE THREAD

**Issue by mAAdhaTTah** [tinacms/tinacms#3488]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

PRs to the main branch fail with the following error:

```
Error when checking client information. You provided
--
08:35:22.787 |  
08:35:22.787 | {
08:35:22.787 | "branch": "dependabot/npm_and_yarn/typeit-8.7.1",
08:35:22.787 | "clientId": "<clientid>",
08:35:22.787 | "token": "<token>"
08:35:22.787 | }
08:35:22.787 |  
08:35:22.787 | Please check you have the correct "clientId", "branch" and "token" configured. For more information see https://tina.io/docs/tina-cloud/connecting-site/
08:35:22.787 | Error: Server responded with status code 404, Not Found.
08:35:22.787 |  
08:35:22.787 | Message from server: Unable to find record '.tina/__generated__/_graphql.json' in Github Repository: 'mAAdhaTTah/frontend[/]', Ref: 'master' [NOTE: The specified branch, 'dependabot/npm_and_yarn/typeit-8.7.1', has not been indexed by Tina Cloud. See https://tina.io/docs/tina-cloud/faq/#how-do-i-resolve-errors-caused-by-unindexed-branches] Please see our FAQ for more information: https://tina.io/docs/errors/faq/
08:35:22.788 | Error: Server responded with status code 404, Not Found.
08:35:22.788 |  
08:35:22.788 | Message from server: Unable to find record '.tina/__generated__/_graphql.json' in Github Repository: 'mAAdhaTTah/frontend[/]', Ref: 'master' [NOTE: The specified branch, 'dependabot/npm_and_yarn/typeit-8.7.1', has not been indexed by Tina Cloud. See https://tina.io/docs/tina-cloud/faq/#how-do-i-resolve-errors-caused-by-unindexed-branches] Please see our FAQ for more information: https://tina.io/docs/errors/faq/
08:35:22.788 | at request (/vercel/path0/node_modules/@tinacms/cli/dist/index.js:2781:11)
08:35:22.788 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
08:35:22.788 | at async Array.checkClientInfo (/vercel/path0/node_modules/@tinacms/cli/dist/index.js:2801:5)
08:35:22.788 | at async next (/vercel/path0/node_modules/@tinacms/cli/dist/index.js:535:7)
08:35:22.907 | Error: Command "npm run build" exited with 1
```

Deployments on `main` work correctly. Note that I recently renamed `master` -> `main`, in case that has something to do with it. I did reset the repository cache, to no avail.

### Reproduction

https://github.com/mAAdhaTTah/frontend/pull/771

### System Info

```shell
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
    Memory: 2.31 GB / 32.00 GB
    Shell: 5.1.16 - /usr/local/bin/bash
  Binaries:
    Node: 17.6.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Code/Infra/domain/frontend/node_modules/.bin/yarn
    npm: 8.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 99.0.1
    Firefox Developer Edition: 77.0
    Safari: 13.1.2
  npmPackages:
    @tinacms/cli: ^1.0.4 => 1.0.4
    @tinacms/mdx: ^1.0.3 => 1.0.3
    tinacms: ^1.1.1 => 1.1.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by Perni1984** [comment]
@mAAdhaTTah are you sure that you have set process.env.TINA_CLIENT_ID and process.env.TINA_TOKEN for all branches on vercel? (https://github.com/mAAdhaTTah/frontend/blob/main/src/%40app/config.js#L7) - from what I can see and read here the env variables should only be set on the main branch.

**Comment by mAAdhaTTah** [comment]
> are you sure that you have set process.env.TINA_CLIENT_ID and process.env.TINA_TOKEN for all branches on vercel?

Yeah, `main` deploys fine cuz those are filled in correctly.

---

It does seem to work sometimes, but it's not 100% clear to me what triggers the branch being indexed.

**Comment by jamespohalloran** [comment]
We've noticed some instances where a branch should be indexed but it's not. It's sometimes hard to tell if it's a configuration issue, or an actual indexing bug.  @spbyrne has been working on some upcoming updates to improve transparency on the indexing state of each branch:

<img width="795" alt="208992661-7946a1f1-5223-457a-ad11-d91ac95d9e63" src="https://user-images.githubusercontent.com/3323181/210361051-0b4142a8-106b-49d6-b20a-08a0bec08e2f.png">

**Comment by mAAdhaTTah** [comment]
That looks super helpful and would def address this issue. Once that's resolved, I can switch my preview branches to use the current branch again.

**Comment by jamespohalloran** [comment]
@mAAdhaTTah  That UI is now live on the project overview page! It should hopefully give you some hints on if your preview-deployment branches aren't getting indexed

**Comment by mAAdhaTTah** [comment]
Sorry for the delay here. I've got the UI, but I'm still getting a failure on [this PR](https://github.com/mAAdhaTTah/frontend/pull/812). Here's the branch status:

![Screen Shot 2023-01-14 at 6 56 00 PM](https://user-images.githubusercontent.com/4371429/212502251-4db2b48f-da2f-4069-b989-a9acbb658c33.png)

It's failing with this error:

```
Message from server: Unable to find record '.tina/__generated__/_graphql.json' in Github Repository: 'mAAdhaTTah/frontend[/]', Ref: 'master' Please see our FAQ for more information: https://tina.io/docs/errors/faq/
--
18:53:06.186 | Error: Server responded with status code 404, Not Found.
```

There are two weird parts:

1. `.tina/__generated__/_graphql.json` definitely [exists on that branch](https://github.com/mAAdhaTTah/frontend/blob/dependabot/npm_and_yarn/next-13.1.2/.tina/__generated__/_graphql.json).
2. The error message says "Ref: 'master'". I did recently change my primary branch from `main` -> `master`, but it's neither the source nor target branch, which is [defined here](https://github.com/mAAdhaTTah/frontend/blob/dependabot/npm_and_yarn/next-13.1.2/.tina/config.js#L17). I did reset the repository cache, made sure Vercel is pointing at the right branch, and reran the build without a build cache.

So the preview deploy is still failing, although I'm not entire sure whether I'm doing something wrong or Tina is.

**Comment by kldavis4** [comment]
@mAAdhaTTah what is the client id for this project?

**Comment by mAAdhaTTah** [comment]
@kldavis4 `876568fe-64e3-439d-b80e-923384c33da2`

**Comment by kldavis4** [comment]
I think the issue here is with the rename from main -> master. You should now see master in the list of branches in the configuration screen. Go back there and click Reindex on the master branch and once that completes the deploy should work.

**Comment by mAAdhaTTah** [comment]
@kldavis4 It's the other way around, I renamed from `master` -> `main`. `master` no longer exists.

**Comment by kldavis4** [comment]
ok, try the build again now

**Comment by mAAdhaTTah** [comment]
Ok, so progress: I was able to get that branch to build correctly (which made the upgrade to Next 13 nice & easy). However, the existing PRs aren't indexed as despite rebasing those branches, they don't show up to be indexed. Do we have to make changes to the Tina generated files every time we want to trigger those branches to be indexed?

**Comment by kldavis4** [comment]
I'm not following completely on the situation with your existing PRs, but in general new branches should get indexed automatically when they are created in github, triggered by webhooks. If you are not seeing the branch in tina cloud, try pushing a commit to that branch and / or creating a new branch to confirm that those webhooks are working as expected on your project.

**Comment by mAAdhaTTah** [comment]
This all seems to be working now, so maybe just an issue with the branches that were already up. Thanks for your help & the new UI!
