### ISSUE TITLE
There's no time picker for "datetime" fields

### ISSUE THREAD

**Issue by johnridesabike** [tinacms/tinacms#3515]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

There's no UI for picking a time in `datetime` fields.

![image](https://user-images.githubusercontent.com/37978984/212096582-bcc9d7a8-70bf-4340-b3b2-e73cfa506991.png)

Am I missing something? I clicked around but couldn't find any time picker.

### Reproduction

https://tina.io/docs/reference/types/datetime/ (I can provide an actual repo if necessary, but this bug is currently visible on the docs' datetime example sandbox.)

### Steps to reproduce

- Click on the date field.
- There's no way to select a time.

I tried in Firefox and Chrome with the same result.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 133.57 MB / 8.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/code/tina-bug-report/my-tina-app/node_modules/.bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 108.0.1
    Safari: 16.2
  npmPackages:
    @tinacms/cli: ^1.0.0 => 1.0.0
    tinacms: ^1.0.0 => 1.0.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
Just added a note to our docs for this. You can supply the `ui.timeformat` property

```
          {
            type: "datetime",
            name: "date",
            label: "Date",
            ui: {
              timeFormat: "HH:mm"
            },
          },
```
