### ISSUE TITLE
Error syncing media - Timeout error

### ISSUE THREAD

**Issue by niutech** [tinacms/tinacms#3523]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have over 2500 images in our repo (jpg, png, gif, webp) and I want to sync them with Tina Cloud, but after while I get the error syncing media - Time out error in the console.

### Reproduction

https://github.com/nexocodecom/nexocode-web

### Steps to reproduce

1. Go to Tina Cloud admin panel
2. Open Media Manager
3. Click Sync and wait

### System Info

```shell
@tinacms/app: 1.0.4
@tinacms/cli: 1.0.6
@tinacms/datalayer: 1.0.0
@tinacms/graphql: 1.0.5
@tinacms/mdx: 1.1.0
@tinacms/metrics: 1.0.1
@tinacms/schema-tools: 1.2.0
@tinacms/sharedctx: 1.0.0
@tinacms/toolkit: 1.2.1
tinacms: 1.1.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@kldavis4 Thoughts on how to handle this?

**Comment by kldavis4** [comment]
@niutech can you provide the client id to investigate further?

**Comment by kldavis4** [comment]
Actually, @logan-anderson this is the issue: https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/components/media/media-manager.tsx#L307 - I think the backend is fine, it is just a lot of images to sync which takes more than 60 seconds to complete. In this case, it looks like it took around 17 minutes, so I'm not sure what's appropriate.

**Comment by niutech** [comment]
If the backend is fine, does it mean that all the images from the repo should've been synced despite the timeout?
Do we need such timeout on the client side? Shouldn't the client wait until all the images have been synced, even if there are thousands of them?

**Comment by kldavis4** [comment]
Yes, the images did sync successfully from what I can see, it just took a
while. I think the client could definitely be smarter. We should probably
be timing out when there is no progress in the sync process.

**Comment by niutech** [comment]
@kldavis4 Any updates?

**Comment by jamespohalloran** [comment]
So to make sure I understand, the images are syncing successfully, but the frontend shows an error while fetching the status after 60'ish seconds? If that's the case, sounds like this is non-blocking, but just a weird UX?

**Comment by niutech** [comment]
Yes, there should be no timeout error on the front end.

**Comment by jamespohalloran** [comment]
Understood, but the images are synced for you regardless of the UI saying the sync failed, correct?
Just trying to understand if this is a blocking issue.

**Comment by niutech** [comment]
I can see my latest images from the repo, so yes.

**Comment by jamespohalloran** [comment]
Gotcha! So we've started moving the sync button from the CMS into the Tina Cloud Dashboard (since ideally, this should initially be done by an admin, not an editor). 
https://github.com/tinacms/tinacms/pull/3942
I'll make note to make sure this is addressed in the process
