### ISSUE TITLE
No way to distinguish objects in a list

### ISSUE THREAD

**Issue by choephix** [tinacms/tinacms#3531]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have a list of objects as part of my schema, and I expect to have a way to differentiate them from each other so that I can better utilize editor. My first instinct is that if the objects themselves have an `isTitle: true` field, that one would be used here, instead of "[List name] Item".

![image](https://user-images.githubusercontent.com/962412/213593401-86ad7373-993e-4c23-bdbf-206cdb01bc72.png)

### Reproduction

any project

### Steps to reproduce

Add a field to any schema ala the following:

```js

    {
      type: "object",
      list: true,
      name: "projects",
      label: "Projects",
      ui: {
        visualSelector: true,
      },
      fields: [
        {
          type: "string",
          name: "abstract",
          label: "Abstract Name",
          isTitle: true,
          required: true,
        },
        {
          type: "rich-text",
          name: "body",
          label: "Body",
          isBody: true,
        },
      ],
    },
```

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8400  @ 2.26GHz
    Memory: 1.18 GB / 3.83 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /workspaces/folio-tinacms/node_modules/.bin/yarn
    npm: 8.17.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  npmPackages:
    @tinacms/cli: ^1.0.6 => 1.0.6 
    tinacms: ^1.1.3 => 1.1.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by Perni1984** [comment]
@choephix https://tina.io/docs/extending-tina/customize-list-ui/

**Comment by choephix** [comment]
Thanks! That's exactly what I was looking for! ♥

I found a bug, where if you provide an override for the items, they are no longer draggable and cannot be reordered. But I can open up a separate issue for that, closing this one.
