### ISSUE TITLE
Build fails when using compilerOptions.paths in tsconfig.json with TinaCMS

### ISSUE THREAD

**Issue by choephix** [tinacms/tinacms#3532]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

`tsconfig.json` provides the ability to define custom aliases for import paths.
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@utils/*": ["./utils/*"],
      "@components/*": ["./components/*"]
    }
  }
}
```

Something like this gives us the ability to instead of importing modules like so:
```ts
import { SomeComponent } from "../../../../components/SomeComponent";
``` 
to write much cleaner and easier to maintain imports code like this:
```ts
import { SomeComponent } from "@components/SomeComponent";
```

When using bundlers, usually there is small additional configuration that needs to be added to their config files for this to work. **Next.js** does this automatically, when it sees `"paths"` defined in `tsconfig.json`.

When using TinaCMS however, builds will fail and produce the following error:
![image](https://user-images.githubusercontent.com/962412/213669328-32a89d7a-efb0-418b-9777-f1d6c819d478.png)
![image](https://user-images.githubusercontent.com/962412/213669393-fd4571b5-3fa0-4935-a16c-0d48d90bda98.png)

### Reproduction

https://github.com/choephix/portfolio-v2/tree/tinacms-tsconfig-paths-issue

### Steps to reproduce

Clone my public repo `https://github.com/choephix/portfolio-v2/tree/tinacms-tsconfig-paths-issue` (make sure you're on branch `tinacms-tsconfig-paths-issue`) and execute `yarn dev` or `yarn build`.

The files that use the special imports are:
• components/gallery/GalleryBackground.tsx
• components/gallery/GalleryThumbsSlider.tsx

Typescript config file:
• tsconfig.json

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8400  @ 2.26GHz
    Memory: 1.18 GB / 3.83 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.7.0 - ~/.nvm/versions/node/v18.7.0/bin/node
    Yarn: 1.22.19 - /workspaces/folio-tinacms/node_modules/.bin/yarn
    npm: 8.17.0 - ~/.nvm/versions/node/v18.7.0/bin/npm
  npmPackages:
    @tinacms/cli: ^1.0.6 => 1.0.6 
    tinacms: ^1.1.3 => 1.1.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by choephix** [comment]
Since the error mentions **Rollup**, my assumption is that it is the bundler which Tina uses and it's config maybe needs to be updated to handle `paths` in `tsconfig.json`.

**Comment by prokhorvlg** [comment]
Ran into the same issue when trying to use typescript aliases. Tried adding various configurations to see if that would resolve this, but they don't appear to have an impact.

**Comment by jtaccinelli** [comment]
Commenting on this in hopes that it gets picked up soon. If there are options to customise the bundler config, they need to be made clearer in the docs.

**Comment by kiastorm** [comment]
I'm hitting this too. I can't proceed until this is fixed, since my UI library relies heavily on these tsconfig paths
