### ISSUE TITLE
Angle brackets in shortcodes break formatting

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3533]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have the following shortcode: 
```
              {
                name: "rimg",
                label: "Custom Image (rimg)",
                match: {
                  start: "{{<",
                  end: ">}}"
                },
                fields: [
                  {
                    name: "caption",
                    label: "caption",
                    type: "string",
                    ui: {
                      component: "textarea"
                    }
                  }
                ]
              },
```

If I type html into the value, E.g:

```
<a href=''>gregre</a>
```

The value that is output is: `{{< rimg href="d" caption="<a href='' >}}` (note the missing end `"`. The value stops at `>`)

### Reproduction

Ask James for private access if needed

### Steps to reproduce

- Use the shortcode above.
- Add html to the shortcode value
- Save
- Check broken markdown in editor

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 5.20 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/Documents/forestry/smashing-magazine/node_modules/.bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox: 88.0.1
    Safari: 15.6.1
  npmPackages:
    @tinacms/auth: 1.0.2 => 1.0.2 
    @tinacms/cli: use_db_status_to_check_client_info => 0.0.0-20230120125152 
    tinacms: use_db_status_to_check_client_info => 0.0.0-20230120125152
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
This is now handled with the markdown parser.
