### ISSUE TITLE
Support `object` type in `rich-text` `children` fields

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#3534]
Right now, you can support "children" by giving a field the name `children` and the type `rich-text`:

```js
{
  type: "rich-text",
  name: "body",
  templates: [{
    name: "Tabs",
    fields: [{
      name: "children",
      type: "rich-text"
    }]
  }]
}
```
But when your children are assumed to be of a certain shape, this is pretty awkward. This `Tabs` component assumes the following shape:
```js
<Tabs>
 <TabItem>Hello world!</TabItem>
 <TabItem>Hello again!</TabItem>
</Tabs>
```
But since `children` is a rich-text field, the editor could put whatever they want in there. It would be better to restrict that with an `object` field:
```js
{
  type: "rich-text",
  name: "body",
  templates: [{
    name: "Tabs",
    fields: [{
      name: "children",
      type: "object"
      list: true,
      templates: [{
        name: 'TabItem',
        fields: [{
          name: 'children',
          type: 'rich-text',
        }]
      }]
    }]
  }]
}
```

cc @spbyrne any other comments?

**Comment by scottgallant** [comment]
Supporting a string (or text area) would have been helpful for a shortcode we demoed last week.
