### ISSUE TITLE
Saving `{` saves causes the mdx to be invalid 

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#3546]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When using the `rich-text` field and the rich-text editor, if a `{` or `}` is added it looks valid, saves correctly but when the page is refreshes the markdown comes back as invalid.

See video: https://www.loom.com/share/6036de82e36f48bd994911fbf54680b1

### Reproduction

https://www.loom.com/share/6036de82e36f48bd994911fbf54680b1

### Steps to reproduce

See video

### System Info

Video is from the docs starter but was able to reproduce in the monorepo.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
I've also seen that behaviour of when something breaks in the rich-text field, it's not obvious something went wrong until you refresh. Think aspect that could be its own ticket?

**Comment by jeffsee55** [comment]
This is now handled by the fact that the markdown parser is used for non-MDX collections
