### ISSUE TITLE
Limiting to options via `list: false` as stated in docs does not work

### ISSUE THREAD

**Issue by lokimckay** [tinacms/tinacms#3552]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

[According to the docs](https://tina.io/docs/schema/#limiting-values-to-a-set-of-options) this code should produce a radio field

> Omitting list: true (or setting it to false) would result in a single-select radio field.

```js
fields: [
  {
    label: 'Categories',
    name: 'categories',
    type: 'string',
    list: false,
    options: [
      {
        value: 'movies',
        label: 'Movies',
      },
      {
        value: 'music',
        label: 'Music',
      },
    ],
  },
]
```

Instead, the following error is thrown:

```
GraphQL Error
String cannot represent value: ["music"]
```

### Reproduction

https://tina-gql-playground.vercel.app/string-list-options

### Steps to reproduce

1. Navigate to [https://tina-gql-playground.vercel.app/string-list-options](https://tina-gql-playground.vercel.app/string-list-options)
1. Change `list: true` -> `list: false` OR delete the line to omit it
1. Observe result

### System Info

```shell
# Not accessible to me - reproduction is in deployed sandbox linked in documentation
# My specs anyway:

  System:
    OS: Windows 10 10.0.19044
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor
    Memory: 6.30 GB / 15.93 GB
  Binaries:
    Node: 17.5.0 - C:\dev\apps\nodejs\node.EXE
    Yarn: 1.22.19 - C:\dev\repo\cc\codecabana.com.au\node_modules\.bin\yarn.CMD
    npm: 8.18.0 - C:\dev\repo\cc\codecabana.com.au\node_modules\.bin\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.61)
    Internet Explorer: 11.0.19041.1566
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
Hey! I just tried this on a recent project and it seems to be working for me:
<img width="480" alt="Screen Shot 2023-01-24 at 10 45 43 AM" src="https://user-images.githubusercontent.com/3323181/214325428-f4ee37ab-9e7b-43a8-9a12-e0edeec18579.png">

I think the playground may just be out of date. Are you running into the issue on latest, or just the playground?

**Comment by lokimckay** [comment]
I'm also seeing the same issue in my project that's using these versions:

```json
"dependencies": {
    "@tinacms/cli": "^1.0.6",
    "tinacms": "^1.1.3",
}
```

**Comment by jamespohalloran** [comment]
Ah I see, you must have ["music"] as a value in your content. When if goes through the API, it's trying/failing to interpret that as a string type.

See the [working updated playground](https://tina-gql-playground.vercel.app/string-list-options?markdownCode=---%0Acategories%3A+music%0A---&schemaCode=import+%7B+defineSchema%2C+defineConfig+%7D+from+%27tinacms%27%0A%0Aconst+schema+%3D+defineSchema%28%7B%0A++collections%3A+%5B%7B%0A++++label%3A+%22Post%22%2C%0A++++name%3A+%22post%22%2C%0A++++path%3A+%22posts%22%2C%0A++++fields%3A+%5B%7B%0A++++++label%3A+%22Categories%22%2C%0A++++++name%3A+%22categories%22%2C%0A++++++type%3A+%22string%22%2C%0A++++++list%3A+false%2C%0A++++++options%3A+%5B%0A++++++++%7B%0A++++++++++value%3A+%22movies%22%2C%0A++++++++++label%3A+%22Movies%22%0A++++++++%7D%2C+%7B%0A++++++++++value%3A+%22music%22%2C%0A++++++++++label%3A+%22Music%22%0A++++++++%7D%0A++++++%5D%0A++++%7D%5D%0A++%7D%5D%0A%7D%29%0Aexport+default+defineConfig%28%7B+schema+%7D%29%0A&reactCode=import+*+as+React+from+%27react%27%0Aimport+%7B+useTina+%7D+from+%27tinacms%2Fdist%2Freact%27%0A%0A%2F%2F+Note%3A+In+most+cases%2C+this+query+would+be%0A%2F%2F+autogenerated+with+%60client.queries.%3CCollection%3E%60%0A%2F%2F+https%3A%2F%2Ftina.io%2Fdocs%2Ffeatures%2Fdata-fetching%2F%0Aconst+QUERY+%3D+%60query+%7B%0A++post%28relativePath%3A+%22hello-world.md%22%29+%7B%0A++++categories%0A++%7D%0A%7D%60%0A%0Aexport+default+function+Page%28props%29+%7B%0A++const+%7Bdata%2C+isLoading%7D+%3D+useTina%28%7B+query%3A+QUERY%2C%0A++++variables%3A+%7B%7D%2C%0A++++data%3A+props.data%0A++%7D%29%0A%0A++if%28isLoading%29+%7B%0A++++return+%3Cdiv%3ELoading...%3C%2Fdiv%3E%0A++%7D%0A%0A++return+%28%0A++%3Cdiv+className%3D%22bg-white%22%3E%0A++++%3Cdiv+className%3D%22max-w-7xl+mx-auto+text-center+py-12+px-4+sm%3Apx-6+lg%3Apy-16+lg%3Apx-8+space-x-2%22%3E%0A++++++++%7Bdata.post.categories%7D%0A++++%3C%2Fdiv%3E%0A++%3C%2Fdiv%3E%0A%29%3B%0A%7D) where I updated the content:

**Comment by lokimckay** [comment]
Aha thanks! that's fixed it 😄 
I guess the error message does make sense now that I know what I was doing wrong, but was a bit hard to understand before I knew

I'll close this now
