### ISSUE TITLE
Page  constrained to viewport height on live site (cant scroll down)

### ISSUE THREAD

**Issue by AndreBClark** [tinacms/tinacms#356]
## Description

This is my first Issue on an active Repo. I hope I have provided enough information, otherwise let me know what more to provide.

I have added tina cms to an existing gatsby v2 site using the manual setup guide. 
I then incorporated the inline editing using the [Create Markdown Files](https://tinacms.org/docs/gatsby/markdown/#creating-markdown-in-gatsby). scrolling on the blog post page works on local my development server. 
However, once I deploy the gatsby site with Netlify the live site can no longer scroll down. it appears somehow limited to viewport height, and the scroll bar is eliminated. it all looks fine on the local development environment even after re-running the develop command, but the issue only presented itself once the site was deployed to my live site.

_Sidenote:_ how is tina cms to work with live sites? do I need to set up my own authentication? could someone point me to documentation explaining how to manage this?
### Steps to reproduce

**original starter:**
https://github.com/thomaswangio/gatsby-personal-starter-blog
**current project:** 
https://github.com/AndreBClark/CosmicDivision
1. Installed the npm packages mentioned in the guides and added this to `gatsby-config.js`
```js
        {
            resolve: "gatsby-plugin-tinacms",
            options: {
                plugins: [
                    "gatsby-tinacms-git",
                    "gatsby-tinacms-remark"
                ],
            },
        },
```

2. added this to my blog post template
```js
import { liveRemarkForm } from "gatsby-tinacms-remark"
import { Wysiwyg } from "@tinacms/fields"
import { TinaField } from "@tinacms/form-builder"
```
3. Wrapped my component with the liveRemarkForm
```js
export default liveRemarkForm(BlogPostTemplate)
```
4. tested editability
5. merged development branch into master and triggered a Netlify deploy
6. go to [blog post page](https://cosmicdivision.dev/colorable-color-contrast-tool/)
7. can't scroll on any pages.
8. using firefox dev tools I did a little digging
 - right click the button element in the inspector
 - select 'scroll into view' to reach the bottom
 - press my edit button
 - it causes a white page
 - console outputs this error:
```
Error: "useField must be used inside of a <Form> component"
    y react-final-form.es.js:270
    _ react-final-form.es.js:449
    O react-final-form.es.js:645
    React 24
    <anonymous> production-app.js:101
    setTimeout handler*e.exports</< ready.js:31
    <anonymous> production-app.js:100
    promise callback* production-app.js:78
    promise callback* navigation.js:122
    Webpack 4
backend.js:6:2315
    r backend.js:6
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 21
    <anonymous> production-app.js:101
    exports ready.js:31
    <anonymous> production-app.js:100
    <anonymous> production-app.js:78
    <anonymous> navigation.js:122
    Webpack 4
```

### Expected result

ability to scroll and view all content on the [blog post page](https://cosmicdivision.dev/colorable-color-contrast-tool/) with tina cms enabled.
### Actual result
site is constrained to viewport height with no scroll bar. Unable to scroll down blog post

### Environment
this gatsby site is currently using NetlifyCMS, don't know if that could be interfering
Windows 10
Firefox Nightly 71.0a1
Chrome Version 78.0.3904.70 (Official Build) (64-bit)

        "babel-plugin-styled-components": "^1.10.0",
        "gatsby": "^2.3.25",
        "gatsby-background-image": "^0.8.11",
        "gatsby-image": "^2.0.39",
        "gatsby-plugin-feed": "^2.1.1",
        "gatsby-plugin-google-analytics": "^2.0.18",
        "gatsby-plugin-manifest": "^2.0.29",
        "gatsby-plugin-netlify-cms": "^4.0.0",
        "gatsby-plugin-offline": "^2.0.25",
        "gatsby-plugin-prefetch-google-fonts": "^1.4.3",
        "gatsby-plugin-react-helmet": "^3.0.12",
        "gatsby-plugin-sharp": "^2.0.35",
        "gatsby-plugin-styled-components": "^3.0.7",
        "gatsby-plugin-tinacms": "^0.1.7",
        "gatsby-plugin-typography": "^2.3.5",
        "gatsby-remark-copy-linked-files": "^2.0.11",
        "gatsby-remark-images": "^2.0.6",
        "gatsby-remark-responsive-iframe": "^2.1.1",
        "gatsby-remark-smartypants": "^2.0.9",
        "gatsby-remark-vscode": "^1.0.4",
        "gatsby-source-filesystem": "^2.0.29",
        "gatsby-tinacms-git": "^0.2.4",
        "gatsby-tinacms-remark": "^0.3.4",
        "gatsby-transformer-remark": "^2.3.8",
        "gatsby-transformer-sharp": "^2.1.18",
        "netlify-cms-app": "^2.9.1",
        "oniguruma": "^7.2.0",
        "polished": "^3.4.1",
        "react": "^16.8.6",
        "react-dom": "^16.8.6",
        "react-helmet": "^5.2.0",
        "react-switch": "^5.0.0",
        "react-typography": "^0.16.19",
        "styled-components": "^4.2.0",
        "typeface-fira-mono": "0.0.72",
        "typeface-fira-sans": "0.0.75",
        "typeface-orbitron": "0.0.72",
        "typography": "^0.16.19",
        "typography-theme-irving": "^0.16.19"

**Comment by ncphillips** [comment]
> Sidenote: how is tina cms to work with live sites? do I need to set up my own authentication? could someone point me to documentation explaining how to manage this?

See the [Tina Teams](https://tinacms.org/teams/) page

**Comment by ncphillips** [comment]
> Error: "useField must be used inside of a <Form> component"

That could definitely be part of the issue. I'll take a look.

**Comment by ncphillips** [comment]
Digging into this out now. 

I think the `useField` error is kind of a red herring. You're going to want to [hide the edit button in production.](https://github.com/tinacms/tinacms-site/blob/master/src/templates/docs.js#L57-L59)

**Comment by ncphillips** [comment]
I cloned [your site](https://github.com/AndreBClark/CosmicDivision) and immediately ran into a bunch of problems with `styled-components`.

I noticed that your site is using `styled-components@4.2.0`

TinaCMS uses `styled-components@4.3.2`

After upgarding your site's version of `styled-components` to `4.3.2` everything worked fine locally. That may be related to the issues you're having in production.

**Comment by AndreBClark** [comment]
> Digging into this out now.
> 
> I think the `useField` error is kind of a red herring. You're going to want to [hide the edit button in production.](https://github.com/tinacms/tinacms-site/blob/master/src/templates/docs.js#L57-L59)

That Makes sense, I'll implement that later tonight. 


> I cloned [your site](https://github.com/AndreBClark/CosmicDivision) and immediately ran into a bunch of problems with `styled-components`.
> 
> I noticed that your site is using `styled-components@4.2.0`
> 
> TinaCMS uses `styled-components@4.3.2`
> 
> After upgarding your site's version of `styled-components` to `4.3.2` everything worked fine locally. That may be related to the issues you're having in production.

I'll update styled-components, once I get home and see if that addresses the issue. 
thanks for the quick replies!

I'll keep you up to date.

**Comment by AndreBClark** [comment]
I couldn't wait and went and followed your advice from work. Updating styled-components on my repo remedied the scrolling issue.

I am still encountering a white page while trying to edit, and the sidebar doesn't show any forms. 
that makes sense, that is likely a separate issue.
>  You're going to want to [hide the edit button in production.](https://github.com/tinacms/tinacms-site/blob/master/src/templates/docs.js#L57-L59)

I intend to implement hiding the edit button, once I get get back from work. I will have to refactor my class component into a functional one to accommodate the useSidebar hook. 


ultimately it probably is a good thing this is 'breaking' like this as I haven't set up authentication or environemental variables(?), and anyone could be able to edit. I am don't know how this is supposed to work, I'm gonna need to read more of the docs.

I have signed up for the Teams feature.
This is likely unrelated to the issue and I'm willing to table this subject here and talk about it in appropriate issue/slack but when you say production, I am confused as to the intended workflow and when things should be editable for TinaCMS? I'm gonna need to read the docs more.

**Comment by ncphillips** [comment]
>. Updating styled-components on my repo remedied the scrolling issue.

Woo! 🎉 

> I am still encountering a white page while trying to edit, and the sidebar doesn't show any forms.

Is this when you're running `gatsby develop` or in your production site running on Netlify? I ask because your setup does not support editing from the deployed site (you need the running dev server). You'll want to hide the sidebar in production. See the [gatsby config in the tinacms-site](https://github.com/tinacms/tinacms-site/blob/master/gatsby-config.js#L21) for an example.


Great! I will close this issue and

**Comment by ncphillips** [comment]
> within the scope of the issue(broken scrolling) I think I would consider this resolved

Great 👍  I'm going to close this in favor of #362 for the `styled-component` issue.

>  This is likely unrelated to the issue and I'm willing to table this subject here and talk about it in appropriate issue/slack but when you say production, I am confused as to the intended workflow and when things should be editable for TinaCMS

That sounds good! Let's chat in [Slack](https://app.slack.com/client/TN0TY1295/)
