### ISSUE TITLE
Dev Command Error, Looking For Missing `app` Directory

### ISSUE THREAD

**Issue by redreceipt** [tinacms/tinacms#3562]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Trying to run `npx tinacms dev -c "npx live-server --no-browser"` on a simple, static index.html page, It throws an error after running for the second time (first time is ok)

<img width="1739" alt="Screenshot 2023-01-27 at 2 25 52 PM" src="https://user-images.githubusercontent.com/2659478/215179521-f9b9670e-40c2-46fc-bb48-af71026fc099.png">

### Reproduction

https://github.com/redreceipt/tina-demo

### Steps to reproduce

`npx tinacms dev -c "npx live-server --no-browser"`

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M2
    Memory: 1.21 GB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.19 - ~/Documents/Projects/tina-demo/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    Watchman: 2023.01.09.00 - /opt/homebrew/bin/watchman
  Browsers:
    Firefox: 107.0.1
    Safari: 16.2
  npmPackages:
    @tinacms/cli: ^1.0.6 => 1.0.6 
    tinacms: ^1.1.3 => 1.1.3 
```
```


### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
What happens if you add the following script to your package.json?:

```diff
  "scripts": {
+  "dev": "tinacms dev"
  }
 ```
I believe your npx command will run your globally cached version of tinacms, rather than the version defined in your package.json (I think?). I'm able to run `npm run dev` in that repo multiple times
