### ISSUE TITLE
reference field, autogenerated graphQL

### ISSUE THREAD

**Issue by mmorkt** [tinacms/tinacms#3572]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When using the `reference field` the autogenerated graphQL contains the hole website's data. I don't think this field  should be autogenerated or at least it should only contain  `_sys` data by default.

As for now i made a custom query. But I would love to include `...GlobalParts`. But for now it generates to much data. I can fetch the hole website with `...GlobalParts` and a `reference field`. 
 
My use case is for a menu:

```
query globalQuery($relativePath: String!) {
  global(relativePath: $relativePath) {
    menu {
      pageRef {
        ... on Page {
          title
          _sys {
            breadcrumbs
          }
        }
      }
    }
  }
}
```

I'm considering making a link module in my builder with the `reference field`, but then I have to write the hole page query with a builder myself and that wouldn't be that dynamic 

### Reproduction

none

### Steps to reproduce

console.log() the output of a `reference field`

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 117.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 1.22.19 - ~/sites/idrottsrehab/node_modules/.bin/yarn
    npm: 8.3.0 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome Canary: 112.0.5572.0
    Firefox Developer Edition: 110.0
    Firefox Nightly: 110.0a1
    Safari: 16.1
  npmPackages:
    @tinacms/cli: ^1.0.0 => 1.0.7 
    tinacms: ^1.0.0 => 1.1.4
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
> the autogenerated graphQL contains the hole website's data

Can you be more specific? I'm not sure how the attached PR fixes this or why it's necessary

**Comment by logan-anderson** [comment]
Hello, @mmorkt  I think you can create your own queries to achieve this:

Here is a quick video that explains this: https://www.loom.com/share/546fcd98f4384a6983d30eefe08e5b3f
Here is a link to the docs: https://tina.io/docs/data-fetching/custom-queries/

**Comment by mmorkt** [comment]
Thanks @logan-anderson walk through! 

I ended up doing the exact same thing for my navigation (read my description ;-)). The problem comes when adding "...collectionParts". to make i dynamic, then you can query the hole page you are referring to. 

I've got a sitebuilder aswell where I'm using the ref-field for a link-module and because I've got a lot of fields I'm not interested in building the hole schema manually. Haven't got a solution for this yet. so at the moment I can query the hole page I'm refering to from my link-module. 

Maybe this is expected behavior? Just wanted to let you guys know.

**Comment by logan-anderson** [comment]
@mmorkt I just did some testing and I understand what you mean now. 

The issue is when doing
```graphql
query TestQuery($relativePath: String!)  {
    post(relativePath: $relativePath){
        ...PostParts
        author {
            __typename
            ...on Author {
                name
            }
        }
    }
}
```

The all fields are expended (When we only want some fields)

I think setting 
```
 client: {
    referenceDepth: -1,
  },
```
Would fix this (but you would get this behaviour in all collections).


(Side Note: There _might_ be a bug in reference depth right now I will make a GH issue shortly)


cc @jeffsee55
