### ISSUE TITLE
Next-tinacms-cloudinary returns image urls with http over https

### ISSUE THREAD

**Issue by ollebergkvist** [tinacms/tinacms#3576]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Expect Image URLs to be returned with HTTPs when using the Cloudinary integration.

![Screenshot 2023-02-03 at 9 48 40](https://user-images.githubusercontent.com/50720954/216660046-d30db3c2-3533-4d81-932e-908fb7d11382.png)

### Reproduction

npx create-tina-app@latest

### System Info

```shell
System:
    OS: macOS 12.6.3
    CPU: (6) x64 Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz
    Memory: 3.04 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.asdf/installs/nodejs/16.17.0/bin/node
    Yarn: 1.22.19 - ~/Documents/dev/projects/godsent.gg/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.asdf/plugins/nodejs/shims/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0.1
    Safari: 16.3
  npmPackages:
    @tinacms/auth: ^1.0.2 => 1.0.2 
    @tinacms/cli: ^1.0.7 => 1.0.7 
    tinacms: ^1.1.4 => 1.1.4
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
Possibly related: https://discord.com/channels/835168149439643678/1070899971668316202

**Comment by ollebergkvist** [comment]
I believe this still needs a fix, I investigated this a bit more today and oddly I noticed that some pictures are returned with HTTPS and some with HTTP.
