### ISSUE TITLE
Defining a field named _id causes unexpected behaviour

### ISSUE THREAD

**Issue by johtso** [tinacms/tinacms#3578]
### Describe the issue that you're seeing.

![image](https://user-images.githubusercontent.com/830800/216732551-41c02878-4f8d-48e6-bf66-511dee8d74c5.png)

If you define a field called `_id`, which is the natural thing to do after finding that `id` is not allowed.. it causes the path of the markdown file to be displayed where the value should be.

### Reproduction

https://github.com/johtso/tina-id-bug

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1 Pro
    Memory: 417.47 MB / 16.00 GB
    Shell: 3.6.0 - /opt/homebrew/bin/fish
  Binaries:
    Node: 18.0.0 - ~/.nvm/versions/node/v18.0.0/bin/node
    Yarn: 1.22.19 - ~/Code/id-bug-repro/node_modules/.bin/yarn
    npm: 8.10.0 - ~/.nvm/versions/node/v18.0.0/bin/npm
  Browsers:
    Brave Browser: 97.1.34.80
    Chrome: 108.0.5359.124
    Edge: 109.0.1518.78
    Firefox: 108.0.2
  npmPackages:
    @tinacms/cli: ^1.0.8 => 1.0.8
    tinacms: ^1.1.5 => 1.1.5
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
You can now use the `nameOverride` property to get around this:

```js
{
  type: 'string',
  name: 'myId',
  nameOverride: 'id'
},
```
