### ISSUE TITLE
Exposed ENV vars

### ISSUE THREAD

**Issue by jsntv200** [tinacms/tinacms#3579]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

While converting our Jekyll site from Forestry to TinaCMS I noticed that compiling the admin exposes all ENV vars. Supplied is the link to current production index.js for tina.io, search for `TINA_`. If for whatever reason you require some private credentials for your build step then its time to roll your credentials.

I believe this is the offending line of code:
https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/app/src/index.ts#L146

It should only be outputting ENV that TinaCMS requires and it should be noted in the docs that you only want to use public non destructive / read-only ENV vars as they will be publicly exposed.

### Reproduction

https://tina.io/admin/assets/

### Steps to reproduce

- Add an env var to your build steps
- Build the admin
- Inspect the generated index.js for the exposed env var

### System Info

```shell
N/A
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@jsntv200 Thanks for the report. We did not realize that this entire object was getting sent to the frontend. Just put up a PR that fixes it. It will not only send `NODE_ENV`, `NEXT_PUBLIC_*`, `TINA_PUBLIC_*`, and `HEAD` (for integration with Netifly)

**Comment by scottgallant** [comment]
@jsntv200, thank you for identifying and logging this issue.
