### ISSUE TITLE
Markdown WYSIWYG Menu Buttons Visually Broken

### ISSUE THREAD

**Issue by BradMcGonigle** [tinacms/tinacms#360]
## Description

The markdown WYSIWYG menu is visually broken in Safari 13

### Steps to reproduce

Add an a markdown  WYSIWYG form field.  Mine looks like
```
{
  label: 'Body',
  name: 'rawMarkdownBody',
  component: 'markdown',
},
```

### Expected result

Markdown WYSIWYG menu buttons should look like:
![Screen Shot 2019-10-23 at 1 09 51 PM](https://user-images.githubusercontent.com/115338/67417301-6f236180-f596-11e9-81ad-7cca99ad0290.png)

### Actual result

Markdown WYSIWYG menu buttons look like:
![Screen Shot 2019-10-23 at 12 54 35 PM](https://user-images.githubusercontent.com/115338/67417331-7f3b4100-f596-11e9-84a9-e04f15abefc8.png)

### Environment

macOS
Safari Version 13.0.2 (15608.2.30.1.1)

**Comment by spbyrne** [comment]
Thanks, I'll take a look at this.

**Comment by BradMcGonigle** [comment]
> Thanks, I'll take a look at this. 

https://github.com/tinacms/tinacms/pull/361 should fix it

**Comment by spbyrne** [comment]
Awesome, thanks!
