### ISSUE TITLE
Default Item is stored in in `_schema.json`

### ISSUE THREAD

**Issue by 1alexvash** [tinacms/tinacms#3602]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

This morning, for example I have launched Tina, and I have witnessed 4 files modified
![image](https://user-images.githubusercontent.com/46556479/218028628-1123d5c7-7cf1-4690-b1de-a1ccb0b479cb.png)

It is nothing critical, but it makes git history harder to read and analyze

### Reproduction

https://github.com/1alexvash/AlexCodeBlog/tree/Tina-CMS

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 AMD Ryzen 7 5700G with Radeon Graphics             
    Memory: 22.12 GB / 27.90 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\Desktop\AlexCodeBlog\node_modules\.bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (108.0.1462.76)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @tinacms/cli: ^1.0.6 => 1.0.8
    tinacms: ^1.1.3 => 1.1.5
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
The schema.json & the 2 gitignores should be pushed to git. Once the gitignores are there, the admin/index.html can be deleted (and should be gitignored)

**Comment by 1alexvash** [comment]
Why hasn't Tina automatically added those files to ignore list during the initialization?

**Comment by jamespohalloran** [comment]
Well what I mean is that the top 3 files shouldn't be gitignored. They should be pushed to git. 

For the index.html though, that should also be a line in your public\admin\.gitignore file. Was it possibly manually gitadded?

**Comment by logan-anderson** [comment]
See [this doc](https://tina.io/docs/tina-folder/overview/) for more information. The admin.html should have not been added there should be a generated .gitigore that should automatically ignore that.

**Comment by 1alexvash** [comment]
@logan-anderson 
![image](https://user-images.githubusercontent.com/46556479/218247671-bede0697-160f-45d4-95d4-c8f7d4ded8fa.png)
Date stamp is changing on every run

**Comment by logan-anderson** [comment]
I see this is coming from [from this file](https://github.com/1alexvash/AlexCodeBlog/blob/Tina-CMS/.tina/config.ts#L74) if you make `defaultItem` a function that returns that object instead it should not generate every time.

**Comment by 1alexvash** [comment]
It looks like it did help
