### ISSUE TITLE
Documents displayes in cms only if field has `isTitle` in Latin

### ISSUE THREAD

**Issue by applesin** [tinacms/tinacms#3608]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

After updating tinycms to version 1.2.0, documents with non-Latin field values with the isTitle property are no longer displayed in the list in admin.
Documents are added, they can be edited by specifying a direct link, they are also displayed in Altair.

### Reproduction

https://github.com/applesin/-tinacms-starter

### Steps to reproduce

See `content/posts` in files and `Blog Posts` in cms.
`cosmos-ru.md` will not be returned from data in tinacms.

### System Info

```shell
System:
    OS: Linux 6.1 Arch Linux
    CPU: (8) x64 Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz
    Memory: 4.63 GB / 15.56 GB
    Container: Yes
    Shell: 3.6.0 - /usr/bin/fish
  Binaries:
    Node: 19.6.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
  Browsers:
    Chromium: 110.0.5481.77
    Firefox: 109.0.1
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by applesin** [comment]
since the problem was published, several versions have been released in which the behavior of this problem has changed, so I think it is important to say that in general the problem persists

the problem currently persists of records disappearing in situations where sorting is performed on a field containing non-Latin characters

this is important to be able to use the product in non-latin languages

**Comment by kldavis4** [comment]
I'll have a look at this today

**Comment by applesin** [comment]
@kldavis4 
Thanks for the response!
This fix does not work, but now I see where the problem is.

It works for me:
```
    if (!query.lt && !query.lte) {
      query.lte = filterSuffixes?.right
        ? `${filterSuffixes.right}\u04FF`
        : '\u04FF'
    }
```

**Comment by applesin** [comment]
@kldavis4 

1. checked that used version of ```@tinacms/graphql``` with ```\xFFFF```.
2. clear cache (```__generated__```)
3. running ```tinacms dev```

[result](https://www.veed.io/view/84663b9f-f222-48b8-b911-183ad3959f0f?panel=share)

1. making changes to ```\u04FF```
2. clear cache (```__generated__```).
3. running ```tinacms dev```

[result](https://www.veed.io/view/aacdb60f-3434-41ba-b1b0-8ba84f93c9b7?panel=share)

**Comment by kldavis4** [comment]
I forked your repo linked above and added the beta versions to it and all of the content is showing for me after the update: https://github.com/kldavis4/nonlatinchars

Maybe try deleting the node_modules folder?
