### ISSUE TITLE
How to debug the popup error?

### ISSUE THREAD

**Issue by axelthat** [tinacms/tinacms#3647]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I get the following error when I'm trying to upload a file to amazon s3. But it looks like tina truncates the error. How do I see the full error message?

<img width="459" alt="Screenshot 2023-02-28 at 2 46 14 PM" src="https://user-images.githubusercontent.com/31353695/221804029-bc4b2ce5-ab21-48e5-a27d-bea8049d270f.png">

### Reproduction

.

### System Info

```shell
System:
  OS: macOS 13.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 350.16 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
  Yarn: 1.22.19 - ~/upwork/nick/cashforcars.io/node_modules/.bin/yarn
  npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
Browsers:
  Chrome: 110.0.5481.177
  Firefox: 104.0.2
  Safari: 16.3
npmPackages:
  @tinacms/auth: ^1.0.3 => 1.0.3 
  @tinacms/cli: ^1.2.0 => 1.2.0 
  tinacms: ^1.2.1 => 1.2.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
This is a strange error message. The full error message should be in the console. Can you please provide a way for us to reproduce this error? This way we can either make the error message more readable or fix the underlying issue.

**Comment by axelthat** [comment]
@logan-anderson Here it is: https://github.com/axelthat/next-tina-bug. Please use your s3 credentials.

**Comment by axelthat** [comment]
Fixed. I didn't have enough permissions. Followed ACL guide from here: https://tina.io/docs/reference/media/external/s3/
