### ISSUE TITLE
how to disable git synchronization when click sidebar save button when run in `gatsby develop` mode  

### ISSUE THREAD

**Issue by yrong** [tinacms/tinacms#365]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

| Tool    | Version     |
| ------- | ----------- |
| tinacms | commit-hash |
| npm     | version     |
| node    | version     |

**Comment by ncphillips** [comment]
I am not sure what you're looking for. Is it related to this PR #349?

Please add more information to this issue.

**Comment by yrong** [comment]
this is [my forked project](https://github.com/yrong/gatsby-starter-tinacms), notice in this PR you add a flag `PUSH_ON_COMMIT` to control the push behavior,  my assumption is that add this flag as following into the `gatsby-config.js` should work, am i correct?

`
plugins: [
    {
      resolve: "gatsby-plugin-tinacms",
      options: {
        plugins: ["gatsby-tinacms-git", "gatsby-tinacms-remark"],
        sidebar: {
          hidden: process.env.NODE_ENV === "production",
        },
       **PUSH_ON_COMMIT:false**
      },
    },
`

**Comment by ncphillips** [comment]
Ah yes! Almost. It will be:

```
plugins: [
    {
      resolve: "gatsby-plugin-tinacms",
      options: {
        plugins: ["gatsby-tinacms-git", "gatsby-tinacms-remark"],
        sidebar: {
          hidden: process.env.NODE_ENV === "production",
        },
        pushOnCommit: false
      },
    },
```

That feature was added in #349, which has not been release yet. That issue is currently scheduled to in the November 4th release, but I will talk with the team about adding it to the October 28th release.

**Comment by yrong** [comment]
https://github.com/tinacms/tinacms/blob/4c0dc610a277bbc47872659dbff094078e7f095a/packages/%40tinacms/api-git/src/router.ts#L59

Right, will tweat by my own temporarily and thanks for the reply
