### ISSUE TITLE
How to sort media list by creation time?

### ISSUE THREAD

**Issue by axelthat** [tinacms/tinacms#3657]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Currently, the media list is sorted by name. How do I sort by creation time?

<img width="1240" alt="Screenshot 2023-03-02 at 1 31 33 PM" src="https://user-images.githubusercontent.com/31353695/222364102-34d6a96d-cc80-49d4-b651-908cc715de83.png">

### Reproduction

.

### Steps to reproduce

Just open the media list and you will see for yourself.

### System Info

```shell
System:
  OS: macOS 13.2.1
  CPU: (10) arm64 Apple M1 Pro
  Memory: 350.16 MB / 16.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.18.0 - /opt/homebrew/opt/node@16/bin/node
  Yarn: 1.22.19 - ~/upwork/nick/cashforcars.io/node_modules/.bin/yarn
  npm: 8.19.2 - /opt/homebrew/opt/node@16/bin/npm
Browsers:
  Chrome: 110.0.5481.177
  Firefox: 104.0.2
  Safari: 16.3
npmPackages:
  @tinacms/auth: ^1.0.3 => 1.0.3 
  @tinacms/cli: ^1.2.0 => 1.2.0 
  tinacms: ^1.2.1 => 1.2.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
Any sorting on file metadata isn't currenlty supported.
