### ISSUE TITLE
 Create a Tina project in the subdirectory of the project, loading page data error

### ISSUE THREAD

**Issue by sk894703472** [tinacms/tinacms#366]
## Description

I created a new Tina project in a subdirectory of a git project. When I load the tina data, I request an error. I think that because ‘fileRelativePath’ is not included, it doesn’t start from the git root directory, so I can't find the file.

### Steps to reproduce

Create a new tina start project in a git project, run an error

### Actual result

Trying to add a path prefix to the dev environment does not work, I don't know what to do.

### Environment
![image](https://user-images.githubusercontent.com/28885196/67485504-bf84e700-f69c-11e9-862b-4f3615f0569d.png)

| Tool    | Version     |
| ------- | ----------- |
| tinacms | 0.1.7|
| npm     | 6.4.1     |
| node    | 8.16.3     |

**Comment by spbyrne** [comment]
This may be missing from the documentation, but both `pathToRepo` and `pathToContent` are configurable options for the `gatsby-tinacms-git` plugin. Here's an example from the `demo-gatsby` package:

```
{
      resolve: "gatsby-plugin-tinacms",
      options: {
        sidebar: {
          hidden: process.env.NODE_ENV === "production",
          position: "displace",
        },
        plugins: [
          "gatsby-tinacms-json",
          "gatsby-tinacms-remark",
          {
            resolve: "gatsby-tinacms-git",
            options: {
              pathToRepo: REPO_ABSOLUTE_PATH,
              pathToContent: "packages/demo-gatsby",
              defaultCommitMessage: "Update from the content ",
              defaultCommitName: "TinaCMS",
              defaultCommitEmail: "git@tinacms.org",
            },
          },
        ],
      },
    },
```

I'm not sure if this will fix your issue but it's worth a try.

**Comment by spbyrne** [comment]
In that example REPO_ABSOLUTE_PATH is coming from this:
```
const REPO_ABSOLUTE_PATH = path.join(process.cwd(), "../..")
```
`pathToRepo` is relative to the server root, and `pathToContent` is relative to `pathToRepo`

**Comment by sk894703472** [comment]
Thank you.I solved this problem.

But I made a mistake when committing. Is there any relevant content for my reference?

**Comment by spbyrne** [comment]
I'm sorry but I'm not sure what you're asking.

**Comment by sk894703472** [comment]
When I set pathToRepo and pathToContent.
I can request data normally, my address is wrong when I submit it.
'/Users/Documents/cfdemo**/cfds/cfds/**contents/Design/visual-element/color-system.md'
Cfds appeared twice

**Comment by spbyrne** [comment]
What are your values for `pathToRepo` and `pathToContent`?
