### ISSUE TITLE
Linked images stripped from markdown

### ISSUE THREAD

**Issue by novellac** [tinacms/tinacms#3696]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

**I am doing:** I'm trying to view and edit documents which contain linked images.

**What I expect:** I expect to be able to view the linked image, as well as edit the content (preferably in rich text editor, but at least in raw markdown mode).

**What actually happens:** The linked images are stripped when I open the document in Tina, so I can't view or edit them, and they're not shown on the page.

**Screencast:** https://voicethread.com/share/22418820/

### Reproduction

Please let me know if the screencast is not sufficient and I'll make a repo.

### Steps to reproduce

1. Create a new document in Tina CMS
2. In markdown/raw mode, add the following code (but with real values, or you'll get some unrelated, legit behaviour):
```
[![](/uploads/2021/12/nice_image.png)](https://example.com/niceurl)
```
3. Click save and then get back into the document, or just click out of the raw markdown editor
- Expect to see that the markdown has been stripped from the document.

### System Info

```shell
System:
    OS: macOS 13.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 1.25 GB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.19 - ~/path/to/my/repo/node_modules/.bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 16.3
  npmPackages:
    @tinacms/cli: ^1.0.8 => 1.3.2 
    tinacms: ^1.3.0 => 1.3.2
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
Will be closed by https://github.com/tinacms/tinacms/pull/3698
