### ISSUE TITLE
Editing fields create a lot of `finalForm.change` calls are made when editing fields

### ISSUE THREAD

**Issue by Eugene-Kuzmenko** [tinacms/tinacms#3704]
### Description

On a project we're using TinaCMS toolkit without iframe
I'm noticed that some fields causing freezes over time. During performance measuremenets I've noticed a lot of calls of `finalForm.change`
I examined the source code to figure out why. I suspect it is because of feedback loop in [FormBuilder.tsx](https://github.com/tinacms/tinacms/blob/main/packages/@tinacms/toolkit/src/packages/form-builder/FormBuilder.tsx#L466). It seems it will wrap the methods that were already wrapped before every time form values are change, which is causing a lot of calls

#### From [test project](https://github.com/Eugene-Kuzmenko/tina-cms-field-slowdown-issue)

![image](https://user-images.githubusercontent.com/42930224/225429412-b5e016cf-8add-4829-a569-baa37b70471c.png)

### Reproduction

https://github.com/Eugene-Kuzmenko/tina-cms-field-slowdown-issue

### Steps to reproduce

- Setup Tina Toolkit project (or use the [example](https://github.com/Eugene-Kuzmenko/tina-cms-field-slowdown-issue))
- Open Colors > Background Color and do multiple quick clicks in color picker gradient area
- In browser's devtools go to Performance and hit record
- Click on the color picker gradient area and stop recording
- You can search for finalForm.change calls and find a lot of them

### System Info

```shell
System:
    OS: macOS 11.6
    CPU: (4) x64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz
    Memory: 101.21 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.64
    Firefox: 110.0.1
    Safari: 14.1.2
  npmPackages:
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
I don't think this is related to that since they're not using the iframe.

Thanks @Eugene-Kuzmenko - this code can actually probably be removed soon, to refactor some parts of our iframe implementation.

**Comment by jeffsee55** [comment]
Also @Eugene-Kuzmenko we'll probably be deprecating some of the APIs from the `@tinacms/toolkit`, curious on what your use case is for using things that way?

**Comment by Eugene-Kuzmenko** [comment]
@jeffsee55, I'm not quite sure what exactly is unusual about the way we're doing things, since I don't know how things are usually done. I didn't do a lot of research on how Tina is setup is supposed to look like. I came to our project relatively recently, so everything was already setup
Our project is a self hosted visual website editor. We don't use Tina Cloud or Tina Data Layer. We have our own backend api to hold websites' settings
