### ISSUE TITLE
Add ability to configure the "git commit" command 

### ISSUE THREAD

**Issue by sk894703472** [tinacms/tinacms#374]
## Description

Due to project issues, my repository needs to pass -n to ignore some eslint syntax when submitting. I want to modify the commit command to -n. 
Is this parameter configurable?

* [git commit -n](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--n)

**Comment by ncphillips** [comment]
Hey @sk894703472 this is currently not possible. It's late here, but I'll start looking into it in the next couple days. 

Thanks for bringing this up 😄
