### ISSUE TITLE
Tinacms v1.4.0 not working with Astro on local

### ISSUE THREAD

**Issue by Boston343** [tinacms/tinacms#3741]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am trying to use Tinacms with Astro. With the current latest release of tinacms `"tinacms": "1.4.0"` and the cli `"@tinacms/cli": "1.4.1"` , I am getting a blank screen at the `/admin/index.html` route. If I downgrade the tinacms package and cli to v1.3.3, the `/admin/index.html` route works and I can create and edit posts as expected. In both cases the normal Astro routes work as expected.

I have tried the page in multiple browsers.

### Reproduction

https://github.com/Boston343/astro-tina-test2

### Steps to reproduce

- Create an Astro project `npm create astro@latest`, this is currently v2.1.7
  - I selected the blog starter, and relaxed typescript
- Inside the newly created astro project, add Tina  `npx @tinacms/cli@latest init`
- Update package.json dev command `"dev": "tinacms dev -c \"astro dev\"",`
- start dev with `npm run dev`
- navigate to http://localhost:3000/admin/index.html 
- see issue

### System Info

```shell
Note: my system is actually Windows 11

System:
    OS: Windows 10 10.0.22621
    CPU: (12) x64 AMD Ryzen 5 5600X 6-Core Processor
    Memory: 17.93 GB / 31.91 GB
  Binaries:
    Node: 18.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\Documents\name\Learning\Full Stack Development\Projects\astro-tina-test2\node_modules\.bin\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1413.0), Chromium (111.0.1661.51)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tinacms/cli: ^1.3.3 => 1.4.1
    tinacms: ^1.3.3 => 1.4.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
Thanks for the report, this was a regression for windows, PR for the fix is [here](https://github.com/tinacms/tinacms/pull/3744) but in the meantime if you want to use 1.4 you can use the tagged release `fix-windows-issues-on-cli`

```
yarn add @tinacms/cli@fix-windows-issues-on-cli
```
