### ISSUE TITLE
Node.js + Vite problems with .es.js files

### ISSUE THREAD

**Issue by leomp12** [tinacms/tinacms#3764]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am using Astro and getting the following error on SSR:

![Screenshot 2023-03-30 at 20-14-07 SyntaxError](https://user-images.githubusercontent.com/10326572/228986099-03cc2a85-787e-47b5-8137-59abf30f41eb.png)
![Screenshot 2023-03-30 at 20-14-38 SyntaxError](https://user-images.githubusercontent.com/10326572/228986092-62561e6f-e1be-4138-aaab-42e956ddd61c.png)

Node.js (or Vite ?) seems to be recognizing the built files as CJS instead of ES module.
I'm using package.json `"type": "module"`.

If I import Tina CMS files client side only (e.g. `<Post client:only />`) it works normally, also works if I just remove the `fetch-ponyfill` import (not needed with Node 18) and use CJS syntax at the `client.es.js` file:

```js
/*
import fetchPonyfill from "fetch-ponyfill";
const { fetch, Headers } = fetchPonyfill();
*/
const TINA_HOST = "content.tinajs.io";
class TinaClient {
  constructor({ token, url, queries }) {
    this.apiUrl = url;
    this.readonlyToken = token;
    this.queries = queries(this);
  }
  async request(args) {
    const headers = new Headers();
    if (this.readonlyToken) {
      headers.append("X-API-KEY", this.readonlyToken);
    }
    headers.append("Content-Type", "application/json");
    const bodyString = JSON.stringify({
      query: args.query,
      variables: (args == null ? void 0 : args.variables) || {}
    });
    const url = (args == null ? void 0 : args.url) || this.apiUrl;
    const res = await fetch(url, {
      method: "POST",
      headers,
      body: bodyString,
      redirect: "follow"
    });
    if (!res.ok) {
      let additionalInfo = "";
      if (res.status === 401) {
        additionalInfo = "Please check that your client ID, URL and read only token are configured properly.";
      }
      throw new Error(`Server responded with status code ${res.status}, ${res.statusText}. ${additionalInfo ? additionalInfo : ""} Please see our FAQ for more information: https://tina.io/docs/errors/faq/`);
    }
    const json = await res.json();
    if (json.errors) {
      throw new Error(`Unable to fetch, please see our FAQ for more information: https://tina.io/docs/errors/faq/

        Errors: 
	${json.errors.map((error) => error.message).join("\n")}`);
    }
    return {
      data: json == null ? void 0 : json.data,
      query: args.query
    };
  }
}
function createClient(args) {
  const client = new TinaClient(args);
  return client;
}
// export { TINA_HOST, TinaClient, createClient };
module.exports = { TINA_HOST, TinaClient, createClient };
```

I think just renaming the output files and respective package exports to .mjs would also fix the problem.

### Reproduction

https://github.com/ecomplus/cloud-commerce/tree/tinacms

### Steps to reproduce

```bash
git submodule update --init store
pnpm i
cd packages/storefront
```

Edit `packages/storefront/src/main/Home.astro` to:

```astro
---
import type { PageContext } from '@@sf/ssr-context';
import api from '@cloudcommerce/api';
import Prices from '~/components/Prices.vue';
import ProductCard from '@@sf/components/ProductCard.vue';
import Post from '@@sf/components/Post.vue';

export interface Props {
  pageContext: PageContext;
}

const products = (await api.get('products')).data.result;
---

<main>
  <h1>Welcome to <span class="text-primary">Astro</span></h1>
  <ul role="list" class="mt-3 fs-20">
    {products.map((product) => <li>
      <a href={`/${product.slug}`}>{product.sku}</a>
    </li>)}
  </ul>
  <div class="prose">
    <h1>Oi</h1>
    <p>Olá <a href="/">link</a></p>
    <ul>
      <li>So here is the first item in this list.</li>
      <li>In this example we're keeping the items short.</li>
      <li>Later, we'll use longer, more complex list items.</li>
    </ul>
    <details>
      <summary role="button">Accordion 1</summary>
      <p>…</p>
    </details>
  </div>
  <div>
    <h1>Oi</h1>
    <p>Olá <a href="/">link</a></p>
    <details>
      <summary role="button">Accordion 1</summary>
      <p>…</p>
    </details>
  </div>
  <div class="mt-2">
    <div>
      <label class="block">
        <span class="text-gray-700">Email address</span>
        <input type="email" class="mt-1 block w-full" placeholder="john@example.com">
      </label>
      <label class="inline-flex items-center">
        <input type="checkbox" checked />
        <span class="ml-2 font-brand">Email me news and special offers</span>
      </label>
    </div>
  </div>
  <Prices price={10} client:load />
  <ProductCard client:load />
  <Post client:load />
</main>
```

---

> Sorry about that, I tried to create new https://stackblitz.com/ but never passing from _Indexing local files ..._ 😬 

![Screenshot 2023-03-30 at 20-48-04 Astro Blog Example (forked) - StackBlitz](https://user-images.githubusercontent.com/10326572/228989570-e69cc34d-782a-4886-b6ed-97b0dc6f706b.png)

### System Info

```shell
Astro 2.1.2 (Vite 4.x)
pnpm 7
Node.js 18


  System:
    OS: Linux 6.2 Arch Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
    Memory: 6.93 GB / 15.47 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.1 - ~/.nvm/versions/node/v18.14.1/bin/node
    Yarn: 1.22.19 - ~/code/ecomplus/cloud-commerce/node_modules/.bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.1/bin/npm
  Browsers:
    Chromium: 111.0.5563.110
    Firefox: 111.0.1
  npmPackages:
    @tinacms/cli: ^1.5.2 => 1.5.2 
    tinacms: ^1.4.3 => 1.4.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
@leomp12 is this an issue with the latest version of `tinacms` or `@tinacms/cli` or are you working with Tina for the first time?

**Comment by leomp12** [comment]
The error is not only with latest version.
I've tried Tina first time on 1.0.0 launch, already had this error. At that moment I failed integrating it with Vue due to some Vite related [errors](https://github.com/tinacms/tinacms/pull/3260#issuecomment-1271837053), I gave up at that point and now I'm trying again (seems to work now 😃 ).

**Comment by jeffsee55** [comment]
Sorry if I'm misunderstanding, are you saying this issue is not happening anymore on the latest versions?

**Comment by leomp12** [comment]
If I can recommend related reading: https://antfu.me/posts/publish-esm-and-cjs#bundling
I can also give a try here if you want me to, just not sure if renaming files [exported files](https://github.com/tinacms/tinacms/blob/main/packages/tinacms/package.json#L6-L37) would be a breaking change for you 😬

**Comment by leomp12** [comment]
Ok it seems to be working now 😃 
With tinacms 1.4.6 and vite 4.3.1
closing...

**Comment by arimgibson** [comment]
@leomp12 you didn't change any configurations; just updated Vite and Tina? I'm using Tina 1.5.10 and Astro 2.6.6 (uses Vite 4.3.9) and am still encountering this bug.

If I add `type: "module"` to `node_modules/tina/package.json`, everything works as expected. If I had to guess, I'd wonder if `.es.js` is depreciated because I've only ever seen `.mjs`, which is what that Antfu article suggests too

**Comment by arimgibson** [comment]
Changing the file extensions to `.mjs` fixed it for me. The Node docs also specify that [the .mjs extension](https://nodejs.org/api/modules.html#the-mjs-extension) can be used to load ESModules. 

I'm a little surprised that this isn't a bigger issue, and that others haven't run into this before :thinking:

**Comment by leomp12** [comment]
> @leomp12 you didn't change any configurations; just updated Vite and Tina?

As far as I know yes, but I also found it strange actually...

> If I had to guess, I'd wonder if .es.js is depreciated because I've only ever seen .mjs, which is what that Antfu article suggests too

`.es.js` has never been a standard, the correct thing is to use `.mjs` for libs, or `{ "type": "module" }` in package.json as you mentioned and then `*.js` will be treated as modules by Node.js.

**Comment by arimgibson** [comment]
> `.es.js` has never been a standard, the correct thing is to use `.mjs` for libs, or `{ "type": "module" }` in package.json as you mentioned and then `*.js` will be treated as modules by Node.js.

Thanks for this context! That makes sense; Node is trying to load those modules as CJS because they're not using the designated `.mjs` to be treated as modules.

@jeffsee55 with your approval, I can start looking at creating a PR to generate all module files as `.mjs` instead of `.es.js`? Unless this is a big enough change to warrant an RFC or something of that nature

**Comment by jeffsee55** [comment]
I think the reason it's not a bigger issue is likely because Next is doing some magic to handle CJS/ESM seamlessly while Astro is probably throwing an error as expected. I'm not sure how many Astro users are using Tina's `client` for data fetching, but for visual editing with Tina that's a requirement. 

FWIW, we tried changing things to `"type": "module"` but that caused other issues we had to roll it back, I've just updated a release that cleans some things up and may work:

```
npm install tinacms@fix-es-extension @tinacms/cli@fix-es-extension -E
```
(note the -E is for exact which is important for installing our tagged releases)

It'd be great to know if that works for your Astro. We'll be testing a few other things in that PR before we do a release so it might be unstable for you FYI.

**Comment by arimgibson** [comment]
@jeffsee55 that does make sense; personally haven't used Next so also possible that their default configuration also just uses CJS, and then certain TypeScript settings help everything play together nicely. Astro's CLI creates a tsconfig that `extend`s off of presets set by Astro which target the most modern environments (NodeNext, ESNext, `moduleResolution: node`). Makes sense that could cause compatibility issues as well.

I appreciate that fix! Worth noting that in my setup, these issues showed up with both trying to fetch data via `client` alone, and then also when setting up the experimental visual editing with the `useTina` React hook. Will give it a go and report back
