### ISSUE TITLE
Support `path: ""` or `path: '/'`

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#3768]
Right now if the user wants to have a collection with the path at the root it is not possible and they will get an error. 

We should support `path: /` and allow the user to use the match property. 

EX
```
{
  path: '/',
  name: 'page",
  label: "Pages", 
  match: {
      include: "{foo,bar}/**/*"
  },
}
```

Note:  I took a quick look at doing this and it is not going to be a super quick fix (1-4 days or so).

**Comment by DevGlitch** [comment]
+1

**Comment by logan-anderson** [comment]
Fixed by https://github.com/tinacms/tinacms/pull/3803
