### ISSUE TITLE
Gatsby: Getting blank /admin/index.html

### ISSUE THREAD

**Issue by gsicvj** [tinacms/tinacms#3772]
Last week I successfully migrated from Forestry to TinaCMS v1.3.3.

The project's package.json had ^v1.3.2 written for tinacms and @tinacms/cli.
It started to fetch the latest versions of tinacms v1.4.2 and @tinacms/cli v1.5.3.

This resulted in 404 for /admin/index.html both on localhost:8000 and Netlify deployment.
I've noticed that this was also reported in the Tina's Discord channel.

I saw that I can access TinaCMS locally via localhost:4001/admin/index.html.

At some point builds started failing as well due to:
`tinacms build && gatsby clean && gatsby build`
`11:22:12 AM: Starting Tina build`
`11:22:12 AM: ✘ [ERROR] Could not resolve "scheduler"`
`11:22:12 AM:     node_modules/@udecode/zustood/node_modules/use-context-selector/dist/index.umd.js:1:103:`
`11:22:12 AM:       1 │ ...s,require("react"),require("scheduler"),require("react-dom")):"f...`

I migrated to new folder structure from .tina to tina/.

Then I tried to go back to TinaCMS 1.3.3, but the dependency changes are already on the remote branch.

Trying to run build locally results in this now:
`Done building static site`
`Checking clientId, token and branch. ✅`
`Checking indexing process in Tina Cloud... ❌`
`/.../node_modules/@tinacms/cli/dist/index.js:1764 throw new IndexFailedError(^`
`IndexFailedError: Attempting to index but responded with status 'unknown', To retry the indexing process, click “Reset Repository Cache” in tina cloud advance settings.  undefined`

I reset cache, published a new branch and on v1.3.3 the project is passing build and deploy stages again.

Not sure what happened last week with the configs for URL and port settings, but it's not the expected behaviour.

### Reproduction

https://github.com/gsicvj/TinaCMSAdminIndex404

### Steps to reproduce

Setup a project with these dependencies:
 - "gatsby": "^4.25.4",
 - "@tinacms/cli": "^1.3.2",
 - "tinacms": "^1.3.2",

Run `npm install`

Start the development server with `npm run dev`

Navigate to `localhost:8000/admin/index.html` (Will return 404)

If you go for Netlify deployment, try to access `somewhere.netlify/admin/index.html` (Will return 404)

Navigate to `localhost:4001/admin/index.html` (Will return 200)

### System Info

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 3.05 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    Yarn: 1.22.19 - ~/.../my-tina-app/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.1
  npmPackages:
    @tinacms/cli: ^1.5.2 => 1.5.2 
    tinacms: ^1.4.3 => 1.4.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
It looks like there's some issues serving static html files with Gatsby:
https://github.com/gatsbyjs/gatsby/issues/13072

I just tried this is your repo and I was able to load the admin through: http://localhost:8000/admin/

gatsby-config.js

```diff
+ const express = require(`express`);

module.exports = {
// ...
+  developMiddleware: (app) => {
+    app.use("/admin", express.static("public/admin"));
+  },
```

**Comment by gsicvj** [comment]
Maybe that was an issue in 2019-2020 for local development only.
It seems to be fixed: https://github.com/gatsbyjs/gatsby/issues/13072

Our 404 is present both locally and on the server build.

tinacms v1.3.3 was working fine (including serving static html files)

**Comment by jamespohalloran** [comment]
Hmm, I don't quite understand how get how it would work on a previous Tina version
If you take Tina out of the picture, and just run `gatsby develop`, and place a dummy html file in your public directory, you still get a 404. That tells me that the issue lies more-so in Gatsby's delivery of static HTML files, rather than anything to do with Tina's version.

**Comment by jamespohalloran** [comment]
@jeffsee55 Any thoughts on if this could be the result of a CLI regression?

**Comment by jeffsee55** [comment]
Is this the correct repo for reproducing this? https://github.com/gsicvj/TinaCMSAdminIndex404. That looks like a NextJS project that hasn't been set fully set up.

**Comment by jamespohalloran** [comment]
> Maybe that was an issue in 2019-2020 for local development only. It seems to be fixed: [gatsbyjs/gatsby#13072](https://github.com/gatsbyjs/gatsby/issues/13072)
> 
> Our 404 is present both locally and on the server build.
> 
> tinacms v1.3.3 was working fine (including serving static html files)

I think my suggested fix does still apply for local development, but what you're saying is that you still got a 404 on your production environment.

I just noticed, your build script: "tinacms build && gatsby clean && gatsby build"

"tinacms build" will output the admin html file in your public directory, however you may be whiping it out with "gatsby clean".

What if you change your build script to "gatsby clean && tinacms build && gatsby build"?

Also, your demo repo sets the publicDirectory to "public". I think for Gatsby, you'll have to set this to "static"
https://www.gatsbyjs.com/docs/how-to/images-and-media/static-folder/#when-to-use-the-static-folder

**Comment by jamespohalloran** [comment]
I believe these work around should sort you out: https://github.com/tinacms/tina.io/pull/1534/files
I've tested on a few sites and was able to load the admin with these changes. If you're still facing issues, let us know and we can re-open this ticket

**Comment by gsicvj** [comment]
@jeffsee55 it was something I scrambled fast by frankenstein-ing some templates just to check the http:8000/admin/index.html

@jamespohalloran for some reason the original project setup writes a page-data.json that still results in 404. I'll have to check this separately.

Thank you both for the time and input and closing this report.

**Comment by gsicvj** [comment]
@jamespohalloran a minor detail. In this PR: https://github.com/tinacms/tina.io/pull/1534/files you wrote that onCreateDevServer should be placed in **gatsby-config.js**, but instead has to be placed into **gatsby-node.js** to make express proxies work.

**Comment by jamespohalloran** [comment]
> @jamespohalloran a minor detail. In this PR: https://github.com/tinacms/tina.io/pull/1534/files you wrote that onCreateDevServer should be placed in **gatsby-config.js**, but instead has to be placed into **gatsby-node.js** to make express proxies work.

Thanks! Just updated
