### ISSUE TITLE
Problem running npx tinacms dev with eleventy from forestry migration

### ISSUE THREAD

**Issue by makovez** [tinacms/tinacms#3773]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi, i have followed the steps to migrate from forestry to tina  with  `npx @tinacms/cli@latest init` but I am not able to run this command `npx tinacms dev -c "eleventy --serve && npm run sass:watch"`

```
(base) PS C:\Users\pigna\Documents\cannabis-main-new\coltivazionecanapa> npm run dev  

> cannabis@1.0.0 dev
> npx tinacms dev -c "eleventy --serve && npm run sass:watch"

Starting Tina Dev Server
tina-migration
Indexing local files ⠙
│
○  Tina Dev Server is running... ────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│  🦙  Tina Config                                                                                                                            │
│     CMS:              <your-dev-server-url>/C:\Users\pigna\Documents\cannabis-main-new\coltivazionecanapa\_site\admin\index.html           │
│     API playground:   <your-dev-server-url>/C:\Users\pigna\Documents\cannabis-main-new\coltivazionecanapa\_site\admin\index.html#/graphql  │
│     API url:          http://localhost:4001/graphql                                                                                        │
│                                                                                                                                            │
│                                                                                                                                            │
├────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Starting subprocess: eleventy --serve && npm run sass:watch
(base) PS C:\Users\pigna\Documents\cannabis-main-new\coltivazionecanapa>
```

It doesen't even start. Does anyone have any idea about what can be the problem?

### Reproduction

N/a

### System Info

```shell
Windows 10
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
> It doesen't even start

Do you mean the 11ty process doesn't start?

Can you try running 2 terminals, one for your 11ty process and the other for Tina? This will help point us in the right direction.

**Comment by makovez** [comment]
No, tiny doesn't start. My process starts.

**Comment by jeffsee55** [comment]
Can you provide a reproduction?

**Comment by makovez** [comment]
Is it ok if i put you as temporary contributor in my private repo?

**Comment by makovez** [comment]
[jeffsee55](https://github.com/jeffsee55) i added you as collaborator

**Comment by jeffsee55** [comment]
Sorry @makovez - I think this was resolved with this PR https://github.com/tinacms/tinacms/pull/3809. Can you try to update to the latest versions of `@tinacms/cli` and `tinacms`

**Comment by kldavis4** [comment]
If it's a port conflict, you can use `--datalayer-port` to select a different port (ie 9001)

**Comment by makovez** [comment]
Yes, it works now. Thanks @jeffsee55 and @kldavis4
