### ISSUE TITLE
Indexing branch failed after upgrading to TinaCMS 1.4.3

### ISSUE THREAD

**Issue by niutech** [tinacms/tinacms#3781]
I've upgraded Tina from 1.3.2 to 1.4.3 and moved `.tina/config.js` to `tina/config.js` accordingly. But now reindexing my branch raise errors:
```
indexing branch failed
3320a569-eb2e-49cf-98ee-bf3d3a892a40
indexing branch failed
0c24d7e5-ff86-4835-bf44-6d4b75abb28c
indexing branch failed
ce6de6f8-7e96-4705-8da6-4056df7d5b7d
```
What is the reason?

Client ID: d990a877-78ef-4a59-b3e4-e98cf4e1d676

### Reproduction

https://github.com/nexocodecom/nexocode-web

### Steps to reproduce

1. Upgrade tinacms to 1.4.3
2. Commit and push the updated files
3. Go to Project Configuration
4. Reindex branch

### System Info

```shell
System:
    OS: Windows 10 10.0.19044
    CPU: (8) x64 Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz
    Memory: 2.10 GB / 15.80 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\Workspace\nexocode-web\node_modules\.bin\yarn.CMD
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@niutech that reproduction branch doesn't appear to be public. Did you commit the `tina/tina-lock.json` that is generated after moving `.tina` -> `tina` ?

**Comment by niutech** [comment]
That's it! I've forgot to add `tina-lock.json` to git. Now it reindexes succesfully. Thanks!
