### ISSUE TITLE
TinaCMS throws the following error upon attempting to run a Contextual Edit via TinaCloud

### ISSUE THREAD

**Issue by bazhang87** [tinacms/tinacms#3798]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

TinaCMS throws the following error upon attempting to run a Contextual Edit via TinaCloud.
<img width="1728" alt="Screenshot 2023-04-10 at 4 47 39 PM" src="https://user-images.githubusercontent.com/60352611/231005391-8f610ea9-a027-46c5-ba44-b76335db407a.png">

Tina Config located here:
https://github.com/bazhang87/bootstrap-gptaas/

### Reproduction

https://bootstrap-gptaas.vercel.app/blog/test-article-2

### Steps to reproduce

Login to Tina Cloud via <domain>/admin and GitHub oauth.
Visit Blog post 

Output:

TinaCMS Render Error
Tina caught an error while updating the page:

Cannot read properties of null (reading 'getPostsDocument')

If you've just updated the form, undo your most recent changes and click "refresh". If after a few refreshes, you're still encountering this error. There is a bigger issue with the site. Please reach out to your site admin.

### System Info

```shell
Hosted on Vercel.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
If you update the @tinacms/cli to 0.60.14 or above (preferably 0.60.23) then that undefined error should be resolved. See this discord thread for background: https://discord.com/channels/835168149439643678/1093217476394885222
