### ISSUE TITLE
npm WARN ERESOLVE overriding peer dependency error whensetting up TinaCMS with Eleventy

### ISSUE THREAD

**Issue by babel222** [tinacms/tinacms#3806]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I has trouble migrating an eleventy web site from forestry to tinacms so I tried to install tinacms on a very basic eleventy site I build from scratch without using forestry. Nevertheless I get the same errors, so here is what I'm doing hoping you can help

I have node.js v18.15.0 runing with debian 11 bullseye

first I execute npx @tinacms/cli@latest init here I had to sudo it otherwise I get an Error: Cannot find module 'tslib'

when I sudo the process starts :

- I disguard the client ID 
-I choose NPM as package manager
- I choose other for framework
- I answer Y for using Typescript
- I enter _site as the public folder name

then I got the  message Adding dependencies, this might take a moment...
  ┃ npm install tinacms @tinacms/cli

and after a while I get the following error message :

Error occured during tinacms init
Error: Command failed: npm install tinacms @tinacms/cli
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
npm WARN ERESOLVE overriding peer dependency
Killed

    at ChildProcess.exithandler (node:child_process:419:12)
    at ChildProcess.emit (node:events:512:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 137,
  killed: false,
  signal: null,
  cmd: 'npm install tinacms @tinacms/cli'
}

What's the problem here ?

### Reproduction

npx create-tina-app@latest

### System Info

```shell
node.js v18.15.0 runing with debian 11 bullseye
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by david-gagne** [comment]
I'm also having this issue. I'm running node.js v18.9.0 with macOS Ventura (v13.4) on a 2020 M1 MacBook Air.
