### ISSUE TITLE
Wrong path set when uploading picture using blue "Upload" button

### ISSUE THREAD

**Issue by MattCCC** [tinacms/tinacms#3813]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Wrong path is set when uploading picture using blue "Upload" button. Basically I have next.js app. I added tina, I added following config to upload image:

```
        {
            type: "string",
            name: "image1",
            label: "Image #1",
            required: true,
            ui: {
                component: "image",
            },
        },
```

When I click blue button to Upload media, expected behavior would be that media is uploaded to particular sub directory. Currently it's always uploaded to the root of public/ directory.

I also tried following:
```
        {
            type: "string",
            name: "image1",
            label: "Image #1",
            required: true,
            ui: {
                component: "image",
                parse: (fullSrc: any) =>
                    `${
                        typeof fullSrc === "string"
                            ? fullSrc
                            : `/img/projects/${fullSrc.filename}`
                    }`,
            },
            previewSrc: (fullSrc: string) => fullSrc.replace("/public", ""),
        },
```

But it didn't help either.

### Reproduction

https://donthave.com

### Steps to reproduce

1. Install tina
2. Add image field
3. Add a sub-directory to Media dir
4. Try to upload picture to the subdirectory

### System Info

```shell
Brake
Node 16
Next.js 13
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@MattCCC This sounds like a good use case [for `mediaRoot`](https://tina.io/docs/reference/media/repo-based/). Have you tried that? 

If you publicFolder is "public" and mediaRoot is "img/projects" your images will be uploaded to public/img/projects.

**Comment by logan-anderson** [comment]
If media root does not fit your use case and you are looking for this to be configurable on a per field bases you can try using `uploadDir`. (It would be better to use `mediaRoot` if all your images are in `/img/projects` )


```tsx
        {
            type: "image",
            name: "image1",
            label: "Image #1",
            required: true,
            ui: {
                  uploadDir: ()=>"/img/projects"
            },
        },
```
**One other note:** 

Why are you doing? 

```tsx
        {
           //...
            type: "string",
            ui: {
                 component: 'image',
            },
        },
```

This will cause issues if you are using Git backed media. It could be the cause of your current issue.

Maybe try?

```tsx
        {
           //...
            type: "image",
        },
```


cc @MattCCC  @PothieuG

**Comment by PothieuG** [comment]
I'm facing the same issue. 
When using `uploadDir`, my file always ends up at the root of my `public` folder, despite having a folder structure in TinaCMS that suggests I'm uploading to the right place.
