### ISSUE TITLE
Block alias nameOverride gets ignored

### ISSUE THREAD

**Issue by kslstn** [tinacms/tinacms#3824]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I've defined an 'Embed' template like this:
```
{
  label: 'Test label',
  name: 'test',
  nameOverride: 'my test name override',
  match: {
    start: '{',
    end: '}',
  },
  fields: [{
    label: 'Label',
    name: 'name',
    type: 'boolean',
  }]
},  
```
When I insert that shortcode via the Embed button, Tina inserts:
```
{ test }
```
I would expect it to be:
```
{ my test name override } 
```

### Reproduction

https://github.com/kslstn/tina-issues

### Steps to reproduce

Apply [this change](https://github.com/kslstn/tina-issues/commit/4608c3a6d35838a0f4788733f59a32c41832cdfa#diff-4bc82ba51f58f7590755b31d4b4910ef5d9853480f52c801a9739f51e234afd3) to `config.js`.

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 73.28 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.0.0 - ~/.nvm/versions/node/v19.0.0/bin/node
    Yarn: 1.22.19 - ~/Documents/Werk/ForTomorrow/Website/fortomorrow-website/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v19.0.0/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 112.0
    Safari: 16.2
  npmPackages:
    @tinacms/cli: ^1.5.6 => 1.5.6 
    tinacms: ^1.4.6 => 1.4.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@kslstn Do you mind providing your entire schema? 

I _believe_  the name override property was originally meant for content and not short codes.

**Comment by kslstn** [comment]
It should be in [the repo I linked to](https://github.com/kslstn/tina-issues) (we can't even submit issues without linking to one).

**Comment by logan-anderson** [comment]
> It should be in [the repo I linked to](https://github.com/kslstn/tina-issues) (we can't even submit issues without linking to one).

@kslstn  My bad! Sorry for missing this. 

Looks like this can be obtained with [`name` property in match](https://tina.io/docs/reference/types/rich-text/#using-shortcode-names-with-dashes)


EX
```
{
  label: 'Test label',
  name: 'test',
  match: {
    start: '{',
    end: '}',
    name: 'my test name override,
  },
  fields: [{
    label: 'Label',
    name: 'name',
    type: 'boolean',
  }]
}, 
```
I could understand this being confusing though we might consider consolidating these.

**Comment by kslstn** [comment]
Yes, that was it! Unlike in other `name`s, I can even include special characters, so now I can specify Jekyll _includes_ like this:
```
  label: 'Test label',
  name: 'test',
  match: {
    start: '{%',
    end: '%}',
    name: 'include directory/filename.extension',
  },
```
Thanks!

**Comment by kslstn** [comment]
Sorry - didn't mean to close it. I think you had a point about considering consolidating—it's definetely confusing to me and IMO at least requires some documentation.
