### ISSUE TITLE
413 Content Too Large

### ISSUE THREAD

**Issue by pbougie** [tinacms/tinacms#3831]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Trying to save a JSON file that is over 100 KB in size fails in TinaCMS (in development mode). Tested under 100 KB and it worked as expected. The error in the console is : `[vite] Internal server error: request entity too large`. This limit needs to be increased or made configurable.

### Reproduction

https://github.com/pbougie/tinacms-20230419

### Steps to reproduce

- Clone repo.
- Start with `yarn install` and `yarn dev`.
- Go to `http://localhost:3000/admin/`.
- Go to `News`.
- Make a change to any news item and **Save**.
- See console for error.

### System Info

```shell
System:
  OS: macOS 13.3.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 2.39 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 19.9.0 - /usr/local/bin/node
  Yarn: 1.22.19 - ~/Downloads/tinacms-20230419/node_modules/.bin/yarn
  npm: 9.6.3 - /usr/local/bin/npm
Browsers:
  Chrome: 112.0.5615.121
  Firefox: 112.0.1
  Firefox Nightly: 114.0a1
  Safari: 16.4
npmPackages:
  @tinacms/cli: ^1.5.2 => 1.5.2 
  tinacms: ^1.4.3 => 1.4.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@pbougie is this also happening in production or is it only a local dev issue?

**Comment by logan-anderson** [comment]
@pbougie Found the issue and it is fixed in [this PR](https://github.com/tinacms/tinacms/pull/3837)

**Comment by pbougie** [comment]
@logan-anderson Is there a way to install Tina directly from GitHub using `npm`? I'm in limbo with my clients not being able to edit their sites since Forestry is deprecated and this bug fix being unreleased as a package. Thanks.
