### ISSUE TITLE
ui.format not working as expected

### ISSUE THREAD

**Issue by pbougie** [tinacms/tinacms#3832]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When saving a date with the configuration shown below, the date is saved as `2023-04-19T00:00:00.000Z` instead of `2023-04-19`. It formats the date correctly in the UI but does not when saved back to JSON. My understanding is the `parse` method is to format the attribute before saving to file. See https://tina.io/docs/extending-tina/format-and-parse/.

```
{
  type: "datetime",
  name: "date",
  label: "Date",
  required: true,
  ui: {
    dateFormat: "YYYY-MM-DD",
    parse: (value) => value && value.format("YYYY-MM-DD"),
  }
}
```

### Reproduction

https://github.com/pbougie/tinacms-20230419

### Steps to reproduce

- Clone repo.
- Start with `yarn install` and `yarn dev`.
- Go to `http://localhost:3000/admin/`.
- Go to `News 2`.
- Change the date of any news item and **Save**.
- Check the JSON in `content/news2.json`.

### System Info

```shell
System:
  OS: macOS 13.3.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 2.39 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 19.9.0 - /usr/local/bin/node
  Yarn: 1.22.19 - ~/Downloads/tinacms-20230419/node_modules/.bin/yarn
  npm: 9.6.3 - /usr/local/bin/npm
Browsers:
  Chrome: 112.0.5615.121
  Firefox: 112.0.1
  Firefox Nightly: 114.0a1
  Safari: 16.4
npmPackages:
  @tinacms/cli: ^1.5.2 => 1.5.2 
  tinacms: ^1.4.3 => 1.4.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@pbougie Are you seeing this behaviour with parse in general? Or just the date field? 

Thanks for submitting this issue

**Comment by pbougie** [comment]
@logan-anderson I've only used the `parse` method with dates so far.

**Comment by jamespohalloran** [comment]
On the backend, the date field exports as a date, and not a string, so I'd expect this is outside the context of ui.format. 

If you want to export the value as a string, you can use a string field, and choose a custom component (we have a 'date' field as an available built-in component).

```
          {
            type: 'string',
            label: 'DateStr',
            name: 'DateStr',
            ui: {
              component: 'date',
              dateFormat: 'YYYY-MM-DD',
              parse: (value) => value && value.format('YYYY-MM-DD'),
            },
          },
```

**Comment by jamespohalloran** [comment]
I see our playground example was out of date, I've just updated it: https://github.com/tinacms/tina-playground/pull/23
Let us know if you have any issues!

**Comment by 985563349** [comment]
> On the backend, the date field exports as a date, and not a string, so I'd expect this is outside the context of ui.format.在后端，日期字段导出为日期，而不是字符串，所以我希望这超出了 ui.format 的上下文。
> 
> If you want to export the value as a string, you can use a string field, and choose a custom component (we have a 'date' component as an available built-in component).如果要将值导出为字符串，可以使用字符串字段，然后选择自定义组件（我们有一个“date”组件作为可用的内置组件）。
> 
> ```
>           {
>             type: 'string',
>             label: 'DateStr',
>             name: 'DateStr',
>             ui: {
>               component: 'date',
>               dateFormat: 'YYYY-MM-DD',
>               parse: (value) => value && value.format('YYYY-MM-DD'),
>             },
>           },
> ```

Thank you for your plan. The code is working as expected. But when used in Typescript, a type error occurs: the dateFormat attribute does not exist in StringField.
