### ISSUE TITLE
SVG images do not always appear

### ISSUE THREAD

**Issue by pbougie** [tinacms/tinacms#3835]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have some SVG images that appear as expected in the **Media Manager** but do not appear using the `image` field type in the collections. The screenshot below shows the image controls without the image.

<img width="96" alt="Screenshot 2023-04-20 at 10 46 28" src="https://user-images.githubusercontent.com/58460/233404448-222bf3b5-03e5-4d03-be7e-0b5b4466f476.png">

### Reproduction

https://github.com/pbougie/tinacms-20230419

### Steps to reproduce

- Clone repo.
- Start with `yarn install` and `yarn dev`.
- Go to `http://localhost:3000/admin/`.
- Go to `News 3`.
- Select the first item for either language.
- SVG does not appear but should.

### System Info

```shell
System:
  OS: macOS 13.3.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 1.03 GB / 32.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 20.0.0 - /usr/local/bin/node
  Yarn: 1.22.19 - ~/Downloads/tinacms-20230419/node_modules/.bin/yarn
  npm: 9.6.4 - /usr/local/bin/npm
Browsers:
  Chrome: 112.0.5615.137
  Firefox: 112.0.1
  Firefox Nightly: 114.0a1
  Safari: 16.4
npmPackages:
  @tinacms/cli: ^1.5.2 => 1.5.6 
  tinacms: ^1.4.3 => 1.4.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@pbougie Looks like there is no `width` or `height` property on `bmo.svg` and we do not have a min width or min height. Looks like it is rendering the image but it is 0px by 0px. 

The sort term fix is to add `width="500"` (or something like that) to your image (This might not be ideal). We should be able to put out a fix on our end to set a min width for that image.

Thanks for submitting this issue.

**Comment by logan-anderson** [comment]
cc @spbyrne

**Comment by spbyrne** [comment]
I can add a default minimum width for SVG images given they don't have an intrinsic minimum size. Thanks for reporting this issue!
