### ISSUE TITLE
Hide invisible dot files (.gitkeep, .DS_Store, etc.) inside Media Manager

### ISSUE THREAD

**Issue by appinteractive** [tinacms/tinacms#3849]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

![grafik](https://user-images.githubusercontent.com/432828/233949423-26c04dc4-dcb5-40c3-bad8-3709cbdd70c2.png)

### Reproduction

example.com

### Steps to reproduce

1. have an project with .gitkeep files in media folders
2. open media manager
3. see dot files (which are not media)

### System Info

```shell
npx envinfo --system --npmPackages '{tinacms,@tinacms/*}' --binaries --browsers

  System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 80.56 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/Projekte/Mischa/grenzen-sind-relativ-tina/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Brave Browser: 112.1.50.121
    Firefox: 112.0.1
    Safari: 16.4
  npmPackages:
    @tinacms/cli: ^1.5.6 => 1.5.6
    tinacms: ^1.4.6 => 1.4.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
Do these files also show up in production?

**Comment by appinteractive** [comment]
Yes

**Comment by appinteractive** [comment]
Not the .DS_Store as it's not part of the build but the .gitkeep is shown also on production yes

**Comment by appinteractive** [comment]
Any updates on this one?
