### ISSUE TITLE
Console Errors in Barebones Starter

### ISSUE THREAD

**Issue by eckmancaleb** [tinacms/tinacms#3857]
When creating a new project using the Tina Cli and choosing the barebones starter, the following console errors appear when navigating to a page with live editing:

![Screenshot 2023-04-24 212337](https://user-images.githubusercontent.com/14187108/234151894-1699e293-ca39-4ab9-b0a9-b081a2c8d1e9.png)

### Steps to Reproduce

- Create a new project using the Tina Cli
- Windows environment
- Choose the barebones starter
- Choose NPM
- Run the development server
- Console errors will appear after navigating to the page list and then back to the home page
- A different console error will appear when navigating to the Media Manager:

![Screenshot 2023-04-24 212656](https://user-images.githubusercontent.com/14187108/234152242-5e83b366-46e5-40f1-a4ce-f86571468858.png)

Are there any other configuration or installation steps needed to fix these errors? Thanks!

**Comment by logan-anderson** [comment]
I think this is fixed with [this PR](https://github.com/tinacms/tinacms/pull/3855)

cc @kldavis4
