### ISSUE TITLE
When running tinacms build in Netlify or locally I get: Error when checking client information. Error: Server responded with status code 403, Forbidden.

### ISSUE THREAD

**Issue by elneto** [tinacms/tinacms#3869]
Hi!

I am running out of ideas here. I am running a hugo site and I am trying to migrate it from forestry.io to tinacms.

When I run `npm run dev` (tinacms dev) I am able to use the admin perfectly. 

However, when I run `npm run build` or `tinacms build` either in my local environment or in a netlify deployment,  I keep getting the same error.

I triple checked the clientId and the token. I have tried configuring the URL to our PROD one and I have tried adding * instead in the tinacms configuration in https://app.tina.io/ I have tried adding clientId and token as environment variables in Netlify. But the issue also happens in my local environment.

I can see both master and dev branches being tracked in the web app.

I can't find any answer in here: https://tina.io/docs/errors/faq/

Am I missing something? Any help would be appreciated. Thanks!

Part of package.json: 

```
"scripts": {
    ...
    "dev": "tinacms dev -c \"hugo server -D\"",
    "build": "tinacms build && tailwindcss -i ./themes/tella/assets/css/main.css -o ./themes/tella/assets/css/style.css && hugo --minify"
```

Part of ./tina/config.ts:

```
// Your hosting provider likely exposes this as an environment variable
const branch = process.env.HEAD || process.env.VERCEL_GIT_COMMIT_REF || "main" || "master" || "dev";

export default defineConfig({
  branch,
  clientId: "XXX", // Get this from tina.io
  token: "XXX", // Get this from tina.io
  client: { skip: true },
```

**Comment by elneto** [comment]
Oh, my bad. I was not aware tokens were tied to a branch. I created a new token with '*' and it works. There is a new error though. Please see below. I tried changing the name in config.ts to dev (where I pushed my changes). And I tried reindexing the branches (which generates an error seen in the screenshot). 

```
Checking local GraphQL Schema matches server. ❌
Error: The local GraphQL schema doesn't match the remote GraphQL schema. Please push up your changes to Github to update your remote GraphQL schema.

I cannot reset the repository cache. It gives me an error too. Thanks for your help!

_Unexpected error resetting repository cache. Please contact us for further assistance._

Additional info: Branch: main, Client ID: cd383d43-0d53-4144-8398-415096f75d4f
```

![image](https://user-images.githubusercontent.com/8921830/234877459-18022de0-16f3-4a3c-9417-a33e143c13cb.png)

**Comment by kldavis4** [comment]
It sounds like you have changes to your `.tina/__generated__/_schema.json` which have not been committed and pushed to the branch `main`

**Comment by elneto** [comment]
That was exactly the case. It still did not work in the dev branch but renaming to main and pushing it there made it work both in local and in Netlify. Hope that this issue helps other people experiencing similar issues. Closing this ticket. I appreciate your time replying to this. Thank you very much!

**Comment by ThePresence** [comment]
I'm facing the same issue. Is there any way to resolve this issue without renaming the branch?
