### ISSUE TITLE
Add back `host` option

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#3871]
Hey there, I'm late to the party - sorry for that! Never had my hands on tinacms before the migration from forest.io

While attempting the migration, an issued occurred which - I think - originated in this pull request. Previously there was an Option to expose the Vite server externally (introduced by #3484 by @logan-anderson) - which doesn't seem to be there anymore.

When we run `tinacms dev --verbose -c nuxt` (which is configured to listen to Port `3000`), I have the following processes on those open ports in the container:

```
# netstat -nltp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.11:43609        0.0.0.0:*               LISTEN      -
tcp        0      0 0.0.0.0:3000            0.0.0.0:*               LISTEN      68/node
tcp        0      0 127.0.0.1:4001          0.0.0.0:*               LISTEN      31/node
tcp6       0      0 :::9000                 :::*                    LISTEN      31/node
```

to toy around with and potentially get tinacms up and running, we need the `4001` port configured the same way. I see how the default `4001` port gets passed down in the `dev-command` ([reference](https://github.com/tinacms/tinacms/blob/a982b105d685fc343b989462c882d56c72a04007/packages/%40tinacms/cli/src/next/commands/dev-command/index.ts#L195)) - but the `host` for [Vite needs `server.host` to be passed as part of their Configuration Object](https://vitejs.dev/config/server-options.html#server-host).

So far for my analysis - any suggestions on how to take it further @jeffsee55? I'm not very familiar with tinacms, but would like to help .. if you let me know _how_. 

Thanks
-Stefan

_Originally posted by @steffkes in https://github.com/tinacms/tinacms/issues/3659#issuecomment-1520077320_

**Comment by ralexrdz** [comment]
I'm also trying to run tina with hugo on a docker container. So, with latest version I can now set `server,host` on config file and that should do it? I'll set up a fork and test it and I'll let you know if it works. If it does not work, please let me know what I could be missing

**Comment by ralexrdz** [comment]
I've tested this with this repository: https://github.com/tinacms/tina-hugo-starter

Using this Dockerfile:
```
FROM klakegg/hugo:ext-alpine 
WORKDIR /app
RUN npm i -g yarn
COPY package.json yarn.lock ./
RUN yarn install
COPY . /app
EXPOSE 3000
ENTRYPOINT ["yarn"]
CMD ["dev"]
```

I updated tinacms to latest version using this command: `npm i tinacms@latest`

I updated `tina/config.ts` file to this, adding `build.host: true`:

```
import { defineStaticConfig } from "tinacms";

// Your hosting provider likely exposes this as an environment variable
const branch = process.env.HEAD || process.env.VERCEL_GIT_COMMIT_REF || "main";

export default defineStaticConfig({
  clientId: process.env.TINA_CLIENT_ID!,
  branch:
    process.env.TINA_BRANCH! || // custom branch env override
    process.env.VERCEL_GIT_COMMIT_REF! || // Vercel branch env
    process.env.HEAD!, // Netlify branch env
  token: process.env.TINA_TOKEN!,
  build: {
    outputFolder: "admin",
    publicFolder: "static",
    host: true 
  },
  media: {
    tina: {
      mediaRoot: "uploads",
      publicFolder: "static",
    },
  },
  schema: {
    collections: [
      {
        name: "post",
        label: "Posts",
        path: "content/posts",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          {
            type: "datetime",
            label: "Date",
            name: "date",
          },
          {
            type: "boolean",
            name: "draft",
            label: "Draft",
          },
          {
            type: "rich-text",
            name: "body",
            label: "Body",
            isBody: true,
          },
        ],
      },
    ],
  },
});

```

which installed version 1.5.4

But still after building and running container, cant access admin page and shows this errors

![image](https://user-images.githubusercontent.com/3052915/236354653-3b1198b7-5cf5-4785-aeb8-8f13f8b8d137.png)

Project works perfectly if instead of docker i just run it locally, but I want to deploy this image on a server with multiple other services. 

Let me know if I'm doing something wrong or you want me to set up a test repository to make this possible
