### ISSUE TITLE
Getting error "error loading dynamically imported module" while switching from rich text to Markdown.

### ISSUE THREAD

**Issue by ThePresence** [tinacms/tinacms#3890]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Getting error `error loading dynamically imported module` while switching from rich text to Markdown.

![image](https://user-images.githubusercontent.com/19200271/235499159-f401c63a-940e-47ab-ad49-761a84965baa.png)

### Reproduction

[virendra.dev](https://virendra.dev/blog/)

### Steps to reproduce

Login to Tina Cloud via /admin and GitHub oauth.
Visit Blog post, then edit the blog post and click on markdown icon.

Note: On localhost, it's working fine.

```
TinaCMS Render Error

Tina caught an error while updating the page:

error loading dynamically imported module


If you've just updated the form, undo your most recent changes and click "refresh". If after a few refreshes, you're still encountering this error. There is a bigger issue with the site. Please reach out to your site admin.

See our Error FAQ for more information.
```

### System Info

```shell
Hosted on Netlify
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@ThePresence I was unable to re-produce this. What version of TinaCMS are you using? Can you make a reproduction repo (Or temporarily invite me to your repo)? 

Thanks 😄

**Comment by ThePresence** [comment]
Hi,
I'm using Tina CMS 1.5.2 with Astro JS. Somehow everything is working fine on localhost, but issue persist on production.

**Comment by logan-anderson** [comment]
@ThePresence 

I pulled down the repo (Made a fork so I could set it up with app.tina.io)
I ran `npm install` (It did change the package-lock file)
I ran `npm run build`
I ran `nun run preview` 

and I did not see the issue

See: https://www.loom.com/share/ab6a91326f524efbab3be53d534883ce

Is it possible you need to run install, update the lock file and push that up? 

Let me know if there is something I am missing here. The only other thing I can think of is if its a netilfy deploy issue.

**Comment by ThePresence** [comment]
@logan-anderson Thank you for the reply. Everything is working fine when I run it on localhost but when I deploy it on netlify then only I'm facing this issue. And I'm using yarn. I'll try using npm today.

**Comment by logan-anderson** [comment]
@ThePresence I can try to deploy to netilfy and see if I can re-produce the isssue.

**Comment by ThePresence** [comment]
@logan-anderson  Thank you for the response.

These are the errors I'm getting.

![image](https://github.com/tinacms/tinacms/assets/19200271/7b00815f-5dce-437b-9c8c-78c78418c8d0)

**Comment by logan-anderson** [comment]
@ThePresence It looks like your browser may be blocking some javascript. What browser are you using?  do these error also show up is default chrome?

**Comment by jeffsee55** [comment]
I'm not sure why it's requesting that asset from a URL other than the one being served. I guess Netlify does some proxying that makes this work. I would expect `/admin/assets/index-e8976463.js` to come from the same domain as your site. 

Do you anything unusual with your Netlify setup?

**Comment by ThePresence** [comment]
> I'm not sure why it's requesting that asset from a URL other than the one being served. I guess Netlify does some proxying that makes this work. I would expect `/admin/assets/index-e8976463.js` to come from the same domain as your site. 
> 
> Do you anything unusual with your Netlify setup?

No, I'm using default configs.

**Comment by logan-anderson** [comment]
Hey there, @ThePresence!

I wanted to follow up with you regarding the issue you mentioned earlier. After checking things out, I wasn't able to reproduce the issue on Netlify.

I did make a quick video to show you what I did and what I saw. Here's the link: https://www.loom.com/share/b7f78eb03fc943e78d69313e4a2f9d14

It's possible that a stale URL is being cached on a CDN or something, or that the error you mentioned could pop up if the site "rebuilds" while you're editing.

Please feel free to reach out here if you have any questions or concerns. However, I should mention that without a way to reproduce this error, it will be impossible to fix it. Thanks for your help!

**Comment by ThePresence** [comment]
Hi @logan-anderson

I've tried to open it in incognito, tried different browsers and cleaned cache then build on netlify but still getting the same error.
Can you tell me what steps have you followed so that I will try to do the same.

**Comment by logan-anderson** [comment]
> 



> Hi @logan-anderson
> 
> I've tried to open it in incognito, tried different browsers and cleaned cache then build on netlify but still getting the same error. Can you tell me what steps have you followed so that I will try to do the same.

This is what I did
- Forked your repo
- Put in my own app.tina.io credentials in the schema 
- Added repo to netilfiy with default build commands   
   - Build command: npm run build
   - Publish directory: dist
- Logged in and was able to edit raw markdown

**Comment by ThePresence** [comment]
@logan-anderson 
So I've disabled asset optimization in Netlify and everything seems working fine.
Thank you so much for all the efforts. 👍
