### ISSUE TITLE
Saving "assets.tina.io" to file when uploading media

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3892]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am uploading an image, and seeing "assets.tina.io" added to the content

<img width="1501" alt="Screen Shot 2023-05-01 at 4 25 38 PM" src="https://user-images.githubusercontent.com/3323181/235515866-845c8418-26b9-4eb0-a494-e189a37b6b77.png">

It should save media with relative path

### Reproduction

https://github.com/jamespohalloran/jekyll-media-test

### Steps to reproduce

- With the above repo, host on Netlify (Or ask james for acces to https://fantastic-valkyrie-76788a.netlify.app)
- Upload an image to a blog post

### System Info

```shell
See https://github.com/jamespohalloran/jekyll-media-test
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
Digging into this the issue appears to be to with `publicFolder: "/",`  if you set `publicFolder: "./",` it works as expected.
