### ISSUE TITLE
Installing not working

### ISSUE THREAD

**Issue by carolineolivia** [tinacms/tinacms#3904]
Getting this when running `npm install tinacms @tinacms/cli`

![image](https://user-images.githubusercontent.com/17065639/236205867-fad348b2-e30d-45b6-8159-309a060cfb17.png)

### Reproduction

https://github.com/copenhagencoaching/copenhagencoaching.dk

### System Info

```shell
System:
    OS: macOS 11.6.5
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 37.98 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /usr/local/bin/node
    npm: 9.5.1 - /usr/local/bin/npm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
The error message in your screenshot indicates that you need to free up disk space
