### ISSUE TITLE
Images not visible

### ISSUE THREAD

**Issue by elax46** [tinacms/tinacms#3916]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

By accessing the admin area in any published post the images are not visible. In the media manager the images are loaded correctly but in the editor they are not visible
![Screenshot 2023-05-06 201938](https://user-images.githubusercontent.com/55278049/236640575-3605e641-5501-4578-9337-40bdac1ce2df.png)

The problem occurs both locally and in distribution via netlify. I also tried switching browsers and clearing the cache but nothing

### Reproduction

npx create-tina-app@latest

### System Info

```shell
Binaries:
    Node: 18.16.0 
    Yarn: 1.22.19 
    npm: 8.3.0 
  Browsers:
    Chrome: 113.0.5672.63
    Edge: Spartan (44.22621.1635.0), Chromium (112.0.1722.68)
    Internet Explorer: 11.0.22621.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
To initialize media in your project, you'll need to click "sync" in the media manager from the TinaCMS sidebar

**Comment by elax46** [comment]
> To initialize media in your project, you'll need to click "sync" in the media manager from the TinaCMS sidebar

Already done the images are correctly visible in the Media manager and in the posts that are not seen

**Comment by jamespohalloran** [comment]
Hey, sorry for the delay getting back to you. Could you copy the URL that's in the HTML of the broken thumbnail?
Also, could you share the image that is failing to load for you?

**Comment by elax46** [comment]
> Ehi, scusa per il ritardo nel risponderti. Potresti copiare l'URL che si trova nell'HTML della miniatura danneggiata? Inoltre, potresti condividere l'immagine che non riesce a caricare per te?

doing a more in-depth check I noticed that a further link to `assets.tina.io `cms is inserted in the Markdown example:

`![image](https://assets.tina.io/305bf938-d8d2-41c5-ab47-b12d2cf62b85imagelink.jpg)`
