### ISSUE TITLE
Unable to create a new barebones or tina cloud starter projects

### ISSUE THREAD

**Issue by ggalicia2021** [tinacms/tinacms#3925]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Current behavior: 

I am unable to create a new tina cloud or barebones starter project. I am using the instructions from here (Dashboard quickstart): 
https://tina.io/docs/setup-overview/

I successfully created two projects with the same instructions back in Nov. 2022 and on Feb. 2023. I have not been able to create these starter projects as of April 24th, 2023. 

There are two main issues that constantly come up when creating any of the above starter projects. 

1. GitHub Authentication keeps on loading for over 10 mins. It never finishes.
2. The project is visible in Vercel but it always fails due to a missing a client id. 

### Screenshot

![image](https://github.com/tinacms/tinacms/assets/75684967/33efd9d6-ea09-4186-b76e-bafde3c9c4ff)

### Reproduction

https://app.tina.io/quickstart

### Steps to reproduce

Follow the tina cloud or barebones starter steps. 

### System Info

GitHub authentication never finishes loading. 
The Vercel build fails with missing client id.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by ggalicia2021** [comment]
I am using Tina as a new user with admin role.

**Comment by logan-anderson** [comment]
@ggalicia2021 I just went threw the flow with no issues. If you go to the "environment variables" section of the settings are the environment variables set? 

Should have the following
<img width="344" alt="Screenshot 2023-05-12 at 10 07 58 AM" src="https://github.com/tinacms/tinacms/assets/43075109/58bed783-a837-4b9e-b033-400f5c2292f7">

**Comment by bradstockUser** [comment]
Im also having trouble with creating a new project and importing an existing project on GitHub, bc the authenticate with gut hub btn just has a loading page and never authenticates... I miss forestry

**Comment by kldavis4** [comment]
@bradstockUser if you want help with this issue please open a thread in discord: https://discord.com/invite/zumN63Ybpf in the #help channel
