### ISSUE TITLE
Lists are broken in the WYSIWYG editor

### ISSUE THREAD

**Issue by jpatters** [tinacms/tinacms#393]
## Description

Pressing enter at then end of a list item in the wysiwyg editor should create a new list item and it does not

### Steps to reproduce

Use the wysiwyg editor to create a list (ordered, or unordered). Press enter at the end of the first list item

### Expected result

It should create another list item

### Actual result

It does not create another list item

### Environment

macOS

**Comment by ncphillips** [comment]
@all-contributors please add @jpatters for bugs

**Comment by kendallstrautman** [comment]
Is our `prosemirror-schema-list` package up to date? Looks like they released a patch for this in the past month - https://discuss.prosemirror.net/t/possible-regression-in-splitlistitem-prosemirror-schema-list/2257

**Comment by kendallstrautman** [comment]
Looks like `@types/prosemirror-schema-list` needs to be updated but its not in sync with the latest regular version 1.0.4

**Comment by kendallstrautman** [comment]
Maybe not, looks like were on the updated version --> 1.0.4

**Comment by ncphillips** [comment]
I have an idea of why this might be happening. Looking into it now
