### ISSUE TITLE
🐛Bug - Previously invited SSO users must be invited using the same case

### ISSUE THREAD

**Issue by leahy268** [tinacms/tinacms#3937]
Hi Guys,

This appears to be a bug.  When inviting users to our organization we regularly have issues with them not being able to accept the invite.  Instead Tina asks them to sign up and they never see our organization.  The invite also always appears pending.

Recently I deleted a couple of these users and then reinvited them and got this error message:
![image](https://github.com/tinacms/tinacms/assets/58454534/f0b559b0-9efa-4943-a6af-9aa0528b13aa)
**Figure: UserNotFoundException: User does not exist**

This error was deemed to be an uppercase/lowercase issue.  I initially invited the user as firstnamelastname@email and then had to change that to FirstnameLastname@email to match their UPN from when they signed up with the invite.

This is weird behavior, as if I delete the user from the organization then I must re-invite them so 'user does not exist' shouldn't be an error that should be expected.  But also email addresses are not case sensitive.

Thanks

Warwick

_Originally posted by @leahy268 in https://github.com/tinacms/tinacms/discussions/3926_

**Comment by jamespohalloran** [comment]
Seems like there may be 2 issues here. 
- 1. When you sign up with an email, it's case-sensitive, so you must login with the exact same email. (If I understand correctly, this isn't really a bug, but definitely makes for an awkward UX)
- 2. Re-inviting users after deleting them gives a "User does not exist" error. 

Does that sounds like an accurate summary @leahy268?

One thing I'm unclear on is if this part is a side-effect of issue #1:

> When inviting users to our organization we regularly have issues with them not being able to accept the invite. Instead Tina asks them to sign up and they never see our organization. The invite also always appears pending.

Any ideas on that @kldavis4 ?

**Comment by adamcogan** [comment]
Hi support

Upper/lower case issues are always painful. ⚠️

❌ Email addresses are definitely not case sensitive ... so I would consider a bug 

FYI This is a blocking issue...

-a
www.AdamCogan.com

**Comment by jamespohalloran** [comment]
Hi Adam,

Understood regarding email addresses being case-insensitive, and pains around upper/lowercasing. We use email addresses as usernames in our system. While usernames should ideally be case-insensitive in our system, it would require a large migration that might be a big lift in the short-term. 

What you should be able to do is invite users onto your project (not the organization). Once they receive the invite and click the link, they will login with their SSW email address and be added to the project. Once you confirm that this is done, if you still need them to be added to the organization (to make them an org admin for example), you must invite them using the case sensitive email address.

As for the "User Not Found" error, if that continues to arise I'd like to hear more about how that surfaces. I tried to reproduce and could not, so I'm hoping it is mitigated by using the above workflow.

**Comment by leahy268** [comment]
Hi James,

    > Seems like there may be 2 issues here.
Yes, but they are related to each other.

    > * 1. When you sign up with an email, it's case-sensitive, so you must login with the exact same email. (If I understand correctly, this isn't really a bug, but definitely makes for an awkward UX)

Definitely a bug as a user always receives an email to the same address regardless of the uppercase/lowercase nature of the email address I invite.  It's also a little worse than above as they don't get to choose what email address is recorded by the system as being SSO the system uses the UPN of their account.  After a lot of playing around I seem to end up inviting them and they end up with 2 accounts in the system.  As I see them in Tina both accounts look to be identical (same case), however one will be 'pending' them accepting the invite and the other will be a user.

    > * 2. Re-inviting users after deleting them gives a "User does not exist" error.
    > 
Yes, this is just strange because if I'm inviting a user then they don't exist.

    > Does that sounds like an accurate summary @leahy268?
    > 
    > One thing I'm unclear on is if this part is a side-effect of the first issue
    > 
Yes, I'm certain that it is a side-effect of the first issue.

    > > When inviting users to our organization we regularly have issues with them not being able to accept the invite. Instead 
    Tina asks them to sign up and they never see our organization. The invite also always appears pending.
    > 
    > Any ideas on that @kldavis4 ?
Currently this process requires me to manually invite the user multiple times and get them to sign up with me helping.  It should be a straight forward process but currently it takes me up to 20 minutes per user because as yet I have not worked out the 'magic' formula for getting a user onto the system in one go.

     >What you should be able to do is invite users onto your project (not the organization). Once they receive the invite and click the link, they will login with their SSW email address and be added to the project. Once you confirm that this is done, if you still need them to be added to the organization (to make them an org admin for example), you must invite them using the case sensitive email address.

I will try this although it's not really a good workaround as when we add other projects (i.e. SSW.Rules) it's lot simpler to just add them from the existing organization.  Since there is no method to add them to the organization from the project.

Bear in mind a much better solution would be to just implement SCIM - https://learn.microsoft.com/en-us/azure/active-directory/app-provisioning/use-scim-to-provision-users-and-groups#build-a-scim-endpoint

**Comment by leahy268** [comment]
Hi James,

This workaround works at least so far.  When tested with a new user this morning.  I just added him to the Enterprise App and then to the project and he was in.  I'm glad that works painlessly.

**Comment by leahy268** [comment]
Hi @jamespohalloran, 

So the workaround isn't always working.  I have an example in the screenshots below.  Can we please investigate this further?  I have invited one of our users with both lowercase, and uppercase to the project but he never sees the project.  Previously I had invited him to the organization and across to the project and he could see the org but could not edit the project.  I then removed him from the org and added him as per the workaround above.  

Currently inviting people to use Tina is a very painful experience.

![image](https://github.com/tinacms/tinacms/assets/58454534/29d54b3d-f169-4a58-b958-e51957043e26)
**Figure: Invited to the project with lower case**

![image](https://github.com/tinacms/tinacms/assets/58454534/6a4316b1-8248-4613-ab36-bb2e151b8562)
**Figure: Invited to the project with lower cases (exactly as per the account login in Tina)**

![image](https://github.com/tinacms/tinacms/assets/58454534/a7debc4e-374f-4b29-b663-320242291a36)
**Figure: No access to the project**
