### ISSUE TITLE
Auto generated schema/GraphQL generating incorrectly  

### ISSUE THREAD

**Issue by niftycodeltd** [tinacms/tinacms#3960]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

The auto generated schema/GraphQL is being generated incorrectly.

Getting this

```
... on PageBlocksBody {
    rows {
        __typename
        ... on PersonBlocksBodyRowsContent {}
        ... on PersonBlocksBodyRowsFigure {}
        ... on PersonBlocksBodyRowsSocialShare {}
    }
}
```

when it should be this

```
... on PageBlocksBody {
    rows {
        __typename
        ... on PageBlocksBodyRowsContent {}
        ... on PageBlocksBodyRowsFigure {}
        ... on PageBlocksBodyRowsSocialShare {}
    }
}
```

This is just a small sample. See Discord thread for further details:

https://discord.com/channels/835168149439643678/1092894383126356059

Content repo: https://github.com/niftycodeltd/testing-content.git
Website repo: https://github.com/niftycodeltd/testing.git

In the website repo I have included the branch `production-with-fix` which corrects the issue with my hack of a fix which is detailed on the Discord thread above.

The repos are private but I am happy to give access.

### Reproduction

https://github.com/niftycodeltd/testing.git

### Steps to reproduce

Run project locally and visit http://localhost:3000/about, on the `production` branch you will see that the body block is missing however if you visit the same page on the `production-with-fix` branch you will see that the body block is present.

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Memory: 21.05 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - /Volumes/G-DRIVE/Sites/testing/website/node_modules/.bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Firefox Developer Edition: 114.0
    Safari: 16.4
  npmPackages:
    @tinacms/auth: ^1.0.3 => 1.0.3 
    @tinacms/cli: ^1.5.6 => 1.5.6 
    tinacms: ^1.4.6 => 1.4.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by HenrySkup** [comment]
Hi, I'm running into a similar problem where the generated schema is inserting the wrong collection name within the typename.  could this be a caching issue?

here is an example of the type of data that is being generated : 

```
{
  __typename: 'PageBasic_pageContentDeck',
  title: 'Team',
  show_title: true,
  intro: { type: 'root', children: [ [Object] ] },
  cards: [
    {
      __typename: 'ConsciousCollectiveBasic_pageContentDeckCardsReferenceCard',
      reference: [Object],
      to_list: null,
      makeLink: null,
      layout: 'row',
      style: 'invisible',
      size: 'sm'
    },
...
```

I'm seeing that the issue is rooted in the `./tina/__generated__/types.js` file (i think...)
