### ISSUE TITLE
Nested objects in rich text templates showing blank UI

### ISSUE THREAD

**Issue by HenrySkup** [tinacms/tinacms#3976]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi, I have several templates within the TinaMarkdown component which have within them object fields.  These were working before, but on the latest release, when navigating the CMS to them, all I get is a blank sidebar.

<img width="1572" alt="Screenshot 2023-05-30 at 17 36 46" src="https://github.com/tinacms/tinacms/assets/5592703/5145349f-c0a1-46bd-9330-ebe571c6ece0">
<img width="1569" alt="Screenshot 2023-05-30 at 17 36 50" src="https://github.com/tinacms/tinacms/assets/5592703/945884b1-07b0-4209-9ae1-a991e6eb210b">
<img width="1564" alt="Screenshot 2023-05-30 at 17 36 53" src="https://github.com/tinacms/tinacms/assets/5592703/ab7dfb4c-5264-4c28-b774-83e2597f2dd9">
<img width="1573" alt="Screenshot 2023-05-30 at 17 36 55" src="https://github.com/tinacms/tinacms/assets/5592703/c3134d0a-f484-4ecf-a7a7-7b838a55c7e9">

### Reproduction

n/a

### Steps to reproduce

the page schema is :

```
...
fields: [
    { label : 'Title',
      name      : 'title',
      type      : 'string',
      isTitle   : true,
      required  : true 
    },
    { label: "Show Title",
      name: "showTitle",
      type: "boolean",
    },
    { label: "Main Content",
      name: "body",
      type: "rich-text",
      isBody: true,
      templates : [ 
        { label : 'Thing',
          name  : 'Thing',
          fields : [
            { label : 'Title',
              name      : 'title',
              type      : 'string',
            },
            { label : 'More Stuff',
              name      : 'stuff',
              type      : 'object',
              list : true,
              fields : [
                { label : 'A',
                  name      : 'a',
                  type      : 'string',
                },
                { label : 'B',
                  name      : 'b',
                  type      : 'string',
                },
              ]
            },
          ]
        } ],
    },

...
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 168.02 MB / 16.00 GB
    Shell: 3.2.57 - /bin/sh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Desktop/tina-barebones-starter-main/node_modules/.bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 72.0.2
    Safari: 16.4
  npmPackages:
    @tinacms/cli: 1.5.13 => 1.5.13 
    tinacms: 1.5.6 => 1.5.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
@HenrySkup can you also post the markdown file associated with this issue?

**Comment by HenrySkup** [comment]
sure:

```

---
title: Home
things:
  - _template: opt1
showTitle: false
---

Welcome to the barebones starter for TinaCMS!

<Callout
  color="#222"
  background={{ color: "dark" }}
  content={<>
   hello
  </>}
/>

<Thing title="hello" />


```

**Comment by jeffsee55** [comment]
PR for this is in review but you can test it out now with:

```sh
yarn add tinacms@fix-issue-with-nested-rich-text @tinacms/cli@fix-issue-with-nested-rich-text -E
```
