### ISSUE TITLE
Production media manager does not show preview images

### ISSUE THREAD

**Issue by 1alexvash** [tinacms/tinacms#3988]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

A picture worth a thousand words:

![Group 574](https://github.com/tinacms/tinacms/assets/46556479/1648887f-60d6-48f2-b2d0-a8aec70ad1fe)

### Reproduction

Any time website

### Steps to reproduce

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-11320H @ 3.20GHz      
    Memory: 6.12 GB / 15.78 GB
  Binaries:
    Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\Desktop\AlexCodeBlog\node_modules\.bin\yarn.CMD
    npm: 9.6.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (114.0.1823.37)        
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    @tinacms/cli: ^1.3.1 => 1.3.1 
    tinacms: ^1.3.0 => 1.3.0
```
```


### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
Hey, is this a new project that you've just setup? Or did something change on an existing project for you?
Also, can you share your media configuration in your tina.config.ts?

**Comment by jamespohalloran** [comment]
@1alexvash Also, would you mind sharing your project's clientID, and a URL that is failing to load for you?

**Comment by alexander-vashchuk** [comment]
Hey @jamespohalloran 

Thanks for the following up

Project URL: https://github.com/1alexvash/AlexCodeBlog
Media Configuration Info: https://github.com/1alexvash/AlexCodeBlog/blob/master/.tina/config.ts

clientId: `"c3e7b224-ca52-46a7-9bd6-c7f8c3777c7a"`

**Comment by alexander-vashchuk** [comment]
> URL that is failing to load for you?

The website is working
I just I can't preview images on the production version of the website, only on the localhost this feature is working

**Comment by alexander-vashchuk** [comment]
@kldavis4 

You're right

![image](https://github.com/tinacms/tinacms/assets/86713661/ff7d3865-76d5-406e-9f44-ce71225d7356)

I'm still not seeing any errors

**Comment by kldavis4** [comment]
I believe the file icon is displayed when the frontend does not recognize the asset as an image:
https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/components/media/media-item.tsx#L41

Here is the function for determining if it is an image: https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/toolkit/src/components/media/utils.ts#L25

Note that .webp should be valid so this is strange. You should have an XHR request to `assets.tinajs.io/v1/c3e7b224-ca52-46a7-9bd6-c7f8c3777c7a/list`. Click on the fetch request for that and share the response back here. It should be like: `{"files":[...],"directories":[]}`

**Comment by alexander-vashchuk** [comment]
![image](https://github.com/tinacms/tinacms/assets/86713661/98b19c2b-d2d6-423c-899d-265a81c4083a)

Weird, it looks like pictures are there

**Comment by kldavis4** [comment]
can you post the response I requested?

**Comment by alexander-vashchuk** [comment]
Though I have this object:

![image](https://github.com/tinacms/tinacms/assets/86713661/84e4bae0-4a18-467a-85bf-82db06d568e8)

**Comment by kldavis4** [comment]
Please paste the actual text of that response (instead of the image of it)

**Comment by alexander-vashchuk** [comment]
![image](https://github.com/tinacms/tinacms/assets/86713661/03ae7d4a-d03c-491f-a404-6fabe729c9b3)

**Comment by kldavis4** [comment]
> Though I have this object:
> 
> ![image](https://user-images.githubusercontent.com/86713661/244178065-84e4bae0-4a18-467a-85bf-82db06d568e8.png)
> 
> If this is somewhat relevant

Please paste the actual text of that response (instead of the image of it) ^^^^^

**Comment by alexander-vashchuk** [comment]
If you are referring a network request with the name **"?limit=20"**

Then [this one](https://assets.tinajs.io/v1/c3e7b224-ca52-46a7-9bd6-c7f8c3777c7a/list/?limit=20) returns an error:
```ts
{
  "message": "No authorization header set"
}
```

**Comment by kldavis4** [comment]
@alexander-vashchuk I think there is a communications issue - can you ping me on our discord? Just open a new help thread and at @kldavis4 on the thread

**Comment by kldavis4** [comment]
@alexander-vashchuk I'm not able to replicate this on a current version of tina. I suggest upgrading and see if that resolves the issue.

**Comment by alexander-vashchuk** [comment]
Updated Tina, everything works now:

![image](https://github.com/tinacms/tinacms/assets/86713661/0379edb3-dbdc-46fd-8016-8f25f7909b70)

![image](https://github.com/tinacms/tinacms/assets/86713661/577d1086-d4ad-4d92-a37d-8d8acc345d60)
