### ISSUE TITLE
Filename incorrect when adding content to subdirectory

### ISSUE THREAD

**Issue by jnschrag** [tinacms/tinacms#3990]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have an 11ty site that is multilingual. My pages are organized like this:
![image](https://github.com/tinacms/tinacms/assets/1896496/c44b4cf3-60c9-4e27-a021-5437288ceabb)

so that the final URLs of the site look like this: `en/about` or `es/about`.

I'm running into an issue in Tina where I'm not actually able to create content inside of these subfolders. I see the subfolders in Tina like I would expect, but actually creating the new page results in an issue with the file name if I try to create a file while I'm inside one of those subdirectories.

![image](https://github.com/tinacms/tinacms/assets/1896496/78e9648b-cc69-4701-a282-a2c7cabf1c95)

https://github.com/tinacms/tinacms/assets/1896496/c7538d58-e615-4c07-9d50-04d7dc0496f8

This video demonstrates that I can successfully create a page if I do it from the root of the "pages" collection, but I have to manually add the subdirectory to the filename. I know one solution would be to make this is a dropdown and add it to the filename automatically.

However, my preferred approach would be to create pages directly inside of their respective language subdirectory. As the video shows, if I do this, I still have to add `en/` or `es/` to the filename in order to be able to submit the form. However, this results in the following error:
![image](https://github.com/tinacms/tinacms/assets/1896496/38d50727-d480-479f-a172-b309d9944753)

It looks like Tina is actually including the subdirectory in the URL, but it doesn't show it in the filename field so the UI doesn't match what is actually happening on the backend.

### Reproduction

https://github.com/jnschrag/tinacms-translations/tree/main

### Steps to reproduce

1. Clone repo and install dependencies
2. Go to http://localhost:8080/admin/#/collections/new/pages/~/en (error only occurs when creating a file inside of a subdirectory)
3. Try to create a new page by adding either `en/` or `es/` to the fliename field.

### System Info

```shell
System:
    OS: macOS 11.7.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 5.05 GB / 32.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.n/bin/node
    Yarn: 1.22.19 - ~/Documents/Personal/ndi/tinacms-translations/node_modules/.bin/yarn
    npm: 8.11.0 - ~/.n/bin/npm
  Browsers:
    Chrome: 114.0.5735.90
    Firefox: 113.0.2
    Safari: 16.4.1
  npmPackages:
    @tinacms/cli: ^1.5.16 => 1.5.16 
    tinacms: ^1.5.8 => 1.5.8
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@jnschrag That should be possible without the workaround, so it sounds like a bug. Can you attach your schema to this as well?

**Comment by kldavis4** [comment]
Based on the reproduction, it looks like it is a problem with the match setting on the collection (and a possible conflict with the folder functionality). If I remove the match field from the collection, creating a file in a folder works. 

With the match property it gives this validation error when creating a new file:

<img width="822" alt="Screen Shot 2023-06-05 at 14 29 37" src="https://github.com/tinacms/tinacms/assets/370955/ccc45853-a5f2-48f7-a387-c0d3e407cefe">

@logan-anderson any thoughts / recommendations on this?

**Comment by jnschrag** [comment]
> Based on the reproduction, it looks like it is a problem with the match setting on the collection (and a possible conflict with the folder functionality). If I remove the match field from the collection, creating a file in a folder works.

I figured that was part of the problem. But without using `match` on the collection, I'm not sure how I would get the pages that I need, since I only want to pull markdown files that are in specific directories. So this still feels like a possible bug/something that could be improved on.

**Comment by kldavis4** [comment]
Yes, a fix is still planned - hopefully we will have time soon to address some of these bugs

**Comment by jnschrag** [comment]
Responding bc of the bot, but this is still an issue.
