### ISSUE TITLE
Error migrating from Forestry

### ISSUE THREAD

**Issue by elcarp** [tinacms/tinacms#3991]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When I run `npx @tinacms/cli@latest init`, I get the below error. I have tried deleting node modules and yarn.lock and then reinstalling. Any ideas? 

<img width="933" alt="Screenshot 2023-06-06 at 8 30 30 PM" src="https://github.com/tinacms/tinacms/assets/8285436/559d9700-445e-47cc-87d6-f88ab5ff36ba">

node:internal/modules/cjs/loader:1085
  throw err;
  ^

Error: Cannot find module '@tinacms/mdx'
Require stack:
- /Users/lisecarpenter/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/graphql/dist/index.js
- /Users/lisecarpenter/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/dist/index.js
- /Users/lisecarpenter/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/bin/tinacms
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at Module._load (node:internal/modules/cjs/loader:928:27)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
    at Object.<anonymous> (/Users/lisecarpenter/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/graphql/dist/index.js:2887:18)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/lisecarpenter/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/graphql/dist/index.js',
    '/Users/lisecarpenter/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/dist/index.js',
    '/Users/lisecarpenter/.npm/_npx/b34d1f235ac7f645/node_modules/@tinacms/cli/bin/tinacms'
  ]
}

### Reproduction

https://github.com/elcarp/lisecarpenter.com

### Steps to reproduce

run `npx @tinacms/cli@latest init`

### System Info

```shell
System:
    OS: macOS 11.7.6
    CPU: (8) arm64 Apple M1
    Memory: 140.58 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 20.1.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 9.6.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Firefox: 109.0.1
    Safari: 14.1.3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@jeffsee55 I wasn't able to replicate this, but it looks like the user is on an M1 mac - could that be the issue?

**Comment by elcarp** [comment]
This worked! Many thanks Jeff and Kelly ☺

Best,

Lise

Lise Carpenter
Tel: +66 98 5014856
***@***.***
