### ISSUE TITLE
images with spaces not rendering

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#3993]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When adding an image with spaces in the filename, it is broken in the media manager:

<img width="1245" alt="Screen Shot 2023-06-07 at 10 49 11 AM" src="https://github.com/tinacms/tinacms/assets/3323181/e6d1c730-4664-4e33-a7b1-ea3182c0e7a6">

Also broken on the site
<img width="1248" alt="Screen Shot 2023-06-07 at 10 49 51 AM" src="https://github.com/tinacms/tinacms/assets/3323181/f35830e7-045b-4171-b04b-e6b26cad2af6">

### Reproduction

https://github.com/tinacms/tina-cloud-starter

### Steps to reproduce

Add an image with a space to the media manager

### System Info

```shell
System:
    OS: macOS 12.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 2.32 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/Documents/forestry/starters/tina-cloud-starter/node_modules/.bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 113.0.5672.126
    Firefox: 113.0.1
    Safari: 15.6.1
  npmPackages:
    @tinacms/cli: ^1.5.14 => 1.5.14 
    tinacms: ^1.5.6 => 1.5.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
Fixed by https://github.com/tinacms/tinacms/pull/3994
