### ISSUE TITLE
🐛 Content change causing schema mismatch 

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tinacms#3996]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Related issue #3981

Sometimes when content changes are made through tina (no code or config is touched), the PR build fails. 

<img width="1170" alt="image" src="https://github.com/tinacms/tinacms/assets/38869720/115d9009-53b7-4d36-a7df-89ef5076e9df">

### Reproduction

https://github.com/SSWConsulting/SSW.Website/pull/781

### Steps to reproduce

1. Go to Tina 
2. Make a new branch
3. I get the "GraphQL mismatch error"  but it doesn't block me from making changes
4. Commit some changes
5. Make a PR
6. build fails ☹️ 

### System Info

```shell
System:
    OS: macOS 13.4
    CPU: (12) arm64 Apple M2 Max
    Memory: 24.38 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v20.2.0/bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.106
    Safari: 16.5
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
If you pull down that branch locally (or even your main branch that your branching off of), and run tinacms dev, are there changes to the tina-lock.json file?

**Comment by jamespohalloran** [comment]
Also, This issue kind of seems like a symptom of this other issue you created: https://github.com/tinacms/tinacms/issues/3981. Not sure these should be separate tickets
By ignoring the schema mismatch, the build will predictably fail. (The question is, why are we seeing a schema mismatch?)

**Comment by bradystroud** [comment]
> Also, This issue kind of seems like a symptom of this other issue you created: https://github.com/tinacms/tinacms/issues/3981. Not sure these should be separate tickets

I agree, closing this one in favour of #3981
