### ISSUE TITLE
Build-in search throws an error on production builds / Unrecognized key(s) in object: 'stopwordLanguages'

### ISSUE THREAD

**Issue by jobee** [tinacms/tinacms#4026]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I tried to add the search as described in here: https://tina.io/docs/reference/search/overview/
But `npm run build` fails with:

```
npm run build

> tina-hugo-starter@1.0.0 build
> tinacms build && hugo

Starting Tina build
Checking clientId and token. ✅
Checking branch is on Tina Cloud. ✅
Checking indexing process in Tina Cloud... ❌
IndexFailedError: Attempting to index but responded with status 'failed', To retry the indexing process, click “Reset Repository Cache” in tina cloud advance settings.  [
  {
    "code": "unrecognized_keys",
    "keys": [
      "stopwordLanguages"
    ],
    "path": [
      "search",
      "tina"
    ],
    "message": "Unrecognized key(s) in object: 'stopwordLanguages'"
  }
]
```

This happened to me in production (deployed to Cloudflare Pages), but is reproducible in development as well, follow the steps below.

In Local Mode the search config works perfectly fine:
1. `npm run dev`
2. http://localhost:1313/admin/#/collections/post/~

### Reproduction

https://github.com/jobee/tinacms-reproduction

### Steps to reproduce

1. Connect https://github.com/jobee/tinacms-reproduction to a new Tina Cloud project
2. git clone git@github.com:jobee/tinacms-reproduction.git
3. cd tinacms-reproduction
4. cp .env.example .env
5. Add ID & Tokens from the Tina Cloud project
6. npm install && npm run build

### System Info

```shell
System:
    OS: macOS 13.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 934.36 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Brave Browser: 113.1.51.118
    Safari: 16.4
  npmPackages:
    @tinacms/auth: ^1.0.3 => 1.0.3
    @tinacms/cli: ^1.5.6 => 1.5.19
    tinacms: ^1.4.6 => 1.5.10
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@jobee this as fixed in last week's release of @tinacms/cli. Can you check the yarn.lock in your project for the version of @tinacms/schema-tools that is present in your project? Or push that up the yarn.lock to your reproduction.

**Comment by jobee** [comment]
@kldavis4 I've used npm. It's "@tinacms/schema-tools": "1.4.6"

See https://github.com/jobee/tinacms-reproduction/blob/main/package-lock.json#LL3969C42-L3969C42

**Comment by kldavis4** [comment]
@jobee the issue was on the backend and has been resolved. If you go to your project configuration page in Tina Cloud and click Reindex, and then retry the build, it should now succeed.
