### ISSUE TITLE
🐛  Handle duplicate images - fix error message

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tinacms#4059]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When I upload a image that has the same name as another image, I get this error.

![image](https://github.com/tinacms/tinacms/assets/38869720/4ce427e9-3268-40c0-a85b-d4f125b4b8f4)

The error message was expected, but is not useful.

I would expect something like "this image already exisits"

https://github.com/SSWConsulting/SSW.Website/issues/921

### Reproduction

https://github.com/SSWConsulting/SSW.Website

### Steps to reproduce

1. Upload an image to the media manager
2. Try upload the same image
3. See unhelpful error message

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (12) arm64 Apple M2 Max
    Memory: 28.53 GB / 96.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
    Yarn: 3.5.1 - ~/Developer/SSW/SSW.Website/node_modules/.bin/yarn
    npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @tinacms/cli: ^1.5.19 => 1.5.19 
    tinacms: ^1.5.11 => 1.5.11
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by GFier** [comment]
Same error here, users get confused with the error label: _Unexpected error generating upload url_

Only by inspecting the network tab, I can read the correct error label:

![Screenshot 2023-09-27 at 17 57 39](https://github.com/tinacms/tinacms/assets/64488427/a3f10d28-16b1-44c0-a79e-ef9c834a2f10)
