### ISSUE TITLE
Media manager not responsive

### ISSUE THREAD

**Issue by ituri** [tinacms/tinacms#4083]
I can't insert an image from the media manager on my iPhone 14 pro since the button is hidden at the very bottom and I can't scroll down. 
![image](https://github.com/tinacms/tinacms/assets/871297/5df24eb8-8f6d-44a0-932c-659493a85589)
Doesn't work in landscape mode either.

**Comment by bojanvidanovic** [comment]
Same here! I always need to rotate my phone, zoom out to 85%, and hide the Safari toolbar. :(
