### ISSUE TITLE
Can't remove all entries of the tags/list field

### ISSUE THREAD

**Issue by rachitpant** [tinacms/tinacms#4091]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

As per the documentation , when a field is omitted , it would get deleted.

However i have a jekyll blog post with tags, I used the `tags` ui component. I am able to add/update more tags to a post. I can also remove an existing tag.
However when i  remove the last tag and hit save, I notice in the browser network tab , that field is omitted in the graphql update mutation. As per tina cms documentation , "Omitting a field will result in it being nullified."

However I am not able to remove the last tag from the post. Very sure there is nothing wrong with the config , because i am using the exact same config as the documentation and like i said i am able to add , remove tags . The problem is with just not being able to remove the very last tag.

https://github.com/tinacms/tinacms/assets/1474415/6cf0aa25-5c52-4c92-8404-fe821fdb12ad

### Reproduction

https://mythoughtsto.day/

### Steps to reproduce

In the above screenshot , I am using a custom tag UI component , however I have also tried using the tag component provided by Tina and used the exact same config as provided in the documentation.

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 303.06 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 3.6.0 - ~/code/annoblog/node_modules/.bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.5.1
  npmPackages:
    @tinacms/cli: ^1.5.6 => 1.5.22 
    tinacms: ^1.4.6 => 1.5.13
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jamespohalloran** [comment]
I believe this is now fixed. In the [duplicate issue](https://github.com/tinacms/tinacms/issues/4161), I'm no longer able to reproduce with the reproduction repo. If you still are running into it on the latest Tina version, let us know
