### ISSUE TITLE
Tina has no alert warning when closing the window with unsaved changes

### ISSUE THREAD

**Issue by 1alexvash** [tinacms/tinacms#4094]
### Demo
![animation](https://github.com/tinacms/tinacms/assets/46556479/a64e4b5c-5ebe-4ab0-ac22-8f0ab7f24aac)

### Reproduction

- Use Tina CMS editor

### Steps to reproduce

1) Create a new piece of Tina content
2) Write something
3) Accidentaly close the window

### System Info

```shell
-
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by appinteractive** [comment]
This not only happens when closing the tap but also when navigating around in the admin itself which is quite frustrating. Some interactions trigger a warning, others don't.
