### ISSUE TITLE
useCMSForm hook not respecting initialValues

### ISSUE THREAD

**Issue by kypp** [tinacms/tinacms#410]
First of all, thanks for this project - it's a step in the right direction for the JAM stack.

I'm filling this as a bug report as that's the way I would expect the `useCMSForm` hook to work but perhaps I misunderstood something as it's only mentioned briefly in the documentation.

## Description

`initialValues` passed to the `useCMSForm` hook are not respected in this minimal example:

```jsx
import React from "react"
import { useCMSForm } from "react-tinacms"

export default () => {
  const [values] = useCMSForm({
    id: 'form-identifier',
    fields: [{ name: "hideText", label: "Hide text", component: "toggle" }],
    initialValues: {
      hideText: true
    },
    label: "Hide text",
    onSubmit: (v) => { console.log("Submitted with: ", v) }
  })
  console.log("Rendered with: ", values)

  return <div>
    {!values.hideText &&
      <div style={{ marginLeft: '50%' }}>
        You shouldn't see me on startup
      </div>}
  </div>
}
```

The same goes for more complex forms - all passed `initialValues` are zeroed out and only constructed when the user interacts with the form.

### Steps to reproduce

1. Create a project using the [official Gatsby Quickstart](https://tinacms.org/docs/gatsby/quickstart)
2. Add a `page` with code as above

### Expected result

- `values.hideText` should be `true` when no changes are made through the UI
- `Rendered with: {hideText: true}` should be printed to the console anytime the component renders
- Submitting the form without making any changes should output `Submitted with: {hideText: true}`

### Actual result

The component gets rendered three times and while the first two renders happen with the proper value, with the third render `values` is an empty object.

### Environment

Tested on Linux and Windows with both versions @0.5.0 and @0.6.0-alpha.0 on top of an unmodified Gatsby quickstart

**Comment by ncphillips** [comment]
Thanks for the report!

@all-contributors please add @kypp for bugs

**Comment by dwalkr** [comment]
@kypp This fix has been published on the `canary` channel, and is scheduled to be released on the `next` channel tomorrow. Barring any issues, it will then be released to the stable channel next week.

For now, you can install this version in projects that directly require `react-tinacms` by running `npm install react-tinacms@canary`.

If you're using the Gatsby plugin where `react-tinacms` is a transient dependency, adding the following section to your `package.json` config should install the canary release:

```json
"resolutions": {
    "react-tinacms": "0.5.1-canary.1725"
  }
```
