### ISSUE TITLE
Title listing not working

### ISSUE THREAD

**Issue by HenrySkup** [tinacms/tinacms#4108]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi, I'm getting an error (all of a sudden) with lists of objects (templates) where the suggestion of doing :

```
...
{ label : "Title",
      name      : "title",
      type      : "string",
      isTitle   : true,
      required: true
}
...
```

is leading to the following error

`Error 1: Fields "title" conflict because they return conflicting types "String" and "String!". Use different aliases on the fields to fetch both if this was intentional.`

### Reproduction

n/a

### Steps to reproduce

In a top-level collection schema 

```
{
  label   : 'Basic Page',
  name    : 'basic_page',
  format  : 'mdx',
  fields  : [
    { label : 'Title',
      name      : 'title',
      type      : 'string',
      isTitle   : true,
      required  : true,
    },
    { label : 'Main Content',
      name      : 'content',
      type      : 'object',
      list      : true,
      templates : [
        { label : 'Text Section',
          name  : 'section',
          fields  : [
            { label : 'Title',
              name      : 'title',
              type      : 'string',
             //    isTitle   : true,
             // required  : true,
             //
            },
          ]
        }
 
      ]
    }
  ]
}
```

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M2
    Memory: 149.75 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.1 - /usr/local/bin/node
    Yarn: 1.22.19 - ----------
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Firefox: 72.0.2
    Safari: 16.4
  npmPackages:
    @tinacms/cli: 1.5.13 => 1.5.13 
    tinacms: 1.5.6 => 1.5.6
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeffsee55** [comment]
If you have another collection where `title` is not required, depending on how you're querying things you'll run into this GraphQL limitation. There are a few topics on this issue but here's one for reference https://github.com/graphql/graphql-js/issues/1065. 

To get around this, you'll need to use an [alias](https://graphql.org/learn/queries/)
