### ISSUE TITLE
Search results limited to 15 (in the CMS UI)

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#4130]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When doing a search in the CMS from the document list UI, there are only max 15 results. 

I would expect this to have no limit, and the results would be paginated

Note from Kelly:
> I believe the result size is currently hard coded in the frontend query, so not configurable

> The client does have a limit parameter https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/internalClient/index.ts#L863

> Here it is https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/admin/components/GetCollection.tsx#L120
[GetCollection.tsx](https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/admin/components/GetCollection.tsx)

### Reproduction

Ask James For Access

### Steps to reproduce

- Create a document with a field with a value "FooBar123"
- Duplicate the document 20x
- Configure the search index in config.tsx
- Try searching on the document list UI, you'll see 

### System Info

```shell
System:
    OS: macOS 13.4.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 3.78 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
    Yarn: 1.22.19 - ~/Documents/forestry/starters/tina-cloud-starter/node_modules/.bin/yarn
    npm: 9.1.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Firefox: 116.0.1
    Safari: 16.5.2
  npmPackages:
    @tinacms/cli: ^1.5.26 => 1.5.26 
    tinacms: ^1.5.17 => 1.5.17
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@jamespohalloran  I'm having trouble replicating any issue with pagination of search results: https://www.loom.com/share/c58b4850c1694df18246cd4ac1091515?sid=3768cd99-a0ef-44c7-8b19-be419e1d41da

It does limit results to 15 per page, but I can still page through

**Comment by jamespohalloran** [comment]
Hmm! I'm not sure if there's a detail to this that I'm forgetting, but that does seem to be working now. 
A user reported this, maybe we both just missed the next page button?
Either way, closing for now, and can re-open if I have an epiphany!
