### ISSUE TITLE
Generated query types seems to be invalid when using reference fields

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#4154]
### Discussed in https://github.com/tinacms/tinacms/discussions/4152

<div type='discussions-op-text'>

<sup>Originally posted by **bfamchon** August 18, 2023</sup>
Hello 👋🏼 

I was following the "Deep Dive" videos and decide to integrate a Post reference field to my "Resources" block:

```typescript
{
  name: 'resources',
  label: 'Resources',
  fields: [
    ... // other basic fields
    {
      name: 'featuredPost',
      label: 'Featured Post',
      type: 'reference',
      required: true,
      collections: ['post']
    }
  ]
}
```

Now in my main component, I've got this:

```typescript
{data.page.blocks?.map((block, index) => {
          switch (block?.__typename) {
            ...
            case 'PageBlocksResources':
              return <Resources key={index} {...block} />;
          }
        })}
```

And in my `Resources` component:

```typescript
const Resources = (props: PageBlocksResources) => {...}
```

But in the switch, I have a type warning about some missing fields (`_values`, `_sys.colection`,`_sys.template`) between generated type of block inside `PageQuery`, and generated type `PageBlocksResources`.

And when we look how types are, we found:

```typescript
export type PageQuery = { __typename?: 'Query', page: { __typename?: 'Page', id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, blocks?: Array<{ __typename: 'PageBlocksResources', title: string, description: string, featuredPost?: { __typename?: 'Post', title: string, description: string, miniature: string, body?: any | null, postDate: string, id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null, otherPosts?: Array<{ __typename: 'PageBlocksResourcesOtherPosts', otherPost: { __typename?: 'Post', title: string, description: string, miniature: string, body?: any | null, postDate: string, id: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } } | null> | null } | null> | null } };
```

So without `_values`, `_sys.colection`,`_sys.template` under the `__typename: 'PageBlocksResources')`.

BUT these fields are waiting in the generated type `PageBlocksResources`:

```typescript
export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};

export type Post = Node & Document & {
  __typename?: 'Post';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  miniature: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  postDate: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PageBlocksResourcesFeaturedPost = Post;

export type PageBlocksResources = {
  __typename?: 'PageBlocksResources';
  title: Scalars['String']['output'];
  description: Scalars['String']['output'];
  featuredPost: PageBlocksResourcesFeaturedPost;
  otherPosts: Array<PageBlocksResourcesOtherPosts>;
};
```

I don't have any problem when using basic type as `string`.

BTW, if I override the "PageQuery" type to include missing fields, everything works fine.

Here is a working version when I redefine `PageBlocksResources`:

```typescript
type PBRFP = Omit<PageBlocksResourcesFeaturedPost, '_values' | '_sys'> & {
  _values?: any;
  _sys: Omit<SystemInfo, 'template' | 'collection'> & {
    template?: Scalars['String']['output'];
    collection?: Collection;
  };
};

type ResourcesProps = Omit<PageBlocksResources, 'featuredPost'> & {
  featuredPost: PBRFP;
};

const Resources = (props: ResourcesProps) => {...}
```

Did I misunderstood something in usage ? 🤔 </div>

**Comment by jeffsee55** [comment]
I don't think this is a bug, I _think_ the error you're probably seeing is that `_values` is not included in reference queries out of the box. This is intentional, and the type that you're using (`PageBlocksResources`) is not based on the query, but on the shape of the schema.  `_sys` is properly included, and it has usefulness as you build your site, but `_values` is sort of used as an internal API, so we don't include it in our codegen queries. The example repo has this same issue, solved by omitting `_values` from the expected response:

https://github.com/tinacms/llama-link/blob/main/components/blog-list.tsx#L51-L59

cc @jamespohalloran we _could_ include the `_values` in the generated payload, but IMO it's better to not to. We may even get rid of `_value` in the future.
