### ISSUE TITLE
UI fails when nested objects without list: true

### ISSUE THREAD

**Issue by Raven0us** [tinacms/tinacms#4165]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Collection config
```json5
{
  label: "Page Content",
  name: "page",
  path: "content/page",
  format: "mdx",
  fields: [
    {
      name: "level1",
      label: "Level 1",
      type: "object",
      fields: [
        {
          name: "level1_1",
          label: "Level 1.1",
          type: "object",
          // list: true,
          fields: [
            {
              name: "level1_1_1",
              label: "Level 1.1.1",
              type: "string"
            }
          ]
        }
      ]
    }
  ]
}
```

Fails on creation (empty file) with the stack trace below
```
Uncaught TypeError: Cannot read properties of undefined (reading 'level1_1')
    at Form.getFieldGroup (index.mjs:2022:19)
    at Form.getFieldGroup (index.mjs:2112:27)
    at Form.getActiveField (index.mjs:2006:25)
    at FormBuilder (index.mjs:10857:31)
    at renderWithHooks (react-dom.development.js:14985:18)
    at updateFunctionComponent (react-dom.development.js:17356:20)
    at beginWork (react-dom.development.js:19063:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
```

Adding `list: true` for `level1_1` fixes the issues, you can interact with the UI and create
```md
---
level1:
  level1_1:
    level1_1_1: Works2
---
```

Removing `list: true` will work now that there are values for the UI to render the inputs.

List with a hard limit of 1 could be a valid workaround, but I couldn't find any way to set one.

### Reproduction

https://github.com/oxentree/tinacms-trial

### System Info

```shell
 System:
    OS: Windows 10 10.0.22621
    CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 1.39 GB / 15.96 GB
  Binaries:
    Node: 20.5.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - X:\OXENTREE-PROJECTS\tinacms-trial\node_modules\.bin\yarn.CMD
    npm: 9.8.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.2134.0), Chromium (116.0.1938.54)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @tinacms/cli: 1.5.29 => 1.5.29
    tinacms: 1.5.20 => 1.5.20
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by Raven0us** [comment]
May be related to https://github.com/tinacms/tinacms/issues/3976
Definitely related to https://github.com/tinacms/tinacms/discussions/4030

**Comment by jamespohalloran** [comment]
Just pulled your repo, this doc seems to be working fine for me. Are you seeing an error here?
<img width="1526" alt="Screenshot 2023-08-28 at 10 34 52 AM" src="https://github.com/tinacms/tinacms/assets/3323181/8d2ade17-c442-4968-aa66-0b2757d0cfab">

(If so, makes me wonder if this could be a Windows vs Mac issue)

**Comment by Raven0us** [comment]
Does the other one work? The one in your screenshot is supposed to work; on update, both work, on blank page, it will fail unless you add list: true

It’d be weird for this UI issue to be OS-specific, that’s why I haven’t tried other platforms, but I’ll try that too.

**Comment by jamespohalloran** [comment]
Sorry the name of the document should have tipped me off :D. I can reproduce your issue on the other document. 
We'll do some investigation and report back!

**Comment by jamespohalloran** [comment]
Just opened a PR with the fix here: https://github.com/tinacms/tinacms/pull/4169 (Thanks for creating that reproduction, maybe it much easier to debug!)

In the meantime, you may be able to get around this by using `defaultItem` to fill in the group value when creating a new doc:
https://tina.io/docs/reference/collections/#defaultitem
