### ISSUE TITLE
No TypeScript types for gatsby-tinacms-json plugin

### ISSUE THREAD

**Issue by smashercosmo** [tinacms/tinacms#419]
## Description

There are no TypeScript types for gatsby-tinacms-json plugin package

### Steps to reproduce

1. Install gatsby-tinacms-json plugin package
2. Check gatsby-tinacms-json dir in node_modules

### Expected result

Types should present in the directory

### Actual result

No types in the directory

### Environment

gatsby-tinacms-json@0.5.0

**Comment by ncphillips** [comment]
Thanks for the heads up @smashercosmo. 

This is fixed in `gatsby-tinacms-json@canary`

**Comment by ncphillips** [comment]
@all-contributors please add @smashercosmo for bugs

**Comment by smashercosmo** [comment]
Thx
