### ISSUE TITLE
Match property not working correctly on windows

### ISSUE THREAD

**Issue by kldavis4** [tinacms/tinacms#4210]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Collection structure:
```
content/page1.md
content/page2.md
content/posts/post1.md
content/posts/post2.md
content/authors/author1.md
content/authors/author2.md
```
And collections defined as:
```
collections: [
{
  name: "pages",
  path: "content",
  match: {
    include: "*",
  }
},
{
  name: "posts",
  path: "content/posts",
  match: {
    include: "**/*",
  }
},
{
  name: "authors",
  name: "content/authors",
  match: {
    include: "**/*",
  }
}
```

When you try to open any item in any of these collections when running in local dev on windows, it gives an error like: `[Error] GetDeocument failed: Unable to fetch, errors: Unable to find collection for file at content\posts\post1.md`

Based on the error message it looks like it is probably just an issue with the directory separators.

### Reproduction

na

### System Info

```shell
windows 11
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by Nirose** [comment]
This is happening in Windows 10 as well after upgrade from `1.5.6` to `1.5.20`

![image](https://github.com/tinacms/tinacms/assets/426674/186f08a5-3c31-4e85-a73c-f1f5bfb8b4fc)


This is the output in the terminal
`
GraphQL request:3:11
2 |         query($collection: String!, $relativePath: String!) {
3 |           document(collection:$collection, relativePath:$relativePath) {
  |           ^
4 |             ... on Document {
Unable to find collection for file at exampleSite\content\english\author\john-doe.md
`
