### ISSUE TITLE
Error parsing Markdown

### ISSUE THREAD

**Issue by belgrades** [tinacms/tinacms#4218]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am creating an enumeration with blocks of shell code inside:

## The Markdown chunk that creates the issue

Please replace \\' with a single quote \' so you can generate the proper shell chunk:

```text
Steps: 
1. Clone our RAWRR repository.
   \`\`\`Shell
   # Cloning base repository
   git clone https://github.com/ConexoLA/Rawrr_dev.git
   \`\`\`
2. Install dependencies

Depending on the usage you want to give to RAWRR, you may modify the code using the hot-reload functionality or generate the executable by building the project.

In both cases, you must install all the packages available in `package.json`.

  \`\`\`Shell
  # install package.json packages
  npm install
  \`\`\`
```

## What we should see

1. Clone our RAWRR repository.

   ```Shell
   # Cloning base repository
   git clone https://github.com/ConexoLA/Rawrr_dev.git
   ```
2. Install dependencies

Depending on the usage you want to give to RAWRR, you may modify the code using the hot-reload functionality or generate the executable by building the project.

In both cases, you must install all the packages available in `package.json`.

```Shell
# install package.json packages
npm install
```

## The error 

Code inside list item is not supported

![image](https://github.com/tinacms/tinacms/assets/6496119/9bfbce5d-d16d-4828-8a5c-79301482d1be)
 

### Reproduction

https://github.com/ConexoLA/RAWRRDoc.git

### Steps to reproduce

1. Associate the repo to a cloud tina account
2. Go into collections > usage > installation or collections > uso > instalación

### System Info

```shell
tina-cloud-starter with latest TinaCMS versions
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@belgrades Looks like you are using shortcodes.

Please see [this doc](https://tina.io/docs/reference/types/rich-text/#custom-shortcode-syntax) on how to add the shortcodes to your rich text editor. 

Feel free to reach out with further questions
