### ISSUE TITLE
Undo / Redo is not working in the rich text editor

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tinacms#4220]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

https://www.loom.com/share/b2f46ee9459c4577a97af2342a7d7a77?sid=abf48bab-81f7-48ac-90ef-e65c56ad7d41

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
Working in "tinacms": "1.5.6",   "@tinacms/cli": "1.5.13",

Not working in   "tinacms": "^1.5.20",   "@tinacms/cli": "^1.5.29",

**Comment by logan-anderson** [comment]
@jeffsee55 Any idea why this would work in the monrepo but not on the beta tagged release?

**Comment by jeffsee55** [comment]
It looks like it's due to a esm/cjs issue, so probably started when I pushed that out a couple of weeks ago.
