### ISSUE TITLE
defaultItem ignores child default values

### ISSUE THREAD

**Issue by Raven0us** [tinacms/tinacms#4235]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I'm trying to set default values for nested items, but they won't apply when set at the same level with the nested item's definition.

This is not a big deal as, generally, blocks decide context and context decides defaults, but this behaviour could be mentioned in the docs.

### Reproduction

https://github.com/oxentree/tinacms-block-defaultitem

### Steps to reproduce

1) Clone the reproduction repo and run it
2) Edit or create a new post
3) Add a new "Hero" block
4) Notice that main block defaults (size) was applied, but inner block defaults (color, text) did not.

### System Info

```shell
-
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@Raven0us  this is the expected behaviour. It is a the top level on purpose to help convey that the default item only applies when the template is created.  

I agree that the docs should explain this better.

**Comment by jamespohalloran** [comment]
> Notice that main block defaults (size) was applied, but inner block defaults (color, text) did not.

To elaborate more on this to close the loop, I see that you're using `defaultItem` on a non-list string field. 

`defaultItem` is only a valid prop on:
- Collections/Templates:
     - This can contain nested values. It's applied when a Document is created.
- List Fields
     - These defaults are applied when a new list-item is created.
     
I just added an extra note to a doc here: https://github.com/tinacms/tina.io/pull/1707, but I think we'd be open to other docs suggestions for smoothing out this DX! Hope that gets you sorted for now!
