### ISSUE TITLE
Breaks Hugo Shortcodes `{{< ... >}}` On Save

### ISSUE THREAD

**Issue by gcushen** [tinacms/tinacms#4237]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

On saving a Markdown file with a Hugo shortcode, Tina CMS breaks the Hugo shortcode in the rich-text body by inserting a backslash within the shortcode, so `{{< ... >}}` becomes `{{\< ... >}}`.

The example below can be reproduced to see the issue with the following Hugo shortcode being broken by Tina CMS.

The issue appears to affect Hugo's `{{<` shortcodes but not it's `{{%` shortcodes.

Hence, it's likely some Tina CMS bug with parsing the `<` and `>` symbols within Hugo shortcode syntax.

Example:

`{{< figure src="featured.jpg" >}}` gets converted by Tina CMS to `{{\< figure src="featured.jpg" >}}`

### Reproduction

https://github.com/tinacms/tina-hugo-starter/

### Steps to reproduce

Clone https://github.com/tinacms/tina-hugo-starter/

Then add a file with:

```markdown
---
title: 'Hugo'
---

Hello world

{{< figure src="featured.jpg" title="" numbered="false" >}}
```

Rich-text view shows the original:

<img width="938" alt="Screenshot 2023-10-09 at 00 04 12" src="https://github.com/tinacms/tinacms/assets/7537639/0818b79b-ce72-435f-b9ee-5dfdef347fff">

But the Markdown-view, and thus the file which Tina CMS saves, insert a backslash which breaks the Hugo shortcode:

<img width="925" alt="Screenshot 2023-10-09 at 00 04 19" src="https://github.com/tinacms/tinacms/assets/7537639/efe2e6cd-f5a0-46f5-92e6-c008f82ad0a2">

### System Info

```shell
Hugo v0.119.0
"@tinacms/cli": "^1.5.30",
"tinacms": "^1.5.21"
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by gcushen** [comment]
**Tina CMS also breaks both of Hugo's shortcode notations** (including the `{{% ... %}}` notation) **when there is an underscore in the shortcode name**.

For example, Tina CMS breaks the following valid Hugo shortcode:

```
{{% emoji\_list %}}
{{% /emoji\_list %}}
```

by inserting backslashes and converting it to

```
{{% emoji\_list %}}
{{% /emoji\_list %}}
```

Hence, it appears that Tina CMS either does not support Hugo or is not tested with Hugo.

**Comment by RemiBardon** [comment]
It works, you have to use [Templates](https://tina.io/docs/reference/templates/).

For example, here is part of my `schema.collections[0].fields`:

```js
{
  label: "Body",
  name: "body",
  type: "rich-text",
  isBody: true,
  templates: [
    {
      name: 'youtube',
      label: 'YouTube video',
      match: {
        start: '{{<',
        end: '>}}',
      },
      fields: [
        {
          name: '_value',
          label: 'value',
          type: 'string',
          required: true,
        },
      ],
    },
    {
      name: 'spotify_embed',
      label: 'Spotify embed',
      match: {
        start: '{{<',
        end: '>}}',
      },
      fields: [
        {
          name: 'id',
          label: 'Track ID',
          type: 'string',
          required: true,
        },
      ],
    },
  ],
},
```

**Comment by gcushen** [comment]
@RemiBardon Thanks for the help.

It is not a great experience when it states on the Tina CMS website that Hugo is supported and then the default behaviour of Tina CMS is to break Hugo sites, even when the site content is just containing built-in Hugo shortcodes. Although, I appreciate maybe Hugo is not a priority to support compared with other frameworks.

It still appears that there are issues even after adding extra configuration.

For example, how do you support the built-in relref shortcode?

By default, Tina CMS converts Hugo's `{{< relref "page.md" >}}` shortcode to `{{\< relref "page.md" >}}`, breaking it with a backslash.

If I add the following snippet from the Tina Docs, it still doesn't work. **Perhaps the magical `name: '_value'` is bugged in the current version, or am I missing something?**

```
              {
                name: 'relref',
                label: 'relative ref',
                match: {
                  start: '{{<',
                  end: '>}}',
                },
                fields: [
                  {
                    name: '_value',
                    label: 'value',
                    type: 'string',
                    required: true,
                  },
                ],
              },
```

**Comment by gcushen** [comment]
OK, I have found one of the related issues.

This works:

```
{{< relref "/docs/content/writing-markdown-latex.md" >}}
```

But this doesn't work in Tina CMS (it fails to parse the shortcode and instead, breaks it by adding backslashes on save):
```
[Elements]({{< relref "/docs/content/writing-markdown-latex.md" >}})
```

So it appears that Tina CMS does not support the [documented usage of Hugo's built-in shortcodes](https://gohugo.io/content-management/shortcodes/#ref-and-relref), such as Hugo's relref, as Tina CMS cannot parse shortcodes nested within Markdown, such as in the above example?

If so, then Tina CMS can only work with very simple Hugo sites which don't use Hugo's built-in shortcodes such as relref.

**Comment by jeffsee55** [comment]
Unfortunately there's not a reliable way to predict the syntax for every framework's usage of html entities, which are escaped intentionally by our parsing/stringifying logic. However if you're confident you don't want escaping at all, you can disable it. Note that this may result in user-supplied content like <div>Hello</div> so actually be transformed into HTML, which may lead to unexpected results. It's a bit of a balancing act, but here's how you can do it:

```ts
type: 'rich-text',
parser: {
  type: 'markdown',
  skipEscaping: 'all', // this allows {{< to go unescaped
},
```

Not that your second (`[Elements]({{< relref "/docs/content/writing-markdown-latex.md" >}})
)` example will not be picked up as a template, just not something we support at the moment.

**Comment by jazbogross** [comment]
I'm using Hugo as well and having the same issue with a slightly different use.
I'm using a rich-text field to input some user written CSS. It sort of works by selecting the pure markdown version of the rich text editor, but I get this whenever referring to an id:

css: >
  \#background {position: fixed;  z-index: -1;}
  
I can work around it by removing the backslash with some javascript client side but it's not a great solution. Wouldn't it make sense to have the option of a "code" input field that in addition to the "rick-text" input field?

**Comment by jeffsee55** [comment]
@jazbogross can you just use a `string` field for this? You could provide a `textarea` component for editing this:

```
{
  type: 'string',
  ui: { component: 'textarea' }
}
```
This field would be untouched by any string escaping.

**Comment by jazbogross** [comment]
Hi @jeffsee55 
I was not aware that I could change the ui of the string field. Yes, that should work perfectly. Thanks!
