### ISSUE TITLE
RFC: Adding Form metadata

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#424]
## Summary

Add the ability to attach arbitrary metadata to forms.

### Basic example

I have two potential APIs in mind. 

#### Option 1: Extra values are kept

With this API the form interface would be changed to look like:

```typescriptt
interface Form {
  id: string
  // etc...

  [key: string]: any
}
```

Adding metadata would be done like so:

```js
const form = cms.forms.createForm({
  id: "example",
  fields: [
    // ...
  ],
  onSubmit() {},

  // Extra Metadata
  someUsefulValue: 12345
})

console.log(form.someUsefulValue) // 12345
```

The benefit of this approach is convenience when adding metadata.

The major downside is compromises the `interface` types by allowing anything to be added at the top level.

#### Option 2: Extra values can be added to a `meta` property

With this API the form interface would be changed to look like:

```typescriptt
interface Form {
  id: string
  // etc...

  meta: {
    [key: string]: any
  }
}
```

Adding metadata would be done like so:

```js
const form = cms.forms.createForm({
  id: "example",
  fields: [
    // ...
  ],
  onSubmit() {},

  // Extra Metadata
  ignoredValue: "not here",
  meta: {
    someUsefulValue: 12345
  }
})

console.log(form.meta.ignoredValue) // `undefined`
console.log(form.meta.someUsefulValue) // 12345
```

The benefit of this approach is a clear separation between _necessary_ and _accessory_ information about a form. The form `interface` remains stricter, and it's more obvious that data defined in `form.meta` is not part of the core api.

### Motivation

Generally speaking, it's nice to be able to include additional information about a form or where it comes from. 

The specific use-case in mind, is having **global and contextual forms**. The concept of global and contextual forms does not belong in `@tinacms/core`. That package is _only_ about managing the state of the CMS. It's totally unaware of how forms and plugins are used, it just provides the tools for managing them. The difference in these concepts belongs in `tinacms`. 

This ability to include metadata about the form will allow for this concept–and more like it–to be implemented at higher levels.

**Comment by dwalkr** [comment]
I definitely prefer scoping the meta instead of blowing up the top-level interface.

I can think of a few use cases. Do you think this API could be used to make reusable forms that could be configured by altering values in `form.meta`?

**Comment by ncphillips** [comment]
> I definitely prefer scoping the meta instead of blowing up the top-level interface.

Same here. 

> I can think of a few use cases. Do you think this API could be used to make reusable forms that could be configured by altering values in form.meta?

That's definitely a possibility.
