### ISSUE TITLE
Buttons (Search, Create) unreadable in Firefox due to transparent background

### ISSUE THREAD

**Issue by appinteractive** [tinacms/tinacms#4240]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

After I updated Tina and the Cli, the buttons on my pages list are broken in Firefox (see screenshot)

<img width="928" alt="grafik" src="https://github.com/tinacms/tinacms/assets/432828/91b35d81-7974-4b90-a2b7-503e2c778ca2">

The ClassName attribute has `undefined` but in brave and safari it does work:

`icon-parent inline-flex items-center font-medium focus:outline-none focus:ring-2 focus:shadow-outline text-center inline-flex justify-center transition-all duration-150 ease-out  shadow text-white bg-blue-500 hover:bg-blue-600 focus:ring-blue-500 border-0 text-sm h-10 px-4  rounded-full undefined`

On hover the background color appears, but not on focus. 

**I Think it might have to do with #4239** 

### Reproduction

example.com

### Steps to reproduce

1. install latest versions

```
"@tinacms/cli": "^1.5.30",
"tinacms": "^1.5.21"
```

**Note:** I do have a resolution for final-form due to a missing dependency:
```
"resolutions": {
    "final-form": "^4.20.4"
}
```

2. go to a collection page with Firefox

`http://localhost:3000/admin/index.html#/collections/page/~`

3. See broken buttons in Firefox

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 158.84 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - ~/Projekte/client/project/node_modules/.bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Brave Browser: 117.1.58.127
    Firefox: 118.0.1
    Firefox Developer Edition: 116.0
    Safari: 17.0
  npmPackages:
    @tinacms/cli: ^1.5.30 => 1.5.30 
    tinacms: ^1.5.21 => 1.5.21 

```
```


### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@appinteractive linked PR should fix the 'Search' button background color on firefox. I was not able to replicate any issue with the 'Create New' button.
