### ISSUE TITLE
[Feature] Add Support for Top level lists

### ISSUE THREAD

**Issue by onweru** [tinacms/tinacms#4249]
### Discussed in https://github.com/tinacms/tinacms/discussions/4197

<div type='discussions-op-text'>

<sup>Originally posted by **major-mayer** September  9, 2023</sup>
I recently tried to migrate my Hugo Website from Forestry to TinaCMS and have a few problems.
One of it is that the document sections is still not supported as it was in Forestry: https://github.com/tinacms/tinacms/issues/1982

I especially need it for the translation files of which I have a few of.
They are looking like this:
```yaml
---
- id: nav_button
  translation: Kontakt
- id: service_subtitle
  translation: Entdecken Sie
- id: service_title
  translation: Unsere Angebote
```

I tried manually creating a schema, but as this is a top-level list and you can not specify fields of type list, i found no way how to create a schema.

I tried adding a "translations" object on the top level and putting the list below as a workaround:
```ts
fields: [
          {
            type: "object",
            name: "translations",
            label: "Übersetzung",
            list: true,
            fields: [
            {
              type : "string",
              name : "id",
              label  :"ID"
            },
             {
              type : "string",
              name : "translation",
              label : "Translation"
             }
            ],
          },
        ],
```

But when I add "translations" as the top-level object, Hugo's i18n tooling cannot find the translations anymore.
Any idea how to solve this problem?</div>

**Comment by major-mayer** [comment]
Seems like I am not the only one affected by this.
Any workaround for us until we can have a proper solution?

**Comment by logan-anderson** [comment]
@major-mayer currently no work around. TinaCMS would need to support "Top level lists"

**Comment by major-mayer** [comment]
Okay thanks for the confirmation. Then I would like to make this a feature request.

**Comment by jamespohalloran** [comment]
I'm going to close this issue, and re-open: https://github.com/tinacms/tinacms/discussions/4243
(We try and keep feature requests inside GitHub Discussions)
