### ISSUE TITLE
Getting this error message after adding tina to plugins in gatsby:

### ISSUE THREAD

**Issue by rchrdnsh** [tinacms/tinacms#429]
Here is the error:

<img width="1026" alt="Screen Shot 2019-11-01 at 4 27 31 PM" src="https://user-images.githubusercontent.com/7884263/68061941-97147280-fcc4-11e9-9e3d-dd2f906a5cfe.png">

...after only doing this:

```js
{
  resolve: 'gatsby-plugin-tinacms',
  options: {
    plugins: [
      // We'll add some Tinacms plugins in the next step.
    ],
  },
},
```

...in the `gatsby-config` file.

If I comment this out and re-launch the site it works fine...

?

**Comment by ncphillips** [comment]
Hey @rchrdnsh I'm pretty sure this is related to #362 

We've switched `styled-components` to a peer dependency, but that hasn't been released to `latest` yet. 

You could try either making sure the versions of `styled-components` match, or you could install the `@next` or `@canary` releases

e.g.

```
yarn add \
  gatsby-tinacms-git@next \
  gatsby-tinacms-json@next \
  gatsby-tinacms-remark@next \
  gatsby-plugin-tinacms@next
```

**Comment by rchrdnsh** [comment]
yeah, i switched out the styled components version and it works now. I'll give the beta a try after i get a basic example up and running...

thanks @ncphillips :-)
