### ISSUE TITLE
Rich Text cannot load MD files with HTML and breaks

### ISSUE THREAD

**Issue by mustafasahin0** [tinacms/tinacms#4308]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

![image](https://github.com/tinacms/tinacms/assets/96957435/4587deae-bd76-4a39-82cb-71c69d1833c9)

### Reproduction

localhost:1313/admin

### Steps to reproduce

Try adding an HTML code snippet into the body of your Markdown file, and then attempt to access it through the Tina admin panel. You will encounter the error mentioned above.

### System Info

```shell
System:
    OS: macOS 13.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 519.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.9.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/Downloads/prestigeLawAssociates/node_modules/.bin/yarn
    npm: 10.1.0 - /usr/local/bin/npm
    pnpm: 8.9.2 - /usr/local/bin/pnpm
  Browsers:
    Brave Browser: 109.1.47.186
    Chrome: 119.0.6045.105
    Safari: 16.6
  npmPackages:
    @tinacms/cli: ^1.5.31 => 1.5.31 
    tinacms: ^1.5.22 => 1.5.22
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
Hello @mustafasahin0 Can you please provide the markdown file that is breaking this? Thanks

**Comment by mustafasahin0** [comment]
Hi @logan-anderson. I was not able to reproduce the issue. I am going to close this ticket for now and will reopen it if I am able to reproduce the issue again.

**Comment by mustafasahin0** [comment]
Hi @logan-anderson . I was not able to reproduce the issue. I am going to close this ticket for now and will reopen it if I am able to reproduce the issue again.
