### ISSUE TITLE
ui.global is not working when making it true in nextJs/Astro

### ISSUE THREAD

**Issue by prathamesh-acquaint** [tinacms/tinacms#4318]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

- In my AstroJS application I have integrated Tina CMS. In this I have different different collections. 
- For my website I also have global configuration which I want to make editable through Tina. 
- Since it is not a collection I want to display this on any other section on "/admin" page like below "site".
- After Researching I found out that I can do this by defining key called "ui" and in that making **"global: true"**. 
- I tried that in my application, but it is not working. Means, my global field is not coming under "site" section.
- If I make new project with tina with "npx create-tina-app@latest" command and choosing tailwind starter, then this "global: true" is working there.
- I am on a latest version of Tina. (1.5.22). Astro (2.10.14) , Next(14.0.1)

### Reproduction

https://github.com/prathamesh-acquaint/my-app-test2

### Steps to reproduce

- Build any Astro/Next JS app.
- Integrate Tina CMS into it.
- Try to make global field by "ui.global = true".

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 20.04.6 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 4.33 GB / 15.50 GB
    Container: Yes
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 18.12.0 - ~/.nvm/versions/node/v18.12.0/bin/node
    Yarn: 1.22.19 - ~/next-projcts/my-app-test2/node_modules/.bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
  npmPackages:
    @tinacms/cli: ^1.5.31 => 1.5.31 
    tinacms: ^1.5.22 => 1.5.22
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
right now, I believe global only works with contextual editing. Are you using contextual editing on this site?

**Comment by prathamesh-acquaint** [comment]
> right now, I believe global only works with contextual editing. Are you using contextual editing on this site?

No, On my nextJS site I am not using. And for AstroJS it is not available currently right ?

**Comment by logan-anderson** [comment]
> No, On my nextJS site I am not using. And for AstroJS it is not available currently right ?

Contextual editing is only available when using react (client side) so it is possible to use with astro as along as you are usng client side react.

**Comment by jamespohalloran** [comment]
As @logan-anderson mentioned, ui.global: true only has utility for contextual editing. It sounds like you may be interested in single document collections though?:
https://tina.io/docs/editing/single-document-collections/

If you still need help, let us know, but closing for now.
