### ISSUE TITLE
Media Manager does not resize AVIF files

### ISSUE THREAD

**Issue by danurbanowicz** [tinacms/tinacms#4330]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When uploading JPEG images to Tina's media manager, a scaled-down preview thumbnail is generated by the CMS appending a resize parameter to the asset URL e.g. `?fit=crop&max-w=400&max-h=400`.

However, uploaded AVIF files ignore these parameters and instead the full-size image is served as the media manager thumbnail source.

[AVIF Example](https://assets.tina.io/137dcd27-ddf9-4e7f-9ca7-16033eb2b6c5/photo-1684183164497-f62ee4c78620.avif?fit=crop&max-w=400&max-h=400)
[JPEG Example](https://assets.tina.io/137dcd27-ddf9-4e7f-9ca7-16033eb2b6c5/photo-1681843066079-b3b57b0d215a.jpeg?fit=crop&max-w=400&max-h=400)

Each of my AVIF files is around 3-4 MB in size, with as few as 10 full-size AVIF images in the media manager being enough to cause sluggish scrolling.

Seems https://github.com/tinacms/tinacms/pull/3698 attempted to fix an issue with AVIFs in the media manager, but was this behaviour overlooked?

### Reproduction

https://assets.tina.io/137dcd27-ddf9-4e7f-9ca7-16033eb2b6c5/photo-1684183164497-f62ee4c78620.avif?fit=crop&max-w=400&max-h=400

### Steps to reproduce

Upload an `.avif` file to the media manager and check the resulting asset URL to see if resize parameters are being applied.

### System Info

```shell
System:
  OS: macOS 14.0
  CPU: (8) arm64 Apple M1
  Memory: 727.77 MB / 8.00 GB
  Shell: 5.9 - /bin/zsh
Binaries:
  Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
  Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.1/bin/yarn
  npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
Browsers:
  Chrome: 119.0.6045.105
  Safari: 17.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
AVIF is not currently supported by the library used for resizing by repo-based media.
