### ISSUE TITLE
Help with patch for issue noted here: https://tina.io/blog/2023-02-security-update/

### ISSUE THREAD

**Issue by ravenspace** [tinacms/tinacms#4336]
### Discussed in https://github.com/tinacms/tinacms/discussions/4334

<div type='discussions-op-text'>

<sup>Originally posted by **ravenspace** November 15, 2023</sup>
Hello,
I was wondering if someone could point me to a set of steps for installing patch 1.0.9 mentioned in the above link? I've had to step in to help manage a site and tinacms is new to me. My npm audit keeps throwing up the following:

<pre><b># npm audit report</b>

<b>axios</b>  0.8.1 - 1.5.1
Severity: <font color="#A2734C"><b>moderate</b></font>
<b>Axios Cross-Site Request Forgery Vulnerability</b> - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
<font color="#C01C28"><b>No fix available</b></font>
<font color="#AAAAAA">node_modules/@tinacms/cli/node_modules/axios</font>
  <b>@tinacms/cli</b>  *
  Depends on vulnerable versions of <b>axios</b>
  node_modules/@tinacms/cli

2 <font color="#A2734C"><b>moderate</b></font> severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.
</pre>

Any help/pointers greatly appreciated!
 </div>

**Comment by kldavis4** [comment]
Please don't create issues when you just need support. The best place to get support is on our discord: https://discord.com/invite/zumN63Ybpf in the #help channel
