### ISSUE TITLE
[Feature Request] Allow Media Search

### ISSUE THREAD

**Issue by onweru** [tinacms/tinacms#4341]
The current interface of scrolling left and right is a little basic and once you have more than a few pages to click through, a image filename search would speed up the workflow of adding existing images to new content etc.

For example searching "dog" or "swim" would match "dog_going_for_a_swim_in_the_lake.jpg"

This seems timely, given the recent introduction of content search!

_Originally posted by @atinsley67 in https://github.com/tinacms/tinacms/discussions/4036_

**Comment by jamespohalloran** [comment]
Agreed this would be a valuable feature. We try to keep feature requests to GitHub Discussions (and as noted above, this is covered with https://github.com/tinacms/tinacms/discussions/4036), so closing this issue. Hope to tackle this before too long.
