### ISSUE TITLE
Clicking a collection in visual editing opens a different collection

### ISSUE THREAD

**Issue by dawaltconley** [tinacms/tinacms#4345]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have a project with a bunch of single-file collections that route to individual pages. This was working until I added _another_ single-file collection that didn't route anywhere (for global site data). Now, when you click on the single-file collections in Tina's visual editing sidebar, they all route to the correct page but _some_ of them then open the global collection in the sidebar instead of the collection just clicked.

Here's a screen recording of the behavior. You can see that one page works fine and that it's still possible to reach the correct collection data by clicking on `tina-field` elements in the preview.

https://github.com/tinacms/tinacms/assets/20374950/de032022-6b28-4e9d-8500-3b5160ca3ab1

My config is fairly big so I'm just linking to the affected repo. It's an astro site that uses hydration to load components in the visual editor. The single-file collections are `home.yaml`, `press.yaml`, `events.yaml`, and `services.yaml` (the "work with me" page). The new routerless collection that seems to be causing problems is `global.yaml`, which is just the following:

```typescript
const globalData: Collection = {
  name: 'global',
  label: 'Global Data',
  path: 'content/pages',
  match: {
    include: 'global',
  },
  format: 'yaml',
  ui: {
    allowedActions: {
      create: false,
      delete: false,
    },
  },
  fields: [
    {
      type: 'string',
      name: 'socialLinks',
      label: 'Social links',
      list: true,
    },
  ],
}
```

This is added in commit `7faa4e1ecb8` which is where the problem starts. It initially affected the press, events, and "work with me" collections but not the home collection, for some reason. Also inexplicably, the "Work With Me" page is fixed (it _stops_ redirecting to the global data collection) with commit `2bc057f56b3`, which doesn't change the config but adds a new component to page. So I suspect there's something about the contents of the visual editing field (maybe Astro-specific) that's causing this to bug out but I can't tell why. And it doesn't explain why the global collection broke things in the first place.

### Reproduction

https://github.com/dawaltconley/soraya-palmer

### Steps to reproduce

I'm not entirely sure, would appreciate any guidance if anyone knows where to start. I was not able to reproduce it in the [default Tina starter](https://github.com/dawaltconley/tina-bug-next.git) by adding a number of single-file collections routing to individual pages before adding another single-file collection without `ui.router` defined. I was also unable to reproduce it with [a bare-bones Astro setup](https://github.com/dawaltconley/tina-astro/tree/collections-bug).

### System Info

```shell
System:
    OS: Linux 6.5 Pop!_OS 22.04 LTS
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 12.93 GB / 31.25 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/Code/sites/soraya-palmer/node_modules/.bin/yarn
    npm: 9.8.1 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 7.28.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
    Watchman: 4.9.0 - /usr/bin/watchman
  Browsers:
    Chrome: 118.0.5993.117
  npmPackages:
    @tinacms/cli: ^1.5.29 => 1.5.31 
    tinacms: ^1.5.20 => 1.5.22
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@dawaltconley Can you share how you are querying your data? 

If you click on the "Home" Icon can you see the other forms there?

**Comment by dawaltconley** [comment]
I'm mostly using the default / generated query methods for the single-file (page-specific) collections, as well as any other data presented on the page. So for the events page I have this:

```typescript
const [page, events] = await Promise.all([
  client.queries.eventsPage({ relativePath: 'events.yaml' }),
  client.queries.eventsConnection(),
])
```

Each page also queries the global data collection for the footer (it just contains social media links)

```typescript
const data = await client.queries.global({ relativePath: 'global.yaml' })
```

I'm doing static builds with Astro so this only happens during build. All of the query data is then being passed to the `useTina` hook in react components, some of which only hydrate for visual editing.

I do have one custom query that is called on the home page and gets the writing samples (which tbh I might do away with):

```gql
query writingSamples {
  home(relativePath: "home.yaml") {
    writing {
      title
      selections {
        item {
          ... on Writing {
            url
            title
            image
            imageControls {
              alt
              size
              posX
              posY
            }
            publisher
            description
          }
        }
      }
    }
  }
}
```

**Comment by dawaltconley** [comment]
Ok actually it seems that removing or not hydrating the footer component fixes it, so I might have an idea about what's going on.

The very-non-conventional thing I'm doing is using visual editing with with [Astro islands](https://docs.astro.build/en/concepts/islands/). This means that as the page loads in the visual editor, different islands hydrate react components in different parts of the page. As they hydrate, each component passes a serialized Tina query to the `useTina` hook. Most of a page's islands all use the same query (the single-file page collection), but the footer has its own island for social media links which calls `useTina` on the global data collection. It seems like the order in which these are called causes the problem, and that the pages with this problem just happen to hydrate the footer (calling `useTina` on the global collection) _before_ they hydrate the component with a page collection. Would also explain why it's not totally consistent across devices.

Is `useTina` supposed to pull up the first collection in the sidebar that it calls, even if that collection doesn't have a `router` property? I can think about ways around this on the Astro side, but atm I think that's part of the issue.

**Comment by logan-anderson** [comment]
> Is useTina supposed to pull up the first collection in the sidebar that it calls, even if that collection doesn't have a router property? I can think about ways around this on the Astro side, but atm I think that's part of the issue.

Yes, this is correct. To edit the "Global Data" and view real-time updates on your site, the form is displayed in the sidebar. However, if you prefer not to load the form in the sidebar or edit the data with contextual editing you can opt not to use the useTina hook.

@jeffsee55 would have more insight into the expected behavior, but it's likely that the first instance of the useTinaHook call will determine which form appears first in the sidebar.

Can you click the "Home Button" as shown in the screenshot below, select the desired collection, and then edit the Page collection?

<img width="872" alt="Screenshot 2023-11-22 at 10 44 37 AM" src="https://github.com/tinacms/tinacms/assets/43075109/1c031e7b-bdfb-41a8-bfde-4806b1a712a0">

**Comment by dawaltconley** [comment]
> Can you click the "Home Button" as shown in the screenshot below, select the desired collection, and then edit the Page collection?

Ah yes, ok I can pull up the page collections in the sidebar this way. I admit I wasn't aware of that!

This may be more of a feature request than a bug in that case, though I do think it's confusing UX if clicking a collection in the sidebar can result in a different collection populating the menu.

> However, if you prefer not to load the form in the sidebar or edit the data with contextual editing you can opt not to use the useTina hook.

For the moment, I disabled contextual editing on the footer. I think what I'd ideally prefer (and what may not be currently possible) is to enable contextual editing on certain components _without_ (automatically) loading the corresponding form in the sidebar when `useTina` is called. I.e., for this site: I would like the user to be able to pull up the "Global Data" collection in the sidebar by clicking on the footer (which has a `data-tina-field` attribute) and for the footer to visually reflect changes to the Global Data collection via the `useTina` hook, without loading this collection in the sidebar on page navigation. Maybe a flag could address this, something like `useTina(query, { sidebar: false })`, though this may be most relevant for Astro sites that use asynchronous hydration.

Thanks for the help.
