### ISSUE TITLE
@tinacms/cli update to v1.5.34 caused a Collection with specific object field to fail create/update

### ISSUE THREAD

**Issue by mddanish00** [tinacms/tinacms#4355]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

![image](https://github.com/tinacms/tinacms/assets/46325590/93bd1bba-079b-483f-b431-e4eed2c924cf)
![image](https://github.com/tinacms/tinacms/assets/46325590/0a20354c-f173-4195-a664-b5b3e037bd9a)

If I downgrade the @tinacms/cli package to v1.5.31, it works normally again.

### Reproduction

https://github.com/mddanish00/tina-new-ver-save-authhooks

### Steps to reproduce

1. Install all dependencies using yarn.
2. Run `npm run dev`.
3. Go to TinaCMS admin.
4. Pick `Blog Post` collection.
5. Pick one of Blog Post entry.
6. Add a Menu Item.
7. Try to save.
8. See the error.
9. Stop the dev server.
10. Try downgrading @tinacms/cli to v1.5.31
11. Run `npm run dev` again.
12. Try again to add new Menu Item.

### System Info

```shell
System:
    OS: Linux 6.5 Ubuntu 23.10 23.10 (Mantic Minotaur)
    CPU: (4) x64 Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz
    Memory: 10.49 GB / 15.53 GB
    Container: Yes
    Shell: 5.2.15 - /bin/bash
  Binaries:
    Node: 20.9.0 - /tmp/xfs-502d4bc4/node
    Yarn: 4.0.2 - /tmp/xfs-502d4bc4/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.159
  npmPackages:
    @tinacms/cli: 1.5.34 => 1.5.34 
    tinacms: 1.5.24 => 1.5.24
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
Fixed via https://github.com/tinacms/tinacms/pull/4359 will be released soon
