### ISSUE TITLE
client.queries.page broken for `index.mdx`

### ISSUE THREAD

**Issue by appinteractive** [tinacms/tinacms#4357]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

The `client.query.page` have a broken logic where you need to query `index.mdx` with a leading slash. This is new and very irritating as one need to write glue code to fix the issue.

Query through GraphQL does not have that issue.

### Reproduction

example.com

### Steps to reproduce

- add pages `index.mdx`and `features.mdx`
- query them via `http://localhost:3000/admin/index.html#/graphql` with the relative path of `index.mdx` or `features.mdx`
- try the same with `client.queries.page({ relativePath: 'index.mdx' })` and `client.queries.page({ relativePath: 'features.mdx' })`

The first query will NOT WORK. You will need to query it with a leading slash, but ONLY if its `index.mdx` other names work ONLY WITHOUT the slash.

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Max
    Memory: 100.75 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.1 - ~/.nvm/versions/node/v18.16.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.1/bin/npm
  Browsers:
    Brave Browser: 119.1.60.118
    Firefox: 119.0.1
    Firefox Developer Edition: 120.0
    Safari: 17.0
  npmPackages:
    @tinacms/cli: ^1.5.34 => 1.5.34 
    tinacms: ^1.5.24 => 1.5.24
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by logan-anderson** [comment]
@appinteractive I was not able to reproduce this by running `npx create-next-app@latest` and choosing the barebones starter.

here is a demo video: https://www.loom.com/share/da5e1211defd4d7ba739b58c231e6816

I have a feeling that next may have cached the client and you are (somehow) getting an older version but I am not 100% sure since I am not able to reproduce it. If you are able to share a reproduction github repo I would be happy to look into it further.

**Comment by logan-anderson** [comment]
> Is it a new behaviour from the new next "app" folder approach? I did not encounter that issues before.

I think it is. I have seen this happening in a few cases where I will update something and have to delete the .next folder for it to work. Not sure if anything can be done on our end. It seems like a next issue.

**Comment by appinteractive** [comment]
Maybe it's worth mentioning this behavior in the docs!?
