### ISSUE TITLE
Feat: Color swatches

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#436]
## Summary

Would be awesome to extend the color picker to have the option of passing in an array of colors that would comprise a swatch from which users could select.

### Basic example

We could import [Block Picker](http://casesandberg.github.io/react-color/) from react-color and pass in an array of color values given to us by the field options. Then conditionally render either the `SketchPicker` or the `BlockPicker` in `Popover`. Perhaps we add an additional flag in the field options so the dev could pass in whether they want `swatches` or `picker`.

### Motivation

 This will allow devs (& designers) to limit the color options and maintain a cohesive theme.

**Comment by narendrasoni1989** [comment]
hey @kendallstrautman, @ncphillips , @spbyrne     I would like to pick up this enhancement. It just needs some config to be passed in [ColorPicker](https://github.com/tinacms/tinacms/blob/master/packages/%40tinacms/fields/src/ColorPicker/ColorPicker.tsx) and we can switch between SketchPicker or BlockPicker. Could you please share more information. 

So basically i want to know  :

1. Entry point would be from gatsby-config or somewhere else?

2. Naming convention for config eg;

```
{
        'color-picker-type : 'block' | 'sketch',

        'colors' : [array of theme colors],

        'default-color': 'some-color'
}
```

**Comment by ncphillips** [comment]
The entry point would be in the field definition for your form:

```js
export default remarkForm(BlogPostTemplate, {
  fields: [
    {
      name: "background-color",
      component: "color",
      label: "Background Color",
      // ...extra config
  ]
})
```

There are two relevant places to look:

* The [ColorFieldPlugin](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/plugins/fields/ColorFieldPlugin.tsx) in `tinacms`
* The [ColorPicker](https://github.com/tinacms/tinacms/blob/master/packages/%40tinacms/fields/src/ColorPicker/ColorPicker.tsx) component in `@tinacms/fields`

I would suggest two changes to that convention @narendrasoni1989:

* rename `color-picker-type` to `widget`
* remove `default-color` and instead default to the first value in `colors`

Part of me wonders if it would be better if the block and sketch pickers were separate field plugins entirely. I'm not really sold on that idea though.

**Comment by narendrasoni1989** [comment]
Thanks @ncphillips. Let me implement it, i will incorporate if any more feedback comes for this.

**Comment by ncphillips** [comment]
Hey @narendrasoni1989! Did you have any luck implementing this feature?

**Comment by narendrasoni1989** [comment]
@ncphillips , i am sorry about it. I had Stan Chart marathon run last Sunday :) I will continue on this again in a day.

**Comment by weibenfalk** [comment]
Just created a PR on this one on branch weiben#436 ... Fixed so that you can choose picker and default colors. Also refactored into a functional component with state. Think it looks cleaner. But kept the class one commented out if you want to use that instead =)
