### ISSUE TITLE
Is it possible to set tina/config.js to render markdown in double quotes?

### ISSUE THREAD

**Issue by TaylanTatli** [tinacms/tinacms#4362]
### Discussed in https://github.com/tinacms/tinacms/discussions/4117

<div type='discussions-op-text'>

<sup>Originally posted by **wristtattoo** July 31, 2023</sup>
I'd like my markdown to render in my NextJS (.js not .ts) project as `title: "This is my title wrapped in double quotes"` instead of it currently being rendered without as `title: This is my title without any quotes wrapping it`

Is there something i should add in the schema to achieve this? Thanks</div>

**Comment by kldavis4** [comment]
- Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!
- Reproduction
- Steps to reproduce

**Comment by jamespohalloran** [comment]
Not currently possible to configure this. Sounds like this could be folded into this feature request: https://github.com/tinacms/tinacms/discussions/4376
