### ISSUE TITLE
Feat: Add wysiwyg editor & field for HTML

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#437]
## Summary

In addition to a markdown component, it would be awesome to have an html component with the same editing capabilities as the markdown wysiwyg. 

### Basic example

Similar functionality to forestry's textarea field where you select the html format on the widget. 

### Motivation

This could be useful if sourcing from say a json file and you need to content editors to be able to format text.

**Comment by spbyrne** [comment]
One strategy for rich content in JSON is to still use Markdown, and convert the specific nodes to HTML as needed. 

You can modify `gatsby-node.js` with something like this for single nodes: [(thanks LekoArts!)](https://spectrum.chat/gatsby-js/general/transform-markdown-in-json-using-gatsby-transformer-remark-settings~f08bbbc1-6c95-4cab-afcc-9e783ab2a98f?m=MTU3MjE3MTk1MTMyMg==)
```javascript
exports.onCreateNode = ({
  node,
  actions,
  createNodeId,
  createContentDigest,
}) => {
  const { createNode, createNodeField } = actions

  // Check for the correct type to only affect this
  if (node.internal.type === `ExampleJson`) {
    const textNode = {
      id: createNodeId(`${node.id} markdown field`),
      children: [],
      parent: node.id,
      internal: {
        content: node.content,
        mediaType: `text/markdown`, // Important!
        contentDigest: createContentDigest(node.content),
        type: `${node.internal.type}Markdown`,
      },
    }

    createNode(textNode)

    // Add link to the new node
    createNodeField({
      node,
      name: `markdownContent___NODE`, // Before the ___NODE: Name of the new fields
      value: textNode.id, // Connects both nodes
    })
  }
}
```

For something like blocks, @dwalkr was able to wire up a solution for me in the starter we're releasing soon. 

This way your config for transforming markdown can be used for both JSON nodes & your actual markdown files, so if you have posts in `.md` and pages in `.json` everything can work happily together :smile:

I'd go into more depth but my understanding of `gatsby-node.js` isn't there yet. The starter will be a good reference for this.

**Comment by kendallstrautman** [comment]
Nolan mentioned we can port some of this functionality from Forestry to create this component.

**Comment by xaviemirmon** [comment]
Hey @kendallstrautman is this functionality in Forestry open source?  I would much prefer to save my data as HTML over MD

**Comment by DirtyF** [comment]
@xaviemirmon Forestry is not open source (for now).

**Comment by xaviemirmon** [comment]
Dang! @DirtyF any thoughts on how we might progress this?

**Comment by ncphillips** [comment]
Unfortunately I just gotta do it at some point.    I’ll take a look when I got a few minutes, shouldn’t be much work
