### ISSUE TITLE
GraphQL mismatch for seemingly no reason

### ISSUE THREAD

**Issue by lgwapnitsky** [tinacms/tinacms#4389]
I'm receiving this in a local copy of TinaCMS. Nothing seems to clear it, but I can edit.  Advice?

### Discussed in https://github.com/tinacms/tinacms/discussions/3896

<div type='discussions-op-text'>

<sup>Originally posted by **emilyrbowe** May  2, 2023</sup>
As of this AM (~9:40am ET), our Tina site has been giving us the following error: `GraphQL Schema Mismatch. Editing may not work. If you just switched branches, try going back to the previous branch`

<img width="456" alt="image" src="https://user-images.githubusercontent.com/7975988/235786321-546433d6-5213-4dea-97c4-bc83e49e2cde.png">

We did not switch branches and none of the commits that happened within the Tina editor had anything to do with the config. Any ideas how to solve this or if there was something from the TinaCMS end that might have contributed to this?
</div>

**Comment by lgwapnitsky** [comment]
I don't use Tina cloud

**Comment by kldavis4** [comment]
Did you take the other steps? 

The error indicates that the schema that was used to build the TinaCMS admin SPA does not match the schema that is in the database. 

(Please don't hold back relevant information - it just makes it harder to help you. There is a bug template for reporting issues to assist you with this.)
