### ISSUE TITLE
The local GraphQL schema doesn't match the remote GraphQL schema. 

### ISSUE THREAD

**Issue by makovez** [tinacms/tinacms#4394]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

```

8:47:57.214 | Starting Tina build
-- | --
18:48:00.109 |  
18:48:00.109 |  
18:48:00.598 | GChecking indexing process in Tina Cloud... ⠋GChecking indexing process in Tina Cloud... ⠙GChecking indexing process in Tina Cloud... ⠹GChecking indexing process in Tina Cloud... ⠸GChecking indexing process in Tina Cloud... ⠼GChecking indexing process in Tina Cloud... ⠴GChecking indexing process in Tina Cloud... ⠦GChecking indexing process in Tina Cloud... ⠧GChecking indexing process in Tina Cloud... ⠇
18:48:00.598 |  
18:48:01.085 |  
18:48:01.086 | Error: The local GraphQL schema doesn't match the remote GraphQL schema. Please push up your changes to GitHub to update your remote GraphQL schema.
18:48:01.086 |  
18:48:01.086 | Additional info: Branch: master, Client ID: b834ee0c-6a19-4048-9065-119cab214fab
18:48:01.087 | at BuildCommand.checkGraphqlSchema (/opt/buildhome/repo/node_modules/@tinacms/cli/dist/index.js:2966:15)
18:48:01.087 | at processTicksAndRejections (node:internal/process/task_queues:96:5)
18:48:01.087 | at async BuildCommand.execute (/opt/buildhome/repo/node_modules/@tinacms/cli/dist/index.js:2729:7)
18:48:01.087 | at async BuildCommand.validateAndExecute (/opt/buildhome/repo/node_modules/clipanion/lib/advanced/Command.js:73:26)
18:48:01.087 | at async Cli.run (/opt/buildhome/repo/node_modules/clipanion/lib/advanced/Cli.js:223:24)
18:48:01.087 | at async Cli.runExit (/opt/buildhome/repo/node_modules/clipanion/lib/advanced/Cli.js:232:28)
18:48:01.130 | Failed: build command exited with code: 1
18:48:01.916 | Failed: error occurred while running build command

```

I have tina installed in cloud, suddently everythign was working fine and then some few months ago i started to get this message when buildiing tinacms with "npx tinacms build". I don't understand if it's a problem of tinacms version mismatch between client and server or the actual schema is different. It seems like the only changes in the schema are the one shown in below picture, but also I can't find anyway how to update the schema in cloud and why it is different?

I have tried to print the schema of remote and local by adding a log line in tina build code and it seems like this is the difference:
![image](https://github.com/tinacms/tinacms/assets/21694707/5792b0ea-7c47-4c64-967b-4b1d81d1c316)

### Reproduction

npx tinacms build 

### Steps to reproduce

just run npx tinacms build 

### System Info

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor
    Memory: 16.66 GB / 31.96 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.21 - ~\Documents\cannabis-main-new\coltivazionecanapa\node_modules\.bin\yarn.CMD
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.3636.0), Chromium (120.0.2210.61)
    Internet Explorer: 11.0.19041.3636
  npmPackages:
    @tinacms/cli: ^1.5.6 => 1.5.39
    tinacms: ^1.4.6 => 1.5.28
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
when you run the dev command locally on a clean copy of the branch, do you see any changes to the `tina/tina-lock.json` ?

**Comment by makovez** [comment]
worked thx
