### ISSUE TITLE
ERROR: Could not resolve "tinacms"

### ISSUE THREAD

**Issue by tauriRuut** [tinacms/tinacms#4396]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Installed the latest Astro 4.0.4 and latest tinacms 1.5.28.
I did ran Astro first to see if it worked, it did. Followed the implementation guide and changed script for dev to -  "dev": "tinacms dev -c \"astro dev\"" , which after using npm run dev gave me an error -
<img width="618" alt="Screenshot 2023-12-13 at 14 23 51" src="https://github.com/tinacms/tinacms/assets/151632264/21239883-e873-4025-b8e8-7931d27fb237">

Haven't changed any config nor anything after installing.

### Reproduction

-

### Steps to reproduce

1. npm create astro@latest
2. npm run dev
3. npx @tinacms/cli@latest init
4.change script dev to - "dev": "tinacms dev -c \"astro dev\""

### System Info

```shell
Node v 20.9
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by writeonlycode** [comment]
I'm having this issue as well, but with Node v21.1.0 and Next.js 13.

**Comment by tauriRuut** [comment]
Issue was hidden .yarn and .yarn related files in parent folder.

**Comment by wslyvh** [comment]
@tauriRuut do you remember how you resolved this? I'm having similar issues #4530 but so far have not been able to fix it

**Comment by tauriRuut** [comment]
@wslyvh Delete the hidden .yarn and .yarn related folders, check your hidden files in parent folder such a C-drive or finder whatever you are using. And Delete all the .yarn/.npm files.

**Comment by wslyvh** [comment]
Sadly doesn't work for me, but thanks for getting back!
