### ISSUE TITLE
Esbuild bug

### ISSUE THREAD

**Issue by usarral** [tinacms/tinacms#4400]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am installing tinacms on astro and when i run 
pnpm tinacms dev -c 'astro dev'

It throw the error 
  The plugin "vite:dep-pre-bundle" was triggered by this import

The solution is run pnpm update esbuild and then it works

Solution from https://github.com/vitejs/vite/discussions/7695

### Reproduction

pnpm tinacms dev -c 'astro dev'

### System Info

```shell
System:
    OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 8.53 GB / 15.53 GB
    Container: Yes
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    pnpm: 8.11.0 - ~/.nvm/versions/node/v20.10.0/bin/pnpm
  Browsers:
    Brave Browser: 120.1.61.101
    Chrome: 120.0.6099.71
  npmPackages:
    @tinacms/cli: ^1.5.39 => 1.5.39 
    tinacms: ^1.5.28 => 1.5.28
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by ciutadellla** [comment]
Same here, it was working perfect now I can't build anymore

Expand 354 Lines
--
02:08:35.178 | [build:tina] Error: Failed to resolve entry for package "use-deep-compare". The package may have incorrect main/module/exports specified in its package.json.

**Comment by appinteractive** [comment]
same here... it just died

**Comment by appinteractive** [comment]
also there is a message about depricated babel plugins:

```sh
 deprecated subdependencies found: @babel/plugin-proposal-class-properties@7.18.6, @babel/plugin-proposal-object-rest-spread@7.20.7
 ```
 
 They are used by tinacli:
 
 ```sh
dependencies:
@tinacms/cli 1.5.39
├─┬ @graphql-codegen/typescript 4.0.1
│ └─┬ @graphql-codegen/visitor-plugin-common 4.0.1
│   └─┬ @graphql-tools/relay-operation-optimizer 7.0.0
│     └─┬ @ardatan/relay-compiler 12.0.0
│       └─┬ babel-preset-fbjs 3.4.0
│         ├── @babel/plugin-proposal-class-properties 7.18.6
│         └── @babel/plugin-proposal-object-rest-spread 7.20.7
├─┬ @graphql-codegen/typescript-generic-sdk 3.1.0
│ └─┬ @graphql-codegen/visitor-plugin-common 2.13.1
│   └─┬ @graphql-tools/relay-operation-optimizer 6.5.18
│     └─┬ @ardatan/relay-compiler 12.0.0
│       └─┬ babel-preset-fbjs 3.4.0
│         ├── @babel/plugin-proposal-class-properties 7.18.6
│         └── @babel/plugin-proposal-object-rest-spread 7.20.7
├─┬ @graphql-codegen/typescript-operations 4.0.1
│ ├─┬ @graphql-codegen/typescript 4.0.1
│ │ └─┬ @graphql-codegen/visitor-plugin-common 4.0.1
│ │   └─┬ @graphql-tools/relay-operation-optimizer 7.0.0
│ │     └─┬ @ardatan/relay-compiler 12.0.0
│ │       └─┬ babel-preset-fbjs 3.4.0
│ │         ├── @babel/plugin-proposal-class-properties 7.18.6
│ │         └── @babel/plugin-proposal-object-rest-spread 7.20.7
│ └─┬ @graphql-codegen/visitor-plugin-common 4.0.1
│   └─┬ @graphql-tools/relay-operation-optimizer 7.0.0
│     └─┬ @ardatan/relay-compiler 12.0.0
│       └─┬ babel-preset-fbjs 3.4.0
│         ├── @babel/plugin-proposal-class-properties 7.18.6
│         └── @babel/plugin-proposal-object-rest-spread 7.20.7
└─┬ @graphql-codegen/visitor-plugin-common 4.0.1
  └─┬ @graphql-tools/relay-operation-optimizer 7.0.0
    └─┬ @ardatan/relay-compiler 12.0.0
      └─┬ babel-preset-fbjs 3.4.0
        ├── @babel/plugin-proposal-class-properties 7.18.6
        └── @babel/plugin-proposal-object-rest-spread 7.20.7
 ```

**Comment by ciutadellla** [comment]
Weird...  I tried to roll back to a previous working commit on Prod and it also fails to build.

**Comment by f4z3k4s** [comment]
I just wanted to give TinaCMS a try today and instantly bumped into this error. I use it with Next `13.5.4` & tinacms `1.5.28`. I tried with a previous release `1.5.27` but I get the same error.

**Comment by appinteractive** [comment]
I had to restore my package lock file and throw node_modules away and do another package installation. Then it was working as expected. But now I have to be care full to not update 🫣

**Comment by ciutadellla** [comment]
> I had to restore my package lock file and throw node_modules away and do another package installation. Then it was working as expected. But now I have to be care full to not update 🫣

Saved my day 🥳

**Comment by jjuannn** [comment]
> I had to restore my package lock file and throw node_modules away and do another package installation. Then it was working as expected. But now I have to be care full to not update 🫣

Not working for me 🤕 I'm using `nextjs@12.2.5` and `tinacms@latest`

**Comment by ciutadellla** [comment]
> > I had to restore my package lock file and throw node_modules away and do another package installation. Then it was working as expected. But now I have to be care full to not update 🫣
> 
> Not working for me 🤕 I'm using `nextjs@12.2.5` and `tinacms@latest`. @appinteractive are you working with a specific `tinacms` or with the latest?

I have this ones:
   "@tinacms/cli": "^1.5.31",
    "tinacms": "^1.5.22"

**Comment by jjuannn** [comment]
> I have this ones:
> "@tinacms/cli": "^1.5.31",
> "tinacms": "^1.5.22"

Thanks. Tried with those versions but is not working neither

**Comment by appinteractive** [comment]
@jjuannn you have to use the version number without `^` in front because that is indication "at least version x". Therefore try:

```json
"@tinacms/cli": "1.5.31",
"tinacms": "1.5.22"
```

**Comment by daichi-iwamoto** [comment]
This is indeed a temporary workaround, but it has managed to make things work.

Add an `overrides` section to your package.json file, specifying the version of `use-deep-compare` for use with `@tinacms/cli`.

```
  "overrides": {
    "@tinacms/cli": {
      "use-deep-compare": "1.1.0"
    }
  }
```

Then delete the node_modules and package-lock.json files before proceeding to re-install them.
