### ISSUE TITLE
Error fetching media: Something went wrong while requesting resource

### ISSUE THREAD

**Issue by jmhenderson** [tinacms/tinacms#4402]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Issue: Clicking Media Manager or attempting to add an image using online editor provides the following error: 
Error fetching media: Something went wrong while reqeuesting resource

TinaCMS Cloud and Vercel hosted on GitHub.
Issue exits when Using both TinaStarter and Tine Barebones.

Troubleshooting already attempted:
Confirmed public/uploads exists
used Project Config to Sync and Resync Media
Confirmed Media Branch matches repo.
Ran debugger. Image attached. Debugger indicates 

> #Uncaught (in promise) TypeError: l.isAuthenticated is not a function
>     a https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:729
> 

> 
>  #TypeError: this.api.isAuthenticated is not a function
>     isAuthenticated https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:728
>     list https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:728
>     list https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:728
>     H https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:729
>     L7e https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:729
>     NFe https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:41
>     unstable_runWithPriority https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:26
>     l1 https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:37
>     ch https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:41
>     oL https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:39
>     N0e https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:37
>     unstable_runWithPriority https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:26
>     l1 https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:37
>     N0e https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:37
>     Ac https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:37
>     Xhe https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:41
>     EIe https://tina-cloud-starter-sandy-kappa.vercel.app/admin/assets/index-b5e2414e.js:37
> 

<img width="956" alt="media_error" src="https://github.com/tinacms/tinacms/assets/17572454/4e9ff997-739e-4e08-9f46-92572f549413">
<img width="869" alt="media_error2" src="https://github.com/tinacms/tinacms/assets/17572454/67841a9b-6f1a-4e8e-aab9-de7b6eb049f3">

### Reproduction

https://github.com/jmhenderson/tina-cloud-starter

### Steps to reproduce

attempt to open media manager

### System Info

```shell
windows firefox
windows chrome
iOS safari

replicates on all of the above.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
Upgrade to latest @tinacms/cli and tinacms

**Comment by ngocdanhh** [comment]
> Upgrade to latest @tinacms/cli and tinacms

I have updated and fixed the error in the version
`
"@tinacms/cli": "^1.5.39",
 "tinacms": "^1.5.28"
`

**Comment by laveeshthadani** [comment]
Not working with Tina cloud

**Comment by BenKoenig** [comment]
Same issue. 
I'm on the latest version and used the official starter template directly deployed to Vercel. 
Tried both 'Tina Cloud Starter' & 'Barebones Starter'.

Both gave me the same type error, without changing anything.

**Comment by kldavis4** [comment]
> Same issue. I'm on the latest version and used the official starter template directly deployed to Vercel. Tried both 'Tina Cloud Starter' & 'Barebones Starter'.
> 
> Both gave me the same type error, without changing anything.

this is the solution to the `.isAuthenticated is not a function issue`: https://github.com/tinacms/tinacms/issues/4402#issuecomment-1866807131

**Comment by adamcogan** [comment]
CC @kldavis4 
Closing this one - The TinaCMS and TinaCLI updated apparently fixed this.
It has not been an issue for 8 months.
