### ISSUE TITLE
Error message points to a documentation page that does not exist

### ISSUE THREAD

**Issue by clemlatz** [tinacms/tinacms#4427]
The message

> 'Invalid setup. See https://tina.io/docs/tina-cloud/connecting-site/ for more information.'

from the error thrown here 

https://github.com/tinacms/tinacms/blob/d6af1fafadafec6c9dff0c6b481847c6fe333c5b/packages/tinacms/src/tina-cms.tsx#L165

and here

https://github.com/tinacms/tinacms/blob/d6af1fafadafec6c9dff0c6b481847c6fe333c5b/packages/%40tinacms/cli/src/next/codegen/index.ts#L221

points to page page from the documentation that does not exist anymore and thus results in a 404 error.

**Comment by wicksipedia** [comment]
Thanks for reporting this, it looks like this was fixed in https://github.com/tinacms/tinacms/pull/4601

I've added a redirect on the docs site in case anyone has an old version that doesn't have the updated links - https://github.com/tinacms/tina.io/pull/1988
