### ISSUE TITLE
Self-Hosted contentApiUrlOverride Absolute URL

### ISSUE THREAD

**Issue by tchanxx** [tinacms/tinacms#4435]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi, I am trying to self-host the Tina Node backend. 

I noticed that when I set `contentApiUrlOverride` to an absolute URL like `contentApiUrlOverride: "http://localhost:3000/api/tina/gql"` everything works as expected locally. 

However, when I set `contentApiUrlOverride` to a relative url path like `/api/tina/gql` like the docs say, I get:
```
 ✓ Compiled /[slug] in 1064ms (741 modules)
 ⨯ Internal error: TypeError: Failed to parse URL from /api/tina/gql
    at new Request (node:internal/deps/undici/undici:7134:19)
    at R (/Users/yname/Projects/tina-self-hosted-demo/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:340580)
    at doOriginalFetch (./node_modules/next/dist/server/lib/patch-fetch.js:380:24)
    at eval (./node_modules/next/dist/server/lib/patch-fetch.js:508:20)
Cause: TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at new Request (node:internal/deps/undici/undici:7132:25)
    at R (/Users/myname/Projects/tina-self-hosted-demo/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:340580)
    at doOriginalFetch (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/patch-fetch.js:380:24)
    at eval (webpack-internal:///(rsc)/./node_modules/next/dist/server/lib/patch-fetch.js:508:20) {
  input: '/api/tina/gql',
  code: 'ERR_INVALID_URL'
}
```

I would use the absolute URL, but this doesn't work for production purposes since Vercel won't give me the absolute URL while building. 

Any ideas? 

### Reproduction

N/A

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 962.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/Projects/tina-self-hosted-demo/node_modules/.bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.15.1 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 121.0.6167.184
    Safari: 17.0
  npmPackages:
    @tinacms/cli: ^1.5.34 => 1.5.34 
    @tinacms/datalayer: ^1.2.29 => 1.2.29 
    tinacms: ^1.5.28 => 1.5.28
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
the examples in the documentation have relative urls, so /api/tina/gql should work. It looks like you might be on older version of `@tinacms/cli` and `@tinacms/datalayer`, though, so try upgrading those and see if that resolves the issue.

**Comment by tchanxx** [comment]
Thanks for the reply @kldavis4 . I updated all of my packages, and I still get the same error.

I narrowed it down to this generated code:
```js
// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
  options?: { branch?: string }
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: { branch?: string },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}
```

It is failing at:
```js
 const data = await client.request({
      query: doc,
      variables: vars,
      url,
    })
```

Anyway, oddly enough, I was able to fix this problem by avoiding all of the `client` and replacing them with `databaseClient`

**Comment by EthanShoeDev** [comment]
This should be reopened. It is extremely awkward to self host if you are using a SSG framework if the contentApi must be on the same host as the website. 
I ended up having to make a complicated express reverse proxy wrapper around my web app to work around this constraint.

My code ended up looking like this:

```
app.use((req, _res, next) => {
  console.log(req.method, req.hostname, req.path);
  next();
});

app.post('/api/tina/*', async (req, res) => {
  return tinaBackend(req, res);
});

app.get('/api/tina/*', async (req, res) => {
  return tinaBackend(req, res);
});

app.get('/api/s3/media', mediaHandler as any);

app.post('/api/s3/media', mediaHandler as any);

app.delete('/api/s3/media/:media', (req, res) => {
  req.query.media = ['media', req.params.media];
  return mediaHandler(req as any, res as any);
});

app.use(
  createProxyMiddleware({
    target: proxyLocation, // my web app
    changeOrigin: false,
    logger: console,
  }),
);
```

**Comment by JackDevAU** [comment]
Hey All, 

I'll look at bringing this up in our next sprint of work.

**Comment by eknowles** [comment]
fighting over this issue for a while now, and just found this issue.

am I right that you can't self host on vercel anymore and the docs are misleading?
