### ISSUE TITLE
TypeError: this.api.isAuthenticated is not a function when opening Media Manager

### ISSUE THREAD

**Issue by philals** [tinacms/tinacms#4437]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi

After a fresh install on Vercel of the Cloud Starter (via https://app.tina.io/projects/starter) I can edit posts fine. Clicking on the Media Manager results in the attached error.

Auth seems to work fine. 

### Reproduction

https://tina-cloud-starter-fap3.vercel.app/admin#/~ and click Media Manager in the side panel.

Have tried on Firefox and Chrome

### Steps to reproduce

![image](https://github.com/tinacms/tinacms/assets/8849355/6c291769-9908-4f38-a74b-a0d310fc9459)

### System Info

```shell
See attached image.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
Try updating to the latest `tinacms` dependency in your project

**Comment by SalBayat** [comment]
Hi @kldavis4,

Just a quick FYI, I was trialling the TinaCMS cloud product and deployed from the tina.io website into a repo using the cloud starter template and I have run into this same issue.   I'm not running TinaCMS locally.

**Comment by kldavis4** [comment]
Upgrade to latest `tinacms` and `@tinacms/cli`
