### ISSUE TITLE
Form fields removing unused frontmatter fields

### ISSUE THREAD

**Issue by maciekgrzybek** [tinacms/tinacms#445]
## Description

In my markdown file, I hade two frontmatter fields: title and path. In Tina form, I wanted to have only the title, so I've added it to to the fields object as the second parameter in HOC. But when trying to update the title in the form, Tina actually removed the path field from the markdown file.

### Steps to reproduce

- [create Gatsby page](https://www.gatsbyjs.org/docs/adding-markdown-pages/) with markdown files
- in the markdown file add title and path in frontmatter section
- [add Tina to the project](https://tinacms.org/docs/gatsby/manual-setup)
- [add markdown plugins](https://tinacms.org/docs/gatsby/markdown/)
- [customize](https://tinacms.org/docs/gatsby/markdown/#customizing-remark-forms) Tina form, by adding only the title field
### Expected result

When changing the title in the sidebar, the title should change on the front-end and the page shouldn't break.

### Actual result

Page brokes.

### Environment

MacOS 10.14.5
Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by ncphillips** [comment]
Can you provide a link to a repo where this is happening? I cannot reproduce this.

**Comment by maciekgrzybek** [comment]
Sorry I wan't very specific. Let me recreat the repo and I'll post the URL. 
P.S. Forgot to mention that problem occurs when I'm filtering query with the 'path' from frontmatter.

**Comment by maciekgrzybek** [comment]
Hmm this is weird. I had that issue on my work laptop, but now on my personal one it works fine. I'll test it again tomorrow and let you know.

**Comment by maciekgrzybek** [comment]
Just test it on the initial laptop, it seems all right now. Not sure what happened before (code was exactly the same). Closing that as I can't reproduce the bug again.
