### ISSUE TITLE
CMS Mobile UI is broken

### ISSUE THREAD

**Issue by t1gu1** [tinacms/tinacms#4473]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

- I can’t see post name in the list of post.
- The burger menu seems off.
- Post title are too long for the UI
- Would be better to have a page title in a "header/NavBar" with a left square burger menu.
- Padding between screens aren't similar. (Should not be too big on mobile 20px max)

Here some images:

![IMG_4936](https://github.com/tinacms/tinacms/assets/12479055/9c53a046-d010-4470-9a98-32b3278445eb)
![IMG_4937](https://github.com/tinacms/tinacms/assets/12479055/4e91628e-1d04-4834-a264-0af22f5201bc)
 

### Reproduction

Localhost

### Steps to reproduce

Simply use a mobile.

i used a iPhone 15 Pro max to get these results

### System Info

```shell
Tinacms: 1.6.0
Cli: 1.5.42
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by t1gu1** [comment]
Few things here.

In mobile at least: (Some could fit easy on desktop too)

1. Should have a "NavBar" with the title of the page in the center and a square burger menu to the left. (A bit like when the menu is open)
2. The Post List should be more like bloc with list of info one under each other (Or marbe simply display the title?)
3. The search not configure should take full width.
4. When editing a post, the breadcrumb should be under a "NavBar" (1.) and if too long end with a `...`.
5. When editing a post, the change status should be in the right of the "NavBar" (1.)

By fixing that (Header and breadcrumb), it should fix the content under that appear to be too wide.

**Comment by severinkilchhofer** [comment]
I would like to add that it's not possible to add images on mobile at all. Thanks for taking care of all the mobile issues.

**Comment by Jord-Gui** [comment]
@severinkilchhofer Could you please provide more information on this (e.g., screenshots, where this is occurring) or raise an issue for it (if there isn't already one)? Thanks

**Comment by severinkilchhofer** [comment]
@Jord-Gui Thanks for reaching out. Sure, here is a screenshot and a short screencast of the issue:
After the image upload I want to insert the image but the drawer is not responsive and it's not possible to scroll and tap on the button at the bottom. 
![cms_mobile_image_upload](https://github.com/tinacms/tinacms/assets/26141288/6521f898-6918-469d-b3cd-4216c979884e)

https://github.com/tinacms/tinacms/assets/26141288/d832c338-3ad3-430f-9f0d-a147f5a17f3b

**Comment by Jord-Gui** [comment]
@severinkilchhofer There was a fix for this released yesterday. See PR https://github.com/tinacms/tinacms/pull/4607 for details. 

If you update your tinacms to v1.6.5 and @tinacms/cli to v1.5.47, this should be resolved. Let me know if there are any more problems.

**Comment by ncn-ssw** [comment]
Looks like @Jord-Gui has already broken this down into individual issues, will circle back to this PBI when they are done.

**Comment by severinkilchhofer** [comment]
@Jord-Gui Thanks for your quick response. I can now select the image, which is great! However, the UX for the drawer could still use some improvement. Nonetheless, it works for now, and I'm truly grateful for that!

**Comment by Jord-Gui** [comment]
Hi @t1gu1,

We have resolved the mobile UI issue in our latest patch. 

If you update your packages to `@tinacms/cli: 1.5.48` and `tinacms: 1.6.6`, these issues should be fixed.
