### ISSUE TITLE
Regression: nested MDX objects throw parse error

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tinacms#4484]
Nested object structures in MDX template fields throw an error, config:

```ts
import { RichTextField } from '@tinacms/schema-tools'

export const field: RichTextField = {
  name: 'body',
  type: 'rich-text',
  parser: { type: 'mdx' },
  templates: [
    {
      name: 'Table',
      fields: [
        {
          name: 'rows',
          type: 'object',
          list: true,
          fields: [
            {
              name: 'columns',
              type: 'object',
              list: true,
              fields: [
                {
                  name: 'content',
                  type: 'rich-text',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
```
And value:

```jsx
<Table rows={[
    {
      columns: [
        {
          content: {
            type: "root",
            children: []
          }
        }
      ]
    }
  ]} />
```
Cause this error:

```
Unable to parse field value for field \"rows\" (type: object). Expected type to be Literal but received ObjectExpression
```

**Comment by jmarks-joshua** [comment]
For me this works as I'm embedding and entering the data for the template, but then gives this error only on refresh of the browser. Not sure if that is helpful, but thought I'd add just in case.

**Comment by JackDevAU** [comment]
I'm excited to announce that the issue regarding nested MDX objects has been resolved 🎉

**How to Update and Test:**

Update your TinaCMS package to version `1.6.3`:  

```bash
npm i tinacms
```

Refer to this example (if you want to try it out): https://github.com/tinacms/tinacms/blob/598bb59701e05643d27d472b415d3b81c3ec27fc/packages/%40tinacms/mdx/src/next/tests/mdx-basic-nested-objects-2/field.ts
