### ISSUE TITLE
Typo throwing exception

### ISSUE THREAD

**Issue by adriano-tirloni** [tinacms/tinacms#4489]
Pretty sure this typo is giving the following error.
https://github.com/tinacms/tinacms/blob/141e78c04333a137ab0f07cd1b434bb40de6944e/packages/tinacms/src/toolkit/react-sidebar/components/sidebar.tsx#L517

Error:
![image](https://github.com/tinacms/tinacms/assets/6390605/af62d456-87d2-4b40-a9b3-d98f3bc4cdc4)

**Comment by aryans1319** [comment]
Hey @adriano-tirloni can I work on this issue?
