### ISSUE TITLE
Saving process indicator on the the save button

### ISSUE THREAD

**Issue by maciekgrzybek** [tinacms/tinacms#449]
## Summary

When you click on a save button in the form, there's no indication that saving is actually happening. That can confuse the user as he won't know if the saving is happening. I want to add a simple loader on the button.

![Screen Recording 2019-11-07 at 13 44 35 (1)](https://user-images.githubusercontent.com/16546428/68394780-5efaad00-0166-11ea-8db4-d14152c99e64.gif)

### Motivation
User Story:
As a CMS user
When I changed the content in the Tina form and click the save button
I want to see some kind of visual indicator that the save process started
So I am sure that the CMS is working correctly

**Comment by maciekgrzybek** [comment]
Happy to work on it by the way.

**Comment by maciekgrzybek** [comment]
I've managed to add the functionality to my local version. For now, I got a dummy text Save / Saving... Is that approach you guys want? Or is it better to put in a spinner?

**Comment by maciekgrzybek** [comment]
I looked for some UX/UI articles about it, but most of them are more about general content loading, not situations like this one.

**Comment by DirtyF** [comment]
I can imagine: 
 1. a not too subtle progress bar to convey an action is currently taking place
 2. Save button is disabled while it's saving

We must think how it should feel in different situations, almost noticeable on 5G, very slow on Li-Fi, etc.
@spbyrne ?

**Comment by maciekgrzybek** [comment]
I agree with disabled button, but it's also disabled after successfull save, so I guess we would need to distinguish these two states as well.

**Comment by maciekgrzybek** [comment]
Also, from the perspective of someone from outside of the project, making the button disabled after the successful save is a good interaction, but also not very obvious about what just happened. What do you think a out adding some kind of notification that you can close (or it will disappear after a few seconds)? Something like [this](https://ant.design/components/notification/).

**Comment by maciekgrzybek** [comment]
Just to be clear, I'm not trying to criticize anything :) Just some feedback :)

**Comment by DirtyF** [comment]
To be clear, I was thing of something like Zeit does, the label is replaced by an animation while action is happening: 

<img width="553" alt="progress-button-zeit" src="https://user-images.githubusercontent.com/103008/68475898-a4cc7980-0229-11ea-8d6a-8e907ef1fff5.png">

**Comment by maciekgrzybek** [comment]
Yeah, I also think that would be the best solution.

**Comment by maciekgrzybek** [comment]
I'll create a loading indicator component and add a PR this weekend if that's allright with everyone.

**Comment by ncphillips** [comment]
Absolutely! Thanks @maciekgrzybek 

@all-contributors please add @maciekgrzybek for ideas

**Comment by maciekgrzybek** [comment]
Nice one thanks :)

**Comment by spbyrne** [comment]
Thanks again @maciekgrzybek, the save indicator looks great! 👍
