### ISSUE TITLE
`Component` type incompatible with `wrapFieldsWithMeta` type

### ISSUE THREAD

**Issue by bencmbrook** [tinacms/tinacms#4518]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

The type returned from `wrapFieldsWithMeta` includes a `form` property: 

https://github.com/tinacms/tinacms/blob/18c674b79dc09c284842e3a6c330a19913c2987d/packages/tinacms/src/toolkit/fields/plugins/field-props.ts#L4-L8

However, the `Component` type does not expect this property:

https://github.com/tinacms/tinacms/blob/18c674b79dc09c284842e3a6c330a19913c2987d/packages/%40tinacms/schema-tools/src/types/index.ts#L10-L33

Reproduction:

```tsx
import { wrapFieldsWithMeta, type Collection } from 'tinacms';

export const myCollection: Collection = {
  label: 'Docs',
  name: 'doc',
  path: 'docs',
  format: 'mdx',
  fields: [
    {
      name: 'body',
      type: 'string',
      label: 'Doc Content',
      required: true,
      isBody: true,
      ui: {
        component: wrapFieldsWithMeta((props) => <input />),
        // ^^^ Property 'form' is missing on `component` expected type, but included on `wrapFieldsWithMeta` return type
      },
    },
  ],
};
```

Yields this TypeScript error:

> Property 'form' is missing in type '{ field: TinaField<false> & { namespace: string[]; }; input: { name: string; onBlur: (event?: FocusEvent<string, Element> | undefined) => void; onChange: (event: ChangeEvent<...>) => void; onFocus: (event?: FocusEvent<...> | undefined) => void; type?: string | undefined; value: string[]; }; meta: Meta; }' but required in type 'FieldProps<TinaField<false> & { namespace: string[]; }>'.

<details>

<summary>Complete TypeError:</summary>

```
Type '(props: InputFieldType<{ field: TinaField<false> & { namespace: string[]; }; input: { name: string; onBlur: (event?: FocusEvent<string, Element> | undefined) => void; onChange: (event: ChangeEvent<...>) => void; onFocus: (event?: FocusEvent<...> | undefined) => void; type?: string | undefined; value: string; }; meta...' is not assignable to type 'string | Component<string, true> | null | undefined'.
  Type '(props: InputFieldType<{ field: TinaField<false> & { namespace: string[]; }; input: { name: string; onBlur: (event?: FocusEvent<string, Element> | undefined) => void; onChange: (event: ChangeEvent<...>) => void; onFocus: (event?: FocusEvent<...> | undefined) => void; type?: string | undefined; value: string; }; meta...' is not assignable to type 'Component<string, true>'.
    Types of parameters 'props' and 'props' are incompatible.
      Type '{ field: TinaField<false> & { namespace: string[]; }; input: { name: string; onBlur: (event?: FocusEvent<string, Element> | undefined) => void; onChange: (event: ChangeEvent<...>) => void; onFocus: (event?: FocusEvent<...> | undefined) => void; type?: string | undefined; value: string[]; }; meta: Meta; }' is not assignable to type 'InputFieldType<{ field: TinaField<false> & { namespace: string[]; }; input: { name: string; onBlur: (event?: FocusEvent<string, Element> | undefined) => void; onChange: (event: ChangeEvent<...>) => void; onFocus: (event?: FocusEvent<...> | undefined) => void; type?: string | undefined; value: string; }; meta: Meta; ...'.
        Property 'form' is missing in type '{ field: TinaField<false> & { namespace: string[]; }; input: { name: string; onBlur: (event?: FocusEvent<string, Element> | undefined) => void; onChange: (event: ChangeEvent<...>) => void; onFocus: (event?: FocusEvent<...> | undefined) => void; type?: string | undefined; value: string[]; }; meta: Meta; }' but required in type 'FieldProps<TinaField<false> & { namespace: string[]; }>'.
```

</details>

### Reproduction

See description for a simple repro

### System Info

```shell
`"tinacms": "^1.6.3",`

`"typescript": "^5.4.2",`
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by dawaltconley** [comment]
This issue is still relevant in Tina v2.8.2. Results in an incorrect type error for any component created with wrapFieldsWithMeta
