### ISSUE TITLE
Could not resolve "tinacms"

### ISSUE THREAD

**Issue by wslyvh** [tinacms/tinacms#4530]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I realize this is likely an issue with my local setup, but opening an issue for any tips/insights that could help resolve.`

Any (clean) installation of tina CMS is unable to resolve tinacms on start up.
```
> starter-basic@0.1.0 dev
> tinacms dev -c "next dev"

Starting Tina Dev Server

Build failed with 1 error:
tina/config.js:1:29: ERROR: Could not resolve "tinacms"

Unable to start dev server, please fix your Tina config / resolve any errors above and try again
```

### Reproduction

https://github.com/wslyvh/tina-repro

### Steps to reproduce

I've tried different ways to to set up and install a clean Tina solution, but all with the same result and error on dev/build.
1. Forked the tina-barebones-starter https://github.com/tinacms/tina-barebones-starter
2. Create new Nextjs site and then https://tina.io/docs/frameworks/nextjs/
3. npx create-tina-app@latest

The reproduction link at https://github.com/wslyvh/tina-repro is from option # 3 and currently does NOT run for me.
e.g. `npm install` && `npm run dev`

Possible similar issue to #4396 - but cleaning up node_modules/tmp/folders, etc. did not solve it for me, unfortunately

For testing purposes, I tried to remove `import { defineConfig } from "tinacms"` and the `defineConfig({ .. })`, which does allow to start Tina (but obv. doesn't have a properly functioning CMS)

Any tips would be appreciated!

### System Info

```shell
System:
    OS: Linux 6.8 Pop!_OS 22.04 LTS
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz
    Memory: 28.33 GB / 39.02 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 20.13.1 - ~/.nvm/versions/node/v20.13.1/bin/node
    Yarn: 1.22.19 - ~/Code/tina-repro/node_modules/.bin/yarn
    npm: 10.5.2 - ~/.nvm/versions/node/v20.13.1/bin/npm
    bun: 1.0.26 - ~/.bun/bin/bun
  npmPackages:
    @tinacms/cli: ^1.5.34 => 1.5.34 
    tinacms: ^1.5.24 => 1.5.24
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by JackDevAU** [comment]
Hey @wslyvh 

I just tried this from your repo in GitHub Codespaces and was able to reproduce your issue given your repo. I was able to fix the `tinacms missing` by deleting the `yarn.lock` file and re-running `yarn`. 

Hope that helps!

From:

<img width="432" alt="image" src="https://github.com/tinacms/tinacms/assets/57518417/3d497e80-cd25-4a94-94a2-126e8978bb4e">


To:

<img width="535" alt="image" src="https://github.com/tinacms/tinacms/assets/57518417/b0288470-9c0b-4625-a622-3ac2f1361149">

**Comment by wslyvh** [comment]
Hi @JackDevAU - thanks for testing it out (and apologies for the late response), but unfortunately doesn't work for me.
I tried with different package managers as well (yarn, npm and pnpm), but all same issue :(

I'm sure it's related to my local machine, but even after completely removing yarn/pnpm and all its caches/subfolders, etc. I still get the same issue. Only with with tinacms, unfortunately.

**Comment by Ben0189** [comment]
Check if you have a yarn.lock (or package.json) file higher up in the filetree from the project in your local machine, try removing them if there is any and redo yarn install see if that helps😊

**Comment by JackDevAU** [comment]
Glad you got it working though 🚀

**Comment by caph1993** [comment]
I was having the same issue. The solution for me was this: https://github.com/tinacms/tinacms/issues/4396#issuecomment-2115080647
