### ISSUE TITLE
Tina & NextJS: Changes in the admin panel don't reflect on the site in dev mode

### ISSUE THREAD

**Issue by nayaabkhan** [tinacms/tinacms#4534]
### Discussed in https://github.com/tinacms/tinacms/discussions/4532

<div type='discussions-op-text'>

<sup>Originally posted by **nayaabkhan** May 17, 2024</sup>
Hello, I'm using Tina with Next, following the tutorial on https://youtu.be/PcgnJDILv4w?si=PzyQSZEiaL_VPLg3. However, making changes in the Tina admin panel to a field value doesn't reflect on the site, it seems it is cached. This is running dev servers `"tinacms dev -c \"next dev\""`

The changes are only reflected after removing the `.next` folder and restarting the server.

Have tried the `npx @tinacms/cli@latest init` command too. Same result.

Here's a reproduction repo: https://github.com/nayaabkhan/innovace.studio</div>

**Comment by SasquatchPunter** [comment]
Repo link is broken.

**Comment by nayaabkhan** [comment]
Sorry, I had to make it private as we're making progress on the site and we've switched over to Astro for now. There is seems to work fine.

I'll recreate another public repo and post here.
