### ISSUE TITLE
Created folder is invisible if no items are added but keeps existing

### ISSUE THREAD

**Issue by nekdolan** [tinacms/tinacms#4566]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

If you create a folder, but add not items Tina will add the folder on disk, but won't show it in the collection. This will prevent access to the folder via the UI and since the folder does exist makes it impossible to create another with the same name.

I don't think this issue is related to my code specifically.

### Reproduction

https://github.com/tinacms/tinacms

### Steps to reproduce

1. Create folder and instead adding an item go back to collection level. -> Folder will be invisible.
2. Try to make a folder with the same name. -> Error message

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (12) arm64 Apple M3 Pro
    Memory: 65.23 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.20.2 - ~/.nvm/versions/node/v18.20.2/bin/node
    Yarn: 1.22.22 - ~/WebstormProjects/farsight-org/node_modules/.bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v18.20.2/bin/npm
    bun: 1.1.8 - ~/.bun/bin/bun
  Browsers:
    Chrome: 125.0.6422.176
    Edge: 126.0.2592.56
    Safari: 17.5
  npmPackages:
    @tinacms/cli: ^1.5.46 => 1.5.46 
    tinacms: ^1.6.4 => 1.6.4
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
@nekdolan thanks for the report - pr for fix is linked above (cc @ncn-ssw @brookjeynes-ssw)
