### ISSUE TITLE
🧪 TinaCMS - Replace Cypress with Playwright e2e tests

### ISSUE THREAD

**Issue by JackDevAU** [tinacms/tinacms#4580]
CC @wicksipedia @Ben0189 

**Hey Team,**

Currently, the project uses Cypress to run some end-to-end tests. We've decided to transition from Cypress to Playwright. We'll start by moving the existing Cypress tests to Playwright and then fully adopt Playwright for our end-to-end testing.

>[!IMPORTANT] 
> Due to some pipeline issues, we are skipping the Cypress e2e tests. 

### Editing Text & Rich Text

- [x] Implement test to edit and verify subtitle and heading.
- [x] Implement test to edit and verify bold text, paragraphs, and quotes.

###  Italic Text

- [x] Implement test to verify that italic text is correctly rendered from markdown.
- [x] Implement test to verify that italic text can be typed.

### Bold Text

- [x] Implement test to verify that bold text is correctly rendered from markdown.
- [x] Implement test to verify that bold text can be typed.

### Headings

- [x] Implement test to verify that headings are correctly rendered from markdown.
- [x] Implement test to verify that headings can be typed.

### New Lines

- [x] Implement test to verify that new lines are correctly rendered from markdown.
- [x] Implement test to verify that new lines are correctly rendered from markdown with backslash.
- [x] Implement test to verify that new lines can be typed.

### Paragraphs

- [x] Implement test to verify that paragraphs can be typed.
- [x] Implement test to verify that paragraphs are correctly rendered from markdown. 

~~### Have Edit Mode Button~~

- ~~[ ] Implement test to verify that the user can log in.~~
- ~~[ ] Implement test to verify that the "Enter Edit Mode" button is present and can be clicked.~~
- ~~[ ] Implement test to verify that clicking the "Enter Edit Mode" button sets the `tina.isEditing` value in local storage to `true`.~~
(Removed as low value UI test)

**Comment by Ben0189** [comment]
First stage migrations (only rich text editor)

PR - https://github.com/tinacms/tinacms/pull/5211
