### ISSUE TITLE
💄TinaCloud project config - Improve site URL UX

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tinacms#4584]
See tweet and attached video
https://x.com/cdvillard/status/1799083214792978506

The site URLs field UX is not great.

1. UX - When you type a URL and press enter or click `Add`, you need to click `Save Configuration` as well 👎🏻  - this is not clear
2. ⚠️ Loss of data - When you leave the page, it doesn't warn you there are unsaved changes

To fix, there are a few improvements to implement.

1. Save URLs when `Add` button is clicked
2. You should never be able to navigate away from an unsaved form - ensure there is a warning when you try navigate with unsaved changes
3. Save button - Make it disabled until there are unsaved changes

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by wicksipedia** [comment]
💯 Agree with the above

> 2. You should never be able to navigate away from an unsaved form - ensure there is a warning when you try navigate with unsaved changes

This as well but this will be an issue when we upgrade the version of react-router we are on - I think this should be delayed for now

**Comment by brookjeynes-ssw** [comment]
Work has starting in https://github.com/tinacms/tinacloud/tree/save-tags-independent

**Comment by brookjeynes-ssw** [comment]
Done - here's a done video explaining the new changes - https://www.youtube.com/watch?v=X0R-6PCKmy4
