### ISSUE TITLE
gatsby-tinacms-remark fails inelegantly if gastby-transformer-remark is missing

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#460]
## Description

`gatsby-tinacms-remark` should have `gatsby-transformer-remark` as a peerDependency

### Steps to reproduce

* Create a site that does not use `gatsby-transformer-remark`
* Run `yarn add gatsby-tinacms-remark` 

### Expected result

It should warn about `gatstby-transformer-remark` being a peer dependency

### Actual result

No peer dependency warnings.

Trying yo start the server returns this error

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Unknown type "MarkdownRemark".

File: node_modules/gatsby-tinacms-remark/src/remark-fragment.ts:22:26

failed extract queries from components - 0.191s
```

**Comment by maciekgrzybek** [comment]
I could take a look at this one if it's ok.

**Comment by ncphillips** [comment]
That would be great! One other thing: the error should also say that it needs to be listed as a plugin

**Comment by maciekgrzybek** [comment]
Ok I'll add it then, thanks :)

**Comment by maciekgrzybek** [comment]
So @ncphillips just to clarify, do we want to add the message when installing the tina plugin? or on the build?

**Comment by ncphillips** [comment]
At the very least during install and ideally when running as well.

Setting it as a `peerDependency` would automatically make it show up when installing the plugin.

I'm not sure how you could throw the error whens starting though.

**Comment by maciekgrzybek** [comment]
I've added the PR - https://github.com/tinacms/tinacms/pull/483

**Comment by defaultz12** [comment]
I am still seeing Markdown issue using gatsby.
- "gatsby-tinacms-remark": "^0.5.1",
- "gatsby-transformer-remark": "^2.6.0", and ^2.6.38

**Comment by maciekgrzybek** [comment]
Is it the same error as mentioned [here](https://github.com/tinacms/tinacms/issues/460#issue-521793473) ?

**Comment by arielwebriq** [comment]
I figured it out. I was doing the manual set-up. It needs to have a gatsby markdown ready before setting up tinaCMS.

**Comment by witcradg** [comment]
> I figured it out. I was doing the manual set-up. It needs to have a gatsby markdown ready before setting up tinaCMS.

This needs to be documented. It bit me too.

**Comment by ncphillips** [comment]
I'm not sure anything more can be done for this. Closing for now.
