### ISSUE TITLE
⚙️ TinaCMS - rich-text field - configure toolbar buttons

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tinacms#4611]
For rich-text fields, the current toolbar has things like bold + italic pretty far to the right - some feedback from users is that it would be better if you could customise the options.

Toolbar order source - https://github.com/tinacms/tinacms/blob/main/packages/tinacms/src/toolkit/fields/plugins/mdx-field-plugin/plate/plugins/ui/toolbar/index.tsx

- [x] Add prop to field schema (array) to define order of toolbar buttons
      If `undefined` or `null` default to existing order
- [x] update docs as required
- [ ] include done video

![Image](https://github.com/tinacms/tinacms/assets/600044/4efaf303-94cd-43f1-a4d7-c3bb27b437ea)
**Figure: some of the toolbar buttons aren't useful, or they get hidden on smaller screens**

![Image](https://github.com/tinacms/tinacms/assets/600044/6ab94305-581f-4e71-ac7a-03f8b1587509)
**Figure: proposal - being able to define the order at a schema level would be useful**

**Comment by brookjeynes-ssw** [comment]
Done - https://youtu.be/O1d3OJmqmdc
