### ISSUE TITLE
♻️ TinaCMS - Use css instead of @react-hook/window-size

### ISSUE THREAD

**Issue by Jord-Gui** [tinacms/tinacms#4627]
Cc: @JackDevAU 

There are a few places where we are using @react-hook/window-size to adjust elements based on screen size. It would be better to use css media breakpoints instead to keep everything consistent.

This may require setting a breakpoint for `1000px` in a configuration file and then using it in the Tailwind config to ensure consistency with our existing breakpoints.

- [x] See if a 1000px is necessary
- [x] Refactor the code to use css media breakpoints

![Image](https://github.com/tinacms/tinacms/assets/41951199/47548772-d14d-4b22-9502-d1dc9e62daba)

**Figure: Places where @react-hook/window-size is being used in the code**

**Comment by Jord-Gui** [comment]
Cc: @JackDevAU @wicksipedia @Ben0189 

As per my conversation with @jeffsee55, there might be some extra usage in using the react hook, but its ok to convert to css if everything works. 

- [ ] Check whether the iframe works correctly in css as there might be some extra usage in the sidebar.ts and Sidebar.ts files
- [ ] Check that [index.tsx](https://github.com/tinacms/tinacms/blob/141e78c04333a137ab0f07cd1b434bb40de6944e/packages/tinacms/src/admin/index.tsx) works properly in css (might be some problems with the stickiness)

**Comment by Jord-Gui** [comment]
Update

- The usage in sidebar.ts and Sidebar.ts is valid as the rendering conditions are rather complex

**Comment by ncn-ssw** [comment]
✅ Done - details above
