### ISSUE TITLE
Imports from `tina/config.ts` cannot be resolved

### ISSUE THREAD

**Issue by Lordfirespeed** [tinacms/tinacms#4654]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have some templates imported in my `tina/config.ts`:

```ts
import { defineConfig } from "tinacms";
import {
  homePageHeroTitleTemplate,
  homePageHeroBlurbTemplate,
  homePageHeroLinksTemplate,
  homePageHeroLinkTemplate,
  homePageHeroTemplate,
} from "@/components/home-page-hero";
```

When I run the `dev` server, the import cannot be resolved as the config is compiled to a `.jsx` file which has no knowledge of path aliases defined in `tsconfig.json`.

### Reproduction

None yet

### Steps to reproduce

- Initialise Tina & Next.js
- define a template in `src/myTemplate.ts`
- Import the template to `tina/config.ts` with `import { myTemplate } from "@/myTemplate";`
- Try to run the dev server

### System Info

```shell
System:
    OS: Linux 5.15 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
    CPU: (16) x64 13th Gen Intel(R) Core(TM) i7-1360P
    Memory: 5.14 GB / 7.61 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 21.7.1 - ~/.nvm/versions/node/v21.7.1/bin/node
    npm: 10.5.0 - ~/.nvm/versions/node/v21.7.1/bin/npm
    pnpm: 9.5.0 - ~/.local/share/pnpm/pnpm
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by mr-shortman** [comment]
Import/Path alias is the reason for this error. I dont know how to fix it beside using relative paths in your example 
`import { ... } from "../../../components/home-page-hero"` instead of `import { ... } from "@/components/home-page-hero";`
Would love to see a solution with the path alias

**Comment by Lordfirespeed** [comment]
> Would love to see a solution with the path alias

Solution would involve configuring the 'bundler' responsible for building tina's config to read path aliases from the project's typescript config

**Comment by JackDevAU** [comment]
Hey @Lordfirespeed 

I'm going to close this issue as we are currently tracking this under https://github.com/tinacms/tinacms/issues/5281 (Duplicate Issue). We've made some good progress so far and will hopefully get this out soon™

**Comment by Lordfirespeed** [comment]
> I'm going to close this issue as we are currently tracking this under [#5281](https://github.com/tinacms/tinacms/issues/5281) (Duplicate Issue)

what a scam!! I was here first!! /j :rofl:

Thanks for the good news!
