### ISSUE TITLE
🐛 TinaCMS - Media Manager - Unable to upload videos to external media providers

### ISSUE THREAD

**Issue by Jord-Gui** [tinacms/tinacms#4657]
Cc: @ncn-ssw @kldavis4 @JackDevAU @wicksipedia @Ben0189 

Found while working on https://github.com/tinacms/tina-cloud/issues/2078. 

An error is occurring when trying to upload a video to Cloudinary using the media manager (repo based media is working fine). This may be the same issue that @joshbermanssw got when trying to upload a video to Tina Cloud (follow https://github.com/tinacms/tina-cloud/issues/2078#issuecomment-2234656602 if needed). 

I reckon there's hard code somewhere that treats uploads as image only.
![Image](https://github.com/user-attachments/assets/40535d8a-21b8-4ac9-a382-043026e7e664)
**Figure: Error received after uploading a .mp4 file**

The error returned by the media manager UI is also too generic and needs some fixing up.
![Image](https://github.com/user-attachments/assets/cb8879a7-33a0-452b-902e-ecfc13f97695)
**Figure: The errors shown in the UI (above) vs the actual errors in console (below)**

- [x] Fix the clarity of the error message
- [x] Fix the video upload issue

**Comment by kldavis4** [comment]
@Jord-Gui this looks like it might be the solution to this issue: https://stackoverflow.com/a/32887402 - so I think adding `'resource_type': 'auto'` to the params [here](https://github.com/tinacms/tinacms/blob/main/packages/next-tinacms-cloudinary/src/handlers.ts#L76) should fix it

**Comment by Jord-Gui** [comment]
Update: 
- Looks like the Cloudinary issue is actually separate to the Tina cloud issue. I'll create another PBI to track the Tina Cloud one.

**Comment by Jord-Gui** [comment]
Changes have been merged into main, awaiting next release

**Comment by Jord-Gui** [comment]
✅ Done - released in [tinacms v2.1.0](https://github.com/tinacms/tinacms/pull/4675)
