### ISSUE TITLE
🐛Tina CMS - Tina Cloud Authorization failed - Invalid Site URL

### ISSUE THREAD

**Issue by KristenHu** [tinacms/tinacms#4659]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am trying to log in to Tina CLoud via GitHub, but the pop shows that it's an invalid site URL after I click the "Authorization with GitHub" button.
![image](https://github.com/user-attachments/assets/70b00a54-ebf9-433b-9fbf-eee2b5bb8166)

### Reproduction

https://kristenhu.github.io/tina-cloud/admin/

### Steps to reproduce

1. Click the "Continue to Tina Cloud" button
![image](https://github.com/user-attachments/assets/f6024458-4084-4bb4-9c57-3b9086c5f235)

2. Click the "Authorization with GitHub" button
![image](https://github.com/user-attachments/assets/14bc99ee-0ee4-46a3-ad63-017b2e287478)

### System Info

```shell
Browser: Google Chrome Version 126.0.6478.127
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by ncn-ssw** [comment]
Hi @KristenHu,

I have checked your records in Tina Cloud and your account appears to be configured correctly.

- Do you see "https://kristenhu.github.io" in your project overview at [Tina Cloud](https://app.tina.io) at the location indicated in the screenshot below?
- If you are already logged in to [Tina Cloud](https://app.tina.io), are you still getting the same error when you authenticate at https://kristenhu.github.io/tina-cloud/admin/ ?

![image](https://github.com/user-attachments/assets/67a60398-4b6a-486d-a8da-01ae5c1e312a)
**Figure: Site URLs location on the project overview**

**Comment by KristenHu** [comment]
Succeed after clearing the cache data😊
