### ISSUE TITLE
💄 Collection explorer - Search results don't show file path

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tinacms#4667]
TIL TinaCMS search also searches subfolder, which is really cool 🙂
The UI could be improved. 

Sometimes there are multiple files with the same name, in different folders. The search results do not say which folder they are in

- [x] Make it clear what folder the files are in (see 2nd image as an example)

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/d5b2c35b-48bb-48b3-acbf-52e81f6b2152">

**Figure: ❌ 2 `faq.md` files, what folders are they in?**

<img width="622" alt="image" src="https://github.com/user-attachments/assets/1e64e47d-00eb-4ef6-b3f6-2324dae3aedb">

**Figure: ✅ VSCode - path is next to the filename in grey**

**Comment by Jord-Gui** [comment]
Merged into main - awaiting next release

**Comment by Jord-Gui** [comment]
✅ Done - this has now been released
