### ISSUE TITLE
🐛 TinaCMS - Media Manager - Editing raw markdown UI bug

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tinacms#4678]
**To Reproduce**

Edit a rich-text type field in the CMS, select three dots and click Raw markdown. Ensure content within the field exceeds the length of 1 view port. Scroll down in the parent container (not inside the rich text field container).  You should view the 'View in rich-text editor' button start overlapping some of the text inside the field. 

**Expected Solution**

When scrolling in the parent container, the 'view in rich-text editor' button does not move. 

**Media**

Heres what it looks like on my end, pay attention to the top left of the editor whilst i scroll :) 

https://github.com/user-attachments/assets/af53b310-1a93-4b6e-94d3-efe5a5ab6644

**Comment by Jord-Gui** [comment]
In main now, awaiting a new release.

**Comment by Jord-Gui** [comment]
✅ Done - change is in patch release [v2.0.2](https://github.com/tinacms/tinacms/pull/4687)
