### ISSUE TITLE
🔌 Rich text - update table plugin

### ISSUE THREAD

**Issue by wicksipedia** [tinacms/tinacms#4681]
Newer versions of plate have a great table editing experience - we should leverage that to improve the editing experience

- [x] Support https://platejs.org/docs/components/table-element

**Comment by Jord-Gui** [comment]
Remaining work

- [ ] Ensure code and other blocks saved in the table cell save properly

**Comment by Jord-Gui** [comment]
As per my conversation with @JackDevAU, prioritise the below to get an mvp out:
- See if I make any progress on the heading 1 - 6 support
- Support bullet list, numbered list, code block, quoting
- Support multiple lines within a table cell i.e. pressing enter

Once the above is working, double check with PO

Deprioritise the below
- Will probably need to support custom templates as well
- Table header
- Cell resizing

**Comment by Jord-Gui** [comment]
Cc: @Ben0189 

As per my conversation with @jeffsee55, @JackDevAU, [mdast](https://github.com/syntax-tree/mdast?tab=readme-ov-file#phrasingcontent) does not support having block elements within table cells. To support this, we would need to write our own parser, which requires much more effort. 

As suggested by Jeff, the easiest course of action now is to disable the unsupported cell formats when inside a table. We can ship this and then if it is needed, continue the conversation of a custom parser

**Comment by Jord-Gui** [comment]
As per my conversation with @wicksipedia, in the addition to the above task:
- [ ] Handle gracefully failing the ones that aren't supported (e.g. when a user edits the raw markdown)
- [ ] Update the documentation on what is supported/unsupported
- [ ] Create new PBIs and prioritise with PO for the ones we want to support custom

**Comment by Jord-Gui** [comment]
Cc: @JackDevAU 

After testing what happens when you use raw markdown to edit the table, the parser treats unsupported formats as a paragraph string and displays it literally. e.g. "1. Numbered list". 

As per my conversation with @wicksipedia, try and see if we can give a warning in the editor. Something along the lines of "you've put in an unsupported file". If it is a larger effort than expected, create a new PBI for it along with the others above.

**Comment by Jord-Gui** [comment]
Cc: @wicksipedia @JackDevAU 

As per my conversation with @adamcogan, once this has been released, record a Done Video.
- [ ] Record Done Video

**Comment by Jord-Gui** [comment]
Changes have been merged into main, just need to complete the above admin tasks before closing this off.

**Comment by Jord-Gui** [comment]
I have create a PBI to handle cleaning up of the old markdown table stuff: https://github.com/tinacms/tinacloud/issues/2340

**Comment by Jord-Gui** [comment]
> Cc: [@wicksipedia](https://github.com/wicksipedia) [@JackDevAU](https://github.com/JackDevAU)
> 
> As per my conversation with [@adamcogan](https://github.com/adamcogan), once this has been released:
> 
> * [x]  Record a Done Video
> 
> Remember to escalate this as per the rule [Do you escalate key updates and deliverables?](https://www.ssw.com.au/rules/escalate-key-updates/#:~:text=Not%20every%20PBI%20will%20require,Acceptance%20Criteria%20for%20the%20PBI.)

Done video v1 recorded and viewable here: https://youtu.be/TBXszAxiGnw
Email has also been sent out to the relevant stakeholders

**Comment by Jord-Gui** [comment]
> As per my conversation with [@wicksipedia](https://github.com/wicksipedia), in the addition to the above task:
> 
> * [x]  Handle gracefully failing the ones that aren't supported (e.g. when a user edits the raw markdown)[x]  Fix table html styling (specifically the columns)* [x]  Create new PBIs for the ones we may want to support custom:
>     
>     * [✨ Rich Text Editor - Table Plugin - Support multiple lines and "Enter" key press #5097](https://github.com/tinacms/tinacms/issues/5097)* [✨ Rich Text Editor - Table Plugin - Support saving block elements within table cells #5096](https://github.com/tinacms/tinacms/issues/5096)* [✨ Rich Text Editor - Table Plugin - Highlight unsupported table cell formats #4847](https://github.com/tinacms/tinacms/issues/4847)* [✨ Rich Text Editor - Table Plugin - Enhance table insertion #5171](https://github.com/tinacms/tinacms/issues/5171)[ ]  Update the [documentation](https://tina.io/docs/reference/types/rich-text/) on what is supported/unsupported.
Cc: @JackDevAU 
As per my conversation with @Ben0189, the only task remaining is the documentation update and then this PBI can be closed off

**Comment by ismaelrumzan** [comment]
Hey really excited about this as it's the main blocker for me using tina in some projects. Has this been merged to the latest version? I don't see the ability to include the table in the editor: https://tina.io/docs/reference/types/rich-text/
I saw in the video that you also had a mermaid plug-in. How do I add?

**Comment by ncn-ssw** [comment]
Still awaiting documentation.

**Comment by ncn-ssw** [comment]
> Hey really excited about this as it's the main blocker for me using tina in some projects. Has this been merged to the latest version? I don't see the ability to include the table in the editor: https://tina.io/docs/reference/types/rich-text/ I saw in the video that you also had a mermaid plug-in. How do I add?

Hi @ismaelrumzan,

Both features were merged in TinaCMS version 2.3.0.

**Comment by Ben0189** [comment]
As per conversation with @Jord-Gui , the documentation update is the only task left for this PBI to be closed.

✅ Documentation is [merged](https://github.com/tinacms/tina.io/pull/2322) and is now live on [Tina.io](https://tina.io/docs/reference/types/rich-text#unsupported-elements)

**Comment by Ben0189** [comment]
As per conversation with @ncn-ssw , the current v1 done video is done and waiting for @wicksipedia review

- [ ] Get approval from @wicksipedia for the done video

**Comment by ismaelrumzan** [comment]
Yes, thank you. I got it working but I can't really use until [this](https://github.com/tinacms/tinacms/issues/5096) is resolved

**Comment by ncn-ssw** [comment]
> Yes, thank you. I got it working but I can't really use until [this](https://github.com/tinacms/tinacms/issues/5096) is resolved

Hi @ismaelrumzan,

We've just deployed an update to TinaCloud. Could you please try it again?

**Comment by ismaelrumzan** [comment]
Hey @ncn-ssw I can confirm it's working! Thank you!
This is the repo: https://github.com/cordobadigitalmedia/tina-next-template
