### ISSUE TITLE
Tina using vulnerable version of @udecode/plate-media

### ISSUE THREAD

**Issue by jahabeebs** [tinacms/tinacms#4682]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

A high severity GitHub advisory was issued for @udecode/plate-media versions < 36.0.10 because of an XSS vulnerability

see details here: https://github.com/advisories/GHSA-h3pq-667x-r789

Tina is using @udecode/plate-headless version ^21.4.0 which seems to rely on the vulnerable version of @udecode/plate-media

```bash
jacob@192 od-docs % yarn why @udecode/plate-media
yarn why v1.22.22
[1/4] 🤔  Why do we have the module "@udecode/plate-media"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@udecode/plate-media@21.5.0"
info Reasons this module exists
   - "tinacms#@udecode#plate-headless" depends on it
   - Hoisted from "tinacms#@udecode#plate-headless#@udecode#plate-media"
   - Hoisted from "tinacms#@udecode#plate-headless#@udecode#plate-serializer-docx#@udecode#plate-media"
```

### Reproduction

https://github.com/open-dollar/od-docs

### Steps to reproduce

I added an example repo above that uses Tina CMS. You can do ```yarn why @udecode/plate-media``` to see the dependency graph

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M2
    Memory: 159.25 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.21 - ~/Documents/Programming/od-docs/node_modules/.bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Browsers:
    Chrome: 126.0.6478.185
    Edge: 126.0.2592.113
    Safari: 17.5
  npmPackages:
    @tinacms/cli: ^1.5.32 => 1.5.32 
    tinacms: 2.0.0 => 2.0.0
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [docs](https://tina.io/docs).
- [X] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by wicksipedia** [comment]
we are in the middle of updating to the latest plate [#4619](https://github.com/tinacms/tinacms/issues/4619) which should alieviate this issue
