### ISSUE TITLE
Impossible to upload a video in Tina Media manager

### ISSUE THREAD

**Issue by PothieuG** [tinacms/tinacms#4694]
Currently, it's impossible to upload a video in the Media Manager of Tina.

Workaround:
- Create manually a folder in where your media files are located (public folder)
- Copy/paste your video there
- After refreshing your Media Manager, the video should appears 

How to reproduce : https://youtu.be/cEDL4Z4DogY

![Image](https://github.com/user-attachments/assets/69fb5592-b275-4f27-8eaa-301705460aa9)
**Figure: the error while trying to upload a video via the Media Manager**

**Comment by Jord-Gui** [comment]
Hi @PothieuG, 

Can you please double check which version of tinacms and @tinacmis/cli you are on? We have just released an update to allow support for videos and other file types. 

If you update tinacms to [v2.1.0](https://github.com/tinacms/tinacms/pull/4675), this should be resolved.

For more details see #4657 and [our latest blog post](https://tina.io/blog/TinaCMS-Version-21/)
