### ISSUE TITLE
`toolbarOverride` does not change anything

### ISSUE THREAD

**Issue by biggujo** [tinacms/tinacms#4703]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I wanted to use the `toolbarOverride` feature, as it stated that it has been released according to:
- #4662;
- https://tina.io/blog/TinaCMS-Version-21;
- https://tina.io/docs/reference/types/rich-text/#toolbar-override.

But nothing changes if I add `toolbarOverride: ["heading","bold", "italic"],` to the `rich-text` field

<img width="320" src="https://github.com/user-attachments/assets/dd6e31fa-5c18-492b-920d-6d77c5dbdac6" alt="">

### Reproduction

https://github.com/biggujo/tina-toolbar-override

### Steps to reproduce

1. Scaffold the project with `npx create-tina-app@latest`.
3. Set version of `tinacms` package to `2.1.0`, as it stated in the blog.
4. Add `toolbarOverride: ["heading","bold", "italic"],` to `tina/collections/page.js` to the field of `rich-text`, so we would have something like this:
```js
/**
 * @type {import('tinacms').Collection}
 */
export default {
  label: "Page Content",
  name: "page",
  path: "content/page",
  format: "mdx",
  fields: [
    {
      name: "body",
      label: "Main Content",
      type: "rich-text",
      toolbarOverride: ["heading","bold", "italic"],
      isBody: true,
    },
  ],
  ui: {
    router: ({ document }) => {
      if (document._sys.filename === "home") {
        return `/`;
      }
      return undefined;
    },
  },
};

```

5. Run `npm install`.
6. Start the application with CMS with `npm run dev`.
7. Go to `http://localhost:3000/admin/index.html`.
8. Find out that the toolbar stays the same as the original one.

### System Info

  System:
    OS: macOS 13.5.2
    CPU: (8) arm64 Apple M1
    Memory: 152.03 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.12.2 - ~/.nvm/versions/node/v20.12.2/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - ~/.nvm/versions/node/v20.12.2/bin/npm
  Browsers:
    Chrome: 127.0.6533.89
    Safari: 16.6

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by JackDevAU** [comment]
Hey @biggujo, 

Try updating `@tinacms/cli` from  `^1.5.46` to `^1.5.52`. Though I'm not entirely sure why this isn't working for you 🤔
I just cloned the repo GitHub and (see image below) it seems to be working! 

![Image](https://github.com/user-attachments/assets/c5e4b613-d029-4fc6-b517-9b90de848cc1)
**Figure: Seems to be working** 

![Image](https://github.com/user-attachments/assets/157ad9a7-f8fa-4bf3-87d8-904ba2cc66a2)
**Figure: Note packages we can update to**
