### ISSUE TITLE
TinaCMS - Broken documents view in admin sidebar after 2.2.x Update

### ISSUE THREAD

**Issue by cod3blox** [tinacms/tinacms#4737]
Hello,
I am experiencing an issue with the visual editor after updating to Tina 2.2.0.

I have split my Tina data requests and am using multiple useTina() hooks on my Next.js site. When I enter visual editing mode, my sidebar usually appears like this:

![Image](https://github.com/user-attachments/assets/789a8bb8-9f44-48c6-bd89-a77f4b8876e0)

However, in Tina 2.2.0, this "document view" triggers errors. 
As soon as I try to access the visual edior with /admin#/~, it renders a blank site in browser.

This issue can also be reproduced with the latest tina-cloud-starter after updating to version 2.2.0. Clicking the "home" icon in the sidebar results in the same errors that I'm encountering  on my site.

### Reproduction

https://github.com/tinacms/tina-cloud-starter

### Steps to reproduce

1. Install latest tina cloud starter https://github.com/tinacms/tina-cloud-starter
2. Update dependecies to Tina 2.2.0 (tinacms: ^2.2.0, @tinacms/cli: ^1.6.0)
3. Start Tina in dev mode
4. Open http://localhost:3000/admin#/~/posts 
6. Click on the home icon in the visual editor sidebar

![Image](https://github.com/user-attachments/assets/ef174b8d-d72f-4e22-a3a8-ecd6d3e72d50)

![Image](https://github.com/user-attachments/assets/602db261-0605-4e65-82f8-3c111e351ce2)

### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (32) x64 AMD Ryzen Threadripper 1950X 16-Core Processor
    Memory: 18.19 GB / 31.89 GB
  Binaries:
    Node: 20.12.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.5.0 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.7.1 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.19041.4355
  npmPackages:
    @tinacms/cli: ^1.6.0 => 1.6.0
    tinacms: ^2.2.0 => 2.2.0

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by mddanish00** [comment]
Same. I also get the both of bugs.
- Go to Document View will trugger blank site.
- If not, clicking home icon will trigger blank site too.

For now, I am downgraded tinacms to the previous version.

**Comment by cod3blox** [comment]
Yes, updating to the latest version of Tina is not an option at the moment. Due to the bug, the admin section becomes inaccessible. The last working version is 2.1.0. I hope for a fix soon.

**Comment by guillermodlpa** [comment]
With the version 2.2.0, the issue started to happen to me intermittently when loading the /admin view. Not always. Seems like a race condition.  It seems `@headlessui/react` is updated in some of the repos of Tina, but not in all. Maybe that's how this bug has crept in.

**Comment by mddanish00** [comment]
Noticing today that a new version of tinacms released, I tried again updating to see if the bug was resolved but the bug still occured. Out of my curiosity, I tried only downgrade `@tinacms/cli` to `1.5.52` and...... It works. So, the bug happened because of `@tinacms/cli`.

Also, the previous commenter mentioned that the bug might happened because of the multiple version of `@headlessui/react`. So, I tried running `npm ls @headlessui/react`. 

This is the output before I downgraded.

```
├─┬ @tinacms/cli@1.6.5
│ └─┬ @tinacms/app@2.1.5
│   ├── @headlessui/react@2.1.8 deduped
│   └─┬ graphiql@3.0.0-alpha.1
│     └─┬ @graphiql/react@0.18.0
│       └── @headlessui/react@1.7.19
└─┬ tinacms@2.2.5
  └── @headlessui/react@2.1.8
```

After I downgraded.

```
├─┬ @tinacms/cli@1.5.52
│ ├─┬ @tinacms/app@2.0.2
│ │ ├── @headlessui/react@1.6.6
│ │ ├─┬ graphiql@3.0.0-alpha.1
│ │ │ └─┬ @graphiql/react@0.18.0
│ │ │   └── @headlessui/react@1.7.19 deduped
│ │ └─┬ tinacms@2.1.0
│ │   └── @headlessui/react@1.7.19
│ └─┬ tinacms@2.1.0
│   └── @headlessui/react@1.7.19
└─┬ tinacms@2.2.5
  └── @headlessui/react@2.1.8
```

**Comment by cod3blox** [comment]
@mddanish00 Thank you for trying it out! I was also considering updating and testing it myself. It's such a pitty – I'm still stuck on version 2.1.0 due to this issue, which has several high-rated vulnerabilities. Still after weeks and multiple TinaCMS releases, it's really disappointing that it feels like no one from the Tina team is addressing this.

**Comment by Ben0189** [comment]
There is a pr up for fixing this issue from Tina Team 😉 #4818 .

**Comment by cod3blox** [comment]
That's great news, looking forward to that. Thank you.

**Comment by JackDevAU** [comment]
Hey all, 

Good news the latest release of tinacms has fixed this issue! (Also now clicking the "home" icon takes you back to the collection folder page) 

Versions, 

`tinacms@2.2.6`
`@tinacms/cli@1.6.6`
