### ISSUE TITLE
Generalise api usage for other backends

### ISSUE THREAD

**Issue by swim** [tinacms/tinacms#475]
## Summary
Currently both gatsby-tinacms-json and gatsby-tinacms-remark rely on the git backend. However, other backends may implement a very similar interface and could benefit from these plugins. Similar to the get forms method on the CMS class an additional getter could be added which would return the active api. The active api would be initially set via gatsby-config; with a env variable. The process for registering new api's would be respected.

### Basic example
```
  plugins: [
    {
      resolve: "gatsby-plugin-tinacms",
      options: {
        api: {
          active: process.env.API
        },
        sidebar: {
          hidden: process.env.NODE_ENV === "production",
          position: "displace",
        },
```

```
  const {api} = options

  return (
    <Tina {...options.sidebar} cms={new TinaCMS(api)}>
      {element}
    </Tina>
  )
```

```
  get api() {
    const {active} = this.apiOptions

    return this.apis[active]
  }

  // Return active api
  cms.api
```

### Motivation

- Existing plugins to be reusable with new backends
- Define different backends per env / different backend settings per env
- Sets the stage for a common api interface

**Comment by ncphillips** [comment]
Thanks for the suggestion! This was actually the direction we took initially, however we quickly realized that it was not going to work out. Here's a few reasons why:

1. **There is no common interface (yet)** 
    Each backend works in a different way and is situated differently relative to the site. Creating a common interface would strip all backends of what makes them unique, making it difficult to create plugins/features that were backend specific. By not-creating a generalized API to which developers must adhere, developers are allowed the opportunity to create innovative solutions. 
1. **A generalized API exists, just not that level of API clients**
    The generalized API is the `Form` API in `@tinacms/core`. If you're working in React, then the `react-tinacms` package provides hooks to allow you to setup forms for new backends. The `Form` api is intentionally ignorant of any `backend` object–instead it just accepts an `onSubmit` function and exposes a `subscribe` method so you can watch the values updates.
1. **Tina supports multiple backends at once**
    TinaCMS currently let's you use and edit content from multiple backends. One could be for editing Markdown files stored in git, while another form lets you edit data stored in Contentful. The above api would limit the developer to only editing content from one backend at a time. 

As to the use-cases mentioned:

* **"Currently both gatsby-tinacms-json and gatsby-tinacms-remark rely on the git backend. However, other backends may implement a very similar interface and could benefit from these plugins"**
    There's definitely some confusing interactions between Gatsby and Tina. Those packages (`gatsby-tinacms-json` and `gatsby-tinacms-remark`) are Gatsby plugins, but not a TinaCMS plugins. They provide custom hooks for creating forms that edit data from json/markdown files found in Gatsby sites. There's nothing defined in these plugins that's reusable outside of those specific use cases. All of the actual behaviour is defined `useForm` in `react-tinacms`.
* **"Existing plugins to be reusable with new backends"**
    Currently, all (Tina) plugins will be usable with new backends. If a plugin is meant to be generalized then it shouldn't be interacting with a backend directly. Instead, the plugin should take the approach of `Form` and accept a function for performing an action, while being ignorant of the concept of a "backend".
* **"Define different backends per env"**
    I'm not sure this this is a use-case that I would want to support. You should not be using `git` in development and `contentful` in production. The other use-case makes sense to me, but...
* **"different backend settings per env'**
    Supporting this does not seem to require a generalized API. Configuration is entirely dependent on the backend; it is already possible to configure the git backend. The configuration options for a `wordpress` or `contentful` backend would be entirely different from each other or from `git`.

This could change as the codebase evolves, but I can't see what that would look like just yet.

**Comment by swim** [comment]
Thank you for such a detailed response. Do you in-vision the calls to cms.api.git in both `gatsby-tinacms-json` and `gatsby-tinacms-remark` will be moved / handled in useForm in the future or are those plugins specifically suited for the git backend?

**Comment by ncphillips** [comment]
I wouldn’t expect those calls to be moved to useForm... however! I could definitely see us adding a useGitForm hook to gatsby-tinacms-git that would abstract away the common behaviour, leaving only details about data fetching/validation (input) and serialization (output) in the json and remark packages

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by swim** [comment]
Super pleased with the intended direction, thank you for taking the time to answer my questions <3
