### ISSUE TITLE
Field description doesn't wrap

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#476]
## Description

When adding a description to a Tina field, it stays on one line and doesn't wrap as needed.

### Steps to reproduce

Add a long description to a field.

### Expected result

I'd expect the description to wrap if it's wider than the sidebar.

### Actual result

It stays on one line.

![image](https://user-images.githubusercontent.com/5075484/69080354-2c786c00-0a12-11ea-904e-9188deafd0b1.png)

### Environment

macOS 10.15.1, Chrome

**Comment by maciekgrzybek** [comment]
I'll take a look at this one.
