### ISSUE TITLE
🐛 BUG - Certain characters break the search in the reference field. e.g. /

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tinacms#4763]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I am trying to use the new search feature in the reference collection but it does not seem to work as i would expect.

If i type in content/docs it shows nothing
If i type in contentdocs it shows all items in the content/docs directory 
/a

https://github.com/user-attachments/assets/ddec0143-608c-46ef-92a3-7fb75476bcee

### Reproduction

n/a

### Steps to reproduce

see video 

### System Info

on current prod version of tina.io (tinacms v2.2.1) 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by Ben0189** [comment]
this error happen due to race condition when we release new experimental custom filter for reference field, here are a quick fix so the new release is backward compatible 😊

https://github.com/tinacms/tinacms/pull/4764

**Comment by Ben0189** [comment]
As per conversation with @JackDevAU , user want to search content in a specific folder ('/' is not working). We will have a look into the search function to see if there is a quick fix for this

**Comment by Ben0189** [comment]
✅Done fixes - https://github.com/tinacms/tinacms/pull/4782
