### ISSUE TITLE
Reference field not populating

### ISSUE THREAD

**Issue by savtrip** [tinacms/tinacms#4765]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi guys,

I upgraded to TinaCMS v2.2.2 and noticed the reference field broke. It still successfully links and recognised the reference within the CMS on previously linked posts but it fails to populate new ones.

Notes:
- I have not setup search functionality.
- I have not setup any customisations on the reference field.
- I solely upgraded from TinaCMS v1.5.29.

**Image of where it still links and redirects to authors successfully:**
![Image](https://github.com/user-attachments/assets/23213ea0-4b95-4512-83c4-6aa485b5b8c9)

**Fails to populate on a new list:**
![Image](https://github.com/user-attachments/assets/ff8986df-1b07-4754-b57e-bc9dd1f8c8fe)

**Here is the config for my author:**
![Image](https://github.com/user-attachments/assets/22538c31-529f-4a82-b4a3-8779c15dadd3)

**Here is the reference config:**
![Image](https://github.com/user-attachments/assets/b772c7af-f8f8-40e3-a881-3c9626d3a2c9)

**When I revert back to v1.5.29 it works again:**
![Image](https://github.com/user-attachments/assets/e04ae9ef-79ad-426b-a89f-0ce3c51043cd)

### Reproduction

N/A

### System Info

N/A

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by JackDevAU** [comment]
Hey @savtrip 

Thanks for reporting this issue, we have a fix but cannot deploy it at the moment due to some deployment issues. 
For now the best option is to downgrade to, 

- `tinacms: 2.2.1`
- `@tinacms/cli: 1.6.1`
