### ISSUE TITLE
🐛 Markdown editor - Hyperlinks should automatically be underlined

### ISSUE THREAD

**Issue by sethdaily** [tinacms/tinacms#4774]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When I add a hyperlink, it doesn't get underlined on the page (even though it does get underlined in the rich text editor).

![Image](https://github.com/user-attachments/assets/56df3f9f-6e58-4307-b0cd-9ef56793113f)
Figure: I would expect my link text to be automatically underlined on the page

### Reproduction

I was working on www.ssw.com.au/admin

### System Info

Windows, Edge

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by wicksipedia** [comment]
Sorry but this would be controlled by your site’s CSS implementation
