### ISSUE TITLE
H6 no longer an option in rich-text

### ISSUE THREAD

**Issue by raakvlakraakt** [tinacms/tinacms#4783]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

H6 no longer an option in rich-text after updating to Tina CMS 2. It goes till H5 and the previous h6 is shown as paragraph.

![Image](https://github.com/user-attachments/assets/a6fd819b-2f96-4992-b5da-9eea462c658a)

![Image](https://github.com/user-attachments/assets/8f97fddf-dfd8-4f8f-ab62-d81ccdca9519)

### Reproduction

npx create-tina-app@latest

### Steps to reproduce

Go to a rich-text field in the CMS. Click on some text and try to choose H6.

### System Info

System:
    OS: macOS 12.7.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
    Memory: 906.61 MB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 20.11.1 - ~/.nvm/versions/node/v20.11.1/bin/node
    npm: 10.2.4 - ~/.nvm/versions/node/v20.11.1/bin/npm
  Browsers:
    Brave Browser: 128.1.69.162
  npmPackages:
    @tinacms/cli: ^1.6.3 => 1.6.3 
    tinacms: ^2.2.3 => 2.2.3 

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by wicksipedia** [comment]
✅ Done - added support for `h6` in tinacms@2.2.5

![CleanShot 2024-09-24 at 12 43 19](https://github.com/user-attachments/assets/adcb19a1-7a00-4d32-94af-50f319373480)
