### ISSUE TITLE
Legacy octal escape sequences

### ISSUE THREAD

**Issue by TuinboonDev** [tinacms/tinacms#4787]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hello, I just setup the tina-cloud-start and converted it to be self hosted but every time I try to build with `pnpm build` I get the error 

```js
Error: Transform failed with 1 error:
<stdin>:3:134: ERROR: Legacy octal escape sequences cannot be used in an ECMAScript module
    at failureErrorWithLog (D:\Downloads\tina-cloud-starter-main\tina-cloud-starter-main\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:1649:15)
    at D:\Downloads\tina-cloud-starter-main\tina-cloud-starter-main\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:847:29
    at responseCallbacks.<computed> (D:\Downloads\tina-cloud-starter-main\tina-cloud-starter-main\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (D:\Downloads\tina-cloud-starter-main\tina-cloud-starter-main\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:762:9)
    at Socket.readFromStdout (D:\Downloads\tina-cloud-starter-main\tina-cloud-starter-main\node_modules\.pnpm\esbuild@0.18.20\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: [Object],
      notes: [Array],
      pluginName: '',
      text: 'Legacy octal escape sequences cannot be used in an ECMAScript module'
    }
  ],
  warnings: []
}
 ELIFECYCLE  Command failed with exit code 1.
```

 
  Its editing the `client.d.ts` file in `/tina/__generated__/` to this line: `export const client = createClient({ cacheDir: 'D:\Downloads\tina-cloud-starter-main\tina-cloud-starter-main\tina\__generated__\.cache\1726068197534', url: '/api/tina/gql', token: 'undefined', queries,  });` Which has an escape sequence at the "\1726..."
 

### Reproduction

https://github.com/TuinboonDev/tina-legacy-escape-bug

### Steps to reproduce

1. Git clone or download and unzip the tina-self-hosted-demo
2. install dependencies
3. use `yarn tinacms init backend` and configure it to be self hosted
- next.js
- mongodb
3.5. remove "TINA_PUBLIC_IS_LOCAL=false" or "TINA_PUBLIC_IS_LOCAL=true" in package.json scripts
3.75. remove the double '[...routes].js' file in the pages directory
4. run `yarn dev` and then `yarn build`

### System Info

  System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Memory: 2.12 GB / 15.88 GB
  Binaries:
    Node: 20.17.0 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.3 - D:\Program Files\nodejs\npm.CMD
    pnpm: 9.10.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.86)
    Internet Explorer: 11.0.19041.1566

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by TuinboonDev** [comment]
#4779

**Comment by kldavis4** [comment]
I believe this is already fixed: https://github.com/tinacms/tinacms/pull/4785

**Comment by wicksipedia** [comment]
Hey @TuinboonDev 
I raised a PR against your repo - https://github.com/TuinboonDev/tina-legacy-escape-bug/pull/9

I noticed that there were 2 database files (ts + js) - 1 was using redis, the other mongo which would also prevent the `build` command from working.

Rebuilding the lock file pulled in a newer version of TinaCMS which tested ok on my VM.

Closing this issue, let us know if you have any other problems
