### ISSUE TITLE
Groups/Group Lists/Blocks are broken inside Global Forms

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#479]
## Description

The way groups/group lists/blocks are displayed only works when they're displayed in a regular form. When you open one inside a global form, it gets rendered in the sidebar instead of inside the global form.

### Steps to reproduce

Add a global form that contains a group, or use `useGlobalJsonForm` on an existing json form that contains a group.

### Expected result

I'd expect the panel to open inside the modal.

### Actual result

What happened.
![image](https://user-images.githubusercontent.com/5075484/69080991-6c8c1e80-0a13-11ea-808c-596848b84c31.png)

**Comment by timonweber** [comment]
I’ve just experienced this myself. It would be great if someone can fix it!

**Comment by ncphillips** [comment]
A fix is coming soon @timonweber. @spbyrne is doing a bit of work that will make a fix possible.

**Comment by spbyrne** [comment]
My previous attempt at fixing this used refs to measure the appropriate spot to render the panel. It ended up being overly complicated and prone to failure.

Nolan has set up a form portal that can be used to move any sub component up to the root form level, which will make this a lot easier. I'm currently working on this and should have it ready today.
