### ISSUE TITLE
🚸 TinaCMS | rich text editor - Obscured Toolbar Items in CMS Window

### ISSUE THREAD

**Issue by isaaclombardssw** [tinacms/tinacms#4795]
### Pain

It may appear Tina is missing a few rich-text options (e.g. the embed) as they can be obscured in the thin TinaCMS editor, and the toolbar isn't possible to scroll on.

My late afternoon brain came to the conclusion that those options just didn't exist for a page I was editing. 

I also reckon I'm not the first victim of this one. This is on Firefox / Mac.

I think we could improve the UX.

Additionally, to note, if you click on a half-obscured toolbar item the hidden items will be opened in a floating menu (but nothing in the UI really indicates this).

### Screenshots

![2024-09-12_09-10-14](https://github.com/user-attachments/assets/6eee2fb2-7292-469f-af46-30a57572a6d8)
**Figure 1 – missing toolbar items??**

![2024-09-12_09-09-44](https://github.com/user-attachments/assets/13745670-ba19-4f05-95e1-42d0125fe016)
**Figure 2 – revealed on a wider screen size**

![Screenshot 2024-09-12 at 12 54 39 pm](https://github.com/user-attachments/assets/d95ee15c-4d8f-4de7-9c39-60fac3e1f981)
**Figure 3 – clicking a half-obscured toolbar item to reveal the hidden toolbar items**

### Steps to reproduce

Open a CMS instance where a rich-text field is being edited.

Resize the subwindow.

### System Info

System:
    OS: macOS 13.6.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Memory: 60.18 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
Binaries:
    Node: 20.16.0 - ~/.nvm/versions/node/v20.16.0/bin/node
    Yarn: 1.22.22 - /usr/local/bin/yarn
    npm: 10.8.1 - ~/.nvm/versions/node/v20.16.0/bin/npm
    pnpm: 9.6.0 - /usr/local/bin/pnpm
Browsers:
    Safari: 16.6

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeoffreyfischer** [comment]
@wicksipedia @JackDevAU 
We are facing the same issue on the SSW website: the access to more rich text options is unclear

**Screenshot**
![Image](https://github.com/user-attachments/assets/76e19067-c2d3-438f-b196-315fe64bd2a1)
**Figure: More rich text options are hidden**

**Comment by wicksipedia** [comment]
Hey all, just tested this in tinacms@2.2.5 and wasn't able to reproduce the issue (even tried Firefox on MacOS).

Can you install the latest version and retry please.

![Image](https://github.com/user-attachments/assets/047ca587-8daa-41e8-bb9c-bdf63792af9a)

**Comment by isaaclombardssw** [comment]
I've just updated to 2.2.5 and am encountering the same problem – looks like it works great with the vertical ellipses but I wonder why they're not showing up for me 🤔 

Could it be that something else in the SSW website / tina.io is interfering with it?

![Image](https://github.com/user-attachments/assets/0602cb95-04e5-4fba-8d9c-24fd1bea8ee2)

**Comment by Ben0189** [comment]
✅ Done 

PR - https://github.com/tinacms/tinacms/pull/5004
