### ISSUE TITLE
Docs - Document supported environment

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tinacms#4796]
Right now we only support NodeJS v21 and lower.

We have had some users get confused about this, so we should document it somewhere.

- [x] Add a new page to https://tina.io/docs
- [x] CLI - Add a link to the supported environments doc

**Comment by brookjeynes-ssw** [comment]
>  Add a new page to https://tina.io/docs

Done - https://github.com/tinacms/tina.io/pull/2241

>  CLI - Add a link to the supported environments doc

In review - https://github.com/tinacms/tinacms/pull/4820

**Comment by brookjeynes-ssw** [comment]
Done -
- Node versions have been documented on tina.io
- The `create-tina-app` CLI tool will now warn the user if they're not using a supported version.
