### ISSUE TITLE
Markdown Editing: inline code links, backticks wrap entire link on save

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#480]
## Description

If you edit any links that are inline code, on save or when you 'close' the inline editing mode, the links will get saved in the document with the back ticks wrapping the entire link item. This makes the whole text show up and disables the link. See the changes below. 

<img width="986" alt="Screen Shot 2019-11-18 at 9 05 10 AM" src="https://user-images.githubusercontent.com/36613477/69081501-f5df2900-09f2-11ea-9715-11bd691d1771.png">

### Steps to reproduce

Go the gatsby demo, or the docs site. Open up the inline editing mode. Add a link that is an inline code block. Close and open editing mode or make changes to the link and then watch the source file. 

### Expected result

The backticks remain wrapping the link text.

### Actual result

The backticks move to wrap the entire markdown link. 

### Environment
 
Specifically on docs site @tinacms 0.5.0

**Comment by ncphillips** [comment]
I experienced this recently. We should be able to get some failing test cases added. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by dwalkr** [comment]
FYI I'm pretty sure this happens in the Forestry WYSIWYG too
