### ISSUE TITLE
✨ TinaCMS | config - ability to set filename settings

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tinacms#4800]
cc: @isaaclombardssw @bradystroud 
**🩸 Pain**

We've run into an issue on Tina.io where users did not realise that the filename field on a blog post (collection) was creating the slug indirectly through the title field (the title field had `isTitle: true`). This saw them enter really long titles and therefore the slugs were really long and ugly ☹️ 

Our current work-around was just to remove the isTitle boolean, making the filename field required so users would have to come across it purposely

**🎯 Expected Solution**

To have more flexibility with the filename input. Allowing us to modify the default description of the filename input to add warnings to users that this will determine the slug and it cannot be changed. We also would love to see the option to have the filename field at the top of the page as its quite important and it can get lost in a schema very easily

**Tasks**
- ~~[ ] Improve default description of filename field -> i.e warning users that the filename = slug, that it cant be changed etc~~
- [x] Ability to move the filename field to the top of the schema 
- [x] Ability to customise the filename description

**Comment by Remzi1993** [comment]
In my opinion file names and authors should be renamable, but Tina doesn't offer this functionality, see #4374

**Comment by wicksipedia** [comment]
>  i.e warning users that the filename = slug, that it cant be changed etc

This is specific to how the router is wired up in a site's config - not for all sites. Ideally there should be a `slug` field that separates the id from the content

**Comment by wicksipedia** [comment]
✅ Done - this will be released in the next version of TinaCMS

See how it will work - https://youtu.be/MTshbbBwrHw
