### ISSUE TITLE
TinaCMS | Rich text editor - embed drop down list with lots of templates can render off screen + does not scroll

### ISSUE THREAD

**Issue by Erik2609** [tinacms/tinacms#4809]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

We're using a lot of templates in our rich-text fields, which cause them to render outside of the clickable options. You cant scroll or zoom out while the dropdown is open.
![Image](https://github.com/user-attachments/assets/5efe8656-0336-4ce3-9fe1-57917f4fbc55)

### Reproduction

https://github.com/NGO-Algorithm-Audit/

### Steps to reproduce

Create a rich-text field with a lot of templates.
Open the CMS and open the Embed function.

### System Info

  System:
    OS: Windows 11 10.0.22631
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900HX
    Memory: 46.02 GB / 63.74 GB
  Binaries:
    Node: 20.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.98)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @tinacms/cli: ^1.5.47 => 1.6.1
    tinacms: ^1.6.5 => 1.6.5

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by jeoffreyfischer** [comment]
@wicksipedia @JackDevAU 
We are facing the same issue on the SSW website: when adding an Embed, the list is limited and it's impossible to scroll down in it.

**Screenshot**
![Image](https://github.com/user-attachments/assets/eb886b73-d7f2-4741-afc8-7049c2672548)
**Figure: Can't scroll down in the list of templates**

**Comment by wicksipedia** [comment]
This will be fixed in tinacms@2.2.6 - adding scrolling support and filtering

![Image](https://github.com/user-attachments/assets/41f52ac8-2b7e-4970-bbd5-8aea56c44cfe)
