### ISSUE TITLE
Media Manager Exposing Full Path to Public Folder

### ISSUE THREAD

**Issue by savtrip** [tinacms/tinacms#4817]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Hi tinacms team,

I recently updated to TinaCMS version 2.2.5 and I noticed my media store now exposes the full path of my public folder, as per my screenshot below.

![Image](https://github.com/user-attachments/assets/21054a96-3fb6-424b-b873-eb2cee361e0b)

My TinaCMS config is as so:

```
  media: {
    tina: {
      mediaRoot: "uploads",
      publicFolder: "static",
    },
    accept: ['image/webp']
  }
```

My directory structure for uploaded assets is as so:
```
./static/uploads/
```

When I upload an image it still adds to the mediaRoot folder but for some reason the user now sees the full exposed path, which confuses the content editor of the website. Anyone else run into this issue with the latest version of Tina?

I even deleted my entire TinaCMS Cloud project and re-added it. The problem still persists.

### Reproduction

N/A

### Steps to reproduce

My tinacms config and directory structure.

### System Info

N/A

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by rhysjroberts** [comment]
I'm having the same issue (tinacms 2.2.4, and tinacms/cli 1.6.8).

The 'src' of images inserted using TinaCMS Cloud are having '/public' added in front, which is then resulting in broken images.

Can also confirm this doesn't occur locally.

If anyone has a fix, that would be great!

**Comment by rhysjroberts** [comment]
@savtrip I've only been back to 2.2.0, but the issue was still present. Can't roll back any further as it'll cause further issues, and I'm still in dev mode, so I can afford to wait for a fix before going into prod.

**Comment by ncn-ssw** [comment]
@savtrip, @rhysjroberts

We have just deployed a fix by @kldavis4 to TinaCloud.

If you resync your media, your media will be placed in the correct locations.

![Image](https://github.com/user-attachments/assets/6639a2d1-d87b-4245-ae5e-6d718a9b86bc)
**Figure: Location of the "Resync Media" button within a Project on the Media tab**

**Comment by ncn-ssw** [comment]
Hi @savtrip,

Maintaining the original files is intentional.

We believe some people would have 'worked around' the issue by updating their paths, and didn't want a "Resync Media" operation to break their setups.

A folder can be deleted by deleting all of its contents. We're aware the UX around deleting folders needs improvement.

**Comment by rhysjroberts** [comment]
> [@ncn-ssw](https://github.com/ncn-ssw) awesome, thank you guys for the quick fix, on resync the files appeared again.
> 
> However, it seems TinaCloud continues to hold a cache of the original problem, as per my original screenshot, the `./static` folder remains within the interface. Is there a way to purge the cache of the TinaCloud as a user other than the `Resync Media` button?
> 
> I resolved the issue by deleting my repository from TinaCloud and adding the repo back again, obviously that is a laborious way to purge the cache but it fixed the problem for me.
> 
> [@rhysjroberts](https://github.com/rhysjroberts) did you have the same problem as me?

@savtrip I did, yes. I've deleted the folder as suggested by @ncn-ssw, and the issue seems resolved.
