### ISSUE TITLE
Test gatsby-transformer-remark versions compatibility

### ISSUE THREAD

**Issue by maciekgrzybek** [tinacms/tinacms#484]
As mentioned in this [PR](https://github.com/tinacms/tinacms/pull/483), we need to test out different versions of the `gatsby-transformer-remark` plugin.
The plugin is a peerDependency of the `gatsby-tinacms-remark` plugin. Currently, the required version is `>=2.6`, but we need to make test and make sure which versions could be used as well.

**Comment by andrew-t-james** [comment]
If this is still open I would like to work on this issue.

**Comment by DirtyF** [comment]
@andrew-t-james Please do 🙏

**Comment by andrew-t-james** [comment]
@DirtyF Can you give a little more clarification for this issue, are you wanting tests that swap out the version of `gatsby-transformer-remark` and I am guessing you are wanting test coverage for this package?

**Comment by ncphillips** [comment]
This issue isn't really about increasing test coverage, but feel free to do so if you wish.

I suspect `gatsby-tinacms-remark` works with pretty much every version of `gatsby-transformer-remark`.

It's really just about making sure the `gatsby-node.js` file still works with other versions. You can check by installing older versions of the transformer and manually confirming that it works with the `rawFrontmatter` and `fileRelativePath` properties are on the `Markdown` nodes.

There's three vectors of failure for older versions

1. The [`internal.owner`](https://github.com/tinacms/tinacms/blob/master/packages/gatsby-tinacms-remark/gatsby-node.js#L24) might not be set 
2. The [`fileAbsolutePath`](https://github.com/tinacms/tinacms/blob/master/packages/gatsby-tinacms-remark/gatsby-node.js#L47) may not be created in the same way
3. The package might require an older version of Gatsby that tinacms does not support

**Comment by andrew-t-james** [comment]
@ncphillips Thanks for the information. Much appreciated.

**Comment by andrew-t-james** [comment]
@ncphillips I pulled the gatsby tinacms stater and verified that from version `1.0.0` up until version `2.1.1-alpha.2` the project will not run/build. That was the first version of the gatsby starter that would run. The majority of the errors I hit when trying to start the project are below. If my mind serves me well that is most likely a GraphQL error but I didn't get the chance to verify.

```
UNHANDLED REJECTION Schema must contain uniquely named types but contains multiple types named "JSON".
  Error: Schema must contain uniquely named types but contains multiple types named "JSON".
  - Array.reduce
  - Array.reduce
```
## System Info
```
  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 70.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.15.36 => 2.18.1 
    gatsby-image: ^2.2.27 => 2.2.33 
    gatsby-plugin-feed: ^2.3.16 => 2.3.21 
    gatsby-plugin-google-analytics: ^2.1.21 => 2.1.28 
    gatsby-plugin-manifest: ^2.2.21 => 2.2.29 
    gatsby-plugin-offline: ^3.0.14 => 3.0.22 
    gatsby-plugin-react-helmet: ^3.1.11 => 3.1.15 
    gatsby-plugin-sharp: ^2.2.29 => 2.3.2 
    gatsby-plugin-tinacms: ^0.1.16 => 0.1.17 
    gatsby-plugin-typography: ^2.3.12 => 2.3.17 
    gatsby-remark-copy-linked-files: ^2.1.26 => 2.1.30 
    gatsby-remark-images: ^3.1.26 => 3.1.32 
    gatsby-remark-prismjs: ^3.3.18 => 3.3.24 
    gatsby-remark-responsive-iframe: ^2.2.23 => 2.2.27 
    gatsby-remark-smartypants: ^2.1.12 => 2.1.16 
    gatsby-source-filesystem: ^2.1.31 => 2.1.38 
    gatsby-tinacms-git: ^0.2.14 => 0.2.15 
    gatsby-tinacms-json: ^0.8.0 => 0.8.1 
    gatsby-tinacms-remark: ^0.6.0 => 0.6.1 
    gatsby-transformer-json: ^2.2.20 => 2.2.22 
    gatsby-transformer-remark: 2.1.1-alpha.2 => 2.1.1-alpha.2 
    gatsby-transformer-sharp: ^2.2.23 => 2.3.9 
  npmGlobalPackages:
    gatsby-cli: 2.8.22

```

**Comment by ncphillips** [comment]
Awesome @andrew-t-james! I would think that means the version listed in the `gatsby-tinacms-remark` package.json wouldbe:

```json
{
  "peerDependencies": {
    "gatsby-transformer-remark": ">=0.2.1"
  }
}
```
