### ISSUE TITLE
Visual toggle indicator broken

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#489]
## Description

When using the toggle field, the values change as expected, but the visual indicator isn't shifting. 

### Steps to reproduce

Clone Tina Grande. Checkout Theme > Typography > try to toggle that h2.

### Expected result

The visual toggle would switch.

### Actual result

No visual indicator that the value has toggled.

### Environment

"gatsby-plugin-tinacms": "^0.1.14-alpha.1",
"gatsby-tinacms-git": "^0.2.12-alpha.1",
 "gatsby-tinacms-json": "^0.7.0-alpha.2",
 "gatsby-tinacms-remark": "^0.5.0-alpha.1",

**Comment by maciekgrzybek** [comment]
Can I give it a go?🚀

**Comment by DirtyF** [comment]
@maciekgrzybek You shouldn't have to ask for permission :)

**Comment by maciekgrzybek** [comment]
:) Ok, just always want to make sure that no one is already working on it :)

**Comment by DirtyF** [comment]
Let's make it a rule of thumb:  if there is no assignee, no open PR, no `has-pull-request`label on the issue, or request like yours  in a comment, then feel free to work on an issue.

**Comment by maciekgrzybek** [comment]
Sounds good :)

**Comment by spbyrne** [comment]
Hey @maciekgrzybek, @ncphillips managed to fix this issue [here](https://github.com/tinacms/tinacms/commit/a9d36c90cd05b9dd9febf673abbcbc4cd15acdd8). It was a final-form issue. We wanted to publish this morning without introducing this issue into the release, hence the patch.

Thanks 😄
