### ISSUE TITLE
Relative Paths not working for some files on Windows 10

### ISSUE THREAD

**Issue by SceptreData** [tinacms/tinacms#491]
## Description

I'm trying to get the [Grande TinaCMS starter](https://github.com/tinacms/tina-starter-grande) running on my windows 10 machine. It seems to build properly, but when I visit my site on local host I am presented with [Type Error, cannot read property 'title' of null.](https://i.imgur.com/mG1NY3G.jpg). After doing a bit of digging, It looks like gatsby is not correctly assigning a relative path to the site.json file. When I query the file through GraphQL fileRelativePath returns an absolute path.

 I noticed that the file in question, (site.json) has included a special field for gatsby "__gatsby_resolved", which (i'm guessing) is trying to manually set the fileRelativePath. I tried searching for it, but I couldn't find any information or reference to how it was used in Gatsby. Some quick perusing through the gatsby source code told me that it has something to do with Node creation.

Is it possible this isn't doing what it's supposed to on my Windows system?

### Steps to reproduce

1. git clone tina-starter-grande
2. gatsby develop

That's it, I haven't made any changes to the repo.

### Expected result

Gatsby should correctly source the site.json file, and the page will load.

### Actual result

[Type Error, cannot read property 'title' of null.](https://i.imgur.com/mG1NY3G.jpg).

### Environment

Windows 10 Version 1903
OS Build 18362.476
Yarn 1.16

In addition to the default packages included with [tina-starter-grande](https://github.com/tinacms/tina-starter-grande).

**Comment by ncphillips** [comment]
I suspect this is related to PR #383  

@all-contributors please add @SceptreData for bugs

**Comment by spbyrne** [comment]
I've created a draft PR that may fix the issue, but it's untested. PR #493. I'm getting a windows system setup now to test it out.
