### ISSUE TITLE
Unable to npm install gatsby-tinacms-remark

### ISSUE THREAD

**Issue by pcast01** [tinacms/tinacms#509]
## Description

When I try to npm install gatsby-tinacms-remark I get this error.
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tinacms%2freact-core -
Not found
npm ERR! 404
npm ERR! 404  '@tinacms/react-core@^0.2.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)npm ERR! 404 It was specified as a dependency of '@tinacms/form-builder'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

### Steps to reproduce

I have a gatsby blog that I am just trying out tina-cms and I was following the instructions on the site here: https://tinacms.org/docs/gatsby/markdown.

### Expected result

gatsby-tinacms-remark should install

### Actual result

Error is thrown from NPM.

### Environment

| Tool    | Version |
| ------- | ------- |
| browser | Chrome         |
| os      |  Windows 10      |
| node    |   10.8.0      |
| npm     |   6.9.0      |
| tinacms |    0.1.15     |

**Comment by ncphillips** [comment]
WOops! Thanks I'll fix this

**Comment by ncphillips** [comment]
Can you try again @pcast01 ?

**Comment by pcast01** [comment]
Yeah it works now. Thanks for the quick reply!

**Comment by ncphillips** [comment]
😅 thanks for the report!

@all-contributors please add @pcast01 for bugs

**Comment by ncphillips** [comment]
@all-contributors-bot please add @pcast01 for bugs
