### ISSUE TITLE
Unable to use the TinaRemark in markdownRemark inside of GraphQL query

### ISSUE THREAD

**Issue by pcast01** [tinacms/tinacms#512]
## Description

Unable to use the TinaRemark in markdownRemark inside of GraphQL query

### Steps to reproduce
When I am creating pages I use the blog-post.js template which uses the query below, it throws an error stating that "UNHANDLED REJECTION GraphQLCompilerContext: Unknown document `TinaRemark`." Not sure if this is a bug or not.

With this graphQl query:
```
export const query = graphql`
  query($slug: String!) {
    site {
      siteMetadata {
        url
        title
        labels {
          tag
          tech
          name
          size
          color
        }
      }
    }
    myContent: markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      html
      frontmatter {
        title
        date(formatString: "MMMM DD, YYYY")
        tags
      }
      fileRelativePath
      rawFrontmatter
      rawMarkdownBody
      ...TinaRemark
    }
  }
`
```
### Expected result

The site will not run. Now I took out "...TinaRemark" and the site will run. The fields inside markdownRemark kept throwing errors because the required fields were not there.(id,fileRelativePath, rawFrontmatter, rawMarkdownBody). Once added all the required fields then this error was shown. "useCMS could not find an instance of CMS"

### Actual result

On extract queries step in gatsby develop an error is thrown. UNHANDLED REJECTION GraphQLCompilerContext: Unknown document `TinaRemark`.

### Environment

| Tool    | Version |
| ------- | ------- |
| browser |   Chrome      |
| os      |   Windows 10      |
| node    |   10.8.0      |
| npm     |   6.9.0      |
| tinacms |   0.1.15      |

**Comment by pcast01** [comment]
Here is my blog-post.js template code.

import React from "react"
import { graphql } from "gatsby"
import { remarkForm } from "gatsby-tinacms-remark"
import Layout from "../components/layout"
import SEO from "../components/seo"
import "./blog-post.css"

import Sidebar from "../components/sidebar/Sidebar"
import TechTag from "../components/tags/TechTag"
import CustomShareBlock from "../components/CustomShareBlock"

function BlogPostTemplate(props) {
  const post = props.data.markdownRemark
  const labels = props.data.site.siteMetadata.labels
  const siteName = props.data.site.siteMetadata.title
  const siteUrl = props.data.site.siteMetadata.url
  const url = `${siteUrl}${props.pageContext.slug}`
  const tags = post.frontmatter.tags

  const getTechTags = tags => {
    const techTags = []
    tags.forEach((tag, i) => {
      labels.forEach(label => {
        if (tag === label.tag) {
          techTags.push(
            <TechTag
              key={i}
              tag={label.tag}
              tech={label.tech}
              name={label.name}
              size={label.size}
              color={label.color}
            />
          )
        }
      })
    })
    return techTags
  }

  return (
    <Layout>
      <SEO title={post.frontmatter.title} />
      <div className="post-page-main">
        <div className="sidebar px-4 py-2">
          <Sidebar />
        </div>

        <div className="post-main">
          <SEO title={post.frontmatter.title} />
          <div className="mt-3">
            <h2 className="heading">{post.frontmatter.title}</h2>
            <div className="d-block">{getTechTags(tags)}</div>
            <br />
            <small>
              <i>Published on </i> {post.frontmatter.date}
            </small>
            <div dangerouslySetInnerHTML={{ __html: post.html }} />
            <CustomShareBlock
              title={post.frontmatter.title}
              siteName={siteName}
              url={url}
            />
          </div>
        </div>
      </div>
    </Layout>
  )
}

export const query = graphql`
  query($slug: String!) {
    site {
      siteMetadata {
        url
        title
        labels {
          tag
          tech
          name
          size
          color
        }
      }
    }
    myContent: markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      html
      frontmatter {
        title
        date(formatString: "MMMM DD, YYYY")
        tags
      }
      fileRelativePath
      rawFrontmatter
      rawMarkdownBody
      ...TinaRemark
    }
  }
`

export default remarkForm(BlogPostTemplate, { queryName: "myContent" })

**Comment by ncphillips** [comment]
Could you check if `gatsby-tinacms-remark` is in your `gatsby-config.json`? That's the package that defines that GraphQL Fragment.

Also could you run this command in the terminal and post the output here:

```bash
npm ls | grep tinacms | grep -v deduped
```

**Comment by pcast01** [comment]
Yes it is.

```
 {
      resolve: "gatsby-plugin-tinacms",
      options: {
        plugins: ["gatsby-tinacms-git", "gatsby-tinacms-remark"],
      },
    },
```

Here is my output. Looks like I have an old versions of gatsby-transformer-remark?

```
npm ERR! peer dep missing: emotion@^9.2.4, required by react-custom-share@0.4.8
npm ERR! peer dep missing: gatsby-transformer-remark@>=2.6, required by gatsby-tinacms-remark@0.6.0
npm ERR! peer dep missing: react@^16.9.0, required by @mdx-js/react@1.3.1
npm ERR! peer dep missing: jquery@1.9.1 - 3, required by bootstrap@4.3.1
npm ERR! peer dep missing: react@^16.9.0, required by @mdx-js/react@1.3.1
npm ERR! peer dep missing: typescript@*, required by ts-pnp@1.1.2
npm ERR! peer dep missing: typescript@>=3.5.0, required by ts-essentials@3.0.5
+-- gatsby-plugin-tinacms@0.1.15
| +-- @tinacms/core@0.5.0
| +-- react-tinacms@0.9.1
| `-- tinacms@0.9.1
|   +-- @tinacms/fields@0.1.15
|   +-- @tinacms/form-builder@0.2.7
|   +-- @tinacms/icons@0.3.9
|   +-- @tinacms/styles@0.1.0
+-- gatsby-tinacms-git@0.2.14
| +-- @tinacms/api-git@0.4.6
| +-- @tinacms/git-client@0.4.1
| +-- gatsby-plugin-tinacms@0.1.16
| `-- tinacms@0.10.0
|   +-- @tinacms/fields@0.1.16
|   +-- @tinacms/form-builder@0.2.8
|   +-- @tinacms/react-core@0.2.0
+-- gatsby-tinacms-remark@0.6.0
| +-- @tinacms/form-builder@0.2.8
| `-- tinacms@0.10.0
|   +-- @tinacms/fields@0.1.16
```

**Comment by ncphillips** [comment]
gatsby-plugin-tinacms has been upgraded. It should now be 0.1.16

I think updating will fix your issue. That’s frustrating though I’m going to look into improving the dependency versions to prevent these kinds of issues in the future

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pcast01** [comment]
I will check and see if this fixes it. I am running into errors with sharp currently. I'll update you when I get past that.

**Comment by pcast01** [comment]
Ok, that did fix it! The blog posts show up now.
