### ISSUE TITLE
[feature] Elm `elm-pages` support

### ISSUE THREAD

**Issue by heyakyra** [tinacms/tinacms#515]
## Summary

[Elm](https://elm-lang.org/) is a purely functional language for building ridiculously stable and fast web applications (compiles to JavaScript), and [`elm-pages`](https://github.com/dillonkearns/elm-pages) is a type-centric static site generator built on `elm`. Some of the project’s goals are:

-  Make SEO (and nice Slack/Twitter/Discourse previews like you see above) dead simple!
-  Let you use nice Elm types to set up your SEO and render your pages
-  Pure Elm configuration
-  Generate a performant single-page app from your markup

### Motivation

I'm looking for:

1. Git-backed static site management, editable by non-developers
2. Free Software (as in open source) either web based or cross platform
3. Zero cost hosting and editing without capping team members
4. Editable from page itself, or at least no server required for editing
5. Elm compatibility!

Most have heard of Netlify but that really only does 1 & 2. If you want 3 and 4 you have to host your own identity server or some such, if I understand correctly. 

Then there's https://github.com/GetPublii/Publii which does 1-4 (but only editing from a desktop app, not directly from the page itself on the web)

Finally, only TinaCMS is the that hits 1-4 in the most ideal way, but only misses #5! I know I would love to be able to use this with `elm` projects, and I'm sure many others would too.

**Comment by surjithctly** [comment]
@heyakyra Does this feature support Eleventy once its implemented?

**Comment by DirtyF** [comment]
@surjithctly No, [Elm](https://elm-lang.org/) is a functional language and has nothing to do with Eleventy. Tina currently only support React-based websites. If you can run React with Eleventy, then Tina should work. We recommend NextJS though.
