### ISSUE TITLE
Clicking home icon in Visual editing mode breaks the Tina UI

### ISSUE THREAD

**Issue by cre8ive-gds** [tinacms/tinacms#5173]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

When authoring content using the visual editor, I click on the home icon in breadcrumbs, expect the app to load and redirect the user to the home page, instead it breaks.
Attaching a demo GIF.

![Image](https://github.com/user-attachments/assets/57c2659c-fe01-4bbf-8bdf-a543f7e9234c)

### Reproduction

N/A

### Steps to reproduce

1. Use astro starter project.
2. Integrate with Tina CMS using Tina cloud, and add some collections to the schema.
3. Enable visual editing.
4. When authoring via visual editor, click on the home icon.

### System Info

N/A

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by JackDevAU** [comment]
Hi @cre8ive-gds 

What version of `tinacms` & `@tinacms/cli` are you using? 
This issue got fixed with a recent release. I recommend updating to the **latest** versions for the above mentioned packages.

**Comment by cre8ive-gds** [comment]
@JackDevAU Yes it was with an older version of tinacms and tinacms/cli. This works well in tinacms v2.3.0 and @tinacms/cli" v1.6.10.
Closing this issue.
