### ISSUE TITLE
Media: search and get image from Unsplash

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#519]
## Summary
Someone from Unsplash reached out to me to do a Tina + Unsplash integration. I think it's a good idea (eventually), hence this issue. 

Editors often need to search for an image to be used in their content/fields. Unsplash is the best resource of images:

> Our library has more than 1M+ beautiful, free photos. Every photo on Unsplash is free to use for commercial/personal use and has been contributed by a community of 150k+ photographers.

### Basic example

A person from Unsplash sent me this:

> Here are the[ API Guidelines](https://help.unsplash.com/en/articles/2511245-unsplash-api-guidelines), and the [API documentation](https://unsplash.com/documentation) where your team will see some of the features we do around dynamic photo sizing, collections, orientation filtering, etc. You can also play around with the API by signing up [here](https://unsplash.com/developers). 

### Motivation

This would be a great feature for Tina and could expose Tina to the Unsplash community via their marketing channels.

**Comment by spbyrne** [comment]
This would be a great feature and I'd definitely use it in Grande since I'm already using Unsplash images. I was thinking something like this would be great for starters/themes.

**Comment by ncphillips** [comment]
For reference, there's an open [RFC](https://github.com/tinacms/rfcs/pull/3) about media

**Comment by kendallstrautman** [comment]
This could be an awesome feature of the media gallery.

**Comment by jonmiller0** [comment]
Are you all envisioning this being a new field type? I have a hacky version of this KINDA working with Next.js and the UnSplash API, but as I wrap up my hacky version, I will be looking to refactor into a more usable solution before pushing a PR...

I think it makes sense to be a "media_manager" field type that excepts different options to configure the UnSplash API (among other media options), but I also don't have a deep enough knowledge of the existing code base to know if that's the best move.

any thoughts @ncphillips @kendallstrautman @scottgallant @spbyrne ?

**Comment by scottgallant** [comment]
Exciting, @jonmiller0. 

The best people to advise on this would be @ncphillips and @dwalkr since I believe they put together the RFC on media found here: https://github.com/tinacms/rfcs/pull/3/files and discussed in slack here: https://tinacms.slack.com/archives/CNMPL8LDT/p1576176369004300

I'll continue to follow this from afar but you should hear from them soon.

**Comment by jonmiller0** [comment]
@scottgallant this is very helpful and I immediately need to rework some items based on this. thank you!!

**Comment by ncphillips** [comment]
Yes, @dwalkr and I will be doing some work on media this week. 

Unsplash is an unusual usecase as it's a provider but not a storage backend. I think that's a usecase we should put some good more thought into. 

Anyway, I'd definitely love to see your protoype before the PR.

**Comment by jonmiller0** [comment]
Sounds great. Based off the RFC I am rethinking my original approach, but when I have a prototype ready, I will drop in here. I’ll check in next week to hear what you and @dwalkr discuss!

Thanks.

Jon Miller

**Comment by kendallstrautman** [comment]
As I understand it, this type of feature would be implemented after we create a media manager UI

**Comment by kendallstrautman** [comment]
There was talk of making an Unsplash media store, but what we feel may be more aligned with most usecases is if editors could _search and source_ images from unsplash and download or copy them to their current media store.

**Comment by kendallstrautman** [comment]
Pinging @lazyplatypus for feedback or ideas.

**Comment by lazyplatypus** [comment]
Hey @kendallstrautman I think this would be interesting.
