### ISSUE TITLE
TinaCMS | When a file is renamed / deleted, update content that references it

### ISSUE THREAD

**Issue by kldavis4** [tinacms/tinacms#5209]
- [x] When renaming a file, update the content that references it
- [x] When deleting a file, warn user that "X pages reference the content" before removing the references

**Comment by kldavis4** [comment]
This is done except for handling nested reference fields: https://github.com/tinacms/tinacms/pull/5218

**Comment by kldavis4** [comment]
Handling nested references is implemented now.

Demo video https://www.youtube.com/watch?v=v6yZQmol9fo

**Comment by ncn-ssw** [comment]
Remaining work:

- [ ] Updated documentation

**Comment by JackDevAU** [comment]
✅ Done - Feature released in version 2.5.0 of `tinacms`
