### ISSUE TITLE
TS can't find type definitions for gatsby-tinacms-json

### ISSUE THREAD

**Issue by smashercosmo** [tinacms/tinacms#522]
## Description

TS can't find type definitions for gatsby-tinacms-json

### Steps to reproduce

try to import ```gatsby-tinacms-json``` package in any ts file

### Expected result

TS should find type definitions for the package

### Actual result

TS can't find type definitions for the package

#### Tinacms Package Versions

```text
gatsby-tinacms-json@0.8.0
```

**Comment by ncphillips** [comment]
Thanks @smashercosmo!

For reference, I believe the issue is that the `types` field in the package.json should be pointing at `"src/index.d.ts"`

**Comment by smashercosmo** [comment]
yes, this is the issue)
