### ISSUE TITLE
🐛 Bug - TinaCloud schema validation not checking paths

### ISSUE THREAD

**Issue by ncn-ssw** [tinacms/tinacms#5221]
@wicksipedia @kldavis4 

As documented at https://github.com/tinacms/tinacms/discussions/5214, a developer has seen an issue where the build did *not* fail when the paths in the collections of their local schema in `tina-lock.json` did not match the version held by TinaCloud.

The build should have failed to ensure that the user was aware that they had not committed their updated schema.

See the [lnigojv/website](https://github.com/Inigojv/website/blob/main/) repository for the reproduction.

## Tasks

- [ ] Determine why the check against TinaCloud passed when it shouldn't have
- [ ] Fix

**Comment by kldavis4** [comment]
It looks like the check is not comparing the local tina schema, but instead the graphql schema. I think it would probably make sense to add a tina schema comparison check as well.

**Comment by wicksipedia** [comment]
> It looks like the check is not comparing the local tina schema, but instead the graphql schema. I think it would probably make sense to add a tina schema comparison check as well.

json equality check? or compare hashes of the file?

**Comment by kldavis4** [comment]
> > It looks like the check is not comparing the local tina schema, but instead the graphql schema. I think it would probably make sense to add a tina schema comparison check as well.
> 
> json equality check? or compare hashes of the file?

Either one is probably fine

**Comment by kldavis4** [comment]
@tinacms/cli update here: https://github.com/tinacms/tinacms/pull/5248
Needs tina cloud release prior to merge.
