### ISSUE TITLE
✨ Add option to embed LinkedIn posts

### ISSUE THREAD

**Issue by sethdaily** [tinacms/tinacms#5224]
When editing in a content block, I have the option to embed a tweet. There should also be an option for embedding a LinkedIn post.

1. Add the same functionality for LinkedIn

![Image](https://github.com/user-attachments/assets/7567be20-d2d6-42fc-bdc0-165985eb8ba0)
Figure: give me the same option for LinkedIn

**Comment by wicksipedia** [comment]
I think you meant to log this in a different repository
