### ISSUE TITLE
"r.join is not a function" in NextJs during generateStaticParams in Production Build

### ISSUE THREAD

**Issue by abel3t** [tinacms/tinacms#5226]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

While creating an production build, the following error occurs during the "Collecting page data" step:

```bash
TypeError: r.join is not a function
```

### Reproduction

```bash
npm run build
```

### Steps to reproduce

1. **Set up a Next.js 14 project using the App Router**:
   - Ensure your project is using the App Router (`app` directory).
   
2. **Implement `generateStaticParams`**:
   - Add the following code in your component or page file to generate static parameters:

   ```typescript
   export async function generateStaticParams() {
     const posts = await client.queries.postConnection();
     return (
       posts?.data?.postConnection?.edges?.map((post) => ({
         slug: post?.node?._sys.filename,
       })) || []
     );
   }
   ```

3. **Run a production build**:
   - Execute the build command to generate a static site: `npm run build` or `yarn build`.

### System Info

```bash
System:
    OS: macOS 15.0.1
    CPU: (8) arm64 Apple M1 Pro
    Memory: 425.78 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.8.1 - ~/.nvm/versions/node/v20.8.1/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 10.1.0 - ~/.nvm/versions/node/v20.8.1/bin/npm
    pnpm: 8.6.10 - ~/Library/pnpm/pnpm
    bun: 1.0.30 - ~/.bun/bin/bun
  npmPackages:
    @tinacms/cli: ^1.5.53 => 1.6.8 
    tinacms: ^2.1.1 => 2.3.0 
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by mAAdhaTTah** [comment]
I'm also experiencing this, although it doesn't seem to stop the build.

**Comment by JackDevAU** [comment]
Hi @abel3t & @mAAdhaTTah 

Cheers for finding this - Taking a look now 🙏

**Comment by JackDevAU** [comment]
Hi All, 

A fix has been released in the following versions, 

- **tinacms** `v2.4.0`
- **@tinacms/cli** `v1.6.11`

Thanks for your patience 🦙

**Comment by abel3t** [comment]
Thanks @JackDevAU
