### ISSUE TITLE
Upload image as banner image

### ISSUE THREAD

**Issue by gogears** [tinacms/tinacms#527]
## Description

How to place the image as banner in blog's post page and blog listing page

### Steps to reproduce

1) In markdown file where to specify the file path
2) And which path should be those file had to placed

### Expected result

In below mentioned video there will be a option to upload images in the sidebar, please check them
[Sample Reference](https://res.cloudinary.com/forestry-demo/video/upload/q_100,h_584/v1571425758/tina-hero-demo-v2.webm)

### Actual result

I could not able to find how to place image as banner in post

### Environment

| Tool    | Version |
| ------- | ------- |
| browser |    Chrome Version 78.0.3904.108     |
| os      |     MacOS Mojave 10.14.6    |
| node    |    V12.13.1     |
| npm     |    V6.12.1     |
| tinacms |    react-tinacms(V^0.8.0)     |

**Comment by DirtyF** [comment]
@gogears Have you checked https://github.com/tinacms/tina-starter-grande there's a hero setting where you can change the banner  if it helps.

**Comment by gogears** [comment]
> @gogears Have you checked https://github.com/tinacms/tina-starter-grande there's a hero setting where you can change the banner if it helps.

@DirtyF Thanks for replying immediately, will check and get back to you

**Comment by gogears** [comment]
1) In what procedure we can make the changes with the current UI, based user requirement
2) How to make it ready for production ready and run in specific port number

**Comment by gogears** [comment]
>     1. In what procedure we can make the changes with the current UI, based user requirement
> 
>     2. How to make it ready for production ready and run in specific port number

@DirtyF do you any solution for this

**Comment by DirtyF** [comment]
@gogears If you're looking for a way for a team to use Tina in a browser, register for https://tinacms.org/teams, early phase should begin soon. Head over to https://community.tinacms.org/ for generic questions, this repository is mainly to discuss tinacms development. Thanks.

**Comment by kendallstrautman** [comment]
@gogears - We recently published a [blog](https://tinacms.org/blog/editing-on-the-cloud/) that could answer some of your questions!
