### ISSUE TITLE
Broken link to self hosted limitations on website.

### ISSUE THREAD

**Issue by nicko-winner** [tinacms/tinacms#5277]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

Broken link on website. https://tina.io/docs/self-hosted/overview
![Image](https://github.com/user-attachments/assets/bcc2bc7c-9078-465e-bb50-1baf348425cc)

![Image](https://github.com/user-attachments/assets/5ee453c7-0afe-4d10-9808-8a3bc14cab25)

### Reproduction

https://tina.io/docs/self-hosted/overview

### Steps to reproduce

click the link for "Self Hosted Limitations". 

### System Info

```shell
All
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by kldavis4** [comment]
Thanks for the report. Should be fixed shortly. Here is the link https://tina.io/docs/introduction/faq#what-features-are-unavailable-in-self-hosted-tina-compared-to-tinacloud
