### ISSUE TITLE
Change content in remark forms occur error

### ISSUE THREAD

**Issue by Sampangpang** [tinacms/tinacms#534]
When I modify the content in remark forms. There is frequent occur this error.Refresh is fine and value also changed. (Even I create a new sample project. It's also happened)

```
react-beautiful-dnd
An error has occurred while a drag is occurring.
Any existing drag will be cancelled.
> Uncaught useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query
```

**Comment by DirtyF** [comment]
Hi, is the sample project public so we can reproduce this easily? 🙏

**Comment by Sampangpang** [comment]
> Hi, is the sample project public so we can reproduce this easily? 🙏

Yes. I just fast input character in text-area field. Sometimes it happens. But for mine project, It's frequent.

**Comment by ncphillips** [comment]
Hey @Sampangpang thanks for the report! 

We haven't seen this issue for a while. Could you provide some more information to help us track it down?

Run the following command to get the list of tinacms-package versions in your node_modules:

    npm ls | grep tinacms | grep -v deduped

Also, please add as much information about your environment as possible:

| Tool    | Version |
| ------- | ------- |
| os      |         |
| node    |         |
| npm     |         |

Maybe how much RAM is in your machine as well.

**Comment by Sampangpang** [comment]
```
$ npm ls | grep tinacms | grep -v deduped
gatsby-starter-tinacms@0.1.0 D:\projects\video_wall
+-- gatsby-plugin-tinacms@0.1.16
| +-- @tinacms/core@0.5.0
| `-- tinacms@0.10.0
|   +-- @tinacms/fields@0.1.16
|   +-- @tinacms/icons@0.3.9
|   +-- @tinacms/react-core@0.2.0
|   +-- @tinacms/styles@0.1.0
+-- gatsby-tinacms-git@0.2.14
| +-- @tinacms/api-git@0.4.6
| +-- @tinacms/git-client@0.4.1
+-- gatsby-tinacms-json@0.8.0
+-- gatsby-tinacms-remark@0.6.0
| +-- @tinacms/form-builder@0.2.8
+-- react-tinacms@0.8.1
| +-- @tinacms/core@0.4.4
```

os:       win10
node:   v12.13.1
npm:    6.12.1
RAM:   16GB


Full Error Info:
```
react-beautiful-dndAn error has occurred while a drag is occurring.Any existing drag will be cancelled.> Uncaught useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:export const pageQuery = graphql`query BlogPostBySlug($slug: String!) {markdownRemark(fields: { slug: { eq: $slug } }) {...TinaRemark// etc...}}2. If you are using an alias, For example:export const pageQuery = graphql`query BlogPostBySlug($slug: String!) {markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {...TinaRemark// etc...}}then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })`👷‍ This is a development only message. It will be removed in production builds.
__stack_frame_overlay_proxy_console__ @ index.js:2177
index.js:2177 raw ErrorEvent
__stack_frame_overlay_proxy_console__ @ index.js:2177
index.js:1 Uncaught useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query

1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      ...TinaRemark
      // etc...
    }
 }

2. If you are using an alias, For example:

   export const pageQuery = graphql`
     query BlogPostBySlug($slug: String!) {
       markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {
          ...TinaRemark
       // etc...
       }
    }

  then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':

    export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })
`
  
index.js:2177 The above error occurred in the <Component> component:
    in Component (created by HotExportedComponent)
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent (created by PageRenderer)
    in PageRenderer (at json-store.js:93)
    in JSONStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:64)
    in RouteUpdates (at root.js:63)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:126)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div
    in Unknown
    in _default (at app.js:67)

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
__stack_frame_overlay_proxy_console__ @ index.js:2177
index.js:2177 useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query

1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      ...TinaRemark
      // etc...
    }
 }

2. If you are using an alias, For example:

   export const pageQuery = graphql`
     query BlogPostBySlug($slug: String!) {
       markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {
          ...TinaRemark
       // etc...
       }
    }

  then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':

    export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })
`
  
__stack_frame_overlay_proxy_console__ @ index.js:2177
index.js:2177 react-beautiful-dndAn error has occurred while a drag is occurring.Any existing drag will be cancelled.> Uncaught useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:export const pageQuery = graphql`query BlogPostBySlug($slug: String!) {markdownRemark(fields: { slug: { eq: $slug } }) {...TinaRemark// etc...}}2. If you are using an alias, For example:export const pageQuery = graphql`query BlogPostBySlug($slug: String!) {markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {...TinaRemark// etc...}}then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })`👷‍ This is a development only message. It will be removed in production builds.
__stack_frame_overlay_proxy_console__ @ index.js:2177
index.js:2177 raw ErrorEvent
__stack_frame_overlay_proxy_console__ @ index.js:2177
react-hot-loader.development.js:2406 Uncaught useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query

1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      ...TinaRemark
      // etc...
    }
 }

2. If you are using an alias, For example:

   export const pageQuery = graphql`
     query BlogPostBySlug($slug: String!) {
       markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {
          ...TinaRemark
       // etc...
       }
    }

  then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':

    export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })
`
  
index.js:2177 The above error occurred in the <AppContainer> component:
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent (created by PageRenderer)
    in PageRenderer (at json-store.js:93)
    in JSONStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:64)
    in RouteUpdates (at root.js:63)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:126)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div
    in Unknown
    in _default (at app.js:67)

React will try to recreate this component tree from scratch using the error boundary you provided, LocationProvider.
__stack_frame_overlay_proxy_console__ @ index.js:2177
index.js:83 Uncaught useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query

1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      ...TinaRemark
      // etc...
    }
 }

2. If you are using an alias, For example:

   export const pageQuery = graphql`
     query BlogPostBySlug($slug: String!) {
       markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {
          ...TinaRemark
       // etc...
       }
    }

  then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':

    export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })
`
  
index.js:2177 The above error occurred in the <LocationProvider> component:
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:126)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in styled.div
    in Unknown
    in _default (at app.js:67)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
__stack_frame_overlay_proxy_console__ @ index.js:2177
react-dom.development.js:12212 Uncaught useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query

1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      ...TinaRemark
      // etc...
    }
 }

2. If you are using an alias, For example:

   export const pageQuery = graphql`
     query BlogPostBySlug($slug: String!) {
       markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {
          ...TinaRemark
       // etc...
       }
    }

  then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':

    export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })
`
```

Mine graphql query is: 
```
export const pageQuery = graphql`
query {
  markdownRemark (
    fields: {
      slug: {
        regex: "/home/"
      }
    }
  )
  {
    html
    fileRelativePath
    rawFrontmatter
    rawMarkdownBody
    frontmatter {
      title
      displayWeatherPanle
      news_api
      region_stock_api
      regionstock_appid
      regionstock_username
      regionstock_password
      city_code
      video_link
      video_replay
      video_replay_interval
      video_timing_switch
      video_timing
      stocklist_api
      stocklist_username
      stocklist_password
      cover_image {
        childImageSharp {
          fluid {
            src
          }
        }
      }
    }
  }
}
`
```

**Comment by ncphillips** [comment]
Awesome! Thanks a lot. That’s quite helpful. Hopefully someone gets a chance to check this out soon.

**Comment by Sampangpang** [comment]
I updated the most new version of tinacms. Still has this problem, but for sample is fine. 
Here is more detail error:


Error: useRemarkForm(markdownRemark) 'markdownRemark' was not found on the top node of the graphql query

1. Check if the 'markdownRemark' attribute is included in the GraphQL query. For example:

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      ...TinaRemark
      // etc...
    }
 }

2. If you are using an alias, For example:

   export const pageQuery = graphql`
     query BlogPostBySlug($slug: String!) {
       markdownRemark: markdownRemark(fields: { slug: { eq: $slug } }) {
          ...TinaRemark
       // etc...
       }
    }

  then you can optionally use the 'queryName' option to specify a new property in place of 'markdownRemark':

    export const remarkForm(BlogPostTemplate, { queryName: markdownRemark })
`
  
▼ 17 stack frames were expanded.
errorHandler
D:/projects/refinitiv/video_wall/node_modules/react-error-overlay/lib/index.js:1995
invokeGuardedCallbackDev
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:385
invokeGuardedCallback
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:440
commitRootImpl
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:25082
unstable_runWithPriority
D:/projects/refinitiv/video_wall/node_modules/scheduler/cjs/scheduler.development.js:697
runWithPriority$2
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:12149
commitRoot
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:24922
finishSyncRender
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:24329
performSyncWorkOnRoot
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:24307
(anonymous function)
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:12199
unstable_runWithPriority
D:/projects/refinitiv/video_wall/node_modules/scheduler/cjs/scheduler.development.js:697
runWithPriority$2
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:12149
flushSyncCallbackQueueImpl
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:12194
flushSyncCallbackQueue
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:12182
scheduleUpdateOnFiber
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:23709
enqueueSetState
D:/projects/refinitiv/video_wall/node_modules/react-dom/cjs/react-dom.development.js:13994
PageQueryStore../node_modules/react/cjs/react.development.js.Component.setState
D:/projects/refinitiv/video_wall/node_modules/react/cjs/react.development.js:325
▲ 17 stack frames were expanded.
PageQueryStore._this.handleMittEvent
D:/projects/refinitiv/video_wall/.cache/query-result-store.js:38
```
  35 | }
  36 | 
  37 | handleMittEvent = () => {
> 38 |   this.setState({
  39 |     pageQueryData: getPageQueryData(),
  40 |   })
  41 | }
```
View compiled
▼ 2 stack frames were expanded.
(anonymous function)
D:/projects/refinitiv/video_wall/node_modules/mitt/dist/mitt.es.js:58
emit
D:/projects/refinitiv/video_wall/node_modules/mitt/dist/mitt.es.js:58
▲ 2 stack frames were expanded.
r.<anonymous>
D:/projects/refinitiv/video_wall/.cache/socketIo.js:56
```
  53 |       }
  54 |     }
  55 |     if (msg.type && msg.payload) {
> 56 |       ___emitter.emit(msg.type, msg.payload)
  57 |     }
  58 |   })
  59 | } catch (err) {
```
View compiled
▼ 18 stack frames were expanded.
r.emit
http://localhost:8000/socket.io/socket.io.js:6:19839
r.onevent
http://localhost:8000/socket.io/socket.io.js:8:10571
r.onpacket
http://localhost:8000/socket.io/socket.io.js:8:10193
r.<anonymous>
http://localhost:8000/socket.io/socket.io.js:8:12354
r.emit
http://localhost:8000/socket.io/socket.io.js:6:19839
r.ondecoded
http://localhost:8000/socket.io/socket.io.js:6:25583
a.<anonymous>
http://localhost:8000/socket.io/socket.io.js:8:12354
a.r.emit
http://localhost:8000/socket.io/socket.io.js:6:19839
a.add
http://localhost:8000/socket.io/socket.io.js:6:12498
r.ondata
http://localhost:8000/socket.io/socket.io.js:6:25536
r.<anonymous>
http://localhost:8000/socket.io/socket.io.js:8:12354
r.emit
http://localhost:8000/socket.io/socket.io.js:6:19839
r.onPacket
http://localhost:8000/socket.io/socket.io.js:7:2948
r.<anonymous>
http://localhost:8000/socket.io/socket.io.js:7:560
r.emit
http://localhost:8000/socket.io/socket.io.js:6:19839
r.onPacket
http://localhost:8000/socket.io/socket.io.js:7:15217
r.onData
http://localhost:8000/socket.io/socket.io.js:7:15166
WebSocket.ws.onmessage
http://localhost:8000/socket.io/socket.io.js:8:6594
▲ 18 stack frames were expanded.
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by ncphillips** [comment]
Thanks for the additional details @Sampangpang. I'm digging into bugs today and am hoping to get to this soon.

**Comment by ncphillips** [comment]
@all-contributors please add @Sampangpang for bugs

**Comment by ncphillips** [comment]
Something messed up. @all-contributors please add @Sampangpang for bugs

**Comment by ncphillips** [comment]
I have two hypothesis about this problem. 

1. It's a null value issue that was fixed the latest release
1. The page URL is being generated by one of your frontmatter values

In the first case, updating all the tinacms dependencies in your package.json should resolve the issue.

I'm not sure if it's the second case because I can't look at your code. But if it is, you'll need to change how the URL is being generated. Someon else had a [issue with similar symptoms](https://github.com/tinacms/tinacms/issues/583#issuecomment-577222081)

**Comment by Sampangpang** [comment]
Yes. Updated and it fixed. Thank you.

**Comment by ncphillips** [comment]
Wonderful! Thanks for your patience on this @Sampangpang 😃

**Comment by panzerstadt** [comment]
so i came across this recently while working on it, and solved it by setting TINA_GIT_DEBOUNCE_MS=5000 instead. updating to the latest version of tinacms didn't help in my case. just putting it out here in case it helps.
