### ISSUE TITLE
I cannot see changes made locally show on my localhost server

### ISSUE THREAD

**Issue by MysticNynja** [tinacms/tinacms#5390]
### Describe the issue that you're seeing. Any Loom videos or screenshots usually help a lot!

I have tried the NextJS template and the barebone template with npm and yarn.  I cannot get changes made locally to show up in the browser.  Simply I am just changing the words inside the about.mdx page in the blank template to say 'This is a "" page.' The default says 'This is an "about" page.'

I have tried rerunning the server and nothing makes that page refresh.  

### Reproduction

https://github.com/MysticNynja/TinaCMS-Error

### Steps to reproduce

Start the server with npm run dev
Browse to localhost:3000
Edit the Home page
I don't see it reflect when I save the file, refresh the page, or restart the server.

### System Info

```shell
System:
    OS: Windows 11 10.0.22631
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 36.57 GB / 63.85 GB
  Binaries:
    Node: 22.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.22 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 11.0.0 - ~\AppData\Roaming\npm\npm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
  npmPackages:
    @tinacms/cli: ^1.6.12 => 1.7.0
    tinacms: ^2.5.0 => 2.5.2
```

### Validations

- [x] Follow our [Code of Conduct](https://github.com/tinacms/tinacms/blob/main/CODE_OF_CONDUCT.md)
- [x] Read the [docs](https://tina.io/docs).
- [x] Check that there isn't [already an issue](https://github.com/tinacms/tinacms/issues) that reports the same bug.

**Comment by MysticNynja** [comment]
The other thing I am seeing is when I delete a blog post, one that was pre written, it errors out with this error message on screen and I have to restart the server

`[Error] GetCollection failed: Unable to fetch, errors: Error querying file content/posts/voteForPedro.mdx from collection post. Please run "tinacms audit" or add the --verbose option for more info`

Then when I restart the server that blog post is still there.

**Comment by MysticNynja** [comment]
![Image](https://github.com/user-attachments/assets/1a3c6599-dfd8-4cf6-ab7b-0109adc177b5)

**Comment by cod3blox** [comment]
> The other thing I am seeing is when I delete a blog post, one that was pre written, it errors out with this error message on screen and I have to restart the server
> 
> `[Error] GetCollection failed: Unable to fetch, errors: Error querying file content/posts/voteForPedro.mdx from collection post. Please run "tinacms audit" or add the --verbose option for more info`
> 
> Then when I restart the server that blog post is still there.

This one is an old Bug that only appears on Windows when deleting items. Have this too. 
https://github.com/tinacms/tinacms/issues/4018

**Comment by MysticNynja** [comment]
Ok I see that bug with the deleting, that is fine I can live with restarting. 

The other problem is now working in a blank template (like the one I have linked) but when you start a NextJS template I delete the file (get the error that is known) So i restart the server.  Now I can still see the file that was deleted in the browser.  I no longer have it in my /posts folder.

Even if I browse with an incognito window I still see it
![Image](https://github.com/user-attachments/assets/19d36dfc-b46b-4414-a75f-d7e19e519fed)

Just to reiterate, NextJS starter project, delete a post, restart, see error.

**Comment by kldavis4** [comment]
@MysticNynja this sounds like a Next caching issue. Try deleting the .next folder and then restarting

**Comment by MysticNynja** [comment]
@kldavis4 Yes deleting the .next folder while the server was shut down and then starting it back up again did the trick.

I don't know if this is a good workflow going forward.  When this goes to production, I would rather not have to do this every time one of the users deletes something.  Should I file a new bug for this behavior?

**Comment by kldavis4** [comment]
These issues are all only related to dev mode so not something you'd need to worry about in production. The issue with the file not getting removed is an issue with next and not with tinacms. There is already a bug for the windows delete issue (which again only applies in dev mode on windows).

**Comment by MysticNynja** [comment]
OK awesome. As long as it doesn't happen in production, I'll look at nextjs to see if there is a resolution on their end.

Thanks for helping me out!
