### ISSUE TITLE
Date picker issues in create post modal

### ISSUE THREAD

**Issue by jpatters** [tinacms/tinacms#545]
## Description

In this screenshot you can see that the date picker isn't really visible.
<img width="467" alt="Screen Shot 2019-12-19 at 4 01 59 PM" src="https://user-images.githubusercontent.com/195614/71205649-3099e280-2279-11ea-9b3f-71996626ac08.png">

In this screenshot I've tried to capture the behaviour of clicking on a date. It chooses the date previous to the one I've clicked
<img width="470" alt="Screen Shot 2019-12-20 at 7 49 39 AM" src="https://user-images.githubusercontent.com/195614/71253123-536dda80-22fd-11ea-8004-3cea60c18102.png">

Also, the field shows a default value but if I submit the form without selecting a date, the field is not submitted. Basically, the default value shows but doesn't actually do anything.

### Steps to reproduce

Add a date picker to a create page modal.

#### Tinacms Package Versions

```text
npm ERR! peer dep missing: typescript@>=3.5.0, required by ts-essentials@3.0.5
├─┬ gatsby-plugin-tinacms@0.1.17
│ ├─┬ @tinacms/core@0.5.1
│ └─┬ tinacms@0.11.0
│   ├─┬ @tinacms/fields@0.1.17
│   ├─┬ @tinacms/form-builder@0.2.9
│   ├── @tinacms/icons@0.3.9
│   ├─┬ @tinacms/react-core@0.2.1
│   ├── @tinacms/styles@0.1.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |    firefox     |
| os      |     macos    |
| node    |     v10.16.1    |
| npm     |     6.12.0    |

**Comment by DirtyF** [comment]
Reminds me of the same issue on Forestry (related to timezone and date output format)

**Comment by spbyrne** [comment]
The date and color pickers both get cut off by whatever form view they're in (same issue happens in the sidebar). Once I become a portal master after fixing the current group/block UI issue I'll see about using the same approach to fix this.

Ideally portals will be used for any popover/modal to prevent this type of thing from happening.

**Comment by kendallstrautman** [comment]
This is an issue in the _Settings Modal_ for inline editing.

**Comment by spbyrne** [comment]
Working on a potential solution for this here: #1282
