### ISSUE TITLE
feat: table support in markdown wysiwyg

### ISSUE THREAD

**Issue by JeffersonBledsoe** [tinacms/tinacms#549]
The current markdown parser already seems to implement tables, cells and headers for the markdown nodes ([see here](https://github.com/tinacms/tinacms/blob/d20b8c4c0cadf120cc5f377d46fdd4412850a99f/packages/@tinacms/fields/src/Wysiwyg/plugins/schema/nodes/tables.ts))
If the proposal involves a new or changed API, include a basic code example. Omit this section if it's not applicable.
 
### Motivation

Tables are a bit of a pain to work with in Markdown so having a WYSIWYG way of creating and editing them would be very useful to both those familiar and unfamiliar with markdown

**Comment by DirtyF** [comment]
Agreed, Prosemirror has a dedicated plugin: https://github.com/ProseMirror/prosemirror-tables

We can split up this in smaller tasks: 

- [ ] Display existing Markdown tables 
- [ ] Support alignment properties
- [ ] Editor button to add a simple table (to be shaped)
- [ ] Advanced tables management (rows, columns)  (to be shaped)
- [ ] Handle advanced cases (pipes in the cell)

**Comment by DirtyF** [comment]
@jpuri Let me know If I can help on this one.

**Comment by jpuri** [comment]
PR https://github.com/tinacms/tinacms/pull/588 addresses first 3 points above.

**Comment by jpuri** [comment]
@DirtyF : can you plz details these
- Handle advanced cases (pipes in the cell)
- Provide a table component for developers

**Comment by DirtyF** [comment]
@jpuri I'll open a new PR for the rest, I was mostly listing future improvements.
