### ISSUE TITLE
Customizable width of the sidebar

### ISSUE THREAD

**Issue by weibenfalk** [tinacms/tinacms#558]
## Summary

Think it would make sense to add an option to set a custom width to the sidebar. If you think it's a good idea I can try to implement this for the gatsby plugin to see how it works and create a PR. My idea is to set a max-width so it will be responsive and scale down on mobile devices. 

Haven't looked at the components/plugins for the form fields in detail so don't know if it will be a bigger project refactoring them. But guessing they are set to scale to the width of the sidebar?

### Basic example

```
{
    resolve: 'gatsby-plugin-tinacms',
    options: {
      sidebar: {
        position: 'displace',
        maxWidth: '400px'  // could also just be width
      },
    },
}
```

### Motivation

The sidebar can feel small on bigger screens.  Would be great to have the possibility to decide how wide the sidebar should be.

**Comment by DirtyF** [comment]
Would be even better if you could resize it without any optional setting.

**Comment by weibenfalk** [comment]
Yes, that would be great ... but guess that requires a lot more work as it will affect the whole site when the user resizes dynamically. Or it is much simpler than I think right now without having thought it through =) 

Guess it would be great to still be able to set the initial width though. There's probably also use cases when you don't want the user to be able to resize but only set a max-width.

**Comment by weibenfalk** [comment]
Check out the below video. Is this something you want? Still a lot of refactoring to do as I just got it working =) And it doesn't seem to work with inline editing yet. Haven't looked at why yet ... It changes size when I press the inline editing button and I have no clue why now as I haven't tampered with that at all. I created a new component, a resizerBar, and added it to Tina with some small tweaks and local states. 

I also didn't want to re-render the whole sidebar on each pixel move with the mouse. That's why I created this kind of "ghosting" process where the user drags the line to the desired width first. Then I update the width of the sidebar and everything in it. This way I just have to re-render the resize-bar itself when it moves and update its local state. 

As you can see there are also some tweaks that have to be made to the form fields so they will have full width. And I didn't test it with the "fixed" version of the sidebar yet. Just the "displace" one. 

Anyways ... below is the video: 

https://www.dropbox.com/s/1zv811ixk7pwwfa/tina-resizable-test.mov?dl=0

**Comment by DirtyF** [comment]
Wow, I didn't think you'll go the hard way. 😊 
Would it help with the rendering if the sidebar was kind of blurry on drag?
It mostly raises the question: how large should the sidebar be in different contexts? 
When do we need a larger sidebar?
What do you say @spbyrne?

**Comment by weibenfalk** [comment]
Hey … No to make the sidebar blurry would probably demand more computer power =) 
I actually think that this feels really smooth when using it. It feels natural some how. 
This is a fairly easy implementation also without to much refactoring, this way.

In my honest opinion. I always felt that the sidebar is kind of small when editing a lot of text. 
That’s why I thought it is good to be able to at least set the max width on it.

**Comment by spbyrne** [comment]
This is amazing 👍 I like the approach you've used to prevent rerendering until you've released the mouse. Also the resize handle looks quite good.

**Comment by spbyrne** [comment]
I think the sidebar should just default to the current width with the ability to set a different initial width. The user can then resize it as needed.

One change I intend to make is to float the sidebar above the content below a certain screen size, even if it's set to displace. This way on a phone you'd be able to open the sidebar without the site breaking. In fact, maybe on mobile the sidebar should just open to something like 90% width and cover most of the content. But this can be another PR (mobile sidebar improvements)

**Comment by weibenfalk** [comment]
Thanks again :) I will look into why it isn’t working as it should with inline editing. Think it is because I changed some width to 100% on the sidebar instead of giving it the width by props. But really don’t know right now. Will look into it ASAP .. can make a pr so you can try it out yourself also 

Skickat från min iPhone

**Comment by chintenemeegamarachchi-dev** [comment]
Dear all, I am new to Tina and liking it very-much. Having the ability to resize the editing window will add tons of value to devs like myself whos planning to build custom plugins

Looking forward to seeing this feature implemented 

Cheers for developing such a fantastic library
