### ISSUE TITLE
feat: support footnotes

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#566]
## Summary

The Markdown editor can display existing footnotes

### Expectation

Given I have a reference `[^1]` and  a footnote `[^1]: https://example.com` in my Markdown
When I'm using the editor
Then it displays the footnote and the reference. 

See: https://prosemirror.net/examples/footnote/

Nice to have: a way to add a footnote (can can done in another PR)

### Motivation

Do not break existing content, display it nicely.
Getting familiar with prosemirror extensibility

**Comment by jpuri** [comment]
Hey @spbyrne, can you plz share some design details for this task.

@DirtyF : from code it looks like support for footnotes is required to be added in translator also, can you plz confirm.

**Comment by DirtyF** [comment]
@jpuri I don't know what translator is but whatever it takes to be able to display footnotes in the editor 😄

**Comment by ncphillips** [comment]
Yes, it would need a Prosemirror schema definition, as well as the [Translator's tokens](https://github.com/tinacms/tinacms/blob/use-json-form-options/packages/@tinacms/fields/src/Wysiwyg/Translator/MarkdownTranslator/commonmark/tokens.ts#L109).

**Comment by selfire1** [comment]
Hi! I'd just like to mention interest in this issue. Writing a whole post in Tina, only to edit it in another place to add footnotes is cumbersome.

In https://github.com/tinacms/tinacms/issues/3058#issuecomment-1232204672 it was mentioned that it is an aim to support footnotes internally. I'd love that functionality.

Happy to open another issue if this is the wrong place for a FR for footnote support.
