### ISSUE TITLE
feat: advanced table management

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#593]
## Summary

Add some controls to edit tables in the editor
 - [x]  add/remove a column
 - [x] add/remove a row (#table
 - [x] prevent table inception (#642 )
 - [x] support markdown styling (bold, italic, link) (#664)
 - [x] delete table (#631)
 - [x] align columns (#641)

 https://github.com/ProseMirror/prosemirror-tables#commands

**Comment by DirtyF** [comment]
@jpuri  There is a lot of options for tables, let's start small and improve step by step.

**Comment by jpuri** [comment]
Hey @DirtyF : are there more advance controls that will be nice to have in tables.

**Comment by DirtyF** [comment]
Delete table?

**Comment by jpuri** [comment]
Yep its planned: https://github.com/tinacms/tinacms/issues/631
