### ISSUE TITLE
Standard gatsby blog starter blog form not being recognized

### ISSUE THREAD

**Issue by weisisheng** [tinacms/tinacms#594]
## Description

On previously working simple blog, installed the Tinacms according to instructions (and visiting a number of other sites).  Believe code is correct but form found at blogpost.js not recognized.

Seems similar to this closed issue, https://github.com/tinacms/tinacms/issues/512 but double checked and everything is updated.

### Steps to reproduce

Followed instructions 1-3 here, https://www.gatsbyjs.org/blog/2019-12-20-integrate-tinacms-with-your-gatsby-website/

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

Fields to edit post should show.

### Actual result

What actually happened?

Site renders but tinacms sidebar shows welcome and link to external form guide.

#### Tinacms Package Versions

```
I use yarn...

yarn list | grep tinacms | grep -v deduped
├─ @tinacms/api-git@0.5.0
├─ @tinacms/core@0.5.1
├─ @tinacms/fields@0.1.17
│  ├─ @tinacms/core@^0.5.1
│  ├─ @tinacms/icons@^0.3.9
│  ├─ @tinacms/styles@^0.1.0
├─ @tinacms/form-builder@0.2.10
│  ├─ @tinacms/core@^0.6.0
│  ├─ @tinacms/core@0.6.0
│  ├─ @tinacms/forms@^0.1.0
│  ├─ @tinacms/react-core@^0.2.2
│  ├─ @tinacms/react-core@0.2.2
│  │  ├─ @tinacms/core@^0.6.0
│  │  ├─ @tinacms/forms@^0.1.0
├─ @tinacms/forms@0.1.0
├─ @tinacms/git-client@0.4.1
├─ @tinacms/icons@0.3.9
├─ @tinacms/react-core@0.2.1
│  ├─ @tinacms/core@^0.5.1
├─ @tinacms/styles@0.1.0
├─ gatsby-plugin-tinacms@0.1.18
│  ├─ @tinacms/core@^0.6.0
│  ├─ @tinacms/core@0.6.0
│  ├─ @tinacms/fields@0.2.0
│  │  ├─ @tinacms/core@^0.6.0
│  │  ├─ @tinacms/icons@^0.3.9
│  │  ├─ @tinacms/styles@^0.1.0
│  ├─ @tinacms/react-core@0.2.2
│  │  ├─ @tinacms/core@^0.6.0
│  │  ├─ @tinacms/forms@^0.1.0
│  ├─ tinacms@^0.11.1
│  └─ tinacms@0.11.1
│     ├─ @tinacms/core@^0.6.0
│     ├─ @tinacms/fields@^0.2.0
│     ├─ @tinacms/form-builder@^0.2.10
│     ├─ @tinacms/forms@^0.1.0
│     ├─ @tinacms/icons@^0.3.9
│     ├─ @tinacms/react-core@^0.2.2
│     ├─ @tinacms/styles@^0.1.0
├─ gatsby-tinacms-git@0.2.15
│  ├─ @tinacms/api-git@^0.5.0
│  ├─ @tinacms/core@^0.5.1
│  ├─ @tinacms/git-client@^0.4.1
│  ├─ gatsby-plugin-tinacms@^0.1.17
│  ├─ gatsby-plugin-tinacms@0.1.17
│  │  ├─ @tinacms/core@^0.5.1
│  │  └─ tinacms@^0.11.0
│  └─ tinacms@^0.11.0
├─ gatsby-tinacms-remark@0.6.2
│  ├─ @tinacms/core@^0.6.0
│  ├─ @tinacms/core@0.6.0
│  ├─ @tinacms/fields@0.2.0
│  │  ├─ @tinacms/core@^0.6.0
│  │  ├─ @tinacms/icons@^0.3.9
│  │  ├─ @tinacms/styles@^0.1.0
│  ├─ @tinacms/form-builder@^0.2.10
│  ├─ @tinacms/react-core@0.2.2
│  │  ├─ @tinacms/core@^0.6.0
│  │  ├─ @tinacms/forms@^0.1.0
│  ├─ tinacms@^0.11.1
│  └─ tinacms@0.11.1
│     ├─ @tinacms/core@^0.6.0
│     ├─ @tinacms/fields@^0.2.0
│     ├─ @tinacms/form-builder@^0.2.10
│     ├─ @tinacms/forms@^0.1.0
│     ├─ @tinacms/icons@^0.3.9
│     ├─ @tinacms/react-core@^0.2.2
│     ├─ @tinacms/styles@^0.1.0
├─ tinacms@0.11.0
│  ├─ @tinacms/core@^0.5.1
│  ├─ @tinacms/fields@^0.1.17
│  ├─ @tinacms/form-builder@^0.2.9
│  ├─ @tinacms/form-builder@0.2.9
│  │  ├─ @tinacms/core@^0.5.1
│  │  ├─ @tinacms/react-core@^0.2.1
│  ├─ @tinacms/icons@^0.3.9
│  ├─ @tinacms/react-core@^0.2.1
│  ├─ @tinacms/styles@^0.1.0

```

Gatsby CLI version: 2.8.26, Gatsby version: 2.17.6

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  chrome         |
| os      |   ubuntu 19.10      |
| node    |  v 12.14.1       |
| npm     |  I use yarn  |
| yarn | 1.19.1

**Comment by ncphillips** [comment]
Thanks for the report @weisisheng. I just followed the first few steps in the blog post and had no problems. Is the repo you made publicly available?

**Comment by weisisheng** [comment]
I hoped to add a link to repo but there is private info within.  I will try to install again next few days or isolate the code for public viewing.  Thanks for the fast response.

**Comment by ncphillips** [comment]
@all-contributors please add @weisisheng for bugs

**Comment by ncphillips** [comment]
Hey @weisisheng There's been a couple releases since you reported this. If you upgrade all of your tinacms dependencies is this still happening?

**Comment by weisisheng** [comment]
Thanks for check-in.  I will need to give a try soon.  I have been transitioning to a new, more complex theme so bogged down with that.  I can give the new ones a try.

**Comment by weisisheng** [comment]
No errors installing, gave it another round and still can't get blog post form to render.  I will dig into it further.  Guessing it is my lack of gatsby knowledge for now.
