### ISSUE TITLE
@tinacms/api-git should not always configure the Git remote.

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#599]
In order to support cloud editing environments. The `@tinacms/git-api` is setup to [configure the Git remote](https://github.com/tinacms/tinacms/blob/master/packages/@tinacms/api-git/src/router.ts#L126) to make sure it can be pushed too. This function is always called, but this behaviour is not desirable when working locally. We need some way to split these up.

**Comment by kendallstrautman** [comment]
Unwanted behavior related to this in #918

**Comment by ncphillips** [comment]
I think this was fixed 🤔
