### ISSUE TITLE
Provide visual feedback when forms fail to save

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#600]
## Description

The form UI provides no indicator when saving fails.

### Steps to reproduce

1. Go to a Gatsby site that uses Tina + Markdown
1. `git remote remove origin` 
1. Start the dev server
1. Edit some content in the form
1. Press save

### Expected result

Some kind of UI notification 

### Actual result

Looks like the form saves, but it didn't

**Comment by jarodpeachey** [comment]
@ncphillips Could I take this issue on?

**Comment by ncphillips** [comment]
Sure, but let's rope @spbyrne in here. The technical part isn't hard but I'm not sure what the designs should be like

**Comment by spbyrne** [comment]
We've discussed notifications for a number of different cases. We don't have to start with something that's reusable, but I'd at least like to design with that in mind. @jarodpeachey feel free to start in on this if you'd like. Did you have anything in mind for how this might look?

**Comment by spbyrne** [comment]
I'm thinking maybe a toast-like popup for this would be good.

**Comment by jarodpeachey** [comment]
Yeah, I think a toast popup would be pretty cool. Just slide it up from the bottom of the page. The color would be whatever the main theme color is.

![tinacms-alert](https://user-images.githubusercontent.com/46693952/72749644-9fc06a80-3b88-11ea-8ee1-590837e66add.jpg)

**This would be the error state**

![tinacms-alert-error](https://user-images.githubusercontent.com/46693952/72749757-e615c980-3b88-11ea-8677-98bb5c5a86a4.jpg)

**Comment by spbyrne** [comment]
Nice! Yeah, that looks great.

**Comment by jarodpeachey** [comment]
@spbyrne This is my first time contributing. How would I test the changes I make? I would imagine I would need to open a project that uses Tina and link it to my local package rather than the ones in the node_modules folder?

Thanks again.

**Comment by ncphillips** [comment]
@jarodpeachey you can use `packages/demo-gatsby` to test your changes.

Alternatively, you can follow the instructions in the README to try install an external site in the `packages/@testing`, but that might be harder. 

Those are the best options for now. We have some thoughts on how to make it even easier to get some testing sites setup. Hopefully I'll get a chance to look into that soon.

**Comment by jarodpeachey** [comment]
@ncphillips @spbyrne Sorry to ask such a simple question, but what package and file would I add the logic to display the message? Where is the submit request received?

Thanks.

**Comment by DirtyF** [comment]
🙏 Don't leave me hangin' on, give actionablle feedback, states what's happening and what should be my next move: `Failed to save changes, ???`

**Comment by ncphillips** [comment]
IIRC we’re hanging because there’s some weird design and implementation details to figure out. This is the first issue of this kind, we don’t have anything like a toast UI figured  decided upon

**Comment by kendallstrautman** [comment]
Can this be implemented with [Alerts](https://github.com/tinacms/tinacms/pull/822) now?

**Comment by ncphillips** [comment]
Yes it can. It could be added to the existing form hooks

**Comment by IronSean** [comment]
I just ran into this as well. It confused me when I hit save and nothing happened and the save buttons remained disabled.

It could be a toast in the screen center like the images above, but it could also be in the editor pane. For sidebar editing that's where I expect to be looking when I hit save and I might not see a toast notification elsewhere on the screen. For inline editing I see where that might not work.

Also, if the saving fails I think the save buttons should re-enable. Without looking I assume the form state removes it's dirty status after hitting save, but if the save fails the form is still technically dirty.

I also think my initial assumption was that save would re-enable itself after successfully saving too, and just remain disabled during the save operation. But that's a whole other UX discussion.

**Comment by ncphillips** [comment]
> Also, if the saving fails I think the save buttons should re-enable. Without looking I assume the form state removes it's dirty status after hitting save, but if the save fails the form is still technically dirty.

I believe this is a final-form behaviour. The logic being that if the form failed to save then the form is invalid and therefore pressing save again would be pointless.

> Also, dumping the error in the console might be nice for developers. I had to examine the network response to see what the error was when saving failed.

What was the error?

**Comment by IronSean** [comment]
Actually I hadn't even read that far, just saw there _was_ some structured json in the error response. But it's only
```json
{
  error: "Git Operation failed: Check the logs for more details",
  status: "failure"
}
```

And HTTP412, precondition failed. So writing that to the console wouldn't necessarily have been that helpful anyway. I'm still tracking down what the actual bug is.

**Comment by IronSean** [comment]
I tracked down my issue, I didn't have a remote named `origin`. I created a Feature Request here about supporting that in the future: https://github.com/tinacms/tinacms/issues/1199

Also, oddly when I did change my remote's name to `origin` then hit save in TinaCMS it committed everything I'd tried to save throughout the day, with the correct commit timestamps.
![image](https://user-images.githubusercontent.com/1960190/83450198-38b29c80-a42b-11ea-8f37-0f77035b8637.png)
