### ISSUE TITLE
Typescript type-checking fails when using DateTime field in RemarkCreatorPlugin

### ISSUE THREAD

**Issue by jsoulet** [tinacms/tinacms#604]
##  Description

In a Typescript Gatsby project, using RemarkCreatorPlugin to create a custom DateTime field makes the TS compilation fails because Field interface doesn't includes 

### Steps to reproduce

1. Create a Gatsby project that uses gatsby-typescript-plugin
2. Create a TinaCMS plugin component using RemarkCreatorPlugin that customize a date time field
```javascript
const CreateBlogPlugin = new RemarkCreatorPlugin({
  label: 'New Blog Post',
  filename:  form => ({  /* ... */  }),
  frontmatter: form => ({  /* ... */  }),
  fields: [
   /* ... */
    {
      name: 'date',
      component: 'date',
      dateFormat: 'YYYY-MM-DD',
      timeFormat: false,
      label: 'Date',
      defaultValue: new Date(),
      required: true,
    },
  ],
}) 
```
3. Run typescript type checking ```tsc --noEmit```

### Expected result

return without error

### Actual result

Script fails
```text
Type '{ name: string; component: string; dateFormat: string; timeFormat: boolean; label: string; defaultValue: Date; required: boolean; }' is not assignable to type 'Field'.
Object literal may only specify known properties, and 'dateFormat' does not exist in type 'Field'.
```
#### Tinacms Package Versions
```text
├─┬ gatsby-plugin-tinacms@0.1.17
│ ├─┬ @tinacms/core@0.5.1
│ └─┬ tinacms@0.11.0
│   ├─┬ @tinacms/fields@0.1.17
│   ├── @tinacms/icons@0.3.9
│   ├─┬ @tinacms/react-core@0.2.1
│   ├── @tinacms/styles@0.1.0
├─┬ gatsby-tinacms-git@0.2.15
│ ├─┬ @tinacms/api-git@0.5.0
│ ├── @tinacms/git-client@0.4.1
├─┬ gatsby-tinacms-remark@0.6.1
│ ├─┬ @tinacms/form-builder@0.2.9
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Firefox Browser edition v72 |
| os      | MacOS Catalina 10.15.1 |
| node    | v11.15.0 |
| npm     | 6.13.1 |

### How to fix?

Add `required?: string` to Field interface
 
Create a DateTimeField interface that extends Field
Add params to this interface (source: [Date Time field doc](https://tinacms.org/docs/fields/date#options))
```
export interface DateTimeField extends Field {
    dateFormat?: boolean | string
    timeFormat?: boolean | string
}
```

In CreateRemarkButtonOptions interface, uses
`fields: (Field | DateTimeField)[]`

I'm about to create a PR, and I'll be happy if you could review it

**Comment by ncphillips** [comment]
Thanks for the heads up @jsoulet!

I think in this case I would rather loosen the types on `CreateRemarkButtonOptions`.

Adding `DateTimeField` to the `CreateRemarkButtonOptions` interface solves the problem for dates, but I'm pretty sure it exists for all of the other field plugins as well. This means you'd end up with:

```
fields: (Field | DateTimeField | TextField | MarkdownField | GroupField .....)[]
```

Which is neither pretty nor practical. If you wanted to create your own custom FieldPlugin it would be difficult for you to extend that even further.

Last resort would be to switch it to `fields: any[]`. Preferably there's some way to say that it should have the things required on `Field`, but any other property can be added as well. 🤔

**Comment by jsoulet** [comment]
Hi @ncphillips,

Typescript seems to allow to specify that some extra properties can be added using ```[propName: string]: any;```
Source: [Excess Property Check](https://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks)

This might solve the case of custom FieldPlugin
I can suggest to add `dateFormat` and `timeFormat` of types `string | boolean` + `[propName: string]: any;`

**Comment by ncphillips** [comment]
That could be helpful. Maybe something like this:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/824015/72470552-5d2d1580-37b7-11ea-9b72-7ed0369122de.png">

**Comment by jsoulet** [comment]
Indeed 👍 

Do you still consider adding the extra `required`, `dateFormat`, `timeFormat` into Field interface definition ? That would be helpful for type-checking.

There might be some uncovered properties for some other FieldPlugins that .
I can precisely compare which ones and list them

**Comment by ncphillips** [comment]
Those are not universal fields, so I would not add them to the `Field` interface. 

I would lean towards being a little loose here. It's a difficult to balance between type-completeness and simplicity. 

My experience is that creating complex types to try and provide type-complete code is difficult. Usually the resulting types are quite fragile and end up causing more pain then they prevent.

**Comment by jsoulet** [comment]
I get it.
Do you want a PR for the piece of code you suggested or I let you fix the issue ?

**Comment by ncphillips** [comment]
A PR would be greatly appreciated! 😍
