### ISSUE TITLE
Add styles for Markdown inline editing

### ISSUE THREAD

**Issue by nibtime** [tinacms/tinacms#615]
## Summary

Currently, the [docs for inline editing](https://tinacms.org/docs/gatsby/inline-editing/) suggest to use the plain `Wysiwyg` component. This component is not styled yet. But there are styles actually available in the code base ([on MarkdownField](https://github.com/tinacms/tinacms/blob/f36579334ad16164031f4b7dfe487954cf007a8b/packages/tinacms/src/plugins/fields/MarkdownFieldPlugin.tsx))

### Basic example
What worked for me, was simply copying the styles from MarkdownField and creating a component `StyledWysiwym` to use in a custom component `MarkdownWysiwym`, that I use whenever I want to render html from Markdown

```typescript
export const MarkdownWysiwym: React.FC<MarkdownWysiwymProps> = ({ html, isEditing, setIsEditing, isActive }) => {
  const onClick = () => setIsEditing(p => !p)

  const editButton = isActive && (
    <button className={`button is-info is-outlined m-bottom-default`} onClick={onClick}>
      {isEditing ? "Preview Markdown Content" : "Edit Markdown Content"}
    </button>
  )

  return (
    <>
      {editButton}
      <TinaField name="rawMarkdownBody" Component={StyledWysiwym}>
        {/* tslint:disable-next-line: react-no-dangerous-html */}
        <div className={`content`} dangerouslySetInnerHTML={{ __html: html }} />
      </TinaField>
    </>
  )
}
```

That works fine, however the editing menu keeps detaching from the editor towards the top when scrolling. I use Bulma and worked around it, by wrapping the component into a dedicated editing container (`style={{ position: "static" }}` does the trick), Bulma classes are just for a nicer layout while editing.
```typescript
  <Layout>
    {!isEditing ? (
      <Content>
        <MarkdownWysiwym
          isActive={true}
          html={data.markdownRemark.html}
          isEditing={isEditing}
          setIsEditing={setIsEditing}
        />
      </Content>
    ) : (
      <section className="container section" style={{ position: "static" }}>
        <MarkdownWysiwym
          isActive={true}
          html={data.markdownRemark.html}
          isEditing={isEditing}
          setIsEditing={setIsEditing}
        />
      </section>
    )}
  </Layout>
```

### Motivation
Without Styles it's not really Wysiwym 😉 . Also, I think editing Markdown bodies in the sidebar is not optimal, as the space is too limited. Plus, the code is basically already there.

**Comment by spbyrne** [comment]
When you say the Wysiwyg isn't styled yet, do you mean the editor toolbar, or the content of the editor? If it's the latter that's intentional as it's meant to leverage your page styles. That way when you enter edit mode your content isn't suddenly styled differently.

**Comment by nibtime** [comment]
@spbyrne 
Ah, you're right! It's because Bulma seems to only apply styles to html elements wrapped in a content container. If I apply the content container around `TinaField` instead of the child inside, the content is styled. 

However in doing so, the editing menu detaches again to the top of the page when scrolling, which didn't happen with my solution before.

**Comment by spbyrne** [comment]
Ah, gotcha! I'm glad you got the styles working 👍 

I'm not sure what the detaching menu issue could be. We've merged in a 'sticky' menu for the editor but I don't believe that's published yet. Would you mind posting a screenshot of the issue?

**Comment by spbyrne** [comment]
I'm going to close this issue since it relates to styling for the inline editor, but I'd like to help troubleshoot your menu detaching issue so please open a new issue with details on that.
