### ISSUE TITLE
Allow changing Save and Reset button text

### ISSUE THREAD

**Issue by sijad** [tinacms/tinacms#620]
## Summary

currently it's not possible to change Save and Reset button text, this can be useful for translating.

### Motivation

I need this to change Save button text based my website language.

**Comment by weibenfalk** [comment]
I tried this implementation and got it to work by setting the text in the options when initializing the plugin (in Gatsby) but @ncphillips maybe this is a bigger change that has to be made? Some kind of localization ... There's more buttons than Save and Reset that need to be customizable. For example cancel, edit and preview ...

**Comment by ncphillips** [comment]
Any API that let's you optionally override the text would be good. A guiding principle for TinaCMS is [inversion of control](https://kentcdodds.com/blog/inversion-of-control). For that reason I would not want the idea localization to be a part of `tinacms`. Instead the solution would be more abstract. I'll think on this a bit.

**Comment by weibenfalk** [comment]
Thanks @ncphillips  ... I get it. I played with the below idea to set the text for the buttons where the plugin is initialized in Gatsby config: 

```
options: {
        sidebar: {
          hidden: process.env.NODE_ENV === "production",
          position: "displace",
          buttons: {
            save: "Spara",  // Swedish for save
            reset: "Återställ", // Swedish for reset
          },
        },
}
```

**Comment by ncphillips** [comment]
That's a nice API 👍 

I'm more concerned about the mechanism of actually making the change.

**Comment by weibenfalk** [comment]
Thanks! I see your point there ... it's working here locally. So just shout if it's something you would like to try out.

**Comment by ncphillips** [comment]
Maybe open a draft PR? I would like to see what approach you took.

**Comment by weibenfalk** [comment]
I've created a draft PR now ... I've just started trying things out so it can be a little bit unstructured yet. But it's working at least ...
