### ISSUE TITLE
Support Docusaurus (v2)

### ISSUE THREAD

**Issue by jsjoeio** [tinacms/tinacms#622]
## Summary

Support TinaCMS usage with [Docusaurus](https://v2.docusaurus.io/)

### Basic example

Supporting the most basic Docusaurus site 
```bash
npx @docusaurus/init@next init my-website classic
```
...add Tina

### Motivation

Docusaurus is growing in popularity as a solution for docs. It would be wonderful to support it as well!

P.S. - I would be interested in contributing to help make this happen!

**Comment by ncphillips** [comment]
That's very interesting. Since it's React + Markdown based, I suspect that most of the heavy lifting is already done. Definitely something worth checking out.

**Comment by ncphillips** [comment]
Yes. We have everything we need, it's just a question of figuring out how to use what we have in the Docusaurus framework. Here's what needs to be figured out:

- Add Tina component to the app. This needs to be done as high up as possible so it's never removed while navigating. In `gatsby-plugin-tinacms` we use the [`wrapRootElement`](https://github.com/tinacms/tinacms/blob/master/packages/gatsby-plugin-tinacms/gatsby-browser.tsx) in the `gatsby-browser.js` file to do this.
- We need to start start up the `@tinacms/api-git` server so we can write to disk. The `gatsby-tinacms-git` plugin does this using [`onCreateDevServer`](https://github.com/tinacms/tinacms/blob/master/packages/gatsby-tinacms-git/gatsby-node.ts). With Next.js sites it is done more [manually](https://tinacms.org/docs/nextjs/adding-backends)
- Add forms to pages would consist of several things:
  - For the Blog, this would be done by overriding the [BlogPostPage](https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic/src/theme/BlogPostPage) from your theme and calling the `useLocalForm`. You could look to [useRemarkForm](https://github.com/tinacms/tinacms/blob/master/packages/gatsby-tinacms-remark/src/useRemarkForm.tsx) for inspiration in setting up that form. 
  - For that form to be usable, we need to add metadata to the props of `BlogPostPage`. Specifically, we need the equivalents of `fileRelativePath`, `rawMarkdownBody`, and `rawFrontmatter`.

**Comment by jsjoeio** [comment]
Awesome! Thanks @ncphillips for adding those specific details. This should be enough context for myself (or anyone else) to get started on it.

**Comment by mitchmac** [comment]
I'm going to close this issue because the maintainers don't have this planned for the foreseeable future. We can revisit this issue if anyone has interest in moving it along.

**Comment by anirudhmurali** [comment]
Would love to see this support added!

**Comment by Abijith10** [comment]
Is Docusaurus support coming anytime soon?
