### ISSUE TITLE
FieldPlugins for text should default to empty string, instead of undefined

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#632]
## Summary

By default, a cleared text field's value is `undefined`. Instead it should be an empty string: `''`.

This applies to several plugins:

- [ ] TextFieldPlugin
- [ ] TextareaFieldPlugin
- [ ] SelectFieldPlugin
- [ ] MarkdownFieldPlugin
- [ ] ColorFieldPlugin
- [ ] ImageFieldPlugin

### Basic example

Currently users must add a `parse` function on their text field definitions to get empty strings:

```js
{
  name: "frontmatter.title",
  component: "text",
  parse: value => value || '',
}
```

This should not be required.

### Motivation

The current behavior is unexpected for most use cases. This assertion is based off of #630 as well as our experience with Forestry.io

### Solution

Add the `parse` function above to the `TextFieldPlugin` directly. 

Look at the [DateFieldPlugin](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/plugins/fields/DateFieldPlugin.tsx#L76-L81) for reference

**Comment by molebox** [comment]
Could i take a pop at this?

**Comment by ncphillips** [comment]
Please do!

**Comment by molebox** [comment]
Sweet! I havent looked at the code base before but will give it a go :)
