### ISSUE TITLE
Table cell markdown translator to support rich styling.

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#634]
## Summary
Wysiwym support rich text bold/italic etc in table cells. But markdown translator needs to be fixed to support that as well.

Currently it is not possible to have multiple paragraphs/blocks in table cell, it supports only inline content. If markdown supports multiple blocks in table cell we can add that also.

**Comment by ncphillips** [comment]
### Example

| Bold | Italic |
| --- | --- |
| **Text** | *Text* |

### Source
```markdown
| Bold | Italic |
| --- | --- |
| **Text** | *Text* |
```

**Comment by DirtyF** [comment]
It should also support link (can be done in a separate PR)

| header | header |
|:------:|:------:|
|  **cell**  |  [link](https://tinacms.org)  |
|  _cell_  |  [link](https://tinacms.org)  |

source: 

```markdown
| header | header |
|:------:|:------:|
|  **cell**  |  [link](https://tinacms.org)  |
|  _cell_  |  [link](https://tinacms.org)  |
```

**Comment by jpuri** [comment]
https://github.com/tinacms/tinacms/pull/664

**Comment by DirtyF** [comment]
@jpuri Let's use [GitHub keywords](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords) and mention in PR description `fix` or `close`
