### ISSUE TITLE
Support table columns alignment

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#641]
## Summary

Allow users to choose how to align table columns: left, center, right
### Basic example

| header | header | header |
|--------|:------:|-------:|
| cell   |  cell  |   cell |
| cell   |  cell  |   cell |
| cell   |  cell  |   cell |

Resources: https://www.tablesgenerator.com/markdown_tables

**Comment by jpuri** [comment]
![Screenshot 2020-01-27 at 4 14 49 PM](https://user-images.githubusercontent.com/2182307/73168608-28f31680-4120-11ea-936b-9caffa557d52.png)

Hey @spbyrne : we can create a floating toolbar like above and add more table related options to it.
