### ISSUE TITLE
Add Remove Option to WYSIWYG Header Dropdown

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#643]
## Summary

Add an option to the heading wysiwyg ddl to remove the current heading and revert the selected text back to a regular paragraph.

### Motivation

Right now once you've created a heading it's difficult to revert it back to regular text.

**Comment by ncphillips** [comment]
Good idea. 

There's currently three to do it that aren't terribly discoverable:

* **Input Rule:** Press backspace at the start of the heading
* **Menu:** Select the heading and then click the same heading option from the menu
* **Keyboard Shortcut:** `CMD+OPTION+N`, where `N` is the heading size.

**Comment by spbyrne** [comment]
Interesting. Solution #2 there would be more obvious if the heading was highlighted when you opened the menu. It would look more like a toggle. 

Maybe instead of a 'remove heading' option in the DDL, we could add a 'clear formatting' button that's a little more general purpose + an active heading style to the DDL, so the user has 2 clear paths.

**Comment by ncphillips** [comment]
I believe the prosemirror examples editors have those kinds of buttons.
