### ISSUE TITLE
Update 'Form Setup Guide' URL for Emtpy Sidebar

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#656]
## Summary

When the sidebar has no forms registered, it prompts folks to checkout the 'Form Setup Guide'. This guide currently links to the [Markdown with Gatsby](https://tinacms.org/docs/gatsby/markdown/#creating-remark-forms) docs. Let's link to a more open-ended [starting point](https://tinacms.org/docs/getting-started/introduction#get-started).

### Motivation

Guide the setup experience to be inclusive of Next.js & JSON-powered sites.

**Comment by DirtyF** [comment]
Hint: https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/components/FormView.tsx#L272

**Comment by jonmiller0** [comment]
updated link and added PR

**Comment by molebox** [comment]
Can i take this?

**Comment by marklawlor** [comment]
I believe this issue has regressed in these versions

"@tinacms/api-git": "^0.7.0",
"@tinacms/git-client": "^0.6.0",
"next": "^9.3.0",
"next-tinacms-json": "^0.3.5",
"tinacms": "^0.16.0"
"typescript": "^3.8.3"

The links above no longer work, here is a permalink to
