### ISSUE TITLE
Redo - undo after adding table column / row is not working

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#663]
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What actually happened?

#### Tinacms Package Versions

```text

```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by DirtyF** [comment]
✅ Test is passing on Safari 13/macOS on `current table_translator_fix`branch:

1. Select a column
2. Click delete icon
3. CTRL-Z to undo: revert delete column
3. SHIFT_CTRL-Z to redo: column is deleted.

**Comment by DirtyF** [comment]
@jpuri closing as this looks fixed now.
