### ISSUE TITLE
ability hide global settings button

### ISSUE THREAD

**Issue by sijad** [tinacms/tinacms#680]
## Summary

global settings form always is visible even if there's no global form registered and after clicking on it an empty drawer shows up. it should be possible to hide global settings button to prevent confusions.

![2020-01-27-14:35:29-screenshot](https://user-images.githubusercontent.com/7693001/73169881-013a8900-40f5-11ea-97ab-f0f8d5891fc1.png)

### Motivation

when there's not any global form or settings, its button still showing up and it might confuse some users.

**Comment by ncphillips** [comment]
I have two ideas:

* Hide the icon if there's no items there
* Still show it, but have an empty state that links to docs explaining what that menu is

Maybe @spbyrne has other ideas?

**Comment by spbyrne** [comment]
Hiding it if there's no items seems like the best option to me.

**Comment by sijad** [comment]
can I do this?

**Comment by ncphillips** [comment]
Absolutely. The [Sidebar](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/components/sidebar/Sidebar.tsx#L50-L55) component in the `tinacms` package is what you're looking for. 

You would want to not render it or the [MenuPanel](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/components/sidebar/Sidebar.tsx#L60-L80) when `cms.screens.all().length === 0`

Thanks 😄
