### ISSUE TITLE
react-tinacms-editor: handle inline blocks

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#682]
Currently the editor button only toggle code blocks, not inline code.

* [ ] Toggle the `code` mark for a partial line selection

It would be awesome if you could also toggle inline code blocks à la GitHub when you select a word for instance and hit the code button.  Unless you select multiple lines, the toggle should insert inline code.

Current workaround:  type Markdown in the editor to insert  \`inline code\`

**Comment by jpuri** [comment]
Hi @DirtyF ,

This seems to work already:

![Screenshot 2020-02-28 at 6 09 17 PM](https://user-images.githubusercontent.com/2182307/75549367-81863e00-5a55-11ea-81e7-a8dc6dfe515f.png)

**Comment by DirtyF** [comment]
I didn't manage to test properly, we don't really support inline-code formatting at the moment.

Will update this issue description, it's low priority at the moment.

**Comment by ncphillips** [comment]
I’m not quite sure what this issue is about. The wysiwyg already supports both inline code and code blocks, so I’m not sure what the problem is. The title and description will have to be further clarified.

**Comment by DirtyF** [comment]
Code button already exists but only supports setting code blocks and it's not reversible, except with undo.

![tina-code-button](https://user-images.githubusercontent.com/103008/77365391-58a45080-6d56-11ea-9007-189148fb86cb.gif)


Ideally, we can use a single button to handle inline-code by default, and when the selection is a block, make it a togglable code block like GitHub does:
![code-button](https://user-images.githubusercontent.com/103008/77365089-c7cd7500-6d55-11ea-9268-5536bfcb68d0.gif)
