### ISSUE TITLE
Access image settings

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#688]
```gherkin
Given I have inserted an image in the Markdown editor
When I click on the image
Then Image is in select state
And I can access image settings
```

We don't want to show alt and title by default when you click on a media, we'll have to diaply an icon that conveys that you can enter those.

The reason for this, is that we will have other icons to display when you click on an image, like a link icon for instance to add/edit a link on a media.

**Comment by DirtyF** [comment]
Image controls on Dropbox Paper: 
![paper-image-select](https://user-images.githubusercontent.com/103008/73261835-2d293d80-41cd-11ea-9741-79ddfa0ed77c.jpg)

Image controls in Notion.so:
<img width="802" alt="notion-image-select" src="https://user-images.githubusercontent.com/103008/73262100-b9d3fb80-41cd-11ea-8907-f696b8b01a03.png">

Notion.so image menu: 
<img width="272" alt="notion-image-menu" src="https://user-images.githubusercontent.com/103008/73262220-facc1000-41cd-11ea-8339-b5798f5c3538.png">

@scottgallant What image settings should we start with?

**Comment by ncphillips** [comment]
Check the markdown spec for what options should be accessible.

Could also add “link” but I think that’s complex enough to warrant a separate issue.

**Comment by DirtyF** [comment]
Core Markdown attributes would be alt and title.

**Comment by kendallstrautman** [comment]
Closing as this seems [done](https://github.com/tinacms/tinacms/projects/5#card-32257588).
