### ISSUE TITLE
Focus on URL field when inserting links

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#689]
```gherkin
Given I select something in the editor
When I click on the link icon
Then URL field is focused by default
```

### Current
<img width="327" alt="link-modal-current" src="https://user-images.githubusercontent.com/103008/73262764-47641b00-41cf-11ea-992d-d43b09e40d77.png">

### Expected
<img width="277" alt="link-modal-url-focus" src="https://user-images.githubusercontent.com/103008/73262763-47641b00-41cf-11ea-8559-82cf2ad2092d.png">

On existing links, the focus is correctly set on the URL field by default.

**Comment by ncphillips** [comment]
The focus is also correct if you use the key map. 


The problem is caused by the fact the menu is outside of the wysiwyg content area. Clicking the button shifts focus and messes up the refocus on the input

**Comment by DirtyF** [comment]
Yes, hitting CMD+K on macOS Safari is OK, same when you paste an URL in a cell. Still happens now that modal is correctly positioned.
