### ISSUE TITLE
Customize editor toolbar

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#690]
As a developer
I can customize the icons available to editors for a Markdown field

### Example

As a developer 
in order to build blocks based page builder with a Markdown block and a Heading.
I am able to turn off `h1` and `h2`headings in the Markdown editor

**Comment by DirtyF** [comment]
This should be further shaped up and scoped: 

What settings can we set for editors?
Global or local settings?

**Comment by DirtyF** [comment]
@scottgallant feel free to provide real user scenario to illustrate this feature request.

**Comment by ncphillips** [comment]
I have a use case. I want to build blocks based page builder with a Markdown block and a Heading. I would want to be able to turn off h1 and maybe h2 headings in tthe markdown

**Comment by ncphillips** [comment]
Also, from a technical perspective start with local only at first. I.e. what props to pass the Wysiwyg component to configure the menu programmatically each time. 

Global would need more thinking that would technically be out of scope of wysiwyg

**Comment by webtwitter** [comment]
I'm also interested of this. Can we chose what to show/hide on toolbar?
