### ISSUE TITLE
Delete image after selection only

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#691]
Some editors like https://paper.dropbox.com/ do not delete image on the first backspace stroke, but on the second one, to make sure the user actually wanted to delete the image. It's good user experience to prevent accidental deletion.

On Tina, image is currently selected on click or when using the right arrow, but on backspace, the image don’t get selected

https://www.loom.com/share/8f1677674f8c426c85c374cb6fb42fba

Would be nice to select the image on the first backspace keystroke, like we do when using the right arrow.

**Comment by jpuri** [comment]
Hey @DirtyF : in wysiwyg this is expected behaviour from backspace to delete content and not to select node. Arrow keys are used to select node.

I do not think this is issue.

**Comment by DirtyF** [comment]
It's a nice to have. to prevent accidental deletion. 
Some editors like https://paper.dropbox.com/ do not delete image on the first backspace stroke, but on the _second_ one, to make sure the user actually wanted to delete the image.

@scottgallant asked for this initially and I agree, again nice to have not a priority.
