### ISSUE TITLE
Undo/redo actions in editor

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#708]
Given I'm using the WYSIWTM editor
When I click undo, then it does undo the latest action 
When I click redo, then it does redo the latest action 

Things to watch for:
- undo and redo icons are visible in the editor toolbar
 - icon states (e.g. when no action to undo, icon is not active)
 - Keyboard shortcuts are also working (e.g. CMD+Z / SHIFT+CMD+Z on macOS) in Firefox, Safari, Chrome

How many actions can you undo? (10? 20? other?)

**Comment by ncphillips** [comment]
IIRC keyboard shortcuts already work. I believe you could undo indefinitely, at least to the point where the browser loaded.

**Comment by ncphillips** [comment]
> **SHIT**+CMD+Z

This seems unorthodox but I like it

**Comment by spbyrne** [comment]
Right now the WYSIWYG toolbar is about at capacity for how many actions it can support when in the sidebar. If we're going to add more controls it will require some tweaking. 

Possible solutions:
1. Wrap additional actions to another line.
2. Truncate the list with a 'more' button to reveal other actions.
3. Overflow the list in a way that can be scrolled.

I can confirm keyboard undo/redo works great.

**Comment by DirtyF** [comment]
4. Reduce icon width (67px at the moment, GitHub icons are 22px wide in comparison)
5. Group similar actions in menus as shown on https://prosemirror.net/examples/markdown/

**Comment by spbyrne** [comment]
I'm not sure where you're getting that icon width from. The buttons expand to fill the toolbar space, but the icons themselves are only 20px wide.

**Comment by DirtyF** [comment]
Sorry, you're right I was thinking about the button width 😊, so no problem to add more icons for now?
