### ISSUE TITLE
Improve WYSIWYM icons

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#709]
A few design tasks related to the toolbar and table icons:

 - [x] table alignment icons (#740)
 - [ ] Icon state whether a column is aligned or not (e.g. if a column is already centered, the center icon is seen as _active_, if I click on _left_ then, left icon moved to _active_ state. 
- [x] undo and redo icons (#708)
- [ ] insert media icons
- [ ] toolbar responsiveness? How should it behave in the sidebar? Wrap?

**Comment by spbyrne** [comment]
Hey @DirtyF can we close this and if needed create individual issues for the remaining items?
