### ISSUE TITLE
Avoid warnings on bootstrapping

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#719]
### Steps to reproduce

`npm run bs`

### Expected result

No warnings about dependencies

### Actual result

```
lerna WARN EHOIST_ROOT_VERSION The repository root depends on @testing-library/react@^9.3.2, which differs from the more common @testing-library/react@^9.1.4.
lerna WARN EHOIST_PKG_VERSION "react-dismissible" package depends on @testing-library/react@^9.1.4, which differs from the hoisted @testing-library/react@^9.3.2.
lerna WARN EHOIST_PKG_VERSION "@tinacms/react-core" package depends on @types/jest@^24.0.23, which differs from the hoisted @types/jest@^24.0.15.
lerna WARN EHOIST_PKG_VERSION "react-tinacms-blocks" package depends on @types/jest@^24.0.23, which differs from the hoisted @types/jest@^24.0.15.
lerna WARN EHOIST_PKG_VERSION "@tinacms/api-git" package depends on @types/node@^12.7.11, which differs from the hoisted @types/node@12.6.8.
```

### Environment

| Tool    | Version |
| ------- | ------- |
| tinacms |     0.12.1    |

**Comment by ncphillips** [comment]
IIRC this was solved by your PR @DirtyF ?

**Comment by DirtyF** [comment]
Just a remaining warning, I'll fix:

lerna WARN EHOIST_ROOT_VERSION The repository root depends on @types/jest@^24.0.25, which differs from the more common @types/jest@^24.0.23.
lerna WARN EHOIST_PKG_VERSION "react-tinacms-inline" package depends on @types/jest@^24.0.23, which differs from the hoisted @types/jest@^24.0.25.
