### ISSUE TITLE
WYSIWYG: Link Toolbar Button Scrolls Page

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#735]
## Description

When you'd like to edit/add a link and click the link toolbar button when a text or a link is selected, the page jumps and the modal isn't visible. When you do scroll to the modal, it's open but the position is slightly too high (looks like it's pointing above the text, not at it)

### Steps to reproduce

Run storybook, highlight some text and click the link option in the wysiwyg toolbar.

### Expected result

The link modal should pop up, no scrolling.

### Actual result

The link modal pops up, but is not visible as the page jumps up.

![WYSIWYG Link Issue 1](https://user-images.githubusercontent.com/5075484/74248119-801aee80-4cbd-11ea-8c28-3ad08d1d3c62.gif)

**Comment by PaulBunker** [comment]
I'd like to expand on this issue. The page jump happens with any user input. In the gif below I press enter and then scroll down and press h

![Feb-23-2020 11-11-58](https://user-images.githubusercontent.com/1537408/75110351-75e9e000-562d-11ea-9959-0ea8824b3db8.gif)

I spent a good few hours investigating but didn't get anywhere useful.  There are a lot of WYSIWYM issues open but I believe this one to be Very high priority as it renders the component unusable.

Side note: I'll try and picking up some low hanging fruit to get to know the code for the editor better. hopefully I can be more helpful in the future.
