### ISSUE TITLE
Strikethrough ~~Like this.~~ crashes wysiwyg

### ISSUE THREAD

**Issue by PaulBunker** [tinacms/tinacms#745]
## Description
wysiwyg crashes if you add the following line in your markdown:

`Strikethrough uses two tildes. ~~Scratch this.~~`

### Steps to reproduce

create a markdown file with the following contents
```
Strikethrough uses two tildes. ~~Scratch this.~~
```
open the page and click edit (using inline editing and the wysiwyg)

### Expected result

you should be able to edit the page

### Actual result

What actually happened? The page crashes giving many errors. including the following.

```ErrorEvent {isTrusted: true, message: "Uncaught Error: Token type `s_open` not supported by Markdown parser", filename: "http://localhost:8000/commons.js", lineno: 6853, colno: 71000, …} 
    in AppContainer (created by HotExportedComponent)
    in HotExportedComponent (created by PageRenderer)
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Context.Consumer (created by Location)
    in Location (at root.js:118)
    in Root (at root.js:126)```

#### Tinacms Package Versions
```text
├─┬ gatsby-plugin-tinacms@0.1.21
│ └─┬ tinacms@0.12.0
│   ├── @tinacms/core@0.7.0
│   ├─┬ @tinacms/fields@0.3.1
│   ├─┬ @tinacms/form-builder@0.2.13
│   ├─┬ @tinacms/forms@0.1.2
│   ├── @tinacms/icons@0.4.1
│   ├─┬ @tinacms/react-core@0.2.5
│   ├── @tinacms/styles@0.1.1
├─┬ gatsby-tinacms-git@0.2.18
│ ├─┬ @tinacms/api-git@0.5.4
│ └── @tinacms/git-client@0.4.1
```

**Comment by PaulBunker** [comment]
Adding a gif to prove I'm not lying :)

![Feb-23-2020 11-11-58](https://user-images.githubusercontent.com/1537408/75110487-1096ee80-562f-11ea-8994-6757b2d00bd8.gif)

**Comment by PaulBunker** [comment]
Gif for clarity

![Feb-23-2020 11-28-34](https://user-images.githubusercontent.com/1537408/75110549-b64a5d80-562f-11ea-9796-daac488e6b9d.gif)

**Comment by ncphillips** [comment]
@PaulBunker I'm not able to reproduce this in `demo-gatsby` or `demo-next`. Could you check if it has been resolved?

**Comment by DirtyF** [comment]
I did a quick test and I get a blank screen when adding `Strikethrough uses two tildes. ~~Scratch this.~~` in a post on Gatsby demo in Safari... can't even open the developers tools.

**Comment by PaulBunker** [comment]
I think this is just the screen of death issue but I happened to get it adding 'tildes'  I reproduced using the letter 'h' a few times just now.

**Comment by DirtyF** [comment]
In my case, it was OK, and it went AWOL just when adding the double tildes. Trying to get rid of this screen of death so see if tildes are really responsible for this.

**Comment by PaulBunker** [comment]
Closing for now could be a different cause
