### ISSUE TITLE
Spelling error in blocks empty-state text 

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#756]
## Description

Empty state should say "There are no items"

<img width="330" alt="Screen Shot 2020-02-14 at 9 36 11 AM" src="https://user-images.githubusercontent.com/776019/74554151-b8b10700-4f0d-11ea-9514-e7cf40eeadae.png">

### Steps to reproduce

remove all blocks

### Expected result

"Are"... not "is" or " ain't" :)

**Comment by ncphillips** [comment]
> There ain't no items in hur

**Comment by zivkaziv** [comment]
Can I fix it?
