### ISSUE TITLE
gatsby-plugin-tinacms not building

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#767]
## Description

Lerna build error on current `master` branch

### Steps to reproduce

```
git pull
npm run hard-rest
```

### Expected result

No build error

### Actual result

```
Building Package: gatsby-tinacms-remark@0.7.2
lerna ERR! npm run build exited 2 in 'gatsby-plugin-tinacms'
lerna ERR! npm run build stdout:

> gatsby-plugin-tinacms@0.1.23 build /Users/frank/tina/tinacms/packages/gatsby-plugin-tinacms
> tsc

options.d.ts(18,10): error TS2305: Module '"../../../../../../Users/frank/tina/tinacms/packages/tinacms/build"' has no exported member 'TinaCMSConfig'.
```

#### Tinacms Package Versions

```text
npm ls | grep tinacms | grep -v deduped
npm ERR! peer dep missing: eslint-plugin-flowtype@2.x, required by eslint-config-react-app@4.0.1
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| os      |    macOS 10.15.3     |
| node    |    12.6.0     |
| npm     |      6.13.4   |

**Comment by ncphillips** [comment]
The CI is building and the it's working for me locally with `node@12.6.0` and `npm@6.9.0`. I'll try with latest `npm`.

That error would usually come up if the packages aren't linked or if the dependency wasn't built. Try running this a

```
lerna run dev --stream --scope tinacms
```

Then 

```
lerna run dev --stream --scope gastby-plugin-tinacms
```

**Comment by DirtyF** [comment]
Deleted the whole repo, cloned it and start installing from scratch again, and now it's building 🤷‍♂
