### ISSUE TITLE
Single Forms Not Rendered as Expected in Sidebar

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#778]
## Description

When you only have a single form for a page,  the form list shouldn't be rendered.

### Steps to reproduce

On the TinaCMS.org site, we only have one form for the homepage, but instead of rendering by default the sidebar displays a form list of one.

### Expected result

There should be no form list, only a form.

### Actual result

You get a form list with one option.

**Comment by kendallstrautman** [comment]
Implemented by #781
