### ISSUE TITLE
Create Content Plugin Button and Menu Placement

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tinacms#780]
## Description

When there's no global forms registered with Tina the hamburger menu doesn't get rendered, so the sidebar header flex justification places the create content menu on the left side, cutting off the dropdown when opened.

### Steps to reproduce

On the `master` branch, run `demo-gatsby`. Open the sidebar on a blog post details page to view the create content button issue.

On the homepage, there's a global Tina form so the placement issue won't be visible. You can change this by using `useLocalForm` inside of `packages/demo-gatsby/src/pages/index.js` instead of `useGlobalForm`. Read more [about global vs. local forms here](https://tinacms.org/docs/concepts/forms/).

### Expected result

The create content button should be placed in the same position (right side of the sidebar header).

### Actual result

<img width="209" alt="Screen Shot 2020-02-20 at 1 47 23 PM" src="https://user-images.githubusercontent.com/5075484/74963102-890b6e80-53e7-11ea-841c-577b9ec697e2.png">

### Proposed Solution

Either render an empty `<span>` in place of the hamburger menu icon to hide it, or change the flex `justify-content` property on the sidebar header component.

**Comment by maciekgrzybek** [comment]
I'll fix this one :)

**Comment by maciekgrzybek** [comment]
PR ready to review here - https://github.com/tinacms/tinacms/pull/804
