### ISSUE TITLE
MDX: Improve editing experience for MDX files

### ISSUE THREAD

**Issue by PaulBunker** [tinacms/tinacms#793]
# Motivation

As a content creator I would like the editing of MDX files to be cleaner and more intuitive so that I can focus on the content I am creating

Editing MDX files can be a bit frustrating in the current editing environment. Below I have tried to explain some thoughts about this problem to open a discussion on the topic.

## Issues

**MDX/HTML alignment** I've added some images below to show the raw file in a code editor vs in the wysiwym. Also the reformatting that happens when you start editing.
<img width="395" alt="Screenshot 2020-02-23 at 09 50 38" src="https://user-images.githubusercontent.com/1537408/75109569-e9d3ba80-5624-11ea-86a3-878a2c8ce03e.png">
<img width="411" alt="Screenshot 2020-02-23 at 09 51 18" src="https://user-images.githubusercontent.com/1537408/75109573-f0623200-5624-11ea-8708-69129c98ff25.png">
![Feb-23-2020 10-17-36](https://user-images.githubusercontent.com/1537408/75109674-cbba8a00-5625-11ea-8573-baf718cceb97.gif)

### Other issues I consider to be related

 - [Code block syntax](https://github.com/tinacms/tinacms/issues/794): use back-ticks instead of indentation
 - [Switch to raw mode](https://github.com/tinacms/tinacms/issues/626) for those who are more comfortable with this type of editing and also quickly fix niggles like cursor placement that you can run into in the wysiwym
 - [Backslash for new line](https://github.com/tinacms/tinacms/issues/795) - backslash is a visible character wysiwym currently uses double space

## Ideas for an improved MDX editing environment

Define components and their props upfront so they can be added with plus symbol like blocks

  - **Inline components**:
  User clicks the add 'block' plus symbol, chooses `Icon`
  The `<Icon name=""/>` (or <Icon /> with the props obfuscated ) component is added to the prose as inline code with an interface for choosing the props. This could also be some other visual indicator of an inline block.
  In this case a menu like the one for links but with a dropdown to pick the image/image-name used for the icon.

  - **Block level components**:
  User clicks the add 'block' plus symbol, chooses Icon
  A new block is added in the sidebar and the 'code' is added to the wsym but rendered as code perhaps with a background colour.
  The user can then use the sidebar to customise the props

  - **Block level components that accept children**:
  User clicks the add 'block' plus symbol, chooses Icon
  A new block is added in the sidebar and the 'code' is added to the wsym but rendered as code perhaps with a background colour.
  There is a space between the opening and closing tags where the user can add content.
  _can we do blocks inside blocks or just markdown? It would be nice to add image components inline icons inside these types of blocks_

## Pie in the sky?

 - Define some components that would render in the editor and clickable to change the props. This would certainly not be possible for all components but for small inline components i.e. <Icon name="trash" /> it could be nice to have them actually render and have an interface like editing links with a pop up to change the props, as mentioned above. A select in this case with the available icon names.

 - Drag and drop from a list of components into the editor

Thanks for taking the time to read my thoughts 🦙

`@-ing` Some people that might be interested:
 👋🏼@jsjoeio @ncphillips @kendallstrautman @scottgallant  👋🏼

**Comment by ncphillips** [comment]
This is something we’ve discussed at length. We should get a summary of our thoughts up for sure. In short, it’s a huge undertaking and would require at least a new [Translator](https://github.com/tinacms/tinacms/tree/master/packages/%40tinacms/fields/src/Wysiwyg/Translator/MarkdownTranslator) or maybe even an entirely new editor. It’s not out of the question though.

**Comment by jsjoeio** [comment]
Wow. I didn't realize how much could go into this 😮 Thanks for taking the time to write all this up, Paul. Seems like there is a lot of work to be done. Once @ncphillips shares the thoughts they have, maybe we can scope out the work into small, manageable chunks.

**Comment by PaulBunker** [comment]
I think it could be worth writing a custom transformer plugin for gatsby so the page doesn't crash when editing, one where if there are errors the 'body' of the node contains the error message instead of blowing up

**Comment by ncphillips** [comment]
What about a PR to [gatsby-plugin-mdx](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#readme)?

**Comment by PaulBunker** [comment]
Yes that’s a good point! Your comment just made my life much easier. I’m working on a PR for gatsby now 🤞they like the idea.

**Comment by AGMETEOR** [comment]
Having issues here https://github.com/tinacms/tinacms/issues/1098

**Comment by jamespohalloran** [comment]
MDX is now supported! https://tina.io/docs/editing/mdx/
