### ISSUE TITLE
WYSIWYM: Change markdown syntax for code blocks

### ISSUE THREAD

**Issue by PaulBunker** [tinacms/tinacms#794]
# Motivation

As a developer sometimes I have to edit markdown created by the wysiwym. I would like the syntax to be more inline with my preferred syntax choice

## Issue

Most of us developers are used to using three "backtics" for code blocks the wysiwym uses indentation which differs from the syntax choice used in github and to my knowlege most other places.

I understand that this could be my own preference so perhaps this could be configured somehow with an option either in global config or at the field level.

**Comment by ncphillips** [comment]
I agree 💯

FWIW the editor will use backticks if there’s a language included

\```javascript

Also you can also add a language using th wysiwygs by typing the above line and pressing space.

But yeah, I’d rather it just always use the backtick syntax
