### ISSUE TITLE
WYSIWYM: optional 'y-offset' for sticky menu

### ISSUE THREAD

**Issue by PaulBunker** [tinacms/tinacms#796]
## Summary

As a website maintainer I would like to control the point at which the wysiwym menubar becomes 'sticky' so that I can make my website look good

### Basic example

![Feb-23-2020 13-57-41](https://user-images.githubusercontent.com/1537408/75112521-e6502b80-5644-11ea-89a4-1772e81fafb1.gif)

### Motivation

I have a sticky header on my site and I'd like to have the menu stick below it.

**Comment by ncphillips** [comment]
@spbyrne Could be implemented using the current sticky prop:

`<Wysisig sticky=“32px” />

**Comment by spbyrne** [comment]
This is implemented and available in the latest release. You set the offset like so:
```
<Wysiwyg sticky={'72px'} input={input} />
```
