### ISSUE TITLE
This is a fantastic project -- keep it going!

### ISSUE THREAD

**Issue by chaddjohnson** [tinacms/tinacms#797]
Hi guys! This is not an issue -- just an encouragement.

Having built content management systems professionally and worked in the industry for 20 years, I'd like to say, you all are building something really great. It truly is a next-gen way of managing websites.

Keep this project going -- it's the best thing out there that I've ever seen for managing content-focused websites in 20 years. The UX concepts are awesome. The code and documentation are excellent as well. Nice work.

And thank you for making it open source.

**Comment by scottgallant** [comment]
@chaddjohnson thank you for the kind words 🙏. This warms Tina's ❤️. 

Lots of cool stuff to come, we're just getting started :D
