### ISSUE TITLE
Error when deleting a code block

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#814]
## Description

I tried to delete the content of a code block and then 💥 

### Steps to reproduce

1. edit a post on gatsby-demo, 
2. create or edit a code block, 
3. remove content with backspace until your browser freezes and dumps a stack trace… 💩  

### Expected result

Don't blow in my face when I edit content, let me delete a code block.

### Actual result

```js
←→1 of 2 errors on the page
RangeError: Selection passed to setSelection must point at the current document
setSelection
node_modules/prosemirror-state/dist/index.es.js:555
  552 | // selection that the editor gets when the transaction is applied.
  553 | Transaction.prototype.setSelection = function setSelection (selection) {
  554 |   if (selection.$from.doc != this.doc)
> 555 |     { throw new RangeError("Selection passed to setSelection must point at the current document") }
      | ^  556 |   this.curSelection = selection;
  557 |   this.curSelectionFor = this.steps.length;
  558 |   this.updated = (this.updated | UPDATED_SEL) & ~UPDATED_MARKS;
```

![Capture d’écran 2020-02-25 à 23 19 01](https://user-images.githubusercontent.com/103008/75293475-86b17600-5826-11ea-8d0c-92bb3b1edcbc.png)

#### Tinacms Package Versions

current `master`.

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |   latest Safari      |
| os      |    latest macOS    |
| node    |    12.6.1     |
| npm     |     6.13.4    |

**Comment by ncphillips** [comment]
@all-contributors please add @DirtyF for bugs
