### ISSUE TITLE
Field - Select

### ISSUE THREAD

**Issue by scottgallant** [tinacms/tinacms#82]

**Comment by kendallstrautman** [comment]
I can try to look into this @ncphillips, want to give me the rundown on what's going on?

**Comment by ncphillips** [comment]
I don’t think it’s worth trying to figure out the issues with `react-select`. 

First, we shouldn't add another styling library to Tina. 

Second, it’s a bit overkill for the basic functionality we want to provide anyway. 

I’m leaning toward either:

1. making a dead simple select field from scratch or
2. finding a simple one that uses `styled-components` already

In either case, if someone wants the more complex behaviour that could be created as a separate plugin

**Comment by kendallstrautman** [comment]
@spbyrne - could you link to the one you found here?

**Comment by spbyrne** [comment]
[React Styled Select](https://github.com/agutoli/react-styled-select) seems promising.

**Comment by kendallstrautman** [comment]
[RC Select](https://github.com/react-component/select) might be worth looking into also

**Comment by ncphillips** [comment]
RC Select uses imported css files. IIRC @jamespohalloran had issues with that

**Comment by smashercosmo** [comment]
Why not https://github.com/downshift-js/downshift?

**Comment by ncphillips** [comment]
Interesting! Do you know what it uses for styling?

**Comment by smashercosmo** [comment]
Nothing. It's 'headless' select component. You can style it whichever way you want.

**Comment by ncphillips** [comment]
Definitely worth checking out 👌

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by weibenfalk** [comment]
Hey ... I have created a PR on this one (Created a select Field #547). The branch is weiben#82 

I've created a standard controlled select element. Haven't styled it yet though. Want to see if you want to use it first. =) 

Merry Christmas to you all!

**Comment by ncphillips** [comment]
Closed by #563

**Comment by jarodpeachey** [comment]
@ncphillips Is there a timeline for when the Select field will be available?

**Comment by ncphillips** [comment]
Select field is currently available!

Thank you for reminding me that it’s not documented! 😱

**Comment by jarodpeachey** [comment]
No problem! Thanks for letting me know.

**Comment by ncphillips** [comment]
@kendallstrautman has some docs on the way 👍

**Comment by kendallstrautman** [comment]
@jarodpeachey - [the docs](https://tinacms.org/docs/fields/select)!
