### ISSUE TITLE
TinaCMS Alerts API

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#821]
## Summary

Visual alerts on the success or failure of actions is important for a variety of cases. TinaCMS would benefit greatly from a consistent API for creating alerts.

- [x] Finalize API

**The details of this API are not final. Feel free to add any comments or concerns.**

**Any changes will be added to to this document. You can view the edit history to gain more context.**
### Examples

**Four Types of Alerts**
```ts
cms.alerts.info("Quebec is a province in Canada.")    // Gray
cms.alerts.error("You can't use cheddar in poutine!") // Red
cms.alerts.warn("We'd prefer you speak French")       // Yellow
cms.alerts.success("La séparation est finie !")         // Green
```

**Default**

By default, alerts will be visible for 2000 ms.

```ts
cms.alerts.success("La séparation est finie !")
```

**Timeout**

A `number` can be passed as the second argument to indicate how long the
alert should be visible. 

```ts
cms.alerts.success("La séparation est finie !", 5000)
```

**Manual Close**

Alternatively, a falsy value can be passed as the second argument to indicate that 
the alert should be visible until the user dismisses.

```ts
cms.alerts.warn("We'd prefer you speak French", 0)
cms.alerts.warn("We'd prefer you speak French", false)
cms.alerts.warn("We'd prefer you speak French", null)
```

**Programmatic Close**

The alert functions return a callback that will dismiss the alert.

```ts
const closeAlert = cms.alerts.info("Quebec is a province in Canada.", false)   

waitForQuebecToSeparate()
  .then(() => closeAlert())
  .then(() => cms.alerts.success("La séparation est finie i!"))
```

**Interfaces**
```ts
interface Alerts {
  info(message: string, until?: number): () => void
  error(message: string, until?: number): () => void
  warn(message: string, until?: number): () => void
  success(message: string, until?: number): () => void
}
```

### Motivation

Use cases this supports:

- Success/Failure when saving forms
- Success/Failure when creating PR

### Related Issues

- #600

**Comment by dwalkr** [comment]
1. Would "notification" be a better name than "alert"? The difference isn't huge but I think of how `alert()` in javascript blocks the main thread and always requires user action to dismiss

2. Not sure if this is any better but dismissing alerts made me think of the timeout API:

```javascript
const timeout = setTimeout(func, ms)
clearTimeout(timeout)
```

possible usage:

```javascript
const alert = cms.alerts.info(message, true)
cms.alerts.dismiss(alert)
```

**Comment by dwalkr** [comment]
more thoughts:

The dual-typing on `until` is a bad smell for me. To me, passing in 0ms is a familiar enough convention for "indefinitely". Beyond that, remembering which is which between true and false could be annoying.

In this case we would lose the ability to make notifications that can't be dismissed by the user. But is that a bad thing? Maybe we shouldn't have notifications that the user can't get rid of.

**Comment by ncphillips** [comment]
**Notifications vs Alerts**

I sort of agree. I was thinking of "notifications" at first, but the difference in UI/UX made me pause.

I was thinking a "notification" API might be for information you want more of a record of. Forestry has Notifications and alerts/popups/toasts/whatever. Notifications are for things like "build failed" and "Bob update a file", while alerts are for things like "save success" and "connection issues".

They both notify the users about things but the UI/UX around them is quite different.

**cms.alerts.dismiss(alert)**

That's kind of cool. I was comparing it more to the `Observable` pattern:

```ts
const unsubscribe = fetchData().subscribe()

unsubscribe()
```

**Dual-typing `until`**

Yeah I don't love that. There's sort of two different concepts: 

- timeout
- dismissable

```ts
// Manual close
cms.alerts.info("Hello World", 0)

// Programmatic
let close = cms.alerts.info("Hello World", 0, false)
close()

// Timeout + No Dismiss
cms.alerts.info("Hello World", 1000, false)
```

**Comment by dwalkr** [comment]
I see the use for programmatically closing alerts, and all alerts could return a close function regardless of timeout to allow them to be closed programmatically

I don't see a use for alerts that can _only_ be closed programmatically, feels a little bit user-hostile. That part depends a little bit on UI though, if these are e.g. toast notifications that clutter the screen, user should always have control over those

**Comment by ncphillips** [comment]
The idea for only closed programmatically is for things like network connectivity issues. i.e. "You're not connected to the internet so you won't be able to save your work

**Comment by dwalkr** [comment]
alerts seems like the wrong solution for that. I'd rather see than in some persistent UI element (toolbar/statusbar)

**Comment by ncphillips** [comment]
Hmm possibly. I would be down with simplifying the API as you suggested.

Second argument only accepts a `number`  and treat `0` is indefinite

**Comment by dwalkr** [comment]
I'm assuming alert UI will be somewhat obtrusive. It should be, presumably alerts will demand your attention! But in that case they should _always_ be user-dismissible. Things that need to be communicated continuously (and not dismissed) should be in a less-obtrusive UI element

**Comment by dwalkr** [comment]
What can we put in alerts? Will it only be text? Would we want some sort of call to action there?

"You're not logged in" -> CTA to open login prompt

"This PR has been closed and cannot accept any more commits" -> CTA to open settings

Maybe we could start w/ strings and address this lateR?

**Comment by ncphillips** [comment]
Delaying was my thought as well. The most pressing use-case is just the Save Response information for forms and other actions. There's been a lot of pressure for that, but little for any kind of CTA usecase.
