### ISSUE TITLE
Warning: React does not recognize the `tinaForm` prop on a DOM element

### ISSUE THREAD

**Issue by chaddjohnson** [tinacms/tinacms#827]
## Description

When using TinaCMS with either Gatsby or Next.js, I am seeing the following error:

<img width="893" alt="Screen Shot 2020-02-29 at 3 15 42 PM" src="https://user-images.githubusercontent.com/676134/75614415-7ccd9280-5b06-11ea-8546-9830ff6072b6.png">

### Steps to reproduce

I followed both the Gatsby and Next.js tutorials.

### Expected result

No error should occur.

### Actual result

The error occurred, though things seem to work fine still. The error seems to be more of a warning.

#### Tinacms Package Versions

```text
├─┬ @tinacms/api-git@0.5.6
├── @tinacms/git-client@0.4.2
├─┬ next-tinacms-markdown@0.2.3
├─┬ tinacms@0.14.0
│ ├── @tinacms/core@0.7.1
│ ├─┬ @tinacms/fields@0.5.1
│ ├─┬ @tinacms/form-builder@0.2.15
│ ├─┬ @tinacms/forms@0.2.0
│ ├── @tinacms/icons@0.5.2
│ ├─┬ @tinacms/react-core@0.2.7
│ ├── @tinacms/styles@0.1.2
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Chrome 79.0.3945.130 (Official Build) (64-bit) |
| os      | macOS Version 10.15.1 (Build 19B88 |
| node    | 12.14.1 |
| npm     | 6.13.4 |
| yarn     | 1.21.1 |

**Comment by ncphillips** [comment]
@all-contributors please add @chaddjohnson for bugs

**Comment by chaddjohnson** [comment]
@ncphillips Thanks! Nice of you.

**Comment by kendallstrautman** [comment]
Reproducable on the `demo-next` index page.

**Comment by kendallstrautman** [comment]
The issue is the `tinaForm` prop in the[ fields builder](https://github.com/tinacms/tinacms/blob/master/packages/%40tinacms/form-builder/src/fields-builder.tsx#L89-L106). If we change `tinaForm` to `tinaform`, the warning goes away but I'd have to look further into where else we would need to make changes if we refactored this prop name.
