### ISSUE TITLE
Use hook `useProsemirror` to get latest update on editorView

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#861]
I should be able to use hook `useProsemirror` to get latest update on editorView anywhere in editor code.

This will save from passing `EditorView` to different menu components.

**Comment by ncphillips** [comment]
That's a good idea! I might rephrase this issue to "Add ProsemirrorContext to Wyswyg". We'll need 3 pieces:

1. `useProsemirror` creates the prosemirror editor
2. `ProsemirrorContext.Provider` will wrap the wysywg & menu
3. `useContext(ProsemirrorContext)` for access
