### ISSUE TITLE
Re-arrange wysiwym code

### ISSUE THREAD

**Issue by jpuri** [tinacms/tinacms#862]
Re-organise folder structure for wysiwym to make it more meaningful.

**Comment by DirtyF** [comment]
What do you suggest?

**Comment by jpuri** [comment]
To start with I want to re-organise files and folders, to a structure like this:

```
- schema
   -- nodes
   -- marks
- components
   -- menu and related components
- plugins
   -- image
       -- prosemirror-plugin
       -- nodeView
       -- editingModal
   -- table
       -- prosemirror-plugin
       -- nodeView
       -- editingModal
   -- link
       -- prosemirror-plugin
       -- nodeView
       -- editingModal
   -- code-block
       -- prosemirror-plugin
       -- nodeView
       -- editingModal
....
```

**Comment by jpuri** [comment]
New folder structure I would propose:

```
- context
    - editorState.tsx
- components
    - Editor
       - index..tsx
       - styles
           - CodeMirror.tsx
           - ProseMirror.tsx
    - Menu
    - InlineMenu
- plugins
    - block
    - inline
    - image
    - link
    - common
    - table
- schema
    - nodes
    - marks
    - index.ts
- Translator
```

**Comment by jpuri** [comment]
Hey @ncphillips : Above is details of new folder structure I would propose.

On high level intent is we have folders for `prosemirror schema`, `react components`, `context`, etc.

Each prosemirror feature like `table`, `image`, `inline styles`, `lists`... will be a folder in plugin. It will club its related prosemirror plugin, menu components, commands, etc.

This will make architecture pluggable, adding removing any of these plugins will add remove the feature. We can go ahead to dynamically add plugins to editor like schema.

**Comment by ncphillips** [comment]
Looks good to me!
