### ISSUE TITLE
Gatsby - Image Upload unresponsive

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#863]
## Description

 Right now in `demo-gatsby`, if you try to update a thumbnail on a blog post, you'll see that the file is uploaded to the correct directory, but the new frontmatter value is not written to the source file. This has be reproduced outside the monorepo aswell in Grande and Brevifolia. Haven't yet tested with Next.js

### Steps to reproduce

Go into `demo-gatsby` and try to update a thumbnail on a blog post.

### Expected result

The frontmatter value for the image should be updated with the return value from the `parse` function defined on the field config.

### Actual result

No changes to the source file occur at all.

#### Tinacms Package Versions

```text
├─┬ gatsby-plugin-tinacms@0.1.27
│ └─┬ tinacms@0.16.0
│   ├── @tinacms/core@0.7.2
│   ├─┬ @tinacms/fields@0.7.0
│   ├─┬ @tinacms/form-builder@0.2.16
│   ├─┬ @tinacms/forms@0.2.1
│   ├── @tinacms/icons@0.7.0
│   ├─┬ @tinacms/react-core@0.2.8
│   ├── @tinacms/styles@0.3.0
├─┬ gatsby-tinacms-git@0.4.0
│ ├─┬ @tinacms/api-git@0.7.0
│ └── @tinacms/git-client@0.6.0
├─┬ gatsby-tinacms-json@0.8.11
├─┬ gatsby-tinacms-remark@0.7.6
```

**Comment by aratner** [comment]
Got this console error when uploading a new image in the sidebar
![Screen Shot 2020-03-09 at 6 23 14 PM](https://user-images.githubusercontent.com/47365929/76264604-ad18dd80-6238-11ea-8682-5a14617c33e1.png)

**Comment by kendallstrautman** [comment]
This is due to the image upload failing silently. Steps to get this working again include configuring the git plugin like so: 
```js
         {
            resolve: "gatsby-tinacms-git",
            options: {
              pathToRepo: process.cwd(),
              pathToContent: "",
              defaultCommitMessage: "chore: update from tina",
              defaultCommitName: "TinaCMS",
              defaultCommitEmail: "git@tinacms.org",
              pushOnCommit: false,
            },
          },
```
I think the `pathToRepo` and `pathToContent` values are particularly important since the `git-router` was recently updated to need this info. Also make sure all required peer dependencies are installed!

**Comment by kendallstrautman** [comment]
Note that we should fix it so that this failure to upload the image throws a better error

**Comment by kendallstrautman** [comment]
This may be related to #918
