### ISSUE TITLE
Error when using Tina with Gatsby: Cannot query field "products" on type "MarkdownRemarkFrontmatter".

### ISSUE THREAD

**Issue by chaddjohnson** [tinacms/tinacms#864]
## Description

I really love and believe in TinaCMS, but this issue is preventing me from using it.

When using TinaCMS with Gatsby, I constantly see the following error when simply typing in a text field after a few seconds:

<img width="823" alt="Screen Shot 2020-03-10 at 12 18 58 PM" src="https://user-images.githubusercontent.com/676134/76334590-a1292c00-62c9-11ea-8184-465f1dfd3d6f.png">

It is followed immediately by this error:

<img width="822" alt="Screen Shot 2020-03-10 at 12 19 00 PM" src="https://user-images.githubusercontent.com/676134/76334598-a6867680-62c9-11ea-87a6-321bd51b3bca.png">

I have to refresh the page to keep using Tina. This makes Tina unusable.

I have tried and tried but cannot get past this, and I have no leads as far as the cause. I’ve never seen this error occur when using just Gatsby by itself — only when using TinaCMS with Gatsby.

I even tried defining a schema but ran into technical issues related to Gatsby. Again, this isn’t necessary with straight Gatsby — only when Tina is in the picture.

Have you all seen this error, and do you all have any ideas what might be wrong?

### Steps to reproduce

Simply type in a text field. It seems to happen if I type too quickly. It's as if Tina or Gatsby isn't able to keep up -- as if there are overlapping re-builds happening or something. The error does not happen if I type slowly (enter one character at a time and wait one second between each keypress).

Here is [a demo project](https://github.com/chaddjohnson/tinacms-bug-864) where the issue is present.

### Expected result

No error should occur.

### Actual result

The error occurred.

#### Tinacms Package Versions

```text
├─┬ @tinacms/api-git@0.5.6
├── @tinacms/git-client@0.4.2
├─┬ next-tinacms-markdown@0.2.3
├─┬ tinacms@0.14.0
│ ├── @tinacms/core@0.7.1
│ ├─┬ @tinacms/fields@0.5.1
│ ├─┬ @tinacms/form-builder@0.2.15
│ ├─┬ @tinacms/forms@0.2.0
│ ├── @tinacms/icons@0.5.2
│ ├─┬ @tinacms/react-core@0.2.7
│ ├── @tinacms/styles@0.1.2
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser | Chrome 79.0.3945.130 (Official Build) (64-bit) |
| os      | macOS Version 10.15.1 (Build 19B88 |
| node    | 12.14.1 |
| npm     | 6.13.4 |
| yarn     | 1.21.1 |

**Comment by DirtyF** [comment]
Hey chad, did you try to pass `TINA_GIT_DEBOUNCE_MS` env variable and set it higher than 1000?

See: https://github.com/tinacms/tinacms/commit/3117eb48c48444648aa7a6e622d74eaf19244167

**Comment by ncphillips** [comment]
This is a painful issue, as far as I can tell `gatsby` doesn't send data for queries when it's rebuilding...sometimes. I think @dwalkr dug into it a bit more?

Frank's right though, that flag might help. [Here's the doc](https://tinacms.org/docs/gatsby/configure-git-plugin#configuring-the-file-writing-debounce)

**Comment by chaddjohnson** [comment]
Setting TINA_GIT_DEBOUNCE_MS to 5000 seems to help! I changed the `develop` npm script to `TINA_GIT_DEBOUNCE_MS=5000 gatsby develop`.

I'll post here if this issue crops up again.

Thanks @DirtyF and @ncphillips .
