### ISSUE TITLE
WYSIWYM Image upload

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tinacms#866]
Now that Tina offers a media store, we can start working on managing images in the Markdown editor.

The first step is to allow people to add one media at a time in the editor.

Given I'm using the WYSIWTM editor
When I click on media button
Then I can add an image in the editor

**Comment by jpuri** [comment]
Hey @DirtyF : this one looks like duplicate: https://github.com/tinacms/tinacms/issues/166

**Comment by DirtyF** [comment]
Duplicate of #166
