### ISSUE TITLE
New Tab Option

### ISSUE THREAD

**Issue by pxwee5** [tinacms/tinacms#876]
## Summary

![image](https://user-images.githubusercontent.com/14123790/76478267-f6ea0980-646c-11ea-8f3a-cecec6941672.png)

Add a checkbox that says "Open in new window/tab".
This should produce `target="_blank" rel="noopener`.

Brief explanation of the feature.

## Motivation

Some inline links links to external website needs to be opened in a new tab.

**Comment by DirtyF** [comment]
On a related note, some browsers (Firefox, Safari) are now assuming that target blank implies `rel="noopener"` See: https://github.com/whatwg/html/pull/4330

**Comment by ncphillips** [comment]
I think this is a feature that could only be available when editing `html` 

Unfortunately CommonMark does not support setting those two properties. If the markdown parser of choice allows this feature, maybe a tinacms:wysiwyg plugin could add that behaviour

**Comment by DirtyF** [comment]
maybe with https://github.com/arobase-che/remark-attr (similar to https://www.npmjs.com/package/markdown-it-attrs)

**Comment by Raven0us** [comment]
If anyone still needs this.

You can work around this limitation by passing a component that handles anchor elements to `TinaMarkdown`

Example

```tsx
const settleRichText = (value: TTinaRichText, components: Record<string, object> = {}) => {
    const formattedComponents = {
        ...{
            a: (props?: {
                url: string;
                children: React.JSX.Element;
            }) => {
                const url = props?.url || "#"
                const target = url.startsWith("https://oxentree.com") || url.startsWith("/") ? "_self" : "_blank"
                
                return <Link href={url} target={target}>{props?.children}</Link>
            }
        },
        ...components
    }
    
    
    return <TinaMarkdown components={formattedComponents} content={value} />
}
```
