### ISSUE TITLE
useLocalJsonForm does not automatically create form fields

### ISSUE THREAD

**Issue by marklawlor** [tinacms/tinacms#879]
## Description

From the docs:

```
By default, useLocalJsonForm creates a text field for each value in data. It's possible to customize the form by passing a second argument into useLocalJsonForm:
```

### Steps to reproduce

Use  useLocalJsonForm with a single argument

Eg ` const [data] = useLocalJsonForm(jsonFile);`

### Expected result

The sidebar includes a text field for each key in the jsonFile's daata

### Actual result

No fields are created

#### Tinacms Package Versions
```
├─┬ @tinacms/api-git@0.7.0
├── @tinacms/git-client@0.6.0
├── next-tinacms-json@0.3.5
├─┬ tinacms@0.16.0
│ ├── @tinacms/core@0.7.2
│ ├─┬ @tinacms/fields@0.7.0
│ ├─┬ @tinacms/form-builder@0.2.16
│ ├─┬ @tinacms/forms@0.2.1
│ ├── @tinacms/icons@0.7.0
│ ├─┬ @tinacms/react-core@0.2.8
│ ├── @tinacms/styles@0.3.0
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  Chrome 80       |
| os      |  Ubunutu       |
| node    |  12.x       |
| npm     |   6.13.x      |

**Comment by kendallstrautman** [comment]
I noticed this recently. Thanks for making an issue. If you pass in a form options object as the second argument, the fields will populate.

**Comment by marklawlor** [comment]
Manually creating the custom fields via the second argument appears to be working as expected

**Comment by kendallstrautman** [comment]
Note when we go to fix: this occurs with `useLocalMarkdownForm` as well.

**Comment by kendallstrautman** [comment]
We need to add a `generateFields` function to these helpers
