### ISSUE TITLE
Empty form setup guide should link to more general documentation

### ISSUE THREAD

**Issue by marklawlor** [tinacms/tinacms#881]
## Description

Empty forms on NextJS projects incorrectly link to a Gatsby getting started guide

### Steps to reproduce

Create an empty form and click getting started from the sidebar

### Expected result

It directs you here `https://tinacms.org/docs/nextjs/creating-forms`

### Actual result

It directs you here `https://tinacms.org/docs/gatsby/markdown/#creating-remark-forms`

For users following the NextJS tutorial this is slightly confusing

#### Tinacms Package Versions
Link to offending line `https://github.com/tinacms/tinacms/blob/547723c1d941f827efb8c3459121a99f6bcc2eb8/packages/tinacms/src/components/form/FormView.tsx#L212`

```text
"@tinacms/api-git": "^0.7.0",
"@tinacms/git-client": "^0.6.0",
"next": "^9.3.0",
"next-tinacms-json": "^0.3.5",
"tinacms": "^0.16.0"
"typescript": "^3.8.3"
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |         |
| os      |         |
| node    |         |
| npm     |         |

**Comment by kendallstrautman** [comment]
This should probably link to the more general [Forms docs](https://tinacms.org/docs/forms) page

**Comment by kendallstrautman** [comment]
@marklawlor — if you wanna take a stab at contributing, [this](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/components/form/FormView.tsx#L212) is the file.

**Comment by kendallstrautman** [comment]
Also odd but I thought we already updated this link, somehow it's back to the Gatsby one. See #656
