### ISSUE TITLE
No DeleteAction exposed from gatsby-tinacms-json

### ISSUE THREAD

**Issue by mmintel** [tinacms/tinacms#884]
## Description
Hey there,  according to this article here (https://tinacms.org/blog/add-and-delete-files) there should be an `DeleteAction` exposed by `gatsby-tinacms-json`

> You can import the DeleteAction from gatsby-tinacms-remark or gatsby-tinacms-json, depending on your filetype. Then on your form options definition, add the action and that’s it!

However I am just receiving `undefined` and I also had a look at the source code of this plugin and couldn't see anything related. Probably just forgotten and I am the first who tries to delete json files?

Cheers

### Steps to reproduce
```
import { DeleteAction } from "gatsby-tinacms-json"
```

### Expected result

DeleteAction should be defined and a delete button should be displayed in the sidebar.

### Actual result

DeleteAction is undefined.

App crashes and throws:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `M`.
```

#### Tinacms Package Versions
(provided command doesn't work in my yarn workspace)

```text
"dependencies": {
    "gatsby-plugin-offline": "^3.0.35",
    "gatsby-plugin-sharp": "^2.4.5",
    "gatsby-plugin-tinacms": "^0.1.27",
    "gatsby-remark-copy-linked-files": "^2.1.37",
    "gatsby-remark-images": "^3.1.44",
    "gatsby-remark-prismjs": "^3.3.31",
    "gatsby-remark-responsive-iframe": "^2.2.32",
    "gatsby-remark-smartypants": "^2.1.21",
    "gatsby-source-filesystem": "^2.1.48",
    "gatsby-tinacms-git": "^0.4.0",
    "gatsby-tinacms-json": "^0.8.11",
    "gatsby-tinacms-remark": "^0.7.6",
    "gatsby-transformer-json": "^2.2.26",
    "gatsby-transformer-remark": "^2.6.53",
    "gatsby-transformer-sharp": "^2.3.16",
    "prismjs": "^1.19.0",
    "react-beautiful-dnd": "^13.0.0",
    "slugify": "^1.4.0",
    "styled-components": "^5.0.1"
  }
```

**Comment by ncphillips** [comment]
Good catch! 👍 

I'm thinking it might also make sense to move that into `gatsby-tinacms-git`. Then `gatsby-tinacms-json` could export it and the API would still work the way you described

**Comment by ncphillips** [comment]
@all-contributors please add @mmintel for bugs
