### ISSUE TITLE
Switch simple-git in favour of isomorphic-git to allow deployments without a backend

### ISSUE THREAD

**Issue by marklawlor** [tinacms/tinacms#885]
## Summary

[simple-git](https://www.npmjs.com/package/simple-git) is exactly what is name says - a simple wrapper around the `git` binary. This means that the runtime environment needs the `git` binary. When deploying to production environments, this limits the deployment options and forces the user to have a backend or custom server.

[isomorphic-git](https://isomorphic-git.org/) is a pure Javascript implementation of git that works in both the NodeJS and the browser (with some limitations/workarounds needed). This would allow TinaCMS to work on a static site against a git backend.

### Motivation

**Allow for more "client only" deployments:**

A great example is the TinaCMS website that authenticates against Github. In this scenario there is no need for a backend service, as the frontend is already authenicated and could push directly to the Github repo.

Here is an example where someone has created a client only version of tinacms against firebase https://github.com/ncphillips/demo-tinacms-firebase. This could be replicated with Git

**Allow for more deployment configurations**

In the case of using TinaCMS in production (eg the TinCMS website), it would allow for more deployment options such as Static Site Hostings or Serverless deployments.

**Comment by ncphillips** [comment]
This is a super interesting idea!

I definitely think it is worth exploring, but I wouldn't take the approach of replacing `simple-git` in `@tinacms/api-git` with `isomorphic-git`. Instead I would prefer to create a new package. I'm pretty confident that the set of challenges needed to solve "git in the browser" is quite different than that of on a server. For example, even if we did replace `simple-git` most of the behaviour of `@tinacms/api-git` is implemented using `express` and `fs`. That means even if you did replace, `simple-git` you couldn't use that package in the browser.

But if we explore using `isomorphic-git` in a brand new package then the challenges around building browser-only git api could be solved without worrying about breaking the existing package.

**Comment by marklawlor** [comment]
Hi @ncphillips, 

I agree that maybe the git-in-browser idea should be its own package and probably should have its own issue.

However I would reconsider using isomorphic-git for the backend. Not every deployment environment has access to the `git` binary. For example if I am a NextJS user, Zeit heavily push their own deployment platform now.sh which does not provide access to the git binary. I'm assuming the same is true for other deployment platforms such as netify. 

I am currently experimenting with TinaCMS and this issue has forced me to change to a different deployment provider (AWS Lambda with a prepackaged git layer https://github.com/lambci/git-lambda-layer).

**Comment by dangayle** [comment]
I would really love to be able to use this with Now. We're so close to being able to set up websites for clients that have no server overhead to deal with, TinaCMS is really a great step in that direction, in conjunction with services like Now.

**Comment by dangayle** [comment]
> I definitely think it is worth exploring, but I wouldn't take the approach of replacing `simple-git` in `@tinacms/api-git` with `isomorphic-git`. Instead I would prefer to create a new package. 
> 
> But if we explore using `isomorphic-git` in a brand new package then the challenges around building browser-only git api could be solved without worrying about breaking the existing package.

That makes perfect sense.

**Comment by ncphillips** [comment]
> I would really love to be able to use this with Now. We're so close to being able to set up websites for clients that have no server overhead to deal with, TinaCMS is really a great step in that direction, in conjunction with services like Now.

I think the `react-tinacms-github` project is really your best bet on this front. That's what we use on tinacms.org.

The setup guide is underway and will be available soon, [you can check it out here](https://tinacms-site-next-git-next-git-guide.tinacms.now.sh/guides/nextjs/github-open-authoring/initial-setup) though!

**Comment by dangayle** [comment]
@ncphillips Whoa, that is cool. Thanks for the heads up!

**Comment by ncphillips** [comment]
@dangayle if you give it a go feel free to comment on the PR with any feedback! 😄
