### ISSUE TITLE
Prop on <Tina> context provider to completely disable TinaCMS 

### ISSUE THREAD

**Issue by marklawlor** [tinacms/tinacms#887]
## Summary

The TinaCMS Context Provider should have a prop to completely disable **all** functionality (eg all network requests), not just hide the sidebar. While hiding the sidebar does stop editing of TinaCMS, it still sends unnessary network requests for data.

### Basic example

In this example UserProvider is a custom context provider which let me knows if a user is authenicated to provide edits to the website.

```
    return (
      <UserProvider>
        {({ isAuthenicated }) => (
          <Tina cms={this.cms} disabled={!isAuthenicated}>
            <Component {...pageProps} />
          </Tina>
        )}
      </UserProvider>
    );
```
### Motivation

**My use case**

I understand that disabling network requests will cause the website not to display the latest changes until the website is rebuild either via Gatsby or NextJS.  This is the exact functionality I want.

For my use-case:

Non-authenicated users should always only see a controlled compiled version of the website and never have access to Tina editing functionality or see edits applied by other users

When an authenicated user makes an edit, my backend automatically creates a branch where all edits are applied and that user will see their own version of the website.

Since 99.99% of site visitors users are unauthenicated, TinaCMS sending these network requests (which will always error) creates unnessarry network overhead.

**Comment by kendallstrautman** [comment]
Implemented via #1170
