### ISSUE TITLE
feat: File Field Plugin 

### ISSUE THREAD

**Issue by ncphillips** [tinacms/tinacms#891]
## Summary

A basic `"file"` field should be supplied.

### Basic example

```js
{ 
  name: "frontmatter.pdf",
  label: "PDF",
  component: "file"
}
```
### Motivation

Currently there is an `"image"` upload but it is specifically for uploading images.

**Comment by mmintel** [comment]
tinacms-fields has you covered: https://github.com/mmintel/tinacms-fields/tree/master/packages/tinacms-file-field
