### ISSUE TITLE
Sidebar: Markdown toolbar z-index above color picker

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#906]
## Description

The Markdown Toolbar z-index is set super high, which is good unless you have another 'popup' type field that is active and _should_ sit above it. See image. 

<img width="385" alt="Screen Shot 2020-03-13 at 11 56 29 AM" src="https://user-images.githubusercontent.com/36613477/76899012-68a2c880-685c-11ea-995c-9540469b5554.png">

### Steps to reproduce

Add a color field next to a markdown field in the sidebar. Open the color picker. Observable on the info page of [brevifolia-next-tinacms](https://github.com/kendallstrautman/brevifolia-next-tinacms)

### Expected result

The color picker, or whatever 'popup' field that is active should be on top. 

### Actual result

The markdown toolbar remains on top no matter what.

#### Tinacms Package Versions

```text
├─┬ @tinacms/api-git@0.7.0
├── @tinacms/git-client@0.6.0
├── next-tinacms-json@0.3.5
├─┬ next-tinacms-markdown@0.2.5
├─┬ tinacms@0.16.0
│ ├── @tinacms/core@0.7.2
│ ├─┬ @tinacms/fields@0.7.0
│ ├─┬ @tinacms/form-builder@0.2.16
│ ├─┬ @tinacms/forms@0.2.1
│ ├── @tinacms/icons@0.7.0
│ ├─┬ @tinacms/react-core@0.2.8
│ ├── @tinacms/styles@0.3.0
```

**Comment by blaggacao** [comment]
Same for link popup on HTMl fields, see #930 for an analogous report.
