### ISSUE TITLE
(partly) infer CmsFormOptions from PropertyTypes

### ISSUE THREAD

**Issue by blaggacao** [tinacms/tinacms#909]
## Summary

The form config passed as second argument to eg. `useLocalJsonForm` carries information about the shape of the underlying datastructure. Part of this information is also present in the `propTypes` attribute of the react component (if set). Therefore, overload (somhow, how?) the `propTypes` attribute to fill in the missing information.

### Basic example

Now:
```jsx
Component.propTypes = {
  content: PropTypes.shape({
    sector: PropTypes.string.isRequired,
    ...
  }).isRequired,
}
```
After implementing this feature (tentative syntax):
```jsx
const tinaTypedContent = {
    sector: TinaPropTypes.string(..., description="foo", component="textarea").isRequired,
    ...
}

Component.propTypes = {
  content: PropTypes.shape(tinaTypedContent).isRequired,
}
```

- `[]` shape would map to a Group List field
- `{}` shape would map to a Group field

### Motivation

Deduplication. Maintainability.

**Comment by ncphillips** [comment]
Hey @blaggacao, let me see if I understand your thought.

Are you looking to generate the `propTypes` of a component based on the `fields` array that is passed to the forms?

i.e.

```js
const fields = [
  { name: "title", component: "text" },
  { 
    name: "author",
    component: "group",
    fields: [
      { name: "name", component: "text" },
      { name: "twitter", component: "text" },
    ]
]

function BlogPost(props) {
  const [post] = useLocalJsonForm(props.post, { fields })
}

BlogPost.propTypes = {
  post: getPropTypesFromFields(fields)
}
```

**Comment by blaggacao** [comment]
I'd say since `PropTypes` is the more generic of the two (`PropTypes` and `TinaCMS`), for the sake of making it easy to adopt Tina, It should be the other way round: Tina to infer from (potentially previously existing `PropTypes`) through a thin `PropTypes` wrapper:

Taking your exact example:

```js
import { TinaPropTypes } from tinacms
import PropTypes from prop-types  // Could also be entirely replaced by the tina cms drop-in wrapper

function BlogPost(props) {
  const [post] = useLocalJsonForm(props.post)  // hook inspects the object for a e.g. `__tinaFormOptions` attribute construed by the wrapper

  return <>{/* ... */}</>
}

BlogPost.propTypes = {
  post: PropTypes.shape({
    title: TinaPropTypes.string(component="text").isRequired,
    author: TinaPropTypes.arrayOf(
      TinaPropTypes.shape({
        name: TinaPropTypes.string(component="text"),
        twitter: TinaPropTypes.string(component="text"),
      })
    )
  })
}
```

Having PropTypes already declared, I could make a basic functioning form with complex types by just doing `sed -i '/PropTypes/TinaPropTypes/g' `
