### ISSUE TITLE
error Couldn't find package "@tinacms/media@^0.1.0"

### ISSUE THREAD

**Issue by hugominas** [tinacms/tinacms#921]
## Description

Hi, tried bumping up the tinacms version and noticed a dependency error with media@^0.1.0. 
I wasn't sure this was something to do with my dependencies so I cloned the main repo and tried installing, the same  error happened:

error Couldn't find package "@tinacms/media@^0.1.0" required by "tinacms@^0.18.0" on the "npm" registry.

### Steps to reproduce

Clone and install this package https://github.com/tinacms/tinacms/tree/master/packages/gatsby-tinacms-git

### Expected result

clean install without fatal error

### Actual result

Instalation stopped 
error Couldn't find package "@tinacms/media@^0.1.0" required by "tinacms@^0.18.0" on the "npm" registry.

### Environment

MacOS nvm 10.13 or Docker nodejs 10.13 base image

#### Tinacms Package Versions

packages from the repo

**Comment by ncphillips** [comment]
Thanks for the heads up @hugominas, missed that one. I just made it public can you try again?

**Comment by hugominas** [comment]
It works as expected, thanks @ncphillips
