### ISSUE TITLE
Warning (@tinacms/styles): Inter font should not be imported via CreateGlobalStyle

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#926]
## Description

This warning when developing:

> Please do not use @import CSS syntax in createGlobalStyle at this time, as the CSSOM APIs we use in production do not handle it well. Instead, we recommend using a library such as react-helmet to inject a typical <link> meta tag to the stylesheet, or simply embedding it manually in your index.html <head> section for a simpler app.

### Steps to reproduce

Go to `demo-next`, kick up development mode and you'll see this warning in the console.

### Expected result

No warning, and the font still imports properly.

### Actual result

The warning displayed, but it didn't seem to affect the font.

#### Tinacms Package Versions

```text
├─┬ @tinacms/api-git@0.7.0
├─┬ @tinacms/form-builder@0.3.0
│ ├─┬ @tinacms/forms@0.3.0
│ ├─┬ @tinacms/react-core@0.2.9
│ │ └─┬ @tinacms/forms@0.3.0
├── @tinacms/git-client@0.6.2
├── @tinacms/styles@0.4.0
├── next-tinacms-json@0.3.7
├─┬ react-tinacms@0.9.15
├─┬ react-tinacms-editor@0.2.0
│ ├── @tinacms/core@0.7.3
│ ├── @tinacms/icons@0.7.0
├── react-tinacms-inline@0.4.0
├─┬ tinacms@0.18.0
│ ├── @tinacms/alerts@0.1.0
│ ├─┬ @tinacms/fields@0.7.0
│ │ ├── @tinacms/styles@0.3.0
│ ├─┬ @tinacms/form-builder@0.2.16
│ ├─┬ @tinacms/forms@0.2.1
│ ├── @tinacms/media@0.1.0
│ ├── @tinacms/react-alerts@0.1.0
│ ├── @tinacms/react-modals@0.1.0
```

**Comment by spbyrne** [comment]
I'd like to hear suggestions for how we should best load fonts. Should it happen only on-demand when Tina is opened? I'm not sure what the best approach is but I know this needs corrected.

**Comment by kendallstrautman** [comment]
Ideally, global styles and the reset would go in some sort of `head` element. Maybe we use react-helmet for this? I'm not sure the best way either, we'll have to do some digging
