### ISSUE TITLE
CSS in sidebar - can't import css within the sidebar

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tinacms#93]
Css cannot be imported within the sidebar code. I tried adding [rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss) to the build process, but the styles are added in the main document's head (outside of the iframe).

With rollup-plugin-postcss, you can specify `extract: false`, so maybe the sidebar can include the built css files within the iframe's head?

Added rollup-plugin-postcss here: https://github.com/tinacms/tinacms/pull/94

**Comment by spbyrne** [comment]
@jamespohalloran Is this still relevant?

**Comment by ncphillips** [comment]
It's not relevant, and maybe even fixed. I assume this was because of the sidebar being in an iframe.
