### ISSUE TITLE
tinacms: GlobalStyles only available when sidebar is visible

### ISSUE THREAD

**Issue by kendallstrautman** [tinacms/tinacms#941]
## Description

Right now, the `GlobalStyles` and `TinaReset` only render if [the sidebar is not hidden](https://github.com/tinacms/tinacms/blob/master/packages/tinacms/src/components/TinaProvider.tsx#L57). That's an issue now with Inline Editing if we want to hide the sidebar, but also access the `GlobalStyles` that are needed for `BlockControls` and other ui components.

### Steps to reproduce

Go to `demo-next`, set `sidebar.hidden = true`, then toggle inline editing mode. You will see how the `BlocksControls` do not inherit the proper styles, because the css-variables they are calling don't exist.

### Expected result

I would expect that even if the sidebar were hidden, I would still have access to `GlobalStyles`.

### Actual result

If the sidebar is hidden, the inline UI does not render properly since those variables are missing.

### Potential Solutions

We may need to add another flag for 'toolbar' or 'inline-ui' to have a finer-grained control whether you want to use the sidebar or newer inline-only approach. Open to other approaches?

#### Tinacms Package Versions

```text
├─┬ @tinacms/api-git@0.7.0
├─┬ @tinacms/form-builder@0.3.0
│ ├─┬ @tinacms/forms@0.3.0
│ ├─┬ @tinacms/react-core@0.2.9
│ │ └─┬ @tinacms/forms@0.3.0
├── @tinacms/git-client@0.6.2
├── @tinacms/styles@0.4.0
├── next-tinacms-json@0.3.7
├─┬ react-tinacms@0.9.15
├─┬ react-tinacms-editor@0.2.0
│ ├── @tinacms/core@0.7.3
│ ├── @tinacms/icons@0.7.0
├── react-tinacms-inline@0.4.0
├─┬ tinacms@0.18.0
│ ├── @tinacms/alerts@0.1.0
│ ├─┬ @tinacms/fields@0.7.0
│ │ ├── @tinacms/styles@0.3.0
│ ├─┬ @tinacms/form-builder@0.2.16
│ ├─┬ @tinacms/forms@0.2.1
│ ├── @tinacms/media@0.1.0
│ ├── @tinacms/react-alerts@0.1.0
│ ├── @tinacms/react-modals@0.1.0
```

**Comment by ncphillips** [comment]
I'm planning on doing some pretty heavy refactoring of the `TinaProvider` in preparation for the Toolbar. I'm hoping that it will eventually go from this:
```tsx
    <CMSContext.Provider value={cms}>
      <SiteWrapper
        open={cms.sidebar.isOpen}
        position={position || cms.sidebar.position}
      >
        {children}
      </SiteWrapper>
      {!cms.sidebar.hidden && (
        <>
          <GlobalStyles />
          <TinaReset>
            <ModalProvider>
              <Alerts alerts={cms.alerts} />
              <Sidebar />
            </ModalProvider>
          </TinaReset>
        </>
      )}
    </CMSContext.Provider>
```
to this:
``tsx
   <CMSContext.Provider value={cms}>
      <ModalProvider>
        <GlobalStyles />
        <Alerts alerts={cms.alerts} />
        {props.ui === "sidebar" && <Sidebar>{children}</Sidebar>}
        {props.ui === "toolbar" && <Toolbar>{children}</Toolbar>}
      </ModalProvider>
    </CMSContext.Provider>
```
That should fix this issue.

Want to pair on it tomorrow or early next week?

**Comment by kendallstrautman** [comment]
Yeah that looks awesome! I'd love to pair 🤘
