### ISSUE TITLE
CSS Transition: all effects every element on user's site/app

### ISSUE THREAD

**Issue by limitlessloop** [tinacms/tinacms#944]
###  Description

This should be an easy one to improve upon.

Because `transition: all` is applied to the `SiteWrapper` every element inside also inherits this property causing every property on every element, to transition. These include things like font-size. In my scenario, in some cases, it is interfering with my site and causing font sizes to 'jitter' as CSS loads and font-size properties are animated.

### Steps to reproduce

Change the value of any property on any element inside `SiteWrapper`. For example either be using the inspector tool or by toggling a HTML class.

### Expected result

Tina should not interfere with user's styles.

### Actual result

All properties of user's app (inside `SiteWrapper` ) are animated.

This causes some issues/interference even when Tina is not in use as the styles are still applied to the wrapper. Please consider limiting the properties which need to be transitioned like `width` and only applying them when in use for the Tina sidebar.

**Comment by spbyrne** [comment]
I think there's certainly room for improvement here. The `transition` CSS property isn't actually inherited by default, but it's an easy fix to at least set it to `width` for the site wrapper element in case someone happens to be setting `transition-property` to `inherit`.

**Comment by ncphillips** [comment]
@all-contributors please add @limitlessloop for bugs

**Comment by limitlessloop** [comment]
Ah yes, sorry that was my bad in assuming that the cause was because it was inherited by default. It was in fact happening because properties like `font-size` are inherited, and therefore changes to these properties on or inherited by the `SiteWrapper` were also being transitioned.

Thanks for limiting it to width for now. 😄
