### ISSUE TITLE
<div class="SiteWrapper"> included in gatsby build output

### ISSUE THREAD

**Issue by aratner** [tinacms/tinacms#954]
## Description

Is the `<div class="SiteWrapper">` supposed still be there when you `gatsby build` your site? If so, is there a way to remove or customize its css properties? Its `position: absolute` is causing some layout issues for me when my site winds up in its final environment.

#### Tinacms Package Versions
├─┬ gatsby-plugin-tinacms@0.1.31
│ └─┬ tinacms@0.18.2
│   ├── @tinacms/alerts@0.1.0
│   ├── @tinacms/core@0.7.3
│   ├─┬ @tinacms/fields@0.9.1
│   ├─┬ @tinacms/form-builder@0.3.0
│   ├─┬ @tinacms/forms@0.3.0
│   ├── @tinacms/icons@0.7.0
│   ├── @tinacms/media@0.1.0
│   ├── @tinacms/react-alerts@0.1.0
│   ├─┬ @tinacms/react-core@0.2.9
│   ├─┬ @tinacms/react-forms@0.1.0
│   ├── @tinacms/react-modals@0.1.0
│   ├── @tinacms/styles@0.4.0
│   └─┬ react-tinacms-editor@0.3.0
├─┬ gatsby-tinacms-git@0.4.5
│ ├─┬ @tinacms/api-git@0.7.0
│ └── @tinacms/git-client@0.6.4
├─┬ gatsby-tinacms-json@0.8.16
├─┬ gatsby-tinacms-remark@0.7.11

**Comment by spbyrne** [comment]
Thanks @aratner! Currently there's no way to remove this wrapper in production, but I can see how this would be problematic. We're going to discuss a solution for this soon.
